### ISSUE TITLE
There was an error while I was executing the command "cmake --build cmake-build --config Release -- -j" in jetson orin

### ISSUE THREAD

**Issue by lxq-iang** [nanoporetech/dorado#10]
/dorado/dorado/data_loader/DataLoader.cpp:12:10: fatal error: pod5_format/c_api.h: No such file or directory
   12 | #include "pod5_format/c_api.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by lxq-iang** [comment]
make[2]: *** No rule to make target '../dorado/3rdparty/pod5-0.0.14-Linux/lib64/libarrow.a', needed by 'bin/dorado'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:320: CMakeFiles/dorado.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target '../dorado/3rdparty/pod5-0.0.14-Linux/lib64/libarrow.a', needed by 'tests/dorado_tests'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1288: tests/CMakeFiles/dorado_tests.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by vellamike** [comment]
Hi @lxq-iang  - we do not currently support ARM devices, we plan to in future and we will update release notes when this changes.

**Comment by lxq-iang** [comment]
ok, @vellamike thank you for your answer, I look forward to receiving support for ARM devices soon.

**Comment by iiSeymour** [comment]
Orin is now supported and linux-arm64 builds are available.
