### ISSUE TITLE
polyA sequence are not called by dorado

### ISSUE THREAD

**Issue by yul96** [nanoporetech/dorado#100]
It seems dorado won't do basecall for polyA sequence either in the end of RNA or inside a plasmid construct. Is there a plan to include this feature soon?

**Comment by vellamike** [comment]
Hi @yul96 - could you provide some more details? Is Dorado refusing to call the read at all, or giving the wrong sequence for the polyA, or misassigning the length?

**Comment by yul96** [comment]
it just removes the polyA sequence - we don't see the polyA sequences, and see a gap on the alignments. see screenshot
<img width="483" alt="image" src="https://user-images.githubusercontent.com/107077700/220823408-22cba66c-e0cd-416a-bcf7-cecc9223394c.png">

**Comment by chatla01** [comment]
Hi, Any update on this issue. I am using RBK114.24 kit with 10.4.1 Flow cells on gridION with Minknow (Dorado basecaller) with super accurcy and On for modified baseses. The reads are missing polyA tails. Any updates on this? 
![image](https://github.com/nanoporetech/dorado/assets/28633634/1dcdf176-16d5-4230-a11f-ba797093b55e)

**Comment by tijyojwad** [comment]
Hi @chatla01 - we just released dorado [v0.4.3](https://github.com/nanoporetech/dorado#installation) with support for [poly(A) tail length estimation](https://github.com/nanoporetech/dorado#polya-tail-estimation) for cDNA and dRNA. With this feature the basecalls themselves remain unchanged, but dorado can estimate the length of the homopolymer region and save that to the output record.

This may be helpful for your situation. Would be great to get your feedback!

**Comment by dweemx** [comment]
Hi @tijyojwad,

Great new feature! Does the poly(A) estimation also work for DNA samples? If not, are you planning to make this feature also available for DNA samples?

**Comment by tijyojwad** [comment]
Hi @dweemx - works for DNA as well (tuned for cDNA primarily)

**Comment by chatla01** [comment]
Hi @tijyojwad,
I base called the data with dorado-0.4.3-linux-x6 on GridION. The bam files it produced doesn't have pt:i info. Unless I am missing something. 

I am sequencing the plasmid DNA with RBK114.24 kit with 10.4.1 Flow cells, baseclled with Minknow with modified bases on with super accuracy. The basecalled data (fastq_pass) will be feed into wf_clone_validation. I would appreciate if dorado keep the polyA information in fastq files. 

The commands I used for re-basecalling with dorado-0.4.3-linux-x6. 
"bin/dorado basecaller dna_r10.4.1_e8.2_400bps_sup\@v4.2.0 /data/2023nove02_plasmid_run_9/BCMA/20231031_1011_X2_FAX33004_e5c230d7/pod5_pass/barcode23/ --modified-bases 5mC 6mA --device cuda:all -r --estimate-poly-a > run9/Barcode23.bam"
"samtools view Barcode23.bam | grep 'pt' "  This doesn't give anything

Please let me know if I am not doing something wrong?  Thank you.

**Comment by tijyojwad** [comment]
Hi @chatla01 - your cmd looks good to me. If the `pt` tag is not present then dorado wasn't able to estimate the tail length. I'm surprised though that it didn't detect it on any reads. do you have a sense of how long the tails might be in your dataset? E.g. are they expected to be quite short, or can be long too?

Could you run dorado with `-vv` option? That'll output a lot of trace information so you'll want to redirect the stderr to a file. In that please search for polyA, and can you post what you find?

**Comment by chatla01** [comment]
Hi @tijyojwad, 
These are plasmid sequences, all plasmids I am working with have 80 polyAs. Wf_clone_validation recognizing anywhere from 10 to max 35 As. 
I ran the command with -vv option 
`bin/dorado basecaller dna_r10.4.1_e8.2_400bps_sup\@v4.2.0 /data/2023nove02_plasmid_run_9/BCMA/20231031_1011_X2_FAX33004_e5c230d7/pod5_pass/barcode23/ --modified-bases 5mC 6mA --device cuda:all -r --estimate-poly-a -vv > run9/Barcode23_vv.bam 2>errors.txt' 
no pt in the Barcode23_vv.bam 
I have attached errors.txt here. Please let me know what do you think. 
[errors.txt](https://github.com/nanoporetech/dorado/files/13444156/errors.txt)

**Comment by palakpsheth** [comment]
I can also confirm @tijyojwad that no `pt` tag appears with cmd:
`dorado basecaller --estimate-poly-a --emit-sam dna_r10.4.1_e8.2_400bps_sup@v4.2.0 barcode10/ > barcode10_duplex_dna_r10.4.1_e8.2_400bps_sup@v4.2.0.unmapped.sam`

**Comment by palakpsheth** [comment]
is there an assumption that the polyA region must appear anchored to the 3' end of the read?

For example I have a record from the previous cmd above:

```
27b85cc1-2f0d-4e52-bf35-36b405179a11	4	*	0	0	*	*	0	0	ATATAATCTACTCGTTCAGTTACGTATTGCTAAGGTTAAGAGAGGACAAAGGTTTCAACGCTTCAGCACCTTCAGTTCAGGCACACACTACCGCGTCTCATCGATTTTTTTTCGCTGGTCTTGGTCATGGACACAGGCAGGATCTCTGTGGTCACGCTGATGGTGAACTTGGTGGGGATAGCGATAGAGTTGTTGGAGTAGGCCACGCTGTTCTCGGCGCCCAGAGACATTGTGTAGGCAATGATGCTCTGGCTGGCCACGCTTCTGGCTCTCCGAGGGCTGTTTGTCTGTGTCTGGTAGCTGGCGCAGATTCCAGCGCCGATGGGGATGTCGCACTCGTAGCTATTGTTCACGTGCTCGGCTCCGATCAGACAGCCGGCTCTGGTCTGAAACACATTGCTGCCGGTGGAGTACACCCGCCATGTAGGTGTCAGCTGATCGGCGTGAATGGCCACGGGCACTTCGGTACAGTTCACGTCCTGGTACAGCACTGCCACCTGATTGCTGGTGTTGGTGCCAGGGGTGATCACAGACACTCCGCCGAAGCTGCAAGGGGTGATGTCCAGGATTTCCAGTGTCTGGGGATCTCTAACGGCGTCTGTGGTATCGGCGATATCCCGGCCAAACTGCTGGAATGGCAGGAACTTCTTGTTGCTCTCTGTCAGCACGCCGGTGCCGGTCAGGCCGTTGAAGTTGAAGTTCACGCATTTGTTCTTCACGAGATTGGTGCTTTTATTAGGGCCGCACACTGTGGCAGGGGCATGCAGCAGTTCGAAGCTCAGCACCACCACTCTGTAGGGCTGATAGCCCACGCCATTTGTGGGCTGAAAGCCGTAGGACTGCAGTGGGAAGTAGCAGTTGAAGCCTTCCACGCCGTTACAAGGGGTGCTGCCGGCCTGATAGATCTCGGTGGAGATGTCCCGCTCGAAGGGCTTCAGATTGGACTTCCGGAACAGCCGGTACAGGTAATTGTAGTTGCCGCCGACTTTGGAGTCCAGGTTGTTGCTGTTCCAGGCAATCACACAGCCGGTGAAGTCGTCGGGCAGCTTGTAGTTGTAGTCGGCGATCTTGCCTGTCTGTCCAGGGGCAATCTGCCGCACTTCGTCTCGGCCATGAAGGGAAAAGAAAAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAAAAGAAAGAGAGAGAGAAAGAAAGGAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGCTGGGACACGTACTCGAAGGTGCAGTTGTTGGCGCTGCTGTACACCCGGAACTCGCTTTCCATCCAGCTCTTGTTGTTCTTGTGGTAGTAGACGCCAGGAAGGGGTCGTTCCAGAACTGGAACTCGCACACTTTGATGACCACGTTGGTGGCGTTGTTCACGATCAGCAGGCTCTGGGTCTTGCTGTCCAGTGTGGTGCCGAAGATCCAGCCTCTGATGATGTTGGACTTCTCGGTGCTGGCAAAGTACACCCCGTCGTTGAAGGGCAGCACGGGGTTGTCGAATCTCTTGGTGCCATTGGTGCCGGACACGTGGATGGCGTGGAACCAGGTCACGTTGCTGAAGAAAGGCAGGAACAGGTCCTGGGTAGAGTGCAGCACGCTGGATCTGAACACCTTGTCGGGGTAGTACACGCCTCTGGTAAAGCTGTTGGTGTAGGCTGGAGGCAGCTGTGTTCTGGTGGTCAGGTTCACACACTGGCTGGACACCAGAGGCAGCAGCACCAGGAACACGAACATGGTGGCGGGTTCTTGTCTGAGTCTGTGGGGACCAGAAGAATACTAGTTTATTCTCTATAGTGAGTCGTATTAGTCCTTGACGAGACGGGAATCTAGAGCGGTGTCGAGGTGCTGAAGCGTTGAAACCTTTGTCCTCTCTTAACCTTAGCAATACGTT	$$$%%%&''((*&&'--3000277::?DC=>==@HFECDEFHEFEHGFOGGHJIJGCDABIFGFGFFHS@?=./BCDJFSJSHJFGDECDDEDADFDKJCEC>>?>?EFFHK<311DESIHLJNEBA@@AAB@@<;<<=HNLSKECBAEAB=>JFBBA@?A:44*(''''%&/23=CCC?@@@BM98889C45DD<CEFCBCEDKNGIGSGSFSIJHSJPGGOMMIIFRMILFFGEEDDGFFDDEHHKGOJFIKSKSHKLHSLJIMKSKNRGKHSKKHKSOKSGFIIHHOJPJRHSKIKISG>==<<?>;87//-.20111128;DCKHIPKCEBDEIIGESGNGSKHLJKNJHGFHLHDFFHDH:;FFMHHJFINLSHSHGS@@@A@OIRGGEFCCBDEGNFQGHHESLIQMRMHKJEIHROIJBBCCHSHEOGJQILSMKGIKIMIEFJSJLKGFEIEGHIDSJRKLHGGGGQKSSSSKSLHSGGIS?>444@@DLIFGJHHSSOSJJSOA@@@@F/....CSJHKILGEHGJIPSOIHJKJHNOHKGOLSIIOJKSQRKJJHGSKKII@KSLHKSKGFGHHKKSSLIHKIOLGNHGHIKKLNSIGFEIC??>>88867BBDSNJSSJSKA99:CCEDFHEDEDHHSKMSJEHKSJFHGKGSHSIKKKFCDIFSSEDEB;8/-,((((BCEBBDCEDEDEEDEHIFECDCBA>6-,,*****.--.023335****+//07DDEEJEHFEEEDCDEFINEEFFBBBEDGSFHHSJMSFCHIDCEDAEEBDDBCC64444=?>87677;=@>>>>>===<=??>AA>====@@?===>ADDEAA@????AB87777;<==?>BBBDC>><<<;777732232:>BHGCBCGEHEEFGMA>>>=?BCCDEHEHLGFFDCBGHEKHSSFCFDKA@>==>???@?BEDFFGBBCACACDBBCA@@>>>CBBAA@@@A@@BDDFDBBCCCFEEDCCEEGEIIHFGEDJEHKHIGFJJGG>=<=<A@@?ADFFHEEEGJJHIIFFHGIGGBAAA@BA@@@ACLDFDEDDGEECCEDGFHA<<;<=FDEFDFEGDECBBB@987656/,,,+)'&%%%%$$###&&'('(((''&'&&&%&%$&%%&&&'%&'&&'%%&%&&&&'&%&%%&%%'%&&&&(&%&%%%%%%%%%&&&&%%&('(((''%&&&%%'(''&''&&&'&&%&&&&&&&&&%&&&&&%$##""""""#################$####$$$$$$$$$%%%%%%%%%%%&&''(()))(%%%%&&%%&&'(+,-/01122200/***++,,--+++++++++*(&&&&&&$$$$$$$$$$$$$###$############$$$$$$$$$#########$$$$$$$$$$$$$############$$$$$$$############"""""""""""""""""""""""#$$$$%*1111.---.>??CDGHCDEDCMOLLJHILSSIIIFGEGFK@EGSILJHKHSGKIEGIHHSKSSNHGSJSHSIKHHSCBD;;;:::>883..BA@E>>>>8777+++++==SJJOHSKSKKNSKGGSKSSSNLFSMHJISKHKGLSSQIRNLHSGSMKISIJNPSJOIGISJHSIILSPLHKLSLLIGJMSSIHOHSHHKRSSSJSPKSLESGKHSNGLHMLNLKPNHHGKLSSSI>===?BBAACS87???CCDGPJOHSOKSSFISSSKSSGMHHHJRSSSJPSMIHIIJMLIIGGIIIQGIHKKSSPFHIJSSLKMKGJGKOJKSFQISKOHGGEJKKJILRHIQKGSIJRHIKLSHLJJSIHNGHGNSKIHMKPSKJSLMSFGIIJGPLIIOOSJSSOKMNHGHEISSFIMKHFGJLKKKHOGFHGHFGIFGSFDDEDNJGKLIGMHHKGKEISGSSJSGGHGSHFSIMIGKHSIJRLLKPJLGHSSHNMLIQLMLNIIMHJFGHB>=>>=@EB::9984421110.))))+555IJGJJEL>??1111180000ACBBMFFHKIIGGJGKFLPJFGSDFEGKINHHJLJKGJIGCDBPHSGJEHGLIPGMPONLFHKISOGHKKPEEFGGEFGOEEFBCIDB=?:;;89DF@?..7-+++'&&$	qs:i:11	du:f:6.7444	ns:i:33722	ts:i:10	mx:i:1	ch:i:271	st:Z:2023-10-14T04:34:36.879+00:00	rn:i:11217	fn:Z:channel-271.pod5	sm:f:76.2331	sd:f:42.5691	sv:Z:quantile	dx:i:0	RG:Z:3d4e956d712e1e48c5efd351d6f1965dce84baa6_dna_r10.4.1_e8.2_400bps_sup@v4.2.0
```

**Comment by chatla01** [comment]
any updates?

**Comment by tijyojwad** [comment]
Hi @chatla01 just checking to see if you can provide a sample dataset?

**Comment by tijyojwad** [comment]
HI @palakpsheth - for cDNA dorado can find polyA on 3' end and polyT on 5' end, depending on the orientation.

**Comment by dweemx** [comment]
> Hi @dweemx - works for DNA as well (tuned for cDNA primarily)

Hi @tijyojwad,

I tested this feature for a sample sequenced with the `SQK-NBD114.96` DNA kit. I used the `dna_r10.4.1_e8.2_400bps_hac@v4.3.0` mode for the basecalling step. I run the `dorado basecaller` specifically on the `pod5` of 1 particular barcode/sample:

```bash
dorado \
   basecaller \
      -vv \
      --recursive \
      --device cuda:all \
      --reference plasmid.fasta \
      --estimate-poly-a \
      --emit-moves \
      dna_r10.4.1_e8.2_400bps_hac@v4.3.0 \
      barcode_47/ \
      > calls_with_moves.bam 2> error.log
```
It seems that the algorithm was not able to estimate the poly(A) region of the reads. I have no reads with the `pt:i`.

You can find the log here: [error.log.gz](https://github.com/nanoporetech/dorado/files/14008882/error.log.gz).

Any reason why it was not able to estimate the poly(A) region. Are planning to tune the estimation for DNA soon?

**Comment by tijyojwad** [comment]
Hi @dweemx - the polyA tail estimation is primarily designed for cDNA kits (PCS and PCB) and RNA. Other kits are not really supported as the experimental methods are not designed to captured the (full) tail.

**Comment by dweemx** [comment]
Hi @tijyojwad,

I thought you mention previously that it was also supposed to work for DNA?

Are you planning to make it work for the DNA kits?

**Comment by tijyojwad** [comment]
Hi @dweemx - my apologies, I should have clarified, that it only works for _cDNA_ kits. We do plan to add support for specifying custom primers for polyA search, and that will enable use cases like yours which use NBD kits. But note that those preparation methods are not designed to capture the tail.

**Comment by dweemx** [comment]
Hi @tijyojwad,
Ok thanks. Do you have an ETA for this feature (support for custom primers to search for poly(A) for NBD kits) or a feature roadmap available to track this feature?

**Comment by chatla01** [comment]
Hi @tijyojwad,

Dorado is not going call polyA (80 to 100 bp) sequences in the middle of plasmid?

**Comment by tijyojwad** [comment]
Hi @chatla01 - I now have a better understanding of polyA estimation in plasmids - looks like they can occur in the middle of the reads and have different flanking sequences than what we expect from normal cDNA preps. This is not currently supported by dorado, but it's on our roadmap. We will reach out to you offline.

**Comment by yul96** [comment]
@tijyojwad thank you for working on this, looking forward to testing it out

**Comment by palakpsheth** [comment]
> Hi @chatla01 - I now have a better understanding of polyA estimation in plasmids - looks like they can occur in the middle of the reads and have different flanking sequences than what we expect from normal cDNA preps. This is not currently supported by dorado, but it's on our roadmap. We will reach out to you offline.

We would be very interested in this feature working well

**Comment by chatla01** [comment]
> Hi @chatla01 - I now have a better understanding of polyA estimation in plasmids - looks like they can occur in the middle of the reads and have different flanking sequences than what we expect from normal cDNA preps. This is not currently supported by dorado, but it's on our roadmap. We will reach out to you offline.

Hi tijyojwad, Please feel free to reach out, I don't mind sharing some data. I am in touch with Androo Markham. Thank you.

**Comment by tijyojwad** [comment]
I'm going to close this issue as it's become a mixup of several things. @chatla01 can you create a new issue for the plasmid polyA calling? I will follow up with updates there (and I'll Cc @palakpsheth as well)
