### ISSUE TITLE
Do you have a 0.7.3 binary available for linx x86?

### ISSUE THREAD

**Issue by robin-sto** [nanoporetech/dorado#1000]
Please let me know

**Comment by malton-ont** [comment]
Hi @robin-sto,

Available binaries are [here](https://github.com/nanoporetech/dorado?tab=readme-ov-file#installation). Assuming you mean `linux x86_64`, then yes. If you really mean a 32-bit variant (or "linx" is something I'm not aware of) then no.

**Comment by robin-sto** [comment]
Thank you.  When this tar is unzipped, I am only seeing a dorado directory and not an executable.  Also, there is no bin directory.  Is there something more that has to be done to generate these items?

**Comment by robin-sto** [comment]
Thank you for clarifying, that was the problem.  I had the wrong file.
