### ISSUE TITLE
Providing model directories to dorado duplex

### ISSUE THREAD

**Issue by JudoWill** [nanoporetech/dorado#1001]
# Issue Report

## Please describe the issue:

`dorado duplex model reads` doesn't seem to allow you to specify two locally downloaded models.

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

When running:
```bash
dorado duplex sup path/to/reads
```
The program downloads two files.

```
[info]  - downloading dna_r10.4.1_e8.2_400bps_sup@v5.0.0 with httplib
[info]  - downloading dna_r10.4.1_e8.2_5khz_stereo@v1.3 with httplib
```

Since I'm running this across each channel, I used `dorado download` to pre-fetch the models. However, I can't seem to figure out out to specify both.

```bash
dorado duplex {prefix}/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 {prefix}/dna_r10.4.1_e8.2_5khz_stereo@v1.3 path/to/channel-1.pod5
```
fails with "Too many arguments".

Adding quotes:
```bash
dorado duplex "{prefix}/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 {prefix}/dna_r10.4.1_e8.2_5khz_stereo@v1.3" path/to/channel-1.pod5
``` 
Doesn't resolve to a path and fails at the loading stage.

Specifying only the stereo model fails at the model loading step.
```bash
dorado duplex {prefix}/dna_r10.4.1_e8.2_5khz_stereo@v1.3 path/to/channel-1.pod5
```

Specifying only the simplex model runs without errors but it produces an invalid bam file.
```bash
dorado duplex {prefix}/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 path/to/channel-1.pod5
```
Digging through the bam, it seems that the duplex reads are empty and it causes a parsing error.

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*
Above.

## Run environment:
- Dorado version: 0.7.2
- Dorado command: dorado duplex
- Operating system: Ubuntu
- Hardware (CPUs, Memory, GPUs): NA
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): Pod5
- Source data location (on device or networked drive - NFS, etc.):  local
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB):  NA
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue): NA

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)
Logs from a "successful" run of `dorado duplex` with only a simplex model

```
[2024-08-26 16:04:54.508] [info] Running: "duplex" "--reference" "refs/hg38hxb2f.ont.mmi" "/deepdata/share/collections/assets/dorado_models/models/dna_r10.4.1_e8.2_400bps_sup@v5.0.0" "pod5/channel-141.pod5"
[2024-08-26 16:04:54.516] [info] > No duplex pairs file provided, pairing will be performed automatically
[2024-08-26 16:05:02.822] [warning] Indexing parameters mismatch prebuilt index: using paramateres kmer size=15 and window size=10 from prebuilt index.
[2024-08-26 16:05:09.916] [info] cuda:0 using chunk size 12288, batch size 256
[2024-08-26 16:05:14.452] [info] cuda:0 using chunk size 10000, batch size 1408
[2024-08-26 16:05:15.641] [info] > Starting Stereo Duplex pipeline
[2024-08-26 16:05:15.657] [info] > Reading read channel info
[2024-08-26 16:05:15.705] [info] > Processed read channel info

samtools index channel-141.bam
[E::hts_idx_push] NO_COOR reads not in a single block at the end 9 -1
[E::sam_index] Read '6961eba4-a4e7-452f-9080-9ff46b894ae9' with ref_name='chr17', ref_length=83257441, flags=0, pos=2939834 cannot be indexed
samtools index: failed to create index for "/home/will/Downloads/channel-141.bam"
```

**Comment by HalfPhoton** [comment]
There is no way to specify a stereo model in dorado on the command line. 

Dorado should implicitly use the stereo model in the directory you've set as`{prefix}` if the simplex model is also in that directory and you only need to set the simplex basecalling model as you have done. 

This behaviour will change in an upcoming release where the new `--models-directory` option will be available. 

--- 

However, this example should have worked 
```
dorado duplex {prefix}/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 path/to/channel-1.pod5
```

Can you tell us how the output is corrupt?

Best regards,
Rich

**Comment by JudoWill** [comment]
Gotcha, since its auto picking the right model using
```bash
dorado duplex {prefix}/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 path/to/channel-1.pod5
```
I'll just do that.

What I didn't realize doing `samtools index channel-1.bam` is that the file doesn't come out pre-sorted by position (which makes sense now that I think about it). After I did a `samtools sort` everything indexes and exports correctly.

I'll keep my eye out for `--models-directory`.
