### ISSUE TITLE
dorado basecalling of recovered pod5 files not working

### ISSUE THREAD

**Issue by chris-krohn** [nanoporetech/dorado#1006]
Hi

After an issue with our MinION Mk1C we recovered non-basecalled files into pod5 files - using the recommended `/opt/ont/minknow/bin/recover_reads` command of MinKNOW on the device. 

However, dorado did not basecall these recovered files. 

I tried the following basecallers to basecall them:

basecaller [./dna_r10.4.1_e8.2_400bps_sup@v5.0.0](mailto:./dna_r10.4.1_e8.2_400bps_sup@v5.0.0)
basecaller ./[dna_r10.4.1_e8.2_400bps_hac@v5.0.0](mailto:dna_r10.4.1_e8.2_400bps_hac@v5.0.0)
basecaller ./ [dna_r10.4.1_e8.2_400bps_hac@v4.3.0](mailto:dna_r10.4.1_e8.2_400bps_hac@v4.3.0)
 
using the following command as recommended by ONT support:

`/mnt/dorado-0.7.3-linux-x64/bin/dorado basecaller [./dna_r10.4.1_e8.2_400bps_xxxx](mailto:./dna_r10.4.1_e8.2_400bps_sup@v5.0.0) recoveredPOD5/ --min-qscore 7 --kit-name SQK-NBD114-96 --sample-sheet samplesheet.csv --barcode-both-ends`

**RESULTS:**

See [terminaloutputs.txt](https://github.com/user-attachments/files/16791020/terminaloutputs.txt) for commands and verbose outputs in terminal.

Note that no folder named dorado_logs or similar were present in /var/log or otherwise. There were no logs.
Attempts (1), (2) and (3) resulted in 836 B, 2.8 KB and 840 KB of .bam data respectively. For (1) and (2) the file was zero for most of duration of basecalling, i.e it did not actively add much base-called data.

The recovered POD5 data (36.1 GB) for reference:
![image](https://github.com/user-attachments/assets/1e7bc0dd-a442-4b67-8219-9be9aafab1e3)

**Comment by HalfPhoton** [comment]
Hi @chrismitbiz, 

It looks like dorado is filtering out all of the reads. 
```
[2024-08-25 04:02:32.919] [info] > Simplex reads basecalled: 8
[2024-08-25 04:02:32.919] [info] > Simplex reads filtered: 742991
```

Can you run `pod5 view` on this dataset to see if the files can read by the pod5 api and if the reads are a sensible length after being recovered?

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
The reads data shown here all looks sensible at a glance... I suspect the signal data has been corrupted somehow. 

Can you share an original pod5 file with us and it's recovered pair? I can send a link to upload data securely to us if so.

Best regards,
Rich

**Comment by chrismitbiz** [comment]
Yes that should be possible. You can send to christian.krohn@rmit.com.au. 
Thank you! 
Chris

**Comment by HalfPhoton** [comment]
Hi @chris-krohn,
Apologies for the delay. 

Could you create a [customer support](https://nanoporetech.com/support) request where they can collect and share the data with me.

Please reference this GitHub Issue so they have all the necessary context. 

Kind regards,
Rich

**Comment by chris-krohn** [comment]
Thanks Rich,  Thanks for getting back to this. I have no need to solve this problem anymore. Although, data was uploaded to the support team with you included so if you wanted to follow this up you can. Happy to close this otherwise.
