### ISSUE TITLE
Does dorado do "modified base status separated from basecalling" like remora does?

### ISSUE THREAD

**Issue by rainwala** [nanoporetech/dorado#1007]
Hello, 

I would like to know whether dorado uses the "modified base status separated from basecalling" approach like remora does. If this is the case, I assume using a modified basecalling model should not affect the accuracy of calling the four canonical bases at all (which is important for my use case). Is that assumption correct?

**Comment by malton-ont** [comment]
Hi @rainwala,

Yes, you are correct. Canonical basecalling is performed first then modification calling is performed as a separate step, and so does not affect the called sequence.

**Comment by rainwala** [comment]
Thank you!
