### ISSUE TITLE
basecalling model selection

### ISSUE THREAD

**Issue by sjfleck** [nanoporetech/dorado#1008]
Hello,
I'm using Dorado v0.7.3 for the first time. I'm trying to figure out the correct basecalling model, but I'm having trouble. My fast5 file includes:
Xbasecall_config_filenamedna_r9.4.1_450bps_hac.cfg

I believe this means I should use "dna_r9.4.1_e8_hac@v3.3"

A second set of fast5 files include:
Pbasecall_config_filenamedna_r10.4_e8.1_hac.cfg

I'm not sure what to do here because all the models listed on the github page are e8.2, not e8.1. 

Do you have a recommendation for me? Also, please let me know if you need any further information from my fast5 files. Thank you for any help you are able to provide. Thank you,
Steve

**Comment by malton-ont** [comment]
Hi @sjfleck,

Yes, for `dna_r9.4.1_450bps_hac.cfg` you will want to use `dna_r9.4.1_e8_hac@v3.3`. Note that we recommend converting your data to pod5 format for optimal performance.

Dorado does not support the r10.4 chemistry. For this, you will need to go back to guppy I'm afraid.

**Comment by sjfleck** [comment]
Thank you for your quick response. Do I have to use the high accuracy basecalling (dna_r9.4.1_e8_hac@v3.3) or can I use the super-accurate basecalling (dna_r9.4.1_e8_sup@v3.3) for Dorado? Thank you

**Comment by malton-ont** [comment]
@sjfleck,

You can use any of the `dna_r9.4.1_e8` models.

**Comment by SRIVSSI** [comment]
Hi @malton-ont 

Just curious about your response earlier, that Dorado does not support r10.4 chemistry.
Does that mean that the newest Flow Cells (R10.4.1) are not compatible with the newest Dorado basecaller in MinKNOW?

This sounds a bit strange since there are basecallers for 10.4 and all.. Or did I understand this wrong?

Thanks!

**Comment by malton-ont** [comment]
Hi @SRIVSSI,

I believe you have misunderstood. Dorado supports 10.4.1 (e8.2), but not 10.4 (e8.1).
