### ISSUE TITLE
Order of flags importance

### ISSUE THREAD

**Issue by pwh124** [nanoporetech/dorado#101]
Hello,

We have noticed that the order of the flags matters when running Dorado, especially the `--modified-bases` option. We have seen this same behavior with previous versions as well as v0.2.1.

For example, when I run:
```
~/software/dorado_0.2.1/bin/dorado basecaller --verbose -x "cuda:all" --num_runners 8 --modified-bases 5mCG_5hmCG ~/software/dorado_0.2.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.0.0 {pod5}.pod5 >  {output}.sam
```
I get the following error
```
[2023-02-16 09:37:35.844] [error] '/home/phook2/software/dorado_0.2.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.0.0' is not a supported modification please select from 5mCG, 5mCG_5hmCG
```
And when I flip the `--modified-bases` flag to another position, like so:
```
~/software/dorado_0.2.1/bin/dorado basecaller --verbose -x "cuda:all" --modified-bases 5mCG_5hmCG --num_runners 8 ~/software/dorado_0.2.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.0.0 {pod5}.pod5 >  {output}.sam
```
It begins to run.

Paul

**Comment by vellamike** [comment]
Hi @pwh124 - this definitely sounds like a bug. We are looking into it.

**Comment by iiSeymour** [comment]
Thanks @pwh124 there is a little more detail here https://github.com/nanoporetech/dorado/issues/56#issuecomment-1343445514
