### ISSUE TITLE
What is the relationship between qs tag and base modification?

### ISSUE THREAD

**Issue by 1Wencai** [nanoporetech/dorado#1011]
Hello，
For a read, is there a relationship between Q score and the accuracy of detecting base modification? Does the larger the Q score, the higher the credibility of the base modification reported by this read?
Do you have a specific value for filtering qs tag? I want to detect 6mA base modification.

wencai

**Comment by malton-ont** [comment]
Hi @1Wencai,

The `qs` tag reports the mean confidence in the canonical basecall (see [here](https://github.com/nanoporetech/dorado/issues/994) for previous discussions around this).

The confidence in each modification call is reported in the `ML` tag. See "1.7 Base modifications" [here](https://samtools.github.io/hts-specs/SAMtags.pdf) for details.
