### ISSUE TITLE
Loss of Data after Dorado Correction

### ISSUE THREAD

**Issue by Ladybug1030** [nanoporetech/dorado#1014]
# Issue Report

## Please describe the issue:

This is not really an issue but a question to assist with understanding my data.

I have a question about how dorado correct works. I have noticed a substantial difference between the amount of data (after running Nanoplot) I have before and after dorado correct. For instance, after dorado basecalling I may have 4 GB of data and after performing dorado correction, I have 600 Mb of data.  I have also observed a shift in my N50 after dorado correction as well. Initially with the 4 Gb of data, I may an N50 of 2 kb, but then after dorado correct with the 600 Mb of data, my N50 is now 20 kb.  Is dorado correct removing all of the small reads? Is it using minimap2 to perform a "soft-clipping" of the small reads? Or is it a hard-clip? 

## Steps to reproduce the issue:

N/A

## Run environment:
- Dorado version: 0.7.1
- Dorado command: dorado correct
- Operating system: SLURM Cluster
- Hardware (CPUs, Memory, GPUs): GPU 
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): initial fast5s were converted to pod5s for dorado basecalling. All reads were then converted to fastqs that were bgzipped for dorado correct.

**Comment by malton-ont** [comment]
Hi @Ladybug1030,

N50 of 2kb is too short for `dorado correct`. See https://github.com/nanoporetech/dorado/issues/956.
