### ISSUE TITLE
clair3 r104_e81_sup_g5015 model error

### ISSUE THREAD

**Issue by sjfleck** [nanoporetech/dorado#1018]
# Issue Report

## Please describe the issue:

I have old reads (sequenced with cell type FLO-MIN112 and kit type SQK-LSK112). I need to use the clair3 r104_e81_sup_g5015 base calling model. I downloaded this model using the instructions in nanoporetech/rerio, but when I ran it with dorado, I got an error immediately.

## Steps to reproduce the issue:

cd my/working/directory
RERIO_DIR=/projects/academic/tkrabben/modules_KrabLab/rerio
$RERIO_DIR/download_model.py $RERIO_DIR/clair3_models/r104_e81_sup_g5015_model

module load gcc/11.2.0  
module load openmpi/4.1.1
module load samtools/1.16.1
DORADO_DIR=/projects/academic/tkrabben/software/Dorado/dorado-0.7.3-linux-x64/bin
MODEL=r104_e81_sup_g5015
${DORADO_DIR}/dorado basecaller ${MODEL} ${POD5_DIR} > ${PREFIX}.simplex.${MODEL}.calls.bam

## Run environment:
- Dorado version:0.7.3
- Dorado command: ${DORADO_DIR}/dorado basecaller ${MODEL} ${POD5_DIR} > ${PREFIX}.simplex.${MODEL}.calls.bam
- Operating system: Ubuntu 22.04.4 LTS 
- Hardware (CPUs, Memory, GPUs): 1 CPU, 1GPU, 16 GB memory (I can test with any number of threads or amount of memory up to 512 GB. 16GB for memory was fine with other runs)
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): fast5 (but also tried pod5 even though I don't think guppy works with pod5)
- Source data location (on device or networked drive - NFS, etc.): private data
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): I base call my fast5/pod5s individually and combine the fastq later to run herro on. 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)
from .err file:
[2024-09-04 23:20:51.723] [info] Running: "basecaller" "r104_e81_sup_g5015" "./fast5_pass3"
terminate called after throwing an instance of 'std::runtime_error'
  what():  toml::parse: file open error -> r104_e81_sup_g5015/config.toml
/var/spool/slurmd/job17070698/slurm_script: line 58: 382113 Aborted                 ${DORADO_DIR}/dorado basecaller ${MODEL} ${POD5_DIR} > ${PREFIX}.simplex.${MODEL}.calls.bam

I should also note here that ./r104_e81_sup_g5015/config.toml does not exist. It was don't one of the files generated when I downloaded that model

**Comment by HalfPhoton** [comment]
Hi @sjfleck, 
Clair3 and Dorado are different tools for different uses and their models are not compatible with each other. 

This clair3 model is not a basecalling model. It's a Clair3 small variant calling model for basecalls generated from guppy 5.0.15 for the r10.4 e8.1 condition.

Best regards,
Rich
