### ISSUE TITLE
DNA damage models/methods

### ISSUE THREAD

**Issue by ethan-mcq** [nanoporetech/dorado#1019]
# Issue Report

## Please describe the issue:
In London calling, Clive mentioned "the ability to detect damaged DNA bases, including genomic Uracil (dU) at 96.34% accuracy." I am very interested in the methodologies used to do this and if there is a separate model that is available to perform this analysis. We are looking to detect damaged Uracil in RNA and would like to jump on this!

**Comment by HalfPhoton** [comment]
Hi @ethan-mcq, as this is not a Dorado issue I'd kindly request that you ask this question on the Nanopore Community Forums.

We're always working on more mods models and will release them as and when they are developed. 

Kind regards,
Rich
