### ISSUE TITLE
CUDA CUBLAS error when basecalling with v0.2.1

### ISSUE THREAD

**Issue by jagos01** [nanoporetech/dorado#102]
Hello,
Basecalling with dorado v0.2.1 using the following command:
```
dorado basecaller /home/dorado-0.2.1-linux-x64/models/dna_r10.4.1_e8.2_260bps_sup@v4.1.0 /home/Data_Raw/TNO3/260bps/ --emit-moves | samtools view -Sh > /home/data1/Analyzed_data/TNO3/TNO3.260.all.simplex.sup.bam
```
generates the following error:
```
[2023-02-16 09:56:54.768] [info] > Creating basecall pipeline
[2023-02-16 09:56:57.111] [error] CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
Exception raised from gemm<c10::Half> at ../aten/src/ATen/cuda/CUDABlas.cpp:448 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f8dc765c457 in /home/dorado-0.2.1-linux-x64/bin/../lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f8dc76263ec in /home/dorado-0.2.1-linux-x64/bin/../lib/libc10.so)
frame #2: <unknown function> + 0x2fdba11 (0x7f8d6a8e6a11 in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cuda_cu.so)
frame #3: <unknown function> + 0x2ff586d (0x7f8d6a90086d in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cuda_cu.so)
frame #4: at::native::structured_mm_out_cuda::impl(at::Tensor const&, at::Tensor const&, at::Tensor const&) + 0x4a (0x7f8d6a9020fa in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cuda_cu.so)
frame #5: <unknown function> + 0x2d1ec08 (0x7f8d6a629c08 in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cuda_cu.so)
frame #6: <unknown function> + 0x2d1ec80 (0x7f8d6a629c80 in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cuda_cu.so)
frame #7: at::_ops::mm::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&) + 0x6e (0x7f8d9f2cfcde in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x4033e20 (0x7f8da0af8e20 in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x4034b23 (0x7f8da0af9b23 in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cpu.so)
frame #10: at::_ops::mm::call(at::Tensor const&, at::Tensor const&) + 0x161 (0x7f8d9f3230f1 in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x1dac081 (0x7f8d9e871081 in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cpu.so)
frame #12: at::native::matmul(at::Tensor const&, at::Tensor const&) + 0x49 (0x7f8d9e871499 in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x2d6ea40 (0x7f8d9f833a40 in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cpu.so)
frame #14: at::_ops::matmul::call(at::Tensor const&, at::Tensor const&) + 0xc3 (0x7f8d9f41f283 in /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cpu.so)
frame #15: dorado() [0x558f92]
frame #16: dorado() [0x55a1d2]
frame #17: dorado() [0x55b1f9]
frame #18: dorado() [0x49a926]
frame #19: dorado() [0x49cf34]
frame #20: dorado() [0x45df95]
frame #21: __libc_start_main + 0xe7 (0x7f8d6592cc87 in /lib/x86_64-linux-gnu/libc.so.6)
frame #22: dorado() [0x461d9f
```
This error occurs on systems running Ubuntu 18.04 and 20.04 both with CUDA 11.2.
The above command works with v0.1.1.  Any suggestions are appreciated.
Thanks,

**Comment by vellamike** [comment]
Hi @jagos01,

I've been unable to reproduce this error. Would it be possible for you to try this on a system with CUDA 11.7 or CUDA 12.0?

**Comment by jagos01** [comment]
Hello Mike,
I will try to install CUDA 11.7 on my system this weekend.  The output of ldd dorado is:

ldd /home/dorado-0.2.1-linux-x64/bin/dorado
	linux-vdso.so.1 (0x00007ffd0d7a7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f01cfdab000)
	libtorch.so => /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch.so (0x00007f01d01ad000)
	libtorch_cuda.so => /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cuda.so (0x00007f01d018e000)
	libtorch_cuda_cpp.so => /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cuda_cpp.so (0x00007f01c07a2000)
	libtorch_cpu.so => /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cpu.so (0x00007f01a549d000)
	libc10_cuda.so => /home/dorado-0.2.1-linux-x64/bin/../lib/libc10_cuda.so (0x00007f01d008e000)
	libc10.so => /home/dorado-0.2.1-linux-x64/bin/../lib/libc10.so (0x00007f01cffdc000)
	libcublas.so.11 => /home/dorado-0.2.1-linux-x64/bin/../lib/libcublas.so.11 (0x00007f019bd1f000)
	libtorch_cuda_cu.so => /home/dorado-0.2.1-linux-x64/bin/../lib/libtorch_cuda_cu.so (0x00007f01702e3000)
	libnvToolsExt.so.1 => /home/dorado-0.2.1-linux-x64/bin/../lib/libnvToolsExt.so.1 (0x00007f01700d9000)
	libcudart.so.11.0 => /home/dorado-0.2.1-linux-x64/bin/../lib/libcudart.so.11.0 (0x00007f016fe34000)
	libzstd.so.1 => /home/dorado-0.2.1-linux-x64/bin/../lib/libzstd.so.1 (0x00007f016fb81000)
	libhdf5.so.8 => /home/dorado-0.2.1-linux-x64/bin/../lib/libhdf5.so.8 (0x00007f016f6db000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f016f4be000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f016f29f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f016f097000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f016ec8a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f016e8ec000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f016e6d4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f016e2e3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f01cffaf000)
	libcudart-e409450e.so.11.0 => /home/dorado-0.2.1-linux-x64/bin/../lib/libcudart-e409450e.so.11.0 (0x00007f016e03a000)
	libnvToolsExt-847d78f2.so.1 => /home/dorado-0.2.1-linux-x64/bin/../lib/libnvToolsExt-847d78f2.so.1 (0x00007f016de2f000)
	libcudnn.so.8 => /usr/local/cuda/lib64/libcudnn.so.8 (0x00007f016dc06000)
	libgomp-a34b3233.so.1 => /home/dorado-0.2.1-linux-x64/bin/../lib/libgomp-a34b3233.so.1 (0x00007f016d9da000)
	libcublasLt.so.11 => /usr/local/cuda/lib64/libcublasLt.so.11 (0x00007f0162255000)
	libcublas-f6acd947.so.11 => /home/dorado-0.2.1-linux-x64/bin/../lib/libcublas-f6acd947.so.11 (0x00007f0158ad3000)
	libsz.so.2 => /home/dorado-0.2.1-linux-x64/bin/../lib/libsz.so.2 (0x00007f01588d0000)
	libcublasLt-2e7ea254.so.11 => /home/dorado-0.2.1-linux-x64/bin/../lib/libcublasLt-2e7ea254.so.11 (0x00007f0143a80000)
	libaec.so.0 => /home/dorado-0.2.1-linux-x64/bin/../lib/libaec.so.0 (0x00007f0143878000)

**Comment by vellamike** [comment]
I see from LDD that Dorado is using the cuBLAS shared library on your
system rather than the one we bundle. Can you try running dorado with the
executable in the working directory? I.e ./dorado?

**Comment by jagos01** [comment]
Hello @vellamike,
I can try that on my other system tomorrow.  I have installed CUDA 11.7 on another system (that failed to call with CUDA 11.2) and it is currently basecalling without any errors.  I noticed dorado v0.2.0 has a --read-id flag but I do not see it with dorado duplex -h.  How is this flag used.
Thanks

**Comment by vellamike** [comment]
OK! If it runs successfully with dorado on the cwd it points to a need for us to improve the way we bundle dorado.

Regarding the `-read-ids` flag, this is exposed for the basecaller not duplex:

```
mvella@shadow-moses0:~/dorado-0.2.1/bin$ ./dorado  basecaller -h
Usage: dorado [-h] [--device VAR] [--read-ids VAR] [--max-reads VAR] [--min-qscore VAR] [--batchsize VAR] [--chunksize VAR] [--overlap VAR] [--num_runners VAR] [--modified-bases VAR...] [--modified-bases-models VAR] [--emit-fastq] [--emit-moves] model data

Positional arguments:
  model                  	the basecaller model to run. 
  data                   	the data directory. 

Optional arguments:
...
  **-l, --read-ids         	A file with a newline-delimited list of reads to basecall. If not provided, all reads will be basecalled [default: ""]**
```

For duplex this option is used automatically (the pairs file is interpreted as a read-ids list so only reads in a pair are basecalled. Let me know if you would like further explanation.

**Comment by aw1231** [comment]
I am receiving the same error with Master and 0.2.1 and my `ldd` looks similar. I'm not sure what you mean by running `./dorado`. I ran the build and did `cd cmake-build/bin` and then `./dorado` with the same effect. Is that what you meant?

**Comment by vellamike** [comment]
Hi @aw1231  - are you running dorado with the executable in your current working directory?

**Comment by aw1231** [comment]
That's where I'm stuck. Should I run it from the folder where my pod5 data is or should I run it from the `bin` folder made by cmake?

**Comment by vellamike** [comment]
I didn’t realise you were compiling from scratch. Before we debug this
further, is there a reason not to just use the released binaries?

**Comment by aw1231** [comment]
Hi! We tried the released binaries and they work great! Thanks.
