### ISSUE TITLE
CPU calling: set num_cpu_runners

### ISSUE THREAD

**Issue by juanjo255** [nanoporetech/dorado#1021]
Hello developers!

A doubt, can I set the number of cpus when using `--device cpu`? I saw that when the started the basecalling this sentences appeared: CPU calling: set num_cpu_runners to 4.

Thank you very much for the help,

Juan

**Comment by juanjo255** [comment]
Oh I found that probably this part of the code is setting the num of cpus automatically based on RAM available and need it using the batch size. I needed very fast basecalling cause I'm in a rush jeje and I was using SUP, changing to FAST model start using all the CPU.
 
![Screenshot 2024-09-17 at 8 00 22 AM](https://github.com/user-attachments/assets/cdbdb560-8fbf-4657-a24b-411384a678fd)

I will wait for developers confirmation

**Comment by malton-ont** [comment]
Hi @juanjo255,

Yes, you are correct - dorado will determine the number of cpu runners based on the model and the available RAM. If you are in a hurry for your basecalling then we heartily recommend finding a supported GPU rather than using CPU!
