### ISSUE TITLE
New RNA models

### ISSUE THREAD

**Issue by DepledgeLab** [nanoporetech/dorado#1025]
Dorado v0.8.0 now has four RNA modification models that can be used during basecalling but it is not clear whether the inosine_m6A model considers m6A in all contexts? In other words, should this be considered the replacement for the all context m6A model from Dorado v0.7.0?

**Comment by HalfPhoton** [comment]
Yes - it's an all-context inosine **and** m6A model

**Comment by mbosm** [comment]
Hello. I just want to make sure I understand the difference between the new RNA modification models. Is it like....

A) inosine_m6A calls both inosine and m6A as one 'modification' and if you use modkit to generate a bed file of the modification, it will output a single modification at both kinds of sites?
B) inosine_m6A calls both inosine and m6A, but as different modifications, and if you use modkit, it will generate a bed file with both kinds of modifications?

How is this different from the m6A_DRACH dorado basecalling? Does this basecalling only look for m6A at DRACH motif sites or any A site? Is it m6A specific, or will it also call an inosine an m6A if it's a DRACH motif site?

Could you hypothetically call m6A exclusively with m6A_DRACH, call both with inosine_m6A, and then 'subtract' the m6A likely sites from the pool of both to get the likely inosine ones?

**Comment by DepledgeLab** [comment]
Option B is correct

When running Modkit on inosine_m6A data I see both modifications recorded in the output (which can then be parsed to analyze each individually). The difference (as I understand it) with m6A_DRACH is that this only looks at m6A and only within DRACH motifs.

**Comment by HalfPhoton** [comment]
Yep! You've answered both of your own questions correctly. 👍 

Thanks for replying and not leaving this issue go stale - Is this issue resolved? 

Best regards,
Rich

**Comment by mbosm** [comment]
It's resolved to my satisfaction. Thank you!

Mike
