### ISSUE TITLE
dorado demux new output names

### ISSUE THREAD

**Issue by phpeters** [nanoporetech/dorado#1026]
Thanks guys for the new version! 

Not really an issue, more something for the changelog: The naming of the demux-output files contains now the acquisition ID as well and not only the provided alias from the sample sheet.

dorado demux  --output-dir demux  --sample-sheet sampleSheet.csv sample.bam
new output with v0.8.0: acquisitionID_alias.bam
old output until v0.7.3:  alias.bam

all the best!
Philipp

**Comment by HalfPhoton** [comment]
Thanks @phpeters for bringing this to our attention. 

Appended the following to the [release note](https://github.com/nanoporetech/dorado/releases/tag/v0.8.0): 
> https://github.com/nanoporetech/dorado/commit/db73e5d767dcc3a9ea9c2d62e2a3d77d7058a231 - Add run_id to filenames output by demux

Best regards,
Rich

**Comment by jfnjdoh** [comment]
This broke a nextflow pipeline I had but it's an easy fix. I'm just curious, what was the reason for this change?

**Comment by HalfPhoton** [comment]
@jfnjdoh - This allows inputs from multiple different runs but of the same barcode kit to be easily identifiable after being demuxed together.
