### ISSUE TITLE
shows no mapping in centromere

### ISSUE THREAD

**Issue by santoshbiowarrior333** [nanoporetech/dorado#1027]
I am new to nanopore seq, however after mapping the reads to T2T assemby, i observed that most of the repeated satellites as well as centromere shows no mapping. Is it the Dorado or any command that is not allowing the mapping to there regions?

**Comment by HalfPhoton** [comment]
Hi @santoshbiowarrior333, 

I don't think this is a Dorado issue.

Please submit this question to the [nanopore community](https://nanoporetech.com/support) forum where they'll be able to assist.

Best regards,
Rich

**Comment by santoshbiowarrior333** [comment]
Thank you.
