### ISSUE TITLE
Modified basecalling much slower on v8 compared to older versions

### ISSUE THREAD

**Issue by bencarty2** [nanoporetech/dorado#1029]
Hello,

I've been trying the DNA modified basecalling for the most recent 5mCG_5hmCG, 6mA on Dorado v8.0 (sup@v5.0.0). RTX 4090 GPU. Compared to the same pod5s on my previous go-to version (Dorado v6.1, sup@4.3) for the same mods, the basecalling time is significantly slower on v8 with an otherwise exact same script. Almost double the basecalling time. Is this generally to be expected? 

Thanks!

**Comment by malton-ont** [comment]
Hi @bencarty2,

See https://github.com/nanoporetech/dorado/issues/957. `sup@v5` basecall models use a new architecture which provides increased accuracy but are currently slower than the older models. We are actively working on performance improvements, which will be released in future versions of dorado.
