### ISSUE TITLE
configure incomplete

### ISSUE THREAD

**Issue by isabelluo** [nanoporetech/dorado#103]
Hi developers and all experienced MinION users, 
I encountered some configuration issue for dorado. 
when I typed in the "cmake -S . -B cmake-build" command
two errors returns. 
```
"-- Build type: 
-- Submodule update
CMake Error at cmake/Koi.cmake:18 (message):
  Unsupported CUDA toolkit version: 10.1.243
Call Stack (most recent call first):
  cmake/Koi.cmake:45 (get_best_compatible_koi_version)
  CMakeLists.txt:23 (include)"
```

I think it might be the cuda toolkit version issue, but I dont know which tool kit version I should update to.  
in order to provide better trouble shoot for my issue, the following some basic version information installed in our linux computer. 

```
--  Cmake version :Cmake 3.25.2 
-- nvcc version:Cuda compilation tools, release 10.1, V10.1.243
-- nvidia-smi : 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A4000    Off  | 00000000:65:00.0  On |                  Off |
| 41%   31C    P8    18W / 140W |    270MiB / 16376MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1509      G   /usr/lib/xorg/Xorg                 65MiB |
|    0   N/A  N/A      2016      G   /usr/lib/xorg/Xorg                145MiB |
|    0   N/A  N/A      2143      G   /usr/bin/gnome-shell               30MiB |
|    0   N/A  N/A      3550      G   ...379416372210713123,131072       17MiB |
+-----------------------------------------------------------------------------+
```

Here is what I have. Please help me, I am new to all these computer and working environment knowledges. Any help would be appreciated.

**Comment by iiSeymour** [comment]
Hey @isabelluo 

You don't have to compile from source as we provide builds [here](https://github.com/nanoporetech/dorado#installation) but to answer the issue, this is how cmake decides which CUDA toolkit to select https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html.

Your system probably has `/usr/local/cuda` pointing at `/usr/local/cuda-10.1`

```
$ ls -ld /usr/local/cuda*
/usr/local/cuda -> /etc/alternatives/cuda
/usr/local/cuda-11 -> /etc/alternatives/cuda-11
/usr/local/cuda-11.1
/usr/local/cuda-11.3
/usr/local/cuda-11.4
/usr/local/cuda-11.7
/usr/local/cuda-11.8
/usr/local/cuda-12 -> /etc/alternatives/cuda-12
/usr/local/cuda-12.0
$ ls -ld /etc/alternatives/cuda
/etc/alternatives/cuda -> /usr/local/cuda-11.7
```

You can either change the symlink on your system to a later toolkit or specify to cmake the location like so 

```
$ cmake -DCUDAToolkit_ROOT=/usr/local/cuda-11.7 -S . -B cmake-build
``` 

See the [DEV.md](https://github.com/nanoporetech/dorado/blob/master/DEV.md) for more details.

**Comment by isabelluo** [comment]
Hi @iiSeymour 

I tried your suggestion and it did not work for me. I think I might have to re-navigate my problem. please help me with it
First of all, our computer is using ubuntu 20.04, and the cuda is installed under /usr/lib/cuda. 
However, when I tried the both creating links or specify cmake location the following are the returns:
----------------------------------------------------------------------------------------
(base) garcialab@VET-188-47KZZQ3:~/dorado$ /usr/lib/cuda -> /etc/alternatives/cuda
-bash: /etc/alternatives/cuda: Permission denied
(base) garcialab@VET-188-47KZZQ3:~/dorado$ /usr/lib/cuda-11 -> /etc/alternatives/cuda-11
-bash: /etc/alternatives/cuda-11: Permission denied
---------------------------------------------------------------------------------------------
$ cmake -DCUDAToolkit_ROOT=/usr/lib/cuda-11.7 -S . -B cmake-build
-- Build type: 
-- Submodule update
CMake Error at cmake/UpdateSubmodules.cmake:10 (file):
  file

    "/home/garcialab/dorado/cmake.lock"

  creation failed (check permissions).
Call Stack (most recent call first):
  cmake/UpdateSubmodules.cmake:25 (git_submodule_update)
  CMakeLists.txt:18 (include)


-- Configuring incomplete, errors occurred!
See also "/home/garcialab/dorado/cmake

-build/CMakeFiles/CMakeOutput.log".
See also "/home/garcialab/dorado/cmake-build/CMakeFiles/CMakeError.log".

--------------------------------------------------------------------------------------------------------

I am not sure if I misunderstood you or if I did anything wrong. pl
ease let me know if I did!
I also tried to look at the log file and it seems like the problem is with GNU linker, but I am so confused there.... 
therefore, I decided to attach my log files that the computer wants me to look at.  perhaps this can help. 

Thank you so much for your response. 

[CMakeError.log](https://github.com/nanoporetech/dorado/files/10785387/CMakeError.log)

[CMakeOutput.log](https://github.com/nanoporetech/dorado/files/10785388/CMakeOutput.log)

**Comment by iiSeymour** [comment]
Can you double check you can run `nvcc` with:

````
/usr/lib/cuda-11.7/bin/nvcc --version
````

You seem to be getting  permission issues after using `chmod`. I would suggest deleting `/home/garcialab/dorado` and checking out a fresh copy. If the `nvcc` check above is successful I believe  `cmake -DCUDAToolkit_ROOT=/usr/lib/cuda-11.7 -S . -B cmake-build` should work on your fresh checkout.

**Comment by isabelluo** [comment]
Hi @iiSeymour 

This is what I got with the command
/usr/lib/cuda-11.7/bin/nvcc --version
-bash: /usr/lib/cuda-11.7/bin/nvcc: No such file or directory

so no it is not successful. 
or should I go ahead and delete dorado first then to the nvcc check? 
or what do you mean by the term " checking out" a fresh copy of  /home/garcialab/dorado after deleting it. 

appreciate your help

**Comment by iiSeymour** [comment]
The default location is normally `/usr/local` not `/usr/lib`. Can you post the output of `ls -ld /usr/local/cuda*` and `ls -ld /usr/lib/cuda*`.

> what do you mean by the term " checking out

A fresh `git clone`.

**Comment by isabelluo** [comment]
$ ls -ld /usr/local/cuda*
ls: cannot access '/usr/local/cuda*': No such file or directory

$ ls -ld /usr/lib/cuda*
drwxr-xr-x 6 root root 4096 Dec  8 15:53 /usr/lib/cuda

Here they are. Yes, I did check about the default cuda location. what I found is that Ubuntu 20.04 has a different default location for cuda.

**Comment by iiSeymour** [comment]
Are you sure ` /usr/lib/cuda` is a cuda-toolkit installation? Can you run ` /usr/lib/cuda/bin/nvcc --version` and `which nvcc` and post the output.

If you have `sudo` rights then `sudo rm -rf dorado` should do it, if not clone the repository in a different location.

**Comment by isabelluo** [comment]
$  /usr/lib/cuda/bin/nvcc --version
-bash: /usr/lib/cuda/bin/nvcc: No such file or directory
$ which nvcc
/usr/bin/nvcc

Should nvcc be under cuda bin? is this the problem?

**Comment by iiSeymour** [comment]
and I assume the `/usr/bin/nvcc --version` show cuda 10.1? You'll need to _(additionally)_ install the cuda 11.7 toolkit if you want to build dorado.

Alternatively, you can just download and run the pre-compiled release: [dorado-0.2.1-linux-x64](https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.2.1-linux-x64.tar.gz)

**Comment by isabelluo** [comment]
Yes it does return cuda 10.1.  sorry I forgot to mention that. 
So the cuda version is the problem for all the error?

**Comment by iiSeymour** [comment]
You only need a cuda toolkit _(11.7)_ if you want to build dorado from source.

You can download and run dorado just like guppy from the link below. 

https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.2.1-linux-x64.tar.gz

**Comment by isabelluo** [comment]
okay I am sorry if this sounds dumb. 
So I downloaded Dorado from the link you provided. Extracted the tar.gz. file and put it right under my home directory....
Then I typed in dorado download and -help and everything, but it returns with "command not found"
Is there anything else I should do to get it ready?
I wonder if I have to change the .bashrc to let it search for a path or create a link for the command or something.

**Comment by iiSeymour** [comment]
You can either put `/home/garcialab/dorado/dorado-0.2.1/bin` on your `$PATH` or use a relative or absolute path to the executable like so:

```
$ ./dorado-0.2.1/bin/dorado                       # relative path from ~
$ ~garcialab/dorado-0.2.1/bin/dorado     # abs path from any location
```

**Comment by isabelluo** [comment]
thank you @iiSeymour 
I finally got it configured and started to run. 
However, I still think there are some issue with the CUDA device.  There might be multiple others but these are the ones that I have found so far. The following are my commands and returns
The first error showed that CUDA is not found and I wonder if this has anything to do with the default location for this particular program thinking where CUDA should be at. In our case, CUDA is at /usr/bin/ not like the others. 

The second question I have would be that I would like dorado to base call file by file and generate one to one fastq files. and there are specific directories I want the output to be saved. Since the error is saying that the file does not exist, do I need to create the directories prior to basecalling? or there is a command for me to specify one-to-one output?  I think for most of the program, it should be okay to redirect the output save path though. 

---------------
trying to emit a fastq outputs 
---------------
$ dorado basecaller --min-qscore 7 --emit-fastq --device cuda:auto dna_r9.4.1_e8_hac@v3.3 1/*pod5 > call.fastq
[2023-02-21 10:48:54.839] [info] > Creating basecall pipeline
[2023-02-21 10:48:54.865] [error] CUDA device requested but no devices found.

######
-----------------
trying to specify output directory
-----------------
$ dorado basecaller --min-qscore 7 --emit-fastq --device cuda:auto dna_r9.4.1_e8_hac@v3.3 1/*pod5 > fastq/call.fastq
-bash: fastq/call.fastq: No such file or directory
______________

**Comment by isabelluo** [comment]
@iiSeymour 
Thank you it did work 
Just to make sure, there are no demultiplexing options for dorado at this point right?

**Comment by iiSeymour** [comment]
@isabelluo glad to hear! Yes, that is correct.

**Comment by isabelluo** [comment]
@iiSeymour  
But in an updated dorado versions, would the demultiplexing options got added ?
and on the terminal dorado did output that how many reads were basecalled and how many reads did not pass the q-score screening. 
For the purpose of monitoring, can I have these basecalling summaries saved  in a document somehow? like set a flag or something?
