### ISSUE TITLE
dorado 0.8.0 ignoring models-directory parameter

### ISSUE THREAD

**Issue by lsterck** [nanoporetech/dorado#1030]
# Issue Report

When running the new dorado version it seems that it ignores both the --models-directory cmdline parameter as well as the DORADO_MODELS_DIRECTORY env var .

## Please describe the issue:

dorado stops with error "Model path does not exist at: '<some model>' - Please download the model or use a model complex.
I expect it looks for the models in the specified directory, which exists and holds all the models.

## Run environment:
- Dorado version: 0.8.0+acec121
- Dorado command: dorado basecaller --models-directory /db/models/ dna_r10.4.1_e8.2_400bps_sup@v4.3.0 ./pod5/
- Operating system: LINUX 
- Hardware (CPUs, Memory, GPUs): 
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.):  pod5
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

dorado basecaller --models-directory /db/models/ dna_r10.4.1_e8.2_400bps_sup@v4.3.0 ./pod5/ -v
[2024-09-20 11:19:50.521] [info] Running: "basecaller" "--models-directory" "/db/models/" "dna_r10.4.1_e8.2_400bps_sup@v4.3.0" "./pod5/" "-v"
[2024-09-20 11:19:50.653] [debug] set models directory to: '/db/models'
[2024-09-20 11:19:50.653] [error] Model path does not exist at: 'dna_r10.4.1_e8.2_400bps_sup@v4.3.0' - Please download the model or use a model complex
[2024-09-20 11:19:50.653] [error] finalise() not called on a HtsFile.

**Comment by HalfPhoton** [comment]
Can you add the output from the trace logging using `-vv`  please?

**Comment by lsterck** [comment]
Hi,
sure, no problem here it is :
`ls /db/models/dna_r10.4.1_e8.2_400bps_sup@v4.3.0/`
0.conv.bias.tensor    4.rnn.bias_hh_l0.tensor    5.rnn.weight_hh_l0.tensor  7.rnn.bias_hh_l0.tensor    8.rnn.weight_hh_l0.tensor
0.conv.weight.tensor  4.rnn.bias_ih_l0.tensor    5.rnn.weight_ih_l0.tensor  7.rnn.bias_ih_l0.tensor    8.rnn.weight_ih_l0.tensor
1.conv.bias.tensor    4.rnn.weight_hh_l0.tensor  6.rnn.bias_hh_l0.tensor    7.rnn.weight_hh_l0.tensor  9.linear.weight.tensor
1.conv.weight.tensor  4.rnn.weight_ih_l0.tensor  6.rnn.bias_ih_l0.tensor    7.rnn.weight_ih_l0.tensor  config.toml
2.conv.bias.tensor    5.rnn.bias_hh_l0.tensor    6.rnn.weight_hh_l0.tensor  8.rnn.bias_hh_l0.tensor
2.conv.weight.tensor  5.rnn.bias_ih_l0.tensor    6.rnn.weight_ih_l0.tensor  8.rnn.bias_ih_l0.tensor

(that /db/models/ has been populated by running `dorado download --model all` )


`dorado basecaller --models-directory /db/models/ dna_r10.4.1_e8.2_400bps_sup@v4.3.0 ./pod5/ -vv`

[2024-09-20 17:54:30.448] [info] Running: "basecaller" "--models-directory" "/db/models/" "dna_r10.4.1_e8.2_400bps_sup@v4.3.0" "./pod5/" "-vv"
[2024-09-20 17:54:30.453] [trace] Model option: 'dna_r10.4.1_e8.2_400bps_sup@v4.3.0' unknown - assuming path
[2024-09-20 17:54:30.566] [debug] set models directory to: '/db/models'
[2024-09-20 17:54:30.566] [error] Model path does not exist at: 'dna_r10.4.1_e8.2_400bps_sup@v4.3.0' - Please download the model or use a model complex
[2024-09-20 17:54:30.566] [error] finalise() not called on a HtsFile.

**Comment by HalfPhoton** [comment]
Ah of course - you're using a model name (path) not a model complex. 
> Model option: 'dna_r10.4.1_e8.2_400bps_sup@v4.3.0' unknown - assuming path

If you use the model complex `sup@v4.3.0` it should resolve automatically as described in the readme:

> #### Model search directory and temporary model downloads
> Once the automatic model selection process has found the appropriate model given the input data, it will search for existing model directories to avoid downloading models unnecessarily. The behaviour of this search can be controlled as follows: ...

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
> 👍 

Hopefully that's the issue resolved 🤞 

Best regards,
Rich

**Comment by lsterck** [comment]
indeed it does !!! (tested and works)

so when providing the model on cdmline, never include the dna...bps_ part thus.

thanks for the swift reply and resolving this
(and apologies for overlooking that from my side)

**Comment by HalfPhoton** [comment]
No worries, it should have been clearer in the documentation / error message too.

Happy basecalling!
