### ISSUE TITLE
Unknown certs location for current distribution - Dorado v0.8.0

### ISSUE THREAD

**Issue by juanjo255** [nanoporetech/dorado#1031]
Hello developers!

I downloaded the new Dorado V0.8.0 but I am facing problems when trying to download models. they download fine, but when running` dorado basecaller`. It finds the models (`[debug] - matching modification model found: dna_r10.4.1_e8.2_400bps_sup@v5.0.0_5mCG_5hmCG@v2`), but it always print this warning: `[warning] Unknown certs location for current distribution. If you hit download issues, use the envvar `SSL_CERT_FILE` to specify the location manually.` and then tries to download the model again. This is problematic because clusters cannot download anything, therefore the run fails.

I downloaded models in this way and it works with curl, I also tried to download the model in zip manually using the link, but the problem persists.
`dorado download --model dna_r10.4.1_e8.2_400bps_sup@v5.0.0_5mCG_5hmCG@v2`

I hope you can help me,

Thank you very much,

Juan.

**Comment by HalfPhoton** [comment]
Hi Juan, 

I'm a bit confused by your description - but it looks like the automatic model downloader for the mods model is failing on the cluster. because they have no external access.

Can you try this instead:

Download all the models into a `models` directory which is shared on the cluster from your machine with internet access.

`dorado download --models all --models-directory /path/to/models`

The use the same `--models-directory /path/to/models/` argument in your `dorado basecaller` command on the cluster. This should search the `models` directory and not need to download them again.

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
@juanjo255 has this resolved your issue?

**Comment by juanjo255** [comment]
Hello!

Thanks for the answer!

The problem is that I can download my models into a directory as usual, and I give this path to dorado, the problem is that Dorado tries to download it again after this warning` [warning] Unknown certs location for current distribution. If you hit download issues, use the envvar SSL_CERT_FILE to specify the location manually `

**Comment by HalfPhoton** [comment]
Can you share your dorado command and the verbose logging output `-vv` to show this error?

Thanks

**Comment by juanjo255** [comment]
Sure!

This is the command:
`dorado basecaller --min-qscore 7 --trim adapters --modified-bases 5mCG_5hmCG --device "cpu"  -vv  ~/biocomp_tools/dorado_models/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 pod5/ `

To clarify:
1. Only to reproduce the error I set the CPU (I actually run in GPU).
2. I gave a empty pod5 folder just to make it fail, but when I give a folder with pod5 it starts correctly. The problem is with the model path, it is correct, but as you can see at the beginning it downloads the model again.
[dorado.log](https://github.com/user-attachments/files/17098933/dorado.log)

Thanks for the help!

Juan

**Comment by HalfPhoton** [comment]
As I said in the original reply - you need to use the `--models-directory` argument to re-use downloaded models.

The following should work;

Use a model complex and models-directory;
````bash
dorado download --model all --models-directory  ~/biocomp_tools/dorado_models/
dorado basecaller \
     --min-qscore 7 --trim adapters --device "cpu"  -vv \
     --models-directory  ~/biocomp_tools/dorado_models/ \
     sup@v4.1.0,5mCG_5hmCG  pod5/ 
````

Please note; v5.1.0 models are available for this condition in dorado v.0.8.0: 
Replace `sup@v4.1.0,5mCG_5hmCG` with `sup,5mCG_5hmCG` to use the latest models.

Or - specify the paths to both models directly

```bash
dorado basecaller  \
   --min-qscore 7 --trim adapters   --device "cpu"  -vv \ 
   --modified-bases-models ~/biocomp_tools/dorado_models//dna_r10.4.1_e8.2_400bps_sup@v5.0.0_5mCG_5hmCG@v1/ \
   ~/biocomp_tools/dorado_models/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 pod5/
```

Rich

**Comment by juanjo255** [comment]
It worked!

Thank you very much!

Juan
