### ISSUE TITLE
Dorado correct for R9 data

### ISSUE THREAD

**Issue by asan-emirsaleh** [nanoporetech/dorado#1032]
Hello!
Thank you for you efforts in developing open-source tools for genome data analyses.

I am looking for the best workflow with r9.4.1 data (I have only this kind of data).
Can I use experimental r9.4.1 model from HERRO project for `dorado correct`? Is the r10.4.1 model compatible with r9.4.1 data? And finally, can I use the output of `vechat` with `dorado correct` and the r10.4.1 model?

Can you please provide me with some information when the dorado team plan to release the r9.4.1 model for `dorado correct` pipeline?

Best regards
Asan

**Comment by HalfPhoton** [comment]
Hi @asan-emirsaleh, 
Continuing from this [previous issue](https://github.com/nanoporetech/dorado/issues/921). 

To answer your questions;
> Can I use experimental r9.4.1 model from HERRO project for `dorado correct`?

To the best of my knowledge we have not tested the experimental r9.4.1 model and have done no verification if it does or does not work. Please feel free to give it a try and let us know what happens, but at this time we don't support the experimental R9.4.1 model in dorado correct.

> Is the r10.4.1 model compatible with r9.4.1 data?

No, they will not be compatible as the error profiles will be different between the two conditions.

> And finally, can I use the output of `vechat` with `dorado correct` and the r10.4.1 model?

I don't know - I'm not familiar with `vechat` - This question might be best placed for the Nanopore community 

> Can you please provide me with some information when the dorado team plan to release the r9.4.1 model for dorado correct pipeline?

We currently don't plan to add support for the R9.4.1 condition / models in `dorado correct`.

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
@asan-emirsaleh, have your questions been answered satisfactorily / is this issue resolved?

Kind regards,
Rich

**Comment by asan-emirsaleh** [comment]
Thank you a lot. My questions were partially resolved.
I have an empirical view on the question about r9.4.1 models. There are a lot of labs that have sequenced their objects on R9 pore flow-cells, and still did not published their results because of lack of data (sequencing depth was not sufficient for problem resolving), of pure quality of the data, of shortcomings with analyses etc. I have no any statistics, but I guess that the majority of non-human-related data that were produced to date by ONT long read sequencing belongs to the r9.4.1 pores. Especially it is in relation to complex eucaryotic genomes. So I don't understand why the ONT team do not prioritize models for legacy r9.4.1 data. If a lineage of much more accurate models for r9.4.1 would have been presented (for basecalling, duplex data processing, correction and polishing), the amount of finished and published genomic projects would also been increased. And, consequently, it the would increase the trust to the abilities of technology to resolve complex cases. Off course, human genomics is the major use case, but the analyses of non-model and complex genomes is the cutting-edge of genomics that broads our understanding of what the life is.

I have two questions in relation `dorado`. The first is, is `dorado correct` used r10.4.1 model identical to that from the `HERRO` project? Are they both in the same format etc? Can it be used?
And the second is, can the r9.4.1 model from the `HERRO` project be used with `dorado correct`? I understand that it was not tested. The question is, is it possible from technical point of view?

Thank you for your attention to this topic on objectively discontinued lineage.
Best regards
Asan

**Comment by HalfPhoton** [comment]
Hi Asan, 

> Is dorado correct used `r10.4.1` model identical to that from the HERRO project? Are they both in the same format etc? Can it be used?

Yes - at this time the models are the exact same.

> Can the r9.4.1 model from the HERRO project be used with dorado correct? I understand that it was not tested. The question is, is it possible from technical point of view?

Yes - Technically it's possible - I can't see anything in the HERRO codebase that suggests that they're different models which is encouraging.

Rich

**Comment by asan-emirsaleh** [comment]
Hello @HalfPhoton !
I followed the idea to try `dorado correct` with r9.4.1 data. I used the model from `HERRO` supplimentary. But the `dorado` expects some metadata or configs to be present:
```
[error] Caught exception: toml::parse: file open error -> /scratch/emirsaleh-cc_g/_apps/dorado/models/model_R9_v0.1.pt/config.toml
```
Could you please suggest how can I convert or modify the HERRO model to make it usable for `dorado`?

**Comment by HalfPhoton** [comment]
Dorado expects a `config.toml` in the model directory - Try using the one from the dorado downloaded r10.4 HERRO model assuming that it's the same architecture.
