### ISSUE TITLE
How does basecaller trim RNA reads that did not detect polyA ？

### ISSUE THREAD

**Issue by Yang990-sys** [nanoporetech/dorado#1034]
As stated in the title，I‘m curious about it. Is the adapter for undetected polyA reads not trimmed ?

**Comment by malton-ont** [comment]
Hi @Yang990-sys,

Dorado looks for a characteristic change in signal between the adapter and the RNA sequence. If it detects this, that section of the signal is trimmed away prior to basecalling. This is independent of whether polyA estimation is requested.

See [here](https://github.com/nanoporetech/dorado/blob/release-v0.8/dorado/read_pipeline/ScalerNode.cpp#L62) for the algorithm used.
