### ISSUE TITLE
Dorado `--models-directory` requires write permissions

### ISSUE THREAD

**Issue by lsterck** [nanoporetech/dorado#1035]
Hi,

apparently this issue has not been completely resolved for me :/ 
The part where one specifies the model to be used in combination with the models-directory parameter (or env var) is OK when providing it as you mentioned in issue #1030 
however, when one uses the fast, hac or sup approach it still seems to ignore the models-directory parameter (or env var) and thus tries to download the appropriate model again, though that model is already available in the specified directory and would therefore not need to be downloaded again (according to the manual) ... 

related to (or follow-up) of #1030

**Comment by HalfPhoton** [comment]
Can you share the commands you used and the log output please?

**Comment by lsterck** [comment]
sure ....

[info] Running: `"basecaller" "--device" "cuda:all" "--no-trim" "--recursive" "--models-directory" "/db/dorado/models/" "fast" "./pod5"`
[trace] 'fast' found variant: 'fast' and version: 'latest'
[debug] set models directory to: '/db/dorado/models'
[trace] POD5: ./pod5/test_1.pod5 flowcell_code: 'FLO-MIN114' sequencing_kit: 'SQK-RBK114-96' sample_rate: 5000
[trace] POD5: ./pod5/test.pod5 flowcell_code: 'FLO-MIN114' sequencing_kit: 'SQK-RBK114-96' sample_rate: 5000
[trace] Searching for: chemistry: dna_r10.4.1_e8.2_400bps_5khz, model_variant: fast
[trace] Reject dna_r10.4.1_e8.2_400bps_hac@v4.2.0 on model type: fast
[trace] Reject dna_r10.4.1_e8.2_400bps_sup@v4.2.0 on model type: fast
[trace] Reject dna_r10.4.1_e8.2_400bps_hac@v4.3.0 on model type: fast
[trace] Reject dna_r10.4.1_e8.2_400bps_sup@v4.3.0 on model type: fast
[trace] Reject dna_r10.4.1_e8.2_400bps_hac@v5.0.0 on model type: fast
[trace] Reject dna_r10.4.1_e8.2_400bps_sup@v5.0.0 on model type: fast
[trace] Found 3 model matches:
[trace] - dna_r10.4.1_e8.2_400bps_fast@v4.2.0
[trace] - dna_r10.4.1_e8.2_400bps_fast@v4.3.0
[trace] - dna_r10.4.1_e8.2_400bps_fast@v5.0.0
[trace] Searching for: chemistry: dna_r10.4.1_e8.2_400bps_5khz, model_variant: fast
[trace] Reject dna_r10.4.1_e8.2_400bps_hac@v4.2.0 on model type: fast
[trace] Reject dna_r10.4.1_e8.2_400bps_sup@v4.2.0 on model type: fast
[trace] Reject dna_r10.4.1_e8.2_400bps_hac@v4.3.0 on model type: fast
[trace] Reject dna_r10.4.1_e8.2_400bps_sup@v4.3.0 on model type: fast
[trace] Reject dna_r10.4.1_e8.2_400bps_hac@v5.0.0 on model type: fast
[trace] Reject dna_r10.4.1_e8.2_400bps_sup@v5.0.0 on model type: fast
[trace] Found 3 model matches:
[trace] - dna_r10.4.1_e8.2_400bps_fast@v4.2.0
[trace] - dna_r10.4.1_e8.2_400bps_fast@v4.3.0
[trace] - dna_r10.4.1_e8.2_400bps_fast@v5.0.0
[error] Insufficient permissions to download models into /db/dorado/models
[error] Failed to prepare model download directory
[error] finalise() not called on a HtsFile.

looking into the models dir, the following subdirs are present :
'/db/dorado/models/dna_r10.4.1_e8.2_400bps_fast@v4.0.0'/
'/db/dorado/models/dna_r10.4.1_e8.2_400bps_fast@v4.1.0'/
'/db/dorado/models/dna_r10.4.1_e8.2_400bps_fast@v4.2.0'/ 
'/db/dorado/models/dna_r10.4.1_e8.2_400bps_fast@v4.3.0'/ 
'/db/dorado/models/dna_r10.4.1_e8.2_400bps_fast@v5.0.0'/

**Comment by HalfPhoton** [comment]
```
[error] Insufficient permissions to download models into /db/dorado/models
```

Do you have read / write permission in the `--models-directory` from your cluster?

You can test this with 

```bash
TEST_PATH="/db/dorado/models/tmp.txt"
touch $TEST_PATH
echo "test" >> $TEST_PATH
cat $TEST_PATH
rm $TEST_PATH
```

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
It looks like dorado is checking it has write permissions before it really needs them [here](https://github.com/nanoporetech/dorado/blob/acec121e438099741b690d49c7bff4bf25e1851c/dorado/utils/fs_utils.cpp#L71-L77).

**Comment by lsterck** [comment]
Hi ,

well yes and no 😄 
I can write in that folder but not with the user I use to run dorado itself.
That models directory is sort of closed of for 'normal' users as they should not write in it. The content is centrally maintained by the bioIT team. 
I kinda figured that would be (part of) the issue here. 

I understand and agree that you should check the permissions, question is if it has to check it even if it would not need them, right? 😉

**Comment by HalfPhoton** [comment]
Yeah it should only need read-only until it actually needs to write to this is a bug on our end.

So the issue should be resolved in the meantime if you add RW permission for the cluster "user" for that directory while we get this fixed.

Best regards,
Rich

**Comment by lsterck** [comment]
Hi,

Goh, a 'bug' is perhaps a bit strong wording , let's just say there is room for improvement 😉 
OK, great I'll work around it for the time being.

thanks,
L.

**Comment by HalfPhoton** [comment]
A fix for this issue will be available in an upcoming release and it will  be noted in the changelog / release notes so hopefully you can drop the work-around.

As this isn't blocking you anymore I'll close this ticket. 

Thanks for making us aware of this issue.

Best regards,
Rich
