### ISSUE TITLE
Can dorado demux based on the presence/absence of an adapter sequence?

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/dorado#1036]
# Issue Report

## Please describe the issue:

I have aligned/basecalled pod5->bams that I want to demultiplex into two files based on the presence/absence of a specific adapter sequence at the beginning of the read. Can I use dorado demux with custom barcodes to do this? When I read the documentation it seems to support demuxing based on barcodes flanked by constant sequences, but I'm not sure if it's capable of doing something like presence/absence of a specific sequence.

## Run environment:
- Dorado version: v0.8.0
- Dorado command: dorado demux
- Operating system: Linux
- Hardware (CPUs, Memory, GPUs): A100/H100
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5

**Comment by malton-ont** [comment]
Hi @billytcl,

No, dorado does not have any specific facility to demux based on the adapters. You could try just aligning to the adapter sequences. Alternatively, if the adapter is long enough you could split it into two or three sections and use these as the mask and a single barcode for a custom barcode arrangement, but this is untested.
