### ISSUE TITLE
dorado basecaller has duplicate command line flag -o

### ISSUE THREAD

**Issue by lucast122** [nanoporetech/dorado#1037]
# Issue Report

## Please describe the issue:

dorado basecaller uses the flag -o twice once for output folder and once for overlap. Output folder can only be defined using --output-dir though.

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

`dorado basecaller -o sample/ dna_r10.4.1_e8.2_400bps_fast@v5.0.0 .`
gives
[2024-09-25 15:03:12.156] [error] Failed to parse 'a' as decimal integer: pattern 'a' not found

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment: 
- Dorado version: 0.8.0+acec121
- Dorado command: dorado basecaller -o a dna_r10.4.1_e8.2_400bps_fast@v5.0.0 .
- Operating system: Ubuntu20
- Hardware (CPUs, Memory, GPUs): ryzen threadripper, 512GB RAM, NVIDIA RTX3070Ti
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location (on device or networked drive - NFS, etc.): device
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB):
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by HalfPhoton** [comment]
@lucast122 , thanks for raising this issue. We'll get this fixed. 

Best regards,
Rich

**Comment by malton-ont** [comment]
Thanks for your patience. This issue is resolved in dorado 0.9.0.
