### ISSUE TITLE
std::bad_alloc error

### ISSUE THREAD

**Issue by haghani-sara** [nanoporetech/dorado#1039]
I'm trying to basecall my pod5 files on our linux remote server, but I keep getting the same std::bad_alloc error. The run starts but then shortly stops and all I get is an empty output bam file. Not sure if it's relevant, but I'm submitting the script to our PBS Pro job scheduler. I've checked with system admin and resource requests are within limit. Wondering if there is something wrong with the program? Please let me know if I should provide any additional details. Thank you in advance!

## Run environment:
- Dorado version: dorado-0.8.0-linux-x64
- Dorado command: 

#!/bin/bash

#PBS -N dorado
#PBS -l select=1:ncpus=64:mem=250gb:ngpus=1
#PBS -l walltime=144:00:00
#PBS -q gpu
#PBS -j oe

REFERENCE="/data/tehbt/home/gmsv2194/reference"
DORADO_PATH="/data/tehbt/home/gmsv2194/install/dorado-0.8.0-linux-x64/bin"
MODEL="$PBS_O_WORKDIR/models/dna_r10.4.1_e8.2_400bps_hac@v5.0.0"

"$DORADO_PATH/dorado" basecaller --models-directory "$MODEL" --modified-bases 5mC_5hmC ./pod5_files --reference "$REFERENCE/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna" > dorado.bam

- Operating system: Linux ln-vm-02 5.14.0-362.8.1.el9_3.x86_64
- Hardware: drive version 550.90.07 and CUDA version 12.4 (ncpus=125, mem=256gb, max walltime of 240:00:00, Nvidia A100 GPU)
- Source data type: pod5

## Logs

>$DORADO_PATH/dorado basecaller --device auto --models-directory [models/dna_r10.4.1_e8.2_400bps_hac@v5.0.0](mailto:models/dna_r10.4.1_e8.2_400bps_hac@v5.0.0) --reference $REFERENCE/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna --modified-bases 5mC_5hmC pod5_files/PAW88681_8ab3ad6b_4e7dcd9d_1.pod5  >/data/rozen/home/gmsywss/temp_folder/dorado.bam
[2024-09-25 18:10:27.064] [info] Running: "basecaller" "--device" "auto" "--models-directory" ["models/dna_r10.4.1_e8.2_400bps_hac@v5.0.0"](mailto:models/dna_r10.4.1_e8.2_400bps_hac@v5.0.0) "--reference" "/data/tehbt/home/gmsv2194/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna" "--modified-bases" "5mC_5hmC" "pod5_files/PAW88681_8ab3ad6b_4e7dcd9d_1.pod5"
[*** LOG ERROR #0001 ***] [2024-09-25 18:10:27] [] std::bad_alloc

**Comment by HalfPhoton** [comment]
Hi @haghani-sara,

Your command is malformed - specifically you're not setting the positional arguments for the model **and** data correctly.

The first problem is your use of the `--models-directory` argument. It's for use with the automatic model selection via the [model complex](https://github.com/nanoporetech/dorado?tab=readme-ov-file#automatic-model-selection-complex) arguments and not for setting the model path directly.

What's happening is that the  `--models-directory $MODEL` is setting the model path as the **search** directory for your models and not _actually_ setting the model. 

The second issue is that `--modified-bases` takes a space-separated list of modbase codes to which you've passed: `5mC_5hmC ./pod5_files` - Note that your intended input data directory has been consumed by this argument.

This leaves no positional arguments left for both model and data which I suspect is causing the crash.

To fix the first issue please try:

```bash
{PBS STUFF}
...

DATA="./pod5_files"
REFERENCE="/data/tehbt/home/gmsv2194/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
DORADO_PATH="/data/tehbt/home/gmsv2194/install/dorado-0.8.0-linux-x64/bin/dorado"

MODELS_DIR="$PBS_O_WORKDIR/models"
MODEL_HAC_V5="$MODELS_DIR/dna_r10.4.1_e8.2_400bps_hac@v5.0.0"
MODBASES="5mC_5hmC"

$DORADO_PATH basecaller $MODEL_HAC_V5 $DATA \
  --models-directory $MODELS_DIR \
  --modified-bases $MODBASES \
  --reference $REFERENCE \
  > dorado.bam
```

Alternatively using the model selection complex:

```bash
$DORADO_PATH basecaller hac@v5.0.0,5mC_5hmC $DATA \
  --models-directory $MODELS_DIR \
  --reference $REFERENCE \
  > dorado.bam

```

I hope this helps

Best regards,
Rich

**Comment by HalfPhoton** [comment]
@haghani-sara, is your issue resolved?

**Comment by KunFang93** [comment]
Hi,

I encountered same error
```
(base) kfang@icrc4lcga001:~/data/kfang/NucPatternOri/ONTdata$ ls
dna_r10.4.1_e8.2_400bps_hac@v5.0.0  flowcells  lambda7KM_Nano_Control.fast5.tar.gz  lambda7KM_Nano_proteinA_EcoGII.bam  lambda7KM_Nano_proteinA_EcoGII.fast5  lambda7KM_Nano_proteinA_EcoGII.fast5.tar.gz  lambda.fa.fasta
(base) kfang@icrc4lcga001:~/data/kfang/NucPatternOri/ONTdata$ dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v5.0.0/ lambda7KM_Nano_proteinA_EcoGII.fast5/ --models-directory dna_r10.4.1_e8.2_400bps_hac@v5.0.0/ --modified-bases hac,6mA --reference lambda.fa.fasta -r --trim > lambda7KM_Nano_proteinA_EcoGII.bam
[2024-09-27 20:58:15.544] [info] Running: "basecaller" "dna_r10.4.1_e8.2_400bps_hac@v5.0.0/" "lambda7KM_Nano_proteinA_EcoGII.fast5/" "--models-directory" "dna_r10.4.1_e8.2_400bps_hac@v5.0.0/" "--modified-bases" "hac,6mA" "--reference" "lambda.fa.fasta" "-r" "--trim"
[*** LOG ERROR #0001 ***] [2024-09-27 20:58:15] [] std::bad_alloc
(base) kfang@icrc4lcga001:~/data/kfang/NucPatternOri/ONTdata$ dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v5.0.0/ lambda7KM_Nano_proteinA_EcoGII.fast5/ --models-directory ./ --modified-bases hac,6mA --reference lambda.fa.fasta -r --trim > lambda7KM_Nano_proteinA_EcoGII.bam
[2024-09-27 20:59:37.729] [info] Running: "basecaller" "dna_r10.4.1_e8.2_400bps_hac@v5.0.0/" "lambda7KM_Nano_proteinA_EcoGII.fast5/" "--models-directory" "./" "--modified-bases" "hac,6mA" "--reference" "lambda.fa.fasta" "-r" "--trim"
[*** LOG ERROR #0001 ***] [2024-09-27 20:59:37] [] std::bad_alloc
```
I wondered if you could shed some light on it? Thanks in advance!

Best,
Kun

**Comment by haghani-sara** [comment]
> Hi @haghani-sara,
> 
> Your command is malformed - specifically you're not setting the positional arguments for the model **and** data correctly.
> 
> The first problem is your use of the `--models-directory` argument. It's for use with the automatic model selection via the [model complex](https://github.com/nanoporetech/dorado?tab=readme-ov-file#automatic-model-selection-complex) arguments and not for setting the model path directly.
> 
> What's happening is that the `--models-directory $MODEL` is setting the model path as the **search** directory for your models and not _actually_ setting the model.
> 
> The second issue is that `--modified-bases` takes a space-separated list of modbase codes to which you've passed: `5mC_5hmC ./pod5_files` - Note that your intended input data directory has been consumed by this argument.
> 
> This leaves no positional arguments left for both model and data which I suspect is causing the crash.
> 
> To fix please try:
> 
> ```shell
> {PBS STUFF}
> ...
> 
> DATA="./pod5_files"
> REFERENCE="/data/tehbt/home/gmsv2194/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
> DORADO_PATH="/data/tehbt/home/gmsv2194/install/dorado-0.8.0-linux-x64/bin/dorado"
> 
> MODELS_DIR="$PBS_O_WORKDIR/models"
> MODEL_HAC_V5="$MODELS_DIR/dna_r10.4.1_e8.2_400bps_hac@v5.0.0"
> MODBASES="5mC_5hmC"
> 
> $DORADO_PATH basecaller $MODEL_HAC_V5 $DATA \
>   --models-directory $MODELS_DIR \
>   --modified-bases $MODBASES \
>   --reference $REFERENCE \
>   > dorado.bam
> ```
> 
> Alternatively using the model selection complex:
> 
> ```shell
> $DORADO_PATH basecaller hac,5mC_5hmC $DATA \
>   --models-directory $MODELS_DIR \
>   --reference $REFERENCE \
>   > dorado.bam
> ```
> 
> I hope this helps
> 
> Edit: If your PBS cluster doesn't have internet access - please download the models you require into `$MODELS_DIR` manually.
> 
> ```shell
> dorado download --models all --models-directory $MODELS_DIR
> ```
> 
> Best regards, Rich

Hi @HalfPhoton,

Thank you so much for your quick reply and providing the correct code! I let it run over the weekend and I now have an output bam file and basecalling process is marked as "finished". Really appreciate it :)

Best,
Sara

**Comment by malton-ont** [comment]
@KunFang93,

Your `--modified-bases` parameter is incorrect. Firstly, it should contain only the modifications, not the model type `--modified-bases 6mA`. Secondly, it must be the last parameter in the command.

Your use of the `--models-directory` parameter is also incorrect - this should specify the location to search for the models, not a model itself.

If you intend to use a model complex and directory, do not specify the model path itself nor the `--modified-bases` parameter - just add the model complex on its own:
```
dorado basecaller \
    hac,6mA \
    lambda7KM_Nano_proteinA_EcoGII.fast5/ \
    --models-directory <location of downloaded models> \
    --reference lambda.fa.fasta \
    -r \
    --trim
```

**Comment by KunFang93** [comment]
I tried the following command but all failed... 
```
(base) kfang@icrc4lcga001:~/data/kfang/NucPatternOri/ONTdata$ ls
dna_r10.4.1_e8.2_400bps_hac@v5.0.0  lambda7KM_Nano_Control.fast5.tar.gz  lambda7KM_Nano_proteinA_EcoGII.fast5         lambda.fa.fasta  test1.bam  test.bam
flowcells                           lambda7KM_Nano_proteinA_EcoGII.bam   lambda7KM_Nano_proteinA_EcoGII.fast5.tar.gz  output_01.pod5   test2.bam
(base) kfang@icrc4lcga001:~/data/kfang/NucPatternOri/ONTdata$ dorado basecaller hac,6mA lambda7KM_Nano_proteinA_EcoGII.fast5/batch101.fast5 --models-directory ./ --reference lambda.fa.fasta --trim
[2024-09-30 15:14:08.625] [info] Running: "basecaller" "hac,6mA" "lambda7KM_Nano_proteinA_EcoGII.fast5/batch101.fast5" "--models-directory" "./" "--reference" "lambda.fa.fasta" "--trim"
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot automate model selection using fast5 files
Aborted (core dumped)
(base) kfang@icrc4lcga001:~/data/kfang/NucPatternOri/ONTdata$ dorado basecaller hac,6mA lambda7KM_Nano_proteinA_EcoGII.fast5/batch101.fast5 --models-directory dna_r10.4.1_e8.2_400bps_hac@v5.0.0/ --reference lambda.fa.fasta --trim
[2024-09-30 15:14:20.371] [info] Running: "basecaller" "hac,6mA" "lambda7KM_Nano_proteinA_EcoGII.fast5/batch101.fast5" "--models-directory" "dna_r10.4.1_e8.2_400bps_hac@v5.0.0/" "--reference" "lambda.fa.fasta" "--trim"
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot automate model selection using fast5 files
Aborted (core dumped)
(base) kfang@icrc4lcga001:~/data/kfang/NucPatternOri/ONTdata$ dorado basecaller hac,6mA lambda7KM_Nano_proteinA_EcoGII.fast5/batch101.fast5 --models-directory dna_r10.4.1_e8.2_400bps_hac@v5.0.0 --reference lambda.fa.fasta --trim
[2024-09-30 15:14:28.957] [info] Running: "basecaller" "hac,6mA" "lambda7KM_Nano_proteinA_EcoGII.fast5/batch101.fast5" "--models-directory" "dna_r10.4.1_e8.2_400bps_hac@v5.0.0" "--reference" "lambda.fa.fasta" "--trim"
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot automate model selection using fast5 files
Aborted (core dumped)
```
I wondered how could I solve it? Thanks so much!

Best,
Kun

**Comment by KunFang93** [comment]
This seems works
```
(base) kfang@icrc4lcga001:~/data/kfang/NucPatternOri/ONTdata$ dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v5.0.0 lambda7KM_Nano_proteinA_EcoGII.fast5/batch101.fast5 --modified-bases 6mA --trim --reference lambda.fa.fasta > test2.bam
[2024-09-30 15:19:06.925] [info] Running: "basecaller" "dna_r10.4.1_e8.2_400bps_hac@v5.0.0" "lambda7KM_Nano_proteinA_EcoGII.fast5/batch101.fast5" "--modified-bases" "6mA" "--trim" "--reference" "lambda.fa.fasta"
[2024-09-30 15:19:07.066] [info]  - downloading dna_r10.4.1_e8.2_400bps_hac@v5.0.0_6mA@v2 with httplib
[2024-09-30 15:19:07.448] [info] Normalised: chunksize 10000 -> 9996
[2024-09-30 15:19:07.448] [info] Normalised: overlap 500 -> 498
[2024-09-30 15:19:07.448] [info] > Creating basecall pipeline
[2024-09-30 15:19:07.452] [error] finalise() not called on a HtsFile.
[2024-09-30 15:19:07.452] [error] Sample rate for model (5000) and data (4000) are not compatible.
```
Thanks!

**Comment by malton-ont** [comment]
> Cannot automate model selection using fast5 files

We recommend converting your data to the [pod5 format](https://pypi.org/project/pod5/). If you cannot do this for some reason, you cannot use the model complex or `--models-directory` and so must fix the order of your arguments.

```
dorado basecaller \
    <path_to_your_hac_model> \
    lambda7KM_Nano_proteinA_EcoGII.fast5/batch101.fast5 \
    --reference lambda.fa.fasta \
    --trim \
    --modified-bases 6mA
```

> Sample rate for model (5000) and data (4000) are not compatible.

Your data is sampled at 4kHz - you will need to use the v4.1 or earlier models.
