### ISSUE TITLE
Dorado v0.8 for modified base calling runs slow

### ISSUE THREAD

**Issue by shogohlab** [nanoporetech/dorado#1040]
I tried running dorado v0.8 basecaller with modified base detection:
dorado basecaller --modified-bases-models rna004_130bps_sup@v5.1.0_m6A_DRACH@v1 > test_output.bam hac test.pod5 

This was scheduled to take 38 days to finish basecalling/mod-calling a ~13M reads pod5 file generated using FLO-PRO004RA:SQK-RNA004:130. 

I repeated the same basecalling/mod-calling but only with the 1st 5,000 reads and the output looks correct. This one took 20minutes. 

Is dorado v0.8 modified base detection and base calling supposed to take this long?

**Comment by HalfPhoton** [comment]
Without hardware information we can't help you determine if 38 days is unusual.

**Comment by shogohlab** [comment]
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    2
Core(s) per socket:    32
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 106
Model name:            Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz
Stepping:              6
CPU MHz:               3199.951
CPU max MHz:           3200.0000
CPU min MHz:           800.0000
BogoMIPS:              4000.00
Virtualization:        VT-x
L1d cache:             48K
L1i cache:             32K
L2 cache:              1280K
L3 cache:              49152K

**Comment by shogohlab** [comment]
## Run environment:
- Dorado version: 0.8.0
- Dorado command:  dorado basecaller --modified-bases-models rna004_130bps_sup@v5.1.0_m6A_DRACH@v1 > test_output.bam hac test.pod5
- Operating system: Red Hat Enterprise Linux Server 7.9 (Maipo)
- Hardware (CPUs, Memory, GPUs): CPUs = 128, Memory= 1056078360 kB, Nvidia A100-80G GPU

- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location (on device or networked drive - NFS, etc.): on device
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): FLO-PRO004RA:SQK-RNA004:130; ~13M reads; pod5 size of 446Gb

**Comment by shogohlab** [comment]
Hi @HalfPhoton , here are the logs below (this time taking up to 7 days). Additionally, based on the dorado "Performance tips" on https://github.com/nanoporetech/dorado, should I be altering some GPU selection parameters before I run dorado?

/usr/local/bin/miniconda3/bin/dorado-0.8.0-linux-x64/bin/dorado basecaller --modified-bases-models /home/rna004_130bps_sup@v5.1.0_m6A_DRACH@v1 > LSG1272_basecalled.bam hac /home/nanopore/_raw_data/pass.pod5 & 
[1] 10352
[sho@localhost ~]$ [2024-09-29 09:28:40.270] [info] Running: "basecaller" "--modified-bases-models" "/home/sho/rna004_130bps_sup@v5.1.0_m6A_DRACH@v1" "hac" "/home/nanopore/_raw_data/pass.pod5"
[2024-09-29 09:28:40.468] [warning] Unknown certs location for current distribution. If you hit download issues, use the envvar `SSL_CERT_FILE` to specify the location manually.
[2024-09-29 09:28:40.470] [info]  - downloading rna004_130bps_hac@v5.1.0 with httplib
[2024-09-29 09:28:49.056] [error] Failed to download rna004_130bps_hac@v5.1.0: SSL server verification failed
[2024-09-29 09:28:49.056] [info]  - downloading rna004_130bps_hac@v5.1.0 with curl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.9M  100 14.9M    0     0  1410k      0  0:00:10  0:00:10 --:--:-- 2123k
[2024-09-29 09:29:00.140] [info] > Creating basecall pipeline
[2024-09-29 09:29:00.143] [info]  - BAM format does not support `U`, so RNA output files will include `T` instead of `U` for all file types.
^C                             ] 0% [00m:50s<07d:14h:31m:17s] Basecalling

**Comment by malton-ont** [comment]
Hi @shogohlab,

This looks like you are running on CPU rather than GPU. Your logs are missing some lines that I would expect to see regarding the batch size selection, e.g.:
```
[2024-09-30 11:18:30.104] [info] cuda:0 using chunk size 9996, batch size 5760
[2024-09-30 11:18:30.197] [info] cuda:0 using chunk size 4998, batch size 8320
```
* Can you confirm that your system is equipped with supported Nvidia GPUs? You said A100 above, which should work
* Are you running on a cluster where you need to explicitly request GPUs to be allocated to the job?
* What is the output from `nvidia-smi`?
* What is the output if you add `-x cuda:0` to your command?

**Comment by malton-ont** [comment]
@shogohlab, do you have any updates on this?

**Comment by shogohlab** [comment]
There is something wrong with our GPU and I'm trying to reconfigure it before running dorado again

**Comment by shogohlab** [comment]
@malton-ont , it was indeed something wrong with the GPU not being properly installed. After fixing that, the same analysis finishes in 2.5hr.
