### ISSUE TITLE
how to perform downstream analysis of poly(A) length (pt:i tag)?

### ISSUE THREAD

**Issue by JhinJhinJhin** [nanoporetech/dorado#1043]
# Issue Report
sorry, It's not issue. I just want some advice about downstream analysis of dorado output.

How to use the output of dorado for poly(A) length analysis?

Is there any software like nanopolish that can do this?

**Comment by malton-ont** [comment]
Hi @JhinJhinJhin,

This question is probably better asked on the Nanopore community.
