### ISSUE TITLE
Use of Methylation Models and Subsequent Analysis

### ISSUE THREAD

**Issue by Taylorain** [nanoporetech/dorado#1049]
# Issue Report
I am currently working on analyzing RNA methylation modifications using DRS data and DNA methylation modifications using ONT data. However, I have encountered several questions that I would greatly appreciate your insights on.

## Please describe the issue:
1. **Modified Bases Models**: Can I use multiple models simultaneously with the `--modified-bases-models` option in my command?
2. **Methylation Information in BAM Files**: Does the methylation information reside in the `mv` column of the generated BAM files? For instance, I see values like `mv:B:c,5,1,0,...` — do these represent methylation status?
3. **Software for Extraction and Visualization**: What software do you recommend for extracting methylation modification information and performing visualization analysis?
4. **Basecalling and Alignment**: Many articles mention that after basecalling, the data should be aligned to a reference genome using `minimap2`. Should I extract sequence information from the BAM files for this alignment? How can I integrate the alignment information with the BAM file that contains methylation modification data?

## Steps to reproduce the issue:
```
dorado basecaller \
  -x cuda:0 \
  --estimate-poly-a \
  --verbose \
  --emit-moves \
  --min-qscore 7 \
  --reference /home/reference/genomic.fna_revise \
  -k 15 \
  --emit-sam \
  --modified-bases-models /home/software/dorado/model/rna004_130bps_sup@v5.1.0 \
  /home/software/dorado/model/rna004_130bps_sup@v5.1.0_inosine_m6A@v1 \
   /home/software/dorado/model/rna004_130bps_sup@v5.1.0_m5C@v1 \
    /home/software/dorado/model/rna004_130bps_sup@v5.1.0_m6A_DRACH@v1 \
     /home/software/dorado/model/rna004_130bps_sup@v5.1.0_pseU@v1 \
  /bio/data_BC202406118-BN240605QD02S41N1/pod5/LM_0_1+2+3/pod5_pass/ | \
samtools view -h -@ 60 | \
awk 'BEGIN {OFS="\t"} {if ($1 ~ /^@/ || length($10) >= 50) print}' | \
samtools view -b -@ 60 -o /sup_drs/0_A.filtered.bam
```

## Run environment:
- Dorado version: 0.8.0+acec121
- Operating system: `Linux  6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC x86_64 GNU/Linux`
- Source data type ：pod5

Thank you for your time and assistance. I look forward to your guidance.

**Comment by Taylorain** [comment]
here is an example of one of the entries from the resulting BAM file:
a00d18d1-87eb-4c16-b28c-d25ed0a81da9    16      CM062196.1      6306    60      16S90M1I88M2D8M1I9M1D4M1D63M3I85M2I53M2D11M1D65M        *       0       0             TTTTTTTTTTTTTTTTTACATCACAAGTTTTCCATAAACACATTTATTAGTGAATTCACAGTCCAACATCACAATGAAGCTGCAATTCAAAAACAACATACAAATGAAAAAAAGCAGAGACAATAAACAATTAGTACACCTAAAATGGTTTCAGTTTCTGTCTGTTACCTGCACATCAGGTGGTTTTAACCTGGATCATTTGTAAAAAACATGAATGAATCTCTTCTTTCTTCCTGCAGAAACTCCACAAACTGCATGTGACCTGGAGCCCTGGCTTCTATGGTGAGCATATTGGCCCACACAGCTGTCATTCACCTAACACTCAGGACAGGTCAGCATCTACACAGCTCAGAGATGATTCTTCTACATGTGAACCACTTCTTTTGTTTATCATTTCATTCTGTAAGATAAACCTTTAATAATTATTTAATATATTTAATGGCTGTTAGTGAGTTTCCCATGCAGTTCAATAAAAAACTGTGTCATTCAATGTTTCTTT       $'()*-0135789::96:87:::20../0712>==?;=9A?<;<;<<9:::470-55765000-----==;;52+''''./97;;>>?>>3<9;775512224>;=<63.,---,1111434442346:===<?@@>>=30/00()28:<<?>?>2??FC=;89889932((((((/226.-2223*(:;:941+%$%'*62,**''()*-874'%&'-++89;;;@@A9==?>::?:9::=:::::ACDDBACBBEC;677>><;@==;:;<<>BA?/+**((''(*-/889:744;<<;99<=>=>??@E;??@@=A@@CC@B?@A@>@@@AAB<?@7;(''&&&&&(((24:9<<?DDB:<=.---,)$##$(-468;>;:67:<=;AA<><?A@@@<=<;;77768<;)::6;<<;::;<:*'),687:778<(?>>::<<<?==7343488.6*))))24336<:84/-*)++,44445;<;>>>;;:980733       qs:f:13.5987    du:f:4.01475    ns:i:16059      ts:i:1900       mx:i:1  ch:i:2123             st:Z:2024-07-03T11:44:55.025+00:00      rn:i:50775      fn:Z:20240702-DRS1287-PAU71353-P03.pass.pod5    sm:f:80.1507    sd:f:16.9074    sv:Z:quantile         dx:i:0  RG:Z:efa9c862de3ba4fffb2a6bf2925237c0d796b9c4_rna004_130bps_sup@v3.0.1  mv:B:c,5,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,1,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,1,0,0,0,1,1,1,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0,1,1,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0  pt:i:48 MN:i:499        MM:Z:A+a?,5,3,4,3,2,27,17,4,36,4,1,3,2,13,12;   ML:B:C,0,0,0,0,17,0,0,0,0,0,6,2,0,0,0 NM:i:18 ms:i:868        AS:i:864        nn:i:0  de:f:0.0268041  tp:A:P  cm:i:30 s1:i:327        s2:i:0  MD:Z:99A78^AG0C16^A4^A121T79^TA11^T38G26      rl:i:14

My purpose is to  analyzethe different methylation modifications(especially m6A) using DRS data(rna004 kit)
Hope you don't mind us asking here about methylation model.

**Comment by malton-ont** [comment]
Hi @Taylorain,

1. Yes, you can run multiple models simultaneously, as long as they target modifications of different canonical bases. So you cannot run `inosine_m6A` and `m6A_DRACH` together, but you can run `pseU` and/or `inosine_m6A` and/or `m5C`. The easiest way to do this is to specify a model complex rather than the model paths: e.g. `sup,pseU,inosine_m6A,m5C`
2. The `mv` tag contains the model stride and move table - see the [docs, here](https://github.com/nanoporetech/dorado/blob/release-v0.8/documentation/SAM.md). Modification information is stored in the `MM` and `ML` tags as per the [SAM specification](https://samtools.github.io/hts-specs/SAMtags.pdf).

Your other questions are better asked on the Nanopore Community forums.

**Comment by Taylorain** [comment]
Thanks pretty much!
