### ISSUE TITLE
--emit-fastq?

### ISSUE THREAD

**Issue by itslittman** [nanoporetech/dorado#105]
is --emit-fastq supposed to create a fastq file in addition to the sam file as basecalling output? It doesn't seem like it does anything, at least on Mac.

noah

**Comment by iiSeymour** [comment]
Hey @itslittman the default output is unaligned SAM but `--emit-fastq` changes the output to fastq _(it's not in addition)_.

**Comment by itslittman** [comment]
@iiSeymour oh okay
Noah
