### ISSUE TITLE
Basecalling on non-NVIDIA GPUs - 

### ISSUE THREAD

**Issue by markcharder** [nanoporetech/dorado#1050]
# Issue Report

## Please describe the issue:

I am aware that there is no plan to support dorado on AMD GPUs, e.g. [I](https://github.com/nanoporetech/dorado/issues/952), so I am sorry to raise this issue again here. I am only raising it because basecalling is a significant bottleneck for us, as the main GPU resource we have is a super-computer with AMD GPUs, and we are starting to produce hundreds of quite large genome sequencing data with the P2 (which is awesome!).

I have managed to convert all of the CUDA calls in the dorado source code to AMD-compatible [HIP](https://github.com/ROCm/HIP) calls, using [hipify](https://github.com/ROCm/HIPIFY/blob/amd-staging/README.md) and some manual editing. The package should be compilable for AMD GPUs, but I have discovered that it requires koi, which is only released as a pre-compiled binary based on CUDA source code. Again, I understand this _may_ be [made open-source](https://github.com/nanoporetech/dorado/issues/20), but it is not clear when.

I was wondering if there was any chance of an update on the timeline for open-source release of koi and/or a private distribution under a different agreement, so that I can make this workable on our cluster. If possible, it would be good to get an idea of whether any of the dorado-associated code would likely fail on AMD GPUs, even if CUDA calls are translated to HIP.

Any help would be greatly appreciated!

Thanks a lot for your time.
Mark

**Comment by vellamike** [comment]
Hi Mark,

The code in koi is very low level and not suited to hipification - open sourcing it wouldn't help. Adapting Dorado to run on AMD GPUs would require a ROCm implementation written by hand.  While this is something we are in the early stages of considering, I'm afraid it won't be within a time scale which would be useful to you.

If you are generating data on a P2 Solo your best bet for now is a desktop computer with a NVIDIA GPU in it.

Best wishes,
Mike

**Comment by markcharder** [comment]
Hi Mike,

Thank you very much for the quick response. It is good to know this, as it will save me time trying to compile on non-NVIDIA GPUs. I look forward to seeing an ROCm version, if/when it is available.

All the best,

Mark

**Comment by hasindu2008** [comment]
@markcharder You may try slorado for AMD GPU basecalling: https://github.com/BonsonW/slorado/
