### ISSUE TITLE
Question re. basecalling correction

### ISSUE THREAD

**Issue by li-xuyang28** [nanoporetech/dorado#1056]
## Question/inquiry:

I am sequencing a duplex mutagenesis library of average fragment size ~1.4kb, where there are invariant/constant regions (200bp 5' and 400bp 3'). I was wondering if it is possible to correct base calling or base call with a strong prior based on those regions with dorado? Thanks!

**Comment by HalfPhoton** [comment]
Hi @li-xuyang28, 

This question is probably best placed in the nanopore community forum as it's a bioinformatics question not a dorado issue. 

However, I don't believe dorado correct will be helpful in this case as your fragment sizes (~1.4kb) are too short - dorado correct has a minimum context size of 10kb.

Best regards,
Rich
