### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by SynBioExplorer** [nanoporetech/dorado#106]
Hi,

Sorry if this is an obvious question, but is there some kind of step by step tutorial on how to use dorado? I have downloaded the installer and tried opening the exec file unsuccessfully.  When calling dorado in the terminal, e.g. dorado download --model dna_r10.4.1_e8.2_260bps_hac@v4.1.0, I get a dorado not found answer. 

Might be a pretty stupid question, hope that is okay and thanks in advance

**Comment by iiSeymour** [comment]
Hi @SynBioExplorer if dorado isn't on your `$PATH` you need to specify the relative (or absolute) path to it. 

```
./dorado download --model dna_r10.4.1_e8.2_260bps_hac@v4.1.0
```

**Comment by SynBioExplorer** [comment]
Thank you @iiSeymour. When I added the location to $Path and tried to re run it, I still have trouble finding the other libraries. 
```
library not loaded: /opt/homebrew/opt/zstd/lib/libzstd.1.dylib
  Referenced from: <6885E217-2FDF-3065-B6F7-E287694A9EFA> /Users/username/bin/dorado
  Reason: tried: '/opt/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/opt/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/usr/local/lib/libzstd.1.dylib' (no such file), '/usr/lib/libzstd.1.dylib' (no such file, not in dyld cache)
```

Should I unpack each of the files in bin, hdf5 and lib ?

**Comment by iiSeymour** [comment]
@SynBioExplorer can you `brew install hdf5 zstd`?

**Comment by SynBioExplorer** [comment]
Hi @iiSeymour,
I installed hdf5 zstd via brew but when trying to run ./dorado download --model dna_r10.4.1_e8.2_260bps_hac@v4.1.0:

`./dorado download --model dna_r10.4.1_e8.2_260bps_hac@v4.1.0 
dyld[10249]: Library not loaded: @rpath/libtorch.dylib
  Referenced from: <6885E217-2FDF-3065-B6F7-E287694A9EFA> /Users/MQ46079823/dorado
  Reason: tried: '/Users/MQ46079823/libtorch.dylib' (no such file), '/Users/lib/libtorch.dylib' (no such file), '/Users/MQ46079823/libtorch.dylib' (no such file), '/Users/lib/libtorch.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libtorch.dylib' (no such file), '/Users/MQ46079823/libtorch.dylib' (no such file), '/Users/lib/libtorch.dylib' (no such file), '/Users/MQ46079823/libtorch.dylib' (no such file), '/Users/lib/libtorch.dylib' (no such file), '/usr/local/lib/libtorch.dylib' (no such file), '/usr/lib/libtorch.dylib' (no such file, not in dyld cache)
zsh: abort      ./dorado download --model dna_r10.4.1_e8.2_260bps_hac@v4.1.0
`

Should I just copy all download files into the /opt/homebrew/opt/  or do I have to unpack them somehow?

**Comment by iiSeymour** [comment]
@SynBioExplorer it looks like you have moved the `dorado` executable into `/Users/MQ46079823` without the dorado `lib` directory.

```
% tree releases/dorado-0.2.1-osx-arm64/      
releases/dorado-0.2.1-osx-arm64/
├── bin
│   └── dorado
├── hdf5
│   └── lib
│       └── plugin
│           └── libvbz_hdf_plugin.a
└── lib
    ├── default.metallib
    ├── libc10.dylib
    ├── libshm.dylib
    ├── libtorch.dylib
    ├── libtorch_cpu.dylib
    ├── libtorch_global_deps.dylib
    └── libtorch_python.dylib
```

**Comment by SynBioExplorer** [comment]
Hi Chris,

Thanks for the help. 
I now got it to work, I had to:

`brew install openssl
brew link openssl --force
brew install libtorch
brew link libtorch 
brew install libaec

and then 
cd /path/to/dorado
chmod +x ./dorado
./dorado`

No clue why, but maybe this helps someone in the future who is also on an apple silicon Macs.
