### ISSUE TITLE
command works on 0.7.0 but error in 0.8.0

### ISSUE THREAD

**Issue by abcdtree** [nanoporetech/dorado#1061]
Hi,

# Issue Report
The same command below works well in 0.7.0, but will return error in 0.8.0
```
dorado basecaller ${model_home}/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 ${data_home}/pod5 --estimate-poly-a --kit-name SQK-PCB114-24 > my.bam

##error message
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Trim interval 118-93 is invalid for sequence TGTTATTGTACTGTACTTGGTTCAGTTATTTTGTGTATGCAAACGATATTAGAGGAAGAGTGAGCACCGTGACAACTAGGCACAGCGAGTCTCGTTTTCTGCTTGGTGCTGGATCTGCTGAACTC
/var/spool/slurm/job66442714/slurm_script: line 30: 114723 Aborte
```

## Run environment:
- Dorado version: 0.8.0
- Dorado command: dorado basecaller ${model_home}/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 ${data_home}/pod5 --estimate-poly-a --kit-name SQK-PCB114-24 > my.bam

my purpose is to test the difference on polyA tail estimation from version 0.7.0 and 0.8.0, anything I need to change for 0.8.0?

Thanks

Josh

**Comment by malton-ont** [comment]
This appears to be the same as #1020, please follow that issue for updates.
