### ISSUE TITLE
Demux removes alignment positions

### ISSUE THREAD

**Issue by mmb78** [nanoporetech/dorado#1062]
Using the dorado-0.8.0-win64; I run basecaller with alignment and to classify the sequences I provide the kit code:
dorado basecaller fast pod5s\ --no-trim --reference genome.fa --kit-name SQK-RBK114-24 > call_align_fast.bam

lines in a "summary" output look like this:
FAZ57604_df3a4e9c_a1bd6646_0.pod5	106c4643-0a94-41a5-abd7-25ef1aa15fb2	a1bd6646e45e4c969a0a443432f18df6d81f595b	83	1	44.985	1.9366	44.987	1.9346	822	12.3559	SQK-RBK114-24_barcode10	genome	21643	22334	124	820	+	706	681	671	15	10	10	60	0.846715	0.985316	0.950425	0

Then I generate individual BAM files for each barcode:
dorado.exe demux --kit-name SQK-RBK114-24 --sort-bam --no-trim --output-dir Demux\ call_align_fast.bam

and I get a line that looks like this for the same sequence as above; position on the genome is lost:
FAZ57604_df3a4e9c_a1bd6646_0.pod5	106c4643-0a94-41a5-abd7-25ef1aa15fb2	a1bd6646e45e4c969a0a443432f18df6d81f595b	83	1	44.985	1.9366	44.987	1.9346	822	12.3559	SQK-RBK114-24_barcode10	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0

**Comment by malton-ont** [comment]
Hi @mmb78,

As you've already classified the reads during basecalling, you should run demux with `--no-classify` rather than with `--kit-name`. This should retain alignment information.

**Comment by mmb78** [comment]
Thanks a lot!! I totally missed this option!
Best,
M
