### ISSUE TITLE
Demux pod5s into pod5s

### ISSUE THREAD

**Issue by jorisbalc** [nanoporetech/dorado#1066]
Greetings,

Is it possible to conveniently demux pod5s into pod5s separated by barcodes? Is there some function or the only workaround is to basecall them by demuxing and reverse extract the reads from pod5s via lists extracted from the bam format?

thanks in advance

**Comment by malton-ont** [comment]
Hi @jorisbalc,

Dexmuxing the pod5 requires knowing which barcode applies to which read. This will require basecalling and demuxing. Once you have a list of which read_ids are associated with which barcodes, you will want to look into `pod5 filter` from https://pypi.org/project/pod5/.
