### ISSUE TITLE
Dorado customer barcode demultiplex 

### ISSUE THREAD

**Issue by GingingYJ** [nanoporetech/dorado#1073]
# Issue Report
I have 4 forward and reverse paired barcodes. I try to demultiplex it. But it only gave me 2 barcode file.
Can someone help me to generate 4 demultiplexed .fastq files? Does dorado have the function of demultiplexing with paired barcodes and paired primers at the same time? Or it can only demultiplex single barcode? 

## Please describe the issue:
#This is my primer:
ATCGCCTACCGTGACAGAGTTTGATCMTGGCTCAG
ATCGCCTACCGTGACCGGTTACCTTGTTACGACTT

#This is my barcode:
forward_barcode reverse_barcode sample_name
AAGAAAGTTGTCGGTGTCTTTGTG     CACAAAGACACCGACAACTTTCTT     Marsh1_1
AAGAAAGTTGTCGGTGTCTTTGTG     ACAGACGACTACAAACGGAATCGA     Marsh1_2
TCGATTCCGTTTGTAGTCGTCTGT     CACAAAGACACCGACAACTTTCTT     Marsh1_3
TCGATTCCGTTTGTAGTCGTCTGT     ACAGACGACTACAAACGGAATCGA     Marsh1_4

#This is my primer + barcode in the sequence:
Primer_Barcode_F	Primer_Barcode_R	samle_name
ATCGCCTACCGTGACAAGAAAGTTGTCGGTGTCTTTGTGAGAGTTTGATCMTGGCTCAG	ATCGCCTACCGTGACAAGAAAGTTGTCGGTGTCTTTGTGCGGTTACCTTGTTACGACTT	Marsh1_1
ATCGCCTACCGTGACAAGAAAGTTGTCGGTGTCTTTGTGAGAGTTTGATCMTGGCTCAG	ATCGCCTACCGTGACTCGATTCCGTTTGTAGTCGTCTGTCGGTTACCTTGTTACGACTT	Marsh1_2
ATCGCCTACCGTGACTCGATTCCGTTTGTAGTCGTCTGTAGAGTTTGATCMTGGCTCAG	ATCGCCTACCGTGACAAGAAAGTTGTCGGTGTCTTTGTGCGGTTACCTTGTTACGACTT	Marsh1_3
ATCGCCTACCGTGACTCGATTCCGTTTGTAGTCGTCTGTAGAGTTTGATCMTGGCTCAG	ATCGCCTACCGTGACTCGATTCCGTTTGTAGTCGTCTGTCGGTTACCTTGTTACGACTT	Marsh1_4

# Based on my primer + barcode information, this is my **arrangement.toml** file:
[arrangement]
name = "custom_barcode"
kit = "SQK-LSK114"

mask1_front = "ATCGCCTACCGTGAC" 
mask1_rear = "AGAGTTTGATCMTGGCTCAG" 
mask2_front = "ATCGCCTACCGTGAC" 
mask2_rear = "AGAGTTTGATCMTGGCTCAG" 

barcode1_pattern = "BC%02i"
barcode2_pattern = "BC%02i"
first_index = 1
last_index = 4 

[[barcodes]]
name = "Marsh1_1"
leading_flank_1 = "LEADING_FLANK_1_SEQUENCE"
barcode_1 = "AAGAAAGTTGTCGGTGTCTTTGTG"
trailing_flank_1 = "AAGAAA"
trailing_flank_2 = "TTTGTG"
barcode_2 = "CACAAAGACACCGACAACTTTCTT"
leading_flank_2 = "TTTCTT"

[[barcodes]]
name = "Marsh1_2"
leading_flank_1 = "LEADING_FLANK_1_SEQUENCE"
barcode_1 = "AAGAAAGTTGTCGGTGTCTTTGTG"
trailing_flank_1 = "AAGAAA"
trailing_flank_2 = "TTTGTG"
barcode_2 = "ACAGACGACTACAAACGGAATCGA"
leading_flank_2 = "AATCGA"

[[barcodes]]
name = "Marsh1_3"
leading_flank_1 = "LEADING_FLANK_1_SEQUENCE"
barcode_1 = "TCGATTCCGTTTGTAGTCGTCTGT"
trailing_flank_1 = "AAGAAA"
trailing_flank_2 = "TTTGTG"
barcode_2 = "CACAAAGACACCGACAACTTTCTT"
leading_flank_2 = "TTTCTT"

[[barcodes]]
name = "Marsh1_4"
leading_flank_1 = "LEADING_FLANK_1_SEQUENCE"
barcode_1 = "TCGATTCCGTTTGTAGTCGTCTGT"
trailing_flank_1 = "AAGAAA"
trailing_flank_2 = "TTTGTG"
barcode_2 = "ACAGACGACTACAAACGGAATCGA"
leading_flank_2 = "AATCGA"

[scoring]
min_soft_barcode_threshold = 0.2
min_hard_barcode_threshold = 0.2
min_soft_flank_threshold = 0.3
min_hard_flank_threshold = 0.3
min_barcode_score_dist = 0.1

# Here are my code:
dorado basecaller fast pod5/   --no-trim > NMPT_test.bam
dorado demux --barcode-arrangement arrangement.toml --emit-fastq --output-dir NMPT_test.bam

# Here are my output files:
1449434712 custom_barcode_barcode01.fastq
1373705644 custom_barcode_barcode02.fastq
5376227984 unclassified.fastq

## Run environment:
- Dorado version: 0.7.1
- Dorado command: dorado demux --barcode-arrangement arrangement.toml --emit-fastq --output-dir NMPT_test.bam
- Operating system: linux slarm
- Hardware (CPUs, Memory, GPUs): CPUs
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): bam

**Comment by malton-ont** [comment]
@GingingYJ,

You seem to have attempted to put the barcodes overrides into the arrangement file. I'm not clear where you got the suggestion for `[[barcodes]]` sections from, but this is incorrect - custom barcode sequences should be specified in a separate `.fasta` file and passed to dorado using the `--barcode-sequences` parameter.

I suggest reading the [custom barcode documentation](https://github.com/nanoporetech/dorado/blob/release-v0.8/documentation/CustomBarcodes.md) first. Note in particular that the `mask2_*` values should be the reverse complement of the sequence as it appears in the forward strand, and the available options for the `[scoring]` section.
