### ISSUE TITLE
Where to find new run_id field added in front of dorado demux outputs

### ISSUE THREAD

**Issue by RxLoutre** [nanoporetech/dorado#1077]
# Issue Report

## Please describe the issue:

Dear dorado team,

I have a snakemake pipeline that wraps dorado basecaller, demux and aligner.

I was fearing when I saw this in the release notes :

_Add run_id to filenames output by demux_

And indeed it makes my rule demux fail, as usually I would expect {alias}.bam, and now it is {run_id}_{alias}.bam.

Can you share with me a command that allows me to find this run_id from the pod5 ? I assume some command of pod5 format ?

Best,

Roxane

**Comment by HalfPhoton** [comment]
Hi @RxLoutre, can can use pod5 view to see the run_id: `pod5 view data.pod5 --include "run_id"`

However can use a wildcard expression in your snakemake pipeline to match ```*_{alias}.bam``` instead? It might be easier and more efficient.

**Comment by RxLoutre** [comment]
It does sounds like my problem is trivial, but it is not solved as easily as you suggest, sadly.

Thank you for the command using pod5.

By any chance, is this the same as the field : "acquisition_run_id" in the final_summary.txt file ?

Best,

Roxane

**Comment by RxLoutre** [comment]
PS : Or is it "protocol_run_id" ?

**Comment by HalfPhoton** [comment]
I'm not familiar especially familiar with the summary file output but I believe it is `acquisition_run_id`:

For info: the following are field descriptions taken from the pod5 [run_info](https://github.com/nanoporetech/pod5-file-format/blob/master/docs/tables/run_info.toml) table specifications.

```toml
[fields.acquisition_id] # This is the same as `run_id` in the reads table 
type = "utf8"
description = "A unique identifier for the run (acquisition). This is the same identifier that MinKNOW uses to identify an acquisition within a protocol."

[fields.protocol_run_id]
type = "utf8"
description = "A unique identifier for the protocol run that produced this data."

**Comment by RxLoutre** [comment]
Insightful, thank you ! I think I should be able to find a workable solution for my pipeline now.

thanks !

**Comment by RxLoutre** [comment]
Are you sure that dorado demux use run_id ?

the output of the pod5 command to get the run_id : 
```

pod5 view pod5/PAW45416_466c7e42_cf63ff3b_0.pod5 --include "run_id" | head -2 | tail -1
466c7e42-a3e3-4f7b-9676-e0912870c2ee

```
The outputs of dorado demux : 
```
cf63ff3be0a0c4705250b7780b749be0ed7e523a_ctrl4.bam
cf63ff3be0a0c4705250b7780b749be0ed7e523a_ctrl2.bam
cf63ff3be0a0c4705250b7780b749be0ed7e523a_unclassified.bam
cf63ff3be0a0c4705250b7780b749be0ed7e523a_ctrl3.bam
cf63ff3be0a0c4705250b7780b749be0ed7e523a_ctrl1.bam
```

Which actually corresponds to the acquisiton_id according to the file final_summary : 

```
cat final_summary_PAW45416_466c7e42_cf63ff3b.txt
instrument=P2S-02334-A
position=
flow_cell_id=PAW45416
sample_id=NobertM-s2
protocol_group_id=202406-035
protocol=sequencing/sequencing_PRO114_DNA_e8_2_400K:FLO-PRO114M:SQK-PCB114-24:400
protocol_run_id=466c7e42-a3e3-4f7b-9676-e0912870c2ee
acquisition_run_id=cf63ff3be0a0c4705250b7780b749be0ed7e523a
```
Trying to find the corresponding value from pod5 but I am not sure anymore : 

```
pod5 view pod5/PAW45416_466c7e42_cf63ff3b_0.pod5 --include "acquisition_run_id" | head -2 | tail -1

POD5 has encountered an error: '"Field: 'acquisition_run_id' did not match any known fields. Please check it exists by viewing `-L/--list-fields`"'

For detailed information set POD5_DEBUG=1'
(nanopore) [rboyer@athena 20200101_0000_P2S-00867-A_PAQ90736_MPLX]$ pod5 view pod5/PAW45416_466c7e42_cf63ff3b_0.pod5 -L
read_id                      Read UUID
filename                     Source pod5 filename
read_number                  Read number
channel                      1-indexed channel
mux                          1-indexed well
end_reason                   End reason string
start_time                   Seconds since the run start to the first sample of this read
start_sample                 Samples recorded on this channel since run start to the first sample of this read
duration                     Seconds of sampling for this read
num_samples                  Number of signal samples
minknow_events               Number of minknow events that this read contains
sample_rate                  Number of samples recorded each second
median_before                Current level in this well before the read
predicted_scaling_scale      Scale for predicted read scaling
predicted_scaling_shift      Shift for predicted read scaling
tracked_scaling_scale        Scale for tracked read scaling
tracked_scaling_shift        Shift for tracked read scaling
num_reads_since_mux_change   Number of selected reads since the last mux change on this channel
time_since_mux_change        Seconds since the last mux change on this channel
run_id                       Run UUID
sample_id                    User-supplied name for the sample
experiment_id                User-supplied name for the experiment
flow_cell_id                 The flow cell id
pore_type                    Name of the pore in this well
```

**Comment by RxLoutre** [comment]
Hi Rich !

Thanks for the detailed answer. Indeed those solutions are way too far fetched for the solution I am trying to implement in my pipeline 😅 I just went by requesting the final_summary file, and I am grep the acquisition_run_id from there in my init_workflow script, which creates a convenient yaml file to be loaded by the snakemake, so it has less decision do make.

Is there any justification behind adding this run_id in front of the alias name in the outputs ? Don't want to sound old and grumpy but "it was better before" 🤓 

Best,

Roxane

**Comment by HalfPhoton** [comment]
Yes - this came up before from a previous issue with a user who had the same complaint https://github.com/nanoporetech/dorado/issues/1026#issuecomment-2377204920

The justification is that;
> This allows inputs from multiple different runs but of the same barcode kit to be easily identifiable after being demuxed together.

Apologies for the inconvenience here.

Best regards,
Rich

**Comment by RxLoutre** [comment]
Not sure who would like to demux several runs that use the same barcode together though 😅 

But okay understood, praying that the outputs of dorado demux don't change too much next version so people like me (and the other comments), don't have to spend a week testing compatibility with our workflows for each new dorado versions 😉 
Thanks for the quick feedback ! Have a great day !

Best,

Roxane
