### ISSUE TITLE
Dorado RNA Model training data characteristics

### ISSUE THREAD

**Issue by williamphu** [nanoporetech/dorado#1078]
Hi,

I was wondering if there's any description/discussion of the types of data used for training the RNA models—what species, synthetic/non-synthetic, bulk RNA, modification-depleted sequences, etc. Specifically, I was wondering how RNA modifications (and the differences in signal) are handled when training the canonical basecaller.

Thanks.

**Comment by HalfPhoton** [comment]
Hi @williamphu,

We don't share detailed specifications of our training dataset. What I can say is that we include a diverse range of species and preparations to ensure we train robust basecalling models. 

Regarding how we train models to handle modifications in RNA, this was described in my colleague Bronya's presentation from the recent Nanopore Community Meeting which is available to view on youtube: https://youtu.be/9qiClBOx7zQ?feature=shared&t=204

Best regards,
Rich
