### ISSUE TITLE
Question about dorado correct

### ISSUE THREAD

**Issue by tbenavi1** [nanoporetech/dorado#1079]
Hello, I have a question about dorado correct. Can you use both --resume-from and --from-paf at the same time? Thank you.

**Comment by HalfPhoton** [comment]
Yes - you should be able to `--resume-from` and load `--from-paf`. [correct.cpp#L456](https://github.com/nanoporetech/dorado/blob/release-v0.8/dorado/cli/correct.cpp#L456) 

Kind regards,
Rich
