### ISSUE TITLE
Update the running examples to use the current models

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/dorado#108]
Hi

Minor thing but since the 260 bp/s runs have been discontinued it would be great to have the example commands be with the 400 bp/s models.

I also think it would be great to have the full set of commands for running duplex basecalling present on this page rather than referring to the duplex tools page.

Best regards
Rasmus

**Comment by vellamike** [comment]
> Minor thing but since the 260 bp/s runs have been discontinued it would be great to have the example commands be with the 400 bp/s models.

You are right! This will be updated.


> I also think it would be great to have the full set of commands for running duplex basecalling present on this page rather than referring to the duplex tools page.

We are currently working to integrate pairing into Dorado itself, so expect big changes on this front which will be reflected in the Readme.

**Comment by vellamike** [comment]
This is now done.
