### ISSUE TITLE
Replacement for the removed -Y option in dorado v0.8.1

### ISSUE THREAD

**Issue by RxLoutre** [nanoporetech/dorado#1082]
# Issue Report

## Please describe the issue:

Hi ! It's me again (sorry). Encountering issues with using dorado aligner. In a previous issue solving : https://github.com/nanoporetech/dorado/issues/884  @malton-ont advised me to use the -Y option to allow minimap2 for soft-clipping, which I believe is also needed for sniffles2 downstream. I realized this option no longer exists :( 

 Can you help me adjusts the calling parameters of basecaller, demux and aligner so I can get alignment + methylation calls in my final bam outputs files after those 3 commands ? Can I just remove the -Y option ? Or is there more adjustements needed ?

Thanks for your help,

**Basecalling :** 
`dorado basecaller -r sushi/workflow/models/dorado/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 --modified-bases-models sushi/workflow/models/dorado/dna_r10.4.1_e8.2_400bps_sup@v5.0.0_5mC_5hmC@v2.0.1 --sample-sheet Test_dataset/sushi/20200101_0000_P2S-00867-A_PAQ90736_MPLX/sample_sheet_PAW45416_466c7e42_cf63ff3b.csv --kit-name SQK-PCB114-24 Test_dataset/sushi/20200101_0000_P2S-00867-A_PAQ90736_MPLX/pod5 > Test_dataset/sushi/20200101_0000_P2S-00867-A_PAQ90736_MPLX/sushi_test_results/bam/20200101_0000_P2S-00867-A_PAQ90736_MPLX.bam`

**Demux :** 
`dorado demux --output-dir Test_dataset/sushi/20200101_0000_P2S-00867-A_PAQ90736_MPLX/sushi_test_results/demultiplexed --no-classify --sample-sheet Test_dataset/sushi/20200101_0000_P2S-00867-A_PAQ90736_MPLX/sample_sheet_PAW45416_466c7e42_cf63ff3b.csv Test_dataset/sushi/20200101_0000_P2S-00867-A_PAQ90736_MPLX/sushi_test_results/bam/20200101_0000_P2S-00867-A_PAQ90736_MPLX.bam`

**Alignement of one output of dorado demux :** 
`dorado aligner -Y References/human/UCSC/GRCh38/Index/minimap2/hg38.mmi Test_dataset/sushi/20200101_0000_P2S-00867-A_PAQ90736_MPLX/sushi_test_results/bam/20200101_0000_P2S-00867-A_PAQ90736_MPLX_barcode03_ctrl3.bam | samtools sort -@32 - -o Test_dataset/sushi/20200101_0000_P2S-00867-A_PAQ90736_MPLX/sushi_test_results/bam/aligned_barcode03_ctrl3.bam && samtools index -@32 Test_dataset/sushi/20200101_0000_P2S-00867-A_PAQ90736_MPLX/sushi_test_results/bam/aligned_barcode03_ctrl3.bam`

**Comment by malton-ont** [comment]
Hi @RxLoutre,

Minimap2 options should be passed to dorado via the `--mm2-opts` parameter as a single quoted string, e.g.:
```
dorado aligner --mm2-opts "-Y -k 15" <ref> <bam>
```
See https://github.com/nanoporetech/dorado?tab=readme-ov-file#alignment for more details.
