### ISSUE TITLE
Movetable Output for Read that Maps to Reverse Strand

### ISSUE THREAD

**Issue by j-o-song** [nanoporetech/dorado#1083]
Hello, 

I have a quick question about the move table for a read that is mapped to the reverse strand of the reference sequence when using dorado with alignment. Does the move table represent how the raw signals map to the original dna sequence (i.e. not the reverse complemented version that is stored in the bam file)? 

Thank you.

**Comment by HalfPhoton** [comment]
Hi @j-o-song, 

Yes, the move table roughly maps the the dna sequence (not the reference alignment / mapping) onto the raw signal in "strided" space. 

Best regards,
Rich

**Comment by j-o-song** [comment]
Hi @HalfPhoton, thank you for your quick response. 

Does that mean if the beginning of the move table is something like [1,0,0,1,0,1,0], and the original DNA molecule is ACGCAT (reverse complement stored in the output bam file would be ATGCGT), the first 3 "1"s in move table represent ACG and not ATG? 

Thank you.

**Comment by davidnewman02** [comment]
Hi @j-o-song 

You are correct. The move table is generated by the basecaller before any alignment is done so it is in the order that bases moved through the nanopore. There is no further manipulation of the move table during alignment, so it remains in the original molecular direction.

David
