### ISSUE TITLE
Dorado Correct Run Using Reads from R9 Flow Cell

### ISSUE THREAD

**Issue by PhDWannaB1030** [nanoporetech/dorado#1085]
# Issue Report

I ran dorado correct for reads I obtained from an R9 flow cell several months ago and I was recently told that Herro correction should be performed for R9 reads instead. I want to know what the main concern is? If there is a concern about errors created during the correction, how much of an error/error rate?

 Run environment:
- Dorado version: 0.7.1
- Dorado command: 
- ```dorado correct  reads.fastq.gz (bgzipped) > reads.fasta
- Hardware (CPUs, Memory, GPUs): GPUs
- Source data type - pod5 used for Dorado re-basecalling of R9 reads previous to dorado correction

**Comment by HalfPhoton** [comment]
Hi @PhDWannaB1030,

Please check out this previous issue regarding running dorado correct on R9 data: https://github.com/nanoporetech/dorado/issues/1032

Please note that we don't plan to support the R9 chemistry in dorado correct.

Best regards,
Rich

**Comment by colindaven** [comment]
I'm not the dev, but there is an alternative for correcting R9.4.1 reads - https://github.com/LuoGroup2023/DeChat/issues/2
I haven't tried it yet but it's on my list.
