### ISSUE TITLE
Poly(A) Sequence and Subsequent Analysis

### ISSUE THREAD

**Issue by x1han** [nanoporetech/dorado#1090]
Hello developers, thank you for creating the Dorado tool. I have received a lot of help from it.
Recently I've been dealing with my nanopore DRS data, and at this stage we'd like to explore some polyA-related questions. We've noticed that the developers have added the --estimate-polyA function, which combines the electrical signal to accurately determine the polyA information, which is great, but we have some other requirements:

1. We have noticed that we can use the 'pt:i' tag in the BAM files generated by Dorado align to determine whether a read is considered to carry a polyA tail and to ascertain its length. However, we are curious about how to precisely identify the polyA sequence, or which segment of the read sequence is exactly the polyA sequence? (This may involve the issue of adapter trimming.)
`4767b5c8-8a00-404a-9263-ba4ac5fa9eff	256	chr1	11999	0	226S7M1D53M1D167M385D474M2D27M1D50M2D222M2I34M4D24M1D204M1D9M1D72M1I179M1I29M1D364M1I100M17S	*	0	0	*	*	pt:i:41	NM:i:44ms:i:3697	AS:i:3303	nn:i:0	de:f:0.0256158	tp:A:S	cm:i:129	s1:i:1342	MD:Z:3A3^G53^C153C13^GTAAGTAGTGCTTGTGCTCATCTCCTTGGCTGTGATACGTGGCCGGCCCTCGCTCCAGCAGCTGGACCCCTACCTGCCGTCTGCTGCCATCGGAGCCCAAAGCCGGGCTGTGACTGCTCAGACCAGCCGGCTGGAGGGAGGGGCTCAGCAGGTCTGGCTTTGGCCCTGGGAGAGCAGGTGGAAGATCAGGCAGGCCATCGCTGCCACAGAACCCAGTGGATTGGCCTAGGTGGGATCTCTGAGCTCAACAAGCCCTCTCTGGGTGGTAGGTGCAGAGACGGGAGGGGCAGAGCCGCAGGCACAGCCAAGAGGGCTGAAGAAATGGTAGAACGGAGCAGCTGGTGATGTGTGGGCCCACCGGCCCCAGGCTCCTGTCTCCCCCCAG30C20G0C108G2G2G107A59T75G54C7^AG27^T1A48^GC133C24G47G0T48^CATT4A19^T5C6A6T184^G9^G60T20C25G135G23C12^T30T45T189T1C26G15T2C1C13A33A63A35	rl:i:0`
2. We've noticed that there are differences in the algorithms used by dorado vs. various software in the market for recognizing polyA. This has led us to be concerned about potential inaccuracies in the computational results associated with polyA like APA. Therefore, we are interested in knowing if it's possible to conduct further in-depth analysis on Dorado's polyA calculation results, such as for APA. Or do you have any recommended software that can perform such tasks? Based on our understanding, many software tools are relatively outdated; for example, nanopolish does not support RNA0004.

We would appreciate any guidance you could provide on this matter. Thank you for your assistance.

**Comment by malton-ont** [comment]
Hi @x1han,

Dorado does not currently output any additional information regarding the polyA tail to the bam file, so it is not possible from the tags there to map to the polyA location, but all of the required information to calculate this is output in the logging when run with the `-vv` (very verbose) flag:

```
dorado basecaller hac data/ --estimate-poly-a -vv --emit-moves > calls.bam 2> log.txt
grep "PolyA bases" log.txt

[2024-10-22 10:37:44.254] [trace] b9a521a5-100c-487b-9bd5-4afa476f8b57 PolyA bases 117, signal anchor 0 Signal range is 168 4017 Signal length 3849, samples/base 33.012573 trim 3200 read len 1307
[2024-10-22 10:37:44.289] [trace] 55dc162c-28f4-460e-b396-6430cd8eb081 PolyA bases 132, signal anchor 0 Signal range is 72 4715 Signal length 4643, samples/base 35.222435 trim 3750 read len 1271
...
```
Add the `trim` value to the `Signal range` values to get the actual position in the signal from the pod5. (Note that for split reads you'll need additional information from the bam file to work out where in the signal the read was split and add that on too).  You can then use the move table from the bam file to determine where in the sequence corresponds to those signal points.

I'm not clear what you're asking in the second part of your question, but I suspect this bit may be better answered on the Nanopore Community forums.
