### ISSUE TITLE
Job Getting Killed After Creating Basecall Pipeline

### ISSUE THREAD

**Issue by pinkfairy57** [nanoporetech/dorado#1091]
Hello,

My job is keep getting killed after creating basecall pipeline

```bash
dorado basecaller hac --no-trim /path/to/file.pod5 > /path/to/calls.bam

[info] Running: "basecaller" "hac" "--no-trim" “/path/to/file.pod5"
[info] Assuming cert location is /etc/ssl/certs/ca-bundle.crt
[info]  - downloading dna_r10.4.1_e8.2_400bps_hac@v4.1.0 with httplib
[info] > Creating basecall pipeline
Killed
```

I received the same error with 

```bash
dorado basecaller hac --models-directory /path/to/models/dna_r10.4.1_e8.2_400bps_hac@v4.1.0 
  --no-trim /path/to/file.pod5 > /path/to/calls.bam
```
Here’s the size for the file if that’s relevant
160K	file.pod5

When I changed my storage for virtual linux environment to 1.9T (available) and 40 CPU cores and ran the command

```bash
dorado basecaller hac --no-trim /path/to/file.pod5 > /path/to/calls.bam

[info] Running: "basecaller" "hac" "--no-trim" "/path/to/file.pod5"
[info] Assuming cert location is /etc/ssl/certs/ca-bundle.crt
[info]  - downloading dna_r10.4.1_e8.2_400bps_hac@v4.1.0 with httplib
[info] > Creating basecall pipeline
Bus error
```

I received a bus error for base caller hac and sup. For fast, it was another kill. This was under the 1.9T (available storage) and 40 CPU cores.

Please help.

**Comment by HalfPhoton** [comment]
Hi @pinkfairy57,

Could you re-run dorado but with the `-vv` (very verbose) flag set which will generate more logging output that would be useful for us to help resolve this issue.

Could you also share more information on your hardware and system setup - specifically could you provide more information on you virtual linux environment?

Kind regards,
Rich

**Comment by pinkfairy57** [comment]
Hello,

Thank you for the help. Here are some of the info I could gather:

dorado -vv basecaller hac --no-trim /path/to/file.pod5 > /path/to/calls.bam

[info] Running: "-vv" "basecaller" "hac" "--no-trim" “/path/to/file.pod5"
dorado:   0.8.1+c3a2952+cu11080
libtorch: 2.0.0-ont
minimap2: 2.27-r1193


strace -o strace_output.log dorado -vv basecaller hac --no-trim /path/to/file.pod5 > /path/to/calls.bam

Last Few lines:

munmap(0x7fd71e4bf000, 4096)            = 0
write(2, "[2024-10-21 13:29:50.319] [", 27) = 27
write(2, "\33[32m", 5)                  = 5
write(2, "info", 4)                     = 4
write(2, "\33[m", 3)                    = 3
write(2, "] Running: \"-vv\" \"basecaller\" \"h"..., 98) = 98
write(2, "dorado:   ", 10)              = 10
write(2, "0.8.1+c3a2952", 13)           = 13
write(2, "+cu", 3)                      = 3
write(2, "11080", 5)                    = 5
write(2, "\n", 1)                       = 1
write(2, "libtorch: ", 10)              = 10
write(2, "2.0.0-ont", 9)                = 9
write(2, "\n", 1)                       = 1
write(2, "minimap2: ", 10)              = 10
write(2, "2.27-r1193", 10)              = 10
write(2, "\n", 1)                       = 1
futex(0x6d79ec00, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x6d79ee28, FUTEX_WAKE_PRIVATE, 2147483647) = 0
madvise(0x7fd6ac4bd000, 28672, MADV_DONTNEED) = 0
exit_group(0)                           = ?
+++ exited with 0 +++


Information on VM: 

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    1
Core(s) per socket:    32
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 106
Model name:            Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
Stepping:              6
CPU MHz:               800.000
CPU max MHz:           2601.0000
CPU min MHz:           800.0000
BogoMIPS:              5200.00
Virtualization:        VT-x
L1d cache:             48K
L1i cache:             32K
L2 cache:              1280K
L3 cache:              49152K
NUMA node0 CPU(s):     0-31
NUMA node1 CPU(s):     32-63
Mem: 1.9T available

02:00.0 VGA compatible controller: Matrox Electronics Systems Ltd. MGA G200e [Pilot] ServerEngines (SEP1) (rev 42) (prog-if 00 [VG controller])
	Subsystem: Emulex Corporation Device 0101
	Flags: bus master, fast devsel, latency 0, IRQ 11, NUMA node 0
	Memory at [location] (32-bit, non-prefetchable) [size=16M]
	Memory at [location] (32-bit, non-prefetchable) [size=16K]
	Memory at [location] (32-bit, non-prefetchable) [size=8M]
	Expansion ROM at [location] [disabled] [size=64K]
	Capabilities: <access denied>

16:00.0 System peripheral: Intel Corporation Device 09a2 (rev 04)
	Subsystem: Lenovo Device 7810

**Comment by HalfPhoton** [comment]
The `-vv` argument is in the wrong place to generate logging output - please place it after the basecaller subcommand otherwise only the version information is shown.

```bash
dorado basecaller -vv ... 
```

**Comment by HalfPhoton** [comment]
Could you please try dorado-0.8.2 this issue is similar to https://github.com/nanoporetech/dorado/issues/1071.

Best regards,
Rich
