### ISSUE TITLE
No supported chemistry found for flowcell_code:'_UNKNOWN_FLOWCELL_' 

### ISSUE THREAD

**Issue by chengyangWang-cell** [nanoporetech/dorado#1096]
[https://github.com/nanopore-wgs-consortium/NA12878](url)

Excuse me:
I'm a beginner in nanopore signal processing, and I want to use Dorado to basecall. 
When I used .pod5( converted by fast5 from [https://github.com/nanopore-wgs-consortium/NA12878](url) ), the errors happened.
C:\Users\w>dorado basecaller hac "D:\user\download\output_01 (3).pod5" > calls.bam
[2024-10-23 09:11:25.887] [info] Running: "basecaller" "hac" "D:\user\download\output_01 (3).pod5"
[2024-10-23 09:11:26.147] [error] No supported chemistry found for flowcell_code: '__UNKNOWN_FLOWCELL__' sequencing_kit: 'SQK-DCS108' sample_rate: 4000
[2024-10-23 09:11:26.148] [error] This is typically seen when using prototype kits. Please download an appropriate model for your data and select it by model path

I'm wondering if some specific fast5/pod5 don't fit Dorado well, given that the data file was derived using 1D ligation kits (450 bp/s) using R9.4 chemistry (FLO-MIN106), which I fail to find relevant models in the table.
Maybe just I'm careless. Looking forward to your reply.

**Comment by HalfPhoton** [comment]
Hi @chengyangWang-cell,

The issue your seeing is that when using the automatic model selection [complex](https://github.com/nanoporetech/dorado?tab=readme-ov-file#automatic-model-selection-complex) `"hac"` dorado must be able to determine which model to use by inspecting the input data. 

For your data, dorado doesn't recognise the flowcell used:  `flowcell_code: '__UNKNOWN_FLOWCELL__'` and therefore cannot find a suitable model for your needs.

To basecall this data you need to first download the basecalling model and specify the model using it's filepath like this:

```bash
dorado download --model <model> 
dorado basecaller <model> <data> > calls.bam
```

From what you've shared with me in the logs, I think you want the `dna_r9.4.1_e8_hac@v3.3` model.

```bash
dorado download --model dna_r9.4.1_e8_hac@v3.3 
dorado basecaller dna_r9.4.1_e8_hac@v3.3 "D:\user\download\output_01 (3).pod5" > calls.bam
```

Kind regards,
Rich

**Comment by chengyangWang-cell** [comment]
> Hi @chengyangWang-cell,
> 
> The issue you're seeing is that when using the automatic model selection [complex](https://github.com/nanoporetech/dorado?tab=readme-ov-file#automatic-model-selection-complex) `"hac"` dorado must be able to determine which model to use by inspecting the input data.
> 
> For your data, dorado doesn't recognise the flowcell used: `flowcell_code: '__UNKNOWN_FLOWCELL__'` and therefore cannot find a suitable model for your needs.
> 
> To basecall this data you need to first download the basecalling model and specify the model using it's filepath like this:
> 
> ```shell
> dorado download --model <model> 
> dorado basecaller <model> <data> > calls.bam
> ```
> 
> From what you've shared with me in the logs, I think you want the `dna_r9.4.1_e8_hac@v3.3` model.
> 
> ```shell
> dorado download --model dna_r9.4.1_e8_hac@v3.3 
> dorado basecaller dna_r9.4.1_e8_hac@v3.3 "D:\user\download\output_01 (3).pod5" > calls.bam
> ```
> 
> Kind regards, Rich

This time it ran smoothly. Actually I downloaded all the r9.4 models to try before raising the issue, but I never tried to manually add the model in commands. That's so magical and meaningful for a beginner. Thank you.
