### ISSUE TITLE
Can Dorado move the Adaptor designed by us with known sequence

### ISSUE THREAD

**Issue by LongYuan0529** [nanoporetech/dorado#1097]
Hi,

I was slightly confused about how the cDNA library works. I have a read set up as follows:

5' -SQK-PCS114[adapter]--Adaptor 1 designed by us [known sequence] -- PolyA -- cDNA -- -- Adaptor 2 designed by us [known sequence] -- SQK-PCS114[adapter] 3'

I want to get poly(A) tail length, so can Dorado move the Adaptor designed by us with known sequence? Where can I input the sequence?

**Comment by malton-ont** [comment]
Hi @LongYuan0529,

I'm not sure what you mean by "move" the adapter?

Dorado allows custom primers to be used for cDNA polyA estimation by supplying a toml file with:
```
[anchors]
front_primer = "ATCG"
rear_primer = "CGTA"
```
See the [documentation](https://github.com/nanoporetech/dorado/blob/release-v0.8/documentation/PolyTailConfig.md) for a full description.

Your setup looks a little different to the diagrams there - dorado expects the polyA to come after the cDNA on the forward strand, and looks for a polyT in the reverse strand. It may still work with polyA at the 5' end, but there may be a small error depending on if your primer sequence ends in Ts as normally we would try to exclude those from the polyT count.

**Comment by LongYuan0529** [comment]
After I update this toml file, how can I run Dorado program？

**Comment by HalfPhoton** [comment]
@LongYuan0529,

The poly-a estimation arguments (and others) are shown in the `--help`
```bash
$ dorado --help
...
Poly-a arguments:
  --estimate-poly-a           Estimate poly-A/T tail lengths (beta feature).
                                Primarily meant for cDNA and dRNA use cases.
  --poly-a-config             Configuration file for PolyA estimation to change default behaviours
...
```

You can set these as shown:

```bash
dorado basecaller <model> <reads> ... --estimate-poly-a --poly-a-config <config.toml> ... > calls.bam
```

Kind regards
Rich
