### ISSUE TITLE
Dorado SAM specification

### ISSUE THREAD

**Issue by alexcritschristoph** [nanoporetech/dorado#110]
Hi, is there a page that describes the details of the SAM file produced by Dorado? I.E. something equivalent to:
https://pacbiofileformats.readthedocs.io/en/11.0/BAM.html

Are there any special tags, flags, and/or any signal-level data preserved in the SAM?

**Comment by iiSeymour** [comment]
Hi @alexcritschristoph please see https://github.com/nanoporetech/bonito/blob/master/documentation/SAM.md#header

No, we have no plans to put signal data into the SAM.

**Comment by alexcritschristoph** [comment]
Many thanks for the fast response. One more naive question: in the default SAM output, what exactly is being aligned to what? (assuming no reference genome is a part of this)

**Comment by iiSeymour** [comment]
We are producing unaligned SAM in dorado right now.

**Comment by alexcritschristoph** [comment]
Thanks, really appreciate it. Just to follow-up on the above, so there is currently not a way to get any signal or event alignment information out of dorado, right? And if you're interested in that, it means separately implementing a tombo-like resquiggle sort of algorithm right?

Something that *could* potentially be very helpful for users would be if there were tags associated with each base call that defined the event length or mean current level for that base (or the events centered on that base). I get that this might not be possible with how dorado works though.

**Comment by iiSeymour** [comment]
The basecaller can `--emit-moves` which gives you the `mv:B:c` tag in the output which contains a coarse sequence to signal mapping. 

You may also be interested in https://github.com/nanoporetech/kmer_models

@marcus1487 may want to comment further.

**Comment by alexcritschristoph** [comment]
Hey, that's great, thank you for all of your answers.

**Comment by jts** [comment]
FWIW, I've been working on processing the move table to gather simple sample stats like this:
```
ref_name  ref_position  ref_base  read_position  read_base  raw_sample_mean  kmer_model_scaled_mean  basecaller_scaled_mean  kmer       kmer_model_mean
chr1      2953728       G         147            G          77.5             73.6                    -0.886                  TCTAGAGGA  74.5
chr1      2953729       G         148            G          65.4             61.1                    -1.304                  CTAGAGGAA  63.3
chr1      2953730       A         149            A          64.6             60.2                    -1.334                  TAGAGGAAG  59.0
chr1      2953731       A         150            A          71.4             67.3                    -1.096                  AGAGGAAGA  68.5
chr1      2953732       G         151            G          70.5             66.3                    -1.128                  GAGGAAGAA  72.1
chr1      2953733       A         152            A          70.5             66.3                    -1.130                  AGGAAGAAA  68.1
chr1      2953734       A         153            A          67.6             63.3                    -1.229                  GGAAGAAAA  66.1
chr1      2953735       A         154            A          69.4             65.2                    -1.167                  GAAGAAAAC  63.7
chr1      2953736       A         155            A          89.4             85.9                    -0.474                  AAGAAAACT  75.3
chr1      2953737       C         156            C          115.0            112.4                   0.415                   AGAAAACTT  110.7
chr1      2953738       T         157            T          114.7            112.1                   0.405                   GAAAACTTC  113.1
chr1      2953739       T         158            T          112.5            109.8                   0.327                   AAAACTTCA  106.8
chr1      2953740       C         159            C          90.5             87.0                    -0.436                  AAACTTCAC  92.5
chr1      2953741       A         160            A          103.5            100.5                   0.016                   AACTTCACT  70.3
chr1      2953742       C         161            C          105.9            103.1                   0.101                   ACTTCACTC  96.0
chr1      2953743       T         162            T          126.4            124.3                   0.812                   CTTCACTCT  120.5
chr1      2953744       C         163            C          120.1            117.7                   0.591                   TTCACTCTT  103.9
chr1      2953745       T         164            T          120.1            117.7                   0.591                   TCACTCTTA  99.8
chr1      2953746       T         165            T          118.5            116.1                   0.538                   CACTCTTAG  115.4
```

The purpose is to debug getting R10.4.1 models into nanopolish, but I am also considering making this a replacement for `nanopolish eventalign` since it is much easier to do (doesn't require training a new HMM for every pore, for starters) and the reads are accurate enough now that just projecting the move table onto the reference is likely pretty useful. 

My implementation is largely based on what remora is doing with the move table (without a refinement step, at least for now) so I don't want to duplicate what @marcus1487 is doing/planning to do. If there's an intention to release a tool that exposes this type of projected signal alignment to the reference, let me know.

**Comment by Flower9618** [comment]
> The basecaller can `--emit-moves` which gives you the `mv:B:c` tag in the output which contains a coarse sequence to signal mapping.
> 
> You may also be interested in https://github.com/nanoporetech/kmer_models
> 
> @marcus1487 may want to comment further.

Hi, I do not know whether I am right for understanding about move table. But when I calculate the sum(move table), it is not same as the sequence length, but it should be same, right?

**Comment by iiSeymour** [comment]
@Flower9618 the move table is in downsampled space _(the model encoder has strided convolutions)_ and the first integer is the downsample factor so the sum of moves minus that value should equal the sequence length.

**Comment by Flower9618** [comment]
> this explanation

Thank you so much for your reply. So, if the downsample factor is 5, the element in the move table is 1, it means the sequence moved one base when detecting these 5 raw samples which is downsampled to this element, right?

**Comment by iiSeymour** [comment]
@hiruna72 yes, but a technicality is the following would not be true if the model does not downsample the time domain _(i.e. the downsampling factor is 1)_.  

> The number of ones (1) in the move array equals to the fastq sequence length.

**Comment by Flower9618** [comment]
@iiSeymour However, I find for some read is right, but for others, the number of 1 is not same as the length of sequence.
And for the move table and signal, I find the move table * stride not equal to the length of signal.
Thank you so much.

**Comment by iiSeymour** [comment]
What delta are you seeing in sequence space? For mapping back to signal space you want to account for any trimmed samples _(see [ts:i](https://github.com/nanoporetech/bonito/blob/master/documentation/SAM.md#read-tags))_.

**Comment by Flower9618** [comment]
@iiSeymour For the move table and signal, move table * stride = signal length - trimmed signal. I see. Thank you so much.
But for move table and sequence, the sum of move table minus downsample factor != sequence length. I do not know the reason. Is the situation right?

**Comment by Flower9618** [comment]
@iiSeymour For the move table and signal, the length of move table = length signal -trimmed signal. I see. Thank you.
But for move table and sequence, for some reads, the sum of move table minus downsample factor is bigger than sequence length, may be 4 or 1. I do not know the reason. Is the situation right?

**Comment by Flower9618** [comment]
I just find for the .sam and .fastq after running dorado, the sequence context is a little different. For example,
in .sam, the sequence is "TTTGTCCTGTACTTCGTTCAGTTACGTATTGCTCTATAAACTTATTAATTTTTGAATGTATACAGACCATCTTTCAACAGCTAGTACAAGGTCTTCTTTAGGGGTGAAAGCATGTTTTATACTCCTCTTGAATGCTGCAGTTTTAAGTATGCCAATACAGGCAAAGTACTCAATAAAACCTTTTGATTTATCAATGAATGTACTGATTACTTACTATCATTCTTATAAAACCATGGTAGGTAAAATAGAAATACTAATGATGCCTTTGCCTTTTATATGATTGTTGTGAGGATCAAATCAGGTATGAGAGGGGAAATTACTCCACTAATATTATGAAGACCTATTAGGTCATTAACAGAAATTCAGCTGAAATTGTTCTTTATTTTATAGGATGTGCTTTTTTGCCTCCTGCTTTGGAATTTCATCAAAACAAAGAAAACAAACAAATCCTGAATATACACTGAATGGTTTGACTCTAGTTGGAGATTTTTAAAGTTTTGCTCCAACCTTGACTGACTCCAATTCTAAAGACAACTGAGCAGGCTAGTTAGGAAATTCTTATGCAACTTATAAAAATAGAGACCCCAAAGGGCTTTTTGGCATAATAGAATAGAATAGAATAGAAAAATACTTTTGATGTGTGGTTGCGGGTTAATCCCTTCGTCTTTGTCACCATTAAGGAAGAGAAATACTCCTCTAAGATCAAAGAGAAGATTTTGACCTGTATTCCCAAACACTGTGCAGAGATTATCCCATTACCATATAATAACACTGTCCTTTGTATCTGGGTAGTTTCCTGTGGCACAGCTTTTGATGGAAAGCAATGTGATGAATTTGGGGTGGAAAACTGCAGAAATGGGAGGTCATATGAATCATGTGACCTTCAAAGTGGGGATATACATCAGTGCTCACATGCCAACCCCAAATAGACTAGTGCCCCCTTATCCACAGGGAATACCATTTAGGAGACTTACCAATGTGGATGCCTGAAACCGCGGACAGTATGAAACCATAAAACGTGCTATTTTCCTACACATACATATCTCTAATAAAGTTTGATTTGTAAGTTAGGCACAGTAAGATTAGAAACAGTAACTAATGATAAGTTAGAACAATTATAACAACATACTGTAATGCAAATTATATGAATGTTTTCTCCTCTTTCTCTCAAAATACTGTAATGTTTTCAGATCACAGCTGAGGGCGTTAACTGAAACTGCAGAAAGTGTAACTGTGGATAAGAGGTGACTACAGTTTTAGGGATAAGAATGAAATAAGAATATATTTTTATTTTATTCTTATCCCTAAAACTGTAGTCACCTCTTATCCACAGTTACACTTTCTGCAGTTTCAGTTAACACCCTCAGCTGTGATCTGAAAACATTACGAGTATTTTGAGAGAAAGAGGAGAAACATTCATATAATTTGCATTACATATGTTGTTATAATTGTTCTAACTTATAACATTACTGTTTTAATCTCTTACTGTGCCTAACTTACAAATCAAACTTTATTAGAGATATGTATGTGTAGGAAAAAACACAGTATGTTTATGGTTTGGTATACTGTCCGCAGTTTCAGGCATCCATGGGGGTCTTGAAATGTATTTCCTGTGGATAAGGGGGCCTGTTTATTTGGGGTTGGCATGTGAGCACTGTTAGGCACTGCACGACTTCTCAAACCTTAAAGTCAAATTGCATACAGCCATCTTCACTTCCTGTTCCACCCCAATTTTCATCCCATATTTGCTTTTTATCAAACCTGCTACAAACTAAACTTCACAAATAAAAGGAAGGTGCCATGACATGGTATGGAGTACCTCTGCACAGTGTTTGGGAAATACA", which length is 1844.
But in .fastq, the sequence is "ATGTCCTGTACTTCGTTCAGTTACGTATTGCTCTATAAACTTATTAATTTTTGAATGTATACAGACCATCTTTCAACAGCTAGTACAAGGTCTTCTTTAGGGGTGAAAGCATGTTTTATACTCCTCTTGAATGCTGCAGTTTTAAGTATGCCAATACAGGCAAAGTACTCAATAAAACCTTTTGATTTATCAATGAATGTACTGATTACTTACTATCATTCTTATAAAACCATGGTAGGTAAAATAGAAATACTAATGATGCCTTTGCCTTTTATATGATTGTTGTGAGGATCAAATCAGGTATGAGAGGGGAAATTACTCCACTAATATTATGAAGACCTATTAGGTCATTAACAGAAATTCAGCTGAAATTGTTCTTTATTTTATAGGATGTGCTTTTTTGCCTCCTGCTTTGGAATTTCATCAAAACAAAGAAAACAAACAAATCCTGAATATACACTGAATGGTTTGACTCTAGTTGGAGATTTTTAAAGTTTTGCTCCAACCTTGACTGACTCCAATTCTAAAGACAACTGAGCAGGCTAGTTAGGAAATTCTTATGCAACTTATAAAAATAGAGACCCCAAAGGGCTTTTTGGCATAATAGAATAGAATAGAATAGAAAAATACTTTTGATGTGTGGTTGCGGGTTAATCCCTTCGTCTTTGTCACCATTAAGGAAGAGAAATACTCCTCTAAGATCAAAGAGAAGATTTTGACCTGTATTCCCAAACACTGTGCAGAGATTATCCCATTACCATATAATAACACTGTCCTTTGTATCTGGGTAGTTTCCTGTGGCACAGCTTTTGATGGAAAGCAATGTGATGAATTTGGGGTGGAAAACTGCAGAAATGGGAGGTCATATGAATCATGTGACCTTCAAAGTGGGGATATACATCAGTGCTCACATGCCAACCCCAAATAGACTAGTGCCCCCTTATCCACAGGGAATACCACTTCAGAGTTCCCAATGTGGATGCCTGAAACCGCGGACAGTATGAAACCATAAACGTGCTATTTTCCTACACATACATATCTCTAATAAAGTTTGATTTGTAAGTTAGGCACAGTAAGATTAGAAACAGTAACTAATGATAAGTTAGAACAATTATAACAACATACTGTAATGCAAATTATATGAATGTTTTCTCCTCTTTCTCTCAAAATACTGTAATGTTTTCAGATCACAGCTGAGGGCGTTAACTGAAACTGCAGAAAGTGTAACTGTGGATAAGAGGTGACTACAGTTTTAGGGATAAGAATGAAATAAGAATATATTTTTATTTTATTCTTATCCCTAAAACTGTAGTCACCTCTTATCCACAGTTACACTTTCTGCAGTTTCAGTTAACACCCTCAGCTGTGATCTGAAAACATTACGAGTATTTTGAGAGAAAGAGGAGAAACATTCATATAATTTGCATTACATATGTTGTTATAATTGTTCTAACTTATAACATTACTGTTTTAATCTCTTACTGTGCCTAACTTACAAATCAAACTTTATTAGAGATATGTATGTGTAGGAAAAAACACAGTATGTTTATGGTTTGGTATACTGTCCGCAGTTTCAGGCATCCATGGGGGTCTTGAAATGTATTTCCTGTGGATAAGGGGGCCTGTTTATTTGGGGTTGGCATGTGAGCACTGTTAGGCACTGCACGACTTCTCAAACCTTAAAGTCAAATTGCATACAGCCATCTTCACTTCCTGTTCCACCCCAATTTTCATCCCATATTTGCTTTTTATCAAACCTGCTACAAACTAAACTTCACAAATAAAAGGAAGGTGCCATGACATGGTATGGAGTACCTCTGCACAGTGTTTGGGAAATACA", which length is 1840.

**Comment by iiSeymour** [comment]
@Flower9618 how are generating the `.sam` and `.fastq` here?

**Comment by Flower9618** [comment]
Maybe I found the reason. Because I run the dorado two times. I compare the .fastq generated in first time with the .sam generated in second time, which means the result about two times will be a little different, even with same .pod5 file.

**Comment by hiruna72** [comment]
> @hiruna72 yes, but a technicality is the following would not be true if the model does not downsample the time domain _(i.e. the downsampling factor is 1)_.
> 
> > The number of ones (1) in the move array equals to the fastq sequence length.

@iiSeymour gotcha, thanks!
