### ISSUE TITLE
Significant decrease in demux yield going from dorado-v0.5.1 to dorado v >= 0.7.3

### ISSUE THREAD

**Issue by wshropshire** [nanoporetech/dorado#1101]
Hello, 

We have noticed that using the same basecaller (dorado-v0.8.2) with two different demux versions (dorado-v0.5.1 vs. dorado-v0.8.2) gets wildly discrepant yields for this one particular run:
v0.5.1
<img width="556" alt="Screenshot 2024-10-24 at 12 50 20 PM" src="https://github.com/user-attachments/assets/390b7007-1e46-4e10-9e7b-b796b941f995">
 v0.8.2
<img width="625" alt="Screenshot 2024-10-24 at 2 18 30 PM" src="https://github.com/user-attachments/assets/5a5cef1c-490b-4a91-89b4-700f36196491">

You can see the amount of unclassified reads goes up significantly (8X); we also didn't seem to see any significant contamination or issues with the 0.5.1 demux reads to begin with and their NanoPlot QC metrics were all fine (Q20+/N50 > 7Kb). 

I'm using the same command for each: 
<img width="697" alt="Screenshot 2024-10-24 at 2 24 12 PM" src="https://github.com/user-attachments/assets/7eb7bd6c-873a-4316-bdd7-387308ad05ac">

Is this an issue with a parameter that I'm missing on new demux commands? Any thoughts or help would be great, but otherwise, we are just downgrading to 0.5.1 demux command.

**Comment by HalfPhoton** [comment]
Hi @wshropshire,

Thank you for raising this issue - we're investigating and we'll get back to you with updates.

From your examples I can't see any obvious issues or missing arguments.

Kind regards,
Rich

**Comment by wshropshire** [comment]
Hi, I realized I hadn't added the `--no-trim` option for `dorado basecaller` and this recovered the reads.

Best, 

Will

**Comment by HalfPhoton** [comment]
Thanks for letting us know @wshropshire
