### ISSUE TITLE
alignment with "dorado basecaller" command 

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/dorado#1102]
Hello, when using 'dorado basecaller' command to do the alignment with '--reference' parameters. Can I set up multiple threads to speed up the alignment process？

**Comment by HalfPhoton** [comment]
Hi @Flower9618,
Dorado basecaller does not have CLI arguments to set the number of threads used during alignment.

I'm interested in why you're exploring this as we typically see that alignment during basecalling runs concurrently and doesn't hugely affect basecalling performance.

Kind regards,
Rich

**Comment by malton-ont** [comment]
Dorado standalone already attempts to determine an appropriate number of threads to use for alignment - see [here](https://github.com/nanoporetech/dorado/blob/release-v0.8/dorado/cli/basecaller.cpp#L431), [here ](https://github.com/nanoporetech/dorado/blob/release-v0.8/dorado/cli/basecaller.cpp#L474) and [here](https://github.com/nanoporetech/dorado/blob/release-v0.8/dorado/utils/parameters.cpp#L8).
