### ISSUE TITLE
Question about the transition state and the stay score. 

### ISSUE THREAD

**Issue by mamdouhJ** [nanoporetech/dorado#111]
Hello, 

Thank you for the amazing work so far. I have a couple of questions about the possible states and the indices of the possible transition states. 

1. Let's say we have a state_len = 5, We then would have 1024 possible states, Does each state represent a 5-mer in this case? e.g., state1= "AAAAA", state2="AAAAC", state3="GGGGG" or am I mistaken?
2. How do you account for the blank_symbol in the different states? since possible states = n_base^state_len 
3. In https://github.com/nanoporetech/dorado/blob/fae79899a35ad18248a766adf6e3ab4f6c8e4400/dorado/decode/CPUDecoder.cpp#L54-L60 How did the possible 4 transitions states for each state got assigned? 
4. What is the value of the stay_fixed_score? 

Thank you so much for your time.

**Comment by iiSeymour** [comment]
Hello @mamdouhJ 

The space is actually `n_base ^ state * (n_base + 1)` so it's `AAAAA -> {A, C, G, T, N}` _ect_ *(where N is blank/stay)*. The value is typical 2.0 for the stay score and the free parameters are in the range -5.0, 5.0.

**Comment by mamdouhJ** [comment]
Thanks, @iiSeymour  for the reply. Does that mean for each timestep we would have `n_base ^ state_len * (n_base + 1)`  scores therefore, for each possible state we have a score for every possible symbol in the alphabet `{A, C, G, T, N}` or each state is already assigned an emission symbol from the alphabet already?

**Comment by iiSeymour** [comment]
Yes, that's correct *(the former)*.

**Comment by mamdouhJ** [comment]
Thanks, What about the transitioning between the different states? From what I understood, each state can transition to one of four states, how are these possible transition states assigned to each state?
