### ISSUE TITLE
Dorado Demultiplexing Inconsistency 

### ISSUE THREAD

**Issue by okverynice** [nanoporetech/dorado#1111]
# Issue Report
I am working with data sequenced with a Promethion P2. The library protocol was done with a Twist Mechanical Fragmentation kit, using stubby adapters and IDT UDI 96 well plates. I have sequenced the same samples with HiFi (from the same library), and when visualizing the samples on IGV, it seems that there are significant inconsistencies. At places, it looks like sample 1 from the Promethion sequencing matches sample 7 from the HiFi sequencing. I basecalled with dorado (dna_r10.4.1_e8.2_400bps_sup@v5.0.0) and had it output a fastq.

## Please describe the issue:
I saw issue #559 and used the same mask sequences for my first round of demultiplexing. I believe the IDT UDI plates we have use the format AATGATACGGCGACCACCGAGATCTACAC[i5]ACACTCTTTCCCTACACGACGCTCTTCCGATC and GATCGGAAGAGCACACGTCTGAACTCCAGTCAC[i7]ATCTCGTATGCCGTCTTCTGCTTG. After seeing that the demultiplexing was strange, I decided to modify the mask sequences to include the full leading and trailing adapters associated with the i5 and i7 indexed adapters, thinking that this may increase the stringency of demultiplexing (at the cost of a reduced yield). When I did this, it resulted in about 54% unclassified reads compared to 25% for the partial masks. Although the data looked better on IGV , there were still inconsistencies when compared the the pacbio data.  The main issue is I am not sure that dorado is demultiplexing correctly, and I want to check that my input files are correct. Two final questions, is there a way to demultiplex in line with basecalling, and why do my output fastq files have the format ce4c950b91b799f67de45a2b9da60272b36c0380_unclassified.fastq rather than the expected unclassified.fastq format?

## Steps to reproduce the issue:
Basecalling command: "${dorado}" basecaller --emit-fastq "${model}" "${reads}" | bgzip > "${output_file}"

My first arrangement file:
[arrangement]
name = "test-github-kit"
first_index = 1
last_index = 7
kit = "BC"
mask1_front = "GACCACCGAGATCAC"
mask1_rear = "ACACTCTTTCCC"
mask2_front = "GACGGCATACGAGAT"
mask2_rear = "GTGACTGGAGTTCAGA"
barcode1_pattern = "i5_%02i"
barcode2_pattern = "i7_%02i"

Second arrangement file:
[arrangement]
name = "NMDP-full-mask"
first_index = 1
last_index = 7
kit = "BC"
mask1_front = "AATGATACGGCGACCACCGAGATCTACAC"
mask1_rear = "ACACTCTTTCCCTACACGACGCTCTTCCGATC"
mask2_front = "CAAGCAGAAGACGGCATACGAGAT"
mask2_rear = "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATC"
barcode1_pattern = "i5_%02i"
barcode2_pattern = "i7_%02i"

tsv: (Shorted for brevity)
experiment_id,kit,flow_cell_id,alias,barcode
test,test-github-kit,a01,NMDP_01,barcode01
test,test-github-kit,a01,NMDP_02,barcode02

Barcode fasta: (shortened for brevity)
>i5_01
GCTATAGCTT
>i5_02
CCTGGATTGG
>i7_01
TCCGATCTTA
>i7_02
TGTTCACGGC

Command:
dorado demux --output-dir "${out_dir}" \
    --kit-name BC \
    -t "${SLURM_CPUS_ON_NODE}" \
    --sample-sheet barcodes_dorado_full_mask.tsv \
    --barcode-sequences barcodes_dorado.fasta \
    --barcode-arrangement arrangement_file_full_mask.toml \
    --emit-fastq "${input_fastq}"; wait; 

## Run environment:
- Dorado version :dorado-0.8.0-linux-x64
- Dorado command: 
- Operating system: Linux
- Hardware (CPUs, Memory, GPUs):
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.): 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by HalfPhoton** [comment]
Hi @okverynice,

I believe the issue here is that the initial basecalling was done without disabling adapter/primer trimming with `--no-trim`. and as such dorado will have removed most of the adapter sequences in your output.

As for demuxing in-line with basecalling. This can done with the `--kit-name` and `--output-dir` arguments in the basecaller.

If adapter/primer trimming is done while basecalling in combination with demultiplexing, then dorado will ensure that the trimming of adapters and primers does not interfere with the demultiplexing process.

For example, trimming will not effect demultiplexing on kit-name in the following command:

```bash
dorado basecaller <model> reads/ --kit-name <kit-name> --trim all
```

However, if you intend to do demultiplexing as a separate step, it is recommended that trimming is disabled when basecalling with the `--no-trim` / `--trim none` option, to ensure that barcode sequences remain intact in the calls.

```bash
dorado basecaller <model> <reads> --no-trim ... > calls.bam
dorado demux calls.bam --kit-name <kit-name> --output-dir <output-dir> ...
```

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
Also regarding new output filenames: https://github.com/nanoporetech/dorado/issues/1026

**Comment by HalfPhoton** [comment]
Documentation has been improved. Please check out [Read Trimming: Effect on Demultiplexing](https://dorado-docs.readthedocs.io/en/latest/basecaller/read_trimming/#effect-on-demultiplexing).
