### ISSUE TITLE
Dorado correct running very slowly when merging different runs

### ISSUE THREAD

**Issue by SimonaSecomandi** [nanoporetech/dorado#1112]
Hi all, 

I am using dorado 0.7.3+6e6c45c to correct my ONT reads. I have two low coverage runs from the same individual. The first is around 11X (N50 23 kbp) and the second 5X (N50 16 kbp).

I successfully ran `dorado correct` on the first run alone, which finished in a couple of hours. I merged the different fastq files in the folder "fastq_pass" and run `dorado correct` on the merged file:

`cat $datapath/first_run/fastq_pass/* > $datapath/first_run/raw_reads_cat/$runname.fastq.gz`

`gunzip $datapath/first_run/raw_reads_cat/$runname.fastq.gz`

`$DORADO correct -t 32  $datapath/first_run/raw_reads_cat/$runname.fastq > $datapath/first_run/dorado_correct/$runname.corrected.fasta`

When I got the second run, I merged it with the first run simply with `cat` and then run `dorado correct`:

` cat $datapath/first_run/fastq_pass/* $datapath/second_run/fastq_pass/* > $datapath/raw_reads_cat/$runname.fastq.gz`

`gunzip $datapath/raw_reads_cat/$runname.fastq.gz`

`$DORADO correct -t 32  $datapath/raw_reads_cat/$runname.fastq > $datapath/dorado_correct/$runname.corrected.fasta`

 The correction has been running for almost two days. Could this longer run time be related to the merging of the two runs? I did it since `dorado correct` works better with a high coverage and it was removing half of the reads when I ran it on the first run alone.  
 
Many thanks!

Simona

**Comment by HalfPhoton** [comment]
Hi @SimonaSecomandi, 
Yes it's likely taking longer as dorado can infer on more regions now that there's more coverage. 

Kind regards,
Rich

**Comment by SimonaSecomandi** [comment]
Hi @HalfPhoton, many thanks!

It makes sense of course, but I find odd that adding only 5X more increases the running time from 2 hours to two days. Anyway, the job was canceled automatically after 2 days and only produced an empty fasta file. 

However, I rerun the same commands on the same merged data using dorado 0.8.2 and the correction finished after 4 hours!

Best,

Simona

**Comment by HalfPhoton** [comment]
Interesting that it had no output but that appears to be resolved in 0.8.2 👍
