### ISSUE TITLE
Log command output failed

### ISSUE THREAD

**Issue by liuyang2006** [nanoporetech/dorado#1114]
# Issue Report

## Please describe the issue:

When I run command in command line, I can see the verbose command output. However, when I redirect the command output to a log file, there is nothing in the logfile.

## Steps to reproduce the issue:
command I used:
```
dorado basecaller /project/sli68423_1316/users/yang/tools/dorado-0.8.2-linux-x64/models/dna_r10.4.1_e8.2_400bps_hac@v5.0.0 /project/sli68423_1316/users/yang/aml_nanopore/results/2024_10_30_guppy_run_test/run_script_PT01/input_pod5/ --models-directory /project/sli68423_1316/users/yang/tools/dorado-0.8.2-linux-x64/models --modified-bases-models /project/sli68423_1316/users/yang/tools/dorado-0.8.2-linux-x64/models/dna_r10.4.1_e8.2_400bps_hac@v5.0.0_5mCG_5hmCG@v2 -x auto --verbose -r --reference /project/sli68423_1316/users/yang/reference/chm13v2.0/chm13v2.0.fa --output-dir . --batchsize 96    > aaa.log   2>&1
```

## Logs

There is nothing output to `aaa.log` file

**Comment by HalfPhoton** [comment]
Hi @liuyang2006,

Can you try redirecting only the stderr instead? 

```bash
2> aaa.log
```

**Comment by HalfPhoton** [comment]
Also, you can use the model selection complex to clean up your Dorado call
Removing the long paths to the model and modbase models.
```bash
dorado basecaller hac,5mCG_5hmCG ... 
```
