### ISSUE TITLE
Automated Model Selection for Fast5 File to FastQ File

### ISSUE THREAD

**Issue by pinkfairy57** [nanoporetech/dorado#1116]
Hello,

Is there a way to basecall from fast5 to fastq directly (I know it’s not suggested) using the automated model selection? I tried doing it but got this error. 

dorado basecaller -vv sup path/to/file.fast5 --emit-fastq > path/to/output.fastq

[info] Running: "basecaller" "-vv" "sup" "path/to/file.fast5" "--emit-fastq"
[trace] Model complex: 'sup' found variant: 'sup' and version: 'latest'
[info]  - Note: FASTQ output is not recommended as not all data can be preserved.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot automate model selection using fast5 files
Aborted

This command was run on the "models" directory where I have all the models downloaded using “dorado download --model all”.

Worked when I did:

dorado basecaller -vv /path/to/models/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 --no-trim path/to/file.fast5 --emit-fastq > path/to/output.fastq

**Comment by HalfPhoton** [comment]
Hi @pinkfairy57,
The automatic model selection is not implemented for fast5 inputs. Please use the model path as you have shown. 

I'd recommend updating the model though to use the v5 model as it has better accuracy over v4.1

Best regards,
Rich
