### ISSUE TITLE
Question on CpG Island-Specific Methylation Analysis Using Dorado

### ISSUE THREAD

**Issue by Taylorain** [nanoporetech/dorado#1117]
Hi, I’m currently using the `dna_r10.4.1_e8.2_400bps_sup@v5.0.0_5mCG_5hmCG@v2.0.1` model in Dorado for methylation analysis. I have a few questions regarding its capabilities, particularly in relation to CpG islands:

**CpG-Specific Methylation Detection:** From my understanding, this model identifies methylation specifically at CpG sites. Could you confirm if this is correct?
**CpG Island-Specific Analysis:** Is there a way in Dorado to limit or filter methylation calls specifically to CpG islands? Or would I need to post-process the output data to isolate methylation data that overlaps with known CpG island regions?

CpG Island Identification within Dorado: Lastly, does Dorado have any built-in feature to identify CpG islands, or is it recommended to pre-define these regions using other tools and cross-reference them with Dorado’s output?

**Comment by HalfPhoton** [comment]
Hi @Taylorain,
Yes, this model will only call on CG contexts.

Please take a look at [ModKit](https://github.com/nanoporetech/modkit) for post processing / filtering tools for modBAMs. There's no way to do this filtering at basecall time.

Best regards,
Rich

**Comment by Taylorain** [comment]
I get, thanks pretty much!
