### ISSUE TITLE
SUP Modification Basecalling Model Architecture

### ISSUE THREAD

**Issue by harikaurel** [nanoporetech/dorado#1121]
Hi! From what I understand, Remora is integrated with Dorado, and the latest SUP canonical basecalling models now use Transformer-based architectures. I was curious if the SUP models for modification basecalling are also Transformer-based or if they still rely on CNNs and LSTMs?

**Comment by malton-ont** [comment]
Hi @harikaurel,

The modification models are currently CNN+LSTM.
