### ISSUE TITLE
'XM' tag not found by grep. (call from pod5)

### ISSUE THREAD

**Issue by ysuzuki1978** [nanoporetech/dorado#1123]
I made a methylation call in dorado to output a bam file, sorted it, and then used grep to extract 'XM', but no hits at all. Is there a different tag for the methylation? Please tell me.

/home/yasu1978/nanopore/dorado-0.7.3-linux-x64/bin/dorado basecaller /home/yasu1978/nanopore/model/dna_r10.4.1_e8.2_400bps_hac@v5.0.0 --modified-bases 5mC_5hmC --reference /home/yasu1978/reference/mouse/GRCm39.mmi --device cuda:0 /home/yasu1978/methyl/CD/pod5/pass_9 >  /home/yasu1978/methyl/CD/methylation_output_09.bam

**Comment by HalfPhoton** [comment]
Hi @ysuzuki1978,

Please take a look at the new documentation specifically the section on [modifications](https://dorado-docs.readthedocs.io/en/latest/basecaller/mods/#sam-tags-mm-ml).

Best regards,
Richard
