### ISSUE TITLE
Question about `--estimate-poly-a` and Adapter Removal in DRS Basecalling

### ISSUE THREAD

**Issue by Taylorain** [nanoporetech/dorado#1125]
Hi!
I’m working with Direct RNA Sequencing (DRS) data generated using the SQK-RNA004 kit, and I’m using the following command for basecalling:

```bash
dorado basecaller \
  -x cuda:0 \
  --estimate-poly-a \
  --verbose \
  --emit-moves \
  -k 14 \
  --emit-fastq \
  sup /DRS_data/pod5/pod5_pass/ \
> /bio/sup_drs/2_fastq/0_A.fa
```

I have a question regarding the `--estimate-poly-a` option and adapter removal. Specifically, I would like to know if enabling `--estimate-poly-a` affects the removal of adapters during basecalling. Are adapters automatically removed when this parameter is active, or should I explicitly specify another option to ensure adapter trimming?

Thank you very much for your guidance!

**Comment by HalfPhoton** [comment]
Hi @Taylorain 

[PolyA estimation](https://dorado-docs.readthedocs.io/en/latest/basecaller/polya_estimation/) will not effect [read trimming](https://dorado-docs.readthedocs.io/en/latest/basecaller/read_trimming/#trimming-while-basecalling). 

I've linked the relevent parts of the new documentation above. Which should hopefully explain these features in more detail.

Best regards,
Rich

**Comment by Taylorain** [comment]
Thank you for your help. So, even though I used the --estimate-poly-a parameter during basecalling, the adapters have already been automatically removed, correct?

**Comment by HalfPhoton** [comment]
Yes, the basecaller default is `--trim all`.
