### ISSUE TITLE
Methylation calling v5.0.0_5mCG_5hmCG@v2 model output non-CpG results

### ISSUE THREAD

**Issue by liuyang2006** [nanoporetech/dorado#1126]
I am using below command, but output contains non-CpG methylation predictions? Could you please confirm and provide solutions to remove non-CpG sites predictions?

Command used:
```
dorado basecaller    dna_r10.4.1_e8.2_400bps_hac@v5.0.0 in_data --modified-bases-models dna_r10.4.1_e8.2_400bps_hac@v5.0.0_5mCG_5hmCG@v2 --reference chm13_v2.fa --output-dir out_call_dir
```

Output BAm files in IGV Viewer:
![Screenshot 2024-11-09 at 9 21 31 AM](https://github.com/user-attachments/assets/e8d3ad74-4a25-465a-bbd3-dadb44e394e6)

**Comment by HalfPhoton** [comment]
Hi @liuyang2006,

Can you double check the BAM header that it wasn't using the SUP 5mCG_5hmCG @v2.0.0 and not the HAC model as you show in the command?

This issue with the SUP version was addressed in the v2.0.1 patch update. 

Best regards,
Rich

**Comment by liuyang2006** [comment]
Hi Rich,

I am using HAC model (dna_r10.4.1_e8.2_400bps_hac@v5.0.0_5mCG_5hmCG@v2), here is the bam header:
```
samtools view -H  J01.bam| less

@HD     VN:1.6  SO:coordinate
@PG     ID:basecaller   PN:dorado       VN:0.8.2+6b413c9        CL:dorado basecaller /project/sli68423_1316/users/yang/tools/dorado-0.8.2-linux-x64/models/dna_r10.4.1_e8.2_400bps_hac@v5.0.0 /project/sli68423_1316/users/yang/aml_nanopore/results/2024_10_31_run_script_new_data/run_script_J01/input_pod5/ --models-directory /project/sli68423_1316/users/yang/tools/dorado-0.8.2-linux-x64/models --modified-bases-models /project/sli68423_1316/users/yang/tools/dorado-0.8.2-linux-x64/models/dna_r10.4.1_e8.2_400bps_hac@v5.0.0_5mCG_5hmCG@v2 -x auto --verbose -r --reference /project/sli68423_1316/users/yang/reference/chm13v2.0/chm13v2.0.fa --output-dir . --batchsize 96
        DS:gpu:NVIDIA A100-PCIE-40GB
@PG     ID:samtools     PN:samtools     PP:basecaller   VN:1.18 CL:samtools sort -@ 16 -o J01_dorado_bam_out_combine.bam calls_2024-11-03_T05-47-29.bam
@PG     ID:samtools.1   PN:samtools     PP:samtools     VN:1.18 CL:samtools sort -@ 16 -o J01_dorado_bam_out_combine.bam calls_2024-11-03_T05-47-29.bam
@PG     ID:samtools.2   PN:samtools     PP:samtools.1   VN:1.18 CL:samtools sort -@ 8 -o J01_dorado_bam_out_combine.bam calls_2024-11-03_T05-47-29.bam
@PG     ID:samtools.3   PN:samtools     PP:samtools.2   VN:1.18 CL:samtools view -H J01_dorado_bam_out_combine.bam
@RG     ID:208f72a9ea4d5c7ec4441b27e1381e486806e037_dna_r10.4.1_e8.2_400bps_hac@v5.0.0  PU:PAY12935     PM:PCA100178    DT:2024-10-11T23:50:24.401+00:00        PL:ONT  DS:basecall_model=dna_r10.4.1_e8.2_400bps_hac@v5.0.0 modbase_models=dna_r10.4.1_e8.2_400bps_hac@v5.0.0_5mCG_5hmCG@v2 runid=208f72a9ea4d5c7ec4441b27e1381e486806e037     LB:J01  SM:J01
@SQ     SN:chr1 LN:248387328
@SQ     SN:chr2 LN:242696752
@SQ     SN:chr3 LN:201105948
@SQ     SN:chr4 LN:193574945
```

**Comment by HalfPhoton** [comment]
@liuyang2006,

Is this a mis-called A -> C in your pileup?

Best regards,
Rich

**Comment by HalfPhoton** [comment]
@liuyang2006,

The only information that Dorado has at the time of modified basecalling is the canonical basecalled sequence and **not** the aligned sequence. 

What you're seeing here are mis-called `D` (not-C) bases called as `C` which are also neighbour `G`, which in the **basecalled sequence**, match the `CG` motif. Dorado modified basecaller will predict the presence of modified bases at all context (motif) hits as [described here](https://dorado-docs.readthedocs.io/en/latest/basecaller/mods/#modification-context).

Best regards,
Rich
