### ISSUE TITLE
Issue with --estimate-poly-a

### ISSUE THREAD

**Issue by Suchi-alt** [nanoporetech/dorado#1127]
Hi,

I’m encountering an issue with the pt:i tag in the BAM file output. Despite adding primers to the polyaconfig.toml file, the pt:i values don’t align as expected with the corresponding reads. I’ve tried adjusting parameters like the flank threshold and primer definitions, but the values still seem inconsistent.

I’m working with pod5 files and exploring ways to calculate polyA lengths. Would it make sense to write a Python or Bash script to calculate polyA lengths for each fastq file as a means to validate the pt:i values? Since I’m new to sequencing, I want to ensure I’m not overlooking something fundamental.

Any guidance would be greatly appreciated!

**Comment by malton-ont** [comment]
@Suchi-alt,

If you're calling plasmids you should be setting `plasmid_front_flank` and `plasmid_rear_flank` rather than the primers. See the [docs here](https://github.com/nanoporetech/dorado/blob/release-v0.8/documentation/PolyTailConfig.md).

**Comment by malton-ont** [comment]
Yes, that is correct.

**Comment by Suchi-alt** [comment]
Thanks alot! :)

**Comment by Suchi-alt** [comment]
Thank you so much :)
