### ISSUE TITLE
How to check the modification model version

### ISSUE THREAD

**Issue by hungweichen0327** [nanoporetech/dorado#1130]
Dear community,

I would like to know how to check the modification model version.
For example, the current modification model version of  dna_r10.4.1_e8.2_400bps_hac@v5.0.0 is **V2**.
But I did not know whether I used the latest version (V2) rather than the previous one (V1).
If I used the previous one (V1), did it impact the output read quality?

Thank you for the help.

**Comment by malton-ont** [comment]
@hungweichen0327,

The modbase model used is stored in the `DS` tag of the read group (`@RG`) header. See the docs [here](https://github.com/nanoporetech/dorado/blob/release-v0.8/documentation/SAM.md#read-group-header).

Using different modbase models will not affect read quality (qscore) but may affect the accuracy of the modbase calls.

**Comment by HalfPhoton** [comment]
Hi @hungweichen0327,
Following on from the documentation on [model versions](https://dorado-docs.readthedocs.io/en/latest/models/models/#model-version-numbers) you can check the model version by inspecting the SAM/BAM header with:

```bash
samtools view -H calls.bam

# Grep for the model name
samtools view -H calls.bam | grep "hac\S*" -o
```

The modbase calls will be slightly better with v2 modbase models but the canonical calls will be unchanged.

Best regards,
Rich

**Comment by HalfPhoton** [comment]
Updated documentation FAQ: "[Which model did I use?](https://dorado-docs.readthedocs.io/en/latest/troubleshooting/faq/#which-model-did-i-use)"

**Comment by hungweichen0327** [comment]
I would like to confirm the meaning of modbase.
modbase = Compatible Modifications = 4mC_5mC 5mCG_5hmCG 5mC_5hmC 6mA, isn't it?

**Comment by HalfPhoton** [comment]
Modbase is an abbreviation of "modified base". 
For example, a "modbase model" would be modified base model such as `dna_r10.4.1_e8.2_400bps_hac@v5.0.0_5mC_5hmC@v2.0.0`.

We try to consistently use "modified base" throughout the documentation but "modbase" is used in the codebase as a short-hand.
