### ISSUE TITLE
Q: No supported chemistry found for <..> 

### ISSUE THREAD

**Issue by sklages** [nanoporetech/dorado#1135]
I have two datasets (GridION, 01/2023), each of them from five flowcells, fast5.

Fast5 data has been converted to pod5 without any issue, each pod5 around 300G.

Dorado has been called like:
```
[2024-11-16 22:37:29.670] [info] Running: 
  "basecaller" "sup@v4.1.0,5mCG_5hmCG" 
  "/dev/shm/mxqd/mnt/job/53252484" 
  "--device" 
  "cuda:all" 
  "--batchsize" "0" 
  "--trim" "all" 
```

The error I get looks like:
```
[2024-11-16 22:11:39.490] [error] 
    No supported chemistry found for 
    flowcell_code: 'FLO-MIN112' 
    sequencing_kit: 'SQK-LSK112' 
    sample_rate: 4000
[2024-11-16 22:11:39.490] [error] 
    This is typically seen when using prototype kits. 
    Please download an appropriate model for your data and select 
    it by model path
  terminate called after throwing an instance of 'std::runtime_error'
    what():  Could not resolve chemistry from data: Unknown chemistry
```

(I have reformatted outputs for better readability)

I solved this issue (for me) by providing the file paths to the baecalling and the modified base models directly:

```
dorado basecaller \
  /path/to/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 \
  --modified-bases-models /path/to/dna_r10.4.1_e8.2_400bps_sup@v4.1.0_5mCG_5hmCG@v2 \
  pod5/MyData.pod5 \
  --trim \
  --device cuda:all \
  --output-dir MyData
```

- why does `dorado` fail on automatic model selection? We have 'flowcell_code', 'sequencing_kit' and 'sample_rate'. I'd think this should be enough to select the approbiate models for 4kHz data?
- just curious: why is `dorado` not using `/dev/stderr` for progress status when using `--output-dir`? I am using `dorado` non-interactively (usually without `--output-dir`) catching stdout/stderr, which is empty here .. so I do not see any basecalling progress ..

**Comment by HalfPhoton** [comment]
Hi @sklages,
The model selection fails because your data doesn't match a known condition. It's either r10.3 or r10.4 (I'm not sure which from memory) data which isn't supported by Dorado.

As for the stderr progress info, if you're not running in an interactive terminal session then the output is disabled. 

I believe there's an outstanding feature request to generate some logging output in this case. Maybe weI'll print updates every few percent / interval. 
I'll link the original issue when I'm next at my machine.

Best regards,
Rich

**Comment by sklages** [comment]
thanks @HalfPhoton for the quick and helpful response!

Does this mean that "my" `dorado´ call - which is technically working - will produce wrong or at least not very accurate basecalled data? Do I need to run guppy for these datasets?

The relationship between kits, data and software is not always very, hmm, obvious ..  :-)

**Comment by HalfPhoton** [comment]
Hi @sklages, my pleasure!

The models won't have been trained on the specific conditions so there's a risk of inaccurate calls. I'd recommend using guppy and the models trained for this specific condition.

Yeah, we could work on improving the warning message in Dorado to say which condition is detected even if it's not supported. I think there's an outstanding feature request from a previous issue for that too. 

Best regards,
Rich

**Comment by sklages** [comment]
@HalfPhoton - customer confirmed R10.4.1 + LSK112 at 400bps. 
Did I get you right, the incompatible condition is actually the combination of latest R10.4.1 flowcell with the older Kit 12 (LSK-112)?

**Comment by HalfPhoton** [comment]
@sklages, it's the flow cell that's unusual, `FLO-MIN112` is r10.4 and not r10.4.1 unfortunately.

**Comment by HalfPhoton** [comment]
The source code ([kits.cpp](https://github.com/nanoporetech/dorado/blob/release-v0.8/dorado/models/kits.cpp#L345)) contains this information:

```c++
/*
Mapping of Chemistry to the complete set of sequencing kits associated with that chemistry.
The cross product of a chemistry's set of flowcells and kits is generated at runtime
*/
const std::unordered_map<Chemistry, ChemistryKits> kit_map = {
        {Chemistry::UNKNOWN, {"__UNKNOWN_CHEMISTRY__", 1, SampleType::DNA, {}}},
        {Chemistry::DNA_R9_4_1_E8, {"dna_r9.4.1_e8", 4000, SampleType::DNA, kit_sets::kit10::sets}},
        {Chemistry::DNA_R10_4_1_E8_2_260BPS,
         {"dna_r10.4.1_e8.2_260bps", 4000, SampleType::DNA, kit_sets::kit14::sets_260bps}},
        {Chemistry::DNA_R10_4_1_E8_2_APK_5KHZ,
         {"dna_r10.4.1_e8.2_apk_5khz", 5000, SampleType::DNA, kit_sets::kit14::sets_apk}},
        {Chemistry::DNA_R10_4_1_E8_2_400BPS_4KHZ,
         {"dna_r10.4.1_e8.2_400bps_4khz", 4000, SampleType::DNA, kit_sets::kit14::sets_400bps}},
        {Chemistry::DNA_R10_4_1_E8_2_400BPS_5KHZ,
         {"dna_r10.4.1_e8.2_400bps_5khz", 5000, SampleType::DNA,
          kit_sets::kit14::sets_400bps_5khz}},
        {Chemistry::RNA002_70BPS,
         {"rna002_70bps", 3000, SampleType::RNA002, kit_sets::rna002::sets}},
        {Chemistry::RNA004_130BPS,
         {"rna004_130bps", 4000, SampleType::RNA004, kit_sets::rna004::sets}},
};
```

This feature request is tracked in [this issue](https://github.com/nanoporetech/dorado/issues/1022).

This is [the issue](https://github.com/nanoporetech/dorado/issues/913) for the progress output without an interactive terminal.

Best regards,
Rich

**Comment by HalfPhoton** [comment]
@sklages, 
Are you happy we close this issue as resolved? We'll track the the feature requests in the original issues.

Best regards,
Rich

**Comment by sklages** [comment]
Sure, thanks Rich
