### ISSUE TITLE
Using spot instances to reduce compute costs

### ISSUE THREAD

**Issue by kopichris** [nanoporetech/dorado#1136]
In [Benchmarking the Oxford Nanopore Technologies basecallers on AWS](https://aws.amazon.com/blogs/hpc/benchmarking-the-oxford-nanopore-technologies-basecallers-on-aws/), the authors mention the possibility of reducing compute costs using spot instances.  

I would like to explore this option using the `sup` model type; however, I am worried about the risk of interruption for long-running processes using spot instances.  To reduce the risk of interruption, I wonder if it makes sense to split the input pod5 files into smaller chunks (as in [Duplex Basecalling](https://github.com/nanoporetech/dorado?tab=readme-ov-file#improving-the-speed-of-duplex-basecalling)) and then run each chunk on separate spots instances to reduce runtime.

The unaligned BAM files from each process and sample would be merged upon completion.  Are there any drawbacks to this approach or reasons why this might not seem feasible?  I appreciate any input or feedback your team could provide.  Thank you in advance for your time and consideration.

Best,
Chris

**Comment by HalfPhoton** [comment]
Hi @kopichris, 

I do something similar internally for our basecalling pipelines. The solution we have creates basecalling batches balanced by samples. If you have your own benchmarks for the configuration of models / options you want to run, you can create batches of some approximate _run time_ of a few hours or your preference.

* Use `pod5 view --include "num_samples"` and `awk` to count the total number of samples in the dataset
* Divide by your benchmark basecalling speed and multiply by your desired job run time.
* Create collections of input data cheaply using directories of symlinks or create "real" pod5 subsets with `pod5 subset`.
* Basecall each subset and merge the bams after.

Best regards,
Rich

**Comment by kopichris** [comment]
Hi @HalfPhoton,

I really appreciate your thoughtful feedback and response -- this is super helpful.  Thank you again for your time.  I hope you have a great week.

Best,
Chris
