### ISSUE TITLE
Calibration strand detection

### ISSUE THREAD

**Issue by willros** [nanoporetech/dorado#114]
Hi!

Just wondering if you are planning to provide a calibration strand detection option in dorado, like --calib_detect in Guppy? 

Thanks,
William

**Comment by Xuanpei-Zhai** [comment]
Hi

I've encountered this issue as well. How does dorado remove standards?

**Comment by josiegleeson** [comment]
I've also ran into this issue, at the moment it doesn't appear to remove it, so you will have to do it manually during mapping.

**Comment by MarkBicknellONT** [comment]
Hi all,

Thanks for the feedback - we are not currently intending to add calibration strand detection to the dorado command line tool suite.  If you have run a flow-cell with calibration strands included and you wish to filter them from your data, you can align your reads to the calibration strand sequence and then filter out any hits using (e.g.) `samtool view --incl-flags 0x4 <bam file>`.

The reference sequences for DNA and RNA calibration strands are outlined here:
https://help.nanoporetech.com/en/articles/6632934-what-is-dna-cs-dcs
https://help.nanoporetech.com/en/articles/6632031-what-is-rna-cs-rcs

Kind regards,
Mark
