### ISSUE TITLE
Modification tags and re-calling

### ISSUE THREAD

**Issue by wanghlv** [nanoporetech/dorado#1142]
Hi, I'm wondering if I'd like to call all modification possible using the rna004_130bps_sup@v5.1.0, will DORADO write out each modification separately in a different field in BAN file or output as different files. Thanks! Also, if I would like to redo-modification call later, do I need to start from POD5 files again? Thanks again!

**Comment by malton-ont** [comment]
Hi @wanghlv,

Modification data is stored in the output BAM file as `MM` and `ML` tags - see the docs [here](https://dorado-docs.readthedocs.io/en/latest/basecaller/mods/#sam-tags-mm-ml) and the specification [here](https://samtools.github.io/hts-specs/SAMtags.pdf) (section 1.7) for more details.

If you want to recall the modifications you will need to re-basecall from pod5, yes.
