### ISSUE TITLE
Resume from question. 

### ISSUE THREAD

**Issue by cahuparo** [nanoporetech/dorado#1143]
Hi! 

I am running` dorado correct` and I had an interrupted run. I used the `--resume-from` flag as suggested. 

When I searched the finished/completed (v2) output of `dorado correct` I can't find the reads generated in the initial/stoped run (v1)

```
> less -S *22*v2* | grep -E "26335ab7-ad74-4ce4-a650-38a5a0acb099" | wc -l
0
```
Are users supposed to concatenate all output files generated?

Thanks, 

Camilo

**Comment by HalfPhoton** [comment]
Hi @cahuparo, 
Yes, as [the docs](https://dorado-docs.readthedocs.io/en/latest/correct/correct/?h=resume#resume) say the previous inputs are skipped and not copied. You'll need to merge these outputs when they're finished.

> The --resume-from argument takes a list of previously corrected reads provided via a .fai index from the outputs of the previous run. The reads that have been previously processed are then skipped when resuming.

Best regards,
Rich
