### ISSUE TITLE
suspiciously drastic differences between dna_r10.4.1_e8.2_400bps_sup@v4.3.0 and v5.0.0

### ISSUE THREAD

**Issue by sjfleck** [nanoporetech/dorado#1148]
# Issue Report

## Please describe the issue:

I'm getting vastly different results between base calling with "dna_r10.4.1_e8.2_400bps_sup@v4.3.0" (with MinKnow and set the minimum length to 1kbp and q score of 10) and "dna_r10.4.1_e8.2_400bps_sup@v5.0.0" (on a cluster node with GPUs). I noticed that Minknow base called with an older version of Doardo (v4.3.0), so I transferred the pod5 directory onto my university's cluster, basecalled with v5.0.0, and filtered the base called reads for reads ≥1kbp and Q≥10. v4.3.0 resulted in a 168.8 Gb fastq.gz file of passed reads (min length≥1kbp and Q≥10). When I base called with v5.0.0, I got a fastq.gz file 258.2 Gb in size. I then filtered the fastq.gz file using fastp for min length≥1kbp and Q≥10 and the resulting fastq.gz file was 105.4 Gb.

To summarize, v4.3.0 produced a 168.8 Gb fastq.gz file and v5.0.0 produced one that was 105.4 Gb. Both were filtered for min length≥1kbp and Q≥10. Can you help me understand what is happening here? Thank you

## Steps to reproduce the issue:
I'll just included the necessary variables for the commands

Script 1:
MODEL=dna_r10.4.1_e8.2_400bps_fast@v5.0.0
${DORADO_DIR}/dorado download --model ${MODEL}
${DORADO_DIR}/dorado basecaller ${MODEL} ${POD5_DIR} > ${PREFIX}.simplex.${MODEL}.calls.bam
samtools bam2fq ${PREFIX}.simplex.${MODEL}.calls.bam > ${PREFIX}.fastq
gzip ${PREFIX}.fastq

Script 2:
MIN_READ_LEN=1000
fastp -i ${READS} -o ${SP}_L${MIN_READ_LEN}.fastq.gz \
-h ${SP}_L${MIN_READ_LEN}.html -j ${SP}_L${MIN_READ_LEN}.json \
-l ${MIN_READ_LEN} -e 10 \
--disable_adapter_trimming --disable_trim_poly_g -V -w 16

## Run environment:
- Dorado version: 0.7.3
- Dorado command: dorado basecaller
- Operating system: Linux
- Hardware (CPUs, Memory, GPUs): CPU = 1, memory 48Gb, GPU = 1 
- Source data type: pod5
- Source data location: University cluster storage 
- Details about data: FLO-PRO114M, SQK-LSK114, I ran the data in 6 separate runs without any errors and concatenated the fastq.gz files afterward. Total bases: 259 billion. Total reads: 39 million (which almost exactly matches the passed+failed reads in the final reports output in MinKnow) 

Let me know if you need log files for this issue. There's also a chance I need to contact fastp about this, but it seems more like a Dorado issue than a fastp issue. Thank you

**Comment by iiSeymour** [comment]
Hi @sjfleck I think the issue is with the first line of script 1 where you have specified the fast model not the sup model.
