### ISSUE TITLE
duplex basecalling

### ISSUE THREAD

**Issue by ziphra** [nanoporetech/dorado#115]
Hello, 

I am not sure about what to do after dorado duplex basecalling.

Should I merge the duplex reads basecalled with the simplex reads that were basecalled before? Should I remove the duplex reads  also basecalled during simplex basecalling before to avoid duplicate reads? 

Many thanks in advance

**Comment by vellamike** [comment]
Hi @ziphra,

> Should I merge the duplex reads basecalled with the simplex reads that were basecalled before? 
Some proportion of simplex reads will not have made it to Duplex, so depending on how sensitive your application is to data volume, this is possibly a good idea.

> Should I  remove the duplex reads also basecalled during simplex basecalling before to avoid duplicate reads
All the duplex reads will have been basecalled at the simplex stage and there are no "duplicates". A Duplex read is a combination of two simplex reads which came from both strands of a DNA molecule.

**Comment by ziphra** [comment]
Ok, I get it. Thank you.
