### ISSUE TITLE
methylated Guanine (mG)

### ISSUE THREAD

**Issue by eltonjrv** [nanoporetech/dorado#1152]
# Issue Report
Brief question/probing
## Please describe the issue:
I wonder if there's any upcoming 7mG modification model to be applied for rRNAs' direct RNA-seq. 
I'm currently using differr (https://github.com/bartongroup/differr_nanopore_DRS) but results are not too compelling in some cases.
Any other recommendations would be appreciated.
Thanks,
Elton

**Comment by eltonjrv** [comment]
Thanks for your reply, Adrien (and nice chatting again with you :) 
Good to know on the upcoming 2'O methylation model. We'll definitely use it for assessing ncRNAs through DRS.
So, I believe as of now I should keep relying on differential error rate approaches for m7G cases.
Thanks again and I'm sure we'll keep in touch,
Warm regards,
Elton

**Comment by a-slide** [comment]
Yes I can confirm that the current basecalling model should not have seen many instances of m7G and hence should be making errors in some cases, but you probably know that basecalling errors are not always a very reliable proxy for modified bases.
If you would like to go a bit deeper you could also run a signal comparison analysis, if you have a control sample without m7G. There are community tools for this such as Xpore and Nanocompore, and you can also run a quick analysis with Remora API https://github.com/nanoporetech/remora/blob/master/notebooks/metrics_api.ipynb

**Comment by eltonjrv** [comment]
Thanks again, Adrien.
Yes, we do have a knock-down for the m7G writer under assessment.
I'll give Xpore and Nanocompore a try.
Best,
Elton

**Comment by ChristianOrtizL** [comment]
Hi all, any follow ups on this? There was a lot of chatter and interest about m7G at the recent UCSC RNA Futures conference. Lots of folks interested in looking at full length transcripts, and also assessing METTL1 biology. Thanks! Seems like the chemistry for it is still difficult to bring to the market.
