### ISSUE TITLE
is dorodo modification accuracy calling at all affected by calling multiple modification calls? 

### ISSUE THREAD

**Issue by aleighbrown** [nanoporetech/dorado#1153]
We're exploring RNA modifications with direct RNA-sequencing sequenced on a PromethION flow cell

We're interested mostly in m6A sites, but have a possible interest in looking at m5C as well. 

Is there any reason to suspect that the current dorodo models would have any issues with accuracy calling 2 modification at once? I saw some issues from 2023 suggesting that accuracy may be lower when calling multiple types at once but given the speed of change I just wanted to make sure this wasn't suspected to be an issue anymore. 

E.g. is there any reason to suspect that running with rna004_130bps_sup@v5.1.0, m6A_DRACH,m5C would be less accurate at calling m6a sites than rna004_130bps_sup@v5.1.0 m6A_DRACH alone?

We haven't run yet - I'm just curious to know if this might be expected to cause issues in our samples, 

Thank you!

**Comment by malton-ont** [comment]
Hi @aleighbrown,

The separate models are run independently, so should give the same results whether they are run together or separately.

**Comment by aleighbrown** [comment]
Thank you!
