### ISSUE TITLE
Error in detection of modified bases in RNA sequecing by PromethION. 

### ISSUE THREAD

**Issue by shakti83kumar** [nanoporetech/dorado#1156]
Hi Evereyone,

I have RNA sequencing data that have been generated by PromethION. Screen shots of Run summary, Run configuration, Sequence output, Run health, Run log has been attached below. I want to find out RNA modified base "m6A" from the data. I run the program. but it is showing error. 
Please help me.
![Screenshot from 2024-12-02 16-24-12](https://github.com/user-attachments/assets/65a54781-e481-4dc5-8bbc-cd36b2477527)
![Screenshot from 2024-12-02 16-24-20](https://github.com/user-attachments/assets/4f4cbf4a-8d54-4cbc-9efa-2d2f76af3cdf)
![Screenshot from 2024-12-02 16-24-29](https://github.com/user-attachments/assets/fa5f7536-04b8-4409-8199-40be9b765ad6)
![Screenshot from 2024-12-02 16-24-44](https://github.com/user-attachments/assets/4f80379a-66fd-46bc-b445-59505fd82029)
![Screenshot from 2024-12-02 16-24-51](https://github.com/user-attachments/assets/3808ede4-419b-4599-89da-476782557846)
![Screenshot from 2024-12-02 16-29-03](https://github.com/user-attachments/assets/c10f95e3-5b99-422b-bf09-87b59a630746)

**Comment by juanjo255** [comment]
Hello @shakti83kumar ! 

I think probably is an error with syntax. When I'm basecalling using modified option, I do it this way:
`dorado basecaller --min-qscore 7 --trim adapters --modified-bases 5mCG_5hmCG --models-directory /path/to/models/ sup@v5.0.0 "$file" > Output.bam`

Note the simplex model setting for model-directory then the modified-bases add the specificity.

I hope it helps!

**Comment by malton-ont** [comment]
@shakti83kumar,
```
dorado basecaller .../rna004_130bps_hac@v5.0.0_m6A@v1...
```
Your command is incorrect: the first model should be the canonical basecall model, not a modification model; modifications should be passed via the `--modified-bases` or `--modified-bases-models` parameters. Your command should look like:
```
dorado basecaller .../rna004_130bps_hac@v5.0.0 ... --modified-bases-model .../rna004_130bps_hac@v5.0.0_m6A@v1 > calls.bam
```
See the docs [here](https://dorado-docs.readthedocs.io/en/latest/basecaller/mods/#via-modified-bases-models-cli-argument) for further examples.
