### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by baibhav-bioinfo** [nanoporetech/dorado#1158]
Hello everyone, 
I have a plant sample DRS data with RNA004 chemistry. I was trying to identify the m6A sites using Dorado basecalling, but was getting the segmentation error repeatedly.
can anyone please suggest something here?

```text
dorado basecaller rna004_130bps_hac@v5.1.0 /path/to/pod5 \
 --modified-bases-models rna004_130bps_hac@v5.1.0_m6A_DRACH@v1/ \
 > calls.bam
[2024-12-02 19:09:54.362] [info] Running: "basecaller" "rna004_130bps_hac@v5.1.0" "/path/to/pod5" "--modified-bases-models" "rna004_130bps_hac@v5.1.0_m6A_DRACH@v1/"
[2024-12-02 19:09:54.388] [info] > Creating basecall pipeline
[2024-12-02 19:09:54.972] [info]  - BAM format does not support `U`, so RNA output files will include `T` instead of `U` for all file types.
Segmentation fault (core dumped)
```

**Comment by bitezhu** [comment]
Same situation.

**Comment by baibhav-bioinfo** [comment]
@bitezhu okay, 
let me know if you are able to find a solution....i will let you know if my command works first.

**Comment by malton-ont** [comment]
Hi @baibhav-bioinfo,

I'm not able to reproduce this locally so I suspect it only occurs with specific data, or is related to your system configuration. Can you please provide the system info as requested in the issue template? And also, please provide the log information generated by running your command with the `-vv` flag. Finally, if you could isolate this issue to a few reads that you are able to share with us, then we can investigate further.

**Comment by malton-ont** [comment]
@baibhav-bioinfo,

I don't think it's a file size issue - I think the issue occurs with a read you've now excluded. If you can find which read that is, we can investigate.

Modification information is stored in the `MM/ML` tags of each BAM record. See the [docs here](https://dorado-docs.readthedocs.io/en/latest/basecaller/mods/#sam-tags-mm-ml).

**Comment by baibhav-bioinfo** [comment]
Thankyou so much for the help @malton-ont ,
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/baibh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/baibh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


MM:Z:A+a?,4; | ML:B:C,6
-- | --
MM:Z:A+a?,4,11,10,3,4,14; | ML:B:C,2,0,132,0,255,231
MM:Z:A+a?,17,30; | ML:B:C,0,0
MM:Z:A+a?,3,10; | ML:B:C,28,0



</body>

</html>

**Comment by baibhav-bioinfo** [comment]
thankyou so much @malton-ont for the generous help
okay, i will look error which i am getting
for now, whats the general cutoff which i can as threshold to retain high confidence m6A modified sites (manual says 0.45)? 

tried running with "--modified-bases-threshold" option, but its not filtering the sites and outputting same bam

dorado basecaller rna004_130bps_hac@v5.1.0 pod5/chunk_0.pod5 --modified-bases-models rna004_130bps_hac@v5.1.0_m6A_DRACH@v1/ --modified-bases-threshold 0.90 > chunk_0_.90.bam

**Comment by malton-ont** [comment]
@baibhav-bioinfo,

The `--modified-bases-threshold` parameter is only used for all-context models. You are running a `DRACH` context, so this is ignored. This is because the SAM specification gives no way to indicate whether a base was skipped because it did not meet the threshold or whether it was simply not evaluated due to the surrounding context.

For information on the range of the `ML` tag, see the SAM tags specification [here](https://samtools.github.io/hts-specs/SAMtags.pdf). In short, the value lies between [0, 256).

**Comment by baibhav-bioinfo** [comment]
okay, thanks for the clarification @malton-ont 
But i can manually filter the result with 230.4 (0.90*256 for 90% confidence) as a cutoff?

**Comment by malton-ont** [comment]
You may also be interested in [modkit](https://github.com/nanoporetech/modkit) as a tool for parsing and manipulating your modification results.

**Comment by sklages** [comment]
> (2) How to use the GPU in the dorado command?

See [Supported Platforms](https://dorado-docs.readthedocs.io/en/latest/#supported-platforms) and also [Specifying hardware resources](https://dorado-docs.readthedocs.io/en/latest/#specifying-hardware-resources)

To monitor GPU usage you can use something [nvtop](https://github.com/Syllo/nvtop).

**Comment by HalfPhoton** [comment]
@baibhav-bioinfo,

> (1) I have plant DRS data, so are the pre-trained models i am using are correct?
what species are the models trained on? If the models are trained on human data only, are they suitable for plants too?

The models are trained on a wide variety of samples and should be suitable for you plant samples.

> (2) How to use the GPU in the dorado command?

Thanks for [the contribution](https://github.com/nanoporetech/dorado/issues/1158#issuecomment-2516386763) @sklages 👍 

> (3) If everything is fine and i get the read position of the m6A sites. How do i convert the read position to transcript and then genomic location?

You'll need to align your data to a reference and extract the alignment coordinates. This can be done with the `--reference` dorado basecaller argument to [basecall and align at the same time](https://dorado-docs.readthedocs.io/en/latest/basecaller/alignment/#alignment-during-basecalling), or you can align as a separate process with [dorado aligner](https://dorado-docs.readthedocs.io/en/latest/basecaller/alignment/#aligning-existing-basecalls).

Best regards,
Rich

**Comment by malton-ont** [comment]
@baibhav-bioinfo,

If you have additional questions not related to the segmentation fault you reported, please open separate issues. You may also want to take a look at the Nanopore Community forums, where a wide range of bioinf people can help out.

**Comment by baibhav-bioinfo** [comment]
thankyou so much for the responses @sklages @HalfPhoton
I will open separate issue for the other issues.
and i will also seek the nanopore community for help
