### ISSUE TITLE
Can Dorado handle merged samples sequenced with V10 and V14 chemistries?

### ISSUE THREAD

**Issue by Patricie34** [nanoporetech/dorado#1160]
Hi everyone,

I’d like to ask for your advice.
I have samples sequenced with both V10 and V14 chemistries, converted to POD5 format. My intention is to merge them and then perform Dorado duplex basecalling (with hemi-methylation detection) using the model dna_r10.4.1_e8.2_400bps_sup@v4.3.0.

Is it possible to perform it this way? Could there be any conflicts, such as duplicate read IDs or metadata issues, when merging POD5 files?
Additionally, would the pod5 subset command work correctly on merged POD5 files?

Thank you!

## Run environment:
- Dorado command: dorado duplex sup,5mCG_5hmCG ${sample.path} --reference ${sample.ref} --verbose --recursive > ${sample.name}.duplex.bam 
- Operating system: Kubernetes cluster managed by Nextflow
- Hardware (CPUs, Memory, GPUs): nvidia/gpu
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5

**Comment by Patricie34** [comment]
Thank you very much for your response.
Hi @HalfPhoton,

our goal here is to enhance coverage during variant calling. In our previous analysis, when we had samples in our dataset sequenced with both V10 and V14 chemistry, we performed basecalling for each separately using the corresponding basecalling models, then merged the BAM files and proceeded with variant calling afterwards.

This approach used simplex basecalling. However, now we want to use duplex basecalling and we're considering merging the POD5 files from the previous basecalling step and performing duplex to produce a single BAM file per sample.

If I understand correctly, would you recommend merging the BAM files afterwards, as we did before?

Best regards,

Patricie

**Comment by HalfPhoton** [comment]
Hi @Patricie34,

> This approach used simplex basecalling. However, now we want to use duplex basecalling and we're considering merging the POD5 files from the previous basecalling step and performing duplex to produce a single BAM file per sample. 
If I understand correctly, would you recommend merging the BAM files afterwards, as we did before? 

Yes, I think the correct approach here is to do the same as your did for simplex basecalling. It should all work the same for your downstream analyses. 👍 

Best regards,
Rich
