### ISSUE TITLE
Best way to realign bam to different assembly version?

### ISSUE THREAD

**Issue by faulk-lab** [nanoporetech/dorado#1163]
What's the best way to use dorado to realign a bam file to a different assembly version? 

For instance, I have a bam file containing modifications that was mapped to hg38 and I would like to remap the reads to the T2T genome instead. I do not want _additional_ alignments, I want to totally remove and replace the primary alignments with new alignment coordinates to the new genome. I need all the other field information to remain in the file, i.e., modifications, version info, etc.

Can `dorado aligner` do this?

**Comment by HalfPhoton** [comment]
Hi @faulk-lab,

[Dorado aligner](https://dorado-docs.readthedocs.io/en/latest/basecaller/alignment/) should just work for you here. The mod tags should be preserved when re-aligning to a new index as they're properties of the sequence not the alignment.

Best regards,
Rich
