### ISSUE TITLE
using Dorado for m6A analysis 

### ISSUE THREAD

**Issue by baibhav-bioinfo** [nanoporetech/dorado#1164]
Hello everyone, first let me thank the developers for creating such a useful and diverse software dorado.
I have some queries which if answered will be very thankful.
 
I do not have any access to GPU but i have a HPC, and i have ~15 million reads/sample, can that be basecalled with base modification in 48 hours time limit?

(I am getting the segmentation error repeatedly, i will have to figure out a way to handle that)

also, 

(1) once i get the bam output file from dorado, how do i get the genomic/transcriptomic location 

(2) How to proceed to the differential modification analysis between conditions?

**Comment by malton-ont** [comment]
@baibhav-bioinfo,

Regarding the performance, this will depend on the model you are running, which modifications, the length of your reads, and the system you are running on. If you can provide this information (as requested in the issue template), we may be able to advise.

Regarding your other questions, these are better asked on the Nanopore Community forum as they are not related to dorado specifically.

**Comment by baibhav-bioinfo** [comment]
sure @malton-ont, 
Following is the command i am running, which states the models i will be using

time dorado basecaller rna004_130bps_hac@v5.1.0 test.pod5 --modified-bases-models rna004_130bps_hac@v5.1.0_m6A_DRACH@v1/ --reference ref.fasta > test.bam

I am running for **m6A modification** from Nanopore DRS data. 
**Reads stats:**
file                     format  type    num_seqs         sum_len       min_len  avg_len  max_len
sample_1.fastq  FASTQ   RNA   11,623,521  12,862,446,548        1        1,106.6  255,108
**pod5** size for each sample is ~450 GB

HPC system i am using have specification 
CPU: Intel Xeon CPU MAX 9480 
Cores: 112 (56*2)

**Comment by malton-ont** [comment]
Hi @baibhav-bioinfo,

For 10,000,000 reads of 1000nt at 130bps and 4kHz, that's about 3e11 samples of data. For a runtime of 48 hours, dorado would need to be running at 1.8 million samples per second, which I think is unlikely when running in CPU mode.

I'd suggest getting hold of a device with a GPU - this will be much more effective. If that's not possible, you could consider splitting you pod5 files into smaller sets and running multiple jobs, then combining the results afterwards.
