### ISSUE TITLE
Clarifying demux parameters

### ISSUE THREAD

**Issue by cliffbueno** [nanoporetech/dorado#1167]
Hello,
I am using dorado to demultiplex MinION reads.

I wanted to clarify the `max_barcode_penalty` parameter. I read that it says: "The maximum edit distance allowed for a classified barcode.". I also read that the decision is done by: "Is the barcode penalty _below_ max_barcode_penalty and the distance between the top 2 barcode penalties greater than min_barcode_penalty_dist?." My question is essentially, is this a "less than" or "less than or equal to" decision? For example, if I want to allow a maximum of 2 base pair mismatch, should I set `max_barcode_penalty` to 2 or 3?

Thanks!
Cliff

**Comment by malton-ont** [comment]
Hi @cliffbueno,

The check is "less than or equal to". You can see this [here](https://github.com/nanoporetech/dorado/blob/release-v0.8/dorado/demux/BarcodeClassifier.cpp#L922). We'll clarify the documentation to reflect this correctly.

**Comment by cliffbueno** [comment]
Ok thanks! Are those also the defaults for custom demultiplexing or only for the ONT kits?

**Comment by malton-ont** [comment]
Those are the defaults for custom as well.
