### ISSUE TITLE
RNA004 Pore Model Question

### ISSUE THREAD

**Issue by lubitelpospat** [nanoporetech/dorado#1168]
Hi folks,
Not sure if there's a more appropriate place to ask this question - could you please help me figure out how to interpret the pore model for RNA004 chemistry? The kmer_models GitHub repo says that the "expected level table is in standard units" - are there some pre-calculated, rna population-wise standardization factors, or should the signal be converted based on its own values? The second does not seem to make sense because in that case, signal levels will depend on the specific read and thus wouldn't be applicable to all reads. Sorry if this is the wrong place to ask, but the issues in the kmer_models repo are disabled. Hope to chat more on this soon!

**Comment by malton-ont** [comment]
Hi @lubitelpospat,

I'm not 100% clear what you are looking for here. I believe the models you are talking about are used in [remora](https://github.com/nanoporetech/remora) to provide a baseline for rescaling the kmer signal before it is passed to the RNN - you may have more luck asking on their github page, or the nanopore community?

**Comment by lubitelpospat** [comment]
> Hi @lubitelpospat,
> 
> I'm not 100% clear what you are looking for here. I believe the models you are talking about are used in [remora](https://github.com/nanoporetech/remora) to provide a baseline for rescaling the kmer signal before it is passed to the RNN - you may have more luck asking on their github page, or the nanopore community?

Hi @malton-ont ,
Thank you so much for your answer! Will try the remora GitHub, thanks! 
Sorry, for asking this question in the wrong place - will close this issue now.
