### ISSUE TITLE
drop in the number of aligned reads

### ISSUE THREAD

**Issue by alisamatisse** [nanoporetech/dorado#1176]
# Issue Report

My Nanopore data were initially basecalled using the fast model in MinKNOW, but due to unsatisfactory quality, I switched to the sup model for improved accuracy. I performed basecalling and demultiplexing with Dorado and alignment with Minimap2 (scripts attached).
I observed a significant reduction in the number of reads when using the sup model compared to the fast model. Despite attempts to reproduce the original results, I couldn't.
Is it expected to have fewer reads with a more accurate (sup) model?

## Run environment:
- Dorado version: dorado-0.8.3
- Source data type: pod5

## Aligned data size from the fast model

22 G
19 G
13 G

## Aligned data size from the sup model

7.6 G
6.9 G
4.9 G

## Basecalling script 

```
# Set variables
MODEL="sup,5mCG_5hmCG"                     # Model for basecalling
POD5_DIR_1=<...>  # Directory containing POD5 files
POD5_DIR_2=<...>
OUTPUT_DIR=<...>

# Function for basecalling
process_pod5_files() {
    local POD5_DIR=$1
    for pod5_file in "$POD5_DIR"/*.pod5; do
        # Extract the basename of the POD5 file (without extension)
        base_name=$(basename "$pod5_file" .pod5)

        # Run Dorado basecaller
        echo "Processing $pod5_file -> Basecalled data in $OUTPUT_DIR"
        ~/dorado-0.8.3-linux-x64/bin/dorado basecaller \
            --device cuda:all \
            "$MODEL" \
            "$pod5_file" \
            --no-trim \
            > "$OUTPUT_DIR/${base_name}_basecalled.bam"
    done
}

# Step: Basecalling Only
process_pod5_files "$POD5_DIR_1"
process_pod5_files "$POD5_DIR_2"
```
## Demux script

```
OUTPUT_DIR=<...>   # Directory containing basecalled BAM files
DEMUX_OUTPUT_DIR=<...> # Directory for demultiplexed BAM files
KIT_NAME="SQK-NBD114-96"                     # Kit name used for demultiplexing

# Create output directory for demultiplexed files if it doesn't exist
mkdir -p "$DEMUX_OUTPUT_DIR"

# Function for demultiplexing

~/dorado-0.8.3-linux-x64/bin/dorado demux --output-dir "$DEMUX_OUTPUT_DIR" --kit-name "$KIT_NAME" "$OUTPUT_DIR"
```

## minimap2 alignment

```
# Set variables
INPUT_DIR=<...>  # Directory with input BAM files
OUTPUT_DIR=<...>   # Directory for aligned BAM files
REFERENCE=<...>          # Reference genome
THREADS=10                 # Number of threads for Minimap2

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Function for alignment
align_bam_files() {
    for bam_file in "$INPUT_DIR"/*.bam; do
        # Extract the basename of the BAM file (without extension)
        base_name=$(basename "$bam_file" .bam)

        # Define output file paths
        fastq_file="$OUTPUT_DIR/${base_name}.fastq"
        aligned_bam="$OUTPUT_DIR/${base_name}_aligned.bam"

        # Convert BAM to FASTQ
        echo "Converting $bam_file to FASTQ -> $fastq_file"
        samtools fastq "$bam_file" > "$fastq_file"

        # Align the reads using Minimap2
        echo "Aligning $fastq_file -> $aligned_bam"
        minimap2 -a -x map-ont -t "$THREADS" "$REFERENCE" "$fastq_file" | \
        samtools view -Sb | \
        samtools sort -o "$aligned_bam"

        # Index the sorted BAM file
        samtools index "$aligned_bam"

        # Remove intermediate FASTQ file to save space
        rm "$fastq_file"

        echo "$bam_file has been aligned and saved as $aligned_bam"
    done
}

# Step: Alignment
align_bam_files
```
Scripts are ugly and separated but I wanted to do that so I can trace an error... it did not help, unfortunately. 
Where should I look for the problem? Thank you and please let me know if I can provide more info!!

Kind regards,
Alisa

**Comment by malton-ont** [comment]
Hi @alisamatisse,

My first guess here would be that you're getting better sequences from the sup model so there are fewer spurious secondaries. Can you check the number of secondary/supplementary alignments in each output dataset?

Different sequences may also lead to differences in read-splitting, which would compound these issues. Dorado should be logging the total number of input reads that were basecalled - if these values are similar between models then read-splitting may be a partial explanation.

I can't quite tell from your description whether the "data size" you have posted is the size of the BAM files or the number of reads they contain. Since you're using a CG-context model, the accuracy of the calls may also affect the number of modbase calls - in this instance the size of the dataset files would not be a good metric for comparison.

**Comment by alisamatisse** [comment]
Thank you so much! Let me investigate that. I will reopen the issue in case I don't figure out what is happening. What I posted was BAM file sizes.

**Comment by alisamatisse** [comment]
I am still not sure what was the problem, but with the sup model I do get higher quality reads at the same region of interest coverage (we perform adaptive sampling). 

Thanks!
