### ISSUE TITLE
dorado aligner for centromere

### ISSUE THREAD

**Issue by santoshbiowarrior333** [nanoporetech/dorado#1177]
Hi,

I am interested in the reads at centromere, my N50 is 110kb.
Do i need to change any parameters for facilitating this alignment in repeated region of genome?

**Comment by HalfPhoton** [comment]
Hi @santoshbiowarrior333, This question is best asked on the [Nanopore Community Forum](https://community.nanoporetech.com/getting_started) as it's not a dorado issue.

Best regards,
Rich
