### ISSUE TITLE
Splitting a pod5 based on read-ID or aligned-fastq?

### ISSUE THREAD

**Issue by mbosm** [nanoporetech/dorado#1180]
This is probably an odd request, but it would be pretty helpful for my work!

I'm currently in the process of sequencing human samples containing a virus, and I'm doing direct-RNA sequencing so I can look at the RNA modifications on the virus. When I publish my work, I'd like to include not just BAM-aligned fastq files but pod5 files so that other researchers could do the same modification calling using dorado.

The issue is that that pod5 file is also going to contain all the human RNA reads from that sequencing run, and I'd rather not share that data for privacy reasons.

I've used dorado to do m6A/m5C/pseudouridine calling and have results aligned against the viral genome as a sorted BAM. Presumably the read ID found in the fastq files are also present in the pod5 file, right? Is there some way to have dorado split the pod5 file, so that reads that match a list (or reads that align in a BAM file) are put in one pod5 file, and reads that don't match the list (or don't align) are put in another pod5 file?

My only other alternative is not to include pod5 files when publishing, so I thought I'd ask. Thanks!

**Comment by HalfPhoton** [comment]
Hi @mbosm,
You can collect the read_ids from the fastq file into a list (text file with one read id per line) and use the [pod5 filter tool](https://pod5-file-format.readthedocs.io/en/latest/docs/tools.html#pod5-filter) to create a pod5 file with only these reads.

Best regards,
Rich

**Comment by mbosm** [comment]
Great, thank you so much!
