### ISSUE TITLE
Caught exception: CUDA error: system not yet initialized

### ISSUE THREAD

**Issue by ChristianKniep** [nanoporetech/dorado#1184]
# Issue Report

## Please describe the issue:

When running dorado (latest container image) on a multi-GPU A100 system from AWS (p4.24xl) I we see an exception warning `system not yet initialized` indicating that CUDA was not initialized correctly.

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version: `0.9.0+9dc15a8`
- Dorado command: 
   `podman exec -ti 6f9fe4d09918 sh -c "dorado correct FILE.fq --from-paf FILE.paf > FILE_corrected_reads.fasta"`
- Operating system: AL2023
- Hardware (CPUs, Memory, GPUs): p4.2xl
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.): EBS volume
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)
```
[2024-12-18 07:13:57.208] [info]  - downloading herro-v1 with httplib
[2024-12-18 07:13:58.911] [error] Caught exception: CUDA error: system not yet initialized
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Device-side assertions were explicitly omitted for this error check; the error probably arose while initializing the DSA handlers.
Exception raised from c10_cuda_check_implementation at /pytorch/pyold/c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f097e7269b7 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f0977cab115 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f097e6f0958 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
frame #3: c10::cuda::CUDAKernelLaunchRegistry::CUDAKernelLaunchRegistry() + 0x9d (0x7f097e6f002d in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
frame #4: c10::cuda::CUDAKernelLaunchRegistry::get_singleton_ref() + 0x44 (0x7f097e6f01f4 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
frame #5: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x35 (0x7f097e6f0875 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
frame #6: dorado() [0xb7e6d2]
frame #7: dorado() [0x9da36a]
frame #8: dorado() [0x950bc0]
frame #9: dorado() [0x89e96f]
frame #10: dorado() [0x4f6a00]
frame #11: __libc_start_main + 0xf3 (0x7f0972be4083 in /lib/x86_64-linux-gnu/libc.so.6)
frame #12: dorado() [0x823f5f]
```

**Comment by HalfPhoton** [comment]
@ChristianKniep, can you tell us the specific version of dorado being used here. We've just had a release of dorado to 0.9.0.

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
Hi @ChristianKniep, can you confirm you're able to run another CUDA application? 
This issue is similar to [this one](https://github.com/pytorch/pytorch/issues/35710). 

Kind regards,
Rich
