### ISSUE TITLE
What does `dorado download --data <pod5_file>` do?

### ISSUE THREAD

**Issue by Shians** [nanoporetech/dorado#1187]
Based on the help string

```
Usage: dorado [--help] [--model VAR] [--models-directory VAR] [--list] [--list-yaml] [--list-structured] [--data VAR] [--recursive] [--overwrite] [--verbose]...

Optional arguments:
  -h, --help          shows help message and exits
  --model             the model to download [nargs=0..1] [default: "all"]
  --models-directory  the directory to download the models into [nargs=0..1] [default: "."]
  --list              list the available models for download
  --list-yaml         list the available models for download, as yaml, to stdout
  --list-structured   list the available models in a structured format, as yaml, to stdout
  --data              path to POD5 data used to automatically select models [nargs=0..1] [default: ""]
  -r, --recursive     recursively scan through directories to load POD5 files
  --overwrite         overwrite existing models if they already exist
  -v, --verbose       [may be repeated]
```

I expected that using the --data argument would download only the models relevant to that particular pod5. However it appears to download all models. Is this the intended behavior?

**Comment by malton-ont** [comment]
Hi @Shians,

The `--data` argument is intended to be using in conjunction with specifying a model complex (e.g. `hac,5mC_5hmC`) via the `--model` parameter. See the docs [here](https://dorado-docs.readthedocs.io/en/latest/models/downloader/#download-models-for-a-specific-condition). We'll look into clarifying the inline documentation for this.

**Comment by HalfPhoton** [comment]
@Shians, can you clarify what you mean by:
> It appears to download all models. Is this the intended behavior?

If you specify `--models hac --data reads` - all hac models suitable for that condition are downloaded which is intended behaviour.

**Comment by Shians** [comment]
I had used the data argument without any other argument and it downloaded all models. Thanks for the clarification.
