### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by joannacolovas** [nanoporetech/dorado#119]
I recently installed dorado-0.2.1-osx-arm64 on a MacPro desktop, and when I try to download the models to run dorado with, I get the error "zsh: bad CPU type in executable: Documents/dorado-0.2.1-osx-arm64/bin/dorado [file location of dorado installation].

Please advise!

**Comment by vellamike** [comment]
Hi @joannacolovas - are you running this on an intel or M1/M2 MacBook Pro?

**Comment by joannacolovas** [comment]
Hi @vellamike It's a 2019 Mac pro tower with an intel processor

**Comment by vellamike** [comment]
Hi @joannacolovas - Dorado only works with the more recent Apple Silicon-based computers (M1, M1 Pro, M1 Max, M1 Ultra etc). The reason for this is that it is optimised for Apple GPUs. Since the device you are you are using is Intel-based it will not work with the current version of Dorado.
