### ISSUE TITLE
minimum length/base pairs

### ISSUE THREAD

**Issue by Ashok-pappu** [nanoporetech/dorado#1190]
Dear Developers, I noticed minimum length/base pairs arguments is not present in dorado, is it possible to set manually or any other way to give min-length while running basecalling.

Best regards
Ashok Coumar Jayaveloue

**Comment by malton-ont** [comment]
Hi @Ashok-pappu,

Dorado has a cut-off of 5bp - reads shorter than this will be discarded. There is currently no way to override this - if you are looking for a higher cut-off then you will need to filter your data afterwards:
```
samtools view -e "length(seq) > 25" calls.bam
```

**Comment by Ashok-pappu** [comment]
thank you
