### ISSUE TITLE
Building on mac osx

### ISSUE THREAD

**Issue by thomasvangurp** [nanoporetech/dorado#12]
I'm going to document what I ended up installing on my m1 macbook pro max to compile dorado:

## 0. Packages installed using brew
- cmake
- openssl
- hdf5

## 1. Xcode installation and profile switch for being able to use metal
You need to download and install Xcode, i would recommend downloading it directly from https://developer.apple.com/download/all/ instead of  installing it from the App store as the latter is relatively slow (max 2.4 Mb/sec download)

Afterwards, you need to switch
`sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer`

**Comment by iiSeymour** [comment]
Thanks @thomasvangurp - we have made builds available now https://github.com/nanoporetech/dorado#installation
