### ISSUE TITLE
Documentation doesn't mention that duplex model also needs to be downloaded

### ISSUE THREAD

**Issue by oneillkza** [nanoporetech/dorado#120]
Hi!

In your readme, the instructions are to run Dorado in duplex mode using:

```
$ dorado duplex dna_r10.4.1_e8.2_400bps_sup@v4.1.0 pod5s/ --pairs pairs.txt > duplex.sam
```

Which implies that you should download the `dna_r10.4.1_e8.2_400bps_sup@v4.1.0`

But when you run with just that model you get the error

```
[error] toml::parse: file open error -> dna_r10.4.1_e8.2_4khz_stereo@v1.1/config.toml
```

So it turns out that it also needs the `dna_r10.4.1_e8.2_4khz_stereo@v1.1` model. It might be good to document this.

**Comment by iiSeymour** [comment]
Hi @oneillkza 

I thought we automatically downloaded the `dna_r10.4.1_e8.2_4khz_stereo@v1.1` model if it wasn't found in the model directory, but we don't. Thanks for reporting - I will get this fixed.

**Comment by oneillkza** [comment]
Glad to have picked it up!

**Comment by iiSeymour** [comment]
Fixed in https://github.com/nanoporetech/dorado/commit/24db2739971239fc45a93ed47920be72698bd0b4.
