### ISSUE TITLE
how fast it is to convert from pod5 to fast5.

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/dorado#121]
Hi, thank you so much for sharing this tool and detailed document.

I would like to know how fast it is to convert from pod5 to fast5.  For promethION data, there are a lot of .fast5 files, meybe 20 millions reads , if I transfer these files into .pod5, how long does it take?

Thank you so much!

**Comment by iiSeymour** [comment]
see https://github.com/nanoporetech/pod5-file-format/issues/25
