### ISSUE TITLE
use dorado to call modifications

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/dorado#122]
Hi, I would like to know if I use dorado to call modifications by using --modified-bases, it means dorado will use remora trained model to do the modification calling, right? What the difference between 1. using dorado to do the basecalling and modification calling at the same time. 2. using dorado to do the basecalling, and then using remora to do the modification calling. 

Thank you very much.

**Comment by cjw85** [comment]
Primarily ease of use. There is no reason to prefer using remora over Dorado.

**Comment by Psy-Fer** [comment]
As someone who has done this a fair bit with various tool combinations for the last few years, using the basecaller to call mods at the same time as basecalling is definitely easier than doing it in multiple steps.

So yes, use dorado to call mods when you basecall.

**Comment by Flower9618** [comment]
I see.  I just think that if dorado does the basecalling and mofication calling at the same time, the performance of modification calling may be affected.

**Comment by Psy-Fer** [comment]
It won't impact the accuracy at all.

**Comment by iiSeymour** [comment]
@Flower9618 it's same remora model - no performance/accuracy concerns.
