### ISSUE TITLE
Does Dorado do adapter trimming? 

### ISSUE THREAD

**Issue by pqzhang256** [nanoporetech/dorado#123]
Does Dorado already have adapter trimming built-in with the basecalling process? Or additional trimming is needed?

**Comment by iiSeymour** [comment]
@pqzhang256 dorado doesn't currently do any adapter trimming.

**Comment by tijyojwad** [comment]
Hi @pqzhang256 - adapter trimming was released as part of v0.5.0. you can download the latest version from https://github.com/nanoporetech/dorado#installation and give it a try!
