### ISSUE TITLE
Dorado fails with subfolders

### ISSUE THREAD

**Issue by olawa** [nanoporetech/dorado#124]
MinKNOW stores files in subfolders for different runs and for pass and fail. Guppy handles this with -r and duplex_tools has no problems pairing fail and pass reads but dorado silently quits with 0 reads found. Why not let dorado by default handle MinKNOW output folders?

**Comment by iiSeymour** [comment]
Recursive directory traversal adding in [v0.2.2](https://github.com/nanoporetech/dorado/releases/tag/v0.2.2)
