### ISSUE TITLE
dorado fails with 'CuBLAS error 8'

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/dorado#125]
When I run dorado with 'dna_r10.4.1_e8.2_400bps_sup@v4.0.0' model, it will fails with the error:
`[2023-03-16 07:48:21.498] [info] > Creating basecall pipeline`
`[2023-03-16 07:48:40.892] [error] CuBLAS error 8`

What is the problem means?

Thank you very much!

**Comment by iiSeymour** [comment]
@Flower9618 what GPU are you running on? Can you post the output from `nvidia-smi` and `ldd .../bin/dorado` _(where `...` is replaced with the path containing dorado)._

**Comment by Flower9618** [comment]
GPU is V100. 
Here is the output of `nvidia-smi` and `ldd ./bin/dorado`:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/77596901/225788676-a215a68b-6164-4f68-a3fb-8780199a9f2f.png">
![image](https://user-images.githubusercontent.com/77596901/225788829-a19f52e5-b85a-4510-b513-0d0d49a027bf.png)

Thank you so much!

**Comment by iiSeymour** [comment]
I see dorado is linking against `libcublasLt.so.11` in `/data1/ronggiao/software/cuda-11/1/lib64` and not the dorado lib directory. Can you add the dorado lib directory to the front of the `LD_LIBRARY_PATH`. 

```
$ export LD_LIBRARY_PATH=/mnt/dc2_dc1stor_data302/data01/rongqiao/Softwares/dorado0.2.1/dorado-0.2.1-linux-x64/lib:$LD_LIBRARY_PATH
$ ldd /mnt/dc2_dc1stor_data302/data01/rongqiao/Softwares/dorado0.2.1/dorado-0.2.1-linux-x64/lib/bin/dorado
$ /mnt/dc2_dc1stor_data302/data01/rongqiao/Softwares/dorado0.2.1/dorado-0.2.1-linux-x64/lib/bin/dorado -v
```

**Comment by Flower9618** [comment]
Thank you so much. It works for me. Dorado starts running after I set the LD_LIBRARY_PATH. 
However, the speed is very slow. num_workers is 2, which is default setting. Any ways to be faster?

Thank you so much!!!
