### ISSUE TITLE
Q: limit CPU resources (threads)?

### ISSUE THREAD

**Issue by sklages** [nanoporetech/dorado#129]
`dorado` seems to use all available CPU resources, spawns a lot of threads (corresponding to the number of CPUs, including a few `cuda-EvtHandlr` threads).

Will there be a parameter for restricting threads, e.g. `--threads` during basecalling?

**Comment by iiSeymour** [comment]
Hey @sklages with each release we monitor the resource usage with GNU time _(among other techniques)_ and the CPU load average wasn't something I've seen to be problematic. 

How are you measuring CPU resource usage and can you provide the CPU and GPU information for the system please?

**Comment by Ge0rges** [comment]
Hi I am still interested in whether we can give dorado a maximum number of CPUs to use the same way that can be done with GPUs using the `-x cuda:0,1,2` flag is there `-x cpu:0,1,2`?

**Comment by sklages** [comment]
@Ge0rges - you probably don't want to pinpoint the actual CPU IDs in the `dorado` call. Better to specify the number of threads to be used in general for cpu-based basecalling..

**Comment by Ge0rges** [comment]
Which argument is used to specify the number of threads?

**Comment by sklages** [comment]
for basecalling there is none (yet). You should probably open a new issue with a feature request for that.
