### ISSUE TITLE
Failed to find the kernel: lstm_simd_768_fwd_16

### ISSUE THREAD

**Issue by thomasvangurp** [nanoporetech/dorado#13]
Using dorado version  `0.0.1a0`.
  I've successfully built dorado on my mac, downloading basecaller models works. I do however get the following error for the super accurate model:
```
(base) mbp-van-thomas:bin thomasg$ ./dorado basecaller dna_r9.4.1_e8_sup@v3.3 fast5_pass
> Creating basecall pipeline
Failed to find the kernel: lstm_simd_768_fwd_16
```

**Comment by gbouras13** [comment]
Mac M1 dorado v 0.0.1, identical error for me

**Comment by iiSeymour** [comment]
Fixed in https://github.com/nanoporetech/dorado/commit/fcc230e194d2a261f54dfa39d59fe9ab896e70d0
