### ISSUE TITLE
Q: alignment support with supplementary alignments?

### ISSUE THREAD

**Issue by sklages** [nanoporetech/dorado#130]
When you are implementing alignment support with `minimap2`[1] will you keep supplementary alignments? At least as an option? 
In `bonito` these alignments are removed and not present in the final BAM file [2].
That's why we are currently separating the basecalling step from the alignment step in our current "bonito workflow"..

[1] https://github.com/lh3/minimap2/issues/1030
[2] https://github.com/nanoporetech/bonito/issues/318

**Comment by iiSeymour** [comment]
@sklages I'm working through the implementation of this currently so thanks for raising. Yes, I can make supplementary alignments available.

**Comment by sklages** [comment]
@iiSeymour - I haven't built/tested yet, but does `dorado` keep supplementary alignments in `v0.3.0`?

**Comment by tijyojwad** [comment]
Hi @sklages - yes supplementary alignments should be there in the output. Let us know if you see otherwise

**Comment by iiSeymour** [comment]
dorado's aligned output matches minimap2 w.r.t sec/sup records and included tags.

**Comment by ziphra** [comment]
Hi, I think dorado aligned bams miss the SA tag which gives information about supplementary alignments. I used v0.3.1. This is required for some variant callers I believe. At least, sniffles needs it to call translocation.

**Comment by tijyojwad** [comment]
Hi @ziphra - thank you for highlighting this! SA:Z is indeed missing. We will add it to the next release

**Comment by iiSeymour** [comment]
@ziphra the SA tag is now present in the v0.3.3 release.
