### ISSUE TITLE
fail to transfer sam file from dorado to other format.

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/dorado#131]
Hi, I try to transfer .sam file from dorado to .fastq or .bam, but it fails. There are the error message:

1. .sam to .fastq:
`samtools fastq test.sam -T MM,ML > test.fastq`
`Problem copying aux tags: [@02f1f969-7194-46e2-a19f-841278a5b70a        MM:Z:C+h?,6,9,18,94,283,36;C+m?,6,9,18,94,283,36;       ML:B:*** Unhandled aux type ***]`
`[bam2fq_mainloop] Error converting read to FASTA/Q`

2. .sam to .bam:
`samtools view test.sam -Sh > test.bam`
`[E::sam_parse1] incomplete B-typed aux field`
`[W::sam_read1] Parse error at line 2893`
`[main_samview] truncated file.`

Is there any advice for this situation? Thank you very much~

**Comment by sklages** [comment]
which `samtools` version are you using?

How does the record in question look like? E.g.:
```
fgrep '02f1f969-7194-46e2-a19f-841278a5b70a' test.sam
```

**Comment by Flower9618** [comment]
Thank you for your reply.

The version of samtools is:
`samtools --version`
`samtools 1.9`
`Copyright (C) 2018 Genome Research Ltd.`

The command and the result is:
`fgrep '02f1f969-7194-46e2-a19f-841278a5b70a' test.sam`
`02f1f969-7194-46e2-a19f-841278a5b70a    4       *       0       0       *       *       0       2827    ATGTTACTGCCTACACTGATTTCAGCGTATTGTTAAATTATGAACTTTGTGAAAATATCCAGTGCAAGAATTCTCCCTAAGGGAAAATATGAACTTGACGAATGCTCTGATCAGTGAATCAGGTGGCTTGTGGTTCATGAGTGGCAGCAAAGTTGTAAAATGGAGAGAGAGAGAGAGGTTAATATTTTAACAAATACCCTTTGTGTTGAAATTCAAGATGTTACTAATATTTGATATCCTGAATTTTAATTCTAAAGAAAAAAGCAGAACGCCATGTCTTGATAAAACATTTCTCAGGTCTAGGAAATTAGACATCAATTATATTATTGGAGAGTTACATTGATCACACATCTGACACTGGGTAGATTTTCCTTTTAAAATCATTTAATACCTCAAAGCTTAAAATCTTGAATTTCATGTGACCCTTGCCCAATTGAGAACTGATTATGTGTATAATGTGTGCTCAGGATTATAAAATGATTCATCTAACTATGTCAGCAGCAACTTTCTCCTCAGTTATGATTGTATCCACATTGTGATGTTCCATACCAATCTTGTCTCCTCCCCCTAAAAATTGATTTCACTGTCATCACATCATCATTAGCATCTCTATATATTGCAAAGTTATAAGTAATGGGCTGTTGGATATGGAAGATAACATTCATCCAGTTTTCAAGTGTTAACTGTCTGCTGTTTGTCAGACACTGACTATGGCCAATTGCTGGTGACCACAAAACAGAGATCTTTGCTAACGTATGAATTTACACTCTAGCAGAAGTAGACAGATGATAATCAATAGGCACAATAAGTAAGAATGAGTTATAATAATAGGGGTGGTAAAAGCTGTAAATTCTACTCTTTATTGATACTTTTTATTTTGGTCATGTCTTTTTTTCCTATTTTCACTTAGTTCTTTGTCCATGGTTTCCTGTAGCTCTTTGAGATATTTAAGATAATTGATTTAAATTCTTTGTTTAGTAAGTCCAATGTCTGGGCTCCTTTAATGGACAGTTTCTGTGATTTTTCCTCCCTTTGAATAAGCCATATCTTCCTATTTATTTGTATTTTTTAAAATTTCTGTTGTCAAATCCTTGGCATTGGAATCTTATGATGTAGTAGCTCTAGAAATAGGATTTTCCACTTTCCCCTTAGTATAATGTTCTTGATTGTTGAAGGCTACAATCAAGTTTGTTTAGTGACTTTTCCATACTATTTTCTGCAAAGATTGTATTCTTTGTCATGTGTGATTACTGAAATCTGTTTTTTTTTTTAACCTTATCTGGCCAGAGTGTGTAGATTTGTCTCAAATGTTTACAACTATGAAGAAAACAAAACAACAACAAAAACAAAACAAAACAAAAAAACACTCCAGTCTTTGCTGATTGGTCCTGTGCTGGGACATTCTGTCAACCCTTAGTTAGGCCCCTCATAACTGTGCCTTATCTTTCACTTCCTGCTTGCCCTGACCTAGGTCAGTCACCAGTGAAAGCTTAAGGTCTTCTCAGGTCTTTTCTGAGTGTACACCCTGCCTGGACATGCCAATAGGGGTTTCTAAATTCTCTATTTTACATAGGTACTTTTGAGATGCCCTCATTTTTCAGAAGAACTGCTTTCAGCTTTTCTCCTAGGCTTAATGCTGTATATTGCATGCCTCAACTTTAATCCTTTGCCCCAGGTGGCTGTGGGATTTCATTCACCTCACAGTGTTTTCTAGCAATGCCTCCCTCTCTCCACCCTAGAAGTTCTAGACTTCCAGTGAAAAAGAAAACAAATAAACTTTGTCCATCCTTCAGGTCCTTACCAGACAAATTAGAACAGACAAATACAATAATTTGTGAATAAATTAGTCTTTATTCCCTCTGGAACCCTGCTATGAGGATCCCACAATAGGCACATTGACCCTCTGTTCTGGCCACTGCTAAGCCTGGTAAGAGGTCAGAAGACAGTCAGAAAATCTGCACAAAGCTTTCCCATCCTATTATTCTCTTTGATTTAATGTTCACTTAGTTCTGTAAACCTTTAGTTTTCAGCATTCTAGAAAATTGGTTTTGAGCAGTTCTATTTGCTTCAATATTGTCTGGAAGCAGGCTTGGACTGCCTACTCTCCATTTATTAACATTCACACCTGACAAGTGCTATAAAGTAAGAATAGAGCAGGGAGAAGGAAAACGTTAGAGTGGTCAGGGGTGTTGCAATTTTAAATGGAGTGGTAAAATTCTGCTTAGTGAGATCTCTTTTGATAAGTGATTTGAATAAAGATGGAGAGAAAGGAATTATAATCTGTATCAGGGAAAAAGTGTCTGGGCATAGAAAACACTGCCAGGGTATTAATGAAGGAGCACACTGGGCATGGGTGAGAAACAGCACAGAAACTGGTAAGCCAGAGACACATGAGGAAGAGGGAGATGAAGTCAGGATATAAAAGGAGGGAGTAGGATCTTTCATGGGACAATCCAGGTGATTGCATGGACTTTGCTCTAAGGATTACGAGTAAAGTCTGAGACCATTGTAAGGTTAGCACAGGAATAACCTGATCTGTCTTATGTATTAAAGGATCATATTGGCTATTAGGCTGAATGCAGAATATAGGGTAAGAAGGATAATATCTAGGAGACTGGTAATGAGGTTTATCCCAGACATCCAAAGAAACAACAACCACCAGCAACAAAAAACAAATGGCAGTAGCAGTCAGGGTAAAGCAGGGTGTAATGCTGAAGATAATGAAATAAGTCTGGATTTACAAAATATATTTTGAAGCTGAATAGGGATTTGAGACAGGAAAAAATATAAGAATGACTGCAAGGTTTTTACTTGCATAACTAAAGTA       %%&()&%%$$$#####$$%%%%%&'&&&'/3833331/1B@>>=999952111576/+))))+*++))*,-,***,,*,3467/9705--,.../1--,-.100..--(((''''(,-(%%%%$$$$%(+.10..,'((../014489==>?CC?>???CC>211&%'+*--/./.1,++++/..-**))'('&&('((((0*+3//..:856((&%$$'&)&&%''')/7:+,@AAFDFFGGAEJII{LH?=<9645*.AA=;96,)(''')'&&&'))++-1225?DCBA9<@?@EA@A:999:;<:888:==CDDFKFJ>><::;:100)('''+010000/0////@79@AACADDHDBD:::99=;95/-)').4(((((A>?E@>>>=@DFB?><....:/.-0027;>9::::9:?B@@B/././A+,999::666@?@ADCDDBCBABCCDDDEEDCCD=====GGNFPEECDCCDCECEFDGJFCC......:;;78864432+%$$####$$$%%&&*,,-9;<<;;,,,,,-,,..('&%$$$%'%$$$$&(*..1225559;:81'''../38;;????ACDH98888FIKECDDCQCB@DFEBA?>=>GFFGGDEFBAAAGEECBBA@BAABDFEFEDCCEEF:999A?87;>CGCB@@?=ADCCCECFDDEDBBABDDFF>B@DCGDFGEEFDDEEEEDBBB@@??100.-*******,0199=BBBCCCECHDCAAA??@@?BFCFEGDECACCCDCEAA999:E@@@ACBDDEEEGH=<<<<>BCBDDDD=:9876/.)'&&&%#####$$'+,089<=<<<0///165****()/*+/00:99;8<@12=;7667BEDGFO=<<88?A??==::;;;<<><////.'&&&&%'')+,,-19<=<=@???@BDCCA=<<=??BECCCBBAAFHB@<;9776733334ACDD?9998-,,,+,11<9::99::<?86/(&%%%%%%%'0211//0////****$$$$$))'&&&''(+,(4BCCCA<;;<=>76654677;AAEEEA@???=?FE@BDAEC6/++++22267:;:88879;;;<,++++,86++,;<==<99998:87876899=;9999;5?93244.**60,4+,899:CECE988855777::211223;30-/112544553320*+755568:;88323/..-.6/.710001//--,/357>?@B88665779:9::::>><<=??<<;96577?AEHEB?;9877.-,,&&&'''$&&&(())+++--''''&'''++,''%%&&''''''(2355<:<;;<<DB?@A==AACEE98ACA:7::85246688765201,,44463---,-22266.----4:9000039:<7777000006.2---34452262-678::;<98778;<?@>A?712=>?>>>><=>===<;;;<><;;:;8754334666;>>>@;9999===>:943334<;;;<=?=74(()00:88888:6686((3)).-,+*'')''((+).+(('(*+;5666588;51300---,,,++-6,****+,997/.-.-+)'))()(&'(())((()*++..-1./))).04446=?BA?>=>=?>>?=;::9:76566<<?4)=<<<==?>==;:85/)()&&&((,,'''')))1117:;;;?===<>>>145111<<=>=<;:99654-,12,*,+)*..//00))))*/31(&%%%%'''&)*++++'-0.(3391899,545018778--4320//0...++,1444339888678...0>?@CCCA?>>?@>?9888('''-&&'&%%&&)+1224,+*(('''))'''''+//0//...+,//05665697651012/'(7557/.&&&&69:;;<<<<=<=====>=<:98'&&&)((-.-/))))*+0.%$$$$&'--....-,--()/.-,*)%&)'&&&&71133399;;553224-(())+,,-1114<:94--01=<110/./0)($$&'(*8:555553''&&&)(+&&+++100//..21121+*(''('$$$%$%$%%'&&%%%$$$%*+++&%%&(+-,,,,,::2(()))+3---4423479==65433.+)((&%&%&&*-/-,+**)'''00*--,'''(+,-.,,,,,84:<<<<;;;;>?>@B@A?><;--,*))*,...-+++%%&&&&'(((()*3416;;;;;88899;;:9440-*)(()((('')&*(((((($$$%%''&&&)*,-/34)))))3....48>=20//1323333498798.((((((/022023----45)))2699;;;322123335544/''(-+-'%%$$$$$$$$&))11/+++,,'''')/1899;:0000+++***))((())./,++(((&&&&'%&%%$&(&&'))+*'''-..<>?@@?>??<;;;;=@1/.*)&%%%%&&&&%$$$%'')/'&$$$$%''()((''(+++'&&&*'()****)))*+./-----..12562**()668965556<=:9999:;:8878889;?><877755444334224431121253//../.11033222667777666.&-*(((*(''(+)&&(.=>?=BD@@>=771/.,'''(,,,+*,*)(((*+,-00/01///('''')&&'&&''')+-,--;;9:99;:9977::89998754.-****+,*)))*+78=7666647764621234:65566:55543221./154/.-)(((.,'&'**.233355568=633334;;66541(%%%%       qs:i:11 du:f:7.033250   ns:i:28133  ts:i:10  mx:i:4  ch:i:1898       st:Z:2023-03-10T20:45:33.944+00:00      rn:i:644257     f5:Z:PAI27129_pass_218202b0_7713927b_2036.pod5  sm:f:108.251    sd:f:30.049  sv:Z:quantile   RG:Z:218202b0-40fe-4cae-985c-8dc936815d92_dna_r10.4.1_e8.2_400bps_sup@v4.0.0    MM:Z:C+h?,6,9,18,94,283,36;C+m?,6,9,18,94,283,36;   ML:B:C,5,13,23,1,255,4,1,242,232,254,0,1`

Thank you so much !

**Comment by sklages** [comment]
Without having a closer look at the record, my first try would be to update `samtools`/`htslib` to current version (`1.17`) as `1.9` is quite old and much development has been done since then... 

Then you can also use `samtools view -T "*"`.

**Comment by Flower9618** [comment]
Thank you so much. updating the version of samtools is useful for me.
