### ISSUE TITLE
dorado on Apple M1 Ultra / GPUs

### ISSUE THREAD

**Issue by ishengtsai** [nanoporetech/dorado#133]
Hi,

I am wondering if a benchmark on Apple M1 Ultra basecalling is available, and whether you would recommend it please? We are thinking to get a lab shared computer with MinION attached on it and Apple Mac studio seems to be a reasonable choice if dorado is continually supporting alternative chips.

**Comment by iiSeymour** [comment]
Hi @ishengtsai - we are committed to supporting Apple Silicon in Dorado.
