### ISSUE TITLE
Build error on AWS Ubuntu instance

### ISSUE THREAD

**Issue by eyesmo** [nanoporetech/dorado#134]
I'm trying to install/configure Dorado on a t2.micro AWS instance running Ubuntu, so that I can save an AMI/Docker image and then spin that image up on a beefier GPU-enabled instance. (For my uses I prefer building to installing a pre-compiled binary).

When I run
`cmake -S . -B cmake-build` 
I get the following error message:

```

CMake Error at cmake/DownloadAndExtract.cmake:19 (file):
   file failed to create dictionary:
   /home/ubuntu/dorado/dorado/3rd party/torch-1.13.1-Linux
Call Stack (most recent call first):
   cmake/Torch.cmake:88 (download_and_extract)
   CMakeLists.txt:41 (include)
```

Any help greatly appreciated!

**Comment by iiSeymour** [comment]
@eyesmo I see an unexpected space in `/home/ubuntu/dorado/dorado/3rd party` - do you have any local changes?

**Comment by iiSeymour** [comment]
Also how much space do you have in `~` *(df -h ~)* as torch is quite a large download.

```
3.5G    dorado/3rdparty/torch-1.13.1-Linux/
```

**Comment by iiSeymour** [comment]
@eyesmo let me know if this is still an issue.
