### ISSUE TITLE
Unidentified modified bases argument

### ISSUE THREAD

**Issue by hgreenfield124** [nanoporetech/dorado#137]
My command: 

echo "~/dorado_new_heather/Dorado/dorado-0.2.1-linux-x64/bin/dorado basecaller -r 8 -x cuda:\${SGE_HGR_gpu#'cuda'} ~/dorado_new_heather/Dorado/dorado-0.2.1-linux-x64/lib/dna_r10.4.1_e8.2_400bps_sup\@v4.0.0 ../pass --read-ids New2_read_ids_to_run.tsv --modified-bases 5mCG_5hmCG >  NA14044_3_methylation_readIDs.sam -" | qsub -P applications -V -cwd -l gpu=1 -pe mt 16

Error seen attached. Even moving modified bases before read-ids didnt work.

![image](https://user-images.githubusercontent.com/97462404/227949873-16fe8938-2fb1-4cc8-a3c3-68e3d7719408.png)

**Comment by iiSeymour** [comment]
@hgreenfield124 you have a trailing `-` after the output file name.
