### ISSUE TITLE
Performance drop after 400k reads

### ISSUE THREAD

**Issue by ethan-mcq** [nanoporetech/dorado#138]
Hi, we're running Dorado on a 3090 w/ 24gb memory. We are running cuda all and it is running just fine until we hit 400k reads processed, then the performance drops and Dorado then only runs on about 30% of the cores. Anyone had a similar problem with Dorado? I have a video of the performance drop if anyone would like to see it. Let me know if there is any output you would like to see.

**Comment by iiSeymour** [comment]
@ethan-mcq what command are you running when you see this (simplex/duplex/mods)?

**Comment by iiSeymour** [comment]
@ethan-mcq let us know if you still see similar behavior with the latest version.
