### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by partha434** [nanoporetech/dorado#139]
Hi,
While running cmake -S . -B cmake-build, I got the following error.

CMake Error at CMakeLists.txt:307 (find_library):
  Could not find AEC_DLL using the following names: aec

Please help.

**Comment by MicroPriya** [comment]
Hello,

Trying to install Dorado- 
cmake --build cmake-build --config Release -j
got following error-
[  8%] Built target htslib_project
[ 15%] Built target streamvbyte
[ 17%] Built target dorado_allocator_lib
[ 19%] Built target edlib
[ 36%] Built target minizip
[ 37%] Building CXX object CMakeFiles/dorado_io_lib.dir/dorado/data_loader/DataLoader.cpp.o
[ 41%] Built target vbz
[ 42%] Building CXX object dorado/3rdparty/elzip/CMakeFiles/elzip.dir/src/unzipper.cpp.o
[ 43%] Building CXX object dorado/3rdparty/elzip/CMakeFiles/elzip.dir/src/elzip.cpp.o
[ 45%] Built target vbz_hdf_plugin
In file included from /data/Softwares/dorado/dorado/data_loader/../read_pipeline/ReadPipeline.h:2:0,
                 from /data/Softwares/dorado/dorado/data_loader/DataLoader.cpp:3:
/data/Softwares/dorado/dorado/utils/AsyncQueue.h:5:20: fatal error: optional: No such file or directory
 #include <optional>

CMakeFiles/dorado_lib.dir/build.make:271: recipe for target 'CMakeFiles/dorado_lib.dir/dorado/modbase/remora_scaler.cpp.o' failed
make[2]: *** [CMakeFiles/dorado_lib.dir/dorado/modbase/remora_scaler.cpp.o] Error 1
CMakeFiles/dorado_lib.dir/build.make:215: recipe for target 'CMakeFiles/dorado_lib.dir/dorado/decode/beam_search.cpp.o' failed
make[2]: *** [CMakeFiles/dorado_lib.dir/dorado/decode/beam_search.cpp.o] Error 1
CMakeFiles/Makefile2:270: recipe for target 'CMakeFiles/dorado_lib.dir/all' failed
make[1]: *** [CMakeFiles/dorado_lib.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

Kindly help :)

**Comment by sklages** [comment]
> Hi, While running cmake -S . -B cmake-build, I got the following error.
> 
> CMake Error at CMakeLists.txt:307 (find_library): Could not find AEC_DLL using the following names: aec

`libaec` is not found, so install `libaec` on your system. Either with your package manager or via github (see https://github.com/MathisRosenhauer/libaec.git)

**Comment by sklages** [comment]
> Hello,
> 
> Trying to install Dorado- cmake --build cmake-build --config Release -j got following error- <...>

have you installed all linux dependencies? https://github.com/nanoporetech/dorado#linux-dependencies

**Comment by MicroPriya** [comment]
> > Hello,
> > Trying to install Dorado- cmake --build cmake-build --config Release -j got following error- <...>
> 
> have you installed all linux dependencies? https://github.com/nanoporetech/dorado#linux-dependencies

Yes.

curl 7.87.0 (x86_64-conda-linux-gnu) 
git version 2.17.1
ca-certificates  (20211016ubuntu0.18.04.1)
build-essential (12.4ubuntu1)
Cuda compilation tools, release 11.8, V11.8.89
libhdf5-dev  (1.10.0-patch1+docs-4)
libssl-dev (1.1.1-1ubuntu2.1~18.04.21)
libzstd-dev (1.3.3+dfsg-2ubuntu1.2)
cmake version 3.26.3
autoconf (2.69-11)
automake (1:1.15.1-3ubuntu2)

**Comment by partha434** [comment]
Thank you so much

**Comment by partha434** [comment]
> > Hi, While running cmake -S . -B cmake-build, I got the following error.
> > CMake Error at CMakeLists.txt:307 (find_library): Could not find AEC_DLL using the following names: aec
> 
> `libaec` is not found, so install `libaec` on your system. Either with your package manager or via github (see https://github.com/MathisRosenhauer/libaec.git)

Thank you so much....it worked

**Comment by iiSeymour** [comment]
@MicroPriya which compiler and version are you using? It doesn't appear to fully support C++17 which is required to compile dorado.

Is there a reason you are compiling over using the prebuilt binary?

https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.2.4-linux-x64.tar.gz
