### ISSUE TITLE
CPU bottleneck on M1 Max?

### ISSUE THREAD

**Issue by itslittman** [nanoporetech/dorado#143]
I notice at the beginning of basecalling, Dorado uses the GPU, but after a while GPU usage drops to 0 even though the process hasn't finished. The CPU is used until the end of the run. Is this symptomatic of a CPU bottleneck on Apple Silicon?

Noah

**Comment by sklages** [comment]
same here on M1 Pro, see https://github.com/nanoporetech/dorado/issues/117#issuecomment-1477950143

**Comment by itslittman** [comment]
@sklages I'm wondering if it has anything to do with this: https://twitter.com/VadimYuryev/status/1514295682777059329

Interesting read, not sure if it's relevant here.

**Comment by sklages** [comment]
@itslittman - interesting, sounds reasonable and could be an issue ... but that's not my area of expertise. :-)

**Comment by Psy-Fer** [comment]
Are you using fast5 or pod5 with dorado?

**Comment by sklages** [comment]
`pod5` in my case.

**Comment by Psy-Fer** [comment]
While a tad slower, i'm willing to bet if you used fast5, you won't have the same issue. 

Which version of pod5 are the files? It could be if you update to the latest version you won't have this issue (as the solution might overlap with the limited virtual memory issue we had). But would have to test and see.

**Comment by iiSeymour** [comment]
@sklages @itslittman which basecall model are you seeing this with and how much unified-memory does your system have?

**Comment by sklages** [comment]
@iiSeymour - System (at the time testing):
- MBP M1 Pro (14", 2021)
- MacOS 13.2.1
- 32G RAM
- GPU cores 16, Metal 3
- dorado 0.2.1+c70423e (pre-compiled binary)
- small pod5 dataset (40K reads), file version 0.1.4. 
- basecalling models were `dna_r9.4.1_e8_fast|hac|sup@v3.3`

Silicon M1 has not a high priority for me yet, as our workhorses are still linux-based servers. I was just curious how `dorado` performs on my MBP :-)

**Comment by sklages** [comment]
> While a tad slower, i'm willing to bet if you used fast5, you won't have the same issue.
> 
> Which version of pod5 are the files? It could be if you update to the latest version you won't have this issue (as the solution might overlap with the limited virtual memory issue we had). But would have to test and see.

well .. for me currently no high priority .. pod5 is still `0.1.16` ..  I am waiting for `0.1.17` (https://github.com/nanoporetech/pod5-file-format/issues/33) to get some things done. Then I will rerun some small datasets on my MBP (mainly for rough benchmarking) ..

**Comment by itslittman** [comment]
@iiSeymour I'm using the HAC 400bp DNA model with 5mc and 5hmc. I'm running it on M1 max, 32G RAM, 32 core GPU, 10 core CPU. 
I just started a run using fast5 instead of pod5 as input, and it seems to be running faster and using fewer resources.

**Comment by itslittman** [comment]
@iiSeymour Also, I got incorrect/nonsense basecalls with a manually selected batch size (no Dorado errors though). I got correct basecalls (but slower running) with the automatic batch size. And either way, GPU usage goes to zero about an hour into the run. After that, around 2.5 CPU cores (out of 10) are used, and then a few hours later, one core (until conclusion).
