### ISSUE TITLE
Modified bam results

### ISSUE THREAD

**Issue by partha434** [nanoporetech/dorado#145]
Dorado produces basecalls in unmapped bam file. How can I check the modifications from this bam file?

**Comment by sklages** [comment]
Map your data on your reference genome using `minimap2`<sup>[1]</sup> and then run `modbam2bed`<sup>[2]</sup> on the alignment file. You can check the results in e.g. IGV<sup>[3]</sup>

<sup>[1]</sup> https://github.com/lh3/minimap2
<sup>[2]</sup> https://github.com/epi2me-labs/modbam2bed
<sup>[3]</sup> https://software.broadinstitute.org/software/igv/

**Comment by partha434** [comment]
But this is an unmapped bam file. How can I map a bam file to reference genome?

**Comment by Psy-Fer** [comment]
You can go ubam to fastq and carry the meth tags with something like this
`samtools fastq -TMM,ML ${USAM} |  minimap2 -x map-ont -a -t ${num_threads} -y --secondary=no ${REFERENCE} - > ${SAMFILE}`

The magic here is the - T that tells it to carry the MM and ML tags to the fastq, then the -y in Minimap2 tells it to carry them back to the bam.

Then you can use modbam2bed and other downstream tools.

**Comment by cjw85** [comment]
If you do:

```
samtools fastq -T '*' ....
```

you can carry all the tags from the SAM without loss.

**Comment by iiSeymour** [comment]
@partha434  we are working on producing aligned BAMs for the next release.

Note: you need at least samtools 1.16 _(Aug 2022)_ for `samtools fastq -T '*'` https://github.com/samtools/samtools/releases

**Comment by partha434** [comment]
Thank you so much for the codes. This really worked for me... @Psy-Fer @cjw85 
Eagerly waiting for an update related to this on Dorado @iiSeymour

**Comment by iiSeymour** [comment]
v0.3.0 adds the ability to output aligned BAM directly from the basecaller as well as `dorado aligner` which can map/remap uSAM/uBAM and retain tags. 

https://github.com/nanoporetech/dorado#alignment
