### ISSUE TITLE
About 5hmC detection results by dorado

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/dorado#146]
Hi, previously, I ran dorado by the setting '--modified-bases 5mCG_5hmCG', which means dorado will divide C into 3 groups, uC, mC and 5hmC. 

Then, if I just want to divide C from the same dataset into 2 groups, mC and uC, there are two ways, one is rerunning dorado by setting '--modified-bases 5mCG', but it will take some times, another way is using the previous 3-group result directly, just put 5hmC and mC into one group, and uC another group. 

I would like to know the accuracy of these two methods. Which method do you suggest？

Thank you so much!

**Comment by iiSeymour** [comment]
Hi @Flower9618 you don't need to re-basecall for this. Please see modkit https://github.com/nanoporetech/modkit

**Comment by Flower9618** [comment]
Thank you so much. I will try the tool.

By the way, I wonder if I just add the 5hmC and mC probability, the result is the same as running dorado by setting '--modified-bases 5mCG'.

**Comment by iiSeymour** [comment]
See https://github.com/nanoporetech/modkit/blob/master/collapse.md

**Comment by Flower9618** [comment]
I see. Thank you so much.
