### ISSUE TITLE
Add sequencing summary file as output

### ISSUE THREAD

**Issue by RenscoHogers** [nanoporetech/dorado#147]
Hello,

I am not sure if this is possible, but if so, it would be great if dorado could output a sequencing summary text file.
This is done by guppy and is used by quality control tools, and gives more information than the fastq files alone.

Thanks in advance!

**Comment by godotgildor** [comment]
I'd like to second this request.

Alternatively, in @vellamike 's talk describing Dorado, he mentioned that much of the information contained in the summary.tsv files could be retrieved using the uBAM output. If there were a script or description on how to convert from the info in uBAM to the summary.tsv, that would be helpful too.

I took a look and was able to find some fields, while others I'm still not sure where to grab them from.

```
seq_record_dict = {
        "filename": tags["f5"],
        "read_id": seq_record.query_name,
        "run_id": None, # Don't see run_id anywhere.
        "channel": tags["ch"],
        "mux": tags["mx"],
        "start_time": tags["st"],  # Currently in ISO Datetime. The summary.tsv expects a float?
        "duration": tags["du"],
        "template_start": None, # Not sure where to get this from?
        "template_duration": None, # Not sure where to get this from?
        "sequence_length_template": None, # Not sure where to get this from?
        "mean_qscore_template": None # There is the "qs" tag which gives mean basecall qscore rounded to the nearest integer, but expect a float. If we calculate the mean of quality scores, this != the int value for some reason.
    }
```

**Comment by cjw85** [comment]
The `fastcat` and `bamstats` programs from: https://github.com/epi2me-labs/fastcat, might be of interest. Though they are perhaps an incomplete solution and `bamstats` is mostly concerned with aligned reads. The tools are used extensively in the EPI2ME Labs Nextflow workflows (where there was a conscious design choice to not rely on users having kept their sequencing summary files).

**Comment by godotgildor** [comment]
Thanks @cjw85 - I'll take a look at fastcat.

**Comment by RxLoutre** [comment]
Upin this request, I also would like to see a sequencing_summary generated for the same reasons (QC tools use sequencing summary to report the metrics about reads length / quality etc)

**Comment by iiSeymour** [comment]
You can now produces a summary tsv with `dorado summary calls.bam`. This will produce a summary file which matches bonito and I have tested the output with PycoQC.

**Comment by IdoBar** [comment]
Hi @iiSeymour ,

Does `dorado summary` also work with `fastq` files generated from `dorado basecaller --emit-fastq` command?

Thanks, Ido

**Comment by RxLoutre** [comment]
Up on @IdoBar 's question, I have the same issue. I don't work with bam for dorado.

**Comment by fmobegi** [comment]
Did anyone ever get around to resolving this issue?

Recently switched to dorado from guppy and am unable to get decent reports with nanofilt because of the missing summary file

**Comment by IdoBar** [comment]
Hey @fmobegi 
I've resorted to a 4-step approach:
1. Emit the base-called sequences as `bam`
2. Generate the summary file with `dorado summary`
3. Extract the reads in `fastq` from the `bam` with `samtool` (then I can choose if I want the mapped ones or non-mapped or any other filter)
4. Separate the reads to single and duplex reads with `seqkit`

```
# basecall
dorado duplex --reference $REF.fasta -x cuda:0 --min-qscore 7 dorado_models/${MODEL} pod5/  > mapped_reads_Q7.bam
# generate summary file
dorado summary -v mapped_reads_Q7.bam > sequencing_summary.txt 
# extract reads (in this case I was after unmapped reads only
samtools view -Ofastq -f 4 mapped_reads_Q7.bam | pbgzip -c -8 > unmapped_reads.fastq.gz
# separate the duplex and simplex reads
seqkit grep -nri -p  ';' unmapped_reads.fastq.gz -o duplex_unmapped_reads_Q7.fastq.gz 
seqkit grep -nriv -p  ';' unmapped_reads.fastq.gz -o simplex_unmapped_reads_Q7.fastq.gz
```
You can then calculate the ratio of simplex-duplex with
```
DUPS=$(zcat duplex_reads_Q7.fastq.gz | gawk 'NR%4==1' | wc -l)
TOTAL=$(zcat all_reads_Q7.fastq.gz | gawk 'NR%4==1' | wc -l)
DUP_RATIO=$(bc <<<"scale=4;$DUPS/$TOTAL")
```
Definitely not the most straightforward method I could think of...

**Comment by fmobegi** [comment]
Thanks Ido. I will try this approach and see how it goes.
