### ISSUE TITLE
Dorado does not accept versions of libraries packaged with

### ISSUE THREAD

**Issue by saarantras** [nanoporetech/dorado#149]
I grabbed [dorado-0.2.4-linux-x64](https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.2.4-linux-x64.tar.gz) unzipped, added the bin directory to my PATH and the lib directory to my LD_LIBRARY_PATH. However, dorado seems to want different versions of the libraries that provided in the enclosed bin : It wants libcublas.so.11 when libcublas.so.11.11.3.6 is provided, libnvToolsExt.so.1 when libnvToolsExt.so.1.0.0 is provided & so on.

I got dorado to run by moving into the lib directory and executing the following:
```
ln -s libcublas.so.11.11.3.6 libcublas.so.11
ln -s libnvToolsExt.so.1.0.0 libnvToolsExt.so.1
ln -s libcudart.so.11.8.89 libcudart.so.11.0
ln -s libhdf5.so.8.0.1 libhdf5.so.8
ln -s libsz.so.2.0.1 libsz.so.2
ln -s libaec.so.0.0.10 libaec.so.0
```

Is this intended behavior?

**Comment by sklages** [comment]
Seems so, that's what I do when building `dorado` from source, there are additionally some libs with git tag:
```bash
 function link_lib {
   local file=$1
   # libcublas-f6acd947.so.11
   pattern="(.+)-[A-Za-z0-9]{8}(\.so)(.*)$"
     if [[ $file =~ $pattern ]]; then
       lib="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
       libn="${BASH_REMATCH[1]}${BASH_REMATCH[2]}${BASH_REMATCH[3]}"
       echo "Linking '$file' to  '$libn' / '$lib'"
       ln -fs $file $libn
       ln -fs $libn $lib
     fi
  }
```
and then ...
```bash
 cd $INSTALL_PREFIX/lib
 for file in *;do
   link_lib $file
 done
```

**Comment by HalfPhoton** [comment]
Closing as there has been no response from the original user. 
If your issue is still unresolved please re-open the issue.

Kind regards,
Rich
