### ISSUE TITLE
BUG: OutOfMemoryError, descrease default batch size for SUP 10.4 model and 24 Gb GPU

### ISSUE THREAD

**Issue by Alteroldis** [nanoporetech/dorado#152]
I got OutOfMemoryError with all batch sizes higher than 464.
RTX 4090 chip, 24 Gb of VRAM.
If you wish, I can testing other model and batch sizes with the card.

**Comment by iiSeymour** [comment]
Hi @Alteroldis thanks, I think I interpolated the 24GB presets and possible overshot the SUP.

The current max batchsize for SUP is 512, hac is 1536 and fast is 2048, if you could check those that would be very helpful.

https://github.com/nanoporetech/dorado/blob/master/dorado/utils/cuda_utils.cpp#L249

**Comment by Alteroldis** [comment]
@iiSeymour, I know, checked the code before writing request.
I will test other models in few days, there is intensive calculations now).

**Comment by iiSeymour** [comment]
GPU memory allocation is much better in recent releases of dorado and is no longer based on supported presets.
