### ISSUE TITLE
dna_r10.4.1_e8.2_400bps_sup@v4.1.0 basecalling does not start

### ISSUE THREAD

**Issue by kaufmanelij** [nanoporetech/dorado#156]
Hello! I am trying to call a ~1TB pod5 file from an adaptive promethion run. The files were converted from fast5. This is my first time using dorado (downloaded latest windows binaries today). For some reason it does not start basecalling when I enter the following command, the only output is that it starts creating the basecall pipeline before it stops. There is an NVIDIA 4090 in this machine and guppy works fine, though it slows to a crawl when working on this dataset (which I think has to do with the adaptive, it ran through a non-adaptive set in a fraction of the time). 

input:
`E:\>"C:\Eli\dorado-0.2.4-win64\bin\dorado.exe" basecaller "C:\Eli\dorado-0.2.4-win64\models\dna_r10.4.1_e8.2_400bps_sup@v4.1.0" "W:\Eli\pod5" --modified-bases 5mCG_5hmCG > 7254_adaptive.sam`

output:
`[2023-04-24 11:58:42.607] [info] > Creating basecall pipeline`

The dna_r10.4.1_e8.2_400bps_**hac**@v4.1.0 starts just fine, with the same exact message about creating a basecall pipeline, but then I see GPU usage credited to dorado.exe and the program does not end like with the sup.

Thanks!

Actually the hac config doesn't get far either, seems to have crashed after outputting 5GB into the output sam. 
Only added one more line of output and then several dozen newlines:
`[>                             ] 1% [00m:00s<00m:00s]`

**Comment by vellamike** [comment]
Hi @kaufmanelij , when you say it crashes, does it output any error message or just hang?

**Comment by vellamike** [comment]
Apologies but I don't understand what you mean by "hangs for 30 seconds and then just crashes"  - What is happening differently in those preceding 30 seconds?

Could you try running this basecalling without modified bases, it would be good to see if this works.

**Comment by kaufmanelij** [comment]
Sorry @vellamike, I am probably missing some vocabulary here. I enter the input, the output pops out, and then nothing happens for ~10 seconds and then my command prompt pops back up waiting for more input. I don't see any GPU draw from dorado.exe.

All in all it looks like this (this is without modified bases). 

`E:\>"C:\Eli\dorado-0.2.4-win64\bin\dorado.exe" basecaller "C:\Eli\dorado-0.2.4-win64\models\dna_r10.4.1_e8.2_400bps_sup@v4.1.0" "W:\Eli\pod5" --verbose > 7254_adaptive.sam`  
`[2023-04-27 10:06:33.092] [info] > Creating basecall pipeline`  
`[2023-04-27 10:06:36.372] [debug] - selected batchsize 512`  
` `
`E:\>`  #command prompt returns after 10 seconds on a new line.


This computer has 64GB memory (planning to upgrade soon), and 24GB GPU.

**Comment by vellamike** [comment]
Would it be possible to generate a smaller POD5 file and verify whether this happens? If it does, you could share the data with us and we can investigate it internally?

**Comment by kaufmanelij** [comment]
Same result with a 71GB and a 7GB pod5 file from subsets of the same data. What size would be appropriate to share with you? I can be reached at kaufmane@uw.edu to facilitate data sharing. Thanks! It does seem to start with both fast and hac, just not with sup.

**Comment by iiSeymour** [comment]
@kaufmanelij this should be resolved in the latest version, let us know if you still have issues.
