### ISSUE TITLE
dorado install won't work because it can't find openssl

### ISSUE THREAD

**Issue by readingradio** [nanoporetech/dorado#158]
I keep getting an error that cmake can't find the openssl libraries. I put in paths in all the environmental parameters it suggested and/or that I could find, to libcrypto and openssl directories where they are located on the RHEL 8 AWS EC2 server I am running, and I keep getting the same error even when I try to recompile. The reason I am recompiling is because I needed to install cuda, and point cmake to the installation of cuda, otherwise the image was working for me... I am not a system admin or a web developer (even though that seems to be all I do these days), I am a scientist like you all, please help me.

**Comment by tijyojwad** [comment]
For development you'll need the `openssl-devel` package installed. What package manager are you using? Can you check if the devel package is already on your system?
