### ISSUE TITLE
SQK-PCB111.24 strand information 

### ISSUE THREAD

**Issue by SamDeMario-lab** [nanoporetech/dorado#160]
Is there a way to differentiate which reads come from the original RNA and which ones are from the RT from the SQK-PCB111.24 kit using dorado?

I believe that it's possible based on the library structure. 

I may be missing something or this functionality might not exist.

**Comment by cjw85** [comment]
Reviewing the protocol we have:
![Screenshot_20230426-210055](https://user-images.githubusercontent.com/3592009/234689611-2e248e01-05b7-4c7a-8cd7-2d0173c9ec1a.png)


So during the sequencing we will see a polyA tail or a polyT leader in the basecall sequence. This and other artefacts in the sequencing adapters can be used to orient the reads in terms of the progenitor RNA molecule. This is the task performed by our [Pychopper](https://github.com/epi2me-labs/pychopper) software.
