### ISSUE TITLE
segfault with stereo duplex

### ISSUE THREAD

**Issue by mattloose** [nanoporetech/dorado#162]
Running the following command:

```
dorado-0.2.4-linux-x64/bin/dorado duplex dna_r10.4.1_e8.2_5khz_400bps_sup@v4.2.alpha/ eColi_duplex_LSK114/pod5out/ --device cuda:all --pairs dorado_calls/pairs_stage1/pair_ids_filtered.txt  > dorado_calls/duplex/duplex.sam # Stage 1 stereo
```

results in a segmentation fault:

```
[2023-04-27 12:54:33.620] [info] > Loading pairs file
[2023-04-27 12:54:36.663] [info] > Pairs file loaded
[2023-04-27 12:54:50.522] [info] > Starting Stereo Duplex pipeline
Segmentation fault
```

There's not really any helpful information to see why it's segfaulting. The system in use is two V100s (16 Gb Ram).

Any suggestions? Thanks,

**Comment by vellamike** [comment]
Hi @mattloose ,

Duplex calling is currently not supported with the simplex model `dna_r10.4.1_e8.2_5khz_400bps_sup@v4.2.alpha`. you probably want to use the model `dna_r10.4.1_e8.2_400bps_sup@v4.1.0`.

Mike

**Comment by mattloose** [comment]
OK.

I'm kinda confused though. We've just generated all this data at 5khz?

**Comment by iiSeymour** [comment]
Sorry @mattloose - miscommunication here, I'll get you a build with the latest model and full 5khz support tomorrow.

**Comment by mattloose** [comment]
Thanks - though I am confused now at the commands I am running... they were generated by the output of dorado_stereo.sh - that's OK right?

**Comment by iiSeymour** [comment]
Yes, that is right @mattloose we just need to get you an update 5khz build.

**Comment by mitenjain** [comment]
Thank you, we will need this too!

**Comment by iiSeymour** [comment]
5khz added in v0.3.0
