### ISSUE TITLE
M1 installation

### ISSUE THREAD

**Issue by Erleyl** [nanoporetech/dorado#164]
Are these the only libraries for M1? I can see a lot more dependencies and directories on the other builds. 

<img width="406" alt="Screenshot 2023-05-02 at 00 54 51" src="https://user-images.githubusercontent.com/32706783/235545404-748c70bf-f1c5-4765-a12f-6d6afdd20301.png">

/Downloads/dorado-0.2.4-osx-arm64/bin/dorado ; exit;
dyld[77685]: Library not loaded: /opt/homebrew/opt/zstd/lib/libzstd.1.dylib
  Referenced from: <022BE73C-2F28-387E-8195-4F739B2650F2> /Users/erleyl/Downloads/dorado-0.2.4-osx-arm64/bin/dorado
  Reason: tried: '/opt/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/opt/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/usr/local/lib/libzstd.1.dylib' (no such file), '/usr/lib/libzstd.1.dylib' (no such file, not in dyld cache)
Abort trap: 6
logout

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

I have downloaded the files from the link posted.

**Comment by tijyojwad** [comment]
Hi @Erleyl - not sure if you've resolved it, but I think you'll need to install libzstd on your Mac locally before running dorado. we don't seem to be shipping those libs right now (but we can look into that).

```
brew install openssl
brew install zstd
```

**Comment by tijyojwad** [comment]
Hi @Erleyl - the latest release of dorado includes the missing libraries for Mac - https://github.com/nanoporetech/dorado/releases/tag/v0.3.1

**Comment by l-yampolsky** [comment]
I am having the same issue:
dorado ; exit;
dyld: Symbol not found: _OBJC_CLASS_$_MPSGraphRandomOpDescriptor
  Referenced from: [path to dorado]/dorado
  Expected in: /System/Library/Frameworks/MetalPerformanceShadersGraph.framework/Versions/A/MetalPerformanceShadersGraph
 in [path to dorado]/bin/dorado
zsh: abort       [path to dorado]/dorado
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Both before and after running brew install openssl and
brew install zstd

On M1 Mac, MacOS 11.6

And suggestions?
