### ISSUE TITLE
Probably a CUDA Issue

### ISSUE THREAD

**Issue by eyesmo** [nanoporetech/dorado#165]
I'm attempting to run dorado on an AWS p3.2xL instance (with a Tesla V100 GPU) running Ubuntu 22.04. I've installed dorado and thought I'd correctly installed the latest NVIDIA drivers for V100 GPUs (v12.1), according to NVIDIA's online documentation. However, when I try to run `dorado basecaller` on some pod5 files, I get this error:
`error while loading shared libraries: libcublas.so.11: cannot open shared object file: No such file or directory`

When I run `nvidia-smi`,here's the information that's listed:
![image](https://user-images.githubusercontent.com/2289040/235574330-a494d1d0-89c1-49c3-9369-bf669cd7ca5d.jpeg)

Any advice much appreciated!

**Comment by sklages** [comment]
Maybe #149 is related...

**Comment by iiSeymour** [comment]
@eyesmo this should be resolved in the latest version.
