### ISSUE TITLE
libcudnn_cnn_infer.so.8. Error with pre-compiled dorado-0.2.4-linux-x64.tar.gz

### ISSUE THREAD

**Issue by bef22** [nanoporetech/dorado#166]
Hi,
I downloaded the pre-compiled dorado-0.2.4-linux-x64.tar.gz and when trying to run this I get the following error.
Could not load library libcudnn_cnn_infer.so.8. Error: /usr/local/Cluster-Apps/cuda/8.0/lib64/libnvrtc.so: undefined symbol: nvrtcGetCUBIN

I tried to add a symlink for this in the bin folder which came with dorado but it's not being picked up.

Best wishes,
Bettina

**Comment by tijyojwad** [comment]
Hi @bef22 -

Looks like a much older version of the CUDA lib is being picked up. We ship the right library in the `lib` folder of the dorado package. You can try to prioritize that with
`LD_LIBRARY_PATH=<dorado_root>/lib:$LD_LIBRARY_PATH ./dorado basecaller ...`

**Comment by tijyojwad** [comment]
Closing this issue for now. Please re-open if you have more questions.
