### ISSUE TITLE
Stereo Duplex

### ISSUE THREAD

**Issue by astridvincze** [nanoporetech/dorado#168]
I would like to know more about:
-what is Stero Duplex
-why they are used
-which parameter I need to set during basecalling with Dorado to consider them

**Comment by iiSeymour** [comment]
Hi @astridvincze please see the following talk from NCM22 where stereo duplex was introduced https://www.youtube.com/watch?v=8DVMG7FEBys plus the following [duplex tools usage guide]( https://github.com/nanoporetech/duplex-tools#usage-with-dorado-recommended) and this handy script for running it all [dorado_stereo.sh](https://github.com/nanoporetech/duplex-tools/blob/master/duplex_tools/dorado_stereo.sh).

**Comment by astridvincze** [comment]
Thanks!
