### ISSUE TITLE
model dna_r9.4.1_e8_sup@v3.3 producing only human dna reads from fungal data

### ISSUE THREAD

**Issue by readingradio** [nanoporetech/dorado#169]
Hello I am repeat basecalling from the same data- getting completely different results with dorado 9.4 basecaller model. This is very odd. I went back and looked at results from guppy, and they are the fungi we expect in the sample. When I converted to pod5 and basecalled one library barcode only with 10.4 model, similar results. But then I remembered it was an older flowcell that we used (9.4.1) so repeated basecalling with dna_r9.4.1_e8_sup@v3.3 in dorado and every single sequence I've blasted comes back as Homo sapiens or monkeys. Almost gave me a heart attack. Please address this issue!

**Comment by readingradio** [comment]
no, I don't work with human DNA and the only thing changed in the basecall command was the model I selected- though I just realized 9.4.1 is the wrong flowcell and this data was in fact produced on a FLO-MIN112 which means no dorado models available, and will use sup on guppy

**Comment by iiSeymour** [comment]
@readingradio this should not happen -  please let us know if you see anything strange after calling your FLO-MIN112 data with the guppy dna_r10.4_e8.1_sup config.
