### ISSUE TITLE
A basecaller option to save as fast5 or pod5 files (e.g. --save_path)?

### ISSUE THREAD

**Issue by lcscs12345** [nanoporetech/dorado#170]
Hi,

Thanks for your hard work. Dorado works very well and looks very promising.

Is there a --save_path option as guppy_basecaller? Would be useful to get fast5 or pod5 files returned in pass and fail directories.

Keep it up.

Lim

**Comment by iiSeymour** [comment]
Thanks @lcscs12345 we are not planning to output many files like guppy. The BAM produced by dorado has the mean quality score on each record and this can be use to split/filter reads on.

https://github.com/nanoporetech/dorado/blob/master/documentation/SAM.md#read-tags
