### ISSUE TITLE
dorado to have server mode

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/dorado#171]
Hi

It would be great if dorado gets server+client mode similar to guppy_basecall_server and guppy_basecall_client to facilitate easy access to remote GPU resources. 

Best regards
Rasmus

**Comment by MarkBicknellONT** [comment]
Hi Rasmus,

We are in fact working on providing a dorado_basecall_server application as a slot in replacement for the guppy_basecall_server.  This will allow us to support live basecalling in MinKNOW but will also mean that existing pipelines which are currently taking advantage of the guppy_basecall_client, ont-pyguppy-client-lib and so on will continue to work with dorado basecalling.  If you're coming to London Calling, we have a "Data For Breakfast" session on Friday morning (May 19th) where we will be going through the details.  The talk will also be available online.

Regards,
Mark

**Comment by Kirk3gaard** [comment]
Hi Mark
That sounds great. Looking forward to the data for breakfast session.

Best regards
Rasmus

**Comment by Kirk3gaard** [comment]
Would be happy to test this if you want someone to take it for a spin before the introduction into minknow.

**Comment by Kirk3gaard** [comment]
Any updated ETA on this? 
Would be epic for running some jobs on the university GPU cluster where we cannot store more than 1 TB of data and thus streaming data with the basecall server+client is a very convenient workaround.

**Comment by MarkBicknellONT** [comment]
Hi Rasmus,

Great to meet you at London Calling!  We're getting close to code completion on the dorado_basecall_server package now, our aim is still to release next month (July).

Kind regards,

Mark
