### ISSUE TITLE
difference between 260bp model and 400bp model

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/dorado#173]
Hi, I set the 260 bp speed when start the sequencing, but when I run dorado tool, I chose 400bp dorado model. Is there any effect for the result? I would like to know if I have to rerun dorado tool and choose 260bp model.

Thank you so much.

**Comment by iiSeymour** [comment]
Hi @Flower9618 - yes, please use the correct speed when basecalling with dorado.

**Comment by Flower9618** [comment]
ok, thank you so much.

**Comment by Flower9618** [comment]
Hi, @iiSeymour . the speed is needed to match with experiment setting. But the fast, hac or sup version is not related to the experiment, right? So I can choose any one of them to do the basecalling?

**Comment by iiSeymour** [comment]
Yes, that is correct @Flower9618.

**Comment by Flower9618** [comment]
Thank you so much.
