### ISSUE TITLE
All Contexts 5mC Methylation calling updates?

### ISSUE THREAD

**Issue by jcolicchio-soundag** [nanoporetech/dorado#174]
With all of the concurrent updates to remora/dorado/bonito etc. I am having a hard time figuring out what the current best practice is for calling methylation in all cytosine contexts from either R10.4 or R9 flow cells?  We have been hoping to do methylation calling in dorado, but from my understanding non-CG methylation models may still not have been trained?  Any advice would be appreciated!

**Comment by marcus1487** [comment]
R10 5kHz (Kit14) all-context 5mC and 6mA models have been released with dorado 0.3.0. 4kHz models are released via Rerio along with the associated basecaller. These all context models are also included in Remora (v2.1.1) in pytorch format (for use in Remora and Bonito; for more experimental purposes).

**Comment by iiSeymour** [comment]
The following all-context models are available for R10.4.1 `{5mC_5hmC, 5mC, 6mA}`. Please see https://github.com/nanoporetech/dorado#dna-models for the full details.

**Comment by Olinewms** [comment]
Are there any all-context 5mC models available for R9 generated data? Thanks!
