### ISSUE TITLE
[error] Unable to open the group "channel_id": (Symbol table) Object not found

### ISSUE THREAD

**Issue by aCoalBall** [nanoporetech/dorado#176]
Hi, Im trying to running dorado on a remote HPC.
However I got this error message

```
HDF5-DIAG: Error detected in HDF5 (1.8.12) thread 0:
  #000: ../../src/H5G.c line 463 in H5Gopen2(): unable to open group
    major: Symbol table
    minor: Can't open object
  #001: ../../src/H5Gint.c line 320 in H5G__open_name(): group not found
    major: Symbol table
    minor: Object not found
  #002: ../../src/H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../src/H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../src/H5Gloc.c line 385 in H5G_loc_find_cb(): object 'channel_id' doesn't exist
    major: Symbol table
    minor: Object not found
[2023-05-16 14:44:07.849] [info] > Reads basecalled: 0
[2023-05-16 14:44:07.849] [info] > Samples/s: 0.000000e+00
[2023-05-16 14:44:07.849] [error] Unable to open the group "channel_id": (Symbol table) Object not found
```
my command is 
```
dorado basecaller dna_r9.4.1_e8_fast@v3.4 fast5_directory > calls2.sam
```

**Comment by vellamike** [comment]
Hi,would it be possible to convert to  PPD5 and check if this still happens? Fast5 is only in Dorado for some backwards compatibility, conversion to  POD5 and basecalling is faster.

**Comment by malton-ont** [comment]
This error occurs when trying to basecall single-read .fast5 files - Dorado's fast5 support is limited to multi-read .fast5. You can use the `ont-fast5-api` python package to convert your files. However, if you're going to the trouble of converting files you might as well go straight to .pod5 as Mike suggests.

**Comment by poojashree10-AI** [comment]
#001: ..\..\src\H5Gint.c line 320 in H5G__open_name(): group not found
    major: Symbol table
    minor: Object not found
  #002: ..\..\src\H5Gloc.c line 430 in H5G_loc_find(): can't find object
im getting this error in hecras

**Comment by malton-ont** [comment]
@poojashree10-AI,

I don't know what `hecras` is. If it is another software, please raise an issue with the developers. If it is a hardware configuration and you are seeing this issue in the `dorado` software, please see the answers above or, if those are not working for you, raise a new issue and fill out the issue template.

**Comment by poojashree10-AI** [comment]
Ok thank you
