### ISSUE TITLE
libkoi-0.3.1-Linux-x86_64 binary is missing support for sm_61 GPU achitecture (Nvidia Pascal)

### ISSUE THREAD

**Issue by MarkiyanSV** [nanoporetech/dorado#179]
Dear Nanopore Developers,

Please restore the Nvidia Pascal GPU achitecture support (sm_61) for Koi Library v 3.1.0 used by the dorado 0.3.0 basecaller
GPU's with this architecture is still widely used for ONT data processing in many low and middle income countries, where we have to make do with what IT equipment is available to us. Also you can include the source code for Koi Library in the dorado package, so we can compile it ourselves for architecture available to us.
The LibKoi-0.2.2 binary has the support for sm_61 architecture.
I was able to compile and run the previous version of dorado last week, and was able to achieve samplerate of ~200K samples/sec with model dna_r9.4.1_e8_sup@v3.3 on the following rig:
Nvidia 1060 Ti 3Gb GPU (2532MiB used by dorado with -b 64)
Dell precision T7500 2xXeon X5680@3.33GHz, 192GB RAM
Driver Version: 520.61.05    CUDA Version: 11.8
for compilation on Ubuntu 18.04 LTS the following was done:
cmake upgraded to 3.26.3
gcc and g++ upgraded to 9, and the following set before running cmake:
#https://askubuntu.com/questions/1256440/how-to-get-libstdc-with-c17-filesystem-headers-on-ubuntu-18-bionic
export CC=/usr/bin/gcc-9
export CXX=/usr/bin/g++-9

PS: All the best regards from Lviv, Markiyan.

**Comment by iiSeymour** [comment]
@MarkiyanSV `SM_61` support was added back in koi `v0.3.4` and is available in the latest versions of dorado.

HTH,

Chris.
