### ISSUE TITLE
batchsize option 0.3.0+88df11b is not working

### ISSUE THREAD

**Issue by husamia** [nanoporetech/dorado#180]
I had a previous issue https://github.com/nanoporetech/dorado/issues/150 about Nvidia RTX A2000 6GB issues with previous dorado version so I tested 0.3.0+88df11b with batchsize 96. It looks like the --batchsize is deprecated.

`c:\dorado-0.3.0-win64\bin>dorado.exe basecaller -v --batchsize **96** --recursive --emit-fastq -x cuda:all c:\dorado-0.3.0-win64\bin\dna_r10.4.1_e8.2_260bps_sup@v4.1.0 D:\ONT\HM12878\fast5_pass\ > D:\ONT\HM12878\fastq_dorado0.3.0_dna_r10.4.1_e8.2_260bps_sup@v4.1.0
[2023-05-19 09:29:38.456] [info] > Creating basecall pipeline
[2023-05-19 09:29:45.739] [debug] - set batch size for cuda:0 to **128**
> Output records written: 0`

**Comment by malton-ont** [comment]
Due to the introduction of new kernels for basecalling, dorado-0.3.0 will adjust the requested batch size to be a multiple of 64. It just so happens that the next multiple of 64 above 96 is the same value as the batch size we use when a batch size cannot be calculated.

**Comment by tijyojwad** [comment]
Hi @husamia  - the `--batchsize` option still exists. But in order to ensure that our kernels are compatible with the GPU, the batch size is padded to the nearest acceptable value. I think that's what's bumping up the batch size 128 for you. Can you try with `-b 64` or `-b 128` (i.e. a multiple of 64)?

**Comment by husamia** [comment]
I've tried change to 64

It didn't fail but will find out if it finishes will report back!

```
c:\dorado-0.3.0-win64\bin>dorado.exe duplex --threads 20 -b 64 --recursive --reference D:\Research\Homo_sapiens_assembly38.fasta -x cuda:all c:\dorado-0.3.0-win64\bin\dna_r10.4.1_e8.2_260bps_sup@v4.1.0 D:\ONT\HM12878\pod5 > D:\ONT\HM12878\fastq_dorado0.3.0_dna_r10.4.1_e8.2_260bps_sup@v4.1.0_GRCh38.bam
[2023-05-19 15:17:34.669] [info] > No duplex pairs file provided, pairing will be performed automatically
[2023-05-19 15:17:34.916] [info] > Index parameters input by user: kmer size=15 and window size=10.
[2023-05-19 15:19:22.290] [warning] Auto batchsize detection failed. Insufficient memory, required 8GB, available 0GB
[2023-05-19 15:19:22.311] [info] > Starting Stereo Duplex pipeline
[2023-05-19 15:19:22.323] [info] > Reading read channel info
[2023-05-19 15:19:23.160] [info] > Processed read channel info
[                              ] 0% [01m:36s<01m:36s]
```

**Comment by MarkiyanSV** [comment]
Just confirming, that when testing with model dna_r9.4.1_e8_sup@v3.6 it seems to round up the chunk size (-b) to the nearest 64 - so chunk -b 1 becomes 64, 65 - 128, and do on.
So the documentation should be updated (it states, that chunk should be multiple of 16, but in this case v0.3.0 and sup model it seems to be 64)
Some benchmarks on a small dataset
Reads basecalled: 5651
-b	VramUSE	Samples/sec
-b1:	3622MiB	1.203e6
-b64	3622MiB	1.195e6 
-b128	5822MiB	1.682e6
-b129	8028MiB	1.854e6
-b192	8028MiB	1.850e6
-b256 10232MiB	1.869e6
-b257	out of Vmem:CUDA out of memory. Tried to allocate 4.88 GiB (GPU 0; 11.77 GiB total capacity; 3.56 GiB already allocated; 2.77 GiB free; 7.67 GiB reserved in total by PyTorch)

My friend's test rig: Asus TUF gaming NVIDIA GeForce RTX 3060 12GB (12288MiB)
HP Z800 2xXenon X5675 @ 3.07GHz, RAM: 48GB 
ubuntu 20.04 LTS, CUDA 11.8, Nvidia Driver Version: 520.61.05

**Comment by tijyojwad** [comment]
Hi @MarkiyanSV - can certainly update the documentation. Could you send me a link for where it says multiple of 16? I did a quick `grep` but couldn't find it..

P.S. just wanted to mention that there's another parameter called chunk size controlled by `-c` option. the `-b` option controls the batch size.

**Comment by husamia** [comment]
@tijyojwad do you have advice on the optimal -c to use my my case?

**Comment by tijyojwad** [comment]
Hi @husamia - did the run with `-b` succeed for you? I'm interested in understanding your use case for changing `-c`

**Comment by MarkiyanSV** [comment]
@tijyojwad I've tried locating that piece in documantation, but couldn't find it. It musk have been some older comment (either github issues for previous dorado version or ONT community.)
In any case it would be a good idea to mention multiples of 64 in dorado help:

`  -b, --batchsize               if 0 an optimal batchsize will be selected [default: 0]`

replace with something like

`  -b, --batchsize               if 0 an optimal batchsize will be selected. It should be specified as multiple of 64. [default: 0]`

**Comment by husamia** [comment]
> Hi @husamia - did the run with `-b` succeed for you? I'm interested in understanding your use case for changing `-c`

yes, the -b 64 works

**Comment by tijyojwad** [comment]
awesome!

@MarkiyanSV - good point, will update the README!

**Comment by husamia** [comment]
[2023-05-29 05:28:04.437] [info] > Basecalled @ Bases/s: 3.809784e+04

**Comment by tijyojwad** [comment]
Hi @husamia - because of the small batch size that can fit on your GPU, your run is memory size limited and the compute cores aren't being fully utilized. My guess is if you were able to fit larger batch sizes, you'd get better performance.

**Comment by MarkiyanSV** [comment]
or at least set in your profile:
**export CUDA_MODULE_LOADING=LAZY**
and than it should be able to handle -b128 (see updated results above)
