### ISSUE TITLE
c10::OutOfMemoryError during duplex calling

### ISSUE THREAD

**Issue by eernst** [nanoporetech/dorado#181]
Very impressive set of features and improvements in this latest release!

Log: [dorado-duplex.res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1.txt](https://github.com/nanoporetech/dorado/files/11517468/dorado-duplex.res_dna_r10.4.1_e8.2_400bps_sup%40v4.0.1.txt)

- Using dorado 0.3.0 release 
- 4Khz R10.4.1 pod5 input
- rerio model res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1
- Running on 2 x V100s 32GB non-virtualized, Driver Version: 530.30.02    CUDA Version: 12.1
- Default automatic batch size detection results in OOM. 
- Using `-x cuda:0` gives same error
- Passing `-b 256` , but not `-b 512` remedies the OOM. 
- Passing `--guard-gpus` doesn't consistently avoid the OOM. 
- Simplex calling runs successfully with mod calling (res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1_5mC@v2) in about 7 hrs, duplex with `-b 256` taking about 15.5 hrs on this dataset (~1.8M reads, N50 ~33 Kbp)
- Same error another dataset with read N50 ~4Kbp.

**Comment by tijyojwad** [comment]
Hi @eernst - thank you for reporting the issue!

Do you get OOM right off the bat with automatic batch size detection, or after some time into the run? Do you have any other processed running on the GPU that could varying memory footprint?

It's surprising that `--guard-gpus` doesn't help since it should theoretically give each inference call enough memory.

My guess is `dorado` is at the edge of memory with `-b 512`. So you may not have to take it down to 256 - something closer 512 would probably work.

**Comment by eernst** [comment]
OOM happens just as basecalling starts after autoscaling without `--guard-gpus`. 

When testing a dedicated machine with no other variable GPU processes running, `--guard-gpus` seemed to do the trick, but on I had one cluster job OOM after some time into calling with `--guard-gpus`, so in that case it could've been a competing process from another user (which shouldn't be happening, but I've seen it, probably some issue with our scheduler config). 

Thanks for the suggestion re: batch size, can confirm that setting `-b 500` seems to work, but I'm not sure how to interpret the log:
```
[2023-05-19 11:42:13.416] [debug] - set batch size for cuda:1 to 512
[2023-05-19 11:42:13.477] [debug] Auto batch size: GPU memory available: 7.745634304GB
[2023-05-19 11:42:13.477] [warning] Auto batchsize detection failed. Insufficient memory, required 8GB, available 7.745634304GB
[2023-05-19 11:42:13.517] [debug] Auto batch size: GPU memory available: 7.9577088GB
[2023-05-19 11:42:13.517] [warning] Auto batchsize detection failed. Insufficient memory, required 8GB, available 7.9577088GB
[2023-05-19 11:42:13.543] [info] > Starting Stereo Duplex pipeline
[2023-05-19 11:42:13.553] [info] > Reading read channel info
[2023-05-19 11:42:16.047] [info] > Processed read channel info
[                              ] 0% [01m:03s<01d:01h:07m:46s]
```

nvidia-smi looks like:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-32GB            Off| 00000000:1B:00.0 Off |                    0 |
| N/A   67C    P0              245W / 250W|  25871MiB / 32768MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE-32GB            Off| 00000000:88:00.0 Off |                    0 |
| N/A   63C    P0              238W / 250W|  25670MiB / 32768MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      4372      G   /usr/libexec/Xorg                            63MiB |
|    0   N/A  N/A      4583      G   /usr/bin/gnome-shell                        136MiB |
|    0   N/A  N/A    841806      C   dorado                                    25666MiB |
|    1   N/A  N/A    841806      C   dorado                                    25666MiB |
+---------------------------------------------------------------------------------------+
```

after basecalling begins (the X/gnome session is just a stub, not actively being used, and so shouldn't be varying).

**Comment by eernst** [comment]
It seems that `-b 448` is the magic number in this case that causes the Insufficient memory warnings to disappear and allows subsequent autoscaling to proceed.

**Comment by MarkiyanSV** [comment]
PS: Also there is such thing as GPU memory fragmentation, so if possible, I would switch that box to runlevel3 (text console only), or designate onboard graphics as boot device (so X11 is not using main GPU's video ram at all).

In my rig I've added ATI graphics card for X11/display, and kept nvidia card as a dedicated GPU for CUDA. It did allow me to increase fragment size and memory utilization by ~ 10%-20% (it was with guppy5/sup mode).

If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

**Comment by MarkiyanSV** [comment]
Also try setting the following environmental variable:

**export CUDA_MODULE_LOADING=LAZY**

After using it, the Virtual/Real ram usage by dorado had gone from 27G/4G to 20G/1G
Video Ram usage for -b320/sup simplex R9.4.1 had gone from 11964MiB to 11336MiB
and sample rate went from 1.825e6 to 1.836e6

PS: If you want to fiddle with GPU memory fragmentatation reduction, you can try:

export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:4096'

But keep in mind, that reducing this to 256 or 512 would have negative impact on performence (memory ir allocated/deallocated in cycles), so better to reduce chunk size in this case. 
https://stackoverflow.com/questions/73747731/runtimeerror-cuda-out-of-memory-how-setting-max-split-size-mb

**Comment by tijyojwad** [comment]
@eernst if this is working for you, can we close this issue?

PS @MarkiyanSV - thank you for the tips :). Those are helpful to know!

**Comment by eernst** [comment]
I will leave the bug status determination up to the devs, but it looks to me like autoscaling is broken in several situations. Non-exclusive GPU use doesn't seem to be the problem.

I get the same errors with autoscaling when doing duplex calling with non research models, even with `--guard-gpus` without other GPU processes running. It looks like there are lots of reports of this sort of CUDA malloc error with Torch v2.0 on workloads that didn't error out with earlier versions, and setting PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:4096 does resolve the issue for me (thanks @MarkiyanSV). Maybe dorado code should set this env var to some reasonable value by default.

**Comment by iiSeymour** [comment]
@eernst autoscaling is much improved in the latest version and duplex calling should be solid now _(note: `--guard-gpus` is removed as it's no longer necessary)_. Let us know if you run into any issues.
