### ISSUE TITLE
Indicator Bar with weird scaling.

### ISSUE THREAD

**Issue by lucapandolfini** [nanoporetech/dorado#184]
Hello,
the progress bar of Dorado 0.3.0 in many cases does not arrive at 100% (although it seems to process all files to completion). Most of the time it stops at 70-81%. This happens with many different data inputs and models.

![2023-05-22_03-25](https://github.com/nanoporetech/dorado/assets/36173642/b3dda5de-8e2e-4ed6-b281-3626bafe46da)

**Comment by tijyojwad** [comment]
Hi @lucapandolfini - thanks for reporting! I believe this primarily happens when there are reads being filtered out. Nevertheless we'll add it to our backlog.

**Comment by lucapandolfini** [comment]
Yes this is the case indeed. But I found it counterintuitive.

**Comment by tijyojwad** [comment]
Hi @lucapandolfini - this bug has been fixed with the latest release - https://github.com/nanoporetech/dorado/releases/tag/v0.3.1
