### ISSUE TITLE
rapid and native barcode demultiplexing

### ISSUE THREAD

**Issue by alexdrong** [nanoporetech/dorado#185]
Hi, will there be support for ONT barcode demultiplexing in dorado in the future? What is the recommended way to demultiplex an aligned bam file?

**Comment by davidryderuk2** [comment]
I've been trying to work out the answer to that question as well. Guppy's demultiplexing command seems to be able to take bam files as an input. In which case maybe we can just do the following?

#### Demultiplex bam file output by dorado and save output in bam format (no option for trimming reads when outputting bam files)
_guppy_barcoder -i ./ --save_path ./ --barcode_kits SQK-NBD114-96 --bam_out -t 10 -q 0_

#### Demultiplex bam file output by dorado and save output in fastq format
_guppy_barcoder -i ./ --save_path ./ --barcode_kits SQK-NBD114-96 -t 10 -q 0 --enable_trim_barcodes_

**Comment by tijyojwad** [comment]
Hi @alexdrong and @davidryderuk2 - we plan on adding barcoding to a future release of `dorado`, but as of now the `guppy_barcoder` is the recommended way to go.

**Comment by tijyojwad** [comment]
Hi @alexdrong - we just released dorado [v0.4.0](https://github.com/nanoporetech/dorado/releases/tag/v0.4.0) which supports barcode demux and trimming.
