### ISSUE TITLE
Filtering Duplex reads using the tag

### ISSUE THREAD

**Issue by astridvincze** [nanoporetech/dorado#189]
Hi,
I tried the new version of duplex basecalling in the following way:

`dorado duplex dna_r10.4.1_e8.2_400bps_sup@v4.2.0 --min-qscore 10 ./pod5 > all_reads.bam`

but when I tried to filter out the duplex and simplex reads I didn't obtain any read. The commands I used to filter them are:

`samtools view -b -h -F "dx:i:0" all_reads.bam > duplex.bam`
`samtools view -b -h -F "dx:i:1" all_reads.bam > simplex.bam`

Am I doing this wrongly? How can I filter correctly my output all_reads.bam in such a way to separe duplex and simplex?

**Comment by davidryderuk2** [comment]
This seemed to work for me:
`samtools view -b -h -d dx:1 all_reads.bam > duplex.bam`
`samtools view -b -h -d dx:0 all_reads.bam > simplex.bam`

**Comment by tijyojwad** [comment]
Thanks for the solution @davidryderuk2 ! 
@astridvincze closing this issue for now, please re-open if this is not resolved for you.

**Comment by Kirk3gaard** [comment]
maybe worth it to simply output a simplex.bam and duplex.bam when basecalling to make this more user friendly?

**Comment by bruzecruise** [comment]
The below code should output a bam file containing only duplex (dx:1) and unpaired simplex (dx:0) reads with the donor simplex (dx:-1) reads removed 

printf "1\n0\n" > tag.txt
samtools view -b -h -D dx:tags.txt all_reads.bam > duplex_Simplex.bam
