### ISSUE TITLE
Request for R9 5hmC+5mC model 

### ISSUE THREAD

**Issue by santanaw** [nanoporetech/dorado#190]
Hi @iiSeymour. Thank you for the newest Dorado release! I would like to do some analyses of 5hmC + 5mC on a large datasets of R9 (Kit 10) using Dorado (to cut down some computational time). Might there be any chance to get 5hmC + 5mC model at least for sup@v3.3 ? Thank you for any consideration.

**Comment by iiSeymour** [comment]
Hey @santanaw I've check and this isn't a model that we already have for the old kit unfortunately.

**Comment by iiSeymour** [comment]
@santanaw good news, we figured out a way to make this model available in dorado v0.3.2.

**Comment by santanaw** [comment]
Hi @iiSeymour. This is incredible!!! Huge thanks for having integrated these models to Dorado!
