### ISSUE TITLE
Existing models very confusing

### ISSUE THREAD

**Issue by AyshaSezmis** [nanoporetech/dorado#191]
I find it very difficult to choose which model I supposed to use for Dorado base calling if I did my sequencing experiment using Rapid Barcoding Kit 96 V14 (SQK-RBK114.96) and R10.4.1 flow cells (FLO-MIN114)? When I look into the available models:
dna_r10.4.1_e8.2_400bps_sup@v3.5.2, 
dna_r10.4.1_e8.2_260bps_sup@v4.0.0, 
dna_r10.4.1_e8.2_400bps_sup@v4.0.0, 
dna_r10.4.1_e8.2_400bps_sup@v4.1.0, 
dna_r10.4.1_e8.2_400bps_sup@v4.2.0
I find it especially very confusing vX.X.X part. What are the difference among v3.5.2, v4.0.0, v4.1.0, v4.2.0 versions? So I understand these are simplex base calling models and if I want to use the duplex base calling, which model should I use? 
dna_r10.4.1_e8.2_4khz_stereo@v1.1, 
dna_r10.4.1_e8.2_5khz_stereo@v1.1
In here what does 4khz and 5khz mean? If these are the available stereo models, then why on Dorado github page we have the following duplex calling example: 
$ dorado duplex dna_r10.4.1_e8.2_400bps_sup@v4.1.0 pod5s/ > duplex.bam
I am totally confused and need some documentation as I can not find any documentation neither at Nanopore community website nor at your github pages.
Finally, I like all the new integrations into the latest Dorado v0.3.0, however, I am confused if we want the most accurate base calling, do we still need to use the dorado_stereo.sh script or in fact at the latest version just doing the following command (dorado duplex dna_r10.4.1_e8.2_400bps_sup@v4.1.0 pod5s/ ) replaces the whole dorado_stereo.sh pipeline?
Any help is much appreciated,
Many thanks,
Aysha

**Comment by tijyojwad** [comment]
Hi @AyshaSezmis , thanks for the question. We can definitely make the instructions clearer on our README and we'll make sure that's part of our next update.

> What are the difference among v3.5.2, v4.0.0, v4.1.0, v4.2.0 versions?

The main difference to be aware of is anything before v4.2.0 is compatible with 4KHz sampling rate on the sequencer, and the 4.2.0 is only compatible with 5KHz sampling rate. If you're not sure about sampling rate I'd start w/ v4.1.0. If the sampling rate is incompatible, `dorado` will throw an error.

> if I want to use the duplex base calling, which model should I use?

During duplex, dorado uses 2 models - a simplex model and a stereo model. `dorado` can internally figure out the right duplex model to use based on the input. You only need to supply the simplex model (such as a sup model referenced in the README). we don't recommend using any fast model w/ duplex. So you can ignore the `dna_r10.4.1_e8.2_4khz_stereo@xxx` models for now.

> do we still need to use the dorado_stereo.sh script

No, you can use use the `dorado duplex` command and that will do all the work or you.

**Comment by AyshaSezmis** [comment]
Hi @tijyojwad 

Many thanks for your reply. Okay, so we shouldn't really use any model with v4.2.0. Actually, yesterday, I submitted a job to our HPC system using dna_r10.4.1_e8.2_400bps_sup@v4.2.0 model and Dorado failed with an error message exactly how you described. Then, yesterday without knowing this sampling rate problem, I changed the model to dna_r10.4.1_e8.2_400bps_sup@v4.1.0 and unfortunately the job has not started yet as GPUs are high in demand in our HPC ssystem.

Now, what are the differences among v3.5.2, v4.0.0, v4.1.0? Are they simply slightly older worse versions then v4.1.0? If so, I recommend removing them from the dorado download system, as they will only confuse many people like me.

Many thanks for your help :)
Best wishes,
Aysha

**Comment by tijyojwad** [comment]
> Are they simply slightly older worse versions then v4.1.0?

yes they are older versions of the models. unfortunately we can't delete them so quickly because there are still users who may need access to the older models (e.g. if they wanted to recreate older results). eventually we will deprecate them.

we will clarify this in the README when we update it! Thanks again for the feedback :).

I'm closing this issue for now, but please re-open if this isn't resolved after switching to v4.1.0.
