### ISSUE TITLE
Empty sequence and qstring provided for read id XXXX

### ISSUE THREAD

**Issue by AyshaSezmis** [nanoporetech/dorado#192]
Hi team,

I have another problem, when I try to use dorado on my POD5 files, with --emit-moves, I get the following error:
[2023-05-18 15:51:35.915] [info] > Creating basecall pipeline
[2023-05-18 15:53:52.241] [error] Empty sequence and qstring provided for read id 00553382-979f-40e3-8f28-1ebf6b5a1436
[2023-05-18 15:53:52.241] [error] Empty sequence and qstring provided for read id 003c0ce5-62ef-4846-a019-76fcb99fef54
[2023-05-18 15:53:52.242] [error] Empty sequence and qstring provided for read id 00570d74-e63a-4a22-8180-e0403a693458
.
.
.
However, If i use the same POD5 files with --emit-fastq, I get a properly called fastq.fq file. However, for this I have used previous version of Dorado (0.2.4). Was this a potential bug with that version? I will now try the latest version of Dorado and see this time if it works properly. If I have the same issue, I will post it on this issue thread.
Many thanks,
Aysha

**Comment by AyshaSezmis** [comment]
Hi @tijyojwad 

Finally, the run started but this time printed all these below faults and errors:

[2023-05-24 09:12:42.179] [info] > No duplex pairs file provided, pairing will be performed automatically
^M[2023-05-24 09:14:08.567] [error] CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f2f078c04d7 in /monfs01/projects/bn96/Aysha/dorado-0.3.0-linux-x64/bin/../lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f2f0788a36b in /monfs01/projects/bn96/Aysha/dorado-0.3.0-linux-x64/bin/../lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f2f0795cb58 in /monfs01/projects/bn96/Aysha/dorado-0.3.0-linux-x64/bin/../lib/libc10_cuda.so)
frame #3: at::native::copy_device_to_device(at::TensorIterator&, bool, bool) + 0x91f (0x7f2ea16613af in /monfs01/projects/bn96/Aysha/dorado-0.3.0-linux-x64/bin/../lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x1985b76 (0x7f2ea1662b76 in /monfs01/projects/bn96/Aysha/dorado-0.3.0-linux-x64/bin/../lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x1d4b670 (0x7f2eefe37670 in /monfs01/projects/bn96/Aysha/dorado-0.3.0-linux-x64/bin/../lib/libtorch_cpu.so)
frame #6: at::native::copy_(at::Tensor&, at::Tensor const&, bool) + 0x62 (0x7f2eefe38802 in /monfs01/projects/bn96/Aysha/dorado-0.3.0-linux-x64/bin/../lib/libtorch_cpu.so)
frame #7: at::_ops::copy_::redispatch(c10::DispatchKeySet, at::Tensor&, at::Tensor const&, bool) + 0x7b (0x7f2ef0a4a4ab in /monfs01/projects/bn96/Aysha/dorado-0.3.0-linux-x64/bin/../lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x5442fb5 (0x7f2ef352efb5 in /monfs01/projects/bn96/Aysha/dorado-0.3.0-linux-x64/bin/../lib/libtorch_cpu.so)
frame #9: at::_ops::copy_::redispatch(c10::DispatchKeySet, at::Tensor&, at::Tensor const&, bool) + 0x7b (0x7f2ef0a4a4ab in /monfs01/projects/bn96/Aysha/dorado-0.3.0-linux-x64/bin/../lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x5445364 (0x7f2ef3531364 in /monfs01/projects/bn96/Aysha/dorado-0.3.0-linux-x64/bin/../lib/libtorch_cpu.so)
frame #11: at::_ops::copy_::call(at::Tensor&, at::Tensor const&, bool) + 0x15f (0x7f2ef0aa77af in /monfs01/projects/bn96/Aysha/dorado-0.3.0-linux-x64/bin/../lib/libtorch_cpu.so)
frame #12: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x58c34b]
frame #13: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x4e9e33]
frame #14: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x5372d6]
frame #15: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x50be13]
frame #16: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x50bf20]
frame #17: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x5383d0]
frame #18: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x50bcbd]
frame #19: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x58cc08]
frame #20: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x58a90f]
frame #21: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x5893b6]
frame #22: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x4a1f4e]
frame #23: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x468ded]
frame #24: __libc_start_main + 0xf5 (0x7f2e9825a555 in /lib64/libc.so.6)
frame #25: /home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado() [0x46e76f]

How do you recommend I solve these problems?

Incase you would like to see my slurm script, this is what I use in our HPC system:
#!/bin/bash
#SBATCH --mail-type=ALL
#SBATCH --mail-user=aysha.sezmis@monash.edu
#SBATCH --mem=100G
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --time=23:00:00
#SBATCH --partition=short,gpu
#SBATCH --gres=gpu:P100:1

POD5="/home/asez0001/bn96/Aysha/Community_phage_project/Phage_community_amplicon_analyses/amplicon_data/recovered_fast5/POD5/POD5"
output_dir="/home/asez0001/bn96/Aysha/Community_phage_project/Phage_community_amplicon_analyses/amplicon_data/Dorado_duplex_v0.3.0_output"

/home/asez0001/bn96/Aysha/dorado-0.3.0-linux-x64/bin/dorado duplex \
/home/asez0001/bn96/Aysha/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 ${POD5} > ${output_dir}/duplex.bam

Many thanks for your help,
Best wishes,
Aysha

**Comment by AyshaSezmis** [comment]
Hi again @tijyojwad,

I have sent the above error messages to our HPC manager and he emailed me the below response:
Hi Aysha,

The problem is that dorada is   pre-compiled software, that was build for a newer architecture of GPUs that what exists on MonARCH.
Our P100 GPUs are Pascal GPUs and not support software for the Ampere series of GPUs. (Our GPU nodes are due to be decomissioned soon. We are still trying to find newer machines to replace them).

To test, I coped your input files to an A100 node being tested on M3.  The code is working fine.

To proceed you'll need to ask the developers to compile for P100 GPUs. Or get a M3 account and use the small number  (2) of A40 nodes we have in a GPU queue.

​I ran the code on a machine with 4*A100 cards, It made effective use of all resources, but crashed towards the end.

[█████████████████████████████▌] 98% [10m:23s<00m:09s] [Dorado_duplex_v0.3.0.sh](http://dorado_duplex_v0.3.0.sh/): line 17: 92389 Segmentation fault      (core dumped) ./dorado duplex ~/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 ${POD5} > test.bam

You will also need to contact the developers about this too if you want to proceed. 

regards
Simon

Today, I have just received my new MacBookPro M2 with 8 GPU units, so I will try downloading the Mac version of Dorado 0.3.0 and see if this works easier without any problems :). 

I will let you know how I go with the Mac version,
Best wishes,
Aysha

**Comment by tijyojwad** [comment]
Hi @AyshaSezmis - 

Sorry to see the set fault! Without more logs it'll be difficult for us to debug. As for GPU, we only support for architectures Volta onwards. If you can run on the Ampere cards that would be best.

Looking forward to your results on the Mac!

**Comment by AyshaSezmis** [comment]
Hi @tijyojwad 

Yes, it works just fine in my new mac, which is great :), but it is taking a while despite using --device "metal" option, I have around 500 POD5 files to process, I think I will just have to let it run continuously. Or do you have any suggestions?

The below is outcome from only 1 POD5 file:
MU00155137X:~ asez0001$ /Users/asez0001/dorado-0.3.0-osx-arm64/bin/dorado duplex /Users/asez0001/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 /Users/asez0001/Desktop/Dorado/POD5 > /Users/asez0001/Desktop/Dorado/duplex.bam
[2023-05-25 12:14:50.835] [info] > No duplex pairs file provided, pairing will be performed automatically
[2023-05-25 12:14:50.854] [info]  - downloading dna_r10.4.1_e8.2_4khz_stereo@v1.1
[2023-05-25 12:14:53.340] [info] > Starting Stereo Duplex pipeline
[2023-05-25 12:14:53.341] [info] > Reading read channel info
[2023-05-25 12:14:53.345] [info] > Processed read channel info
[2023-05-25 12:43:28.626] [info] > Reads basecalled: 3992
[2023-05-25 12:43:28.627] [info] > Basecalled @ Bases/s: 1.319045e+03

Best wishes,
Aysha

**Comment by tijyojwad** [comment]
Hi @AyshaSezmis - I don't have any specific recommendations right now. We plan to look into optimizations for Mac in the future releases.
