### ISSUE TITLE
Dorado Roadmap?

### ISSUE THREAD

**Issue by incoherentian** [nanoporetech/dorado#193]
With Dorado v0.3.0 released, two items have been knocked off this prior roadmap:

DNA Barcode multiplexing
Duplex basecalling
Alignment (output aligned BAMs)
Python API

That roadmap has been removed from the main page entirely now, while demultiplexing has yet to see native implementation.

I would find it reassuring to have a roadmap still in place detailing demultiplexing (and any other major planned developments). A lack of one seems to have quickly led to numerous inquiries by new users, who were clearly not expecting to require guppy demultiplexing alongside dorado. 

Can the Dorado team bring something akin to a roadmap back please?

**Comment by iiSeymour** [comment]
Hey @incoherentian these are still plan for v0.4 _(alignment is already in v0.3)_ and we will put a roadmap back in place, thanks for raising.

**Comment by iiSeymour** [comment]
https://github.com/nanoporetech/dorado#roadmap

**Comment by incoherentian** [comment]
Bril, TY @iiSeymour !
