### ISSUE TITLE
RNA 004 model

### ISSUE THREAD

**Issue by Psy-Fer** [nanoporetech/dorado#194]
Hello

on the Readme it says

RNA models:
    rna003_120bps_sup@v3
    
Is this actually the rna004 model?

Cheers,
James

**Comment by tijyojwad** [comment]
Hi @Psy-Fer - these are ran 3 models. We don't have an rna4 model published yet.

**Comment by Psy-Fer** [comment]
Hey, I find that a little odd, given RNA003 was never released.

**Comment by iiSeymour** [comment]
The model is RNA003 and for those E.A customers. We will be adding RNA002 and RNA004 models.
