### ISSUE TITLE
Unable to determine sample rate for data.

### ISSUE THREAD

**Issue by caonetto** [nanoporetech/dorado#195]
Hi, I am getting this error "Unable to determine sample rate for data" when trying to basecall a minion run done on a mk1c using barcode balancing. I have successfully base called other datasets so its not a problem with my install.

Thanks,

**Comment by olawa** [comment]
Same here - duplex calling with sup worked fine but duplex with the modification model gave this error.

**Comment by caonetto** [comment]
Hi @tijyojwad , im running dorado on pod5 files.

**Comment by tijyojwad** [comment]
Hi @caonetto - would it be possible to share a sample pod5 file for us to take a look?

**Comment by tijyojwad** [comment]
Hi @caonetto are you still seeing errors with the pod5 file?

@olawa - dorado currently does't support mod base calling with duplex. we plan to add that in a subsequent release.

**Comment by tijyojwad** [comment]
note that there's also the `-r` option in `dorado` to find pod5 files recursively.

**Comment by tijyojwad** [comment]
Hi @caonetto - were you able to resolve the issue? If so, I can close the ticket
