### ISSUE TITLE
Trimming sequencing adapters

### ISSUE THREAD

**Issue by bruzecruise** [nanoporetech/dorado#197]
I've recently made the switch from guppy to dorado and I was wondering if dorado can trim sequencing adapters similar to the guppy command: --trim_adapters   ?

Thanks for your help!

**Comment by tijyojwad** [comment]
Hi @bruzecruise - currently `dorado` doesn't support it but we plan to add it in a future release.

**Comment by bruzecruise** [comment]
Cool thanks!

**Comment by nextgenusfs** [comment]
@tijyojwad any update on this, it seems v0.3.3 doesn't not include adapter trimming nor read splitting. Yet guppy is now "archived".... so how are we supposed to run the equivalent guppy command with dorado:
```
guppy_basecaller -i data/ -s outdir --disable_qscore_filtering --do_read_splitting --trim_adapters -c dna_r10.4.1_e8.2_400bps_5khz_hac.cfg
```

**Comment by tijyojwad** [comment]
Hi @nextgenusfs - our last major release was v0.3 and the subsequent ones have been minor updates to it. Since adapter trimming/barcoding is a major feature, we plan to introduce it in a subsequent release. We are actively working on it.

In the meantime, guppy should still be usable for trimming and read splitting and will be supported until dorado has equivalent functionality.

**Comment by tijyojwad** [comment]
HI @nextgenusfs

You can run the ont_barcoder with --trim_adapters and/or --trim_primers to get rid of adapters on already-called reads (fastx or sam/bam).  We don't provide a standalone read splitter, but if the dataset is barcoded, turning on --detect_mid_strand_barcodes with the ont_barcoder will allow you to find barcodes in the middle of reads, which can inform a split point for you.

**Comment by tijyojwad** [comment]
Hi @bruzecruise and @nextgenusfs - dorado supports adapter trimming starting from version 0.5.0. you can download the latest one (v0.5.1) from https://github.com/nanoporetech/dorado#installation

**Comment by bruzecruise** [comment]
wooo great thanks!!!
