### ISSUE TITLE
Guppy_barcoder identifies barcodes in reads that were previously trimmed

### ISSUE THREAD

**Issue by mariaelf97** [nanoporetech/dorado#198]
Hello,

I am using [this ](https://www.ncbi.nlm.nih.gov/sra/?term=SRR23086714) isolate and to make sure that the barcodes were removed, I ran guppy_barcoder on the reads with the kit name that was used during the library preparation. Now, from my understanding, if the barcodes were properly removed, I should see all reads as unclassified but there are reads assigned to 11 different barcodes. My question is that is this something common that guppy basecaller misses some adapter or barcode sequences when post-processing the reads? 

Thank you!

**Comment by MarkBicknellONT** [comment]
Hi @mariaelf97 ,

I could not see the command that was used to process the raw reads into fastq in the ncbi.nlm.nih.gov link you provided, so I'm not exactly sure how the fastq files were generated.  Assuming it was processed with guppy, `guppy_basecaller` and `guppy_barcoder` both have a `--enable_trim_barcodes` flag which will tell the program to trim off barcodes if there was a successful classification.  This flag is off by default.

I tried running the dataset through the barcoder too with the command:
`guppy_barcoder -i /data/SRR23086714.fastq/ -s /data/SRR23086714.barcoded --barcode_kits SQK-RBK004`
I see a small percentage (794 out of 27294 reads) being assigned a barcode classification.  This would indicate that barcodes were probably mostly trimmed in the original processing, assuming the original reads were barcoded.

As to why some of the reads still have barcodes detected, it is difficult to say without access to the original raw data and the exact command line used to basecall the reads.  There are a few possibilities:
- A different kit to SDK-RBK004 was specified to the barcoder when trimming was first performed, so not all barcodes were trimmed successfully.
- Different trim options were specified when the trimming was first performed.  There are several options which might interfere with classification.
- Some of the reads in the sample were processed separately and the barcode trimming was not performed.
- The barcoder is simply matching to whatever sequences are in in the now-trimmed sample.  Most of the classifications are barcode_05 so it is possible that barcode sequence is somewhat similar to a subsequence in the sample.  Some of the classifications are quite high-scoring though, so it seems odd that this would happen.

**Comment by mariaelf97** [comment]
@MarkBicknellONT 
Thank you for your response.
As far as we know the command they used is as following
`guppy_basecaller --input_path fast5/ --save_path fastq_barcode_hac/ --disable_pings --compress_fastq --progress_stats_frequency 60 --config dna_r9.4.1_450bps_hac.cfg --cpu_threads_per_caller 10 -x auto --barcode_kits SQK-RBK004`
Does it have anything to do with the config file specified? 
The weird thing is that they never trimmed the barcodes but majority of reads don't have barcodes attached to them (unclassified) but some do.

**Comment by MarkBicknellONT** [comment]
Hi @mariaelf97 ,

Thanks for the additional information - so it looks like barcodes have not been trimmed in the initial analysis, which indicates that there's simply not very many barcodes being detected on the original dataset.  With the RBK004 kit it shouldn't be physically possible to attach the sequencing adapter without first having a barcode attached, so it is quite surprising.  In the NIH page they do mention that sequencing was done on a FLO-MIN106 R9.4.1 flow cell and using Rapid Barcoding Kit (SQK-RBK004) for library preparation.  Assuming that is correct, and your `guppy_basecaller` command line is the one actually used, it looks like the right basecall config has therefore been used for calling the data.
If the raw FAST5 files are available it might be worth trying to re-basecall them with the command you specified, to see what results you get.

As this isn't really a dorado question, I'll close this github issue, but if you would like to continue the discussion, please feel free to open an issue with technical services or on the community at https://community.nanoporetech.com/.  If you tag me in a community post there I will be alerted to it.

Kind Regards,

Mark
