### ISSUE TITLE
Is the dependent package koi going to be released open source?

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/dorado#20]
Dorado seems to depend on koi from ONT https://github.com/nanoporetech/dorado/blob/master/cmake/Koi.cmake. Is this going to be released as open-source at one point or will it remain closed?

**Comment by vellamike** [comment]
At the present time the Koi implementation is released as a precompiled library. This may change in the future but not as part of our immediate roadmap.

**Comment by hiruna72** [comment]
Hello,

Are precompiled libraries for `arm` processors available?

**Comment by vellamike** [comment]
Currently they are not but this will shortly be available.
