### ISSUE TITLE
Segmentation fault issue after hours of run - dorado duplex

### ISSUE THREAD

**Issue by sofiabanu** [nanoporetech/dorado#201]
Dear Dorado Team,

I've been trying to run dorado duplex on our HPC with 2x A100 GPUs  with the command -  dorado-0.3.0-linux-x64/bin/dorado duplex --emit-fastq --threads 54 -b 256 dorado_models/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 test_duplex/ > test_duplex.fastq

I run into a segmentation fault issue many hours after the run. PFA the error log. How do I solve this?
[dorado_duplex.txt](https://github.com/nanoporetech/dorado/files/11581784/dorado_duplex.txt)

**Comment by vellamike** [comment]
Can you provide some information about your hardware? What CPU and GPU models are you using, and how much host memory is available on your system?

**Comment by sofiabanu** [comment]
Sure, our CPU is Intel xeon gold, GPU is A100 and memory is 256 Gb. Please let me know if more details are required.

**Comment by yusmiatiliau** [comment]
Hi,

I also have the same problem, running dorado on meth calling on HPC with 1x A100 GPU and 400G memory, and got segmentation fault after running ~6 hours. Attached is the error log. 

Thank you

[CL_dorado_SB09_chr01_35931113.txt](https://github.com/nanoporetech/dorado/files/11594045/CL_dorado_SB09_chr01_35931113.txt)

**Comment by sofiabanu** [comment]
> Sure, our CPU is Intel xeon gold, GPU is A100 and memory is 256 Gb. Please let me know if more details are required.

Could I please get a follow up with this? @vellamike or @tijyojwad

**Comment by tijyojwad** [comment]
Hi @sofiabanu - sorry for the late response. From the logs it's not obvious what could be causing the issue. It looks like it got really close to the end though. Can you check if the output `fastq` is okay (except for perhaps the last entry).

I can suggest 2 ways to debug this - 
1. If you could share a smaller dataset we can reproduce on, then we can take a look.
2. you could build a debug version of `dorado` and run it through the debugger (`gdb`). once it segfaults, the `backtrace` will show where the error occurs.

**Comment by sofiabanu** [comment]
Thanks for the quick response @tijyojwad . The fastq file seems fine so far. Could you please provide instructions on how to compile the debug version and run through gdb?

**Comment by tijyojwad** [comment]
certainly!

these are the [instructions](https://github.com/nanoporetech/dorado#clone-and-build) for building dorado. Where it says `cmake -S . -B cmake-build`, make that `cmake -S . -B cmake-build -DCMAKE_BUILD_TYPE=Debug`.

Then compile as usual. Once it's ready, run the binary under gdb as 
```
gdb -ex run  --args ./dorado ...
```
this will start running dorado under the debugger. note that this will be slow, so doing this on a smaller dataset where it reproduces will be better.

you can also generate a core dump and send that to us. to enable core dump check out this [post](https://stackoverflow.com/questions/17965/how-to-generate-a-core-dump-in-linux-on-a-segmentation-fault).

**Comment by sofiabanu** [comment]
Hi @tijyojwad , for test purposes we tried compiling it on an AWS g4dn.xlarge Ubuntu 22.04 GPU instance. We'll try the single threaded mode as well as compiling on our CentOS HPC and post our results asap.

**Comment by tijyojwad** [comment]
Hi @sofiabanu - just following up to mentioned that we released a newer version of dorado which has some stability improvements. It may fix your issue.

https://github.com/nanoporetech/dorado/releases/tag/v0.3.1

**Comment by sofiabanu** [comment]
Thanks @tijyojwad , we'll test this out right away.

**Comment by sofiabanu** [comment]
@tijyojwad This worked! Thanks a bunch.

**Comment by tijyojwad** [comment]
Excellent :)!
