### ISSUE TITLE
M1 Install of 0.3.0 requires libaec

### ISSUE THREAD

**Issue by dbernick** [nanoporetech/dorado#203]
It seems that libaec is also required - it can be hombrew installed

**Comment by sklages** [comment]
On Linux `libaec` is required as well and needs to be installed if not available. 
So this should probably mentioned only in the docs/requirements.

**Comment by sklages** [comment]
@tijyojwad - oh, okay. I got it wrong, I referred to the building process. As `libaec` is not available in our (in-house built) Linux systems, I needed to build it in order to compile `dorado` ...

**Comment by husamia** [comment]
I got dorado-0.3.0-osx-arm64 working after installing libaec with brew 
brew install libaec

**Comment by tijyojwad** [comment]
@dbernick  we have started packaging Mac libaec libraries with the recent release of dorado https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.3.1-osx-arm64.tar.gz
