### ISSUE TITLE
Sample rate for model and data don't match

### ISSUE THREAD

**Issue by lqhungpt** [nanoporetech/dorado#206]
I got sequencing data from Mk1B with the Fast Basecalling option when I sequenced. I converted my fast5 data to pod5 then I ran with Dorado 0.3.0 on M1 pro chip and I got this issue like that:
[2023-05-29 09:34:54.052] [info] > Creating basecall pipeline
[2023-05-29 09:34:54.128] [error] Sample rate for model (4000) and data (5000) don't match.
Do you have any ideas how to fix this issue?

**Comment by vellamike** [comment]
Hi, can you let me know which model you are using?

**Comment by lqhungpt** [comment]
I am using both the model: dna_r10.4.1_e8.2_400bps_sup@v4.1.0 and the model dna_r10.4.1_e8.2_400bps_hac@v4.1.0 had the same result.

**Comment by vellamike** [comment]
It seems you are using data which was generated at 5kHz. Can you try the
4.2 models rather than 4.1?

**Comment by lqhungpt** [comment]
> 

It seems to work now. Thank you very much.
