### ISSUE TITLE
Duplex rates >100% & aborted pipeline

### ISSUE THREAD

**Issue by dubravkapezic-LG** [nanoporetech/dorado#207]
Hi, 

I have been performing duplex basecalling using Dorado on Amplicon libraries prepared using the Native Barcoding kit 24.
Very high rates of duplex reads have been identified, which is great, but for some samples it's above 100% (102-104%). 
I was wondering why that happens? 

I have also encountered an issue where the pipeline reaches 9900 reads and than stalls for hours, only to eventually complete. However, in some cases, instead of completing and reporting the number of basecalled reads and bases, it just says '9900killed'. I am attaching a screenshot. 

Thank you!

<img width="957" alt="Screenshot 2023-05-30 at 09 45 14" src="https://github.com/nanoporetech/dorado/assets/135009364/1518e6e6-bef6-4bfb-9666-91628cb14d74">

**Comment by vellamike** [comment]
As you guessed, >100% is physically impossible. 

* Which version of dorado are you using? based on that output it seems not to be 3.0 ? Can you try the latest one (This does not require duplex tools)
* How are you calculating pairing rates?

**Comment by vellamike** [comment]
Hi @dubravkapezic-LG , I think the reason you get the `killed` message is that you are running out of host RAM ( this is just an educated guess). You are using a version of Dorado which is old, dorado 0.3.0 should solve this problem.

All you need to do is [install dorado](https://github.com/nanoporetech/dorado#installation) and run the Dorado duplex command, for example `dorado duplex dna_r10.4.1_e8.2_400bps_sup@v4.1.0 pod5s/ > duplex.bam`. 


Let me know how it goes.

**Comment by dubravkapezic-LG** [comment]
Thank you, I'll try that. 
It would be helpful to have clear installation instructions if possible, for those like me not overly familiar with the command line in Linux. 
For the future, what is the best way to keep abreast with new versions? Simply checking on the Github page? 

Do I need to re-download all the basecalling models as well? 

Thank you again.

**Comment by vellamike** [comment]
> It would be helpful to have clear installation instructions if possible, for those like me not overly familiar with the command line in Linux.

I was thinking of posting a Youtube video with installation and usage instructions? Would that help?

> For the future, what is the best way to keep abreast with new versions? Simply checking on the Github page?

The Nanopore Community forum and following on GitHub are good ways to keep up to date with latest updates. Also following certain accounts like @nanopore @vella and @iiSeymour on twitter.

> Do I need to re-download all the basecalling models as well?
The old models do not need to be updated, but Dorado releases often come with new models

**Comment by dubravkapezic-LG** [comment]
A You Tube video would be extremely helpful, thank you!

**Comment by dubravkapezic-LG** [comment]
BTW -- after the version update, the `dorado duplex dna_r10.4.1_e8.2_400bps_sup@v4.1.0 pod5s/ > duplex.bam` command  is coming back with: 

__- No duplex pairs file provided, pairing will be performed automatically_

Is this expected?

**Comment by vellamike** [comment]
Hi - yes, this is expected, what the message is telling you is that since you didn't run duplex tools, dorado will perform pairing itself. It's a good thing.

**Comment by dubravkapezic-LG** [comment]
Awesome. Thank you.
