### ISSUE TITLE
Dorado 0.3 Duplex using wrong model?

### ISSUE THREAD

**Issue by palakpsheth** [nanoporetech/dorado#210]
Hello,

Using Dorado 0.3 to call duplex reads, when providing the path to the desired model however the log shows another model (`downloading dna_r10.4.1_e8.2_4khz_stereo@v1.1`) being downloaded. Is this expected? The calling speed makes me think the requested SUP model is being used but how to confirm? Thank you!

`/home/ubuntu/dorado-0.3.0-linux-x64/bin/dorado duplex --emit-sam -v --threads 31 --guard-gpus ./dna_r10.4.1_e8.2_260bps_sup@v4.1.0 /data/ONT_002_dorado/pod5_pass/barcode01/ > /data/ONT_002_dorado/unmapped_sam_pass/barcode01/barcode01_duplex_dna_r10.4.1_e8.2_260bps_sup@v4.1.0.unmapped.sam`

`[2023-05-30 16:43:14.373] [info] > No duplex pairs file provided, pairing will be performed automatically`
`[2023-05-30 16:43:15.364] [info]  - downloading dna_r10.4.1_e8.2_4khz_stereo@v1.1`
`[2023-05-30 16:43:22.521] [debug] Auto batch size: GPU memory available: 14.349591552GB`
`[2023-05-30 16:43:22.521] [debug] Auto batch size: testing up to 192 in steps of 64`

**Comment by tijyojwad** [comment]
Hi @palakpsheth - yes the download is expected. there are 2 stages in duplex calling. during the first stage simplex calling is performed using the sup model you passed in. after that the stereo model is invoked on paired simplex reads using the downloaded model.
