### ISSUE TITLE
Insufficient memory, required 8GB, available 7.8Gb with GTX 1070

### ISSUE THREAD

**Issue by lqhungpt** [nanoporetech/dorado#211]
Hi everyone,
Today, I tried to run Dorado on GTX 1070 Nvidia but I got this issue. Can you show me how to fix this? I found a link to fix it but I did not find where to get cuda_utils.cpp for Windows version.
[info] > Creating basecall pipeline
[warning] Auto batchsize detection failed. Insufficient memory, required 8GB, available 7.8GB

**Comment by tijyojwad** [comment]
Hi @lqhungpt - what is the issue?

We only have auto-batch size detection for 8GB and more, hence the warning. Below that memory limit `dorado` uses batch size of 128 (source [here](https://github.com/nanoporetech/dorado/blob/master/dorado/utils/cuda_utils.cpp#L232)). You can override that using the `-b` option.

**Comment by lqhungpt** [comment]
> Hi @lqhungpt - what is the issue?
> 
> We only have auto-batch size detection for 8GB and more, hence the warning. Below that memory limit `dorado` uses batch size of 128 (source [here](https://github.com/nanoporetech/dorado/blob/master/dorado/utils/cuda_utils.cpp#L232)). You can override that using the `-b` option.

It did not work when I try with -b

**Comment by tijyojwad** [comment]
what was the error? note that the `-b` option needs to be a multiple of 64 (if it's not, dorado automatically pads it to the next multiple of 64).

**Comment by MarkiyanSV** [comment]
If dorado v0.3.0 is run on GTX 1070, than missing sm_61 compile flag for libkoi would also be an issue...

https://github.com/nanoporetech/dorado/issues/179

Run dorado 0.2.2 in such case (untill sm_61 flag is included in libkoi 0.3.x compilation...)

**Comment by lqhungpt** [comment]
> what was the error? note that the `-b` option needs to be a multiple of 64 (if it's not, dorado automatically pads it to the next multiple of 64).

It is running anything after I entered the line code

**Comment by lqhungpt** [comment]
> If dorado v0.3.0 is run on GTX 1070, than missing **sm_61** compile flag for **libkoi** would also be an issue...
> 
> #179
> 
> Run **dorado 0.2.2** in such case (untill sm_61 flag is included in libkoi 0.3.x compilation...)

How to download dorado 0.2.2?

**Comment by lqhungpt** [comment]
> If dorado v0.3.0 is run on GTX 1070, than missing **sm_61** compile flag for **libkoi** would also be an issue...
> 
> #179
> 
> Run **dorado 0.2.2** in such case (untill sm_61 flag is included in libkoi 0.3.x compilation...)

how to download this version? I only found one folder on release site but it did not include dorado.exe for windows

**Comment by MarkiyanSV** [comment]
Just substitute 0.3.0 in the URL with 0.2.2:

https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.2.2-win64.zip

https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.2.2-linux-x64.tar.gz

But ideally (if you are on linux) clone last commit for libkoi-0.2.2 [2a1dac3] and compile it:
https://github.com/nanoporetech/dorado/tree/2a1dac3732e244786e6d61e86f6de7aa6b76e6dc

**Comment by lqhungpt** [comment]
> Just substitute 0.3.0 in the URL with 0.2.2:
> 
> https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.2.2-win64.zip
> 
> https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.2.2-linux-x64.tar.gz
> 
> But ideally (if you are on linux) clone last commit using libkoi-0.2.2 [[2a1dac3](https://github.com/nanoporetech/dorado/commit/2a1dac3732e244786e6d61e86f6de7aa6b76e6dc)] and compile it: https://github.com/nanoporetech/dorado/tree/2a1dac3732e244786e6d61e86f6de7aa6b76e6dc

It worked for me when I tried with the 0.2.2 version but I also got the same notification as with the 0.3.0 version.

**Comment by tijyojwad** [comment]
As an FYI, we currently don't have plans to support architectures before Volta for dorado.
