### ISSUE TITLE
dorado duplex and duplex_tools pair

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/dorado#213]
Hi, I would like to know the difference between `duplex_tools pair` and `dorado duplex`:

1. I run `duplex_tools pair` for the sam file generated from the old version of dorado, trying to find the duplex reads. And I get the pair_ids_filtered.txt, and duplex rate is 3%.
2. I also run `dorado duplex --min-qscore 9 ` just for the pod5 generated from the sequencer. No duplex pairs file provided, pairing will be performed automatically. And I get the duplex.sam, and duplex rate is very low.

For these runs, the data is same. But I got different number of duplex reads, `duplex_tools` get more duplex reads than `dorado duplex`.
So do two methods use the different methods to find the duplex reads, maybe `duplex_tools` find the reads through sequence information, and `dorado duplex` is through signal information. Or just because I set the `--min-qscore 9` to filter the reads for dorado, causing the different duplex reads number.

**Comment by vellamike** [comment]
Hi, `duplex_tools pair` and `dorado duplex` use slightly different pairing and splitting algorithms. It is possible that `min-score` is the issue here.  You mention that your duplex rate was 3% with `duplex_tools`, which is low, What was the duplex rate with `dorado duplex` ?

**Comment by vellamike** [comment]
P.S going forward, improvements to pairing will all be added to `dorado duplex` and `duplex_tools` is largely deprecated.

**Comment by Flower9618** [comment]
> Hi, `duplex_tools pair` and `dorado duplex` use slightly different pairing and splitting algorithms. It is possible that `min-score` is the issue here. You mention that your duplex rate was 3% with `duplex_tools`, which is low, What was the duplex rate with `dorado duplex` ?

Hi, @vellamike . 
The duplex rate with `dorado duplex` is only 0.0?%, which is much lower than 3% by `duplex_tools`

**Comment by vellamike** [comment]
I don't understand - are you saying zero duplex reads are being generated?

**Comment by Flower9618** [comment]
> I don't understand - are you saying zero duplex reads are being generated?

for dorado duplex, duplex rate is 0.16%, for duplex_tools pair, duplex rate is 3%

**Comment by vellamike** [comment]
Thanks, that discrepancy is odd. can you let me know the details of how you calculate pairing rate?

**Comment by Flower9618** [comment]
For dupex_tools, it will generate the output about duplex rate into screen, I just use the value.
Foe dorado duplex, it will generate the sam file, where there is the tag about 'dx'. So I calculate the proportion of molecules which dx is 1 in the total molecules.

**Comment by vellamike** [comment]
Hi @Flower9618  - could you compare pairing rates by using the same metric instead, just so we are comparing the same number? Please calculate the proportion of molecules which dx is 1 for both the pairs list method (duplex_tools) and the automatic pairing method.

**Comment by vellamike** [comment]
Closing this issue as `dorado duplex` is now the recommended way to detect duplex pairs
