### ISSUE TITLE
Help choosing the appropriate Basecalling Models

### ISSUE THREAD

**Issue by ChristopherRichie** [nanoporetech/dorado#214]
Hi Nanoporetech, 

I have a Minion Mk1C, and due to (reasons related to network access), it is not always updated promptly to the latest OS and applications improvements.

I see that there are many basecalling models listed here (https://github.com/nanoporetech/dorado#available-basecalling-models), with attributes I understand like "r9.4.1" and others that I do not understand like "e8", "(4kHz)" and "260bps".

How do choose the appropriate basecalling model for my "current" system, assuming that I know the catalog numbers for my flow cell and reagent kits, as well as the version numbers of the apps installed on the MinIon Mk1C (and the run configuration)?

(The run configuration details in the attached screenshot indicates "fast model, 400bps", but I do not know if that is based on the speed that the machine actually ran at.)

![image](https://github.com/nanoporetech/dorado/assets/74983235/164234ef-3c2d-48ff-a98e-844636472dd3)

thanks
chris

**Comment by raronan** [comment]
Hi Chris

Just to follow up here and help you pick the correct model for your run.   As you have already seen the models names correspond to a how of different parameters - both chemistry and run settings.  Breaking this down:

e.g. dna_r10.4.1_e8.2_400bps_fast@v4.2.0 (5kHz)

- **dna** --> this refers to the analyte being sequenced.  This will be dna unless you have used the direct rna kit (where it will be rna) 
- We then have the **pore type**.  This generally corresponds to the flow cell type.  FLO-MIN114/FLO-FLG114 will be r10.4.1 whereas FLO-MIN106/FLO-FLG001 will be r9.4.1
- **Chemistry type** - the e.8.2 here refers to the chemistry type (kit 14 in this instance).
-   **translocation Speed** - this is a setting selected at run setup.  On starting your run there will be a pop up that indicates whether you want to run at 260bps of 400bps.  The former is more accurate but gives less data.  In your instance it looks like you have run 400bps (which is the default).  in the latest release (23.04) the 260bps option has been removed.  
- **Model type** - This is how large is the model you want to run.  FAST - smallest model and will keep up on most devices.  SUP is the highest accuracy but the slowest basecalling and then HAC sits in the middle.  
- **Model Version Number** - this is the version of the model.  In this instance 4.2.0 (which is the current newest version we have released)
- **Sampling rate** - this is the number of data points per a second we are taking during acquisition.  This was an update in the latest MinKNOW release - 23.04.  https://community.nanoporetech.com/posts/software-release-23-04-5-f-12294 .  This details the move to 5khz for the kit14 data and why we have done this.  Given your data was generated on an older release you will need the 4khz models.  The sample rate is included in the meta data of a fast5 or pod5 if you need to check.  

Not shown on the model above example but we also have modified base versions of these models that will call (e.g.) 5mC as part of the basecalling.  e.g. dna_r10.4.1_e8.2_400bps_fast@v4.2.0_5mCG_5hmCG@v2 (5kHz) will call both 5mC and 5hmC as part of the basecalling and output these into a BAM file alongside your fastqs.  

Taking your run report here - you are on 22.12 (so will be 4khz).  Its kit 14 chemistry type, 400bps.  The most recent models for this condition are (depending if you want to use fast, HAC or SUP)

- dna_r10.4.1_e8.2_400bps_fast@v4.1.0
- dna_r10.4.1_e8.2_400bps_hac@v4.1.0
- dna_r10.4.1_e8.2_400bps_sup@v4.1.0

If you wanted modified bases the options are: (with the equivalent AHC and 

- dna_r10.4.1_e8.2_400bps_fast@v3.5.2_5mCG@v2
- dna_r10.4.1_e8.2_400bps_hac@v3.5.2_5mCG@v2
- dna_r10.4.1_e8.2_400bps_sup@v3.5.2_5mCG@v2
- dna_r10.4.1_e8.2_400bps_fast@v4.1.0_5mCG_5hmCG@v2
- dna_r10.4.1_e8.2_400bps_hac@v4.1.0_5mCG_5hmCG@v2
- dna_r10.4.1_e8.2_400bps_sup@v4.1.0_5mCG_5hmCG@v2

**Comment by ChristopherRichie** [comment]
thanks for this break down of the naming convention.
i was not able to find such a breakdown on the community site.

I want to analyze data from these kits:
SQK-RBK004 (v9 chemistry)
SQK-LSK109  (v9 chemistry)
SQK-LSK110 (v10 chemistry)

I expect that I can get the translocation speed and sampling speed from the summary report.

I presume all v14 chemistry use "e8.2", but is there a chart for **mapping other chemistries to "e-codes**"?
 
Your assistance allows me to move forward, and is very appreciated.
chris

**Comment by ekushele** [comment]
I also encountered this problem. 
How can I map "kit9" to e-code?

**Comment by eesiribloom** [comment]
I similarly cannot find the correspondence between e-code and kit chemistry. In my case I would like to basecall samples sequenced on a FLO-PROO2 (R9.4.1) with kit SQK-LSK110. will this work on dorado?

**Comment by susie-ont** [comment]
Hello! Here is the mapping between kit chemistries and e8 vs. e8.2:

- Kit 9 - e8
- Kit 10 - e8
- Kit 14 - e8.2

We will update the readme to include this soon. 
@eesiribloom - we do have models available for this condition, please see the models that begin with `dna_r9.4.1_e8` in the [DNA models](https://github.com/nanoporetech/dorado#dna-models) section.

I hope this helps!

**Comment by eesiribloom** [comment]
Great, thanks! just double checking kit 10 isn't e8.1 not e8? 
Cheers

**Comment by lukesarre** [comment]
How about SQK-LSK112?
In general it feels a bit flawed to make the e-code so important for basecalling, but so difficult to find for each kit!

**Comment by HalfPhoton** [comment]
Issues around model selection should be improved by the introduction of [automatic model selection](https://github.com/nanoporetech/dorado?tab=readme-ov-file#automatic-model-selection-complex) in dorado 0.5.0 (Dec 2023).
Please re-open if you have further questions.
