### ISSUE TITLE
CMake Error at cmake/Koi.cmake:18 

### ISSUE THREAD

**Issue by TessaMBradford** [nanoporetech/dorado#216]
I have and issue on running cmake -S . -B cmake-build
  
  CMake Error at cmake/Koi.cmake:18 (message):
    Unsupported CUDA toolkit version: 10.1.243
  Call Stack (most recent call first):
    cmake/Koi.cmake:46 (get_best_compatible_koi_version)
    CMakeLists.txt:39 (include)

What version of CUDA toolkit is required?

Thanks,

Tessa

**Comment by tijyojwad** [comment]
Hi Tessa - Koi supports the [following](https://github.com/nanoporetech/dorado/blob/master/cmake/Koi.cmake#L8) CUDA versions
```
12.0 11.8 11.7 11.3
```

**Comment by TessaMBradford** [comment]
Thanks for this info
