### ISSUE TITLE
dorado-0.3.0-linux-x64.tar.gz seems to contain version 0.2.4+3fc2b0f of the dorado binary

### ISSUE THREAD

**Issue by rainwala** [nanoporetech/dorado#217]
Hello, I just installed dorado-0.3.0-linux-x64.tar.gz on Ubuntu 20.04 LTS, but when I tried the command dorado -v from within the bin directory, I got the output 0.2.4+3fc2b0f
Shouldn't the version be 0.3.0?

**Comment by vellamike** [comment]
Hi, @rainwala , I just downloaded `dorado-0.3.0-linux-x64.tar.gz` and ran `dorado -v` and I get:

```
$ ./dorado  -v
0.3.0+88df11b+dirty
```

Perhaps you're making a mistake with paths or something? I can't explain why you would see 0.2.4

**Comment by vellamike** [comment]
wild guess: You put dorado on your PATH previously and are picking up the old one.

**Comment by rainwala** [comment]
My bad, you're right. I did link the new binary, but I am doing this on a PromethION box, and I didn't realise that dorado cam pre-installed, and that my ln command did not overwrite the previous installation!

**Comment by vellamike** [comment]
Glad you've fixed it - but FYI Dorado does **not** come pre-installed on a PromethION box, you've got 0.2.4 in some other way.

**Comment by rainwala** [comment]
Ah OK... thanks for letting me know. I must have installed it and forgotten :)
