### ISSUE TITLE
high RAM consumption when using Dorado with modified base calls.

### ISSUE THREAD

**Issue by tijyojwad** [nanoporetech/dorado#219]
I also experience high RAM consumption when using Dorado with modified base calls.

`dorado basecaller model/dna_r10.4.1_e8.2_400bps_sup@v4.2.0  pod5/ --recursive --verbose -x cuda:all --modified-bases 5mC 6mA > reads_5mc_6mA.bam`

After some hours on the promethION machine the RAM consumption increases to 100% and the the process is killed. The server has 376GB RAM. GPU seems not to be the problem.

On another server with slightly more RAM (1 TB) the same command currently occupies 40% of RAM (after 18 hours) and seems to be stable around that value.

![image](https://github.com/nanoporetech/dorado/assets/16762600/a8218817-58d9-4659-9833-57f1d84d2fc7)

Here is the current log of the process:

```
[2023-05-31 22:15:53.760] [debug] - matching modification model found: dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mC@v2
[2023-05-31 22:15:53.760] [debug] - matching modification model found: dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v2
[2023-05-31 22:15:53.760] [info] > Creating basecall pipeline
[2023-05-31 22:15:56.264] [debug] Auto batch size: GPU memory available: 50.094669824GB
[2023-05-31 22:15:56.264] [debug] Auto batch size: testing up to 768 in steps of 64
[2023-05-31 22:15:57.497] [debug] Auto batchsize: 64, time per chunk 19.251701 ms
[2023-05-31 22:15:57.539] [debug] Auto batchsize: 128, time per chunk 0.333264 ms
[2023-05-31 22:15:57.594] [debug] Auto batchsize: 192, time per chunk 0.284672 ms
[2023-05-31 22:15:57.659] [debug] Auto batchsize: 256, time per chunk 0.253724 ms
[2023-05-31 22:15:57.743] [debug] Auto batchsize: 320, time per chunk 0.26273602 ms
[2023-05-31 22:15:57.835] [debug] Auto batchsize: 384, time per chunk 0.23819466 ms
[2023-05-31 22:15:57.937] [debug] Auto batchsize: 448, time per chunk 0.22913371 ms
[2023-05-31 22:15:58.061] [debug] Auto batchsize: 512, time per chunk 0.242634 ms
[2023-05-31 22:15:58.193] [debug] Auto batchsize: 576, time per chunk 0.22761244 ms
[2023-05-31 22:15:58.382] [debug] Auto batchsize: 640, time per chunk 0.2966767 ms
[2023-05-31 22:15:58.542] [debug] Auto batchsize: 704, time per chunk 0.22598837 ms
[2023-05-31 22:15:58.708] [debug] Auto batchsize: 768, time per chunk 0.21604133 ms
[2023-05-31 22:15:58.722] [debug] - set batch size for cuda:0 to 768
[2023-05-31 22:15:58.722] [debug] - adjusted chunk size to match model stride: 10000 -> 9996
[2023-05-31 22:15:58.722] [debug] - adjusted overlap to match model stride: 500 -> 498
[█▍                            ] 4% [18h:48m:19s<15d:14h:02m:29s] 
```

nvidia-smi output:

![image](https://github.com/nanoporetech/dorado/assets/16762600/c78910e0-72b3-4620-8ac0-c16a5cd7b6fc)

I already did a few duplex base calls where I did not notice such large RAM consumption.
Is this to be expected that mod basecalling requires so much RAM? 

Thank you 
Alex

_Originally posted by @axgraf in https://github.com/nanoporetech/dorado/issues/86#issuecomment-1572253437_

**Comment by axgraf** [comment]
Thank you @tijyojwad and @MarkiyanSV.

@MarkiyanSV I have tried your solution:
> @axgraf I assume you use latest version of dorado. This looks like some memory leaks arround modified bases processing subroutines.
> 
> Untill it is fixed, try splitting input data into 15min - 1hour basecalling time chunks, and process them in series, with new dorado process invocation for each chunk.
> 
> Can also try comparing memory usage and performance with pod/fast5 input formats.
> 
> In such case (on NUMA systems), optimal performance is likely to be achieved, when the dorado max memory allocation stays under the ammount of RAM connected to a single physical processor (so no CPU interconnect contention happens).

I have splitted the pod5 files into chunks of 25 and passed them sequentially to dorado. Now the basecalling is working stable without using much memory. I used the latest version of Dorado (v.0.3.0+88df11b+dirty). 

I haven't been able to compare memory usage with fast5 files yet, as we have a lot of runs piling up right now, so I'll have to hurry up getting them basecalled. I will give it a try as soon as possible.

Might be off topic, but the issue seems to be also present in Guppy (Version 6.5.7+ca6d6af).
I converted the reads into a single large Fastq file (319GB) and passed it to guppy barcoder. I experience the same memory issue. This machine has 256 GB of RAM.

`ont-guppy_6.5.7/bin/guppy_barcoder -x cuda:all -i single_fastq/ -s demultiplexed --enable_trim_barcodes`

![image](https://github.com/nanoporetech/dorado/assets/16762600/6aca0105-f84f-4663-98e7-39a5958fa527)


 I also used the same approach and splitted the Fastq files also into chunks of 4000 reads per file, then it is running without any problems.

**Comment by tijyojwad** [comment]
Hi @axgraf - thanks for the update. Unfortunately we haven't quite addressed the issue yet, but we'll keep at it. The suggestion from @MarkiyanSV is a good alternative alternative, thanks for that :)!

**Comment by Kirk3gaard** [comment]
Tried running some modified basecalling today and also got the job killed by "oom" after several hours on a node with 4xA100 cards. The resume option would be nice  #72 . 

# Commands:
DORADOBASE=~/software/dorado-0.3.0-linux-x64/
DORADO=$DORADOBASE/bin/dorado
MODEL="dna_r10.4.1_e8.2_400bps_sup@v4.2.0"
CONFIG=$DORADOBASE/models/$MODEL
MODS="5mC 5mCG_5hmCG 6mA"
$DORADO basecaller $CONFIG pod5_pass/ --modified-bases $MODS > mod.$FLOWCELLID.$MODEL.bam


Error message:

[██████▊                       ] 22% [05h:49m:23s<19h:39m:33s] 
Killed                  $DORADO basecaller $CONFIG $INPUTDIR --modified-bases $MODS > $OUTPUTDIR/mod.$FLOWCELLID.$MODEL.bam
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=64485188.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by anthony-aylward** [comment]
I am also seeing this issue with version 0.3.0 on Ubuntu 20.04. Luckily my machine has 1TB RAM, but ~460 GB RAM are being used by :

```
dorado basecaller dna_r10.4.1_e8.2_260bps_sup@v4.1.0 pod5/ --modified-bases 5mCG_5hmCG
```

The `pod5/` directory contains a single 555GB POD5 file.

I don't think I had this issue with version 0.2.4.

**Comment by Kirk3gaard** [comment]
@tijyojwad 512 GB RAM and the dataset is only ~15 Gbp from a MinION run.

**Comment by yusmiatiliau** [comment]
Hi ONT, 

I also encountered this issue when running modified basecalling on my sample (the pod5 is ~360GB). Using previous 0.3.0 version of dorado, the run was killed after ~11 hours (basecalled at ~50% of reads) with out-of-memory error. I provided 200G on A100 GPU. Using the latest version of 0.3.1, the same run was killed after ~2.5 hours and error log did not show how far the basecalling has gone. I have not tried the --resume option, but the resulting bam with the latest version is only 2.6GB, so still quite far from finishing. Also, there is no mention of this issue being fixed on the 0.3.1 release, so is this still work in progress?

It did work when I split the data into several pod5 chunks, and run dorado separately, but it's just not very convenient in the long run, especially when you have multiple samples. 

Thanks

**Comment by HalfPhoton** [comment]
Closing this issue as we now advise [subsetting the pod5](https://github.com/nanoporetech/dorado?tab=readme-ov-file#improving-the-speed-of-duplex-basecalling) for better performance and stability in the documentation. 
We've also added the `--resume` feature since this ticket was originally created.

**Comment by xsvato01** [comment]
Hi, I am having OOM kills (137 exit status) with simple non-modified calling. Are there any minimal RAM (and also CPU) requirements for Dorado? I could not find it in the readme. I used 64 GB of RAM. GPU has 10GB VRAM. I am concurrently running minimap2.

Also, can input .fast5 files (as opposed to the recommended and optimized .pod5) cause this issue?

Thank you
