### ISSUE TITLE
intermittent but prolonged slow down during basecalling

### ISSUE THREAD

**Issue by wilsonte-umich** [nanoporetech/dorado#223]
I noticed during a base calling run that Dorado worked at a good pace initially (for hours, presumably), then for many hours it slowed down a lot, then it picked back up again to "full speed" (I can't say if it did this more than once).

During the fast phases, both CPU and GPU were busy at essentially 100%, as I'd expect.

During the slow phase, both CPU and GPU were only intermittently active.  Both would be idle at 0% for substantial times, then pulse briefly to higher activity. CPU would typically not get above 50% during this phase, GPU would hit 100% but not stay there. 

The run in question was a filtered subset of putative SV-containing reads being re-basecalled using the sup model. One possible consequence is these may have included a larger than typical fraction of lower quality reads. But I have a hard time ascribing the strange prolonged slow period to the reads as they would have been intermixed throughout.

The job never crashed, progressed some even during the slow phase, and finished without error.  But the slow phase was quite significant - the job was on pace early on to finish in ~11 hours, but ended up taking nearly 20 hours.

The smallish Slurm job had 1 CPU and 1 V100 GPU.  Other details:
Dorado version: 0.3.0-linux-x64
model: dna_r10.4.1_e8.2_400bps_sup@v4.1.0

```
 lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterprise
Description:    Red Hat Enterprise Linux release 8.4 (Ootpa)
Release:        8.4
Codename:       Ootpa
```

```
dorado basecaller --emit-moves --read-ids ${READ_IDS_FILE} ${MODEL} ${POD5_DIR}
```

The following was taken during the FAST phase, sorry I didn't get a copy during the slow phase.  Note that on our shared server cluster, another user did have a job running on the other GPU on the node - however, this did not correlate at all with the fast and slow phases. Their job started in the middle of the slow phase, and my job picked up to fast while theirs was still running. 

```
nvidia-smi    
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   33C    P0    65W / 250W |    514MiB / 16384MiB |     50%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  On   | 00000000:D8:00.0 Off |                    0 |
| N/A   63C    P0   244W / 250W |  14136MiB / 16384MiB |    100%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   1759813      C   /opt/xxxxxxxlab/bin/python        382MiB |
|    1   N/A  N/A   1399576      C   ....3.0-linux-x64/bin/dorado    14132MiB |
+-----------------------------------------------------------------------------+
```

**Comment by MarkiyanSV** [comment]
Assuming there is no storage or system bus contention:
First try isolating this issue, wheather it is realted to input data or some race conditions during processing.
The easiest way would be to split input dataset into chunks which gets processed in 15-30 mins
https://github.com/nanoporetech/dorado/issues/86#issuecomment-1572549339

than monitor processing time of each chunk: 
**/usr/bin/time -v -o $CHUNK.time.log dorado ....**

**Comment by wilsonte-umich** [comment]
Thanks - yes, I considered that an external system factor like IO might be throttling Dorado but I couldn't find anything obvious when it had slowed down. 

Unfortunately, today our cluster is going down for scheduled maintenance for a few days...

As for breaking it in chunks, would that create any problems with the read ids filtering?  I also wonder whether applying a filter for thousands of read ids across hundreds of pod5 files might be an issue?  Also, I assume you suggest this as a diagnostic, I would hope to not have to do that routinely.

**Comment by MarkiyanSV** [comment]
Yes, this is only for diagnostics. (If you locate slow chunk - try further splitting it up, and perhaps sharing it with developers, so they can debug it). 
Also I would also try going from fast5 files directly, group them into similarly sized chunks, and see if any groups take much longer to process. 
Obviosly make sure to group them in chronological order (as they were written out during run), so influence of run conditions (if any) onto the basecalling speed can be detected.

**Comment by tijyojwad** [comment]
> I also wonder whether applying a filter for thousands of read ids across hundreds of pod5 files might be an issue?

This shouldn't be an issue, but note that reading from multiple pod5 files does incur more overhead (more files need to be opened and read through). So working with fewer, larger files is recommended.

A few things I can think of -
1. I/O throughput changes as you suggested. If your file is on an external file system, then network bandwidth will play a role. If possible, you could try to copy the data over to your local system and then running dorado.
2. Is your read ids list sparse and the dataset really large? It could be that the filtering is taking time as we iterate over the data.

**Comment by wilsonte-umich** [comment]
Thanks, that's much of what motivated my question.  The multiple read source files is how they are delivered to me by the core facility, so not something I'd want to have to adjust, and I gather is common.  But I don't know how the filter is applied exactly, e.g., does it hunt and peck for each read individually (inefficiently going back to each pod5 repeatedly), stream the pod5s (or fast5s) in one pass and reject reads not on the filter list, something else entirely?

I don't have an exact number, but as a ballpark the filter list might be something like 5% of the total reads.  The idea is to apply sup to just that fraction that we need best base accuracy for, to avoid the considerable additional overhead of running sup on all reads (even with the unexpected slowdown, it did achieve that goal). This seems like a generally useful strategy, does it match the current filter design?

The files were on a high speed network drive designed for purposes like this on our cluster, and it generally is more that sufficient, including during the fast phases of my run where IO clearly kept up.  But if problems persist, I will consider copying files to the execution node prior to running Dorado.

Unfortunately, I can't try anything until next week due to the scheduled maintenance period.

**Comment by MarkiyanSV** [comment]
@wilsonte-umich
**The files were on a high speed network drive...**
So, is this drive array SSD or HDD based?
By any chance any Seagate SMR HDD's in there or any QLC flash?
Are you writing to the same disk(s) as you are reading from at the same time?
I would split such workflow (processing 5% of SUP data) onto two parts:
1. (Optional) for each pod/fast5 file, first cat it to /dev/null (get it into the node's ram buffer), provided it is smaller than 1/2 node RAM size.
2. Filter needed raw reads from it and write them to local node scratch storage.
3. Basecall from local storage (and write out to storage with basecall results), can be local first. (Ideally use differend physical HDD/SSD from the one with input data).

also (depending of filesystem used) remeber such mount options as:
**commit=300,data=writeback,noatime,nodiratime**
@tijyojwad And they may be also quite userfull for Gridion/Promethion & P2 device FS too...

PS: In such intermittent storage performance cases, there is a lot of variables to watch...

Unfortunatelly both **SMR** HDD's and **QLC** flash are **VERY BAD for sustained mixed IO** workloads (throughput drops by order(s) of magnitude)... **RAID5 / RAID6** doesn't help either... And if used together, (like current new **WD RED 8TB drives**) - it grinds to a full halt in mixed IO...

https://www.servethehome.com/wd-red-smr-vs-cmr-tested-avoid-red-smr/

For processing NAS RAID I would go with **RAID10 or RAID0**, with 32-128MB chunk size and use bigalloc for FS with cluster size 128K - 1M.

**Comment by wilsonte-umich** [comment]
Thanks, all helpful perspectives. Will try to build a smarter IO, since yes, I was reading and writing the same drive. The purpose of the shared scratch drive is to do large file IO during HPC and it does so perfectly well across many genomics applications (including much of the Dorado run I described), but RAM and node-local drives are also available, with some copying before and after execution.

For perspective, I am an end user of our ample university HPC cluster and don't know the answer to most of your detailed questions. Certainly, I'm not in a position to change drive mounts. That may be frustrating to you, but I don't think I'm unusual...

**Comment by tijyojwad** [comment]
> I don't know how the filter is applied exactly, e.g., does it hunt and peck for each read individually (inefficiently going back to each pod5 repeatedly), stream the pod5s (or fast5s) in one pass and reject reads not on the filter list, something else entirely?

We currently do the latter, but there are different ways to go about it. However those include random access into pod5s, and could again lead to some perf regression. Network drives sometimes have prefetching which works nicely with serial streaming of data (which is `dorado` is doing now).

Another possibility is that perhaps the other application running on your system was very CPU hungry, causing dorado threads to starve. In general it's best if `dorado` is the only application running on your system. `dorado` scales pretty much linearly with multiple GPUs, so in your setup you could schedule it to run using both GPUs and not get interrupted by other applications.

**Comment by wilsonte-umich** [comment]
Yes, first thing I will do once the cluster is back up is to request all the GPUs on a node to have exclusive use.  I suspect the shared scratch drive prefetches (at least it seems to behave that way), so this problem might just magically stop happening, and if not, I'll copy files to local first.  Thanks all, I'll report back when I'm able.

**Comment by wilsonte-umich** [comment]
At this point, I am confident the initial observation was due to intermittent IO limitations, not dorado. I will check with sys admins to understand why scratch drive performance can be so variable (likely load on a shared resource).

To fill in a few details, it was 699G net file size over 941 pod5 files (file sizes matched publicly available ONT WGS data), filtering for 9.5% of the total reads.

The following strategy gave consistent dorado performance:
- copy a batch of pod5 files from shared scratch drive to worker node /dev/shm
- run dorado on the batch
- write to indexed tmp file on node local drive
- repeat as needed
- cat tmp files back to shared scratch drive

```sh
cd $POD5_DIR
POD5_FILES=(*.pod5)
POD5_BATCH_SIZE=20 # number of pod5 files processed in a batch
for ((i=0; i < ${#POD5_FILES[@]}; i+=POD5_BATCH_SIZE)); do 
    POD5_CHUNK=${POD5_FILES[@]:i:POD5_BATCH_SIZE}
    cp $POD5_CHUNK /dev/shm # adjust file paths as needed
    dorado basecaller --read-ids $READ_IDS_FILE $ONT_MODEL_DIR /dev/shm |
    samtools view -b - > /tmp/$i.unaligned.bam 
    rm /dev/shm/*.pod5
done
samtools cat /tmp/*.unaligned.bam > /scratch/$UBAM_FILE
rm /tmp/*.unaligned.bam
```

Regardless, transfer of pod5 to the node is a significant slow step. By isolating the transfer, dorado stays maximally active when running, but of course does nothing while files are copying, so the net required time might be a wash?

Hope this thread helps somebody - I run many jobs (e.g., minimap2) from scratch and never encountered IO limits so notably.

**Comment by tijyojwad** [comment]
Thanks for the details @wilsonte-umich ! One recommendation I have is to overlap the final cat step with basecalling. something like this pseudo code
```
for ... in batch of pod5s:
    cp pod5 batch to /dev/shm
    samtools cat previous_batch &
    cat_pid = $!
    dorado basecall ... > new_batch
    wait $cat_pid
    previous_batch = new_batch
```

since dorado's I/O is only on local disks, it shouldn't interfere with the I/O ops for samtools. but of course you'll want to keep an eye on any CPU usage too to make sure that's not oversubscribed.

**Comment by wilsonte-umich** [comment]
This works for copying in the next batch in the background while one batch is calling. Dorado stays constantly busy except during the first preload, but will tolerate an intermittent IO slowdown by waiting patiently for the next batch to finish copying if it hasn't yet. Thanks for prompting that.

Still not sure how to handle a copy/cat back off the node concurrently. What I want is something like `samtools view -b >> /scratch/out.bam &` but you can't append bam files, and I want to use bam not fastq to maintain the flags.

```sh
cd $POD5_DIR
POD5_FILES=(*.pod5)
POD5_BATCH_SIZE=20

set_batch_copy () {
    BATCH_FILES=${POD5_FILES[@]:COPY_I:POD5_BATCH_SIZE}
    COPY_DIR=/dev/shm/$COPY_I
    mkdir $COPY_DIR   
}
run_dorado () {
    CALL_DIR=/dev/shm/$CALL_I
    dorado basecaller --read-ids $READ_IDS_FILE $ONT_MODEL_DIR $CALL_DIR |
    samtools view -b - > /tmp/$CALL_I.unaligned.bam 
    rm -r $CALL_DIR    
}

COPY_I=0
set_batch_copy
cp $BATCH_FILES $COPY_DIR
CALL_I=$COPY_I
for ((COPY_I=POD5_BATCH_SIZE; COPY_I < ${#POD5_FILES[@]}; COPY_I+=POD5_BATCH_SIZE)); do 
    set_batch_copy
    cp $BATCH_FILES $COPY_DIR &
    COPY_PID=$!
    run_dorado
    wait $COPY_PID
    CALL_I=$COPY_I
done
run_dorado

samtools cat /tmp/*.unaligned.bam > /scratch/$UBAM_FILE
rm /tmp/*.unaligned.bam
```

**Comment by wilsonte-umich** [comment]
To complete the thought, this version uses unaligned.sam.gz, instead of unaligned.bam. By stripping the SAM header, it is possible to append the previous dorado output batch file back to external /scratch concurrently with dorado running the next batch. For safety, I copy in the next batch and copy out the previous batch in series. I imagine this will increase the call file size, but it maximizes utilization of the GPU worker node and minimizes execution time. In testing, dorado takes longer than the file copying, so it runs about as fast the the node resources and external IO allow.

```
cd $POD5_DIR
POD5_FILES=(*.pod5)
POD5_BATCH_SIZE=20

do_batch_copy () {
    if [ "$COPY_IN_I" != "" ]; then
        BATCH_FILES=${POD5_FILES[@]:COPY_IN_I:POD5_BATCH_SIZE}
        COPY_DIR=/dev/shm/$COPY_IN_I
        mkdir $COPY_DIR  
        cp $BATCH_FILES $COPY_DIR
    fi
    if [ "$COPY_OUT_I" != "" ]; then
        CALL_FILE=/tmp/$COPY_OUT_I.unaligned.sam.gz
        cat $CALL_FILE >> /scratch/out.unaligned.sam.gz
        rm $CALL_FILE        
    fi
}
run_dorado () {
    CALL_DIR=/dev/shm/$CALL_I
    dorado basecaller --read-ids $READ_IDS_FILE $ONT_MODEL_DIR $CALL_DIR | 
    samtools view - | # strip header
    pigz -p $N_CPU -c > /tmp/$CALL_I.unaligned.sam.gz
    rm -r $CALL_DIR    
}

COPY_IN_I=0
do_batch_copy
CALL_I=$COPY_IN_I
for ((COPY_IN_I=POD5_BATCH_SIZE; COPY_IN_I < ${#POD5_FILES[@]}; COPY_IN_I+=POD5_BATCH_SIZE)); do 
    do_batch_copy &
    COPY_PID=$!
    run_dorado
    wait $COPY_PID
    COPY_OUT_I=$CALL_I
    CALL_I=$COPY_IN_I
done
COPY_IN_I=""
do_batch_copy &
COPY_PID=$!
run_dorado
wait $COPY_PID
COPY_OUT_I=$CALL_I
do_batch_copy

```

**Comment by tijyojwad** [comment]
Nice!

**Comment by wilsonte-umich** [comment]
Pursuant to the issue above and this one on pod5: <https://github.com/nanoporetech/pod5-file-format/issues/112>

For those looking to get `pod subset` and `dorado duplex` or `dorado basecall` to run efficiently on an HPC cluster node, I've shared [full documentation](https://wilsontelab.github.io/ont-mdi-tools/overview) for standalone open-source scripts that execute optimized batched file transfer and analysis:

- [repack,sh](https://github.com/wilsontelab/ont-mdi-tools/blob/main/shared/modules/repack/repack.sh), i.e., subset by channel
- [basecall.sh](https://github.com/wilsontelab/ont-mdi-tools/blob/main/shared/modules/basecall/basecall.sh), simplex or duplex

In addition to feature optimization from versions above, the two scripts now provide proper support for batched duplex analysis as described in the docs.
