### ISSUE TITLE
How to correspond the raw electrical signal to the basecalling sequence?

### ISSUE THREAD

**Issue by huicongyao** [nanoporetech/dorado#224]
In fast5 basecalling using guppy, we could have a segmentation group, which could correspond raw digital data to the basecalling sequence, how to implement this in Dorado?

**Comment by iiSeymour** [comment]
@huicongyao you need to add `--emit-moves` when basecalling to get sequence to signal segmentation information in the BAM file.

**Comment by huicongyao** [comment]
Thank you for your reply, I added `--emit-moves` during basecalling, and it generates a new column with a bunch of 0 and 1, what do they mean biologically?

**Comment by iiSeymour** [comment]
@huicongyao sorry I though you was asking about aligning each base to it's corresponding signal section _(please ignore my previous response)_.

Storing the basecalled sequence data into fast5 is deprecated in guppy and not something we will add in dorado.

**Comment by huicongyao** [comment]
Our research needs information between raw digital data and the corresponding DNA/RNA sequence, is there any possibility that we could redevelop Dorado to generate this information?

**Comment by hiruna72** [comment]
Hi @huicongyao,

Just saw this thread. I suggest you to try [squigualiser](https://github.com/hiruna72/squigualiser/tree/dev). It is in its early development stage.

**Comment by iiSeymour** [comment]
@hiruna72 see my last comment, I believe @huicongyao is talking about the analysis writing support *(for fastq, ect)* in fast5 that we used to support in guppy.

@huicongyao please see https://github.com/nanoporetech/dorado/blob/master/documentation/SAM.md which describes the basecaller output format. All the information is present in the SAM/BAM for linking each record back to it's corresponding raw signal.
