### ISSUE TITLE
simplex read splitting

### ISSUE THREAD

**Issue by bdrosen** [nanoporetech/dorado#226]
Hi, I'm recalling some r9.4.1 data to recover telomere sequence but I don't see any way to split simplex reads.  Telomere recovery is great, I went from ~0.5Mb of telomeric sequence with guppy to 11.8Mb with dorado.  The problem is that of my ~6M reads, guppy split 400k and dorado split none.  I see that splitting is built into the duplex pipeline, but I don't see any parameters for including it in the simplex command.  Any advice?

Thanks,
Ben

**Comment by vellamike** [comment]
Hi, Dorado does not currently implement read splitting. Would it be possible for you to share a small subset of reads which you believe should be split and I will aim to get this feature rolled out quickly?

**Comment by bdrosen** [comment]
Hey Mike, 
I'm glad I didn't just send you a list of reads that guppy split because it looks like guppy is being way too aggressive in splitting.  I aligned a smaller dataset from another flow cell that I also basecalled with both guppy_v6.5.7 and dorado_v0.3.  Guppy split 15,803 reads, but when I look at the alignment of the unsplit parental reads output by dorado, the vast majority of them (~14,568/15,803) had continuous alignments.  In the file I uploaded, the first 5 columns are extracted from the guppy sequencing_summary.txt file while columns 6-10 are from my alignment summary. readLengthBp is the original read length, and hcReadLengthBp is the length of the alignment.  Each dorado row is duplicated because they are all reads split in guppy. 
 The second dorado read is actually one that looks like guppy was correct to split as you can see the dorado read (59307 bp) only aligns for roughly the length of the larger of the two guppy reads (38958 bp).  Here's a [box folder](https://ars-usda.box.com/s/62joxxcm8ojec6iwpc2xmhauuxxwzslo) with the pod5 files for these reads.
Thanks!
Ben
[PAI08478_dorado.split.map.txt](https://github.com/nanoporetech/dorado/files/11681356/PAI08478_dorado.split.map.txt)

**Comment by vellamike** [comment]
Hi @bdrosen 

Just to update you that simplex read splitting is something we are working on but I can't give you an absolute timeline at the moment.

Given that you are finding guppy is over-agressive and it appears your reads largely do not require splitting (by my calculation 8% of reads are being correctly split by guppy meaning that only 32k from 6M reads should be split in your larger set, or 0.5%), is this a major blocker for you?

Mike

**Comment by bdrosen** [comment]
Hey Mike,

I've been using duplex_tools to split the [non-split duplex reads](https://github.com/nanoporetech/duplex-tools#2b-find-additional-duplex-pairs-in-non-split-reads-optional) which make up the vast majority of unsplit reads as far as I can tell.  It would be nice not to have to do this extra step, but it isn't a huge issue.

**Comment by tijyojwad** [comment]
Hi @bdrosen - we just released dorado [v0.4.0](https://github.com/nanoporetech/dorado/releases/tag/v0.4.0) which now supports simplex read splitting as default.
