### ISSUE TITLE
GPU local computation

### ISSUE THREAD

**Issue by AlineMuyle** [nanoporetech/dorado#230]
Hi,
I was wondering if you have any GPU card recommendation for a desktop linux PC to run dorado? Something less expensive than the server cards V100, but powerful enough to run large datasets.
Thanks in advance for your help.
Best wishes

**Comment by vellamike** [comment]
Hi @AlineMuyle, this very much depends on how much data you intend to base call. [These benchmarking numbers](https://aws.amazon.com/blogs/hpc/benchmarking-the-oxford-nanopore-technologies-basecallers-on-aws/) should help you make a decision/.

Nvidia GeForce GPUs are often used by customers for basecalling, although we do not have published benchmark numbers for these GPUs.

**Comment by Kirk3gaard** [comment]
Hi Aline
We have really good experiences with the RTX4090 for basecalling data from promethion flowcells.
Best regards
Rasmus
