### ISSUE TITLE
duplex basecalling out of memory

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/dorado#231]
Hi

I experienced duplex calling dying due to out of memory after 7 hours on a node with 4xA100 cards.

Really looking forward to the resume mode .... #72 
Basecalling crashing is both really annoying and also a bit expensive.

Best regards
Rasmus

Context 4xA100 cards, dorado v. 0.3 and dataset is ~15 Gbp 5khz MinION data.

[2023-06-08 14:06:28.783] [info] > No duplex pairs file provided, pairing will be performed automatically
[2023-06-08 14:07:50.427] [info] > Starting Stereo Duplex pipeline
[2023-06-08 14:07:50.453] [info] > Reading read channel info
[2023-06-08 14:07:53.303] [info] > Processed read channel info
[██████▋                       ] 22% [07h:22m:58s<01d:01h:28m:08s] terminate called after throwing an instance of 'c10::OutOfMemoryError'
  what():  CUDA out of memory. Tried to allocate 5.86 GiB (GPU 1; 39.43 GiB total capacity; 26.55 GiB already allocated; 4.66 GiB free; 33.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by tijyojwad** [comment]
Hi @Kirk3gaard - were you running with the `--guard-gpus` option? The `master` branch now has code that protects GPU memory better by default without needing that flag, but for `v0.3.0` that flag is useful (more so on GPUs with smaller mem, but _could_ help with bigger GPUs too).

Other users have also reported benefits with setting `PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:4096`. That option may incur some overhead. See [this](https://pytorch.org/docs/stable/notes/cuda.html) page.

Resume feature has been escalated to highest priority for dorado, so stay tuned!

As a temporary workaround, you can use the `--read-ids` to filter the subset of reads to be base called.

**Comment by Kirk3gaard** [comment]
Hi @tijyojwad 
No I forgot that setting might be needed. Will rerun with that setting and see whether it solves the issue. 
Best regards
Rasmus

**Comment by tijyojwad** [comment]
100x doesn't sound right. it should be on the order of 2-3x slower (closer to 2) for the same data/model. Is your data on a local drive? For duplex the read pattern from the pod5 is not simple streaming, so it's more sensitive to I/O latency.

**Comment by Kirk3gaard** [comment]
Nice to know. This was on a ceph cluster with 4xA100 cards. So likely that is causing things to be slower than expected. Will see if there is an option to use a local drive for this in the future.
