### ISSUE TITLE
Fast5 to pod5 - 5khz mode dorado

### ISSUE THREAD

**Issue by gwl2** [nanoporetech/dorado#235]
ONT changed the sampling mode to 5khz recently.

I think I remember that the pod5 format was also developed to be able to save this kind of data. 

By accident the format of the raw reads was changed from pod5 to fast 5 for one of our runs. Now I am not sure, if i convert the fast5 to pod5 afterwards, is the resulting pod5 file real 5khz sampled data, or was it lost/reduced to 4 khz due to the initial fast5 format. I'd need that info to choose the right model in dorado.

Note I'll also post this question on the pod5 github, as I am not sure which site is correct for this issue.

**Comment by tijyojwad** [comment]
The sampling rate is stored in both fast5 and pod5. I believe if you convert the fast5 again (as long as it was sequenced in 5KHz mode), the pod5 should have the right info.

Dorado itself will check for the sample rate before running. So if the pod5 wasn't converted properly, `dorado` will error out.

**Comment by gwl2** [comment]
Thanks, good to know!
