### ISSUE TITLE
5mCG model not found

### ISSUE THREAD

**Issue by achang44** [nanoporetech/dorado#236]
I am attempting to get the modified basecalls from nanopore runs. I converted my fast5 into a pod5 containing all my fast5 data.

This is the code I used. 
`./dorado basecaller dna_r9.4.1_e8_hac@v3.3_5mCG@v0 pod5s/ --modified-bases 5mCG > calls.bam`

Error message
`terminate called after throwing an instance of 'std::runtime_error'
  what():  could not find matching modification model for dna_r9.4.1_e8_hac@v3.3_5mCG@v0`

I am in the directory for dorado and the model is downloaded in the same directory.

**Comment by achang44** [comment]
Update: I have used the file path to specify where the model is located
`./dorado basecaller /mnt/c/Users/qbiol/Desktop/Nanopore/220908_March_pooledB_yellow12hr_DNA/20220908_1410_X1_FAS45639_35e2080f/fast5_pass/dorado-0.3.0-linux-x64/bin/dna_r9.4.1_e8_hac@v3.3_5mCG@v0/ --modified-bases 5mCG > calls.bam`

I am now getting an error message 
`[2023-06-13 21:20:02.115] [error] 1 argument(s) expected. 0 provided.`

Do you still support the r9.4.1 models on doroado?

**Comment by sklages** [comment]
@achang44 - The `models` positional parameter is the actual basecalling model, not the modified-bases model

`dorado basecalling_model data OPT` e.g.

Consider:
```
./dorado basecaller \
  dna_r9.4.1_e8_hac@v3.3 \
  pod5s \
  --modified-bases 5mCG \
  > calls.sam
```
or (mostly unnecessary)..

```
./dorado basecaller \
  dna_r9.4.1_e8_hac@v3.3 \
  pod5s \
  --modified-bases-models path_to_mod-base-model \
  > calls.sam
```

**Comment by sklages** [comment]
I'd recommend that you separate your data from your software installations.

E.g. for your `dorado` installation (or any other software) sth like: `/mnt/c/Users/qbiol/software` and for your data accordingly `/mnt/c/Users/qbiol/ontdata` (or some other path where there is enough diskspace for your ONT data).

That will avoid problems ...
