### ISSUE TITLE
dorado 0.3.0 linux x86 8-core intel cpu 32gb + 4gb swap ram kill

### ISSUE THREAD

**Issue by ahurdmontanaedu** [nanoporetech/dorado#240]
Using configuration above allows dorado to access unlimited ram and kill program. Requesting manual setting for ram and core usage by dorado.
Edit: dorado basecaller specifically

**Comment by vellamike** [comment]
Hi @ahurdmontanaedu,

What is the precise command you are running on this system?

**Comment by anthony-aylward** [comment]
I have had the same issue (excessive RAM usage) with version 0.3.0 on Ubuntu 20.04 (linux-x64).  My command was:

```
dorado basecaller dna_r10.4.1_e8.2_260bps_sup@v4.1.0 pod5/ --modified-bases 5mCG_5hmCG
```
The pod5/ directory contains a single 555GB POD5 file.

Things ran as expected (normal RAM usage) with the same command using version 0.2.4.

**Comment by myxotheles** [comment]
Having same issue with latest version 0.3.1. Running on our cluster, maximum RAM/core I am allowed to use is 11G. For 8 cores this is 88G but this is overrun:

```
[2023-06-27 15:46:04.301] [info] > Creating basecall pipeline
[2023-06-27 16:20:50.595] [info] > Index parameters input by user: kmer size=15 and window size=10.
/opt/sge_spool/8.6.12b/sbg5/job_scripts/2991154: line 27: 196237 Bus error 
```

Is there away to limit dorado's memory requirements?

**Comment by vellamike** [comment]
Closing this issue because Dorado memory management has improved significantly since 0.3.1. Please request to reopen if this is still occurring with the latest version of Dorado (0.5.3).
