### ISSUE TITLE
Dorado compiled by ourselves is slower than Dorado release

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/dorado#243]
Could you provide the exact versions of the compilers and steps that are used at ONT to build the release version of Dorado.
when we compile it by ourselves, the performance is slightly lesser. 

For example for super accuracy basecalling with a few thousand reads:
dorado compiled by us: 11 minutes 33.65 seconds
dorado release: 10 minutes 57.84 seconds

This behaviour is observed when I repeat the run and the time measurements are consistent.

We are using gcc/g++ 9 on Linux.

**Comment by vellamike** [comment]
Hi, what are the exact commands you are using to compile?

**Comment by hasindu2008** [comment]
The commands as shown here:
https://github.com/nanoporetech/dorado#clone-and-build
```
$ cmake -S . -B cmake-build
$ cmake --build cmake-build --config Release -j
```

**Comment by iiSeymour** [comment]
The base image for our Linux x64 builds is `nvidia/cuda:11.8.0-devel-centos7` and we are using `DEVTOOLSET_VERSION=9` also.

What is the reported calling `samples/s` between the release build and yours? The extra wall clock time maybe start up / tear down differences i.e. from CUDNN benchmarking/kernel selection. Dorado has built in [NVTX](https://docs.nvidia.com/nvtx/index.html) profiling so I would start by running both under `nsys profile` and comparing the reports in [Nsight Systems](https://developer.nvidia.com/nsight-systems).
