### ISSUE TITLE
single simplex read used in multiple duplex reads

### ISSUE THREAD

**Issue by cfblaeb** [nanoporetech/dorado#245]
Hi,

I have noticed that simplex reads are occasionally used in multiple duplex reads.
Is there anyway dorado can tell me which duplex read it finds most probable?

**Comment by vellamike** [comment]
Hi @cfblaeb 

This will happen very occasionally as Dorado is unable to establish whether a read is the template of a later read or a complement of an earlier one. This is something we are working to reduce the likelihood of. This should be rather rare - how often do you see this?

You can use the [mean q score tag ](https://github.com/nanoporetech/dorado/blob/master/documentation/SAM.md)(`qs:i`)  to identify which read the basecaller thinks is more likely.
