### ISSUE TITLE
dorado fails to build

### ISSUE THREAD

**Issue by GeorgeNikitinNV** [nanoporetech/dorado#247]
After cloning the repo the command:
`cmake -S . -B cmake-build`

fails while is unable to find hdf5:

```
...
CMake Error at /usr/share/cmake-3.22/Modules/FindHDF5.cmake:1061 (message):
  HDF5 was found, but a different variable was set which contains the
  location of the `hdf5::hdf5` library.
Call Stack (most recent call first):
  cmake/HDF5.cmake:52 (find_package)
  CMakeLists.txt:37 (include)
```

**Comment by vellamike** [comment]
Have you installed libhdf5-dev as per the readme?

**Comment by GeorgeNikitinNV** [comment]
> Have you installed libhdf5-dev as per the readme?

Thank you for pointing this out! It was installed, after reinstall everything seems to work!

**Comment by vellamike** [comment]
Great!!
