### ISSUE TITLE
Dorado performance compared to Guppy

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/dorado#25]
Are there any parameters that could be tuned on Dorado to get equivalent performance on Guppy?  I have been running them on a server with SSD with Tesla V100-16GB GPU and Dorado seems to be 1.5-2.5X slower depending on the model. See the commands I used and the runtimes below:

**FAST model (dorado ~2.5X slower)**
ont-guppy-6.1.1/bin/guppy_basecaller -i fast5/ -s fastq_fast1/ -c dna_r9.4.1_e8.1_fast_prom.cfg -x cuda:0 
time = 19:11.3
dorado basecaller dna_r9.4.1_e8.1_fast@v3.4 fast5/ -b 3000 --emit-fastq -x cuda:0 > dorado_fast.fastq
time = 50:48.4

**HAC model (dorado ~1.5X slower)**
ont-guppy-6.1.1/bin/guppy_basecaller -i fast5/ -s fastq_hac1/ -c dna_r9.4.1_e8.1_hac_prom.cfg  -x cuda:0 
time = 58:28.74
dorado basecaller dna_r9.4.1_e8.1_hac@v3.3 fast5/ -b 800 --emit-fastq -x cuda:0 > dorado_hac.fastq 
time = 1:34:45

**SUP model (dorado ~1.5X slower)**
ont-guppy-6.1.1/bin/guppy_basecaller -i fast5/ -s fastq_sup1/ -c dna_r9.4.1_e8.1_sup.cfg  -x cuda:0 
time = 4:14:03
dorado basecaller dna_r9.4.1_e8.1_sup@v3.3 fast5/ -b 200 --emit-fastq -x cuda:0 > dorado_sup.fastq 
time = 6:00:39

**Comment by hasindu2008** [comment]
Unfortunately, that made the runtime worse - increasing the runners to 2 and halving the batch size to cap memory.

FAST model: 1:08:56
HAC model: 1:47:08
SUP model: 7:36:31

**Comment by vellamike** [comment]
I think the workloads you are using to measure performance are too small.
As a general rule when benchmarking (any application not just in
bioinformatics) you need a workload sufficiently large to make the startup
and shutdown times small.

Could you give some more information about the system you are working on,
full command’s, and your full benchmarking setup? If you could also send
some Nsight Systems traces that would help a lot too.

**Comment by vellamike** [comment]
Yes that should definitely be enough! Are you running the benchmarks with
input files on networked storage?

**Comment by hasindu2008** [comment]
As I have stated in the very first message:  "I have been running them on a server with SSD with Tesla V100-16GB GPU". Actually it is NVME SSD as I have put the spec from smartctl in the second message. The goal was to benchmark the base-calling performance without IO.

**Comment by vellamike** [comment]
Could you provide some Nsight Systems traces for the kernel executions? 

The reason I was wondering about IO is that It's very surprising to me that the 2 runners vs 1  would cause a slowdown in performance. What samples/s performance is Dorado reporting?

**Comment by hasindu2008** [comment]
Could you please tell me the command to collect night systems traces using the commandline? I have done using nvvp in the past which is now deprecated I believe?

**Comment by vellamike** [comment]
That would be `nsys profile <command>` - you probably want to run the profile on a small subset of data (2 minutes worth). It will produce a file with a `qdrep` extension which you then open in Nsight systems. You also may need to [install Nsight Systems](https://developer.nvidia.com/nsight-systems) if it's not on your server already.

Could you let me know what speed Dorado is reporting in terms of MSamples/s?

**Comment by hasindu2008** [comment]
Hey Mike,

DId for a 20,000 reads with 2 num runners using HAC model:
```
dorado basecaller models/dna_r9.4.1_e8.1_hac@v3.3 /data/tmp/sra/NA12878_prom_subsubsample/fast5/PLPN243131/NA12878_SRE/20201027_0537_3A_PAF25452_97d631c6/fast5_pass/  -b 400 --emit-fastq -x cuda:0 --num_runners 2 > a.fastq
> Creating basecall pipeline
> Loaded 20000 reads
> Reads basecalled: 20000
> Samples/s: 8.694753e+06
> Finished
```

Then for the same dataset, the profiling was done and the file is attached.
```
nsys profile /install/dorado/build/bin/dorado basecaller /install/dorado/models/dna_r9.4.1_e8.1_hac@v3.3 /data/tmp/sra/NA12878_prom_subsubsample/fast5/PLPN243131/NA12878_SRE/20201027_0537_3A_PAF25452_97d631c6/fast5_pass/  -b 400 --emit-fastq -x cuda:0 --num_runners 2 > a.fastq
```

https://www.dropbox.com/s/mswp8vl94slq2w1/report1.qdrep.gz?dl=0

**Comment by vellamike** [comment]
Thanks @hasindu2008 - could you confirm which version of Nsight systems you are using to generate the qdrep? I am trying to view the timeline with Nsight Systems 2022.2.1 (Latest version) and seeing the following error:


```
Failed to load report view from: /Users/mikevella/report.qdrep
The report was possibly created with a newer version of NVIDIA Nsight Systems. Please upgrade to the latest version and try again.
```

**Comment by hasindu2008** [comment]
```
nsys  --version
NVIDIA Nsight Systems version 2020.3.4.32-52657a0
```

**Comment by iiSeymour** [comment]
Performance has been significantly increased since July across the board so you should now see dorado on par or better than guppy.
