### ISSUE TITLE
Does dorado accept trained remora models?

### ISSUE THREAD

**Issue by jorisbalc** [nanoporetech/dorado#250]
I have been using the Bonito to run Remora models for data analysis. However, after encountering an issue (referenced in the Remora GitHub repository:  https://github.com/nanoporetech/remora/issues/88). I attempted to export the model in the torchscript for use with Dorado. Unfortunately, it appears that Dorado does not accept the .ts model, as I encountered the following error when providing the model path to the Dorado basecaller command line using the "`--modified-bases-model`" option:
`toml::parse: file open error -> test_model_1.12/config.toml`

My full command line is as follows:
`dorado basecaller --modified-bases-model test_model_1.12 --reference gm119_assembly.fasta /home/v313/Dorado/bin/dna_r10.4.1_e8.2_400bps_sup@v4.2.0/ gm119_mod_reads.pod5 > mod_calls_gm119.bam`

The exported model does not cotain the config.toml. Is it possible for Dorado to somehow accept these models? Would prefer using dorado over bonito, since it's way faster on our machine. Thanks in advance!

**Comment by marcus1487** [comment]
Remora models must be exported with the `remora model export` command. The output directory from this command can be passed directly into Dorado.

I will add this to the Remora README to make this more clear going forward.

**Comment by marcus1487** [comment]
If the remora model export command completed without error the config.toml file should be in the output directory. Could you share the export command run, the result and the contents of the requested output directory?

**Comment by marcus1487** [comment]
Indeed. Bonito pins exact versions of every dependency. Updating your bonito installation should resolve the issue as the current version of Bonito is linked to Remora 2.1.2. 

As a side note, I generally install bonito in a dedicated virtual environment doe to the exact version pinning. You may find this a beneficial practice in your compute environments as well.

**Comment by jorisbalc** [comment]
I'm having some trouble with dorado reading custom remora models. I've trained a remora model on a custom modification and I'm trying to run the model with the following command:
```
v313@v313-GP66-Leopard-11UH:~/working-dir-remora$ dorado basecaller --reference /home/v313/ref-seqs/gm119_ref.fasta --modified-bases-models model_byC_CG/ --batchsize 64 /home/v313/Dorado/bin/dna_r10.4.1_e8.2_400bps_sup@v4.2.0/ mod_pod5s/for_basecalling/ > mod_model_calls.bam
```
It seems like it manages to create the basecalling process and it basecalls the canon bases. However, the terminal is spammed with errors: 
```
[2023-06-20 14:08:02.691] [error] Unknown modified base abbreviation: 5byC
[2023-06-20 14:08:02.691] [error] Unknown modified base abbreviation: 5byC
[2023-06-20 14:08:02.691] [error] Unknown modified base abbreviation: 5byC
[2023-06-20 14:08:02.691] [error] Unknown modified base abbreviation: 5byC
```

5byC being an abbreviation to the custom modification. Am I missing something or is this not yet implemented in dorado?

**Comment by marcus1487** [comment]
This is a combination of limitations in the SAM tag specification and the Remora repository. The strict definition of the modified base tag does not allow arbitrary single letter codes, but only those found in the table in the specification. We are looking into potentially expanding this to allow arbitrary single letter codes from custom Remora models. Additionally we are looking into extending Remora to allow Chebi numeric codes for values which should work in Dorado. 

For now the best hack would be to use one of the available codes in the SAM specification https://samtools.github.io/hts-specs/SAMtags.pdf. For example you could use `f` which is intended for 5fC. We realize that this is not an ideal fix and aim to make this process a smoother moving forward.

**Comment by jorisbalc** [comment]
The only one I managed to get working was `m 5mC`. But it works.

**Comment by marcus1487** [comment]
There was a bug in the modified base specification for 5fC that will be fixed in the next release. Also the next release of Remora will allow specification of modified bases by ChEBI code which should be the preferred method of storage for modified bases without a single letter code going forward.

**Comment by HalfPhoton** [comment]
Closing as resolved
