### ISSUE TITLE
Array out of bounds

### ISSUE THREAD

**Issue by TheSequencingCenter** [nanoporetech/dorado#254]
Hi,

This is our first contribution so we want to follow protocols.

The Cppcheck static code analysis tool (http://cppcheck.net/) found an array out-of-bounds in tensor_utils.cpp, lines 128-129.

/Users/richardcasey/Documents/GitHub/dorado/dorado/utils/tensor_utils.cpp(129): error: Out of bounds access in expression 'counts[i]'
/Users/richardcasey/Documents/GitHub/dorado/dorado/utils/tensor_utils.cpp(129): error: When i==counts.size(), counts[i] is out of bounds.

Here's the code snippet:
for (int i = 0; i <= counts.size(); ++i) {
            if (counts[i] > threshold) {

It should read:
for (int i = 0; i < counts.size(); ++i) {
            if (counts[i] > threshold) {

Out-of-bounds arrays usually lead to unpredictable behavior (i.e. segmentation faults).  

Should we submit a pull request?

**Comment by vellamike** [comment]
Thank you for this! It does indeed appear you have spotted a bug, your help is greatly appreciated. If you would like to add your contribution to Dorado could you submit a pull request please? We do not have a strict protocol in place for external contributors.

**Comment by TheSequencingCenter** [comment]
OK thanks.  We submitted a pull request.  Hopefully we did that right.

**Comment by iiSeymour** [comment]
Thank you for the patch @TheSequencingCenter!
