### ISSUE TITLE
Question about Dorado basecalling output

### ISSUE THREAD

**Issue by huicongyao** [nanoporetech/dorado#258]
Dorado usually takes many multi-pod5 files and outputs a single large sam/bam file, is there any option to output multiple sam/bam files according to their original pod5 files?

**Comment by vellamike** [comment]
This is not supported. Dorado actually outputs to stdout rather than a file. You could easily get the behaviour you seek by running dorado once per group of pod5s you want a bam for though.

**Comment by setshabaTaukobong** [comment]
So just for a bit of clarity on my side, I have about 600 odd pod5 files and I ran dorado which generated on bam file. Is this what is meant to happen or is it suppose to generate many bam files respective to each pod5 file?

**Comment by tijyojwad** [comment]
> Is this what is meant to happen 

yes this is the default behavior

**Comment by setshabaTaukobong** [comment]
@tijyojwad ok, thank you!
