### ISSUE TITLE
dorado basecall

### ISSUE THREAD

**Issue by HITzhongyu** [nanoporetech/dorado#262]
Hi
    I try to use dorado to basecall,  but  when it finished , it report Segmentation fault (core dumped) 
 
`dorado basecaller ~/software/dorado-0.3.0-linux-x64/model/dna_r9.4.1_e8_hac@v3.3/  ./pod5/ -
-emit-moves -x cuda:0,1,2,3 > ./remora/calls.bam`

![image](https://github.com/nanoporetech/dorado/assets/104176070/77f257c2-f733-4915-a9bd-065d5b242c3d)

so  I  want to know whether it  finished?   and is this "Segmentation fault (core dumped)"  an error or can it be ignored?

**Comment by myxotheles** [comment]
HI, I am encountering the same issue (just posted it as a separate issue). Getting segmentation fault after basecalling has finished. Not sure if it means that some of the reads did not base call correctly. Does your BAM file look ok? Because my bam files are truncated because EOF marker missing. Looks like did not write the file correctly.

**Comment by HITzhongyu** [comment]
> 

Hi
    I check the result bam file ,it seems to be correct. But I don't know why it report segmentation fault, and I tried the command again, and this time it ran successfully。

**Comment by iiSeymour** [comment]
@HITzhongyu this has been fixed in c46a2a3558f42831e85efce56765b37be12040b9 in will be in v0.3.1.

**Comment by myxotheles** [comment]
> Hi
> I check the result bam file ,it seems to be correct. But I don't know why it report segmentation fault, and I tried the command again, and this time it ran successfully.

have you checked with samtools quickcheck? I am getting EOF is missing.. but it looks like we are in luck and 0.3.1 will fix the problem. :-)

**Comment by tijyojwad** [comment]
Hi @HITzhongyu - dorado v0.3.1 was just released which fixes the seg fault issue.

https://github.com/nanoporetech/dorado/releases/tag/v0.3.1

**Comment by ejade42** [comment]
I am getting this same issue, where segmentation faults are consistently reported after basecalling and I'm not sure if it is causing errors in the bam output files.

I have been using Dorado v0.9.1 with CUDA v12.6.3, with the dna_r10.4.1_e8.2_400bps_sup@v5.0.0_5mCG_5hmCG@v3 model.

The hardware is a linux-based slurm system on A100 GPUs.
