### ISSUE TITLE
Segmentation fault after 99% basecalled

### ISSUE THREAD

**Issue by myxotheles** [nanoporetech/dorado#263]
Hi, 
I have read the previous posts on segmentation faults. I am getting seg faults at the very end after 99% base called.
The resulting BAM file is truncated and lacks EOF marker. But the file size and reads look ok and I can fix the bamfile with samtools reheader. 

I am analysing cfDNa (short reads).
Generating high number of reads eg 50M reads (because short)
Using dorado 3.0.0
model: dna_r10.4.1_e8.2_260bps_hac@v4.1.0
GPU: Ampere
occurs with modified basecalling, simplex and duplex calling.

Here the last couple of lines from my log:

`[█████████████████████████████▉] 99% [03h:09m:56s<00m:00s] [K

[█████████████████████████████▉] 99% [03h:09m:56s<00m:00s] [K

[█████████████████████████████▉] 99% [03h:09m:56s<00m:00s] [K

[2023-06-24 04:35:40.267] [info] > Reads basecalled: 51172353

[2023-06-24 04:35:40.267] [info] > Basecalled @ Samples/s: 1.957716e+07

/opt/sge_spool/8.6.12b/sbg1/job_scripts/2988002: line 27: 48226 Segmentation fault      ${dorado} basecaller ${model} ${input_dir} --reference ${ref} --modified-bases 5mCG_5hmCG > ${output_dir}/${sample}_.bam

`

PS. Also something wrong with the status bar.. it prints a new bar several times per second so the log files are huge just containing status bars

**Comment by iiSeymour** [comment]
Hello @myxotheles both the segfault and status bar log file issue are solved on master and we are just waiting on one more fix before publishing a release.

**Comment by myxotheles** [comment]
Hi @iiSeymour  that's great to hear! When is 0.3.1 due for release?

**Comment by iiSeymour** [comment]
Now :)

https://github.com/nanoporetech/dorado/releases/tag/v0.3.1
