### ISSUE TITLE
Cannot open aligned BAM

### ISSUE THREAD

**Issue by maximum411** [nanoporetech/dorado#271]
I have a basecalled BAM file from Dorado which I have tried several times to align. While Dorado alignment appears to finish successfully each time, I am unable to inspect or perform any operations on the output BAM file with Samtools. Every Samtools command on the aligned BAM gives this error:

_[E::hts_hopen] Failed to open file post_aligned_v4.bam
[E::hts_open_format] Failed to open file "post_aligned_v4.bam" : Exec format error_

I do not have this same issue with the unaligned input BAM.

Below is the command used to generate the alignment. I have tried alignment with both 0.3.0 and 0.3.1 with both causing the same problem. 

dorado aligner "D:\Human_hg38-rDNA_genome_v1.0\hg38-rDNA_v1.0.fa" "D:\HS_BW_rDNA\no_sample\20230522_1835_MC-113226_FAW93105_b084824b\dorado\unsorted\dorado_calls.bam" -I "8G" > results\post_aligned_v4.bam

**Comment by tijyojwad** [comment]
Hi @maximum411 - 

Is your unaligned BAM generated by the same version of `dorado`? What is your samtools version?

If possible, can you check if running basecalling + alignment together produces a usable file?
```
dorado basecaller <model> <path> --reference ref.fq --max-reads 100 > aligned.bam
```

(the --max-reads options is just to generate a small sample)

**Comment by maximum411** [comment]
Strangely, I am getting an empty BAM as an output when I do this. After getting this with 100 reads I tried up to 10,000 reads but with the same result. This is the command I am using (the working directory has the dorado model folders in it):

dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.2.0 D:\HS_BW_rDNA\no_sample\20230522_1835_MC-113226_FAW93105_b084824b\pod5\ --modified-bases 5mCG_5hmCG --device "cuda:0" -I "6G" --max-reads 10000 --reference "D:\Human_hg38-rDNA_genome_v1.0\hg38-rDNA_v1.0.fa" > D:\HS_BW_rDNA\no_sample\20230522_1835_MC-113226_FAW93105_b084824b\dorado\aligned_all\results\all_aligned_test_3.bam

**Comment by maximum411** [comment]
I seemed to have a problem before with alignment taking up too much memory and crashing, which I solved by limiting the minimap index size. Could this possibly be related to these issues? I just tried it without the -I parameter, and this time it failed to produce any BAM at all.

**Comment by tijyojwad** [comment]
Curious that you get an empty BAM. Do you see the same behavior if you run
```
dorado basecaller <model> <pod5> --max-reads 100 > unaligned.bam
dorado aligner reference.fa unaligned.bam > aligned.bam
```
And can you also try without the `--modified-bases` option?

> I just tried it without the -I parameter, and this time it failed to produce any BAM at all.

What is the difference between an empty BAM and no BAM at all? Does it crash in the latter case?

AFAIK in the minimap2 library (which is what we use to align), the index size bytes is not allocated up front. So if the index is smaller than 16G (default for dorado), it won't still take up 16G of memory. The `I` parameter determines when mm2 will split its index. `dorado` doesn't support split indices, so if we detect that an index has been split then `dorado` will exit.

**Comment by tijyojwad** [comment]
Hi @maximum411 - any update on this?

**Comment by tijyojwad** [comment]
Hi @maximum411 - I'm closing this issue for now. If you are still running into this issue, feel free to re-open this issue.
