### ISSUE TITLE
Modified basecalling for RNA002

### ISSUE THREAD

**Issue by kenneditodd** [nanoporetech/dorado#273]
Hello. I see you have recently added rna002_70bps models for basecalling and are fixing a bug. Will you ever release a model for modified basecalling with the RNA002 kit?

**Comment by kenneditodd** [comment]
> Xpore and m6anet works really well with current basecallers

I'll give m6anet a try. Although, I need more than just m6A modifications. I only have one sample so I cannot use  Xpore.

**Comment by vellamike** [comment]
We have released modified basecalling models for RNA004 (rna004_130bps_sup@v3.0.1) but do not plan to do so for RNA002.
