### ISSUE TITLE
stereo model for duplex call in R9.4.1 data

### ISSUE THREAD

**Issue by Yijun-Tian** [nanoporetech/dorado#275]
Hello,
Is there a duplex model for R9.4.1 data? How to find the information for training the stereo model?
Thanks,

**Comment by iiSeymour** [comment]
Hi @Yijun-Tian no, stereo duplex is R10.4.1 feature only.

**Comment by asan-emirsaleh** [comment]
This is a question of high priority. Many labs produced a huge amount of data on R9 flow cells. One should have an ability to reuse these data with the most recent models and stereo basecalling. Those models might greatly lift in quality the data previously obtained thus improving Nanopore citations.
