### ISSUE TITLE
Modified basecalling

### ISSUE THREAD

**Issue by AjaxWho** [nanoporetech/dorado#277]
Hi Team_ONT, 
Why do you have to provide 2 models for modification basecalling: one canonical (e.g. dna_r10.4.1_e8.2_400bps_sup@v4.2.0 (5kHz)) and the second modified (e.g. dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v2 (5kHz))? Also, is it possible to basecall a 4KHz dataset using a 4KHz canonical and a 5KHz modified base models?
Cheers.

**Comment by tijyojwad** [comment]
Hi @AjaxWho - for a typical use case of modified basecalling, you can ignore the fact that there's a second model. e.g. if you run `dorado basecaller <model> <data> --modified-bases 6mA` then the correct model for 6mA will be picked up automatically.

> is it possible to basecall a 4KHz dataset using a 4KHz canonical and a 5KHz modified base models?

No the version of the models (e.g. 4.2.0) need to match. It's best to let `dorado` find the best match.

**Comment by AjaxWho** [comment]
Gotcha- thanks @tijyojwad
