### ISSUE TITLE
Selecting 5mCG modified basecalling model

### ISSUE THREAD

**Issue by worromot** [nanoporetech/dorado#278]
Hi,

Dorado 0.3.1 (linux binary) works fine when using `--modified-bases 5mCG_5hmCG`. 
I only saw how to run 5mCG in the AWS benchmarking post, so tried  `--modified-bases 5mCG`. This failed with the following message:
```
  terminate called after throwing an instance of 'std::runtime_error'
  what():  could not find matching modification model for dna_r10.4.1_e8.2_400bps_hac@v4.1.0
```
...or, with a different model...
 ` what():  could not find matching modification model for dna_r10.4.1_e8.2_400bps_hac@v3.5.2_5mCG@v2`

What am I missing?

**Comment by arjeffries** [comment]
Get very much the same thing on an R9.4 model with dorado 0.3.1 too.
```
dorado download
dorado basecaller dna_r9.4.1_e8_sup@v3.3_5mCG@v0 10543_15_20kb --modified-bases 5mCG > 5mCG_15kb_20kb.bam
terminate called after throwing an instance of 'std::runtime_error'
  what():  could not find matching modification model for dna_r9.4.1_e8_sup@v3.3_5mCG@v0
Aborted (core dumped)

```

**Comment by sklages** [comment]
@arjeffries @worromot,
> dorado basecaller dna_r9.4.1_e8_sup@v3.3_5mCG@v0 10543_15_20kb --modified-bases 5mCG > 5mCG_15kb_20kb.bam

You are feeding `dorado basecall` with a modified-base model when it expects a standard basecalling model.
`dorado basecaller dna_r9.4.1_e8_sup@v3.3 10543_15_20kb --modified-bases 5mCG > 5mCG_15kb_20kb.bam` would be correct.

**Comment by worromot** [comment]
@sklages -- isn't  `dna_r10.4.1_e8.2_400bps_hac@v4.1.0` a standard model?
The main readme suggests running 
`dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.1.0 pod5s/ --modified-bases 5mCG_5hmCG > calls.bam`
...which runs fine, but not when specifying `--modified-bases 5mCG`

**Comment by sklages** [comment]
@worromot - yes, `dna_r10.4.1_e8.2_400bps_hac@v4.1.0` is a standard model, but `dna_r10.4.1_e8.2_400bps_hac@v3.5.2_5mCG@v2` is not.

Your second error message "with a different model" implies (to me) that `dorado` has been called with a modified-base model rather than a standard basecalling model.

And for `dna_r10.4.1_e8.2_400bps_hac@v4.1.0` basecalling model only the `5mCG_5hmCG` modbase model is available. You probably need to filter afterwards.

**Comment by sklages** [comment]
> @sklages -- thanks for clarification that that only the `5mCG_5hmCG` modbase model is available for `dna_r10.4.1_e8.2_400bps_hac@v4.1.0`. Do you know if there is a way to list what models are available where?

Just run `dorado download --list` to see all available models.

> To clarify the second part: To produce 5mC calls using a model like `dna_r10.4.1_e8.2_400bps_fast@v3.5.2_5mCG@v2`, should it be run without `--modified-bases` switch?

No, to produce `5mC` calls using a model like `dna_r10.4.1_e8.2_400bps_fast@v3.5.2_5mCG@v2`, you should run `dorado` with the basecalling model `dna_r10.4.1_e8.2_400bps_fast@v3.5.2` and specify the modification via `--modified-bases 5mCG`, which in turn should find the matching modification model `dna_r10.4.1_e8.2_400bps_fast@v3.5.2_5mCG@v2`.

**Comment by worromot** [comment]
@sklages -- thanks! The following was not obvious to me from reading the docs:
> ... to produce `5mC` calls using a model like `dna_r10.4.1_e8.2_400bps_fast@v3.5.2_5mCG@v2`, you should run `dorado` with the basecalling model `dna_r10.4.1_e8.2_400bps_fast@v3.5.2` and specify the modification via `--modified-bases 5mCG`, which in turn should find the matching modification model `dna_r10.4.1_e8.2_400bps_fast@v3.5.2_5mCG@v2`.

It might make sense to spell it out in the readme that the modified models cannot be called directly.

**Comment by sklages** [comment]
> It might make sense to spell it out in the readme that the modified models cannot be called directly.

In fact, they can: `--modified-bases-models /path/to/modbase-model` (omitting `--modified-bases`)

**Comment by worromot** [comment]
@sklages - thanks! This is helpful and would be great to include in readme
> In fact, they can: `--modified-bases-models /path/to/modbase-model` (omitting `--modified-bases`)

what's the overall syntax:
`dorado basecaller <main-model> --modified-bases-models </path/to/modbase-model> <input>` ?

**Comment by sklages** [comment]
well, have a look at `dorado basecaller --help`.

I basically run `dorado` like so:
```
BASECALLING_MODEL="dna_r10.4.1_e8.2_400bps_sup@v4.1.0"

 dorado basecaller \
   $BASECALLING_MODEL \
   $POD5_DATA_DIR \
   --modified-bases 5mCG_5hmCG \
   --device cuda:all \
   --verbose \
   --batchsize $batch_size \
   --recursive \
   | samtools view --threads 4 --bam --with-header \
   > $BAM_OUT
```

- `batchsize` is either 0 (let dorado find "best" batchsize, which is often a bit too low) or I set this manually (slightly higher to better use VRAM on e.g. 20G Nvidia A100 partitions (MIG).
- usually there is no need to specify `--modified-bases-models` when using standard/provided modification models. 

But its call is pretty similar to the previous one:
```
BASECALLING_MODEL="dna_r10.4.1_e8.2_400bps_sup@v4.1.0"
MODBASES_MODEL="dna_r10.4.1_e8.2_400bps_sup@v4.1.0_5mCG_5hmCG@v2"

 dorado basecaller \
   $BASECALLING_MODEL \
   $POD5_DATA_DIR \
   --modified-bases-models /path/to/$MODBASES_MODEL \
   --device cuda:all \
   --verbose \
   --batchsize $batch_size \
   --recursive \
   | samtools view --threads 4 --bam --with-header \
   > $BAM_OUT
```

**Comment by iiSeymour** [comment]
@sklages why samtools view?

**Comment by worromot** [comment]
@sklages -- Thanks for sharing this tidbit on mutual exclusivity of `--modified-bases-models` and `--modified-bases`. After re-reading `dorado basecaller --help`, I can't find this level of detail there.  Might be worth documenting it somewhere, though probably it would be too much for --help.

```
$ dorado basecaller --help
Usage: dorado [-h] ... [--modified-bases VAR...] [--modified-bases-models VAR] [--modified-bases-threshold VAR] ... model data
...
  --modified-bases              [nargs: 1 or more]
  --modified-bases-models       a comma separated list of modified base models [default: ""]
...
```
By the way, looks like the syntax in `Usage:` is incorrect/out of date? Dorado version 0.3.1 errors out with model and data listed after options.

**Comment by sklages** [comment]
> @sklages why samtools view?

@iiSeymour - thanks for pointing this out. No idea why I pasted this line .. :-) 
It does no harm but it does not bring any benefit at all as `dorado` writes BAM. 
My `dorado` runs are without `samtools` .. I edited the comment accordingly.

**Comment by worromot** [comment]
Thanks for clarifications!
