### ISSUE TITLE
Specifying as basecalling input one pod5 file, not a directory?

### ISSUE THREAD

**Issue by worromot** [nanoporetech/dorado#280]
More of a feature request than a bug.

Currently (dorado v.0.3.1) the input for basecalling is specified as a directory of pod5/fasta5 files. Attempting to point to a file errors out:
    [error] filesystem error: directory iterator cannot open directory: Not a directory [name.pod5]
One use case for single file would be to start basecalling as pod5 files appear in the directory. Another (at least as a temporary fix) would be to get around out of memory issue for modified basecalling. It is, of course, possible to create a temp directory with one/few files, but that is an ugly way to deal with this.

**Comment by vellamike** [comment]
Thanks for the suggestion. This is a reasonable request. We plan to deprecate FAST5 and will likely add this as part of that change.

**Comment by iiSeymour** [comment]
Hey @worromot

@vellamike added this in https://github.com/nanoporetech/dorado/commit/2f69da6f659442e0b3caebbb94dfc9e84432e6d3 which is part of dorado v0.4.0
