### ISSUE TITLE
Feature Request: Download Progress Indicator

### ISSUE THREAD

**Issue by mattloose** [nanoporetech/dorado#281]
When downloading models dorado gives no indication of progress.

On a slow network connection users can confuse no progress indicator with nothing happening.

**Comment by iiSeymour** [comment]
@mattloose this bug snuck in v0.3.1 and is fixed on master a5818b55cabb56de3d7832b341a849f099ac3008.

**Comment by mattloose** [comment]
Great - I seemed to remember it working before!
