### ISSUE TITLE
Dorado base-calling on a Rocky Linux server with 4 x A100

### ISSUE THREAD

**Issue by homeveg** [nanoporetech/dorado#285]
I am trying to run a Dorado base-calling on a Rocky Linux server with 4 x A100 with 80GB graphic memory per card, 64-core CPU and 256GB RAM.
As an input, I have about 220Gb of pod5 files, generated with the latest MinKNOW software from the MinION run. 
I was using first the dorado-0.3.0, and later dorado-0.3.1.
In both cases, the problem is very similar: When the base-calling has started, it shows ET about 2h:30m for v.0.3.0 and 2h10m for v.0.3.1 and after some time, the ET was already >1day for a v.0.3.0 and >6h for v.0.3.1.

The v.0.3.1 finished 9% within 13 minutes (currently running) and shows 02h:08m estimated run time, but then the ET starts to grow rapidly. After 25 min of run time, it shows still 9% and about 3h 35m. After 30 min - 10% progress and 4h35m ET
Update: It's still running, 17h run time, and 2d21h estimated run time...

I was trying to run it with fully automated settings, and using slightly customized values for "batchsize", "chunksize" and "overlap", which results in a ~5-7% decrease of ET in the beginning, compared to an auto mode.
With the optimized settings, I have about 44% of GPU memory usage, not more than 10% of CPU usage with some small peaks, and system RAM usage below 5%. 
The GPU in the initialisation phase, is not very stable, always jumping from 2-3% to 20-25%, after 7-8% of a progress - the GPU usage increases to 40-50% with some 100% spikes. And this is a point, when the ET start increasing.

Here is my command: 
`dorado basecaller --verbose --batchsize 3100 --chunksize 12000 --overlap 750 --device "cuda:all" --min-qscore 10 --recursive --emit-fastq $ConfPath/dna_r10.4.1_e8.2_400bps_hac@v4.2.0 $WD/$Project/$FCID/ > $WD/$Project/$FCID/fastq_dorado/$Project.hac.fastq`

Below is the nvidia-smi:
```
Wed Jun 28 16:03:55 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe           On | 00000000:17:00.0 Off |                    0 |
| N/A   49C    P0               71W / 300W|  36165MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe           On | 00000000:31:00.0 Off |                    0 |
| N/A   54C    P0              309W / 300W|  36165MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100 80GB PCIe           On | 00000000:B1:00.0 Off |                    0 |
| N/A   48C    P0              104W / 300W|  36165MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100 80GB PCIe           On | 00000000:CA:00.0 Off |                    0 |
| N/A   49C    P0               71W / 300W|  36165MiB / 81920MiB |      4%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   2688830      C   dorado                                    36160MiB |
|    1   N/A  N/A   2688830      C   dorado                                    36160MiB |
|    2   N/A  N/A   2688830      C   dorado                                    36160MiB |
|    3   N/A  N/A   2688830      C   dorado                                    36160MiB |
+---------------------------------------------------------------------------------------+
```

_Originally posted by @homeveg in https://github.com/nanoporetech/dorado/issues/252#issuecomment-1611480345_

**Comment by homeveg** [comment]
I found a way around it, but this is something you can probably implement directly.

1) I've split the whole dataset (which is about 221G) into 10 chunks, about 20G each.  
2) Copied 20G of data to the ramdisk (~30-40 seconds)
3) executed Dorado for the chunk of data (~ 2m45 seconds)
4) deleted data from the temporary location
5) Repeat 10 times...
6) join resulting fastq files

As a result, each chunk was processed within 4 minutes!
CPU utilisation was around 10%, GPU utilisation - 99-100% (!!!) GPU memory - 65% 
For this test I just used the default Dorado settings for a batchsize, chunksize and overlap

<img width="749" alt="image" src="https://github.com/nanoporetech/dorado/assets/13424939/aadeaed6-156e-4840-97a6-602f9767f262">

**Comment by homeveg** [comment]
small update: with the trick I described above (moving a ~22G of data to the RAM disk), the SUP model on the same dataset performed as well extremely well - about 11 minutes for a base calling per 22.5G of data. 
<img width="468" alt="image" src="https://github.com/nanoporetech/dorado/assets/13424939/5b27fe22-d242-42a3-b425-3095c6e27048">

I think, on modern workstations, with 32G or more RAM, it's as well a very good solution, especially taking into account, that the Dorado itself doesn't use too much memory.

**Comment by tijyojwad** [comment]
Hi @homeveg - thanks so much for posting the details of your experiment! This will be very useful for future users. Also glad to see you were able to recover performance!

Based on the above, it looks to me like your bottleneck was I/O. Once you moved to ramdisk, read speed from the pod5s got much faster and the GPU was not starved of data, hence achieving 100% utilization.

**Comment by Psy-Fer** [comment]
out of curiosity, what kind of disk system was the original pod5 data being read from?

**Comment by maximum411** [comment]
> small update: with the trick I described above (moving a ~22G of data to the RAM disk), the SUP model on the same dataset performed as well extremely well - about 11 minutes for a base calling per 22.5G of data. <img alt="image" width="468" src="https://user-images.githubusercontent.com/13424939/251455549-5b27fe22-d242-42a3-b425-3095c6e27048.png">
> 
> I think, on modern workstations, with 32G or more RAM, it's as well a very good solution, especially taking into account, that the Dorado itself doesn't use too much memory.

That is an impressive result! I'd like to try this myself. 

Would you mind sharing the code you used to copy pod5 data into RAM?

**Comment by homeveg** [comment]
> Hi @homeveg - thanks so much for posting the details of your experiment! This will be very useful for future users. Also glad to see you were able to recover performance!
> 
> Based on the above, it looks to me like your bottleneck was I/O. Once you moved to ramdisk, read speed from the pod5s got much faster and the GPU was not starved of data, hence achieving 100% utilization.

You're right, that was the very first thing I thought of too.

**Comment by homeveg** [comment]
> out of curiosity, what kind of disk system was the original pod5 data being read from?

We have a shared XFS filesystem, which use a 10Gb network. But I was checking both, the network bandwidth utilisation and file server performance, and everything was far away from the cap. So it might be the way file server processes the multiple simultaneous read/write requests, that makes it's much slower with the time

**Comment by homeveg** [comment]
> > small update: with the trick I described above (moving a ~22G of data to the RAM disk), the SUP model on the same dataset performed as well extremely well - about 11 minutes for a base calling per 22.5G of data. <img alt="image" width="468" src="https://user-images.githubusercontent.com/13424939/251455549-5b27fe22-d242-42a3-b425-3095c6e27048.png">
> > I think, on modern workstations, with 32G or more RAM, it's as well a very good solution, especially taking into account, that the Dorado itself doesn't use too much memory.
> 
> That is an impressive result! I'd like to try this myself.
> 
> Would you mind sharing the code you used to copy pod5 data into RAM?

sure. 
It's of cause optimised for my purposes, with some hard-coded features, so you might need to change it, but I was trying to make it more or less flexible.  I've attached my code:
[Dorado_basecalling_sh.txt](https://github.com/nanoporetech/dorado/files/11979251/Dorado_basecalling_sh.txt)
