### ISSUE TITLE
How do I get Q20 reads with dorado?

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#288]
ONT is advertising that we are now at the Q20 era but it seems to me I can't really replicate the claim.

I downloaded HG002 R10.4.1 LSK114 5kHz data from S3 via the link at the EPI2ME data release page:
https://labs.epi2me.io/giab-2023.05/

Then I run the wf-human-variation-1.6.1 pipeline (modified to pull dorado-0.3.1 image instead of 0.3.0) and align to the HG002v0.7 assembly I downloaded from
https://github.com/marbl/HG002
It was run on a 4xA100 SXM 80GB box.

./nextflow run wf-human-variation-1.6.1 -w HG002/workspace -profile singularity --mapula --fast5_dir hg002/ --ref ~/genome/HG002v0.7.fa --bed ~/genome/HG002v0.7.bed --basecaller_cfg 'dna_r10.4.1_e8.2_400bps_hac@v4.2.0' --remora_cfg 'dna_r10.4.1_e8.2_400bps_hac@v4.2.0_5mCG_5hmCG@v2' --sample_name HG002 --out_dir HG002 --dorado_ext pod5

Then I run samtools stats on HG002.pass.cram. I am getting an error rate of 2.23%. 
This is only Q16.5 for pass reads. 

SN      raw total sequences:    16627327        # excluding supplementary and secondary reads
SN      filtered sequences:     0
SN      sequences:      16627327
SN      is sorted:      1
SN      1st fragments:  16627327
SN      last fragments: 0
SN      reads mapped:   16572805
SN      reads mapped and paired:        0       # paired-end technology bit set + both mates mapped
SN      reads unmapped: 54522
SN      reads properly paired:  0       # proper-pair bit set
SN      reads paired:   0       # paired-end technology bit set
SN      reads duplicated:       0       # PCR or optical duplicate bit set
SN      reads MQ0:      4571365 # mapped and MQ=0
SN      reads QC failed:        0
SN      non-primary alignments: 20816384
SN      supplementary alignments:       2105927
SN      total length:   278889969539    # ignores clipping
SN      total first fragment length:    278889969539    # ignores clipping
SN      total last fragment length:     0       # ignores clipping
SN      bases mapped:   278852560908    # ignores clipping
SN      bases mapped (cigar):   277821287851    # more accurate
SN      bases trimmed:  0
SN      bases duplicated:       0
SN      mismatches:     6200301200      # from NM fields
SN      error rate:     2.231759e-02    # mismatches / bases mapped (cigar)
SN      average length: 16772
SN      average first fragment length:  16773
SN      average last fragment length:   0
SN      maximum length: 1317210
SN      maximum first fragment length:  1317210
SN      maximum last fragment length:   0
SN      average quality:        32.4
SN      insert size average:    0.0
SN      insert size standard deviation: 0.0
SN      inward oriented pairs:  0
SN      outward oriented pairs: 0
SN      pairs with other orientation:   0
SN      pairs on different chromosomes: 0
SN      percentage of properly paired reads (%):        0.0

By the way, the basecaller_chunk_size is 25 by default for the nextflow pipeline, ie each dorado will take 25 pod5 files. For this dataset, that means dorado will be run 192 times. I heard that increasing it can improve accuracy but what value should I set? What other parameters can I set to improve base accuracy?

How can I tune the parameters of dorado such that I can reduce the error rate to 1% such that I can get true Q20 reads? Or is there actually another way to measure base quality other than aligning to HG002 assembly?

**Comment by ymcki** [comment]
I changed the model to super accuracy model and increased basecaller_chunk_size from 25 to 50. 

./nextflow run wf-human-variation-1.6.1 -w HG002/workspace -profile singularity --mapula --fast5_dir hg002/ --ref ~/genome/HG002v0.7.fa --bed ~/genome/HG002v0.7.bed --basecaller_cfg 'dna_r10.4.1_e8.2_400bps_sup@v4.2.0' --remora_cfg 'dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v2' --sample_name HG002 --out_dir HG002 --dorado_ext pod5 --basecaller_chunk_size 50

SN      raw total sequences:    16947934        # excluding supplementary and secondary reads
SN      filtered sequences:     0
SN      sequences:      16947934
SN      is sorted:      1
SN      1st fragments:  16947934
SN      last fragments: 0
SN      reads mapped:   16895275
SN      reads mapped and paired:        0       # paired-end technology bit set + both mates mapped
SN      reads unmapped: 52659
SN      reads properly paired:  0       # proper-pair bit set
SN      reads paired:   0       # paired-end technology bit set
SN      reads duplicated:       0       # PCR or optical duplicate bit set
SN      reads MQ0:      4643564 # mapped and MQ=0
SN      reads QC failed:        0
SN      non-primary alignments: 21181403
SN      supplementary alignments:       2113877
SN      total length:   283671932453    # ignores clipping
SN      total first fragment length:    283671932453    # ignores clipping
SN      total last fragment length:     0       # ignores clipping
SN      bases mapped:   283634946887    # ignores clipping
SN      bases mapped (cigar):   282605367116    # more accurate
SN      bases trimmed:  0
SN      bases duplicated:       0
SN      mismatches:     4103726028      # from NM fields
SN      error rate:     1.452105e-02    # mismatches / bases mapped (cigar)
SN      average length: 16737
SN      average first fragment length:  16738
SN      average last fragment length:   0
SN      maximum length: 1323773
SN      maximum first fragment length:  1323773
SN      maximum last fragment length:   0
SN      average quality:        35.8
SN      insert size average:    0.0
SN      insert size standard deviation: 0.0
SN      inward oriented pairs:  0
SN      outward oriented pairs: 0
SN      pairs with other orientation:   0
SN      pairs on different chromosomes: 0
SN      percentage of properly paired reads (%):        0.0

Run time for just basecalling increased from 7h0m to 23h37m.

Now I am getting 1.452105% error rate for pass reads which is Q18.38. This is quite good but still fall short of Q20. Perhaps further increasing chunk size will work?

**Comment by ymcki** [comment]
I noticed that the actual claim is "median raw read accuracy of Q20+"
https://store.nanoporetech.com/ligation-sequencing-kit-v14.html

The nextflow pipeline has a readstats.tsv.gz file of the super accuracy run that calculates a number called acc which is the (1.0 - error rate) of a read.

Then I calculate the median acc from the readstats.tsv.gz file and got 99.216%. This is Q21.057 which satisfy the "median raw read accuracy" being Q20+ claim.

For the normal accuracy run, median acc is 98.532% which is Q18.333.

Anyway, I will also try to tune the parameters and see if I can get better read quality.

**Comment by tijyojwad** [comment]
Yes Q20 is for median read accuracy.

I believe there's also a graph produced as part of the workflow which will show the accuracy stats.
