### ISSUE TITLE
Duplex detection channel and endpoint tolerance

### ISSUE THREAD

**Issue by wilsonte-umich** [nanoporetech/dorado#289]
As I understand how `dorado duplex` works, it (in order):
1. performs simplex basecalling
2. identifies complementary read pairs
3. rebasecalls duplex pairs using the stereo model, collapsing them to a single output read with dx flag set to 1
4. [aligns to the reference genome, only if requested]

Correct? If so, then pair matching is based on called bases only? 

Is the nanopore channel used to restrict duplex pair matching?  It would make sense since a true pair must have been sequenced in the same channel, I think (my examination of simplex calls after alignment confirms this is true).

Then, with base-only read matching, how should we understand the tolerance for imperfect matching at the read ends, which is imperfect for at least two reasons:
1. base calling errors that make the position of the adapter-insert sequence transition ambiguous
2. events that lead to premature termination of a read on one strand, e.g., a strand break on one strand 

I'm just trying to fully understand how dorado manages the sensitivity/specificity of duplex pair matching to understand whether downstream code might still have to identify residual still-separated pairs with redundant information.

Said differently,  what criteria must be fulfilled in dorado to match a duplex pair?

Apologies if this was answered elsewhere but I did not find it.

FWIW I would favor maximizing sensitivity in duplex matching.

**Comment by wilsonte-umich** [comment]
Addendum: I could also imagine that pair matching could be done by a black box trained model, but I've inferred that it is a more mundane heuristic...

**Comment by vellamike** [comment]
Hi @wilsonte-umich  - sorry for taking so long to reply to this, it slipped the net.

> Is the nanopore channel used to restrict duplex pair matching
Yes. exactly right.

The pairing algorithm is robust to issues at read ends and early termination of complement reads. The duplex pairing algorithm is broadly as you describe it. The algorithm is implemented [here](https://github.com/nanoporetech/dorado/blob/master/dorado/read_pipeline/PairingNode.cpp).

> FWIW I would favor maximizing sensitivity in duplex matching.
release 0.4.0 of Dorado does increase the sensitivity.  We actually achieve quite high sensitivity and specificity for duplex pairing, so at the moment we're not real considering increasing the sensitivity further as it would hit the FPR.

**Comment by wilsonte-umich** [comment]
Thanks very much.  It helps us planning our pipelines.  Hopefully these descriptions will help others as well.
