### ISSUE TITLE
Dorado only basecalls 4000 reads?

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/dorado#293]
Hello,

I have a 296GB FAST5 file from a previous Nanopore run (R9). I am using dorado to call modified bases by doing `./dorado/bin/dorado basecaller dorado_models/dna_r9.4.1_e8_sup@v3.3 fast5_folder --modified-bases 5mCG  -x "cpu" > fast5_folder/calls.bam` where `fast5_folder` contains only one 296GB `.fast5` file. 

The resulting `calls.bam` file is 13MB and dorado output says it called 4000 reads. 

Why is dorado only calling 4000 reads? This happens when I convert the `fast5` file to `pod5` and then try to basecall the `pod5` file using the same method.

**Comment by vellamike** [comment]
Hi @Ge0rges  - this sounds like an issue with the FAST5 rather than Dorado. Could you try installing the latest version of the pod5 Python tool using `pip install pod5` and then use `pod5 view input.pod5` to check how many reads are in your input POD5?

**Comment by Ge0rges** [comment]
`pod5 view` on the converted fast5 file using `pod5 convert fast5 -o file.pod5 -t 20 input.fast5` gives a TSV with 4001 lines, corresponding to 4000 reads. During the conversion the progress bar shows 4000 reads as well. However the resulting pod5 is 107MB where the original fast5 is 296GB.

**Comment by HalfPhoton** [comment]
@Ge0rges, 
This report is showing us that your fast5 file only has 4000 reads and 0 unusual records. 

This indicates that `pod5` and `dorado` are doing all the work they can and that it's more likely an issue with your file.

Do you know how this file was created? 

Kind regards,
Rich

**Comment by Ge0rges** [comment]
I don't know the precise history of the file. Thank you for your help, I will investigate on my end.

**Comment by Ge0rges** [comment]
@HalfPhoton I can't seem to get clear answers on the history of this file. I think it might be a concatenated fast5 from one or multiple runs. Do you have a suggestion on tools that could help me understand the contents of this file?

**Comment by HalfPhoton** [comment]
@Ge0rges , 

[HDFView](https://www.hdfgroup.org/downloads/hdfview) might be able to help, but seeing as both `H5py` and the hdf5 reader in `dorado` cannot open more than 4000 records in your file I'm not sure how helpful that might be. 

If the file was formed by concatenation of multiple fast5 files, a solution would be to search for the HDF header "magic bytes" defined in the [specification](https://docs.hdfgroup.org/hdf5/develop/_f_m_t3.html#FileMetaData)  and split the file into parts.

```
Decimal: | 137 | 72 | 68 | 70 | 13 | 10 | 26 | 10
Hexadecimal: | 89 | 48 | 44 | 46 | 0d | 0a | 1a | 0a
ASCII C Notation: | \211 | H | D | F | \r | \n | \032 | \n
```

**Comment by ssscj** [comment]
Hi, I met the same problem. Have you found the solution? Thanks.
