### ISSUE TITLE
Correlation between basecalled error rate and actual error rate is only 0.254

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#294]
As a follow up to me trying dorado 0.3.1 on ONT's latest HG002 data:
https://github.com/nanoporetech/dorado/issues/288

I wanted to know how well the basecalled read quality correlates with acc in readstats.tsv.gz after I convert both of them into error rates.

zcat HG002.readstats.tsv.gz|awk '$1!="name"{OFS="\t";print exp(-$14*log(10.0)/10.0)/exp(1.0),(100.0-$NF)/100.0}'|gzip -c > HG002.err.gz

Then I use R to calculate the correlation

> t = read.table(gzfile("HG002.err.gz"))
> cor(t$V1,t$V2)
[1] 0.2549262

0.2549262 seems quite low to me. Is there any plan to improve it??? I think higher correlation is important as pipelines rely on it to filter out fail reads.

**Comment by ymcki** [comment]
For example, ONT's wf-human-variation pipeline will filter out read quality < 10 as fail such that no more downstream processing.

zcat HG002.err.gz|wc -l
16947934
zcat HG002.err.gz|awk '$1>0.1&&$2<=0.1'|wc -l
912903
zcat HG002.err.gz|awk '$1<=0.1&&$2>0.1'|wc -l
51444

In the perfect world, we can save 912903/16947934 = 5.39% reads that are mis-filtered due to poor quality prediction. 
On the other hand 51444/16947934 = 0.3% reads that should be filtered are not filtered.

**Comment by vellamike** [comment]
Hi @ymcki could you could share a plot of estimated Q scores vs true Q scores?

**Comment by vellamike** [comment]
Hi @ymcki - I will close this issue for now because there isn't enough information here to help diagnose it. I suspect your calculation for correlation between predicted and true accuracy is incorrect in some way, but I can't be sure without more information.
