### ISSUE TITLE
Sample rate for data and model don't match 

### ISSUE THREAD

**Issue by dubravkapezic-LG** [nanoporetech/dorado#296]
Hi, 
I am getting an error while trying to use 0.3.1. version of Dorado to basecall some data:

_'_Sample rate for model (4000) and data (5000) don't match'_

How can I get over this please? 
I have re-downloaded the models and tried several different ones (the data was sequenced with the 260bp/sup setting on a 10.4.1 flowcell). 

Thank you!
Dubravka

**Comment by tijyojwad** [comment]
Hi @dubravkapezic-LG - can you post the tracking id and context tags from the minknow run info?

**Comment by dubravkapezic-LG** [comment]
Hi -
thank you for replying -- I don't know where to get this information from...? 
I don't find it in the run report.
Any help appreciated.

**Comment by jorj1988** [comment]
Hi @dubravkapezic-LG ,

The run report itself would be useful if youre willing to share with us? You can upload to the box link here: https://nanoporetech.ent.box.com/f/7c4375e2b71b48258ebed29f198b89ab

To query the info from a pod5 file, you can use the pod5 python library, and use a command like:

```
> pod5 inspect debug <pod5 file here>
```

The command will output a summary of read data in the file, and the various run info data in the file.

Thanks,
- George

**Comment by ymcki** [comment]
Check the minKNOW version of your pod5 data by

pod5 inspect debug pod5_pass/FAU41813_pass_e6a4b621_0.pod5 | grep distribution_version
 'distribution_version': '23.04.5'

If it is below 23.x, then it is 4kHz data.

**Comment by dubravkapezic-LG** [comment]
Here is the info you requested @jorj1988 , thank you for that command:

**Comment by vellamike** [comment]
Hi,

According to this data, this model was run with 400bps not 260bps:

```
sample_frequency': '5000', 'selected_speed_bases_per_second': '400',
```

Perhaps you are mistaken about 260bps/sup setting being chosen? 


You would be able to run one of these models:

```
dna_r10.4.1_e8.2_400bps_fast@v4.2.0
dna_r10.4.1_e8.2_400bps_hac@v4.2.0
dna_r10.4.1_e8.2_400bps_sup@v4.2.0
```

**Comment by dubravkapezic-LG** [comment]
Thank you @vellamike that worked! 
I think the default is now the 400bps speed so I must have just left it. 
Appreciate the help,
Dubravka
