### ISSUE TITLE
Massive memory spikes when using cpu device

### ISSUE THREAD

**Issue by lmulroney** [nanoporetech/dorado#299]
Hi ONT Dorado Dev Team,

I was trying to do some simple testing with basecalling just 1000 direct RNA reads in the new pod5 format, but I was getting some massive memory spikes. I know Dorado is optimized for GPUs, but do you have any ideas what may be causing this?

Command
dorado basecaller -k 14 --device cpu -r --reference gencode.v36.transcripts.fa --emit-moves rna002_70bps_hac@v3 pod5/ > pod5_basecalled.bam

LSF reports
CPU time :                                     483.49 sec.
Max Memory :                                95333 MB
Average Memory :                         37045.34 MB
Total Requested Memory :           80000.00 MB
Delta Memory :                              -15333.00 MB
Max Swap :                                    -
Max Processes :                            6
Max Threads :                                9371
Run time :                                       195 sec.
Turnaround time :                          197 sec.

CPU time :                                       1345.00 sec.
Max Memory :                                 215328 MB
Average Memory :                          55289.67 MB
Total Requested Memory :            100000.00 MB
Delta Memory :                               -115328.00 MB
Max Swap :                                     -
Max Processes :                             5
Max Threads :                                9364
Run time :                                       60 sec.
Turnaround time :                          62 sec.

Thanks,
Logan

**Comment by tijyojwad** [comment]
Hi @lmulroney - which version of dorado are you using? In dorado 0.3.2 (release end of last week) we've fixed quite a few issues which previously could lead to memory spikes.

**Comment by lmulroney** [comment]
Hi @tijyojwad,

dorado --version
0.3.2+d8660a3

**Comment by tijyojwad** [comment]
Hi @lmulroney - apologies for the late response.

Dorado depends heavily on libtorch APIs and memory management, so my guess is some of those spikes are coming from the inference subroutine. The rest of the basecalling pipeline should not really have spiky memory utilization.

**Comment by tijyojwad** [comment]
Closing now due to inactivity and because dorado is primarily optimized for GPU basecalling. Running large scale analysis on CPU will be quite slow. One additional thing to try would be to run without alignment since that can help reduce memory footprint too.
