### ISSUE TITLE
duplex mode can't resume 

### ISSUE THREAD

**Issue by LucasCRK** [nanoporetech/dorado#300]
Hi,

Is there a technical reason for duplex mode not having the --resume_from option? 

Thank you

**Comment by vellamike** [comment]
Hi, yes, resuming a duplex run is technically more complex and we  haven't added this feature yet. What is the reason your work would benefit from resume in Duplex?

**Comment by LucasCRK** [comment]
Hi thank you for your quick response.

I'm basecalling by submitting a job to a lsf cluster. I ran into a memory limit issue that terminated my job. Being able to resume_from  with a duplex run would therefore save a lot of time

**Comment by vellamike** [comment]
In your situation if you are running jobs on a cluster and want some resilience I think the best thing to do would be to split a dataset of pod5 files into per-channel pod5s and run more than one job.

Firstly install POD5:

```
pip install pod5==0.2.0
```

Then run `[pod5 view](https://pod5-file-format.readthedocs.io/en/latest/docs/tools.html#pod5-view)` to generate a table containing information to split on specifically, the "channel" information.

```
pod5 view /path/to/your/dataset/ --include "read_id, channel" --output summary.tsv
```

This will create "summary.tsv" which should look like:

```
read_id channel
0000173c-bf67-44e7-9a9c-1ad0bc728e74    109
002fde30-9e23-4125-9eae-d112c18a81a7    463
...
```

now run `[pod subset](https://pod5-file-format.readthedocs.io/en/latest/docs/tools.html#pod5-subset)` to copy records from your source data into outputs per-channel. This might take some time depending on the size of your dataset

```
pod5 subset /path/to/your/dataset/ --summary summary.tsv --columns channel --output split_by_channel
```

The command above will create the output directory `split_by_channel` and write into it one pod5 file per unique channel.

Once you have this you can execute multiple jobs against smaller subsets of POD5 (e.g one job per 100 channels). This will generate multiple BAMs which you can merge. You will need to write the appropriate script for this depending on what job scheduler you are using.

Let me know if this helps.

**Comment by LucasCRK** [comment]
Thank you for this tip. This helped tremendously

**Comment by TristanLefebure** [comment]
Hi, 
I arrived here with the same issue as Lucas: I am hitting the wall clock while dupex basecalling a big run on a cluster. 

I like Mike's solution but, given that with a good run we sometime end up with a 1.2Tb pod5 folder, before going this way, I was wondering why splitting by channels? Is that to be sure we don't miss some duplex reads split in two different files, or some basecaller needs? A faster solution would be to group/move pod5 files by sets of say 500 pod5 files without having to rewrite everything. 

I am also always a little worried about re-configuring the raw data (here the pod5): what should I keep afterward (I would probably delete all the per channel pod5 and temporary bam folders)? 

Even if that's much less subtle, with many super large runs, a solution that involves less data manipulation and rewriting, but relies on the `--resume_from` option when we hit the wall-clock might still be preferable... What do you think ?

Best

**Comment by tijyojwad** [comment]
> I was wondering why splitting by channels? Is that to be sure we don't miss some duplex reads split in two different files, or some basecaller needs?

duplex reads are guaranteed to come from the same channel, but reads from the same channel can be split across multiple pod5s (without a time ordering guarantee). So simply grouping by pod5 can result in many missed duplex pairs.

> what should I keep afterward

The data before and after the pod5 transformation is the same. So if you plan on running duplex again, I would suggest keeping the channel-grouped pod5s around

We have discussed adding support for resume in duplex, but it hasn't become a priority yet. I'll add this request to our internal feature planning discussion.

**Comment by schmart95** [comment]
I would also be very interested in a `--resume-from` and a demultiplexing function like `--kit-name` or `--sample-sheet` for duplex mode.
