### ISSUE TITLE
Is there any parameter or planned development to support the direct identification of barcode sequences in RNA sequencing data?

### ISSUE THREAD

**Issue by shizhuoxing** [nanoporetech/dorado#303]
Hi,

Thank for providing this excellent tool for processing direct RNA sequencing data.
We are currently working on the development of pooled-sample direct RNA sequencing, but we have encountered a major issue with barcode sequence identification. We would like to see if we can seek help and support here.

We modified the RTA sequence of ONT direct RNA sequencing by adding a segment of RNA barcode, OligoA in Bold in the figure below:

OligoA: AAGAAGUGUCGGUCUGUGTAGTAGTTC

The extracted RNA samples were then ligated with RTA and RMX to build the library, and MinION sequencing was performed to obtain a total of 89,310 throughput reads.
Then we wanted to be able to match the barcode OligoA sequence from the read sequences to test whether directRNA sequencing can accurately identify RNA barcodes, and we did two basecalling parameters separately as follows.

(1), guppy_basecaller -i . /fast5_pass/ -s . /fast5_pass_recall/ -c . /ont-guppy_6.4.2/data/rna_r9.4.1_70bps_hac_prom.cfg --device cuda: all. Resulting 13,547 reads were able to match the upper barcode OligoA sequence.

(2), guppy_basecaller -i . /fast5_pass/ -s . /fast5_pass_recall/ -c . /ont-guppy_6.4.2/data/rna_r9.4.1_70bps_hac_prom.cfg --device cuda:all --trim_strategy none. Resulting  34,436 reads to compare with the upper barcode OligoA sequence.

It appears that most of the reads in the first guppy basecalling was lost OligoA sequences, but after adding the "--trim_strategy none" parameter to the guppy basecalling, the number of OligoA sequences detected in the reads increased significantly, but compared to the total of 89,310 pass reads, the ratio is still too low!

We would like to inquire if Dorado has any plans to develop a parameter that can output OligoA sequences for facilitating subsequent barcode demultiplexing?

Or how can we detect the missing OligoA sequences?

Thanks.

**Comment by tijyojwad** [comment]
Hi @shizhuoxing  - questions around guppy barcoding and adapter trimming would be better addressed in the ONT community portal. At a high level we suspect that the default adapter trimming strategy was removing some raw signal associate with your OligoA sequence, and not using any adapter trimming helped the situation a bit. The community portal should be able to help you out more.

Another thing you can try is running basecalling using `dorado` and then using guppy barcoder to demux.

**Comment by tijyojwad** [comment]
Hi @shizhuoxing - not sure if this post is still relevant to your work, but as of dorado v0.5.0 there is improved handling of RNA adapter trimming. I would suggest basecalling your dataset through dorado to see if you can recover more of your data. Best to use v0.5.3 for your evaluation which was just released.

**Comment by shizhuoxing** [comment]
Hi @tijyojwad - Thank you for your assistance! We still work on this project and have implemented your suggestions. We reprocessed our data using dorado v0.5.3, incorporating the '--no-trim' parameter. However, the results indicate that only about 25,000 reads can detect the OligoA sequence (compared to 34,436 reads with guppy). It seems that the latest version of dorado does not show significant improvement in performance.
