### ISSUE TITLE
GPU benchmarks?

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/dorado#306]
We're looking to get a new server and are interested in GPU recommendations for Dorado. Do newer architectures (eg. Ada/Hopper) make a big anticipated difference in performance?

We have the choice between slightly older GPUs like the A100 40GB or the Ada L40 48GB which now have approximately the same pricing. They seem to have their individual strengths with respect to FP32/FP64, and the A100 looks like it has much higher memory bandwidth. What does ONT recommend?

Also, does Dorado play well with other processes on the same GPU? If not, then would it make more sense to more slightly slower GPUs as opposed to a single powerful one? Especially when performing basecalling on multiple runs in parallel...

**Comment by iiSeymour** [comment]
Hey @billytcl you might find the following a good start https://aws.amazon.com/blogs/hpc/benchmarking-the-oxford-nanopore-technologies-basecallers-on-aws/

We haven't yet benchmarked an Ada L40 _(@EpiSlim do you have numbers on this card?)_ but our Hopper support right now isn't fully optimised and is something that will be improving over future releases.

Dorado expects to have full use of the GPU and the AWS article above covers vertical vs horizontal scaling.

**Comment by EpiSlim** [comment]
At the moment, A100 cards are still a better option than the Ada cards (incl. L40). On the HAC model, the basecalling speed of the L40 is approx. half of the A100. However, I still think the performance gap can be significantly narrowed if the optimised kernels for the A100/H100 were to be adapted to the L40. 

As @iiSeymour mentioned, Hopper is still WIP.

**Comment by billytcl** [comment]
When you're talking about the A100, are we referring to the A100 80GB? Does
this still hold for the lite A100 40GB PCIe? The reason why I ask is
because the 40GB is substantially cheaper, but will be a generation behind
L40.

**Comment by EpiSlim** [comment]
Hi, I was primarily referring to the 40GB version of the A100. 
FYI, despite launching later, the L40 chip is still `sm89` while the A100 is `sm80`. It is only with Hopper `sm90` that we moved to the subsequent generation.

**Comment by shenker** [comment]
Are L40/L40S optimizations planned in the (nearish) future?

I recently reached out to my institution's HPC administrators to see if my lab could purchase some A100's, but received word that A100's were recently discontinued and Dell (our vendor) can no longer purchase them for us. As you know, H100's are extremely expensive right now and seem likely to remain so, leaving L40S's as perhaps the only cost-effective option remaining. But it's hard to make that determination without a sense for how an L40-optimized dorado might perform. Any advice?

**Comment by billytcl** [comment]
L40S hardware benchmarks also seem to be faster than A100, with a somewhat
slower memory bandwidth.

**Comment by vellamike** [comment]
We haven't done any optimisations specifically for L40, but Dorado is good at getting the most out of GPUs and I expect  performance will be reasonably good for the hardware. 

L40 peak fp16 performance is around 60% that of A100 and INT8 quantisation will not be used. My rough prediction is that L40 will be 0.5x the speed of A100.

**Comment by shenker** [comment]
@billytcl Mind pointing me at the L40S hardware benchmarks you're looking at?

**Comment by billytcl** [comment]
Here's the Nvidia detailed hardware specs: https://resources.nvidia.com/en-us-l40s/nvidia-l40s-product and https://www.nvidia.com/en-us/data-center/l40s/ -- here it shows the theoretical FP16 performance as ~760 TFLOPs and ~1500 INT8 TFLOPS, which is higher than A100 80GB in almost all aspects save for the memory bandwidth. Have to look around to see in the wild benchmarks for L40S but I think you get the idea. I believed it's marketed to be the "baby" version of H100 and replacement for the A100 card.

**Comment by ahcm** [comment]
Just because this bug report turns up as top hit for "dorado gpu benchmark":
2 * A10  24GB: 55489,77s user 4728,98s system 559% cpu 2:59:15,91 total
1 * A30  24GB: 62300,13s user 2394,37s system 381% cpu 4:42:22,72 total
1 * V100 32GB: 54662,32s user 3237,22s system 397% cpu 4:02:52,82 total

**Comment by tijyojwad** [comment]
Hi @ahcm - thanks for posting! Do you have the `samples/sec` number output by dorado at the end? Can you also share details of your dataset for these benchmarks (how many reads, N50 of reads, whether data was on local disk or network drive)?

**Comment by ahcm** [comment]
Dear @tijyojwad,

I just wanted to give a rough ballpark, this is far from a real benchmark.
I wouldn't want to get into the rabbit hole of a real benchmark.

But I can offer to run benchmark sets or data you provide, if they run maybe less than an hour. 

Data was on SSD ZFS raidz[12]. I doubt that I/O is a limiting factor in most cases, since the data is maybe 1TB and processing for a few days. So for processing a harddisk based system or network filesystem will be ok. Also consider you might have to copy the data to the SSDs in the first place.

Best
Andreas

**Comment by ahcm** [comment]
Since this still turns up first for me in search, thanks to Rasmus Kirkegaard and contributors, we now have:
https://github.com/Kirk3gaard/2025-Crowdsource-GPU-basecalling-stats
