### ISSUE TITLE
Progress bar not showing after upgrading to 0.3.1 or 0.3.2 from 0.3.0

### ISSUE THREAD

**Issue by ywang285** [nanoporetech/dorado#307]
Hi, I found that after upgrading dorado to 0.3.1 or 0.3.2 from 0.3.0 version, the progress bar disappeared from the output file (.err file) when I use slurm base server. I can see the progress bar when I run dorado on a local PC. Is there a way to make the progress bar output to the .out or .err file from the slurm base server? Thanks!

**Comment by iiSeymour** [comment]
@ywang285 this was an intentional change as the progress bar uses terminal control characters for interactive sessions and was never intended for file based logging.

**Comment by GeorgeNikitinNV** [comment]
@ywang285 have fixed this in #310. Just add `-p` parameter to display progress bar as before.

**Comment by ywang285** [comment]
> 

I will try #310. Thank you so much!
