### ISSUE TITLE
Jupyter notebook progress bar

### ISSUE THREAD

**Issue by palakpsheth** [nanoporetech/dorado#308]
Using `dorado`, after v0.3.0, the progress bar when duplex basecalling in an interactive jupyter notebook no longer appears. I understand that there was an intentional change made. Any recommendations on how to get the progress bar back when calling `dorado` commands via `subprocess` call in python?

thank you!

**Comment by GeorgeNikitinNV** [comment]
Had the same problem, fixed in #310.

**Comment by palakpsheth** [comment]
@GeorgeNikitinNV thanks for the fix but looks like the ONT team didnt merge? any feedback there?

**Comment by palakpsheth** [comment]
@iiSeymour Thanks for the python tip! In my experience, a command line flag to control the progress bar visibility would be most robust. Off by default seems fair to me for user experience consistency with previous release.

Appreciate all the hard work!
