### ISSUE TITLE
docker image available?

### ISSUE THREAD

**Issue by vdejager** [nanoporetech/dorado#31]
I'm still experiencing issues compiling dorado on our HPC. I'm wondering if there is a Docker or Singularity image available with the latest builds? We can run those images on our GPU nodes.

target: Intel + Nvidia A100

**Comment by vellamike** [comment]
Hi @vdejager  - we are now providing binary releases - see under [the installation section of the readme](https://github.com/nanoporetech/dorado#installation). Perhaps you could try this? We currently have no plans to provide containers and are focusing on providing easy-to-use binaries.

**Comment by vdejager** [comment]
thanks. How often will you build the executables?

**Comment by vellamike** [comment]
Going forward we will build an executable with every release, a release being a collection of functional improvements to performance, usability, feature set etc. We don't yet have a fixed release cycle but expect this will be very roughly on an "every few months" basis.

**Comment by cjw85** [comment]
A docker image is now available at: https://hub.docker.com/r/nanoporetech/dorado

We will have native singularity images shortly.
