### ISSUE TITLE
Nvidia A100 vs H100

### ISSUE THREAD

**Issue by paulmenzel** [nanoporetech/dorado#311]
Please close this issue, if it’s off topic.

https://github.com/nanoporetech/dorado/blob/0598965a56c9ca1c6db856d17ee508edf71ec8de/README.md?plain=1#L27-L39

Could somebody please share experience of the performance difference between an Nvidia A100 and H100 (long reads)?

**Comment by vellamike** [comment]
Our internal benchmarking indicates that H100 provides a speedup of 1.2x to 1.5x depending on the model used. We are currently working on further H100-specific optimisations which will be released in future versions of Dorado.

**Comment by sklages** [comment]
@vellamike - given the significant price difference between A100 and H100, it is probably not yet worth considering to purchase H100 (for dorado basecalling).

>.. 1.2x to 1.5x depending on the model used

Are you referring to the basecalling model or the A100 model (40G/80G) used?

**Comment by tijyojwad** [comment]
> Are you referring to the basecalling model or the A100 model (40G/80G) used?

The basecalling model

**Comment by sklages** [comment]
@tijyojwad - And which of the models benefits most from the modern hardware?

**Comment by peradastra** [comment]
> Our internal benchmarking indicates that H100 provides a speedup of 1.2x to 1.5x depending on the model used. We are currently working on further H100-specific optimisations which will be released in future versions of Dorado.

Is this benchmarking still valid? Deciding on which Nvidia GPU to purchase and the 1.2-1.5x doesn't immediately justify the price of the H100. Any advice would be greatly appreciated!
