### ISSUE TITLE
Is it possible to basecall R10.4 Kit 12 data?

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#313]
Want to basecall this HG002 dataset.
https://labs.epi2me.io/gm24385_q20_2021.10/

But I found that none of the dorado images contains models for R10.4 flowcell and E8.1 enzyme.
https://hub.docker.com/r/nanoporetech/dorado/tags

So is it possible to basecall this dataset with dorado? Or Guppy is the only choice?

**Comment by cjw85** [comment]
The dataset hosted in the S3 location contains already basecalls using an appropriate basecaller model.

The sequencing kit used for that dataset is now deprecated. An up-to-date dataset can be found at: https://labs.epi2me.io/giab-2023.05/
