### ISSUE TITLE
question about GPUDecoder

### ISSUE THREAD

**Issue by zwshan** [nanoporetech/dorado#314]
<img width="820" alt="image" src="https://github.com/nanoporetech/dorado/assets/62176674/e453ea37-ec74-4e20-8fcd-bf7e3dbe0b46">
Hello , I want to export Dorado to some AI chips.

Could you please tell me the functionalities of the following functions?
I've used CPUDecoder as a reference, but I couldn't map the functionalities of these four functions to the CPUDecoder code implementation. If you could briefly explain the functionalities of these functions, I will implement them myself and eventually contribute the code to you.

host_back_guide_step
host_beam_search_step
host_compute_posts_step
host_run_decode？

**Comment by tijyojwad** [comment]
Hi @zwshan - thanks for posting and for your interest in exporting dorado to other chips. It would be better if we chat about this. Could you reach out to me at first name dot last name at nanoporetech.com ?

**Comment by zwshan** [comment]
I have send an email to oyjit.Daw@nanoporetech.com. I am not sure if the email address I sent to is correct, but it is already midnight in my region, and I should go to sleep. See you tomorrow morning.

**Comment by zwshan** [comment]
my email: shanzhw@mail2.sysu.edu.cn

**Comment by tijyojwad** [comment]
Closing to follow up offline.
