### ISSUE TITLE
output metadata

### ISSUE THREAD

**Issue by ziphra** [nanoporetech/dorado#32]
Hello, 

I would like some insights on the sam output metadata to perform quality checks on the basecalled data, and I am not sure I am guessing all of them right.

Also, what would you recommend to filter out bad reads? 

Thank you, 

ziphra

**Comment by ziphra** [comment]
Also, I believe this command `dorado basecaller dna_r10.4.1_e8.2_260bps_hac@v3.5.2 pod5s/ | samtools view -Sh > calls.bam` in the README will output a sam file, and that `-b` would allow bam outputs.

**Comment by iiSeymour** [comment]
Hi @ziphra 

The the SAM specification is documented [here]( https://github.com/nanoporetech/bonito/blob/master/documentation/SAM.md), let me know if want any further clarification.

> and that -b would allow bam outputs.

Thanks, you are correct and this needs updating.
