### ISSUE TITLE
question about dorado parameters

### ISSUE THREAD

**Issue by zwshan** [nanoporetech/dorado#321]
Could you please tell me the meaning of chunk size？

Could you please tell me the difference between  chunk size and batch size?

And I can't find the meaning of chunk size in document and internet, thank you!

**Comment by zwshan** [comment]
Based on my reading of the code, I infer that chunksize * num_chunk = signal length.
Is that right?

**Comment by zwshan** [comment]
chunksize * num_chunk = signal length * batch size?

**Comment by tijyojwad** [comment]
The raw signal from the sequencer is split into chunks of a specific size. This is the contiguous segment of the signal that the model runs inference on. After all chunks in a read are base called, they are stitched together to generate the final read.

Batch size is the number of chunks that are inferred on in parallel to get the most utilization out of the GPU/compute unit. Chunks in a batch can be considered independent of each other.

**Comment by zwshan** [comment]
thank you, I got it.
