### ISSUE TITLE
Issue with Windows version of dorado

### ISSUE THREAD

**Issue by awjga** [nanoporetech/dorado#323]
Hi, 

I have encountered a bug while using the Windows version of dorado.
It seems that the output of the SAM file has a binary tag.
Only after running, cat -v  "output.sam" | sed  's/\^@//g' | sed  's/\^M//g' > "corrected.sam"
And correcting the first line of the file, I can then run samtools on my file.

The steps that I have done that encountered the issue:
After running and saving my output in a bam file:
dorado duplex

And running samtools view:
[E::hts_hopen] Failed to open file file.bam
[E::hts_open_format] Failed to open file " file.bam" : Exec format error
samtools view: failed to open " file.bam" for reading: Exec format error

**Comment by tijyojwad** [comment]
Hi @awjga - thanks for reporting!

Are you generating the bam on windows and then running analysis on a linux system? I've had this issue once before and running `dos2linux` on the generated file from windows before using it on Linux addressed the problem. Can you check if that's the case for you? If so, we can look at what could be done to make that more seamless

**Comment by samuelmontgomery** [comment]
Hi - I am having a similar issue with the windows version of dorado when running `dorado summary`

`Failed to open file "~\barcode1_SUP.bam" : Exec format error`
When using --emit-fastq, the file seems to still be written as a .bam file as well as told by guppy_barcoder
`[guppy/warning] common::FastQIterable::increment: Plus sign not found, so setting END flag.
 ' does not start with '@'. Continuing with next read.itle ' ■@ 6 4 3 2 b f 9 5 - a 9 0 2 - 4 5 e b - b 3 d 4 - 7 b 9 a 4 7 3 3 5 2 a 0`

**Comment by tijyojwad** [comment]
Hi @samuelmontgomery - can you post the command line you used to generate fastq? and can you `cat` the first few lines of the generated file and post it here?

**Comment by J-McNamara** [comment]
@awjga I see your note on how to salvage the SAM file from dorado. I get the same issue that you describe with bam output from dorado in windows. Did you find a way to analyze the bam output in Ubuntu?

**Comment by awjga** [comment]
Hi @J-McNamara ,

Sadly no, as I did not spend much time in looking into at the bam file.  I had reran the dorado and set the output to be in SAM file format.

**Comment by tijyojwad** [comment]
Hi @awjga - thanks for trying out `dos2unix`. I think for now generating `sam` and then running `dos2unix` on that is probably the best way to go.
