### ISSUE TITLE
indexing problem output file

### ISSUE THREAD

**Issue by Qvdauwer** [nanoporetech/dorado#325]
Dear Dorado team,

I was trying to run Dorado for methylation calling of some bacterial sequences

but when trying to use the bam files produce by it was impossible to index them using samtools.

So I looked at the log files and there seems to be an error: 
line 20: 19703 Segmentation fault      (core dumped)

full log file:
[dorado_bc_20_30_08_output.txt](https://github.com/nanoporetech/dorado/files/12289568/dorado_bc_20_30_08_output.txt)

This issue seems similar to issue #88 
But I don't know what to do about it

for information here is the full command:
````
#!/bin/bash

#SBATCH -q gpu
#SBATCH --time=06:00:00
#SBATCH --gpus-per-node=1
#SBATCH --mem=200G
#SBATCH --ntasks-per-gpu=8
#SBATCH --partition=ampere_gpu
#SBATCH --job-name=dorado_test
#SBATCH --output=dorado_bc_20_30_08.out

module load dorado/0.3.0-foss-2022a-CUDA-11.7.0

dorado basecaller $VSC_SCRATCH_VO_USER/Dorado/new_model/dna_r9.4.1_e8_sup@v3.6 $VSC_SCRATCH_VO_USER/pod5_files/bc20_Isolates_30_08/ --device "cuda:0" --reference $VSC_SCRATCH_VO_USER/assemblies/Isolates_30_08/barcode20/assembly_flye/assembly.fasta --modified-bases-models $VSC_SCRATCH_VO_USER/Dorado/new_model/dna_r9.4.1_e8_sup@v3.3_5mCG@v0 --verbose > $VSC_SCRATCH_VO_USER/Dorado/aligned_modified_reads_bc20_Isolates_30_08_new_model_v3.bam
````

Since I saw it could also be an issue related to the original pod5 file, here is a copy of the pod5 file used as input:

[all_reads_bc21_Isolates_30_08_pod5.txt](https://github.com/nanoporetech/dorado/files/12290532/all_reads_bc21_Isolates_30_08_pod5.txt)

the pod5 version I used to create the files is 0.2.2

It is ran on a ampere (a100) gpu

when running the exact same job without a reference, it ran without a problem, however indexing that file produces a bam.bai file containing 16 bytes.

Best regards,
Quentin

**Comment by sklages** [comment]
first I'd try with latest (stable) version, `0.3.2` (cuda_11.8) .. there have been fixed quite some issues. `0.3.4` will be out soon (probably), ... for another try :-)

**Comment by sklages** [comment]
@Qvdauwer - has `v0.3.4` solved your issue?

**Comment by selmapichot** [comment]
I am having a similar issue. I used the Dorado to basecall the modified bases. My job finished without an error, but when I tried to use in Modkit the .bam file generated by Dorado, it throws me this error : 

Error! unable to open SAM/BAM/CRAM index for /rds/project/methylated_tumour_pak76302.bam; please create an index

I used the samtools index but the bam.bai output was only 16 B 

I tried the simplex basecalling of WGS pod5 using two different reference genome files, but the .bam I get are missing any sort of indexing.
Any help on this issue will be greatly appreciated.

**Comment by tijyojwad** [comment]
Hi @selmapichot - is the BAM output from dorado being sorted before indexing?

**Comment by selmapichot** [comment]
Hi, 
Yes, they have been sorted with samtools.

**Comment by tijyojwad** [comment]
do you see any reads in the BAM file that's output by dorado? can you run the following on dorado's output?

```
$ samtools quickcheck -u output.bam
$ echo $?
$ samtools view -c output.bam
```

**Comment by tijyojwad** [comment]
Hi @Qvdauwer - closing as I haven't heard back from you. Please re-open if you have any follow up questions.
