### ISSUE TITLE
Q: Read splitting enabled in simplex | Omit duplex-forming simplex reads from duplex-basecalled BAM

### ISSUE THREAD

**Issue by sklages** [nanoporetech/dorado#327]
Have these issues been addressed in `0.3.3`? I loosely refer to #316 and [#209](https://github.com/nanoporetech/dorado/issues/209#issuecomment-1661103100).

**Comment by tijyojwad** [comment]
Read splitting in simplex is not yet addressed.

For duplex, we have expanded the `dx` tag - 
* `dx:i:1` for duplex reads.
* `dx:i:0` for simplex reads which don't have duplex offsprings.
* `dx:i:-1` for simplex reads which have duplex offsprings.

We forgot to push this update to the README, but will do that soon with the fix for duplex CUDA OOM.

**Comment by nextgenusfs** [comment]
Thanks @tijyojwad was just about to ask what `dx:i:-1` means.  So one could then do the following to filter duplex + simplex (non redundant)?
```
$ samtools view --tag dx:1 --tag dx:0 duplex.bam
```

**Comment by vellamike** [comment]
> Thanks @tijyojwad was just about to ask what `dx:i:-1` means. So one could then do the following to filter duplex + simplex (non redundant)?
> 
> ```
> $ samtools view --tag dx:1 --tag dx:0 duplex.bam
> ```

Yes, that's correct.

**Comment by sklages** [comment]
So for now, `dorado duplex` is the way to go .. higher qualities for a bunch of reads and read splitting is applied .. 👍 :-)

**Comment by mattloose** [comment]
If we imagine two reads that form duplex, but the second read is only the last 50% of the original molecule... 

From this there are presumably three possible results. A simplex only fragment from the first 50% of the molecule (presumably classed as dx:0), a duplex fragment of the last 50% of the molecule (presumably dx:1) and then two simplex reads that have duplex offspring (each 50% of the molecule length and presumably dx:-1).

Is that a correct interpretation?

**Comment by sklages** [comment]
with 50% difference  in length I'd would not expect a duplex read to be formed at all. There is probably a threshold for the maximum length difference for two simplex reads potentially forming a duplex read.

**Comment by mattloose** [comment]
My understanding is that this is one of the features this newer version of dorado was bringing?

**Comment by sklages** [comment]
okay, I see. In `0.3.3` .. "truncated reads". So there must be a threshold for what is "truncated".

**Comment by mattloose** [comment]
I don't know that - but anecdotally I saw some fairly low values when calling in 0.3.4 with verbose mode on!

**Comment by sklages** [comment]
well, interesting .. :-) 
@tijyojwad @vellamike -- can you provide some details on how duplex calling is working? Especially when dealing with truncated complement reads?

**Comment by tijyojwad** [comment]
@mattloose for your example in our current implementation we will only output 3 reads - 

1. The simplex reads of the original molecules with `dx:-1` (one for full molecule and one for the 50% complement)
2. The duplex read covering the overlapping 50% with `dx:1`
there will be no `dx:0` read (so effectively you will lose the 50% of simplex molecule that didn't participate in duplex if filtering based on dx tags)

@sklages we now do support truncated complement pairing. The threshold consists of several conditions, but in terms of length the truncated complement read needs to be at least 20% of the template.

**Comment by sklages** [comment]
thanks for the explanation @tijyojwad 

A small dilema though, if I am not completely mistaken: 
If you keep the original simplex reads as `dx:-1` along with the duplex read `dx:1` the redundant sequence 
portion of the longer simplex read creates kind of "fake coverage" (_increase_). 

OTOH, as you have pointed out, upon dx-filtering you will loose the portion of the simplex read not participating in duplex creation. In this case you _decrease_ coverage and even worse, you remove "sequence length" (as the duplex portion is truncated to 50% in the example).
 
That may or may not be a "real" problem ... Just a thought, probably not quite finished...

**Comment by nextgenusfs** [comment]
Seems important @sklages, probably the "proper" output would be:

1. duplex read
2. a single simplex read containing the additional non-duplex sequence

Probably that information isn't currently stored anywhere and you'd need to align the "parental" simplex reads to the duplex to know where to trim/truncate?

**Comment by sklages** [comment]
> 1. duplex read
> 2. a single simplex read containing the additional non-duplex sequence

and maybe
3. some kind of "positional" information (tag) that (1)+(2) belong together. The actual molecule length is len(1.)+len(2.)..

> 
> Probably that information isn't currently stored anywhere and you'd need to align the "parental" simplex reads to the duplex to know where to trim/truncate?

Shouldn't that information be available during duplex formation? 

But as I wrote, just a thought, probably not quite finished. Maybe there is some good reason to not do so ... :-)

**Comment by sklages** [comment]
@tijyojwad - any thoughts/corrections are appreciated:
```
T: template read
C: complement read
P: position

  <non overlapping >
P 1                  500                1000
T =======================================  dx:-1
                     <------ dx:1 ------>
C                    ====================  dx:-1
```

Currently I get in the output BAM file:
- (1) simplex "T" (`dx:-1`)
- (2) simplex "C" (`dx:-1`)
- (3) duplex (`dx:1`)

Overlapping fraction of "T"(1) and complete "C"(2) introduce (fake) redundancy.
Upon filtering on `dx:-1` I completely loose "T" and "C", including "non overlapping" sequence. Also the actual molecule is truncated in duplex-only data. 

So in one case there is too much data, in the other case we got missing data. IMHO is does not matter, how much data it is, it is just not “correct” .. the workaround mentioned (read name parsing, sequence length, alignment) is not really convenient.

A simple thought: additionally to the global duplex/simplex read classification (`dx:0,1,-1`), wouldn't it be feasible to keep the complete sequence of "T" and introduce some local classification tag `dxr`, which describes a region in the given read classified as "duplex" (`dx:1`)?

So taking the above example:

```
P 1                  500                1000
T =======================================  dx:-1
  <------ dx:0 -----><------ dx:1 ------>
C                    ====================  dx:-1
```
- "T" would get `dx:1` (at least partially duplex) and something like `dxr:500-1000` (region) or `dxs:500`(start) + `dxe:1000`(end)
- qualities in "dxr"/"dxs-dxe" region are increased due to duplex formation
- both simplex reads participating in duplex formation are removed from final dataset or (optionally) written to BAM with `dx:-1`
- dataset containing only `dx:0` and `dx:1` is complete and non-redundant

Is there something I completely missed? Any thoughts?

**Comment by tijyojwad** [comment]
HI @sklages - thanks for the inputs!

> "T" would get dx:1 (at least partially duplex) and something like dxr:500-1000 (region) or dxs:500(start) + dxe:1000(end) ... qualities in "dxr"/"dxs-dxe" region are increased due to duplex formation

Duplex could actually change the bases, not just the quality scores. So we'd want to keep both the original simplex parent reads _and_ the duplex reads or there will be loss of information. That's why we have the `dx:-1` tag (i.e. `dx:-1` + `dx:0` are all the original simplex reads).

We'll take this region tagging into advisement for the future though. e.g. Going off your suggestion, one possibility is adding a `dxr` type tag just to the simplex parent (those in `dx:-1` category) to mark which part of the read was involved in duplex. And keeping everything else the same. That way all the information is retained for downstream analysis.

**Comment by nextgenusfs** [comment]
The `dxr` tag seems useful, than would allow for easy trimming/processing of the simplex parents without need for post-processing alignment of simplex parents to the duplex child. 

Shouldn't the goal of base calling be to create the best possible sequence of each molecule?  So I think the idea of creating a single read for a single molecule is the most relevant, use the duplex region when possible and resort to the simplex on the ends.  Perhaps a cli option could be to write/rescue the simplex parents if anybody wanted that.  The "partial" duplex reads are somewhat problematic for experiments like amplicons, ie you could imagine you really want to use duplex higher quality reads but if the ends are not recovered you won't find your primers and will have to discard those reads.  A "stitched" together simplex/duplex/simplex would yield a result that would have higher quality in the middle (duplex region) but yet maintain the original molecule sequence.

I realize can probably do this downstream, e.g alignment of the simplex parents with duplex child, but as @sklages this isn't very convenient.

**Comment by sklages** [comment]
> > "T" would get dx:1 (at least partially duplex) and something like dxr:500-1000 (region) or dxs:500(start) + dxe:1000(end) ... qualities in "dxr"/"dxs-dxe" region are increased due to duplex formation
> 
> Duplex could actually change the bases, not just the quality scores. So we'd want to keep both the original simplex parent reads _and_ the duplex reads or there will be loss of information. That's why we have the `dx:-1` tag (i.e. `dx:-1` + `dx:0` are all the original simplex reads).

Ok, but when the decision is taken for one of the two bases at the same (genomic) position, I'd assume, that the base quality  at this position drops in duplex read. I would not consider this a "loss" of information, but some kind of "consensus error correction"., and thus a somewhat "correct" representation of the molecule .. and important as well: "ready to use data" :-)

**Comment by tijyojwad** [comment]
That's a good question. The duplex model could determine that one strand was correct and derive a qscore from that confidence, or mark it down if it's not sure which one is more correct. I think it can change on a case by case basis.

By loss of information I mostly meant that in the final output, it's probably helpful to keep all the original simplex basecalls and the duplex calls so downstream analysis can have all of it available.

**Comment by imogen-foote** [comment]
> @sklages - quick update that read splitting for simplex is now enabled by default in [v0.4.0](https://github.com/nanoporetech/dorado/releases)

Could you please explain exactly what is meant by 'read splitting for simplex'? Does this mean simplex reads with duplex offspring (dx:i:-1) are split into 
a) the section covered by the duplex read and 
b) the unique section
If this is the case, are the a) sections included as dx:i:-1 and the b) sections included in dx:i:0, or are the a) sections removed entirely and the b) sections included as dx:i:-1? Essentially, I'm just wanting to know what combination of dx:i:0, dx:i:1 and dx:i:-1 will give me all the unique reads without any 'false coverage'. 

Or possibly I am misinterpreting this entirely, in which case could you please clarify. Thank you!

**Comment by tijyojwad** [comment]
Hi @imogen-foote

> read splitting for simplex is now enabled 

This doesn't affect `dorado duplex`, only the `dorado basecaller` cmd. Previously the `dorado basecaller` cmd was not splitting unspilt reads. This functionality has now been added.

**Comment by imogen-foote** [comment]
Hi @tijyojwad, thanks for your quick reply! 
I am still a bit confused what is meant by 'splitting the reads'. Does this simply mean simplex reads called using `dorado basecaller` are labelled as either having duplex offspring (dx:i:-1) or not (dx:i:0)? 
Sorry if this is obvious, but appreciate you clarifying.

**Comment by tijyojwad** [comment]
Hi @imogen-foote - sorry for the late reply. Sometimes during data acquisition multiple reads are concatenated into a single read. Dorado attempts to split such reads into subreads corresponding to the actual underlying data. This is what we refer to as "read splitting". That is not related to the `dx:i` tags directly. Duplex is performed _after_ read splitting, so some duplex pairs come from the split reads.

**Comment by minefield47** [comment]
hi @tijyojwad, 

I have a quick question to ask about duplexing straight from raw pod5 files.

When I run ```dorado duplex``` does the basecalling necessary conduct read splitting for all data passed into the program (i.e. the simplex data outputted is already split to prevent the chimera formations you discuss)? 

Additionally, if you have any links about what determines whether two reads are enough to be duplexed together that would be amazing. I am brand new to ONT technologies and want to get a solid understanding of what is happening under the hood of Dorado. 
Thank you.

**Comment by tijyojwad** [comment]
> does the basecalling necessary conduct read splitting for all data passed into the program

yes that's correct. all the simplex reads are split before we run duplex pairing algorithm.

>  if you have any links about what determines whether two reads are enough to be duplexed

Here's the function in code that determines pairs - https://github.com/nanoporetech/dorado/blob/master/dorado/read_pipeline/PairingNode.cpp#L67 . Hope this helps!

**Comment by ShiriAr** [comment]
@tijyojwad is it still true that using the dx:i:1 tag for a duplex read made of the full simplex read A and half of another simplex read B will lead to loss of the half of A that doesn't participate in the duplex pair?

If so, if anyone knows how much information is lost by using dx:i:1 + dx:i:0 to represent all of the data (duplex + simplex without duplex offspring) please let me know :)

Thank you!
