### ISSUE TITLE
No modified base calling for duplex data?

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#329]
I noticed that "dorado duplex" doesn't have a --modified-bases-models parameter like "dorado basecaller".

Does that mean we can't do methylation calling?

Or can it be done in a separate step?

**Comment by ymcki** [comment]
Good to hear that it is under active development. I think it will be very useful for cancer and epigenomics research.

**Comment by HalfPhoton** [comment]
Hemi-methylation is now supported
