### ISSUE TITLE
key input not found in config.toml

### ISSUE THREAD

**Issue by laurahum** [nanoporetech/dorado#330]
Hi, 

I'm trying to run dorado with the model dna_r10.4.1_e8.2_400bps_fast@v4.2.0_5mCG_5hmCG@v2 like this:
`$ ./dorado basecaller dna_r10.4.1_e8.2_400bps_fast@v4.2.0_5mCG_5hmCG@v2 pod5/ > dorado_basecalling.bam`

And I'm getting the following error:
`[2023-08-10 20:18:14.633] [info] > Creating basecall pipeline`
`[2023-08-10 20:18:14.660] [error] [error] key "input" not found in the top-level table`
 `--> dna_r10.4.1_e8.2_400bps_fast@v4.2.0_5mCG_5hmCG@v2/config.toml`
`   |`
` 1 | [general]`
`   | ^--- the top-level table starts here`

When I check the config file that the error refers to, it is missing the [input] key that other config files for other models have. I just downloaded the models and I tried downloading them again in case the file was corrupted and I'm getting the same error which I have no idea how to solve.

Thanks!

**Comment by iiSeymour** [comment]
Hi @laurahum the model argument needs to be the simplex model `dna_r10.4.1_e8.2_400bps_fast@v4.2.0` and the `--modified-bases` flag is used to specify the mods to call so your command should be: 

```
$ ./dorado basecaller dna_r10.4.1_e8.2_400bps_fast@v4.2.0  pod5/ --modified-bases  5mCG_5hmCG > dorado_basecalling.bam
``` 

See https://github.com/nanoporetech/dorado#modified-basecalling.
