### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by quanguo2088** [nanoporetech/dorado#333]
Build in a6000 + cuda 11.8

Start testing: Aug 14 22:32 CST
----------------------------------------------------------
1/1 Testing: dorado_tests
1/1 Test: dorado_tests
Command: "/home/xxx/dorado/dorado/cmake-build/tests/dorado_tests"
Directory: /home/xxx/dorado/dorado
"dorado_tests" start time: Aug 14 22:32 CST
Output:
----------------------------------------------------------
[2023-08-14 22:32:49.704] [info] > Reading read channel info
[2023-08-14 22:32:49.705] [info] > Processed read channel info
[2023-08-14 22:32:51.280] [error] Unknown modified base abbreviation: 12mA
dorado_tests: /home/xxx/dorado/dorado/dorado/read_pipeline/DuplexSplitNode.cpp:215: dorado::DuplexSplitNode::ExtRead dorado::DuplexSplitNode::create_ext_read(std::shared_ptr<dorado::Read>) const: Assertion `ext_read.move_sums.back() == r->seq.length()' failed.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dorado_tests is a Catch v2.13.8 host application.
Run with -? for options

-------------------------------------------------------------------------------
No split output read properties
-------------------------------------------------------------------------------
/home/xxx/dorado/dorado/tests/DuplexSplitTest.cpp:137
...............................................................................

/home/xxx/dorado/dorado/tests/DuplexSplitTest.cpp:137: FAILED:
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases:  49 |  48 passed | 1 failed
assertions: 330 | 329 passed | 1 failed

<end of output>
Test time =   2.78 sec
----------------------------------------------------------
Test Failed.
"dorado_tests" end time: Aug 14 22:32 CST
"dorado_tests" time elapsed: 00:00:02
----------------------------------------------------------

End testing: Aug 14 22:32 CST

**Comment by vellamike** [comment]
Hi @guoquankisscall , what CPU architecture are you on?

**Comment by vellamike** [comment]
Hi @guoquankisscall  - you have found a broken test, thank you for this. It's greatly appreciated.

The test “[No split output read properties](https://github.com/nanoporetech/dorado/blob/3c63c5c4097f715e7dd324fb65d63e6c3742a4ca/tests/DuplexSplitTest.cpp#L137)” is failing because the [move table and the sum of the moves is not equal to the sequence length](https://github.com/nanoporetech/dorado/blob/master/dorado/read_pipeline/DuplexSplitNode.cpp#L215).  The [move vector of the read is all zeros](https://github.com/nanoporetech/dorado/blob/master/tests/DuplexSplitTest.cpp#L161). We haven't spotted this because we test in Release mode, so the assert is not executed. We will fix this soon.

**Comment by guoquankisscall** [comment]
> 

 Hi @vellamike, my CPU architecture is Intel® Xeon(R) Gold 6148 CPU @ 2.40GHz × 40

**Comment by guoquankisscall** [comment]
> Hi @guoquankisscall - you have found a broken test, thank you for this. It's greatly appreciated.
> 
> The test “[No split output read properties](https://github.com/nanoporetech/dorado/blob/3c63c5c4097f715e7dd324fb65d63e6c3742a4ca/tests/DuplexSplitTest.cpp#L137)” is failing because the [sum of the moves in the move table is not equal to the sequence length](https://github.com/nanoporetech/dorado/blob/master/dorado/read_pipeline/DuplexSplitNode.cpp#L215). The [move vector of the read is all zeros](https://github.com/nanoporetech/dorado/blob/master/tests/DuplexSplitTest.cpp#L161). We haven't spotted this because we test in Release mode, so the assert is not executed. We will fix this soon.


> Hi @guoquankisscall - you have found a broken test, thank you for this. It's greatly appreciated.
> 
> The test “[No split output read properties](https://github.com/nanoporetech/dorado/blob/3c63c5c4097f715e7dd324fb65d63e6c3742a4ca/tests/DuplexSplitTest.cpp#L137)” is failing because the [sum of the moves in the move table is not equal to the sequence length](https://github.com/nanoporetech/dorado/blob/master/dorado/read_pipeline/DuplexSplitNode.cpp#L215). The [move vector of the read is all zeros](https://github.com/nanoporetech/dorado/blob/master/tests/DuplexSplitTest.cpp#L161). We haven't spotted this because we test in Release mode, so the assert is not executed. We will fix this soon.

Thank you for your reply. I am looking forward to your solution.

**Comment by guoquankisscall** [comment]
> Hi @guoquankisscall - you have found a broken test, thank you for this. It's greatly appreciated.
> 
> The test “[No split output read properties](https://github.com/nanoporetech/dorado/blob/3c63c5c4097f715e7dd324fb65d63e6c3742a4ca/tests/DuplexSplitTest.cpp#L137)” is failing because the [sum of the moves in the move table is not equal to the sequence length](https://github.com/nanoporetech/dorado/blob/master/dorado/read_pipeline/DuplexSplitNode.cpp#L215). The [move vector of the read is all zeros](https://github.com/nanoporetech/dorado/blob/master/tests/DuplexSplitTest.cpp#L161). We haven't spotted this because we test in Release mode, so the assert is not executed. We will fix this soon.

Thank you for your reply. I am looking forward to your solution.

**Comment by tijyojwad** [comment]
This unit test was fixed a while back. Closing now.
