### ISSUE TITLE
Dorado failed with exit status 125

### ISSUE THREAD

**Issue by dixith-abhi** [nanoporetech/dorado#334]
I keep getting this error when I run EPI2ME basecalling software:

ERROR ~ Error executing process > 'wf_dorado:dorado (1)'

Caused by:
  Process `wf_dorado:dorado (1)` terminated with an error exit status (125)

Command executed:

  set +e
  source /opt/nvidia/entrypoint.d/*-gpu-driver-check.sh # runtime driver check msg
  set -e
  dorado basecaller         ${DRD_MODELS_PATH}/dna_r10.4.1_e8.2_400bps_hac@v4.1.0 .         --modified-bases-models ${DRD_MODELS_PATH}/dna_r10.4.1_e8.2_400bps_hac@v4.1.0_5mCG_5hmCG@v2                  --device cuda:all | samtools view --no-PG -b -o 0.ubam -

Command exit status:
  125

Command output:
  (empty)

Command error:
  docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
  time="2023-08-14T12:21:23-04:00" level=error msg="error waiting for container: context canceled"

Work dir:
  /mnt/c/Users/Abhi/tools/work/1e/baf61afb782f7d3e8da4b05f7917ce

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

**Comment by SamStudio8** [comment]
Hi @dixith-abhi, this repository is for the Dorado basecaller. Please open
wf-basecalling issues via
https://github.com/epi2me-labs/wf-basecalling/issues
