### ISSUE TITLE
 [error] Unable to determine sample rate for data.

### ISSUE THREAD

**Issue by guoquankisscall** [nanoporetech/dorado#335]
Hello, I get this error, how to solve this problem？Thank you.

GPU: A6000,  CPU: Intel® Xeon(R) Gold 6148 CPU @ 2.40GHz × 40,  CUDA: 11.8

command：./dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.2.0 /datasets/hmz/multi_read -x "cuda:0" -c 1000 -v

get error: 
[2023-08-15 10:26:07.893] [debug] Auto batchsize cuda:0: 10240, time per chunk 0.16470471 ms
[2023-08-15 10:26:07.904] [debug] - set batch size for cuda:0 to 640
[2023-08-15 10:26:07.905] [debug] - adjusted chunk size to match model stride: 1000 -> 996
[2023-08-15 10:26:07.905] [debug] - adjusted overlap to match model stride: 500 -> 498
[2023-08-15 10:26:07.907] [error] Unable to determine sample rate for data.

**Comment by vellamike** [comment]
Hi, what is the data you have in ` /datasets/hmz/multi_read` ? is it POD5?

Also, this is not the problem, but out of interest why are you modifying the chunk size?

**Comment by ymcki** [comment]
Did you run "pod5 inspect debug" to see if sampling rate is 5000?

**Comment by guoquankisscall** [comment]
> Hi, what is the data you have in ` /datasets/hmz/multi_read` ? is it POD5?
> 
> Also, this is not the problem, but out of interest why are you modifying the chunk size?

Thank you.  I replaced 'fast5' with 'pod5' and it worked.

**Comment by guoquankisscall** [comment]
> Did you run "pod5 inspect debug" to see if sampling rate is 5000?

Sorry，I didn't  run "pod5" inspect debug. I solved this problem by modifying the data format.

**Comment by tijyojwad** [comment]
@guoquankisscall can you clarify what you meant by `solved this problem by modifying the data format` ? was it just that your file extension was wrong?

**Comment by guoquankisscall** [comment]
> Yes, this problem is solved when I replace '.fast5' file with '.pod5' file.
