### ISSUE TITLE
Poor duplex speed performance dorado 0.3.4 on node with 4xA100

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/dorado#336]
Hi 

I still see the poor performance without guard-gpus dorado 0.3.4 (#326 ). In fact I started basecalling on another node as well with 2xA10 cards and it seems to keep up with the 4xA100 cards (40 GB RAM version). The 4xA100 cards managed to basecall ~4 GB in 24 hours with super accuracy duplex.

Both nodes are connected to the data through performant ceph storage. So I suspect that it is a dorado issue.

Best regards
Rasmus

**Comment by vellamike** [comment]
Hi @Kirk3gaard , 

I don't think this is a dorado issue. the `guard-opus` flag is actually [doing nothing](https://github.com/nanoporetech/dorado/blob/f7adda4a5010beb57894177bd4474eaddbb024f7/dorado/cli/duplex.cpp#L100) in Dorado 0.3.4 and this behaviour is default.


Are you seeing a machine with 2xA100 keep up with a machine with 4xA100? My theory is that you are IO limited.

Could you try following the split-by-channel instructions in the [section of the readme relating to improving the speed of duplex calling](https://github.com/nanoporetech/dorado#improving-the-speed-of-duplex-basecalling)?

**Comment by ymcki** [comment]
Sorry to hear about your performance issue. It does look like an I/O issue to me. Did you try putting your pod5 in an NVMe SSD?

Ceph RADOS achieved 11.1MBps, CephFS 11.5MBps, Lizard 11.4MBps, and Gluster 5.7MBps. It doesn't seem to be comparable to NVMe SSDs.

If you have time, can you also try dorado-0.2.x and see if you get better duplex calls?

https://github.com/nanoporetech/dorado/issues/331

**Comment by sklages** [comment]
@Kirk3gaard - not sure, but

>~4 GB in 24 hours with super accuracy duplex.

is 4 `Gigabytes` or `Gigabases` ..?

I am currently running `v0.3.4` on a single A100(40G), duplex/sup .. ETA at the beginning was around 30h, is now (after one hour runtime) corrected to 14h. ETA seems to recalculated (+ optimized?) constantly. GPU load is 99%, GPU mem utilisation around 85% (with `batchsize=0`). 

Dataset is DNA, around 554GBytes, 46Gb (estimated bases).  Runtime with `v0.3.2` was around 16h on the same machine.

**Comment by sklages** [comment]
@ymcki 
> If you have time, can you also try dorado-0.2.x and see if you get better duplex calls?

this is not an option as there has been pretty much development in `v0.3.x` . `v0.2.x` is quite old.

**Comment by Kirk3gaard** [comment]
The HPC reported that they have disk problems. So it is likely that you are right about the IO limitations. I am not sure whether it is feasible but it would be cool to have a live reporting of the samples/s (Gbp/hour) along with an expected value given the detected GPU and models.

**Comment by tijyojwad** [comment]
> have a live reporting of the samples/s

Will look into that!

**Comment by Kirk3gaard** [comment]
> Hi @Kirk3gaard ,
> 
> I don't think this is a dorado issue as such. The `guard-opus` flag is actually [doing nothing](https://github.com/nanoporetech/dorado/blob/f7adda4a5010beb57894177bd4474eaddbb024f7/dorado/cli/duplex.cpp#L100) in Dorado 0.3.4 and this behaviour is default.
> 
> Are you seeing a machine with 2xA100 keep up with a machine with 4xA100? My theory is that you are IO limited.
> 
> Could you try following the split-by-channel instructions in the [section of the readme relating to improving the speed of duplex calling](https://github.com/nanoporetech/dorado#improving-the-speed-of-duplex-basecalling)?

Would actually be convenient to have the P24/P48 save data sorted by channel with the release of HD flowcells making duplex calling more common going forward.

**Comment by tijyojwad** [comment]
> Would actually be convenient to have the P24/P48 save data sorted by channel

Absolutely! we're looking into that
