### ISSUE TITLE
dorado summary not providing "passes_filtering"

### ISSUE THREAD

**Issue by lmfaber** [nanoporetech/dorado#338]
Hi nanopore team,

I have a question regarding the `dorado summary` command. Please feel free to close the issue when this is not the right place for this to discuss.
I am re-running my basecalling with a higher quality model. I'm using the dorado basecaller to create a bam file and then create a summary on that file.

When using `dorado summary input.bam > summary.txt` I would expect the columns to be somewhat similiar to the machine output.
* Columns from the `sequencing_summary.txt` from the sequencing machine:
  `filename_fastq	filename_fast5	filename_pod5	parent_read_id	read_id	run_id	channel	mux	minknow_events	start_time	duration	passes_filtering	template_start	num_events_template	template_duration	sequence_length_template	mean_qscore_template	strand_score_template	median_template	mad_template	pore_type	experiment_id	sample_idend_reason`

In fact the only columns I get are a reduced subset of columns and the column that is called "passes_filtering" is missing.
* Columns from the `sequencing_summary.txt` from dorado.
  `filename	read_id	run_id	channel	mux	start_time	duration	template_start	template_duration	sequence_length_template	mean_qscore_template`

I wonder whether there is a plan to implement that column? Anyway, do I get that right, that the "passes_filtering" within the `sequencing_summary.txt` from the machine is set to TRUE when "mean_qscore_template" is >=8? If so, I could also filter the file from dorado that way instead of using the "passes_filtering".

Thanks for your help.
Lasse

**Comment by tijyojwad** [comment]
Hi @lmfaber , we currently do not have plans to implement the summary in a way that matches the sequencer output. However, most of the relevant information should be there already.

> do I get that right, that the "passes_filtering" within the sequencing_summary.txt from the machine is set to TRUE when "mean_qscore_template" is >=8? 

That is correct. I believe the min qscore value might change depending on what run configuration was used for the sequencer run, but 8 as default sounds right. It would also be useful to look through the run configuration to make sure no additional filters were applied (like minimum length cutoff, etc).

**Comment by lmfaber** [comment]
Thank you very much @tijyojwad. That answers all my questions. As there's no plan to match the output from the sequencer, I think the issue can be closed.
