### ISSUE TITLE
Bonito vs dorado

### ISSUE THREAD

**Issue by christopher-vollmers** [nanoporetech/dorado#34]
Hi,

Does dorado use the same models and/or produce the same baseballs as bonito?
The models seem to have very similar names and version numbers. 

Best,
Chris

**Comment by vellamike** [comment]
Hi, yes the models with the same name are the same models.

**Comment by christopher-vollmers** [comment]
Thank you for letting me know!

**Comment by vellamike** [comment]
I just realised I didn't fully answer your question - they are the same models and they produce the same basecalls. There might be some small differences due to small implementation differences but these are expected to be minor.

**Comment by christopher-vollmers** [comment]
Very cool. Thank you for the additional information. Looking forward to trying this on a Mac.

**Comment by billytcl** [comment]
Just adding onto this -- if I train a refined bonito model, is it compatible with dorado?

**Comment by iiSeymour** [comment]
yes @billytcl you can export your model from bonito with `bonito export --format dorado <refined-model>` and this will create a dorado compatible copy of the weights in the model directory.
