### ISSUE TITLE
duplicate read IDs in bam file extracted fastq, but not in fastq usint --emit-fastq

### ISSUE THREAD

**Issue by JWDebler** [nanoporetech/dorado#341]
Hi,

I was just recalling some old fast5 files and there may have been some duplications in there as I used 'fast5_pass', 'fast5_fail' and 'fast5_skip". I think sometimes a file doesn't get removed from the skip folder and you end up with on in there and another on in pass or fail.
![image](https://github.com/nanoporetech/dorado/assets/4354282/98692e54-e679-420f-9bea-a8502ee65b52)

Anyhow, the interesting thing was that for one run I created the default bam file and then used samtools to extract the reads into fastq.

For the second run I used the '--emit-fastq' option to go directly to fastq.

When I ran `seqkit stats` over those 2 fastq files I was expecting to see the same result, but ended up having more reads in the bam extracted fastq. `seqkit rmdup` managed to remove a chunk of duplicates.

My question is, does the `--emit-fastq` option do something similar to `seqkit rmdup` in that it removes duplicate reads? And if so, why does that not happen with the default bam output?
Cheers,
Johannes

**Comment by tijyojwad** [comment]
Hi @JWDebler - just to understand, does your input data have duplicate reads in them? Dorado doesn't do any explicit de-duplication. If a pod5 has multiple copies of a read, it will process all those copies.

We also don't do anything different between writing out BAM and FASTQ (except for the format of course). And for those, we just use the HTSLib APIs to write the records, which AFAIK doesn't do any additional filtering either. So this is indeed strange. Are you certain the same set of fast5s was used for both runs?

**Comment by JWDebler** [comment]
Interesting. I just called the same folder of fast 5 files twice. Once outputting the bam and once the fastq file. Then I extracted the fastqs from the bam file with samtools, and that fastq file ended up having duplicate reads. 
I'll repeat this once back in the lab on Monday, but it seems strange.

**Comment by phpeters** [comment]
Dear @tijyojwad ,

I encountered a similar issue. I was using the current binary of dorado 0.3.4, doing a duplex basecalling on a pod5 data set containing 120000 reads. Once piping into a bam file, once emitting fastq. The number of (split) simplex reads was the same in both result files, but there were more duplex reads in the fastq-emitting run (see numbers below, output from verbose mode). 
Also, the duplex-read-IDs differ partially between the two runs and output methods (see numbers even more below). Any thoughts on this?
Thanks a ton!
Philipp

dorado basecaller -v dna_r10.4.1_e8.2_400bps_sup@v4.2.0 pod5/
Simplex reads basecalled: 145397
Duplex reads basecalled: 17634
Duplex reads filtered: 3178
Duplex rate: 26.96974%
Basecalled @ Bases/s: 8.734423e+05

dorado basecaller --emit-fastq -v dna_r10.4.1_e8.2_400bps_sup@v4.2.0 pod5/
Simplex reads basecalled: 145397
Duplex reads basecalled: 17807
Duplex reads filtered: 3209
Duplex rate: 27.212938%
Basecalled @ Bases/s: 7.942487e+05

number of reads in bam-file: 163031
number of reads in fastq-file: 163204
read IDs in both files: 162806
duplex-read-IDs only in bam: 225
duplex-read-IDs only in fastq: 398

**Comment by tijyojwad** [comment]
Hi @phpeters - our duplex pairing algorithm within` dorado` is currently nondeterministic for performance reasons. Since dorado is heavily multi threaded, the pairs detected can change slightly from run to run based on the order in which reads are basecalled. In our experience the difference in read counts is within 1-2%.
 
That said, we understand it's not ideal and we have it on our roadmap to make it deterministic.

**Comment by phpeters** [comment]
Thanks for your swift reply and explanation!
A follow-up question: since the duplex reads are valid in both runs, is it possible / does it make sense to join the duplex data sets? And thus to repeat duplex-calling (depending on the length, number and quality of the duplex reads) and generate more of them?
Thanks and best!
Philipp

**Comment by tijyojwad** [comment]
I think technically it would be okay to merge the sets and keep the unique duplex read ids. Once a pair is detected the duplex read should be deterministic. So the same duplex read id between 2 runs should have the same sequence.

Even though pairs detected can very run to run, the number of pairs detected will typically pretty close to each other and close to the max yield given the current pairing heuristics (e.g. in your case ~27%). My guess is repeat duplex calling will maybe get you another 0.5-1%, so probably not worth the additional compute to get that. But of course depends on your compute availability and use case!

**Comment by phpeters** [comment]
Thanks or the explanation! And indeed, it's probably not worth the computational time. I just thought about it since I have now the output of two test runs.
Thanks and have a nice weekend!
Philipp

**Comment by phpeters** [comment]
Hej @tijyojwad ,
I would have one additional question regarding this: If I have a simplex read turning up in different duplex reads how should I handle such ambiguous duplex reads? Is there a filtering step in dorado planned, let's say to filter by timestamp?
Thanks and all the best!
Philipp

**Comment by tijyojwad** [comment]
Hi @phpeters - that's a good question. Biologically though there can only be one true pair. So this scenario can happen when false pairs are detected. I would think the false pairs would have a poorer Q score than the true one, and/or be shorter. So you could try to use that to filter them out?

In parallel we're continuing to improve the pairing rate, so these should become less and less prevalent in the future.

**Comment by HalfPhoton** [comment]
Closed as there has been no reply from the issue opener and other questions have been answered. 
Please re-open this issue if needed.
