### ISSUE TITLE
dorado sometimes output single base reads with '*' quality

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#344]
This happened with 0.2.1. Doesn't seem to happen much with 0.3.x.

Anyway, such reads can cause trouble with pysam and potentially other software.

https://github.com/pysam-developers/pysam/issues/1211

Maybe the best approach is just not to output single base reads? They will just make the average/median read length stat looks bad.

**Comment by tijyojwad** [comment]
Dorado shouldn't be outputting single base reads at all. We filter out all reads less than 5 bp long by default - https://github.com/nanoporetech/dorado/blob/master/dorado/utils/parameters.h#L31

Are you seeing this in simplex or duplex?

**Comment by ymcki** [comment]
Good. I am only seeing it in 0.2.1 duplex output via the duplex_tools workflow. It is great that it is fixed in the newer version. 

I think I will just have filter them out by myself when using older version.

**Comment by tijyojwad** [comment]
Got it! May I ask why you're using 0.2.1 and not one of the newer versions?
