### ISSUE TITLE
Modified basecalling all context 5mC r9.4.1

### ISSUE THREAD

**Issue by partha434** [nanoporetech/dorado#346]
Any advice on how to do modified basecalling for data from r9.4.1 flow cell in all context 5mC? I am working on mtDNA and it is mostly modified in non-cpg context instead of cpg?

**Comment by marcus1487** [comment]
We do not have a production or supported solution for all-context modified base calling for R9 data. The best recommendation would be to upgrade to the latest kit14 chemistry to achieve the highest accuracy results. 

We did release a research grade model for all-context 5mC and 6mA in R9 data (`res_dna_r941_min_modbases-all-context_v001.cfg` found in Rerio here: https://github.com/nanoporetech/rerio/tree/master/basecall_models), but this is linked to a basecaller with lower canonical base accuracy and intended for use in Megalodon (which is deprecated and issues with Guppy integration will not be fixed) in reference anchored mode (where you anchor modified base calls to mapped reference bases from a read). This model is only compatible with Guppy and will not be supported or updated.
