### ISSUE TITLE
Adapter trimming availability

### ISSUE THREAD

**Issue by asan-emirsaleh** [nanoporetech/dorado#347]
Hello!
Could you please provide me with the information on your plan about adapter trimming incorporating to the Dorado. It is the feature I rely on in my workflow and it was that I used in guppy. Now, I hope the Dorado trimming implementation would be as robust as that of guppy was, and paused rebasecalling of my old data until adapter trimming feature would be introduced. You included this functionality to the Dorado Roadmap. So a little clarification about estimated terms the feature planned to be implemented will navigate me to start rebasecalling of old data.

Best regards
Asan

**Comment by tijyojwad** [comment]
Hello @asan-emirsaleh 

We're working on barcode demuxing and barcode trimming right now which will be released with the next major version of dorado (expected in a few weeks time). The trimming in this case will remove anything up until the end of barcodes (including the adapter).

We plan to work on adapter trimming in the absence of barcoding next. It's a bit difficult to say if we'll be able to get this in as part of the same release, but I expect it to come in soon after in a subsequent minor release.

Thank you for your patience and for highlighting your need for the feature! It's most definitely still on the roadmap and high on our priority list.

**Comment by ymcki** [comment]
If I am not using barcode at all, do I have adapters in my reads?

**Comment by tijyojwad** [comment]
@ymcki - yes

**Comment by asan-emirsaleh** [comment]
Thank you @tijyojwad 
Adapter trimming in the absence of barcoding is an important use case in small-scale labs. It is the only use case for people who envolved with large genomes. It is also the feature I need to process my data.

Before that I used Porechop, guppy adapter trimming and LongQC (the latter performed all-vs-all alignment via modified minimap2). All the tools give different results. So sensitivity/false positives rate appears to be tricky to balance keeping trimming accurate.

**Comment by asan-emirsaleh** [comment]
@ymcki it is worth to note some terminology. As I understand, it is preferable to say "sequence trimming" when you will say about quality trimming or length trimming (i.e. if you want to trim 3 bases from the 3" end of the sequence), and say "adapter cutting" when yoy want to get out the sequence of barcode or technical adapter.
I find also tis article useful to understand how does the adapter organized: [Porechop_ABI: discovering unknown adapters in Oxford Nanopore Technology sequencing reads for downstream trimming](https://academic.oup.com/bioinformaticsadvances/article/3/1/vbac085/6835406)

**Comment by tijyojwad** [comment]
Hi @asan-emirsaleh  - I completely understand, and it's indeed a non-trivial problem to solve well. While we work on adding adapter trimming to dorado, the guppy adapter trimming (and other tools) should continue working on your data and we'll let you know once trimming is available in dorado.

**Comment by tijyojwad** [comment]
Hi @ymcki - I don't think it's strictly required (since e.g. most downstream mappers should soft clip the adapters anyway during alignment), but some users prefer to trim them. Adding @SamStudio8  re human variation pipeline settings

**Comment by Flower9618** [comment]
Hi, @tijyojwad , if I do the alignment without adapter trimming step, I worry that the molecule will be mapped to incorrect position on genome because of the adapter, especially for the molecule with small size.

**Comment by tijyojwad** [comment]
Hi @Flower9618 - yes that's a fair concern. We're discussing methylated calls in another ticket, but for others `guppy_barcoder` provides an offline method for trimming adapters (and barcodes). So that can be used while dorado adds the necessary support.

**Comment by tijyojwad** [comment]
Hi @asan-emirsaleh 

> Is this option expected to appear in the next release?

We are planning for this to be part of the next release

> Is it a middle adapter removal option? Or it will be of another context?

It splits reads based on adapters that occur within the reads. This doesn't remove the adapter sequence itself from the split reads.

**Comment by asan-emirsaleh** [comment]
Hello @tijyojwad 
ONT team works a lot and introduces many features and fixes each release. It is very encouraging.
In the last release notes, I found these lines:
https://github.com/nanoporetech/dorado/commit/54e14ca01e7391c8857989da7db086a4591375a1 - Add RNA read splitting
https://github.com/nanoporetech/dorado/commit/2dc1f039cac7f3e6cd082b77a5b020fed5488e2f - Enable RNA adapter trimming

Do I understand it correct - it is only available for RNA reads now, with DNA trimming being possibly introduced the next release?

Best regards
Asan

**Comment by tijyojwad** [comment]
Hi @asan-emirsaleh - currently only for RNA, but we're actively working on DNA adapter and primer trimming and plan to quite release it soon!

**Comment by charlesxu90** [comment]
> Hello @tijyojwad ONT team works a lot and introduces many features and fixes each release. It is very encouraging. In the last release notes, I found these lines: [54e14ca](https://github.com/nanoporetech/dorado/commit/54e14ca01e7391c8857989da7db086a4591375a1) - Add RNA read splitting [2dc1f03](https://github.com/nanoporetech/dorado/commit/2dc1f039cac7f3e6cd082b77a5b020fed5488e2f) - Enable RNA adapter trimming
> 
> Do I understand it correct - it is only available for RNA reads now, with DNA trimming being possibly introduced the next release?
> 
> Best regards Asan

Any documents for the adaptor/polyA tail trimming? Such as the algorithms, evaluated performance, or related papers?

I want to evaluate the performance and develop new methods based on such methods, so I want to know if that a solid result.

**Comment by charlesxu90** [comment]
> Hello @tijyojwad ONT team works a lot and introduces many features and fixes each release. It is very encouraging. In the last release notes, I found these lines: [54e14ca](https://github.com/nanoporetech/dorado/commit/54e14ca01e7391c8857989da7db086a4591375a1) - Add RNA read splitting [2dc1f03](https://github.com/nanoporetech/dorado/commit/2dc1f039cac7f3e6cd082b77a5b020fed5488e2f) - Enable RNA adapter trimming
> 
> Do I understand it correct - it is only available for RNA reads now, with DNA trimming being possibly introduced the next release?
> 
> Best regards Asan

BTW, in the latest code, `determine_signal_anchor_and_strand_drna` is as follows, the later process will do nothing as the `anchor` and `trailing_Ts` are 0s?

```
SignalAnchorInfo determine_signal_anchor_and_strand_drna(const dorado::SimplexRead& read) {
    return SignalAnchorInfo{false, 0, 0};
```

**Comment by charlesxu90** [comment]
> > Hello @tijyojwad ONT team works a lot and introduces many features and fixes each release. It is very encouraging. In the last release notes, I found these lines: [54e14ca](https://github.com/nanoporetech/dorado/commit/54e14ca01e7391c8857989da7db086a4591375a1) - Add RNA read splitting [2dc1f03](https://github.com/nanoporetech/dorado/commit/2dc1f039cac7f3e6cd082b77a5b020fed5488e2f) - Enable RNA adapter trimming
> > Do I understand it correct - it is only available for RNA reads now, with DNA trimming being possibly introduced the next release?
> > Best regards Asan
> 
> BTW, in the latest code, `determine_signal_anchor_and_strand_drna` is as follows, the later process will do nothing as the `anchor` and `trailing_Ts` are 0s?
> 
> ```c++
> SignalAnchorInfo determine_signal_anchor_and_strand_drna(const dorado::SimplexRead& read) {
>     return SignalAnchorInfo{false, 0, 0};
> ```
> 
> In the previous version, there is such a function, but is removed.
> 
> ```c++
> SignalAnchorInfo determine_signal_anchor_and_strand_drna(
>         const dorado::SimplexRead& read,
>         dorado::PolyACalculator::ModelType model_type) {
>     static const std::unordered_map<dorado::PolyACalculator::ModelType, int> kOffsetMap = {
>             {dorado::PolyACalculator::ModelType::RNA002, 5000},
>             {dorado::PolyACalculator::ModelType::RNA004, 1000}};
>     static const std::unordered_map<dorado::PolyACalculator::ModelType, int> kMaxSignalPosMap = {
>             {dorado::PolyACalculator::ModelType::RNA002, 10000},
>             {dorado::PolyACalculator::ModelType::RNA004, 5000}};
> 
>     const int kWindowSize = 250;
>     const int kStride = 50;
>     const int kOffset = kOffsetMap.at(model_type);
>     const int kMaxSignalPos = kMaxSignalPosMap.at(model_type);
> 
>     const float kMinMedianForRNASignal = 0.f;
>     const float kMinMedianDiff = 1.f;
> 
>     int bp = -1;
>     int signal_len = read.read_common.get_raw_data_samples();
>     auto sig_fp32 = read.read_common.raw_data.to(torch::kFloat);
>     float last_median = 0.f;
>     for (int i = kOffset; i < std::min(signal_len / 2, kMaxSignalPos); i += kStride) {
>         auto slice = sig_fp32.slice(0, std::max(0, i - kWindowSize / 2),
>                                     std::min(signal_len, i + kWindowSize / 2));
>         float median = slice.median().item<float>();
>         if (median > kMinMedianForRNASignal) {
>             float diff = median - last_median;
>             if (diff > kMinMedianDiff) {
>                 bp = i;
>                 break;
>             }
>         }
>         last_median = median;
>     }
> 
>     spdlog::debug("Approx break point {}", bp);
> 
>     if (bp > 0) {
>         return SignalAnchorInfo{false, bp, 0};
>     } else {
>         return SignalAnchorInfo{false, -1, 0};
>     }
> }
> ```


I realize the claim above the new code:
``` text
RNA polyA appears at the beginning of the strand. Since the adapter
for RNA has been trimmed off already, the polyA search can begin
from the start of the signal.
```
So the adaptors of reads from direct RNA sequencing has been removed. Does the same claim works for the NA12878. If not, how to remove adaptors from that dataset?

**Comment by charlesxu90** [comment]
@tijyojwad  Thanks for the reply. I want to trim the adapter and the polyA tail.

In the given code, I found the code to identify the polyA end, but not the code to trim the adapter. So I assumed that the adaptors already been removed in the latest fast5/pod5 data?

Please correct me if I'm wrong.

**Comment by tijyojwad** [comment]
Hi @charlesxu90 - the code to trim the RNA adapter is in the `ScalerNode` file. The raw data in the pod5 still contains the adapter signal

**Comment by charlesxu90** [comment]
@tijyojwad Get it. Thanks for the information.

**Comment by tijyojwad** [comment]
No, only ends. We depend on read splitting to split reads with middle adapters (which is only available during basecalling), and then the trim module trims end adapters.

**Comment by asan-emirsaleh** [comment]
Thank you for clarifying. As I understand, adapter trimming works also on a single basecalling stage of duplex processing being default option and could not be changed. There is no also a command line key to turn trim on/off in duplex basecalling because it does always work. Could you clarify is it right, please?

**Comment by tijyojwad** [comment]
Hi @asan-emirsaleh sorry for the late response (I was out of office). currently trimming is disabled for duplex. so no explicit trimming happens in duplex, and this cannot be toggled through any cmdline option.

**Comment by pclavell** [comment]
Is there any recommendation on how to cut adapters once we have the fastq files, considering that duplex basecalling is not removing them?

**Comment by tijyojwad** [comment]
you can run `dorado trim` on the output of `dorado duplex` to trim adapters.

**Comment by pclavell** [comment]
When doing `dorado basecall ` an option exists to look for primers that are not from ONT kits `--primer-sequences` but this doesn't exist for `dorado trim` . Does `dorado trim` try to identify other primers by default or just the ONT kits primers?

**Comment by tijyojwad** [comment]
that's an oversight on our part - we should be able to add it to `trim` command. can you create this as another issue and we'll flag it as a feature request?
