### ISSUE TITLE
Reads basecalled: Metal command buffer execution failed

### ISSUE THREAD

**Issue by vdejager** [nanoporetech/dorado#35]
Om MacOS M1 with 16 GB memory I get 

dorado basecaller --emit-fastq ~/bin/dorado-0.0.1+4b67720-Darwin/bin/dna_r9.4.1_e8_sup@v3.3 ./fast5 | gzip > run1.fastq.gz
> Creating basecall pipeline
> Reads basecalled: 200Metal command buffer execution failed: 5, try #0
> Reads basecalled: 300Metal command buffer execution failed: 5, try #0
Metal command buffer execution failed: 5, try #1
Metal command buffer execution failed: 5, try #2 

etc. etc.
what can I do to solve this?

**Comment by vellamike** [comment]
Hi @vdejager  - are basecalls actually produced or is this error preventing that from happening?
