### ISSUE TITLE
guppy -> dorado | update of MinKNOW (for P2)

### ISSUE THREAD

**Issue by sklages** [nanoporetech/dorado#350]
This is only half-related to `dorado` basecaller.
Mainly because commenting/discussing on the ONT announcents is very tedious (on https://community.nanoporetech.com).

Anyone here with experience on updating `MinKNOW` on **P2solo** from `23.04.6` to `23.07.5`?

Update from `22.07.9` (beta) to `23.04.6` was a little desaster here (mainly ownership/permission issues which have been revealed during run start yet).

Reading the comments of the announcement of `23.07.5` update together with the experience of the previous update, makes me hesitate to install it ... in this update `guppy` will replaced by `dorado`.

- Any quirks during or fixes to be done after this update?
- we are running `23.04.6` on Linux MINT 21 (Ubuntu 22.04 LTS based) without any issues. Others here running `MinKNOW` on "newer" systems like `22.04`?
- what is the way to go for testing an update technically? GPU, data directories, permissions etc. 
After the last update the first run failed due to permission issues. This was not obvious/visible in `MinKNOW` before starting the run.
-  any general comments on new version of `MinKNOW`?

**Comment by AngieKou** [comment]
Hi @sklages,

Thank you for the comment, it is likely you will get more responses from other nanopore users if you share this in the community. Could you share why you find commenting there tedious? And is there a way we could help with that ? 

Thank you,
Angie

**Comment by sklages** [comment]
@AngieKou - This was just a try ... as there were also no comments on my colleague's comment. 

Mainly because it is not possible to comment without being **full member** .. orientation on that site is also not very obvious/clear ... lack of good overview ..

So I can close this issue and keep waiting with the update :-) I'll do that if we have fewer libraries to run ..

**Comment by AngieKou** [comment]
Hi @sklages thank you for your feedback on the community, we appreciate it. Please feel free to keep the comments open in both places so you can reach more nanopore users. Also, is your colleagues's comment here : https://community.nanoporetech.com/posts/software-release-23-04-6-f or in some other post? 

Best,
Angie

**Comment by sklages** [comment]
> Hi @sklages thank you for your feedback on the community, we appreciate it. Please feel free to keep the comments open in both places so you can reach more nanopore users. Also, is your colleagues's comment here : https://community.nanoporetech.com/posts/software-release-23-04-6-f or in some other post? 

@AngieKou - Well, I think I'll stick with github, it is more convenient, especially on small devices. :-)

My colleague's post is in https://community.nanoporetech.com/posts/software-release-23-07-5-f-12922

We are planning to update MinKnow most probably in October.
