### ISSUE TITLE
More reads obtained from dorado duplex than simplex?

### ISSUE THREAD

**Issue by nam-hoang** [nanoporetech/dorado#351]
Hi there, 
I have a Nanopore dataset of ~5 Gb in pod5 format, and I did base calling using dorado simplex and duplex just to compare using the following commands:

`dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.2.0 run_01_202308_pod5_files/ --emit-fastq | gzip > simplex.fq.gz`
`dorado duplex dna_r10.4.1_e8.2_400bps_sup@v4.2.0 run_01_202308_pod5_files/ --emit-fastq | gzip > duplex_sup.fq.gz`

For the duplex run, the read quality is significantly improved with 16% duplex rate detected, mean quality from 13.4 to 15.3 (median quality from 14.8 to 17). I got ~9% more read count (~8% more bases) in the duplex run compared to the simple run. I have also tried to do duplex using dna_r10.4.1_e8.2_400bps_hac@v4.2.0 model, and got a similar result, more read count/bases than the simplex run.

I have checked but it seems like no one has asked this question before. I wonder, in this case, do I expect the duplex run to yield less read count compared to the simplex, but of higher quality? Or am I missing something here?

Thank you very much and I am looking forward to hearing what you think.
Best regards,
Nam

**Comment by sklages** [comment]
#327 and #316 may be of interest.

**Comment by tijyojwad** [comment]
Hi @nam-hoang - please refer to https://github.com/nanoporetech/dorado#duplex for the details and let us know if you have any more questions!

**Comment by nam-hoang** [comment]
Thank you very much @sklages. I did not know you asked this already. Very nice and informative discussion there.

Dear @tijyojwad. Yes, thank you very much for your suggestion.
Given that the duplex rate is not so high in my data (16%), if I just want to use ONT reads for genome assembly or scaffolding, is it ok to just take dorado default output (including both simplex and duplex reads) for downstream analyses? Or should exclude simplex reads which have duplex offsprings (tag dx:i:-1)?

**Comment by sklages** [comment]
@nam-hoang - if you simply remove `dx:-1` reads from your data you *may* loose some long(er) reads. 
For denovo assembly and/or scaffolding it is most probably fine to use the complete data (`dx:0/1/-1`).

**Comment by nam-hoang** [comment]
Thank you very much for your advice @sklages.

**Comment by tijyojwad** [comment]
As @sklages said, should be fine to use all.
