### ISSUE TITLE
0.3.4 uses more VRAM than 0.3.2?

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#354]
While 0.3.3's release note claims it uses less VRAM than 0.3.2, in reality, when I use wf-human-variation-1.6.1 pipeline with the 0.3.2 image in my 4xA100 80GB box, I could run maxForks = 2 and finishes basecall and align in 19hrs for a typical run with modified bases. However, when I switch the image to 0.3.4, it crashes with OOM. Then I set maxForks to 1 and it can run into completion in 37hr. 

Is there a parameter I can pass to 0.3.4 to reduce VRAM usage? Thanks a lot in advance.

**Comment by vellamike** [comment]
0.3.4 uses less VRAM _for the same batch size_ - what's going on here is that 0.3.4 is using this lower VRAM consumption to select a much larger batch size, leading to higher VRAM utilisation. In retrospect we didn't do a very good job of explaining this in the changelog.

You could reduce VRAM by reducing the batch size using the `b` parameter, this will work.

However, why are you running this workflow with multiple forks? This is usually a poor way to improve the performance of memory-hungry GPU applications. Is the performance improvement on 0.3.2 significant when you do this?

**Comment by SamStudio8** [comment]
Hi @ymcki, Nextflow has no capability to ensure that tasks using a GPU are assigned to distinct CUDA devices, which is why our workflows are set to use the entire GPU device (ie. all 4 of your A100s) and run tasks in serial (by setting maxForks=1) when the executor is local. This is a limitation of Nextflow for us to overcome and we would like to improve this.

That you have previously been able to use maxForks=2 is more of a lucky happenstance rather than an intended feature, as the workflow cannot make any guarantees to avoid any GPU task exceeding the available VRAM. As @vellamike has suggested, you can try to tune your batch size by passing through options to Dorado with `--basecaller_args '-b N'`, but as the workflows are not currently intended to support parallel GPU tasks on local executors this will have to be left as an experiment.

**Comment by ymcki** [comment]
Thanks for your reply. From looking at the AWS benchmark, it appears to me your main testing platform is a 4xA100 40GB. I suppose that would mean dorado is optimized for A100 40GB. I think maxForks=2 might be a good way to use all the VRAM I have on A100 80GB.

Is it possible to an option in the future to force to pick a batch size that is a certain number of steps back from the optimal batch size?

For example, this is how you pick the batch size
```
  [2023-08-18 11:16:41.881] [debug] Auto batch size: GPU memory available: 83.422543872GB
  [2023-08-18 11:16:41.881] [debug] Auto batch size: testing up to 768 in steps of 64
  [2023-08-18 11:16:42.070] [debug] Auto batchsize: 64, time per chunk 2.943152 ms
  [2023-08-18 11:16:42.120] [debug] Auto batchsize: 128, time per chunk 0.390208 ms
  [2023-08-18 11:16:42.202] [debug] Auto batchsize: 192, time per chunk 0.4267467 ms
  [2023-08-18 11:16:42.288] [debug] Auto batchsize: 256, time per chunk 0.326496 ms
  [2023-08-18 11:16:42.374] [debug] Auto batchsize: 320, time per chunk 0.2608864 ms
  [2023-08-18 11:16:42.459] [debug] Auto batchsize: 384, time per chunk 0.214384 ms
  [2023-08-18 11:16:42.545] [debug] Auto batchsize: 448, time per chunk 0.18847542 ms
  [2023-08-18 11:16:42.633] [debug] Auto batchsize: 512, time per chunk 0.166402 ms
  [2023-08-18 11:16:42.724] [debug] Auto batchsize: 576, time per chunk 0.15390934 ms
  [2023-08-18 11:16:42.820] [debug] Auto batchsize: 640, time per chunk 0.14878401 ms
  [2023-08-18 11:16:42.917] [debug] Auto batchsize: 704, time per chunk 0.1375069 ms
  [2023-08-18 11:16:43.015] [debug] Auto batchsize: 768, time per chunk 0.12478 ms
  [2023-08-18 11:16:43.037] [debug] - set batch size for cuda:3 to 768
```
If I set that parameter to 2, then instead of picking 768, it would pick 640 instead.

**Comment by vellamike** [comment]
> it appears to me your main testing platform is a 4xA100 40GB
We test on multiple GPUs, Dorado is optimised to perform optimally on a wide range of GPUs, including 80GB A100.

> I think maxForks=2 might be a good way to use all the VRAM I have on A100 80GB.

Using all the VRAM isn't necessarily the best way to make a GPU accelerated application faster. Dorado will identify how much free memory is available on your GPU and select the most appropriate batch size to maximise speed.

> Is it possible to an option in the future to force to pick a batch size that is a certain number of steps back from the optimal batch size?

Running with a suboptimal batch size will make dorado slower, even if you have two processes. The GPU driver will not allow both processes to use the GPU at the same time.

Dorado is very heavily optimised and it is unlikely that you can make Dorado faster by running more than one process.

**Comment by ymcki** [comment]
> Running with a suboptimal batch size will make dorado slower, even if you have two processes. 

Suboptimal batch size seems to only slow down the process by 10-15%. So it would seem possible that if two processes can be run in parallel, we should run faster.

> The GPU driver will not allow both processes to use the GPU at the same time.

Does that mean maxForks is a useless option??? 

> Dorado is very heavily optimised and it is unlikely that you can make Dorado faster by running more than one process.

The problem is empirically I am observing significant speed up with maxForks=2 on 0.3.2. If you can replicate my result, then I think it makes sense to investigate why this is happening.

**Comment by vellamike** [comment]
> Suboptimal batch size seems to only slow down the process by 10-15%. So it would seem possible that if two processes can be run in parallel, we should run faster.

This may intuitively seem possible, however it is not correct for applications like Dorado which have very high GPU utilisation. Separate processes do not run in parallel on the GPU hardware, they are time sliced. This is why tools like NVIDIA's CUDA Multi-Process Service (MPS) exist.

> Does that mean maxForks is a useless option???

maxForks in the precise context of what you are trying to do is not useful. However it is certainly not a useless option more generally.

> The problem is empirically I am observing significant speed up with maxForks=2 on 0.3.2. If you can replicate my result, then I think it makes sense to investigate why this is happening.

Can you provide precise detail on what you're seeing (speed measurement, exact commands executed etc).

**Comment by ymcki** [comment]
sbatch -c 96 --mem-per-cpu 8G --gpus=4 --wrap "./nextflow run wf-human-variation-1.6.1 -w ABC/workspace -profile singularity --snp --fast5_dir /data/20230626_XXXX_XX_PAOXXXXX_XXXXX/ --ref ~/genome/hs38.fa --bed ~/genome/hs38.bed --basecaller_cfg 'dna_r10.4.1_e8.2_400bps_sup@v4.2.0' --remora_cfg 'dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v2' --sample_name ABC --out_dir ABC --dorado_ext fast5"

My raw data is fast5 from Promethion R10.4.1 flowcell. Throughput is about 120Gbp. Run time difference is 19hr vs 37hr. 
I edited nextflow.config to switch between 0.3.2 and 0.3.4
        basecaller_container = "dorado:sha62a9bc4388e790387356c778752e2d1fd6d0e2ad" // 0.3.2
        basecaller_container = "dorado:sha50cd2736bf9ffdf00587c0f4c8af82f6fe07740a" // 0.3.4

**Comment by SamStudio8** [comment]
@ymcki Do you have the timeline and trace files in the <outdir>/execution
directory of the workflow?

**Comment by iiSeymour** [comment]
@ymcki see https://github.com/nanoporetech/dorado#performance-tips

Using `maxForks=2` is just working around fast5's single threaded access.

**Comment by ymcki** [comment]
> @ymcki see https://github.com/nanoporetech/dorado#performance-tips
> 
> Using `maxForks=2` is just working around fast5's single threaded access.

I see. Do you mean maxForks will be irrelevant when we switch to pod5?

**Comment by vellamike** [comment]
> I see. Do you mean maxForks will be irrelevant when we switch to pod5?

Yes, that is correct.
