### ISSUE TITLE
Suggestion: add an option to provide samples/s for performance testing 

### ISSUE THREAD

**Issue by husamia** [nanoporetech/dorado#355]
It would be great if you can add an option to provide user basic performance metrics this would be useful for benchmarking across systems. For example, an option mode could be used to run demo data and and provide number of samples/second basecalled

**Comment by vellamike** [comment]
Hi @husamia 

Dorado already provides a read for samples/s by default, e.g:

```
 [2023-08-31 15:07:38.399] [info] > Basecalled @ Samples/s: 1.390118e+07
```

Is this what you need? Or are you looking for something like a `dorado benchmark` command which could use simulated data to just measure performance?

**Comment by husamia** [comment]
@vellamike yes precisely. I am looking for a dorado benchmark command which would use reference simulated data to measure performance.

**Comment by husamia** [comment]
@vellamike I want to compare the performance between the Apple Silicon and the GPU based methods for example. what's an easy way to do it quickly?

**Comment by tijyojwad** [comment]
Hi @husamia - there's no `dorado benchmark` command currently. If you have a reference dataset, I would simply run the same command on both platforms with the same dataset compare performance.
```
dorado basecaller <model> <reference-dataset> > /dev/null
```

Will that be sufficient for your benchmarking?

**Comment by husamia** [comment]
@tijyojwad what is the output? I like the samples/second that Guppy outputs to compare. it seems intuitive enough.

**Comment by tijyojwad** [comment]
Dorado also outputs `samples/sec` at the end of basecalling

https://github.com/nanoporetech/dorado/issues/355#issuecomment-1701125125

**Comment by vellamike** [comment]
Closing this issue since the recommeded way to benchmark dorado is to basecall with a reference dataset and use the measured `samples/s` value.
