### ISSUE TITLE
Dorado doesn't seem to terminate correctly when it fails on HPC environment

### ISSUE THREAD

**Issue by adbeggs** [nanoporetech/dorado#356]
Hi all,

I have Dorado 0.32 running inside our Redhat 8.3 based slurm scheduler driven enviornment. When I have it running on a flowcell if it crashes out (e.g. because I've chosen the wrong .cfg i.e. 4khz instead of 5khz) it doesn't terminate correctly and so the job will run for the full time I've given it on the cluster e.g. 7 days... even though Dorado has finished.

Saying that it is bloody fast on 4xA100 GPUs, can 5-mC and 5-hMC a 60x coverage human cancer sample in just under an hour. 

Andrew

**Comment by vellamike** [comment]
I think this is much more likely to be an issue with the way your SLURM job is configured than a Dorado error as such. In the scenario you've described Dorado will just error out in a very standard way, by throwing a runtime error. Could you run a job which errors out after 20 minutes to see what happens? I'd like to know if it shows the same behaviour, in which case you'd know it's not Dorado. Try this:

```
import time
import sys

def main():
    start_time = time.time()
    timeout = 20 * 60  # 20 minutes in seconds

    try:
        while True:
            elapsed_time = time.time() - start_time

            if elapsed_time > timeout:
                raise RuntimeError("The program has timed out after 20 minutes.")

            # Your application logic here
            time.sleep(1)

    except RuntimeError as e:
        print(e, file=sys.stderr)
        raise e  # Re-raise the error, causing the program to "crash"

if __name__ == "__main__":
    main()
```

**Comment by adbeggs** [comment]
Okay will do – but we haven’t seen this problem with anything else…

A

**Comment by vellamike** [comment]
Thanks, please let me know what happens. 

Did this issue happen during simplex calling?

[Here](https://github.com/nanoporetech/dorado/blob/master/dorado/cli/basecaller.cpp#L88) is the code which would cause the exit. I can't spot anything which Slurm would find challenging to deal with.

**Comment by adbeggs** [comment]
Yes with simplex modified base calling in HAC

A

**Comment by tijyojwad** [comment]
>  it doesn't terminate correctly

if dorado find an incompatible config (e.g. model doesn't match data sampling rate), dorado ends with an exit code of `1`. might also be worth checking if there's any special handling for exit code 1 in your slurm config

**Comment by HalfPhoton** [comment]
Closing this ticket as there's been no update in a while - please re-open if your issue has not been resolved.
