### ISSUE TITLE
Sample rate for model (4000) and data (5000) are not compatible

### ISSUE THREAD

**Issue by gilmahu** [nanoporetech/dorado#357]
Hello dorado ONT community,

I have generated pod5 files using the RBK114.24 kit on the Flowcell 10.4.1
To basecall the reads, I am using Dorado with the model dna_r10.4.1_e8.2_400bps_hac@v4.1.0
I was however surprise to receive this error message:
"Sample rate for model (4000) and data (5000) are not compatible".
Does anyone know which model i should try instead? I guess the data was not of optimum quality? 

Best regards 
Gildas

**Comment by sklages** [comment]
the 5kHz model: `dna_r10.4.1_e8.2_400bps_hac@v4.2.0` :-)

**Comment by gilmahu** [comment]
Thanks, didn't know which corresponds tp which model

**Comment by sklages** [comment]
https://github.com/nanoporetech/dorado#simplex-models

**Comment by gilmahu** [comment]
Hi Sklages, 
I have one fundamental question, is dorado built to only produce a single output file?
I have been struggling with different loops; first, it does not process  files as input but a whole folder, and then it is unable to produce separate basecalled fastq files for each pod file file from the run.
It is producing a single fastq file for the entire folder of pod5 files.
I’m therefore unsure as to how I proceed?
Perhaps I’m expecting dorado to work like guppy?

**Comment by sklages** [comment]
yes, `dorado` works on directories, calls the contents and writes a single output file. That's what I like, it's pretty straight forward :-)

But `dorado` is not yet feature-complete, maybe there will be some more flexibilty implemented in future versions?

What are you trying to achieve? When writing BAM, you can chunk/filter/divide later after basecalling..

If you really need to basecall each pod5 file separately, then loop over each pod5 file, create a subdir, symlink the single pod5 into that subdir, basecall the content of this subdir, remove symlink, go for the next pod5 ...

**Comment by gilmahu** [comment]
Kindly see my detailed response to this via the issue https://github.com/nanoporetech/dorado/issues/359

**Comment by tijyojwad** [comment]
Closing this issue as further discussion is moved to #359
