### ISSUE TITLE
dorado basecaller output fastq for assembly

### ISSUE THREAD

**Issue by gilmahu** [nanoporetech/dorado#359]
I have been using Guppy to basecall Fast5 files into Fastq files for my downstream Whole Genome Sequencing (WGS) assemblies. However, recently, I started using Dorado, and it seems to operate quite differently. To obtain Fastq outputs, I had to add the --emit-fastq flag.

Now, I have a fundamental question: Is Dorado designed to generate only a single output file? I've encountered some challenges while trying to process my data. First, it appears to process folders as input rather than individual files. Additionally, I've been unable to produce separate basecalled Fastq files for each individual pod5 file from the sequencing run. Instead, Dorado seems to generate a single Fastq file for the entire pod5 folder containing pod5 files.

I'm uncertain about how to proceed from here. Am I mistaken in my expectation that Dorado should work similarly to Guppy in this regard? Your insights and guidance would be greatly appreciated. Thank you!

**Comment by sklages** [comment]
see #357 

Why do you need separate fastq files for assembly? (assuming shotgun assembly, not reference-based mapping)
What are you trying to achieve?

**Comment by gilmahu** [comment]
Hi Sklages,

I apologize for my brief absence.

In my regular workflow, I work with Whole Genome Sequencing (WGS) bacterial isolates using both nanopore and Illumina sequencing. After basecalling each nanopore run, I demultiplex the data to obtain Fastq reads for each sample, which are organized into separate barcode folders. I also perform Illumina short-read sequencing of the same samples for hybrid assembly to achieve closed genomes. Since my assembly pipelines primarily rely on Fastq files, Guppy has been my go-to tool for this process.

This week, I decided to try Dorado for the first time. So far, I've managed with a loop to perform the basecalling by creating temporary subdirectories to obtain Fastq basecalled files for all pod5 files as you suggested elsewhere. However, this approach feels somewhat cumbersome.

The challenge I'm facing is that Dorado doesn't seem to handle demultiplexing and sample separation by barcode, which is a crucial step in my workflow. As a result, I find myself having to revert to Guppy for this specific task.

My question for you is whether the single output file generated by Dorado (in the simplex form) can be demultiplexed into different barcode folders using Guppy? Any insights or guidance you can provide on this matter would be greatly appreciated. Thank you!

**Comment by sklages** [comment]
For demultiplexed samples we currently do the basecalling (fast) on the machine (P2solo), which separates the pod5 data per barcode in the run folder (still using guppy). We then use these data for sup basecalling with `dorado`.  
Not perfect, but it works .. looping over these folders is trivial and okay for me .. 

As we need simplex/duplex basecalling in sup-mode, there is currently no other option (going back to guppy is not an option); as dorado is not yet feature-complete, demultiplexing is probably on their todo list :-)

**Comment by gilmahu** [comment]
Great flow. 
So correct me if I'm wrong. Will it make sense, if I try to first demultiplex the pod5 outputs of the sequencing per barcode (using guppy, hoping Guppy recognized the pod5 files and does the job); then I can run sup basecalling on each barcode folder later using Dorado..?

**Comment by sklages** [comment]
IMHO yes. That's how I did it (via minknow) :-)

**Comment by gilmahu** [comment]
I have just tried this and Guppy barcoder, could not demultiplex the pod5 folder per barcode; it probably did not recognize pod5 files. How do you often process the raw pod5 folder before the demultiplexing with the guppy barcoder?

**Comment by sklages** [comment]
fast basecalling on the P2solo, during the run (minknow still uses guppy in `23.04.6`). Minknow writes pod5 data per barcode, I never used guppy for that afterwards.

**Comment by tijyojwad** [comment]
Hi @gilmahu - barcode demultiplexing is on our roadmap for the upcoming release scheduled in a few weeks. Then you would be able to basecall and demux via dorado directly.

For your current setup, you can also look at using the standalone `guppy_barcoder` which can be run on the output of dorado basecalls to only demux the reads.

**Comment by gilmahu** [comment]
@sklages your approach would be the best right now, unfortunately, I have already completed the runs, so I cannot do the fast basecalling on Minknow at this step. 
@tijyojwad, indeed that is what I have to do now, which is to first basecall with dorado and then use guppy_barcoder 

However, i have a general question: when dorado generates the single output Fastq file for all my runs (without prior demultiplexing), will guppy_barcoder still be able to demultiplex that single file per bardode?

**Comment by tijyojwad** [comment]
Yes I believe guppy barcoder can just operate on the combined fastq file generated by dorado. guppy barcoder support this cmdline
`guppy_barcoder -i <input fastq path> -s <save path> --barcode_kits <kit name>` where the `-I` would take in the output fastq from dorado and then you specify output location and barcode kit used.

**Comment by gilmahu** [comment]
Ok @tijyojwad I will try this. I was not sure, so i had to make a loop with dorado to make temporary subfolders in order to basecall each pod5 file into Fastq before i demultiplex with guppy barcoder and it has been taking too long. 
I will get back to you with updates on this

**Comment by gilmahu** [comment]
Hi @tijyojwad and @sklages  I have just tested the approach of basecalling all my pod5 with dorado  into one Fastq.gz output file, then I use guppy the demultiplex them. The difference is that this generated very low number of Fastq per barcode with rather a lot of data into the unclassified barcode folder. On the other hands, when I basecall individually each pod5 (using temporary directories with dorado) i get higher volume of files during the downstream demultiplexing with guppy. But in both cases the unclassified barcode folder has more reads than each barcode folder... If there are some other tricks i will be happy to read more from you  guys. And mostly about this issue of so many reads coming out as unclassified during demultiplexing.

**Comment by tijyojwad** [comment]
Hi @gilmahu - dorado now supports barcode classification as of release v0.4.x - https://github.com/nanoporetech/dorado#barcode-classification

You can run barcode classification with dorado while basecalling, then use the `dorado demux` to demultiplex the output reads into a BAM file per barcode.

**Comment by Ciznetwork** [comment]
Hi,  I am currently having this issue. I need to get demultiplexed fastq files per barcode out of my pod5 files for downstream processing with porechop, but dorado is giving me a single fastq file. Kindly advise on how to solve this problem.

Thanks

**Comment by Ciznetwork** [comment]
@sklages Thanks for the timely response. I will let you know how it goes.

**Comment by Ciznetwork** [comment]
Hi, I have been trying to base-call my pod5 folder with subdirectories; unfortunately, I have been having this error,I also could not see anywhere they specified this by path. Kindly advise. Thank you

[2024-07-23 12:49:07.683] [info] Running: "basecaller" "sup" "--no-trim" "--emit-fastq" "--kit-name" "SQK-NBD114-96" "--min-qscore" "10" "-r" "--device" "cuda:0" "pod5_pass_copy"
[2024-07-23 12:49:07.712] [info]  - Note: FASTQ output is not recommended as not all data can be preserved.
[2024-07-23 12:49:07.725] [error] Failed to determine sequencing chemistry from data. Please select a model by path

**Comment by Ciznetwork** [comment]
@sklages  thanks for your help. The folder is valid  please see the attached shot
<img width="1207" alt="image" src="https://github.com/user-attachments/assets/e358836d-5f5e-42e4-a0c5-9c406fc990b1">

**Comment by sklages** [comment]
`ls pod5_pass_copy/*` .. must not be empty, also omit `--emit-fastq` as you do the demultiplexing in the next step. Stick with BAM as long as you can :-)

**Comment by Ciznetwork** [comment]
@sklages Many thanks again. Let me list what I really want to achieve again
1. I no longer intend to demultiplex with dorado. I found out I can just do this with qcat. qcat will give me the fastq files per barcode that are compatible with the spaghetti pipeline I will be using. This is the reason I am trying to get the fastq files from dorado. Besides, the Samtools FastQ is not doing it the way I want.
2.  When I merged all pod5 subdirectories and gave a single folder containing the pod5 files to Dorado, it worked fine. 
3. What I intend to accomplish is to be able to just give the pod5 fold coming off the sequencer to Dorado for basecalling without any need for merging the subdirectories. I hope this makes sense to you.
Thank you

**Comment by Ciznetwork** [comment]
Hi all, 
I have been getting this error lately trying to basecall and demultiplex with Dorado. Please kindly advise.
Creating basecall pipeline
[2024-08-11 11:59:18.475] [error] toml::parse: file open error -> sup/config.toml
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not read header from file: -
/var/lib/slurm/slurmd/job9932192/slurm_script: line 21: 49910 Exit 1                  dorado basecaller --device cuda:all --min-qscore 7 --no-trim --emit-fastq sup pod5_pass
     49911 Aborted                 (core dumped) | dorado demux --kit-name "SQK-NBD114-96" --emit-fastq --output-dir .

**Comment by Ciznetwork** [comment]
I am running this on a cluster and it has worked well before now.

**Comment by Ciznetwork** [comment]
@tijyojwad , @sklages @rmp  kindly respond 
Hi all,
I have been getting this error lately trying to basecall and demultiplex with Dorado. Please kindly advise.
Creating basecall pipeline
[2024-08-11 11:59:18.475] [error] toml::parse: file open error -> sup/config.toml
terminate called after throwing an instance of 'std::runtime_error'
what(): Could not read header from file: -
/var/lib/slurm/slurmd/job9932192/slurm_script: line 21: 49910 Exit 1 dorado basecaller --device cuda:all --min-qscore 7 --no-trim --emit-fastq sup pod5_pass
49911 Aborted (core dumped) | dorado demux --kit-name "SQK-NBD114-96" --emit-fastq --output-dir .

**Comment by sklages** [comment]
@Ciznetwork - not much I could answer here. let's see ..

1. not sure why you are selecting the route with an old tool on fastq data. `dorado` works fine on demux'ing (as a pipeline, starting from `pod5` data). Stick with `BAM` as long as you can, redemux'ing a `BAM` with `dorado` is fast and straightforward.
2. you found a solution.
3. this is what we do here with each and every run (*P2solo*): providing the `pod5` output folder for the run for basecalling/demultiplexing.

The error you have posted: if it worked before, what have you changed?

**Comment by Ciznetwork** [comment]
@sklages sorry for not reverting since that time. I have been trying to figure out my problems. So I found a way to make dorado basecall and then demux the pod5 into fastqs with this command: "dorado basecaller --device cuda:all --min-qscore 7 --no-trim --emit-fastq sup pod5folder | dorado demux --kit-name  --emit-fastq --output-dir ."
Presently, my downstream pipeline only takes in fastq files. If you know any other ways or tips to process bam files output from dorado  I will also be happy to try. 
Thanks for your time.

**Comment by sklages** [comment]
@Ciznetwork - many (most) downstream tools use fastq, nevertheless, BAM simply holds more information.

E.g. I do not use dorado's alignment command, instead I run mapping after basecalling as a separate step:
```bash
# samtools version >=1.16 
samtools fastq \
  --threads 8 \
  -T "*" \
  $BAM_BCL \
| minimap2 \
  <.. PARAMS ..>
  - \
| samtools sort \
  -m 2G \
  --threads 8 \
  -O BAM \
  -o $BAM_ALN \
  --write-index \
  --reference $REF_FSA \
  -
```

Piping `samtools fastq` to `minimap2` is not really slower than having the fastqs read by `minimap` directly. This way I have no intermediate fastq data. If your downstream program is not able to read from STDOUT for some reason, you'd need to write some intermediate fastq data as input for your program though (or give bash's command substitution a try, no idea how fast it is).
