### ISSUE TITLE
Jetson Orin Support

### ISSUE THREAD

**Issue by mcrone** [nanoporetech/dorado#36]
I was just hoping to get an update on Jetson Orin support. It was identified as being a focus just after the initial release of Dorado, but there has been no update since then. When are we likely to get support for the Jetson Orin?

**Comment by vellamike** [comment]
FYI @EpiSlim 

Hi @mcrone,

We are currently investigating how to get this to work. Apologies for the delay with this feature. If you have urgent work which this is blocking please write to us (mike dot vella at nanoporetech dot com).

**Comment by iiSeymour** [comment]
Initial jetson support is now available. @mcrone you can either build from source or try the `linux-arm64`.

You might need `openblas` for the precompiled build.

```
$ sudo apt install libopenblas0 
```
