### ISSUE TITLE
change stride config.toml file in dorado model

### ISSUE THREAD

**Issue by Marjan-Hosseini** [nanoporetech/dorado#360]
I want to change the stride value in config.toml from stride=5 to stride=1.
The reason I want to change the stride is because I want to infer the number of measurements before one base is called using basecaller. 
I run:

`dorado basecaller dna_r9.4.1_e8_sup@v3.3/ /pod5_files/ --recursive --emit-moves --modified-bases 5mCG_5hmCG -v > /bams/mod_stride1.bam`

This command works perfectly fine when the stride=5, but when I set stride=1 it always give me the following error:

```
[2023-09-04 13:56:06.365] [debug] - matching modification model found: dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0
[2023-09-04 13:56:06.367] [info] > Creating basecall pipeline
terminate called after throwing an instance of 'c10::OutOfMemoryError'
  what():  CUDA out of memory. Tried to allocate 7.55 GiB (GPU 0; 22.20 GiB total capacity; 14.77 GiB already allocated; 5.90 GiB free; 14.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at ../c10/cuda/CUDACachingAllocator.cpp:913 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7ffff7e5c4d7 in /home/downloads/dorado-0.3.2-linux-x64/bin/../lib/libc10.so)
frame #1: <unknown function> + 0x30bc5 (0x7ffff7eddbc5 in /home/downloads/dorado-0.3.2-linux-x64/bin/../lib/libc10_cuda.so)
frame #2: <unknown function> + 0x30ebe (0x7ffff7eddebe in /home/downloads/dorado-0.3.2-linux-x64/bin/../lib/libc10_cuda.so)
frame #3: <unknown function> + 0x3124e (0x7ffff7ede24e in /home/downloads/dorado-0.3.2-linux-x64/bin/../lib/libc10_cuda.so)
frame #4: <unknown function> + 0x19631d1 (0x7fffdffe51d1 in /home/downloads/dorado-0.3.2-linux-x64/bin/../lib/libtorch_cpu.so)
frame #5: at::detail::empty_generic(c10::ArrayRef<long>, c10::Allocator*, c10::DispatchKeySet, c10::ScalarType, c10::optional<c10::MemoryFormat>) + 0x14 (0x7fffdffdec14 in /home/downloads/dorado-0.3.2-linux-x64/bin/../lib/libtorch_cpu.so)
frame #6: at::detail::empty_cuda(c10::ArrayRef<long>, c10::ScalarType, c10::optional<c10::Device>, c10::optional<c10::MemoryFormat>) + 0x111 (0x7fff914c8ab1 in /home/downloads/dorado-0.3.2-linux-x64/bin/../lib/libtorch_cuda.so)
frame #7: at::detail::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0x31 (0x7fff914c8d81 in /home/downloads/dorado-0.3.2-linux-x64/bin/../lib/libtorch_cuda.so)
frame #8: at::native::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0x1f (0x7fff915cbe5f in /home/downloads/dorado-0.3.2-linux-x64/bin/../lib/libtorch_cuda.so)
....
```
My questions are:

1. Is this even possible to change the stride value on config.toml file?
2. Does this need more RAM? How should I figure out how much RAM I need?

**Comment by vellamike** [comment]
Hi, the stride needs to be correct for the model you are using, this is not something you should be changing.

> I want to infer the number of measurements before one base is called using basecaller.
I don't understand what you mean by this, could you explain in more detail what you are trying to accomplish?

**Comment by Marjan-Hosseini** [comment]
Thank you for your response!
I am trying to calculate translocation time per base, I used to basecall using an old version of albacore which would give me a move table like the following:

![XhTUF](https://github.com/nanoporetech/dorado/assets/45966768/f197c1f6-fb20-4dc2-b09f-b7ce29b34c37)

But because albacore stride is fixed to 5, I had to re-squiggle using Tombo to get something like (such that the number of measurements per base is different, and because in ONT sampling rate is fixed, I can compute translocation time in seconds):

![MdHhr](https://github.com/nanoporetech/dorado/assets/45966768/63308b46-168d-4f55-84bb-7dbedbb9fc9f)

Now I am trying to use move table produced by dorado for this purpose and avoid using Tombo for re-squiggling.

**Comment by vellamike** [comment]
The number of measurements per base in Dorado will be different, but it will have a granularity which is determined by the stride. Is the problem that the granularity too high for what you are trying to do?

**Comment by vellamike** [comment]
You don't need to set stride to 1 for this, just count the number of 1 and zero and multiply it by stride. For example 1,0,0 and stride=5 means 15 samples.

**Comment by Marjan-Hosseini** [comment]
But doen't setting stride=5 give less precision compared to if we have stride=1? Like all the translocation times will be multiples of 5.

**Comment by vellamike** [comment]
Yes, this is what I meant regarding granularity. If you need more precision than this it is an open research problem.

**Comment by Psy-Fer** [comment]
Hey. Just to chime in now it's been deemed an open research problem. 

You might get what you need using eventalign from f5c/nanopolish (https://github.com/hasindu2008/f5c)

And you can visualise this using squigualiser (https://github.com/hiruna72/squigualiser)

While squigualiser can use the the move table and stride, it can also use eventalign output from f5c.

The eventalign algorithm doesn't use a stride, it does its own even detection that would be equivalent to stride=1 so you can get the dwell time for each base.

I hope this helps, and please feel free to reach out to our team if you wanna chat more about this stuff.
Cheers,
James
