### ISSUE TITLE
Invalid signature in file

### ISSUE THREAD

**Issue by LauraSkak** [nanoporetech/dorado#362]
I'm working on a set of fast5 files that i would like to do basecalling on.

So far i've converted the fast5 files one by one to pod5 files using the pod5 software. If there is a clever way to way to merge all the fast5 files, so i only have to do one convertion; let me know. I took out a subset of 10 pod5 files each containing 4000 reads and ran the following;

dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.1.0 test_pod5s/ > test_calls.bam

This worked and gave me no errors. When i run the same command with all the pod5 files i

[2023-09-06 14:37:47.195] [error] Failed to open file <full path> /PAM26135_pass_35aa25e5_b919f884_1225.pod5: IOError: Invalid signature in file

and 

[2023-09-06 14:49:41.135] [error] Failed to open file <full path> /PAM26135_pass_35aa25e5_b919f884_1393.pod5: Invalid: null file passed to C API

what do these mean? how do i make it run?

**Comment by HalfPhoton** [comment]
Hi @LauraSkak ,

How did you generate the pod5 files which are causing issues? 

You shouldn't need to merge the fast5s into one file for conversion to pod5. You can do one conversion for a directory of fast5 files which will create one monolithic pod5 file: 

```bash
pod5 convert fast5 /directory/of/fast5s/ --output converted.pod5
```

You can also use the `--recursive` argument to search all sub-directories. [More examples in the documentation](https://pod5-file-format.readthedocs.io/en/latest/docs/tools.html#pod5-convert-fast5)

Best regards,
Rich

**Comment by HalfPhoton** [comment]
Hi @LauraSkak ,

Just to clarify a point here. You asked:
> If there is a clever way to way to merge all the fast5 files, so i only have to do one convertion; let me know

You can convert multiple fast5 files in a directory by passing the _directory_ to `pod5 convert fast5` to create one output. 

```bash
pod5 convert fast5 {directory_of_fast5s} --recursive -o {merged_output.pod5}
```
---

Your issue could be a corrupt / unusual fast5 file. 

Which `pod5` python version are you using - you can see this with `pod5 --version`. If it's not `0.2.4` please upgrade if possible by using `pip install -U pod5`

Can you try the following to resolve the issue:
- Inspect the fast5 files `PAM26135_pass_35aa25e5_b919f884_1225.fast5` and  `PAM26135_pass_35aa25e5_b919f884_1393.fast5` 
    - Are they empty / corrupt? 
    - They should be viewable in python with the `h5py` module which is a dependency of the `pod5` package so it should already be installed
 - Can you convert these files and try again? 

If there are issues in conversion, please exclude the fast5 files and re-try. If possible, we can arrange for you to send us any problematic fast5 files for us to inspect and resolve.

Kind regards,
Rich

**Comment by LauraSkak** [comment]
My pod5 files were corrupted :) I reran the the conversion and then it didn't complain :)

**Comment by HalfPhoton** [comment]
Thanks for the update @LauraSkak - closing as resolved

**Comment by wangziyuan66** [comment]
IOError: Invalid signature in file 

I also confront that issue but the pod files are directly from the Nanopore sequencer.

**Comment by HalfPhoton** [comment]
@wangziyuan66  - please create a new issue
