### ISSUE TITLE
ONT for guanine oxydation

### ISSUE THREAD

**Issue by revaoleg** [nanoporetech/dorado#365]
Hello!
May anybody suggets how to start with ONT sequences (pod5 files, bacterial DNA) to identify 5oxoG modifications? An expectation is that to base call files are free from 5oxoG and other two have these modifications. I cannot find any readily available models. How to do own model training?

**Comment by marcus1487** [comment]
We do not have a trained model for 5oxoG at this time. For model training I would recommend joining our [Betta developers group](https://community.nanoporetech.com/posts/betta-tool-release). You can also get started with [raw signal analysis using Remora](https://github.com/nanoporetech/remora#raw-signal-analysis-1). If you have any issues with Remora raw signal analysis please raise any issues there.
