### ISSUE TITLE
Only one strand of STR basecalled "properly" for a SCA31 case

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#366]
I am using dorado 0.3.2 to basecall my suspected genetic disease cases.
One of the cases is confirmed to have SCA31 which can be diagnosed
by TGGAA repeat flanked by TAAAA repeats in the BEAN1 gene.
https://omim.org/entry/612051?search=BEAN1&highlight=bean1

In this case, when I inspected the 9 reads haplotagged to be on the same
haplotype and have about 2000bp insertion, the repeats look like:
read sam_flag insertion_size STR_manually_counted
9f833ea4-3495-4244-86f5-761977b8199d    0       2209    (TAAAA)71(TGGAA)290
d7c29103-e6df-487b-8393-4e95f06471d0    0       2218    (TAAAA)20(TGGAA)420(TAAAA)30
f746426e-d976-41d5-a93b-9a9d7382cbc7    2048    2203    (TAAAA)17(TGGAA)412(TAAAA)32
06908984-2053-4a6f-a2a2-66c65efcaab5    16      2363    (TAAAA)12(GAAAA)10(TAAAA)9(GAAAA)386(TAAAA)2(GAAAA)61
78d799ba-0175-4e0e-b1ce-2f5a9c37f0e1    16      2168    (TAAAA)64(GAAAA)5(TAAAA)385
27db05a4-121c-4d8d-b5b5-6b51b5efc7a3    16      2236    (TAAAA)10(GAAAA)133(TAAAA)323
ced2a599-3123-47f9-8562-a302934c6735    16      2218    (TAAAA)102(GAAAA)144(TAAAA)216
51c32c9e-4913-45f8-a4f4-5eec48fa02de    16      2217    (TAAAA)29(GAAAA)133(TAAAA)299
179198bb-e045-48ab-8297-434a2fb41a74    16      2201    (TAAAA)22(GAAAA)258(TAAAA)175

Interestingly, I can see all three forward strand reads support TGGAA insertion repeat
whereas in the six on the reverse strand, they are all GAAAA insertion repeat. 

While the current form alerted me to use other technology to confirm, it would be great if dorado can
do better job in cases like this. I believe improvement in calling proper repeat on the other strand
can not only help in marginal cases but also helps people working in the T2T assembly area.

As to the instability in the repeat count for high copy STR, this phenomenon was observed
quite often in my experience, so I suppose it is also another area that can be improved.

**Comment by vellamike** [comment]
Hi,  apologies for the delay. Could you let me know which Kit version and basecalling model you are seeing this issue on?

**Comment by ymcki** [comment]
--basecaller_cfg 'dna_r10.4.1_e8.2_400bps_sup@v4.1.0' --remora_cfg 'dna_r10.4.1_e8.2_400bps_sup@v4.1.0_5mCG_5hmCG@v2'

Kit is LSK114 4kHz

**Comment by vellamike** [comment]
Hi @ymcki , do you have enough sample to rerun this with the 5kHz condition and evaluate on v4.3 models? We have made some substantial improvements to low-complexity regions with this condition and model and I think this might solve your issue.
