### ISSUE TITLE
Does duplex pairing work well for low-complexity PCR amplicons?

### ISSUE THREAD

**Issue by shenker** [nanoporetech/dorado#368]
I've been using dorado duplex to get high-quality reads for (mostly) low-complexity PCR amplicons (2-4kb are only one SNP or a couple of SNPs apart, for *most* of my samples there's also a 500bp high-complexity barcode region on the end).

1) For the vast majority of my samples that have that barcode region, would I be correct in assuming that duplex pairing will work essentially perfectly? (100x coverage, 4kb amplicons with 1M unique barcodes, ~140Gb PromethION run... each barcode is at least 30 SNPs apart from any other)
2) Previously I had assumed that duplex pairing would also work well for my samples without barcodes (purely low-complexity amplicons). I thought this was a supported use case for duplex reads, but reading this tweet thread (+ reply by @vellamike) made me concerned about duplex pairing performance in this regime (even in 0.3.4): https://twitter.com/vellamike/status/1696920400230285374?s=20. Given that, do you consider the pure low-complexity amplicon use case well-supported by dorado 0.3.4?
3) If not, do you anticipate near-term improvements in the pairing algorithm that will allow for good performance for this use case?
4) Alternatively, will high-duplex flow cells (supposedly coming in the next month or two?) largely mitigate this (by drowning out false pairs with true pairs) and I should just wait for them?

**Comment by vellamike** [comment]
Hi @shenker 

What duplex rates are you seeing?

> For the vast majority of my samples that have that barcode region, would I be correct in assuming that duplex pairing will work essentially perfectly? (100x coverage, 4kb amplicons with 1M unique barcodes, ~140Gb PromethION run... each barcode is at least 30 SNPs apart from any other)

We haven't tested this use case, and I would not be able to guarantee that this would work, especially with non high-duplex FCs. Are you able to test for the false +ve rate you are seeing? Duplex read names contain both parent read IDs, so it should be possible for you to compare those simplex sequences of the original simplex reads and compare barcodes.

We haven't added a feature to dorado to use barcode information to inform pairing decisions (although it would do this to some extent anyway as a side-effect of the pairing algorithm).

> Previously I had assumed that duplex pairing would also work well for my samples without barcodes (purely low-complexity amplicons). I thought this was a supported use case for duplex reads, but reading this tweet thread (+ reply by @vellamike) made me concerned about duplex pairing performance in this regime (even in 0.3.4): https://twitter.com/vellamike/status/1696920400230285374?s=20. Given that, do you consider the pure low-complexity amplicon use case well-supported by dorado 0.3.4?

No, low-complexity amplicon, especially short (<2kb) and without barcodes is not well-supported by 0.3.4, it's not something you should do for the time being.

> If not, do you anticipate near-term improvements in the pairing algorithm that will allow for good performance for this use case?

Yes. I think if we were to incorporate barcode information into the algorithm it would be especially effective. This is not something we are working on right now but we could prioritise it.

> Alternatively, will high-duplex flow cells (supposedly coming in the next month or two?) largely mitigate this (by drowning out false pairs with true pairs) and I should just wait for them?

HD flowcells will reduce the false-pair problem, but I would hesitate in saying that it would largely mitigate it without looking at some data myself

**Comment by shenker** [comment]
Hi @vellamike,

Apologies for the slow reply. I now have test cases across two MinION runs and three PromethION runs (all R10.4.1 non-HD) showing poor duplex pairing performance. This is a critical use case for us, so we'd love to hear any (non-binding!) guess you might have about when we could reasonably expect duplex pairing optimizations to ship (and/or when HD flowcells might become generally available. We were not approved for early access).

If it'd be useful, I'd be happy to send any and all data (pod5, dorado duplex bam, and/or read_id<->barcode table, subsetted or in full) that would be useful for testing the duplex algorithm.

## Results
For convenience, I've restricted my analysis to a subset of channels for each run (300-400k reads).
| Experiment   |   Total Reads |   Duplex Reads |   Mapped Reads |   Barcodes Match |   Duplex Rate |   Pair Mismatch Rate |
|--------------|---------------|----------------|----------------|------------------|---------------|----------------------|
| 230707_r (MinION)     |        299531 |          57020 |          45982 |            22957 |      0.190364 |             0.500739 |
| 230726_c (MinION)     |        427900 |         108070 |          82791 |            16439 |      0.252559 |             0.80144  |
| 230818_b (PromethION)     |        410515 |          89496 |          61425 |            10735 |      0.218009 |             0.825234 |
| 230818_r (PromethION)     |        329481 |          75409 |          61521 |            11704 |      0.228872 |             0.809756 |
| 230922_b (PromethION)     |        387231 |          50367 |          42031 |            27010 |      0.13007  |             0.357379 |

“Mapped Reads” refers to duplex reads where the duplex read and both parent reads all map to a complete barcode (spanning from bit 1 to bit 30, see below). “Barcodes Match” is the subset of mapped reads where the duplex read maps to the same barcode as each of its parent reads. “Duplex Rate” is Duplex Reads/Total Reads. “Pair Mismatch Rate” is Barcodes Match/Mapped Reads.

## Details
These are all 2-4kb amplicons. On one end is a 500bp barcode region divided into 30 segments of 15bp each. Each of the segments has 15bp ON variant and a 15bp OFF variant. The ON/OFF variants for all 30 bits comprise 60 15bp sequences which are highly dissimilar from each other. The non-barcode region of each amplicon should be very low complexity (for some runs this region will be fixed except for ~5-10 SNPs scattered across the ~2.5-3.5kb of non-barcode sequence). Basecalled using dorado 0.3.4 (model: dna_r10.4.1_e8.2_400bps_sup@v4.2.0). I use GraphAligner to map all reads to a GFA file representing the 30-bit barcode described above.

**Comment by shenker** [comment]
@vellamike (or anyone else) Just finished re-basecalling everything with dorado 0.4.0. Would appreciate your thoughts.

| Experiment   |   Total Reads |   Duplex Reads |   Mapped Reads |   Barcodes Match |   Duplex Rate |   Pair Mismatch Rate |
|--------------|---------------|----------------|----------------|------------------|---------------|----------------------|
| 230707_r (MinION)     |        352217 |         103557 |          78872 |            24276 |      0.294015 |             0.69221  |
| 230726_c (MinION)     |        470551 |         131284 |          99391 |            15929 |      0.279001 |             0.839734 |
| 230818_b (PromethION)     |        452817 |         115969 |          75390 |            10338 |      0.256106 |             0.862873 |
| 230818_r (PromethION)     |        346993 |          83325 |          65726 |            11516 |      0.240135 |             0.824788 |
| 230922_b (PromethION)     |        458990 |         105816 |          82372 |            29594 |      0.230541 |             0.640727 |

Differences that jump out to me:
- More total reads. I assume this is entirely due to simplex read splitting. But it's not a small increase from 0.3.4, so I'm not totally sure what's going on.
- Significantly more duplex reads (up to double). This increase seems almost entirely more false pairs, with little change in number of true pairs. Reading over the pairing algorithm in [read_pipeline/PairingNode.cpp](https://github.com/nanoporetech/dorado/blob/master/dorado/read_pipeline/PairingNode.cpp), it's clear why the pairing heuristics work well in general but terribly for amplicons.

I understand that for non-amplicon applications increasing duplex pair sensitivity may be good, but it's making a bad problem worse for my amplicon use case. In terms of output quality, it's fine to duplex basecall a bunch of false pairs since I can filter them out by looking at barcodes. But I'm worried that ~80% of GPU time spent on duplex decoding is wasted. (This is highly undesirable, GPU time is precious in academic settings!) Granted, I don't know how much GPU time is spent on duplex basecalling vs. simplex basecalling, so I'm not sure what the overall fraction of wasted GPU time is. Basecalling with 0.4.0 definitely took somewhat longer than 0.3.4 (I can look up runtime statistics if that would be useful).

1) Do these numbers look reasonable to you?
2) Do you think there's any risk that a high rate of false pairs may lead to missing a non-negligible number of true pairs? (I assume not, but wanted to ask.) If this is not a concern, then “fixing” duplex pairing for amplicons is purely motivated by runtime considerations, not the quality of the output (once false duplex pairs are filtered out).
3) Should we be worried about wasted GPU time given the high false pairing rate, or do you think that's a non-issue?
4) If you think there's room for improvement there, what do you think is the best path forward?
  - Maybe `dorado duplex` could be decomposed into simplex basecalling + duplex basecalling steps (similar to `duplex-tools`), in between those steps a user could manually align simplex reads to their custom barcodes and generate, say, a tsv file of read_id -> barcode (or read_id/ch -> barcode), which dorado could then use to filter pairs when duplex basecalling.
  - There may be an easier way of getting amplicons to work well by making minor tweaks to the existing pairing heuristics. For example, if there were CLI options to (1) turn off the “If the lengths are >98% similar and >5kb and delta<100ms -> pair” logic (2) set custom minimum overlap fraction and minimum mapping quality (minimap2) parameters. I'm just spitballing here, you'd know better than I. For my barcode design, the basic thing I want to check is that a read accurately matches its complement for 500bp on both ends.

I'm still looking forward to getting high duplex flowcells to test how that changes things.

**Comment by shenker** [comment]
Any thoughts @vellamike?

**Comment by tijyojwad** [comment]
Hi @shenker thanks for the detailed analysis!

> Do these numbers look reasonable to you?

From your comment I think you're suggesting that many of the false positives are coming from the "early acceptance criteria" check. That could indeed be true, and we can consider an option to disable that. This will force the alignment check for all pairs. So there will be a performance tradeoff for more specificity.

> Do you think there's any risk that a high rate of false pairs may lead to missing a non-negligible number of true pairs?

No, we should still be capturing all true positive pairs.

> Should we be worried about wasted GPU time given the high false pairing rate

If you're running duplex with SUP simplex, the duplex kernel itself doesn't add much overhead. With HAC model, it's more noticeable. Of course, reducing false positive pairs will reduce unnecessary compute which will improve overall performance.

> If you think there's room for improvement there, what do you think is the best path forward?

we have some improvements in the pipeline which will reduce false positive rate in general. `dorado duplex` also supports passing in a custom pairing file via the `--pairs` option. So you can already do what you're suggesting, which is 
* run simplex basecalling
* find pairs through custom script
* pass known pairs to Dorado duplex

**Comment by shenker** [comment]
@tijyojwad That's very helpful, thank you! For now I'll  switch to computing pairs myself and using `--pairs`. Will report back!
