### ISSUE TITLE
Error - no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by oneillkza** [nanoporetech/dorado#37]
I'm just trying out Dorado on our GPU cluster, and it seems to output many (tens of thousands for a single fast5 file so far) instances of the error message:

```
Error - no kernel image is available for execution on the device
```

It looks like this might be related to pytorch versions: https://github.com/pytorch/pytorch/issues/31285

nvidia-smi says the server I was running on has:      Driver Version: 460.84       CUDA Version: 11.2

**Comment by iiSeymour** [comment]
Hey @oneillkza can you also let us know what GPU you are seeing this with.

**Comment by oneillkza** [comment]
This is on a 1080 (maybe 1080Ti -- not 100% sure).

Would that be too old for Dorado? I know we found that some Titan RTX cards we had were too old for Guppy.

The rest of our GPU compute cluster has much more recent cards, mainly 3090s. I can see if Dorado works better one those.

**Comment by iiSeymour** [comment]
Ah yes the 1080 is Pascal which is too old - please do try on the 3090s.

**Comment by oneillkza** [comment]
Yep, seems to be working there. What architecture is the minimum required by Dorado? We do also have a handful of nodes with Turing cards (2080, RTX5000) on our cluster, although it's not the end of the world if we have to restrict Dorado to running on the 3090s.

**Comment by iiSeymour** [comment]
Volta onwards so Turing cards will also work.

**Comment by oneillkza** [comment]
Thanks!

Could I suggest mentioning this requirement in your documentation? I know it wasn't very well documented for guppy, and ended up causing us a lot of frustration when we tried to get it to work on the Titan GTXes. We had to find an obscure third-party blog post about it before figuring it out in that case ...

Otherwise it should be fine to close this issue. :)
