### ISSUE TITLE
Can I basecall 9.4.1/RAD004 files using Dorado? 

### ISSUE THREAD

**Issue by apredeus** [nanoporetech/dorado#370]
Dear Dorado team, 

I was wondering if it makes sense to basecall some old MinION 9.4.1/RAD004 fast5 files using Dorado, or should I use the latest Guppy? There doesn't seem to be a model for anything 9.4.1 except for Kit14. I've managed to run the basecalling successfully, but I'm not sure how much difference would it make. Also, there doesn't seem to be any Dorado-specific models in Medaka (although I did find this table: https://github.com/epi2me-labs/wf-bacterial-genomes/blob/master/data/medaka_models.tsv ) - should this be used to guide the model choice in Medaka? 

Thank you!

**Comment by tijyojwad** [comment]
Hi @apredeus - which guppy config did you initially run basecalling with?

The models dorado has for R9 are v3.3 (has and sup), v3.4 (fast) and v3.6 (sup). So if you ran with something older, then rebasecalling might help.

And yes, I believe that table is the right one to find the corresponding Medaka models.

**Comment by apredeus** [comment]
Hi @tijyojwad - I have used v3.6 sup. Does is make a difference that the model says "Kit14" but my experiment was done using older rapid kit? 

Thank you!

**Comment by JMencius** [comment]
Hi @apredeus I als want to run Dorado with Medaka, may I gently ask what is your latest finding?

**Comment by apredeus** [comment]
Hi @JMencius - so far I think everything worked quite nicely. I did a quick comparison of basecalls (some old Guppy reads I had and Dorado) by mapping them to the assembly, and the difference is pretty huge. So it re-basecalling was totally worth it; kit does not seem to matter as long as it's the right flowcell (9.4.1 in my case), and highest accuracy model (sup) is always better.

One thing I've read recently (from Ryan Wick) is that with the new flowcell and newest Dorado/sup model, Medaka is not needed anymore (he found it made things worse as often as improved them) - but that's mostly because Nanopore-only assemblies are very accurate in this case. 

Hope this helps

**Comment by vellamike** [comment]
Closing this issue as we are no longer releasing new versions of Guppy. Basecall accuracy is dictated by the basecalling model, rather than the basecaller.
