### ISSUE TITLE
Compatibility Question: Using Different Model Versions in Dorado Basecaller for DNA Modifications

### ISSUE THREAD

**Issue by PhiloVa** [nanoporetech/dorado#371]
Hi,

I have a question regarding model compatibility, specifically when working with different versions for DNA modifications
I attempted to run the following command for basecalling with Dorado using the dna_r9.4.1_e8_sup@v3.6 model:

`dorado basecaller dna_r9.4.1_e8_sup@v3.6 /pod5_folder/ --modified-bases 5mCG > unsorted.sam --reference genome.fna --emit-sam`

This failed as it does not automatically match a model.  I then tried specifying a model for modified bases using the --modified-bases-model flag, and it seemed to work:

`dorado basecaller dna_r9.4.1_e8_sup@v3.6 /pod5_folder/ --modified-bases-model r9.4.1_e8_sup@v3.3_5mCG@v0 > unsorted.sam --reference genome.fna --emit-sam`.

I noticed a significant difference in results (using modkit) between the two versions v3.3 (with string --modified-bases 5mCG) and v3.6 (as above). Specifically, there are about double the instances of 5mC when using v3.6 in this way.

Could the version mismatch be the reason for the significantly different counts of 5mC between the two versions, or is it that v3.6 is just much more accurate?

**Comment by tijyojwad** [comment]
Hi @PhiloVa - to check model compatibility between dorado and Medaka you can use this table - https://github.com/epi2me-labs/wf-bacterial-genomes/blob/master/data/medaka_models.tsv

Unfortunately that table doesn't list the `dna_r9.4.1_e8_sup@v3.6` model. That model was released as a one-off for a specific use case/customer, and therefore doesn't have equivalent support across other tools.

We expect the Medaka model `r941_e81_sup_g514` to work well with it, however we haven't explicitly tested that.

For modbasecallinfg, I would suggest using the same version between base calling and methylation calling. In your example, that would be `v3.3`
```
dorado basecaller dna_r9.4.1_e8_sup@v3.3 /pod5_folder/ --modified-bases 5mCG --reference genome.fna --emit-sam > unsorted.sam 
```
