### ISSUE TITLE
Feature request: Pick the right model for the data

### ISSUE THREAD

**Issue by adbeggs** [nanoporetech/dorado#375]
Can I ask for a feature in the next release? Can the correct model i.e. 4kHz, 5kHz, LSK-110 vs 114 etc be chosen for the data, and the only thing you have to decide is fast/hac/sup and mod vs. no mod... it gets pretty tedious to choose the correct model for Dorado when you're working with diverse historical datasets

**Comment by billytcl** [comment]
+1, I suggested it a few weeks back! https://github.com/nanoporetech/dorado/issues/349

To me this should be a pretty high priority as it reduces a lot of friction for new users.

**Comment by Psy-Fer** [comment]
I requested this in 2019 for guppy. Can't come soon enough in my opinion.

So +1

**Comment by tijyojwad** [comment]
Hi @adbeggs - thanks for raising this. Totally agree this is an impactful feature. We have a lot of things baking for the upcoming release (in a couple of weeks), so I'm not sure we'll be able to get this through in time. But we'll try our best, and if not then we'll prioritize it for the next patch release.

**Comment by eesiribloom** [comment]
at the very least more comprehensive list of e.g. which sequencing kit corresponds to which pore type etc. would be useful. especially for older data which might be sequenced on older kits /chemistries.

**Comment by HalfPhoton** [comment]
Auto model selection has been implemented in 0.5.0
