### ISSUE TITLE
Questions about DNA CS

### ISSUE THREAD

**Issue by Yijun-Tian** [nanoporetech/dorado#377]
Does dorado base calling consider the DNA control strand (the calibration DNA strand)? It seems that my quality scores are quite different between libraries with or without DNA CS.

**Comment by vellamike** [comment]
Hi, No - Dorado basecalling does not use the calibration DNA, if your quality scores are different between libraries with and without calibration DNA the cause is something else.

**Comment by Yijun-Tian** [comment]
Thanks, Mike. Seems our p2 solo device causes it.
