### ISSUE TITLE
Dorado runs out of RAM; is killed

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/dorado#379]
Hello. 

I'm working on setting up Dorado in AWS. 

I'm basing my set-up based on the blog post found here. 

https://aws.amazon.com/blogs/hpc/benchmarking-the-oxford-nanopore-technologies-basecallers-on-aws/

One instance that is the most cost-performant is the g4dn.xlarge, x64 based CPU, Tesla T4 GPU, 16GB of ram. 

I used only a few fast5 files converted to pod5, from the same dataset they used ( s3://ont-open-data/cliveome_kit14_2022.05/gdna/flowcells/ONLA29132/20220510_1127_5F_PAM63167_d3c6b017/fast5_pass/)  as an experiment to see that my dorado worked, which was installed using the binary found in the repo. 

The pod5 file size is like ~7GB. 

Here is my command:
dorado basecaller dorado-models/dna_r10.4.1_e8.2_400bps_hac@v4.1.0 benchmark-fast5s/converted/ --verbose --modified-bases 5mCG_5hmCG --reference references/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna > benchmark.5mCG_5hmCG.bam

[2023-09-19 16:07:24.158] [debug] - matching modification model found: dna_r10.4.1_e8.2_400bps_hac@v4.1.
0_5mCG_5hmCG@v2
[2023-09-19 16:07:24.158] [info] > Creating basecall pipeline
[2023-09-19 16:07:25.569] [debug] Auto batch size: GPU memory available: 15.450833GB
[2023-09-19 16:07:25.569] [debug] Auto batch size: testing up to 2079 in steps of 64
....
[2023-09-19 16:07:39.179] [debug] Auto batchsize cuda:0: 2048, time per chunk 0.20046282 ms
[2023-09-19 16:07:39.179] [debug] Device cuda:0 Model memory 3.551232
[2023-09-19 16:07:39.179] [debug] Device cuda:0 Decode memory 1.784832
[2023-09-19 16:07:39.224] [debug] - set batch size for cuda:0 to 768
[2023-09-19 16:07:39.229] [info] > Index parameters input by user: kmer size=15 and window size=10.
Killed

Killed occurring when RAM runs out. 

Is there a minimum RAM requirement or way to modify run to adapt to the ram limitations? 

Thank you!

Additional questions If anybody reading this was one of the authors of that blog:

1. It seems like in the results section it is stated that Guppy failed with this instance, but Dorado worked. Is it possible that actually this was reversed?
2. When I try using the command specified in the blog for running methylation
dorado basecaller \
    /usr/local/Dorado/models/dna_r10.4.1_e8.2_400bps_hac@v3.5.2 \
    ${file_list}/ \
    --modified-bases 5mCG | \
    --verbose | \
    samtools view --threads 8 -O BAM -o /fsx/out/&job_id&/calls.bam
I get: 
could not find matching modification model for dna_r10.4.1_e8.2_400bps_hac@v3.5.2

**Comment by sklages** [comment]
I don't know the minimum RAM requirements. 
RAM consumption can be (probably) reduced significantly by omitting the alignment part.
AFAICS the basecalling benchmarks have been run without alignment.

**Comment by vellamike** [comment]
@sklages is correct, these benchmarks don't include alignment which itself has a memory impact. You should try either running on a computer with more memory or performing alignment post-basecalling.
