### ISSUE TITLE
Can chimeric duplex reads exist in a simplex run?

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#380]
I found some reads from a LSK114 4kHz simplex run that looks like chimeric duplex reads

Some reads that looks like chimeric duplex reads I extracted from bam:
5adb583a-d4a1-4fbd-8bf6-94f9a5b71cbf 0 chr17 15015151 SA:Z:chr17,15015151,-,12S68347M773D69072S,60,2842;
edecc142-bf39-4f64-9b8c-7c9ebe56eb2f 0 chr17 15024312 SA:Z:chr17,15024312,-,13S10085M39D10171S,60,123;
8670694a-b80b-4cf7-821c-733d7a379a45 0 chr17 15063531 SA:Z:chr17,15063531,-,16S2971M25I3042S,60,76;
b7112b6f-a0cd-4bac-97a4-c551e2cc7767 0 chr17 15073307 SA:Z:chr17,15073307,-,11S963M5D998S,60,29;
c79a3a79-ee8c-4b59-b5c2-dcdde1fef198 0 chr17 15155116 SA:Z:chr17,15155116,-,13S1018M3D1518S,60,34;
e3631a54-e540-469b-9a2b-35688ad02494 0 chr17 15159393 SA:Z:chr17,15159393,-,12S407M21D550S,60,32;

Are these duplex reads?

**Comment by vellamike** [comment]
I'm not sure what you mean by "chimeric duplex reads" - would you mind elaborating on what you think the issue might be?

**Comment by ymcki** [comment]
For that I mean the forward and reverse strand of the same read are concatenated together in one read such that you are seeing first half of the read and second half of the read maps to the same place but at different directions with some extra bases in between (adapters?).

**Comment by vellamike** [comment]
Hi, Yes - this is indeed possible, I think your hypothesis is correct. Improved read splitting during simplex to prevent this issue is something we are adding to Dorado soon.

**Comment by tijyojwad** [comment]
Hi @ymcki - read splitting has been added to simplex as of dorado 0.4.0.
