### ISSUE TITLE
Will trimming the reads mess up MM/ML tags

### ISSUE THREAD

**Issue by weishwu** [nanoporetech/dorado#381]
I've run Dorado to do modbase calling in order to detect CpG methylation. Dorado output BAM which I then converted to FASTQ. I usually run NanoFilt to trim off the adapter-containing 5' (~40bp) and 3' (~20bp) ends before mapping and methylation calling. I wonder trimming after running Dorado will make the shortened read sequences incompatible with the info encoded in MM,ML tags. Thanks.

**Comment by ArtRand** [comment]
Hello @weishwu,

Indeed trimming the sequences will likely invalidate the MM/ML tags output by dorado. One option if you plan to use a tool like NanoFilt/Chopper is to follow up the trimming with `modkit repair` ([docs](https://nanoporetech.github.io/modkit/intro_repair.html)), which will project the original MM/ML tags onto the trimmed sequences.  You can always check if the MM/ML tags are correct by iterating through the BAM with [pysam modified bases](https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignedSegment.modified_bases) it will warn you if the tags are incorrect. `modkit` will do this as well in the logs when you use `summary` or a similar command. Hope this helps.

**Comment by weishwu** [comment]
@ArtRand Got it. Thanks!
