### ISSUE TITLE
Locating parent read IDs when using dorado duplex

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/dorado#384]
Sorry if this is documented somewhere or in an issue that I missed. But could not find an answer skimming through them.

1. I am wondering if it is possible to locate the parent read for split reads when using dorado duplex. When using Guppy with the read splitting option enabled, there was a FASTQ tag having this information. But such a tag doesn't seem to be there in the Dorado SAM output.

2. Also, are the readIDs generated for split reads deterministic? For instance, if I use Guppy with read splitting vs. Dorado with read splitting enabled duplex, are the corresponding split reads going to have the same IDs?

3. Also is the read splitting option available in Dorado simplex or when doing simplex through Dorado basecall server?

**Comment by vellamike** [comment]
> I am wondering if it is possible to locate the parent read for split reads when using dorado duplex. When using Guppy with the read splitting option enabled, there was a FASTQ tag having this information. But such a tag doesn't seem to be there in the Dorado SAM output.

Unfortunately this is not possible right now, but it is planned for a future release (soon).

> Also, are the readIDs generated for split reads deterministic? For instance, if I use Guppy with read splitting vs. Dorado with read splitting enabled duplex, are the corresponding split reads going to have the same IDs?

No, Guppy and Dorado will not produce the same split read IDs, although they are deterministic.

> Also is the read splitting option available in Dorado simplex or when doing simplex through Dorado basecall server?

It is not available via Dorado simplex yet (It is coming soon) but it _is_ available via Dorado Basecall Server if you use the `--do_read_splitting` option to the client.

**Comment by hasindu2008** [comment]
Thanks @vellamike for the quick response. If I use `--do_read_splitting` in the client, will those generated read IDs match the ones coming from duplex reads?

**Comment by vellamike** [comment]
Hi @hasindu2008 , no unfortunately they will be different. This is because under the hood the client will perform read splitting using a slightly different method from that which Dorado uses. However these will be unified in the future.

**Comment by tijyojwad** [comment]
Hi @hasindu2008 

re: `locate the parent read for split reads when using dorado duplex`

dorado [v0.4.0](https://github.com/nanoporetech/dorado/releases) (just released) now outputs parent read ids for split reads  in the `pi:Z:` tag
