### ISSUE TITLE
Model error using Dorado

### ISSUE THREAD

**Issue by olu2016** [nanoporetech/dorado#387]
Hi,

I used dna_r10.4.1_e8.2_400bps_sup@v4.2.0 in the following command :
`dorado duplex dna_r10.4.1_e8.2_400bps_sup@v4.2.0 pod5s/ > duplex.bam`

I got the folowing errors:
`[2023-09-29 12:46:04.483] [info] > No duplex pairs file provided, pairing will be performed automatically`
`[2023-09-29 12:46:04.509] [error] Sample rate for model (4000) and data (5000) are not compatible.`

Should I be using a different model?

Thanks

**Comment by susie-ont** [comment]
Hi @olu2016 ! The model `dna_r10.4.1_e8.2_400bps_sup@v4.2.0` is suitable for 5 kHz data, so you shouldn't be getting this error message. Could you please confirm the full command that you are using & the outputs you see?

**Comment by olu2016** [comment]
Hi @susie-ont , 

Here's my cmd:
`dorado duplex dorado_models/dna_r10.4.1_e8.2_400bps_hac@v4.2.0 pod5_folder/ > duplex.bam`

I got an output - duplex.bam (4.0k) and I'm not sure it's the expected output due t the small size.

**Comment by tijyojwad** [comment]
Hi @olu2016 - could you try deleting the model and re-downloading it?

**Comment by malton-ont** [comment]
> Note: It was not possible to download models using dorado download command, but we downloaded dna_r10.4.1_e8.2_400bps_hac@v4.2.0 using benito basecaller function (bonito download --models).

Bonito models are not compatible with dorado - you will need to download the model via dorado. You said you were unable to do so - could you provide the error messages for this?

**Comment by olu2016** [comment]
Hi @tijyowad and @malton-ont 

I have repeated the download using:
`dorado download --model dna_r10.4.1_e8.2_400bps_sup@v4.2.0`

and got this error:

`[2023-10-04 12:53:33.563] [info]  - downloading dna_r10.4.1_e8.2_400bps_sup@v4.2.0`
`terminate called after throwing an instance of 'elz::zip_exception'`
`what():  exception occured when opening archive './dna_r10.4.1_e8.2_400bps_sup@v4.2.0.zip'`
`Aborted (core dumped)`

**Comment by olu2016** [comment]
Hi @malton-ont,

I have write access and I have repeated the download command, but I got the same error.

**Comment by malton-ont** [comment]
@olu2016 Can you check the download location (which should be the working directory where you called dorado from) and examine any files there - possibly an incomplete download is in place which is preventing a new copy being created.

Also, are you behind a proxy? If so, you may need to point dorado at the proxy server by setting the environment variables `dorado_proxy` and `dorado_proxy_port`.

**Comment by olu2016** [comment]
Hi @malton-ont  we've been to download the model. Thanks. I would like to know if dorado can run without nvidia. I'm asking this question because, we tested dorado and got the following message about CUDA:

cmd:
`dorado duplex models/dna_r10.4.1_e8.2_400bps_hac@v4.2.0 pod5/ > ./test.bam`

messages:
`[2023-10-09 15:35:40.935] [info] > No duplex pairs file provided, pairing will be performed automatically`
`[2023-10-09 15:35:41.071] [error] CUDA device requested but no devices found.`

**Comment by malton-ont** [comment]
@olu2016 That's good - would you mind explaining what the solution was in case others come up against this issue?

Dorado can on CPU by passing the option `-x cpu`.

**Comment by olu2016** [comment]
We accessed "https://cdn.oxfordnanoportal.com/software/analysis/dorado" and downloaded models programmatically.

Please let me know if you want me to start a new issue.

My dorado run yielded no output:

cmd:
`dorado duplex models/dna_r10.4.1_e8.2_400bps_hac@v4.2.0 /pod5/ -x cpu > ./test.bam`

outputs:
`[2023-10-11 12:43:09.066] [info] > No duplex pairs file provided, pairing will be performed automatically`
`[2023-10-11 12:43:14.462] [info] > Starting Stereo Duplex pipeline`
`[2023-10-11 12:43:14.490] [info] > Reading read channel info`
`[2023-10-11 12:43:15.046] [info] > Processed read channel info`
`killed`

Any idea what went wrong?

**Comment by malton-ont** [comment]
@olu2016 Yes, please start a new issue. This looks like an out-of-memory issue though.
