### ISSUE TITLE
Is Remora part of Dorado?

### ISSUE THREAD

**Issue by BioRB** [nanoporetech/dorado#393]
Hello,
someone told me that remora is integrated inside dorado.
Is it true?
This thing looks confusing to me. 
Initially I thought dorado was a basecaller and remora was for the modifications. But now dorado has also the options for the modified bases.
Just for my knowledge, I would like to know if the remora script was absorbed inside dorado or if they are 2 different tools.
Inside remora README dorado is cited as an alternative for modification detection (the preferred procedure  actually)

**Comment by vellamike** [comment]
Dorado is Oxford Nanopore's production basecaller. It has the ability to detect modified bases during basecalling using the `--modified-bases` flag as per the [README](https://github.com/nanoporetech/dorado#modified-basecalling). Remora is the tool which we used to train the modified base models used in Dorado. Remora can also perform modified basecalling, but Dorado will be much faster and is the recommended too for most users.
