### ISSUE TITLE
Need clarification on running duplex reads

### ISSUE THREAD

**Issue by lihanchan** [nanoporetech/dorado#396]
I am confused on how to go about running duplex basecalling. Can I run duplex basecalling with the pod5 raw files directly?

Thanks!

**Comment by sklages** [comment]
Sure, https://github.com/nanoporetech/dorado#duplex

**Comment by lihanchan** [comment]
Was confused because of what is stated in this page (https://community.nanoporetech.com/info_sheets/kit-14-device-and-informatics/v/k14_s1019_v1_revj_29jun2022/basecalling-kit-14-duplex-data), specifically the line "Using [Dorado](https://github.com/nanoporetech/dorado), re-basecall your simplex data with the following command to output simplex and duplex reads using the super-accurate (SUP) basecalling model."

From reading the github and running the code, I can directly do duplex basecalling from the raw pod5 data.

**Comment by sklages** [comment]
But the community page you provided states just the same as the github page: `dorado duplex dna_r10.4.1_e8.2_400bps_sup@v4.1.0 pod5s/ > duplex.bam`. So I am afraid I don't understand your confusion ..

**Comment by lihanchan** [comment]
I was confused on which pod5 file to input, but now it is resolved, thanks!
