### ISSUE TITLE
Download models code 200

### ISSUE THREAD

**Issue by husamia** [nanoporetech/dorado#40]
When I run the windows executable for dorado to download a specific model. or even all models using or not using --directory option the files are no where to be found in the folder. 

Command:
`c:\dorado-0.0.1+4b67720-win64\bin>dorado.exe download --directory C:\dorado-0.0.1+4b67720-win64\models --model dna_r9.4.1_e8_sup@v3.3`

output
` downloading dna_r9.4.1_e8_sup@v3.3 [200]
`
does this [200] mean the models were or were not downloaded?

**Comment by oneillkza** [comment]
In general, code 200 in an HTTP request means a successful download.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200

**Comment by husamia** [comment]
There are no files created in the folder. Whats the URL for the config
files, I might download them some other way.

**Comment by iiSeymour** [comment]
@husamia I suspect we have a Windows path issue; I will take a look.

The URLs can be found here https://github.com/nanoporetech/dorado/blob/master/dorado/models.h

**Comment by iiSeymour** [comment]
Model downloading on Window was fixed in 9caa9642b34d0961554b49f5445f399d93f52d40

**Comment by vellamike** [comment]
@husamia  this has been fixed with the[ release of Dorado v.0.0.2](https://github.com/nanoporetech/dorado/releases/tag/v0.0.2)
