### ISSUE TITLE
Dorado Windows Binary Verbose problem

### ISSUE THREAD

**Issue by husamia** [nanoporetech/dorado#400]
The Dorado on Windows Command Line shows a scrolling output that doesn't look good. How can I fix it?

C:\dorado-0.3.4-win64\bin\dorado.exe  basecaller --batchsize 96 --recursive --emit-fastq --device cuda:all C:\dorado-0.3.4-win64\bin\dna_r10.4.1_e8.2_400bps_sup@v4.2.0 D:\ONT\PGx_Twist_UDI\raw_combined_pod5 > D:\ONT\PGx_Twist_UDI\dorado_0.3.4_r10_400bps_SUP_v4.2.0.fastq

<img width="640" alt="image" src="https://github.com/nanoporetech/dorado/assets/13439952/973a95ed-33a8-43fb-9310-f2d9fba08bf8">

**Comment by MarkBicknellONT** [comment]
Hi @husamia ,

Thank you for reporting this issue - can you confirm the version of Windows that you are running on please? (e.g. Windows 10 or 11)

Thanks,
Mark

**Comment by husamia** [comment]
@MarkBicknellONT indeed it's Windows 11 issue

**Comment by husamia** [comment]
after sometime the progress bar stops however, it seems that basecalling is still on going evident by the output file being written

![image](https://github.com/nanoporetech/dorado/assets/13439952/bce0ed07-f270-4435-8c8a-49de4a89ec78)

**Comment by MarkBicknellONT** [comment]
Hi @husamia ,

I did manage to reproduce this in Windows 11 only locally, using 0.3.4.  However if I test 0.4.0 on Windows 11, it is no longer happening. If you upgrade to the latest version the problem should go away.

Kind regards,
Mark

**Comment by husamia** [comment]
@MarkBicknellONT I am still having the same issue with Windows 11 and binary build for 0.4.2 

was the issue resolved for the Windows 11 binary for sure?

**Comment by MarkBicknellONT** [comment]
Hi @husamia ,
I checked again with the 0.4.2 release build on my windows 11 development machine, in case we had reintroduced the problem:

git bash:
```
user@host MINGW64 /c/mbicknell/dorado-0.4.2-win64
$ ./bin/dorado basecaller dna_r10.4.1_e8.2_400bps_fast@v4.2.0 ../data/ > ../out.042.bam
[2023-11-09 17:12:12.740] [info] > Creating basecall pipeline
[2023-11-09 17:12:22.690] [info]  - set batch size for cuda:0 to 1920
[==============================] 100% [00m:03s<00m:00s]
[2023-11-09 17:12:27.379] [info] > Simplex reads basecalled: 4003
[2023-11-09 17:12:27.379] [info] > Basecalled @ Samples/s: 4.772192e+07
[2023-11-09 17:12:27.393] [info] > Finished

user@host MINGW64 /c/mbicknell/dorado-0.4.2-win64

```

cmd:
```
C:\mbicknell\dorado-0.4.2-win64>.\bin\dorado basecaller dna_r10.4.1_e8.2_400bps_fast@v4.2.0 ..\data > ..\out.042_cmd.bam
[2023-11-09 17:15:43.911] [info] > Creating basecall pipeline
[2023-11-09 17:15:54.084] [info]  - set batch size for cuda:0 to 1920
[==============================] 100% [00m:03s<00m:00s]
[2023-11-09 17:15:58.712] [info] > Simplex reads basecalled: 4003
[2023-11-09 17:15:58.713] [info] > Basecalled @ Samples/s: 4.821870e+07
[2023-11-09 17:15:58.741] [info] > Finished

C:\mbicknell\dorado-0.4.2-win64>
```

powershell:
```
PS C:\mbicknell\dorado-0.4.2-win64> .\bin\dorado basecaller dna_r10.4.1_e8.2_400bps_fast@v4.2.0 ..\data > ..\out.042_ps.bam
[2023-11-09 17:17:31.238] [info] > Creating basecall pipeline
[2023-11-09 17:17:41.440] [info]  - set batch size for cuda:0 to 1920
[==============================] 100% [00m:06s<00m:00s]
[2023-11-09 17:17:48.737] [info] > Simplex reads basecalled: 4003
[2023-11-09 17:17:48.737] [info] > Basecalled @ Samples/s: 3.057852e+07
[2023-11-09 17:17:48.760] [info] > Finished
PS C:\mbicknell\dorado-0.4.2-win64>
```
I seem to get the correct behaviour in each case, the same as when I tested 0.4.0.  Perhaps the issue is caused by a difference in win11 version between your machine and ours, or a locale change?  According to the System>About dialog my Windows Edition is "Windows 11 Pro" and Version is "22H2".  The region settings may also be having an effect - I am running with region set to format "English (United Kingdom)". 

Have you tried running in git bash or Powershell to see if you get the same issue there?

Thanks for your patience while we debug this,
Mark

**Comment by husamia** [comment]
@MarkBicknellONT Thank you for checking, Windows 11 22H2 is what I have. 

I think it could be a specific settings for the powershell. This Windows 11 was an upgrade not a clean install it could have picked up wrong PowerShell environment settings. This is the Windows shell. If there is way to rest it I will try that

**Comment by husamia** [comment]
@MarkBicknellONT 
I recently started using Dorado dorado-0.5.0-win64 on Windows 11 

I open the command line in Windows and run basecalling command. I had not encountered the issue but today I am encountering the issue again

I am wondering if this has to do with this https://github.com/microsoft/terminal/issues/15654
