### ISSUE TITLE
How to check the model's architecture

### ISSUE THREAD

**Issue by aCoalBall** [nanoporetech/dorado#402]
Hi there,

I have downloaded some models of Dorado. Like
`dna_r10.4.1_e8.2_400bps_sup@v4.1.0
dna_r10.4.1_e8.2_400bps_sup@v4.1.0_5mCG_5hmCG@v2
dna_r10.4.1_e8.2_400bps_sup@v4.2.0
dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v2
dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mC@v2
dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v2
dna_r10.4.1_e8.2_4khz_stereo@v1.1
dna_r10.4.1_e8.2_5khz_stereo@v1.1
`

What is the format of these files and how to check the model's architecture?

Thanks in advance.

**Comment by HalfPhoton** [comment]
@aCoalBall,
The model architecture for models is described in the `config.toml` file in each of the downloaded model directories. 
Alternatively for full details the dorado source code describes the model architectures. Links to: [simplex] and (https://github.com/nanoporetech/dorado/blob/release-v0.5.3/dorado/basecall/CRFModel.cpp#L814) [modbase](https://github.com/nanoporetech/dorado/blob/release-v0.5.3/dorado/modbase/ModBaseModel.cpp#L137) model architecture definitions. 

The files are [pytorch tensors](https://pytorch.org/docs/stable/notes/serialization.html#saving-loading-tensors)

Kind regards,
Rich
