### ISSUE TITLE
Barcode demultiplexing instructions are not working

### ISSUE THREAD

**Issue by vdruelle** [nanoporetech/dorado#403]
Dear all,

I tried using the barcode demultiplexing from the 0.4.0 Dorado release. I managed to generate the .bam file as explained in the README `dorado basecaller <model> <reads> --kit-name <barcode-kit-name>`.

I then wanted to split the reads from the .bam file following the instruction `samtools split -u <basecalled-bam> -f <output-dir>/<prefix>_%!.bam` but this just does not seem to work. 

Using it as explained I get the error `-bash: !.bam: event not found`, which can be fixed by using  `samtools split -u <basecalled-bam> -f <output-dir>/<prefix>_%\!.bam` to escape the `!`. With this "fixed" command I get a new error `samtools split: Invalid number of arguments: 0`, which by looking at the --help for the `samtools split` command is because we never define an input file ?

Running `samtools split test_data/tmp/dorado_raw/basecalled.bam -f barcode_%\!.bam` instead seems to give an output file where all the reads are present, so it's doing much.

Could you please fix the instructions on how to properly split the reads by barcodes ? Right now it seems I cannot achieve this goal. I am using the latest version of samtools (v1.18).

Best,
Valentin

**Comment by vdruelle** [comment]
I tried the command and it did seem to split things by barcode but the names are really messy. Here is what I get when I `ls` in the output folder:
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0.bam                          rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode13.bam
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode01.bam  rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode14.bam
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode02.bam  rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode15.bam
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode03.bam  rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode16.bam
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode04.bam  rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode17.bam
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode05.bam  rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode18.bam
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode06.bam  rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode19.bam
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode07.bam  rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode20.bam
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode08.bam  rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode21.bam
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode09.bam  rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode22.bam
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode10.bam  rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode23.bam
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode11.bam  rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode24.bam
rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0_SQK-RBK114-24_barcode12.bam  unclassified.bam

It looks like it got the full name (I noticed the RG:Z: argument in the .bam files has a lot of stuff inside). For this reason all of them have an RG:Z argument and the unclassified reads end up in `rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0.bam ` instead of `unclassified.bam`

**Comment by tijyojwad** [comment]
> Running samtools split test_data/tmp/dorado_raw/basecalled.bam -f barcode_%\!.bam instead seems to give an output file where all the reads are present, so it's doing much.

what is the name of the output file generated?

since you have the BAM file generated, can you spot check if there are read entries with the `BC:Z` tag?

**Comment by tijyojwad** [comment]
okay thank you! So it looks like that's doing the right now, i.e. splitting reads out into corresponding BAMs.

Unfortunately, the `samtools split` just uses the read group name as the suffix of the file. So names are messy...

There's also a demux cmd in dorado itself which you can run on your basecalled BAM file. But that's meant for files which haven't been demuxed/trimmed before.

```
$ dorado demux --kit-name <kit-name> --output-dir <output-folder-for-demuxed-bams> <reads>
```

**Comment by vdruelle** [comment]
I figured that using `samtools split {input} -f '{output.directory}/barcode_%#.bam'` (notice the %# instead of %!) gives much nicer names. When I type `ls`:

barcode_10.bam  barcode_12.bam  barcode_14.bam  barcode_16.bam  barcode_18.bam  barcode_1.bam   barcode_21.bam  barcode_23.bam  barcode_2.bam  barcode_4.bam  barcode_6.bam  barcode_8.bam  barcode_0.bam
barcode_11.bam  barcode_13.bam  barcode_15.bam  barcode_17.bam  barcode_19.bam  barcode_20.bam  barcode_22.bam  barcode_24.bam  barcode_3.bam  barcode_5.bam  barcode_7.bam  barcode_9.bam

The barcode 0 seems to be the unclassified files, but since it comes from the original `BC:Z` I think the `0` corresponds to the last character of the full `BC:Z` (`rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0`) which is the last digit of the version. So I would say that fixes the issue but I fear it might merge the unclassified reads with other barcodes as soon as the version switches from 4.2.0 to 4.2.1.

Maybe it would be a good idea to improve this to make it more robust ?

**Comment by tijyojwad** [comment]
oh very nice! I didn't know about the `%#` instead of `%!`. that's definitely much nicer :).

Can you add the `-u <outdir>/unclassified.bam` option and try? I think that will separate out unclassified ones from barcode 0 as well.

**Comment by tijyojwad** [comment]
Actually going through the docs `%#  = @RG index`. Unclassified ones will have a separate read group than the classified barcodes. so they should have a separate index I would think

**Comment by tijyojwad** [comment]
also our barcode numbers start from `01`, not `00`. so I think `0` in your example corresponds to the unclassified ones

**Comment by vdruelle** [comment]
Yes it indeed looks like the barcode 0 corresponds to the unclassified reads, but not for the right reason. When looking at the RG:Z from the reads it looks something like `rg_3d1c37f25842269f4cd968346582d75e87acd252_dna_r10.4.1_e8.2_400bps_sup@v4.2.0`, sometimes with `barcode_X` added at the end if a barcode was detected.

I fear that when using `%#` the barcode is extracted if it's there (as expected), but if it is not there the last digit of the RG:Z tag is extracted (from `v4.2.0` in this case). This would mean that when the version of the model changes, let's say to 4.2.1, these unclassified reads could be merged with barcode 1 (because now the last digit is also 1). This would be a very annoying thing, so I would ask you to handle this properly so things are clearly separated in their respective barcode or unclassified file, in a way that is robust to future updates.

Let me know if my explanation is not clear, I am trying my best but the issue is not easy to describe.

**Comment by tijyojwad** [comment]
Hi @vdruelle - According to the docs `%#  = @RG index`, so it's just an index enumerating the different read groups starting from 0 to num_read_groups.

The read group without the barcode is the first one in the header, so it has index 0. And then rest of them follow. Now of course the order of read groups isn't guaranteed, so `unclassified` may not always map to `0`.

We also just released dorado v0.4.1 which has new functionality in `dorado demux` to split a barcoded BAM into separates BAMs without rerunning classification.
```
$ dorado demux -o <output-dir> --no-classify <input-bam>
```

This should handle your use case more cleanly.

**Comment by vdruelle** [comment]
I updated the pipeline to use `dorado demux` instead. It works like a charm, thanks !
Minor thing: I think there is something wrong in your README. The argument `-o` does not seem to exist for `dorado demux`. It looks like one should use `--output-dir`.

**Comment by tijyojwad** [comment]
Ah good shout! Adjusted the README.
