### ISSUE TITLE
All modifications in single output

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/dorado#404]
Hello,

Is it possible to basecall all modifications in all contexts and output the results into a single BAM file?

Thank you.

**Comment by tijyojwad** [comment]
Hi @Ge0rges ,

In dorado if you run with mod bases it will call these modifications and write the output into a single stream/file. Is that what you're looking for?

e.g.
```
$ dorado basecaller <basecall_model> <data> --modifed-bases 6mA 5mCG_5hmCG > output.bam
```
`output.bam` will have the basecalled records with mod tags for all identified mods
