### ISSUE TITLE
Use a samplesheet

### ISSUE THREAD

**Issue by stefandiederich** [nanoporetech/dorado#405]
Dear all,

now that the new version of dorado is there, I was wondering if there is a possibility to use a samplesheet like described here 
https://community.nanoporetech.com/docs/prepare/library_prep_protocols/experiment-companion-minknow/v/mke_1013_v1_revcx_11apr2016/sample-sheet-upload to feed into dorado. 

So you do not need to specify any kit name and you will get one fastq per sample with the "alias" as a name. 

Bests
Stefan

**Comment by tijyojwad** [comment]
Hi @stefandiederich - thanks for the request! This is part of our development plan already and will be available in an upcoming release.

**Comment by stefandiederich** [comment]
Hi @tijyojwad 
thanks for your quick response. 
Is there an approximate time known?
Bests
Stefan

**Comment by iiSeymour** [comment]
Hey @stefandiederich we just released [v0.4.2](https://github.com/nanoporetech/dorado/releases/tag/v0.4.2) which has initial support for sample sheet aliasing.
```
$ dorado basecaller --kit-name SQK-RBK114-96 --sample-sheet <path> ...
$
$ dorado demux --kit-name SQK-RBK114-96 --sample-sheet <path> ...
```

**Comment by stefandiederich** [comment]
Hey @iiSeymour, 
thanks for the information. I will test this in the next days!

Bests
Stefan

**Comment by MustafaElshani** [comment]
What would be the header for sample_sheet ?
`flow_cell_id`
`position_id`
`sample_id`
`experiment_id`
`flow_cell_product_code`
`kit`
`barcode`

Given the `sample_id` and `barcode` does dorado sort sample_id into folder based on barcoding, or do we still have to `cat` `fastq` for each sample for downstream analysis. Any further information is appreciated

**Comment by MustafaElshani** [comment]
I think I got my answers at [SampleSheets.md](https://github.com/nanoporetech/dorado/blob/master/documentation/SampleSheets.md)

does `dorado basecaller` multiplex or do have have to through `dorado demux`?

**Comment by MostafaYA** [comment]
Hi, 

Thanks for this implementation. 

Does it work also for `duplex`? I tried and there was no errors.   
Also when ommiting `--kit-name SQK-RBK114-96 --sample-sheet` in the `basecaller` subcommand, things seem to work fine afterwards with `dorado demux calls.bam --sample-sheet ... `

```
dorado duplex -r <model> <seq_dir>  > calls.bam
```

````
dorado demux calls.bam --sample-sheet  <path> --output-dir <dir> --kit-name SQK-NBD114-24 --emit-fastq
````

Best

**Comment by tijyojwad** [comment]
Barcoding for `duplex` isn't implemented yet. If you run the demux cmd on output of `duplex`, it'll only classify the simplex reads and the duplex reads will likely all end up unclassified.

**Comment by victorLLA** [comment]
Hi ! Is this still the case with the 0.5.0 version of dorado ? 0.5.1? 

bests

**Comment by victorLLA** [comment]
> Barcoding for `duplex` isn't implemented yet. If you run the demux cmd on output of `duplex`, it'll only classify the simplex reads and the duplex reads will likely all end up unclassified.

Hi ! Is this still the case with the 0.5.0 version of dorado ? 0.5.1?

bests

**Comment by susie-ont** [comment]
Hi @victorLLA - yes, this is still the case. Dorado does not yet support barcoding for `duplex` as of 0.5.1. This is on our roadmap for later this year.
