### ISSUE TITLE
[error] Failed to open Pod5 files 

### ISSUE THREAD

**Issue by setshabaTaukobong** [nanoporetech/dorado#407]
Hi there, I am trying to run Dorado however I am getting the following error:

(base) SFT000060:Desktop setshaba.taukobong$ sh bash-script-2.sh 
[2023-10-11 17:05:26.625] [info] Assuming cert location is /etc/ssl/cert.pem
[2023-10-11 17:05:26.627] [info]  - downloading dna_r10.4.1_e8.2_400bps_hac@v4.1.0 with httplib
working with file /Users/setshaba.taukobong/Desktop/pod5/PAQ82022_pass_223d1296_09eda14b_0.pod5
base name is PAQ82022_pass_223d1296_09eda14b_0
[2023-10-11 17:05:28.204] [info] > Creating basecall pipeline
[2023-10-11 17:05:28.206] [error] Failed to open file /Users/setshabataukobong/Desktop/pod5/PAQ82022_pass_223d1296_09eda14b_0.pod5: IOError: Failed to open local file '/Users/setshabataukobong/Desktop/pod5/PAQ82022_pass_223d1296_09eda14b_0.pod5'. Detail: [errno 2] No such file or directory
[2023-10-11 17:05:28.206] [error] Unable to determine sample rate for data.

Could I please get some assistance on this. Thank you

**Comment by sklages** [comment]
How does your actual `dorado` call look like? I just see that your are calling `bash-script-2.sh`.

**Comment by iiSeymour** [comment]
@setshabaTaukobong I think the path you are providing is incorrect. Note the first output from your script `/Users/setshaba.taukobong` has a `.` in your path but the output from dorado is missing this `/Users/setshabataukobong/`.

**Comment by setshabaTaukobong** [comment]
Hi @iiSeymour, thank you for responding to my query. I have fixed this issue however now I am getting this error (Im assuming Im using the incorrect model):
[2023-10-11 20:19:09.415] [error] Sample rate for model (4000) and data (5000) are not compatible.
bash-script-2.sh: line 24: $fastnew: ambiguous redirect

**Comment by setshabaTaukobong** [comment]
Hi @sklages, thank you for responding to my query.  please see below screenshot.
<img width="1470" alt="Screenshot 2023-10-11 at 20 38 23" src="https://github.com/nanoporetech/dorado/assets/84866754/f9ed0fe4-c860-4320-83ad-ebd781d0fc3a">

**Comment by tijyojwad** [comment]
@setshabaTaukobong since your data is 5KHz, you need to use a `v4.2.0` model for basecalling.

Here's a helpful table that maps basecalling sampling rate to compatible models - https://github.com/nanoporetech/dorado#dna-models

**Comment by sklages** [comment]
@setshabaTaukobong - the two commands after `dorado` will probably give you the next headaches AFAICS .. swap `$fastnew` and `$fastqnew`.  The cat command inside the loop is very inefficient ..

You should consider giving your variables in your script meaningful and distinguishable names.

Why don't you run `dorado` simply on the pod5 folder (without looping). If you don't need the BAM files you can also use `--emit-fastq` .
