### ISSUE TITLE
unable to open run dorado

### ISSUE THREAD

**Issue by LEGMCGILL** [nanoporetech/dorado#409]
Hello community,

I am quite new to bioinformatics in general and I am now in the process of basecalling with Dorado, I manage to install the latest version of it through the command line, but when trying the basic suggested commands to get me started as suggested: dorado -h and dorado <subcommand> -h
All I am getting is a message saying dorado: command not found. 

Therefore I havent even tried to Download any model to do my basecalling, any suggestion, is there some steps  that I still need to follow. Thanks for your help, is very much appreciated.

Laura.

**Comment by malton-ont** [comment]
@LEGMCGILL - to call dorado just via name requires that it is in your `PATH`. If you haven't configured this, try using the full path to the location of the dorado executable. For example, if you have installed dorado in /home/laura/dorado-0.3.4, use:
```
/home/laura/dorado-0.3.4/bin/dorado -h
```

**Comment by LEGMCGILL** [comment]
Oh thank you so much that actually worked for me
