### ISSUE TITLE
barcode_score in dorado 0.4.0

### ISSUE THREAD

**Issue by musquita** [nanoporetech/dorado#410]
In the newest dorado version, how does the barcode scoring works?
previously in guppy_barcoder we were able to setup different minimum scores to consider valid barcode alignment
not sure how can we change this with dorado now
thank you

**Comment by tijyojwad** [comment]
HI @musquita - barcoding scoring works in a similar but slightly different way to `guppy_barcoder`. Both alignment scores for the barcode and the barcode flanks are considered for classification.

The parameters to tune those are not exposed yet. Are you seeing too few classifications with the default settings?

**Comment by musquita** [comment]
No, just asking due to the optimization we were running, wondering if I could do it with this new version (and not dorado + guppy as before)
We were testing the effect of changing the barcode score when multiplexing as we wanted to make sure that potential barcode leakage was reduced to a minimum (as sometimes we run samples from the same species).

**Comment by musquita** [comment]
> HI @musquita - barcoding scoring works in a similar but slightly different way to `guppy_barcoder`. Both alignment scores for the barcode and the barcode flanks are considered for classification.
> 
> The parameters to tune those are not exposed yet. Are you seeing too few classifications with the default settings?

No, just asking due to the optimization we were running, wondering if I could do it with this new version (and not dorado + guppy as before)
We were testing the effect of changing the barcode score when multiplexing as we wanted to make sure that potential barcode leakage was reduced to a minimum (as sometimes we run samples from the same species).

**Comment by tijyojwad** [comment]
Understood, thanks for the details! There's a `--barcode-both-ends` option which can help with that (but this only works for double ended barcodes of course).

We are constantly optimizing the parameters to improve classification. If you notice poor classification/leakage with particular barcode kits, please let us know
