### ISSUE TITLE
cmake not working, CUDA 10.1.243, but different version with nvcc and nvidia-smi

### ISSUE THREAD

**Issue by BastianBrauer** [nanoporetech/dorado#411]
Hi, I'm trying to build dorado, but i get this message

~/dorado$ cmake -S . -B cmake-build
-- Build type: Release
-- Found CUDA 10.1.243 (/usr -> /usr)
-- Submodule update
CMake Error at cmake/Koi.cmake:18 (message):
  Unsupported CUDA toolkit version: 10.1.243
Call Stack (most recent call first):
  cmake/Koi.cmake:45 (get_best_compatible_koi_version)
  CMakeLists.txt:45 (include)

and when i check cuda toolkit version with 

nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

and with:

nvidia-smi
       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060        On  | 00000000:07:00.0  On |                  N/A |
|  0%   37C    P2              21W / 170W |   1242MiB /  8192MiB |      3%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1120      C   ...t/dorado/bin/dorado_basecall_server      934MiB |
|    0   N/A  N/A      2013      G   /usr/lib/xorg/Xorg                          107MiB |
|    0   N/A  N/A      2239      G   /usr/bin/gnome-shell                         47MiB |
|    0   N/A  N/A      4956      G   /usr/lib/firefox/firefox                    139MiB |
+---------------------------------------------------------------------------------------+

So, i dont know what is happenning and I really want to use dorado to basecall some sequences, hope you can help me.

Greetings

Bastián

**Comment by tijyojwad** [comment]
Hi @BastianBrauer - 

The build logs indicate that cmake is finding an older CUDA toolkit
```
Found CUDA 10.1.243 (/usr -> /usr)
```

Most likely the toolkit you want to use is in `/usr/local/cuda-11`. So you can explicitly pass that path to the `cmake` cmd like this
```
$ cmake -DCUDAToolkit_ROOT=/usr/local/cuda-11 -S . -B cmake-build
```

However, if you just want to use `dorado` run basecalling, you can just download one of the pre-built binaries from https://github.com/nanoporetech/dorado/tree/master#installation .

**Comment by BastianBrauer** [comment]
Hi, @tijyojwad thanks for your help!

I run that command and I still get this error...

`~/dorado$ cmake -DCUDAToolkit_ROOT=/usr/local/cuda-11 -S . -B cmake-build
-- Build type: Release
-- Found CUDA 10.1.243 (/usr -> /usr)
-- Submodule update
CMake Error at cmake/Koi.cmake:18 (message):
  Unsupported CUDA toolkit version: 10.1.243
Call Stack (most recent call first):
  cmake/Koi.cmake:45 (get_best_compatible_koi_version)
  CMakeLists.txt:45 (include)


-- Configuring incomplete, errors occurred!
`

**Comment by BastianBrauer** [comment]
Hi @tijyojwad , thanks for your help but when I run that command, I get the error too.

```
~/dorado$ cmake -DCUDAToolkit_ROOT=/usr/local/cuda-11 -S . -B cmake-build
-- Build type: Release
-- Found CUDA 10.1.243 (/usr -> /usr)
-- Submodule update
CMake Error at cmake/Koi.cmake:18 (message):
  Unsupported CUDA toolkit version: 10.1.243
Call Stack (most recent call first):
  cmake/Koi.cmake:45 (get_best_compatible_koi_version)
  CMakeLists.txt:45 (include)


-- Configuring incomplete, errors occurred!

``` 

In the case that I download that pre-built binarie, to use it I just have to extract on folder and run via terminal ?

Thanks

**Comment by tijyojwad** [comment]
hmm looks like it's still picking up a older version of cuda. Can you post what you see with `ls -l /usr/local/cuda*` folder?

You may also need to delete the `cmake-build` folder before retrying the cmd with a new path to the cuda toolkit

**Comment by BastianBrauer** [comment]
Thanks @tijyojwad, I deleted the cmake-build folder and it worked, continued with the installation steps and when I put

`ctest --test-dir cmake-build`

I get this error, and also there's no file in /cmake-build/bin/`

`Test project /home/bioquimica-429/dorado/cmake-build
    Start 1: dorado_tests
Could not find executable /home/bioquimica-429/dorado/cmake-build/tests/dorado_tests
Looked in the following places:
/home/bioquimica-429/dorado/cmake-build/tests/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/Release/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/Release/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/Debug/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/Debug/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/MinSizeRel/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/MinSizeRel/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/RelWithDebInfo/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/RelWithDebInfo/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/Deployment/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/Deployment/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/Development/dorado_tests
/home/bioquimica-429/dorado/cmake-build/tests/Development/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/Release/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/Release/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/Debug/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/Debug/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/MinSizeRel/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/MinSizeRel/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/RelWithDebInfo/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/RelWithDebInfo/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/Deployment/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/Deployment/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/Development/dorado_tests
home/bioquimica-429/dorado/cmake-build/tests/Development/dorado_tests
Unable to find executable: /home/bioquimica-429/dorado/cmake-build/tests/dorado_tests
1/1 Test #1: dorado_tests .....................***Not Run   0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
	  1 - dorado_tests (Not Run)`

**Comment by tijyojwad** [comment]
Hi @BastianBrauer - any updates?

**Comment by agftrace** [comment]
Hi, I am having a similar issue trying to download dorado-0.4.1

`➜  dorado-0.4.1 cmake -S . -B cmake-build
-- Build type: Release
-- Found CUDA  (/usr -> /usr)
-- Unable to find cuda_runtime.h in "/usr/include" for CUDAToolkit_INCLUDE_DIR.
-- Unable to find cublas_v2.h in either "/usr/local/cuda-12.3" or "/math_libs/include"
CMake Error at cmake/Koi.cmake:13 (if):
  if given arguments:

    "VERSION_GREATER_EQUAL" "12.0"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/Koi.cmake:45 (get_best_compatible_koi_version)
  CMakeLists.txt:58 (include)


-- Configuring incomplete, errors occurred!`

Does this mean it is not it not compatible with CUDA version >12.0?

`➜  dorado-0.4.1 nvidia-smi
Tue Oct 24 10:07:36 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.06              Driver Version: 545.23.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070        Off | 00000000:01:00.0 Off |                  N/A |
|  0%   37C    P8              20W / 270W |   1095MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1179      C   ...t/dorado/bin/dorado_basecall_server      984MiB |
|    0   N/A  N/A      1963      G   /usr/lib/xorg/Xorg                           86MiB |
|    0   N/A  N/A      2131      G   /usr/bin/gnome-shell                         11MiB |
+---------------------------------------------------------------------------------------+`

`➜  dorado-0.4.1 nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Sep__8_19:17:24_PDT_2023
Cuda compilation tools, release 12.3, V12.3.52
Build cuda_12.3.r12.3/compiler.33281558_0`

**Comment by iiSeymour** [comment]
@agftrace you can download and run dorado using the following link [dorado-0.4.1-linux-x64](https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.4.1-linux-x64.tar.gz) _(you don't need to build it)_. If you do want to build it you'll need a CUDA 11.8 toolkit installed on your system.

**Comment by BastianBrauer** [comment]
@tijyojwad Ok thanks, build is not working definitively... Can you tell how to use the prebuilt binary? I already downloaded the latest version (dorado-0.4.2-linux-x64), then untared it and what's the next step to use it via terminal? typing dorado or dorado basecaller says that the command is not found...

Thanks for you help

**Comment by tijyojwad** [comment]
Once you download it, you need to invoke the binary directly (or add the binary location to your `$PATH` to pick it up automatically).

e.g., if you untarred the folder in your home directory `/home/user/dorado-0.4.2-linux-x64`, and you run dorado with
```
/home/user/dorado-0.4.2-linux-x64/bin/dorado -h
```

If you want to invoke dorado without passing the full path, you can add `export PATH=/home/user/dorado-0.4.2-linux-x64:$PATH` to your `~/.bashrc`. but every time you update dorado you'll need to adjust the path otherwise it'll keep picking up this older version.

**Comment by BastianBrauer** [comment]
@tijyojwad now it works! thanks a lot
