### ISSUE TITLE
Duplex calling killed midway while using split channel pod5

### ISSUE THREAD

**Issue by sofiabanu** [nanoporetech/dorado#412]
Hi Dorado team, 

I've been getting this issue during duplex basecalling on split channel pod5 files generated using the commands in the README. PFA the log. I've also tried different versions  ranging from 3.2 to 4.0 and also removing the batch size. 

```
time /home/sofia/tools/test_dorado/dorado-0.4.0-linux-x64/bin/dorado duplex --threads 112 -b 256 --device cuda:0,cuda:1 /home/sofia/tools/dorado_models/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 /home/sofia/Mala/Mala_Trio_sup_dup/BNG63/split_by_channel_BNG63 > /home/sofia/Mala/Mala_Trio_sup_dup/BNG63/BNG63_DUPLEX_dor4.bam
[2023-10-12 17:10:04.071] [info] > No duplex pairs file provided, pairing will be performed automatically
[2023-10-12 17:20:54.873] [info]  - set batch size for cuda:0 to 5632
[2023-10-12 17:20:55.951] [info]  - set batch size for cuda:1 to 5696
[2023-10-12 17:20:55.952] [info] > Starting Stereo Duplex pipeline
[2023-10-12 17:20:56.165] [info] > Reading read channel info
[2023-10-12 17:25:56.224] [info] > Processed read channel info
/var/spool/pbs/mom_priv/jobs/338298.ramanujan-1.SC: line 13: 40059 Killed                  /home/sofia/tools/test_dorado/dorado-0.4.0-linux-x64/bin/dorado duplex --threads 112 -b 256 --device cuda:0,cuda:1 /home/sofia/tools/dorado_models/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 /home/sofia/Mala/Mala_Trio_sup_dup/BNG63/split_by_channel_BNG63 > /home/sofia/Mala/Mala_Trio_sup_dup/BNG63/BNG63_DUPLEX_dor4.bam

real	635m43.167s
user	911m9.169s
sys	507m9.659s
```

**Comment by tijyojwad** [comment]
Hi @sofiabanu - this typically happens when the system runs of out host memory.

Can you send your system configurations? CPU cores, host memory, etc.?

Also, I see that your input folder is called `/home/sofia/Mala/Mala_Trio_sup_dup/BNG63/split_by_channel_BNG63`. Does this contain all the pod5s split by channel, or a subset of the channels?

**Comment by sofiabanu** [comment]
Hi @tijyojwad 
The folder contains all the pod5s  split by channel. 
CPU - Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz, GPU - A100 and memory is 256 Gb. 56 cores . 
We've successfully performed duplex basecalling before but for some reason it fails on  the channel pod5. I've tested this on different samples as well.

**Comment by tijyojwad** [comment]
Thanks for the details. You should have enough memory for duplex. Are there other programs running that could be using a lot of memory?

Since you have split the dataset by channel, I would also suggest running dorado on each pod5 separately (or a subset of pod5s together). e.g. you could loop over each pod5 (dorado now accepts path to a specific pod5 as input too), or batch a few pod5s (say 5 of them) into separate folders and run dorado on each folder. Both of these can lower the memory footprint.

**Comment by sofiabanu** [comment]
No, we don't have other jobs running on our GPU node.  I did run each channel pod5 separately in a loop but I couldn't find any duplex pairs in the log files or by manually checking by tag in the bam files. Tested this on couple of samples as well. Here's an example log file. I found the "Duplex reads basecalled: 0" in all the logs of the channel pod5 files. 

```
time /home/sofia/tools/dorado-0.4.0-linux-x64/bin/dorado duplex --threads 112 -b 256 --device cuda:0,cuda:1 /home/sofia/tools/dorado_models/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 /home/sofia/Mala/Mala_Trio_sup_dup/BNG63/channel-2641_dir > /home/sofia/Mala/Mala_Trio_sup_dup/BNG63/channel-2641_test4.bam

[2023-10-12 15:52:38.145] [info] > No duplex pairs file provided, pairing will be performed automatically
[2023-10-12 15:53:25.651] [info]  - set batch size for cuda:0 to 5696
[2023-10-12 15:53:26.743] [info]  - set batch size for cuda:1 to 5632
[2023-10-12 15:53:26.744] [info] > Starting Stereo Duplex pipeline
[2023-10-12 15:53:26.776] [info] > Reading read channel info
[2023-10-12 15:53:26.796] [info] > Processed read channel info
[2023-10-12 15:55:07.726] [info] > Simplex reads basecalled: 12734
[2023-10-12 15:55:07.726] [info] > Duplex reads basecalled: 0
[2023-10-12 15:55:07.726] [info] > Duplex reads filtered: 816
[2023-10-12 15:55:07.726] [info] > Duplex rate: 0.0019181985%
[2023-10-12 15:55:07.726] [info] > Basecalled @ Bases/s: 5.709727e+05

```

**Comment by tijyojwad** [comment]
Duplex reads are filtered out typically because the duplex read length is < 5 bp. That happens when we find false positive pairs in the dataset and not real duplex pairs.

Are you certain this is a duplex dataset? Is this short read/amplicon dataset by any chance?

**Comment by sofiabanu** [comment]
@tijyojwad Yes, it is a duplex dataset and we've generated human WGS data.

**Comment by tijyojwad** [comment]
Got it - could you try the following:

1. Run with `-v` on the cmdline. This will output a lot of logs, so best to also add `2> stderr.log` which will redirect stderr to a file. Then we can see the details of what's going on.

2. Run this data through an older version of dorado, maybe v0.3.4, to see if it works better (in case we introduced a regression)? https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.3.4-linux-x64.tar.gz

**Comment by HalfPhoton** [comment]
Closing as there's been no response  - please re-open if your issue is not resolved
