### ISSUE TITLE
bacterial methylation model

### ISSUE THREAD

**Issue by asershova** [nanoporetech/dorado#413]
Dear Authors,

I run dorado with bacterial methylation model from the rerio, res_dna_r10.4.1_e8.2_400bps_sup@2023-09-22_bacterial-methylation
My command is:
dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.2.0 pod5_dir --modified-bases-models rerio/dorado_models/res_dna_r10.4.1_e8.2_400bps_sup@2023-09-22_bacterial-methylation --emit-moves --reference genome.fna > out.bam

I got an error message

[2023-10-12 07:51:09.414] [error] [error] key "general" not found in the top-level table
 --> res_dna_r10.4.1_e8.2_400bps_sup@2023-09-22_bacterial-methylation/config.toml
   |
 1 | [model]
   | ^--- the top-level table starts here

I would appreciate any advice on how to solve it.

Best regards,

Anna

**Comment by ArtRand** [comment]
Hello @asershova,

There are 2 models, the basecaller model and the modified base model. I think the command you want is something like this:
```bash
dorado basecaller \
    res_dna_r10.4.1_e8.2_400bps_sup@2023-09-22_bacterial-methylation \ # basecaller model
    ${pod5_dir} \
    --modified-bases-models ${modified_base_model(s)} \ # skip this if you're not using them modified bases
    > out.bam
```
Note that the basecaller model `res_dna_r10.4.1_e8.2_400bps_sup@2023-09-22_bacterial-methylation` is not the same as the modified base model. 

Hope this helps, 

A

**Comment by anjatolic** [comment]
Hello @asershova and @ArtRand,
I have a follow up question related to this. What are modified base models compatible with this basecaller model `res_dna_r10.4.1_e8.2_400bps_sup@2023-09-22_bacterial-methylation`? 
@asershova can you share what did you use as modified base models?
