### ISSUE TITLE
heterogeneous GPUs in system, instructions unclear.

### ISSUE THREAD

**Issue by faulk-lab** [nanoporetech/dorado#415]
How to best run dorado in a system with heterogeneous GPUs, e.g., a 3080 Ti + 3090? The instructions state "If you have a hetrogenous collection of GPUs, select the faster GPUs using the --device flag (e.g --device cuda:0,2). Not doing this will have a detrimental impact on performance."

What exactly does that mean? Should you:
1) Select ONLY the faster GPU and run in single GPU mode? 
2) Select the faster GPU FIRST, and the slower second? In my case, `--device cuda:1,0` and it would run DUAL GPUs? 
3) Something else?

Thanks!

**Comment by iiSeymour** [comment]
Hey @faulk-lab 

The `--device` flag only selects which GPUs to run dorado on and the order has no importance. The unclear instructions here should read something like _"use the `--device` flag to select/group homogeneous GPU for best performance"_ however the README is actually outdated w.r.t heterogeneous GPUs. In the latest version of dorado we benchmark and configure each GPU individually so you can run a job on all and expect the ~best performance for each GPU.

**Comment by faulk-lab** [comment]
Oh perfect, that is super helpful that it configures each GPU individually now! Ok, I'll run some benchmarks. Appreciated.
