### ISSUE TITLE
Which version of dorado in MinKNOW?

### ISSUE THREAD

**Issue by rzelle-lallemand** [nanoporetech/dorado#416]
> simplex read splitting is now supported in dorado [v0.4.0 ](https://github.com/nanoporetech/dorado/releases/tag/v0.4.0)

How can I check which version of dorado is included in a given MinKNOW version? I have MinKNOW 23.07.15 installed but the software panel only says:
 
> MinKNOW core:
> 5.7.5
> 
> Guppy:
> 7.1.4
> 
> Bream:
> 7.7.6
> 
> Script Configuration:
> 5.7.11

https://community.nanoporetech.com/downloads lists Guppy v6.5.7 as latest version, so maybe the "Guppy" field in MinKNOW currently refers to the "Dorado basecall server" version (latest version 7.1.4)? I don't see listed anywhere which dorado version in included in the "Dorado basecall server", assuming the former is bundled with the latter. The release notes of MinKNOW also don't list the dorado version.

I'm asking because we're noticing a huge fraction (rough guess 10-20%) of what look like to be unsplit reads in a recent MinKNOW 23.07.5 / SQK-NBD114-24 run. It looks like upgrading to dorado v0.4.0 (and recalling the data) might help: https://github.com/nanoporetech/dorado/issues/367

**Comment by vellamike** [comment]
Hi @rzelle-lallemand, Versions of Dorado in MinKnow are not strictly pinned to their Dorado standalone counterpart.

Have you found that recalling the data with v0.4.0 helps? It's not clear from your message whether you've confirmed this hypothesis.

**Comment by rzelle-lallemand** [comment]
Hi @vellamike, thanks. I haven't tried recalling yet. I was trying to figure out if upgrading MinKNOW would give me a newer version of dorado to basecall with.

So it's not possible to learn from a past (MinKNOW or GridION X5) run what (approximate) version of dorado was used for basecalling? That would be unfortunate.

**Comment by vellamike** [comment]
> So it's not possible to learn from a past (MinKNOW or GridION X5) run what (approximate) version of dorado was used for basecalling? That would be unfortunate.

In future we may give this more detailed information, but at the moment this isn't something we provide. Apologies for the inconvenience.

**Comment by rzelle-lallemand** [comment]
Okay, thanks! I'll install dorado on the side then to troubleshoot our data issue.
