### ISSUE TITLE
dorado run yielded no output

### ISSUE THREAD

**Issue by olu2016** [nanoporetech/dorado#417]
Hi,

My dorado run yielded no output:

cmd used:
dorado duplex models/dna_r10.4.1_e8.2_400bps_hac@v4.2.0 /pod5/ -x cpu > ./test.bam

outputs:
[2023-10-11 12:43:09.066] [info] > No duplex pairs file provided, pairing will be performed automatically
[2023-10-11 12:43:14.462] [info] > Starting Stereo Duplex pipeline
[2023-10-11 12:43:14.490] [info] > Reading read channel info
[2023-10-11 12:43:15.046] [info] > Processed read channel info
killed

Any idea what went wrong?

**Comment by tijyojwad** [comment]
Hi @olu2016 - this typically happens when your system has run out of host memory. How much RAM is available on your system?

**Comment by olu2016** [comment]
Hi @tijyojwad - it's 65GB.

**Comment by olu2016** [comment]
Hi @tijyojwad  - Thanks. After increasing RAM to 126GB, I have some bam output. But, summary stats showed the data might have been truncated for some reason.

cmd:
`dorado summary test.bam`

Top of summary output::
`[W::bam_hdr_read] EOF marker is absent. The input is probably truncated`

Any ideas please? Could it be that the run did not complete and I still need more memory?

**Comment by tijyojwad** [comment]
Hi @olu2016 - 

Do you have `stderr` logs from your run? How did it finish?

It does look like the BAM didn't fully write out. Can you also try to run `samtools quickcheck -u test.bam`?

Is your output file stored over some network mounted storage or kept on a local machine?

**Comment by olu2016** [comment]
Hi @tijyojwad 

Output file is stored on a network mounted storage.

output for 'samtools quickcheck -u test.bam':
`test.bam was missing EOF block when one should be present.`

error.log:
`[2023-10-20 10:13:36.816] [info] > No duplex pairs file provided, pairing will be performed automatically`
`[2023-10-20 10:13:44.037] [info] > Starting Stereo Duplex pipeline`
`[2023-10-20 10:13:44.412] [info] > Reading read channel info`
`[2023-10-20 10:13:44.969] [info] > Processed read channel info`

**Comment by tijyojwad** [comment]
Hi @olu2016 - these logs indicate that the run didn't complete fully. Once successfully completed, dorado reports how many reads were called and a throughput number.

Are you sure the run finished? Do you have a way to check the exit code?

**Comment by olu2016** [comment]
Hi @tijyojwad - you're right the run didn't complete. We're contemplating getting a GPU. One question I have is: if we install a GPU, how much RAM and CPU resources do we need in addition to run Dorado?

**Comment by JMencius** [comment]
Hi @tijyojwad I also encounter the same problem unfortunately. I have more than enough RAM (256 G) in my machine. At the start you can see fastq output in the output directory (I used --emit-fastq option), but the fastq file output disappeared for no reason, and the program is still running.

**Comment by tijyojwad** [comment]
Hi @olu2016 - sorry for the late response

> if we install a GPU, how much RAM and CPU resources do we need in addition to run Dorado?

I would suggest at least 64GB of RAM, ideally 128GB. And 8-16 high performance CPU cores.

**Comment by tijyojwad** [comment]
@JMencius 

> At the start you can see fastq output in the output directory (I used --emit-fastq option), but the fastq file output disappeared for no reason

This doesn't look like a `dorado` issue from the outset. Dorado just writes to `stdout`, and the redirection to file is handled by the shell. What platform are you running on? When you say the program is still running, do you see high CPU/GPU usage? Is the file being written to some NFS storage/shared folder or a local disk?
