### ISSUE TITLE
docker container for the v0.4.0 release

### ISSUE THREAD

**Issue by yuukiiwa** [nanoporetech/dorado#419]
Hi,

It is possible to push the v0.4.0 release to docker hub, please?

Thanks!

Best wishes,
Yuk Kei

**Comment by iiSeymour** [comment]
Hi @yuukiiwa we don't distribute dorado on docker hub.

**Comment by yuukiiwa** [comment]
I got pointed to this docker image: https://hub.docker.com/r/ontresearch/dorado. Is it not from ONT?

**Comment by yuukiiwa** [comment]
Hi @SamStudio8, thanks for the clarification!
