### ISSUE TITLE
Dorado curious performance characteristics

### ISSUE THREAD

**Issue by rhpvorderman** [nanoporetech/dorado#422]
Hi, I am currently trying duplex basecalling on one of the ont-open-data datasets. Simplex calling went fine, but duplex calling proves difficult due to out-of-time or out-of-memory errors on the cluster.

I noticed that dorado memory usage is quite high and keeps growing over time. This seems a little odd to me. From what I understood, dorado reads in data from the duplex strands simultaneously, calls them in simplex mode, and then feeds both strands + some stats from the simplex calling to a special duplex model. 
Given that sort of design the space requirement should be constant: the room for two simplex models + one duplex model + the length of the reads that are currently evaluated. 

Yet I see the memory use rise over time. Did I misunderstand some key design features or is there a memory leak somewhere?

**Comment by vellamike** [comment]
Hi, I have some questions to help understand what you're seeing. Which version of Dorado are you using? What system are you running on? How much RAM consumption do you observe?

**Comment by rhpvorderman** [comment]
I was using 0.3.4, but I saw that I new release came out. So I am running that now. Yet I am seeing the same things:
- Memory usage started at 38 GB but has after two hours steadily increased to 44 GB 
- I started with -t 6, yet these are hardly ever used. CPU usage is average around 150%. One of the threads uses 100% and is apparently bottlenecking.
Current nvidia-smi output
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GRID V100S-32Q      On   | 00000000:02:01.0 Off |                    0 |
| N/A   N/A    P0    N/A /  N/A |  22025MiB / 32768MiB |     98%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   1294004      C   ....4.1-linux-x64/bin/dorado    19833MiB |
+-----------------------------------------------------------------------------+
```
lscpu
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              12
On-line CPU(s) list: 0-11
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           12
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6252 CPU @ 2.10GHz
Stepping:            7
CPU MHz:             2095.077
BogoMIPS:            4190.15
Hypervisor vendor:   VMware
Virtualization type: full                                                                                                                                                                                                                    
L1d cache:           32K                                                                                                                                                                                                                     
L1i cache:           32K                                                                                                                                                                                                                     
L2 cache:            1024K                                                                                                                                                                                                                   
L3 cache:            36608K                                                                                                                                                                                                                  
NUMA node0 CPU(s):   0-11                                                                                                                                                                                                                    
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq s
sse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid avx51
2f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat pku ospke avx512_vnni md_clear flush_l1d arch_capabilities 
```

The system has 188 GiB of memory. I reserved 128 GB in my SLURM Job. Previously I had 64GiB reserved, but that made it crash around the 80% completed marker (judging from the size of the simplex file).

**Comment by vellamike** [comment]
> One of the threads uses 100% and is apparently bottlenecking.

I wouldn't draw this conclusion, threads are dynamically managed in Dorado, you don't really need to set that parameter. Is your GPU utilisation consistently high?

Are you [subsetting your POD5s by channel](https://github.com/nanoporetech/dorado#improving-the-speed-of-duplex-basecalling)? 

I have some theories:

1. Dorado memory utilisation is spikey, you might be hitting an OOM on a spike rather than gradually running out of memory.
2. This is not too likely but are you sure piping to BAM is not the issue here? If your network IO is too slow this could cause the issue you observe.

**Comment by rhpvorderman** [comment]
> Are you [subsetting your POD5s by channel](https://github.com/nanoporetech/dorado#improving-the-speed-of-duplex-basecalling)?

I didn't do that specifically. There are a lot of pod5 data files in the ont-open-data set but I didn't check if these were channel ordered. I will look into that. 

> Dorado memory utilisation is spikey, you might be hitting an OOM on a spike rather than gradually running out of memory.

Currently sitting at 46.7 GiB. Another 2 GB extra over the previous time I checked. I find that odd. Unfortunately I cannot monitor the memory usage if it crashes. I will keep a tap on things.

> This is not too likely but are you sure piping to BAM is not the issue here? If your network IO is too slow this could cause the issue you observe.

Not really. The cluster is on a high-performance storage at about 100MiBs. So a 100G bam file can be written in a 1000 seconds. That is about 17 minutes. So the pipe is clearly not the bottleneck given that the job is running for a few hours already.

I will have a look on the subsetting and report back if that resolves the issue.

**Comment by rhpvorderman** [comment]
I am currently subsetting the data and I estimate that the 1.5 TB will need 120 CPU hours to compete. Given the sheer amount of compute needed for data rearrangement, and the memory requirements for caching some of that data, I understand why dorado performs the way it does on not subsetted data.  Accessing disparate streams of data across multiple files is indeed quite slow  on our NFS cluster. The sequential transfer rate is quite good, but IO operations are very high latency.
Thanks for the additional information.

**Comment by rhpvorderman** [comment]
I have subsetted the data. This has enabled full GPU utilization (hurray!) yet the performance is rather curious still. Duplex basecalling memory goes beyond 64GB. 
How can this be? Pod5 is optimized for streaming the data, the model is fixed size. Where does this memory ballooning come from? What is going on?

I assume that dorado is a well-written application where only the signal data that is currently processed is kept in memory as well as the model and maybe a few indexes to enable fast lookups. Am I missing something here?

**Comment by vellamike** [comment]
Hi @rhpvorderman,

The RAM utilisation comes during Duplex comes in for a rather interesting reason. The POD5 is as you point out optimised for streaming data, however when duplex calling different reads from the POD5 need to be combined (we call this _pairing_). Dorado therefore builds a [cache of reads for every channel](https://github.com/nanoporetech/dorado/blob/master/dorado/read_pipeline/PairingNode.cpp) and stores them until all duplex pairing for that channel has been completed.

We are thinking of ways to reduce this memory utilisation and this situation will be improved in future releases.

**Comment by rhpvorderman** [comment]
Hi @vellamike Interesting. I thought that subsetting the data per channel would reduce the memory usage for the same reason, but it is still quite high. 

Thanks for sharing the code. I see that there are few fast selection criteria and a criterion that requires alignment. The last one needs simplex called data already, so I guess that can indeed blow up the cache a bit.

The problem is of course that the cache data gets  proportionally blown up with the size of the data. I'd argue that requiring anything more than 24 GB already has a scalability problem. (32GB is a reasonable memory size for a proper work PC) . Simplex calling works fine within this boundaries, but the duplex calling process needed 72 GB to complete on the ont-open-data.

My suggestion would be to cache the raw read data from the simplex calling on disk and keep the minimizer index in memory. The minimizer index is much smaller, and simply seeking a file and retrieving the data when necessary is not that bad, especially when a memory map is used. The disk cache can be created per channel. This has the advantage that with properly subsetted data, the disk cache can be removed again after a channel is finished. Given that a run has multiple channels, the disk cache use will only be a small fraction of usage compared to the pod5 data already on disk anyway.

But I don't know if this can be properly inserted in the pipeline as you currently have it. It would be bad if GPU usage is not at 100% for any prolonged length of time. On that metric dorado scored excellently! Thanks!

**Comment by tijyojwad** [comment]
Hi @rhpvorderman 

Thank you for the suggestion! We have been profiling memory utilization in duplex, and have identified some hotspots in our pipeline where the utilization could be reduced. We're looking into multiple avenues for improvement, including reducing the cache size and changing when/how we store necessary metadata.

As @vellamike mentioned, we will be implementing these changes in upcoming releases.

**Comment by rhpvorderman** [comment]
Thanks! With everything explained to me, I will close this issue. Thank you for taking the time to give a thorough explananation!
