### ISSUE TITLE
CUDA device requested but no devices found.

### ISSUE THREAD

**Issue by LEGMCGILL** [nanoporetech/dorado#423]
I am trying basecalling and after feeding the prompt with the commands to run my basecalling I am getting the CUDA device requested but no devices found. 

By reading on the Dorado recommendations I learnt that setting up the LD_LIBRARY_PATH to point Dorado's libraries was the way to go, but that didnt resolve my problem. I am getting the same message. 

I am working in a Linux partition at the moment. And dont quite understand what the issue is.

On the other hand, I am also reading on the same page that  the choosing in between GPUs with the flag --device should fix the performance problems. I am not quite sure how to check that I tried on the prompt but at this poin I am not quite sure what the issue might be. 

All help is welcome. 

Laura.

![image](https://github.com/nanoporetech/dorado/assets/147701622/0aa43f65-bf29-4cf8-8c18-8c8caea55137)

**Comment by sklages** [comment]
We probably need a bit more info ...
- how does `nvidia-smi` output look like? 
- how did you actually start `dorado`? 
- what is the exact error message?

**Comment by LEGMCGILL** [comment]
Hello, thank you for your reply.  

At first it said that nvidia-smi command was not installed. 

Then I installed with with the 

$ sudo apt install nvidia-utils-510

It was strange the message I was getting after installing the command and trying to display it in the prompt since it is saying that NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

The picture is the message I am getting and the command I am using to run the basecalling, currently reading about the NVIDIA drivers to see what information I can get out of it. 

![image](https://github.com/nanoporetech/dorado/assets/147701622/2be10293-db24-4adf-99f8-ea16518d7c69)

**Comment by LEGMCGILL** [comment]
I am still trying to understand how to solve this and although I dont quite get the issue. I came across with the following command to check which is the GPU that I have active in Linux and it displays the following information: 
![image](https://github.com/nanoporetech/dorado/assets/147701622/5d591822-f0d8-4750-a9fd-1243592c1056)
Does this mean that NVIDIA wont be working and hence do not perform the basecalling?

Thanks for your help

**Comment by sklages** [comment]
well, yes, you don't have a NVIDIA card but a AMD card. CUDA is nvidia-specific. So GPU basecalling won't work on your notebook..

**Comment by tijyojwad** [comment]
@sklages is correct. This is our current platform support - https://github.com/nanoporetech/dorado#platforms
