### ISSUE TITLE
direct RNA m5C and m6A mods?

### ISSUE THREAD

**Issue by avilella** [nanoporetech/dorado#425]
Are there models for m6A and m5C RNA modifications in dorado? Do you know if one can basecall direct RNA data with these mods? Thanks

**Comment by tijyojwad** [comment]
Hi @avilella , not yet but we're working on enabling them soon. Stay tuned!

**Comment by tijyojwad** [comment]
Hi @avilella - just to clarify a bit more on my previous message. Our current focus is enabling m6A first.

**Comment by keenhl** [comment]
So, if I understand correctly, it's not possible to detect 5mC modifications from direct RNA experiments in Dorado.  If that is the case, and hopefully it is not, then which application would we use to do that ?
