### ISSUE TITLE
Summary Unable to Open BAM file

### ISSUE THREAD

**Issue by aljazdzy** [nanoporetech/dorado#427]
Hello!  I successfully produced BAM files after running POD5 files through dorado (SUP), but when I try to run it through the summary function, "dorado summary calls.bam" I get, "[E::hts_hopen] Failed to open file calls.bam
[E::hts_open_format] Failed to open file "calls.bam" : Exec format error
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not open file: calls.bam
Aborted"

And I can't quite figure out why.  Is there any potential solution and/or way to troubleshoot this?

**Comment by tijyojwad** [comment]
Hi @aljazdzy 

Did your `dorado` run finish successfully? How large is the file? You can also do a quick sanity check on your file using `samtools quickcheck -u calls.bam`.

**Comment by aljazdzy** [comment]
The file size is 26,189 KB, I thought it ran successfully!  It gave me read counts, total length, that kind of information.  I'll try that though and see what happens.

**Comment by aljazdzy** [comment]
After assessing with samtools I received a similar results.  "calls.bam could not be opened for reading." So there must be something going on with the way the file is being created that is causing this error.  I'm going to continue to try and see if I can assess the error from my side but I'd be grateful for any ideas you may have!

**Comment by aljazdzy** [comment]
Update, I fixed the issue, but for the sake of others: I don't currently have admin access so I was working through powershell, which was a mistake I should have been working through the command prompt.  Also, I still couldn't get summary to work, but if I run it through ubuntu on my laptop that for some reason does work.  It may still be a concern that the summary couldn't output a file in command prompt.

**Comment by falkomathes** [comment]
Thanks @aljazdzy - this worked for me too!
