### ISSUE TITLE
Q: dorado_basecall_server -> adaptive sampling speed

### ISSUE THREAD

**Issue by sklages** [nanoporetech/dorado#429]
With current version of MinKNOW/dorado_basecall_server on a fast SSD with a `Nvidia RTX A6000 (48G)` how fast is "adaptive sampling"? Translocation speed seems to be around 350 bases/sec.

Or how many bases are read to be taken in account for adaptive basecalling? Or how long does it take for MinKNOW to decide wether a read will be discarded or not?

Are there any recent numbers?

**Comment by susie-ont** [comment]
Hi @sklages - Miguel has sent you some details about this in response to your question in the community: https://community.nanoporetech.com/posts/software-patch-release-23-13145
I hope this helps!

**Comment by sklages** [comment]
@susie-ont - yes. Thanks.
