### ISSUE TITLE
Using -x cpu for dorado basecaller but gets killed

### ISSUE THREAD

**Issue by JoukjeKloosterman** [nanoporetech/dorado#434]
Hello,

I am using dorado modified basecalling with the following command:

`dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.1.0 pod5/ --reference human_g1k_v37.fasta --modified-bases 5mCG_5hmCG -x cpu > X5.bam`

and i am using slurm to manage the job:

![image](https://github.com/nanoporetech/dorado/assets/144109774/18cddc41-6b30-41e0-a8c2-cbe293f51c0a)

 However the process gets killed:

![image](https://github.com/nanoporetech/dorado/assets/144109774/d6f114a6-c358-45dc-9bd8-3225f117aded)

It appears to be an out of memory issue. What memory and cores are necessary to run dorado properly with cpus?
or what other configurations should i add?

**Comment by vellamike** [comment]
As pointed out by @sklages, you are hitting an out of memory issue.

Basecalling on CPU is not advised, especially with modified basecalling _and_ alignment. Could you try basecalling on a GPU system?

**Comment by JoukjeKloosterman** [comment]
@vellamike and @sklages ,

I am aware that dorado should be run on GPU, and this works for my system too. However, I want to use the tool in a different pipeline to support methylation calling, which is developed for a cpu system. Hence, i want to use dorado on a cpu system. 

i did remove the alignment, but it still ran out of memory.

**Comment by vellamike** [comment]
I think your best bet in that case is to perform the methylation calling on a system with GPU, and then the next part of the pipeline on the CPU system. Alternatively, you could run on a CPU system with more available memory - but it's not the route I would advise.

**Comment by sklages** [comment]
@JoukjeKloosterman - as @vellamike has recommended: separate the actual basecalling step (including methylation calling) from the downstream processing. That's what we do here as well: base-/methylation calling on powerful GPU machines, any downstream analysis on powerful CPU machines (with the advantage of having better control over minimap2 :-) )
