### ISSUE TITLE
dorado demux mostly unclassified reads (>90%)

### ISSUE THREAD

**Issue by iframst** [nanoporetech/dorado#435]
Hello, I have been using dorado 0.4.1 to re-basecall and demux some R9.4.1 reads. using the HAC model, I get mostly unclassified reads (>90% unclassified), when previously there was less than 5% unclassified using Guppy (2021 data). I have the same experience with three different runs from 2021 and 2022. Is there an error in my process, or am I missing something?
```
dorado basecaller --emit-fastq --kit-name SQK-RBK110-96 /Users/isaacframst/binf/dorado_models/dna_r9.4.1_e8_hac@v3.3 /Volumes/Isaac_superSSD/Mycoplasma/mycoplasma_1/mycoplasma_2/20210708_1449_MN30261_FAP81950_d4630bf3/fast5 > Mycoplasma1_HAC.fastq
```
```
dorado demux --kit-name SQK-RBK110-96 --emit-fastq --output-dir Mycoplasma1_HAC_demux Mycoplasma1_HAC.fastq
```
```
dorado --version
0.4.1+6c4c6360
```

**Comment by tijyojwad** [comment]
Hi @iframst 

Thanks for trying out barcoding! 

The first command for ([in-line barcoding with basecalling](https://github.com/nanoporetech/dorado#in-line-with-basecalling)) will classify and _trim_ the barcodes from reads by default. As a result, when you try to re-classify them again with `dorado demux` they will end up unclassified.

What I think you want to do is run `dorado demux` in demux mode only (no classification). Note that for that to work, you need to store the basecalling results in `BAM` and not fastq. The cmd to demux only is

```
dorado demux --output-dir <output-dir> --no-classify <input-bam>
```

Our recommendation is to keep basecalls stored in BAM and not fastq. If you absolutely need to store them in fastq, then you will need to
1. Run `basecaller` cmd without `--kit-name` and store results in fastq
2.  Run `dorado demux` as you did to both classify and demux after basecalling

**Comment by iframst** [comment]
Hi @tijyojwad 
Thanks for that! I will try:

```
dorado basecaller --kit-name SQK-RBK110-96 dna_r9.4.1_e8_hac@v3.3 <reads dir> > calls.bam

dorado demux --output-dir <output-dir> --no-classify <calls.bam>
```

**Comment by casmerifle** [comment]
Hi @iframst, sorry to comment on this thread, but I'm having trouble with dorado demux as I'm getting all my reads unclassified. Can I clarify with you on the basecaller command you used? I am currently using this:
`dorado basecaller --emit-moves hac,5mCG_5hmCG,6mA --recursive --reference ${REFERENCE} ${INPUT} > calls.bam -x "cpu"`
To my knowledge, none of these options should affect the barcodes obtained. I understand that --kit-name does not need to be specified as tagging with hac would get basecaller to retrieve it from the data itself. Would you have any tips for troubleshooting? I have tried --no-trim for dorado basecaller to no avail. I ran dorado summary as well, and nothing looks out of place. A section of my reads are as follows:
`filename	read_id	run_id	channel	mux	start_time	duration	template_start	template_duration	sequence_length_template	mean_qscore_template	barcode	alignment_genome	alignment_genome_start	alignment_genome_end	alignment_strand_start	alignment_strand_end	alignment_direction	alignment_length	alignment_num_aligned	alignment_num_correct	alignment_num_insertions	alignment_num_deletions	alignment_num_substitutions	alignment_mapq	alignment_strand_coverage	alignment_identity	alignment_accuracy	alignment_bed_hits
second.pod5	556e1e16-cb98-465e-b4a3-8198eedbe918	09e9198614966972d6d088f7f711dd5f942012d7	109	1	3875.42	1.1782	3875.42	1.1762	80	4.02555	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	85209b06-8601-4725-9fe2-b372bfd33053	09e9198614966972d6d088f7f711dd5f942012d7	277	3	3788.21	1.4804	3788.38	1.3092	61	3	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	e7e7937b-ab58-498f-a128-15d6daf3de00	09e9198614966972d6d088f7f711dd5f942012d7	485	2	3725.81	0.9044	3725.96	0.7596	57	7.08606	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	49d2e9fc-ba2f-4c3c-b07a-852cea942ff0	09e9198614966972d6d088f7f711dd5f942012d7	178	4	3776.59	0.9098	3776.6	0.9078	95	5.80001	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	45ac7aca-8568-42a4-abb3-bc0263d28a0b	09e9198614966972d6d088f7f711dd5f942012d7	266	3	3656.09	1.1108	3656.18	1.0212	119	10.4806	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	071ae232-2986-40ed-934a-41b5c0777eed	09e9198614966972d6d088f7f711dd5f942012d7	278	3	3829.44	0.7858	3829.44	0.7838	218	8.85919	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	beb587cf-5294-4948-b361-f809f9524fca	09e9198614966972d6d088f7f711dd5f942012d7	389	2	3749.87	0.6752	3749.99	0.5544	213	16.948	unclassified	chr16	26499318	26499489	40	209	+	171	169	169	0	2	0	60	0.793427	1	0.988304	0
second.pod5	f7369b4b-5eb7-4a84-a090-d91b4eebaa03	09e9198614966972d6d088f7f711dd5f942012d7	388	1	3895.94	1.3906	3895.94	1.3886	216	5.26062	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	11d3cbd3-2983-4620-bdf0-58a1cccb67ae	09e9198614966972d6d088f7f711dd5f942012d7	313	3	3747.86	0.9992	3748.24	0.6216	167	7.24626	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	c5e92834-e662-475b-bf0e-7d0750d2f9cf	09e9198614966972d6d088f7f711dd5f942012d7	402	4	3663.28	1.8152	3663.37	1.728	632	16.3266	unclassified	chrX	27870923	27871554	4	632	-	634	625	621	3	6	4	60	0.993671	0.9936	0.979495	0
second.pod5	609a1949-880f-4f43-9662-ee1731430384	09e9198614966972d6d088f7f711dd5f942012d7	128	3	3803.95	0.7964	3804.08	0.66	164	10.7131	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	82ed7773-f992-48c0-8987-080d8d9340ff	09e9198614966972d6d088f7f711dd5f942012d7	351	3	3894.22	1.2134	3894.22	1.2114	107	6.51346	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	998660e0-7f69-47b3-9f2e-18f16319ca22	09e9198614966972d6d088f7f711dd5f942012d7	382	4	3998.8	0.8364	3998.8	0.8344	217	10.2654	unclassified	chr13	99654083	99654268	26	216	+	194	181	173	9	4	8	41	0.875576	0.955801	0.891753	0
second.pod5	252d403b-cb8e-4e97-a2da-9ef52d904384	09e9198614966972d6d088f7f711dd5f942012d7	278	3	3931.71	1.3808	3931.86	1.2372	422	17.3157	unclassified	chr4	107716798	107717213	0	416	+	417	414	413	2	1	1	60	0.985782	0.997585	0.990408	0
second.pod5	29a0d94b-ee23-4083-b44c-1716e36c3d0d	09e9198614966972d6d088f7f711dd5f942012d7	98	3	3834.58	1.1346	3834.58	1.1326	343	19.1618	unclassified	chr17	9869206	9869475	5	273	-	269	268	268	0	1	0	60	0.781341	1	0.996283	0
second.pod5	b137d67e-edee-4f12-a686-9e508f5c40af	09e9198614966972d6d088f7f711dd5f942012d7	69	3	3933.16	1.5768	3933.16	1.5748	74	5.21401	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	4f24990c-824a-4e11-96f9-253dba70581e	09e9198614966972d6d088f7f711dd5f942012d7	497	3	3897.33	0.8942	3897.34	0.8922	122	3.80078	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	ff5f2b6a-8a02-4243-bd72-92e8335b21aa	09e9198614966972d6d088f7f711dd5f942012d7	98	3	3633.74	1.1512	3633.74	1.1492	96	5.13769	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	e6a93d11-0e10-4562-be9a-072d82a88215	09e9198614966972d6d088f7f711dd5f942012d7	153	4	3819.37	1.2844	3819.38	1.2824	277	2.62379	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	909c2066-09f1-48d8-9d21-780c1e2e0520	09e9198614966972d6d088f7f711dd5f942012d7	58	3	3922	0.732	3922	0.73	237	17.9635	unclassified	chrUn_KI270466v1	348	545	38	235	+	197	197	195	0	0	2	60	0.831224	0.989848	0.989848	0
second.pod5	c9657ba2-6ad6-4f98-a2d7-227a3ad9c056	09e9198614966972d6d088f7f711dd5f942012d7	295	1	3612.51	2.0396	3612.51	2.0376	550	18.4768	unclassified	chr16	75927896	75928415	0	522	-	523	518	517	4	1	1	60	0.949091	0.99807	0.988528	0
second.pod5	7392ba94-fb74-4db7-91ba-add68c2c7c4d	09e9198614966972d6d088f7f711dd5f942012d7	18	4	3697.92	1.4012	3698.07	1.2504	481	17.0542	unclassified	chr14	86898301	86898783	0	475	+	485	472	469	3	10	3	60	0.987526	0.993644	0.96701	0
second.pod5	bd49318b-412c-4339-a70a-a48e34471459	09e9198614966972d6d088f7f711dd5f942012d7	111	1	3731.2	1.6262	3731.2	1.6242	511	22.2194	unclassified	chr20	32338763	32339206	68	511	+	443	443	443	0	0	0	60	0.866928	1	1	0
second.pod5	9c623f62-19c6-4390-9255-8a799513de2a	09e9198614966972d6d088f7f711dd5f942012d7	415	2	3611.26	1.0892	3611.42	0.9288	313	13.961	unclassified	chr18	23567083	23567370	26	313	-	289	285	285	2	2	0	60	0.916933	1	0.986159	0
second.pod5	5204e894-3121-45b9-b95e-ff4ad4f41ba0	09e9198614966972d6d088f7f711dd5f942012d7	373	4	3939.84	1.1868	3939.84	1.1868	89	3.74954	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	3606b5e1-267d-41e2-af4a-f951e935bd10	09e9198614966972d6d088f7f711dd5f942012d7	197	1	3726.75	0.6164	3726.75	0.6144	27	5.25156	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0
second.pod5	78156e5d-eedd-496c-8799-8d4a7810f1b9	09e9198614966972d6d088f7f711dd5f942012d7	205	2	3737.6	0.8538	3737.6	0.8518	20	3.39314	unclassified	*	-1	-1	-1	-1	*	0	0	0	0	0	0	0	0	0	0	0`

Sorry for the trouble and appreciate any insight!
