### ISSUE TITLE
Installing dorado-0.4.1 for the ONT reads duplex basecalling 

### ISSUE THREAD

**Issue by YonataNz1** [nanoporetech/dorado#438]
I am new to Dorado and would appreciate help/ clarity to get the software running for duplex basecalling.

I have downloaded Dorado-0.4.1 on a PC ( NVIDIA RTXA4000 – 16GB) Windows;  the Dorado Readme file specifies that it is Based on libtorch, the C++ API for pytorch, and  Multiple custom optimisations in CUDA and Metal for maximising inference performance.

My questions are: 1) Do i have to install Libtorch and CUBA Toolkit  before I can run Dorado or I can simply  run this via Command prompt 

2) When to use the Dorado Basecall Server ?

Many thanks

**Comment by tijyojwad** [comment]
Hi @YonataNz1 - you don't need to install lib torch or CUDA toolkit. Dorado comes with those dependencies pre-packaged. You would however need to install the right NVIDIA driver version. A helpful list is available [here](https://github.com/nanoporetech/dorado#platforms).

The basecall server is useful when you have multiple basecalling jobs that need to run simultaneously using the same underlying resources.

If you have some datasets that you're processing offline, standalone dorado is likely sufficient for you.

**Comment by YonataNz1** [comment]
Many thanks @tijyojwad
