### ISSUE TITLE
Incorrect number of reads reported when aligning to reference (duplex mode)

### ISSUE THREAD

**Issue by Delayed-Gitification** [nanoporetech/dorado#439]
Hi,

I noticed that when I include a reference fasta to align to during duplex basecalling, it states "Duplex reads basecalled: 97" even though there are only 32 duplex pairs in my pod5 file (32 pairs, 64 reads total).

When I omit the reference file, or include a reference file with a single short sequence (thus preventing any multi-mapping) it reports the correct number.

So I assume this is a bug relating to multimapping reads.

This may also occur in simplex but I haven't tried.

This is the latest version 0.4.1 running on m2 mac

**Comment by tijyojwad** [comment]
Hi @Delayed-Gitification 

Yep I think this is a function of the final number of `alignment` records produced, which can be because of secondary/supplementary alignments. We will fix this to clarify basecalled vs aligned records.

**Comment by tijyojwad** [comment]
Hi @Delayed-Gitification - forgot to update you. This has been fixed in dorado release v0.4.3
