### ISSUE TITLE
Q-score filtering

### ISSUE THREAD

**Issue by eesiribloom** [nanoporetech/dorado#445]
On Guppy, the default Minimum q-score (--min_qscore) is set by the model (fast, HAC, or Sup) and outputs reads into pass and fail folders. Does the same thing apply for dorado models? i.e. if I select say dna_r10.4.1_e8.2_400bps_hac@v4.2.0 does this sort reads into pass/fail by default (in Guppy, HAC would be min_qscore=9 I believe). what is the difference between this and the --min-qscore parameter on dorado?

**Comment by eesiribloom** [comment]
Okay, I understand. 

Do you happen to know if this is calculated in a similar way to `--min_qscore` in guppy? Am I right in thinking `--min-qscore ` on dorado is the mean Q-score per base for a read? 

Is it recommended with dorado to basecall all reads and potentially filter further downstream?

**Comment by tijyojwad** [comment]
> Am I right in thinking --min-qscore  on dorado is the mean Q-score per base for a read?

Yes correct

> Is it recommended with dorado to basecall all reads and potentially filter further downstream?

I think it's up to your use case. If you have a use for the low q-score reads then keeping them basecalled might be beneficial. Otherwise probably best to filter them out at basecalling time so you store less data and process fewer reads downstream.

**Comment by tijyojwad** [comment]
Hi @eesiribloom - wanted to post a correction after some internal discussion. We think it's best you keep all the data (i.e. not filter based on q-score) because sometimes even the low q-score reads can make a difference in downstream analysis. May be more applicable in the case of non-human data.
