### ISSUE TITLE
Q: Demux stats on dorado demux results

### ISSUE THREAD

**Issue by sklages** [nanoporetech/dorado#446]
Basecalling P2 runs outside of MinKNOW using `dorado demux`: is there an easy way to create an extensive report on what has been demux'ed (including the standard run metrics).

So basically pretty much what MinKNOW is creating after a finished run.

**Comment by tijyojwad** [comment]
Hi @sklages - we're planning to add barcode information to `dorado summary` soon. Once that's available, if you run `dorado basecaller` with `--kit-name` you'll get classified outputs, and then the summary can be generated from that BAM. Would that work for you?

`demux` can then be used to split that BAM into multiple BAMs for downstream use.

**Comment by tijyojwad** [comment]
Hi @sklages - the barcode information is now available in a `barcode` column in `dorado summary`.
