### ISSUE TITLE
Cant generate sequencing summary: Missing RG tag

### ISSUE THREAD

**Issue by JannesSP** [nanoporetech/dorado#448]
Hey,

I basecalled older data with dorado (0.4.1) like this
`dorado basecaller ~/bin/dorado_models/rna002_70bps_hac@v3 raw/fast5/ > basecalls/out.bam`

Then I wanted to create the sequencing summary from the `basecalls/out.bam` like
`dorado summary -v basecalls/out.bam > basecalls/sequencing_summary.txt`
And got the following error:
`[2023-11-01 12:58:24.426] [debug] > input fmt: BAM version 1 compressed sequence data aligned: false
[2023-11-01 12:58:24.428] [error] > Cannot generate sequencing summary for files with no RG tags`

Any ideas?

Best,
Jannes

**Comment by tijyojwad** [comment]
Hi @JannesSP - unfortunately we don't support generating summary files for data basecalled from fast5. If you resbasecall after converting the raw data to pod5, the summary command will work as expected. Here are instructions on how to convert fast5 to pod5 - https://pod5-file-format.readthedocs.io/en/latest/docs/tools.html#pod5-convert-fast5

**Comment by malton-ont** [comment]
Hi @JannesSP,

Assuming all your input data is from the same experiment, another option would be to manually add read group information to the bam file using `samtools addreplacerg`:
```
samtools addreplacerg -r "ID:runid_modelname" -o basecalls/out_with_rg.bam basecalls/out.bam
```
Note that `dorado summary` expects the read groups to be in the format `<run_id>_<model_name>`.

**Comment by JannesSP** [comment]
Hey @malton-ont,

I used your command like this:
```
samtools addreplacerg -r "ID:853a2ebb75f05d08ee00f7ff1ba9182d6e00994d_rna002_70bps_hac@v3" -o out.bam in.bam
```
The runid is `853a2ebb75f05d08ee00f7ff1ba9182d6e00994` and the model is `rna002_70bps_hac@v3`.
When I know execute the commend
```
dorado summary -v out.bam > sequencing_summary.txt
```
I get the following error:
```
[2023-11-02 12:16:33.207] [debug] > input fmt: SAM version 1.6 sequence text aligned: false
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted
```
The header for the `out.bam` looks like this now:
```
@HD     VN:1.6  SO:unknown
PG     ID:basecaller   PN:dorado       VN:0.4.2+bb2a133        CL:dorado basecaller /path/to/dorado_models/rna002_70bps_hac@v3 /path/to/fast5/
@RG     ID:853a2ebb75f05d08ee00f7ff1ba9182d6e00994d_rna002_70bps_hac@v3
```
Is my RG ID format incorrect?

Kind Regards,
Jannes

**Comment by malton-ont** [comment]
Hi @JannesSP,

Apologies, it looks like the RG header will also need the experiment start time (in ISO8601 format). e.g.:
```
samtools addreplacerg -r "ID:853a2ebb75f05d08ee00f7ff1ba9182d6e00994d_rna002_70bps_hac@v3\tDT:2022-04-27T16:47:57.305+00:00" -o out.bam in.bam
```

**Comment by JannesSP** [comment]
Hey @malton-ont,

thanks! It worked a bit.
I was able to generate the sequencing summary now, but it seems, that there is still some error.
When I look into the sequencing summary, the `duration` and `template_duration` values are wrong, here the first few lines of the resulting summary:
´´´
filename        read_id run_id  channel mux     start_time      duration        template_start  template_duration       sequence_length_template        mean_qscore_template
FAX28269_d6d578e5_9142ff1b_69.fast5     005288fb-4262-4f7e-9e79-83ab32c3f0b9    9142ff1baa0d7bd736cf432cedab80448826108a        364     1       -1.69774e+09    4.28652 -1.69774e+09    4.28652 167     10
FAX28269_d6d578e5_9142ff1b_69.fast5     00665340-e9cf-44b8-96e5-de7fae3ab121    9142ff1baa0d7bd736cf432cedab80448826108a        362     2       -1.69774e+09    3.16368 -1.69774e+09    3.16368 125     5
´´´
In all the entries they are very close to 0. Here all the unique `duration` values:
`[-1.69769e+09 -1.69767e+09 -1.69770e+09 -1.69771e+09 -1.69773e+09
 -1.69768e+09 -1.69766e+09 -1.69772e+09]`

Just to be sure, the experiment start time can be found in the `final_summary....txt` as "started=2023-10-20T11:18:19.440713+02:00" and the `report_....md` as "exp_start_time: 2023-10-20T11:18:19.440713+02:00"?
They both matched and were in the ISO8601 format, as you said.

Do you have another idea how to fix this?
I need the duration values to generate plots about the sequencing speeds.

Thanks for the great help so far!
Kind regards, Jannes

**Comment by malton-ont** [comment]
@JannesSP,

I'd need the data to debug any further. As @tijyojwad said, generating the summary this way is unsupported and you may have better luck just converting the data to pod5 and rebasecalling.

**Comment by JannesSP** [comment]
Hey @malton-ont,

Huge thanks for your help!
Sadly, another time format did not fix the problem.
I am now converting to pod5.

Have a nice day!
Jannes
