### ISSUE TITLE
Custom barcodes for demultiplexing

### ISSUE THREAD

**Issue by LArnoldt** [nanoporetech/dorado#449]
Guppy offers barcode demultiplexing using custom barcodes (see section "Adding your own barcodes" https://community.nanoporetech.com/docs/prepare/library_prep_protocols/Guppy-protocol/v/gpb_2003_v1_revax_14dec2018/barcoding-demultiplexing) via defining own barcode kits and a deviating data path. 

Would be great to bring back this functionality to dorado. Alternatively, a documentation describing how barcode kits are defined in dorado would be greatly appreciated for manual approaches.

**Comment by tijyojwad** [comment]
Hi @LArnoldt - we've received several requests for defining custom barcode kits and we're working on adding that functionality to dorado! We plan to have it available within the next several weeks.

**Comment by tijyojwad** [comment]
Hi @amardeepranu - no way to do this in dorado till we add the custom barcode support

**Comment by tijyojwad** [comment]
Hello! Custom barcode support was released with Dorado v0.5.0 . Please refer to https://github.com/nanoporetech/dorado#custom-barcodes for more details.

I'm closing this ticket. If you have specific questions on the custom barcode support, feel free to create new tickets :).
