### ISSUE TITLE
SQK-NBD112 kits not available for barcoding

### ISSUE THREAD

**Issue by JWDebler** [nanoporetech/dorado#450]
Hi,
I was just about to basecall some old data when we realised that SQK-NBD112-24 and -96 are not available to select as --kit-name for the barcoding step.
I tried it anyways (in the hope that someone just forgot to add them into the 'help') but it didn't work.
Any idea why they aren't there?
Cheers,
Johannes

**Comment by tijyojwad** [comment]
Hi @JWDebler - The NBD112 kit is for Kit 12 data, and unfortunately none of our models support Kit 12 basecalling anymore. So we don't have that those options available for barcoding either.

**Comment by JWDebler** [comment]
@tijyojwad thanks for that. Are there any plans to add models for kit 12? Or will this data have to be called using 'old' Guppy?

**Comment by tijyojwad** [comment]
No plans to add those models to dorado. Using an older version of guppy is your best bet
