### ISSUE TITLE
dorado demux error

### ISSUE THREAD

**Issue by flokraft85** [nanoporetech/dorado#452]
Hi dorado team,
I have some problems when trying to demultiplex BAM files generated by dorado basecaller.
When I try to use dorado demux with this command
dorado demux --output-dir ./output/ --kit-name SQK-NBD114-24 -t 50 ./input.bam 

I got the following error
[E::bam_set1] CIGAR and query sequence are of different length
Segmentation fault (core dumped)

However, if I use samtools for demultiplexing it worked fine.
samtools split -u ./output/unclassified.bam -f output/"%!".bam ./input.bam

The bam I try to demultiplex was directly generated by dorado basecaller using the command below
dorado basecaller /home/prom/dorado/0.4.0/models/dna_r10.4.1_e8.2_400bps_hac\@v4.2.0 --modified-bases 5mCG_5hmCG -b 5120 --reference /ref.mmi --kit-name SQK-NBD114-24 -r ./input/pod5 > ./output.bam

Is there anything I do wrong, or is it some issue with dorado demux?
Thanks in adavance for your help.

Best,
Florian

**Comment by sklages** [comment]
As you already have classified your barcodes with your basecall command, you need to specify `--no-classify` with your demux command.

**Comment by tijyojwad** [comment]
As @sklages correctly pointed out, when you invoke the `basecaller` cmd with `--kit-name`, it will classify barcodes and trim barcode sequences as part of the basecalling run. To demux an already barcoded output, you need to pass the `--no-classify` argument to `dorado demux`.

**Comment by flokraft85** [comment]
Thanks for the quick reply! Yes, indeed I tried it first with --no-classify, however I got the error message "Unknown argument: --no-classify". However, I realized in between, that this option and the possibility to demux already classified reads, is only available >0.4.1 and I had 0.4.0. I updated dorado and now everything works fine. Thanks again for the immediate help!
