### ISSUE TITLE
Basecalling using R9.4.1 cDNA PCS111 Kit

### ISSUE THREAD

**Issue by pilaralv** [nanoporetech/dorado#453]
Hi all,

We have some cDNA runs using R9 and PCS111 kit that we wanted to try to basecall with Dorado, is this possible?
We get this error when we try to convert the fast5s to pod5 (we can do this fine with our R9 DNA):
FATAL:  while initializing starter command: while copying engine configuration: engine configuration too big > 1048448

Here is exact script we are running:
```
pod5 convert fast5 ${PATH_TO_FLOWCELL}/fast5/*.fast5 -r --output ${OUT_PATH}/pod5_${SAMPLE} --one-to-one ${PATH_TO_FLOWCELL}/fast5

dorado basecaller -x cuda:all ${DORADO_MODELS}/dna_r9.4.1_e8_sup@v3.6 ${OUT_PATH}/pod5_${SAMPLE} --skip-model-compatibility-check > ${OUT_PATH}/${SAMPLE}_pod5.bam

```

Thanks!

**Comment by tijyojwad** [comment]
Hi @pilaralv - sounds like your fast5 to pod5 conversion fails? If so, I wouldn't trust any basecalling run on that output. Would you mind posting the conversion issue on https://github.com/nanoporetech/pod5-file-format/issues ?
