### ISSUE TITLE
Dynamically set window length instead of hardcoding it to 19

### ISSUE THREAD

**Issue by lpryszcz** [nanoporetech/dorado#455]
Hi, we have bunch of models trained by bonito that work well with guppy but use `winlen` different that 19 and can't be used with dorado. 

```bash
$ ~/src/dorado-0.4.2-linux-x64/bin/dorado basecaller models fast5_dir 
[2023-11-07 12:02:31.520] [info] > Creating basecall pipeline
[2023-11-07 12:02:31.564] [error] The size of tensor a (19) must match the size of tensor b (31) at non-singleton dimension 2
Exception raised from infer_size_impl at /pytorch/pyold/aten/src/ATen/ExpandUtils.cpp:31 (most recent call first):
```

Could you please set `winlen` in dorado dynamically (similarly to stride) instead of hardcoding it?
https://github.com/nanoporetech/dorado/blob/bb2a1339a10e077479ea11048fdbb6c460bf7b94/dorado/nn/CRFModel.cpp#L836

**Comment by iiSeymour** [comment]
Hey @lpryszcz we are improving our model loading code right now actually so this should be resolved soon.
