### ISSUE TITLE
Enable custom models in dorado_basecall_server

### ISSUE THREAD

**Issue by lpryszcz** [nanoporetech/dorado#457]
Hi, while using custom models with `dorado_basecall_server`, we get an error. The same models work fine with `dorado basecaller`. How to use custom models in `dorado_basecall_server`?

```bash
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unrecognized model type.
Aborted (core dumped)
```

**Comment by MarkBicknellONT** [comment]
Hi @lpryszcz , this error comes from a part of the code that expects to find one of the following substrings in the model name:
- "_fast@v"
- "_hac@v"
- "_sup@v"
This is used to help the server select an automatic batch size that is suitable for the model.  We are working to remove dependencies on the model names from the code, and use the config.toml file to specify properties instead.  For now though, changing the model name to include one of these strings will fix your current problem.  Note that you will also need to have "dna" or "rna" in the model name so that dorado treats your model as the correct type.

**Comment by lpryszcz** [comment]
another question @MarkBicknellONT , is it possible to disable adapter trimming in `dorado_basecall_server`, similar behaviour to guppy's cfg 
```bash
trim_strategy                       = none
```

**Comment by MarkBicknellONT** [comment]
Hi @lpryszcz , no this isn't supported at the moment.  The dorado basecaller infers the type of trimming it should do automatically from the model type.  We certainly could add an option though.  If you have pre-trimmed signal which you are passing in, generally the signal-space adapter trimming won't do anything.  Nothing in your signal should match the expected adapter signal pattern.

**Comment by lpryszcz** [comment]
thanks, indeed I see that most (if not all) pre-trimmed reads start to basecall from the beginning. 

I've been asking because, the results between basecall servers (guppy and dorado) differ and I'm trying to understand why: dorado results make no sense...  
I'm using the same model and the same config file. 
Does dorado normalise signal differently to guppy? I'm disabling short read scaling in guppy using 
```bash
noisiest_section_scaling_max_size   = 1000 
```
Can the same be used with dorado?
Maybe the problem is that dorado still does short read normalisation? Most of my reads are very short...

**Comment by MarkBicknellONT** [comment]
Hi @lpryszcz ,

The scaling method used by the dorado basecaller can't be changed at the command line at the moment.  In the current release we either perform quantile scaling, or use med_mad style scaling if the model is for dna_r9.4.1.  See: https://github.com/nanoporetech/dorado/blob/master/dorado/nn/CRFModelConfig.cpp#L93

This works somewhat different to guppy, where the scaling method could be set directly in the .cfg file that was used for the model.  In the upcoming release of dorado 0.4.3 we will be exposing the ability to set the scaling method by setting a `scaling` parameter in the config.toml file for a model.

Kind regards,

Mark
