### ISSUE TITLE
Update docker container to latest release version (v0.4.2)

### ISSUE THREAD

**Issue by SESchmedes** [nanoporetech/dorado#460]
Can you please update the docker container on https://hub.docker.com/r/nanoporetech/dorado/ to the latest released version of dorado (v0.4.2)? The latest container is v0.3.4. Thank you!

**Comment by SamStudio8** [comment]
Hi @SESchmedes, the Dorado container is provided for the [wf-basecalling Nextflow workflow](https://github.com/epi2me-labs/wf-basecalling) which currently supports Dorado v0.3.4. We are working on bringing all the latest Dorado features to wf-basecalling.

**Comment by KerenElience** [comment]
You can search `dorado` on <hub.docker.com>, it's useful that the images by other users submitted. Need not wait official version.
