### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by Meer9234** [nanoporetech/dorado#461]
Hi I used this tool for my genome assembly. How do I cite it for a publication?

Kind regards

**Comment by vellamike** [comment]
Good question, perhaps something like this?

```
@misc{ONT2023,
  author = {Oxford Nanopore PLC.},
  title = {Dorado},
  year = {2023},
  publisher = {GitHub},
  journal = {[GitHub repository](https://github.com/nanoporetech/dorado)},
  howpublished = {\url{https://github.com/charlespwd/project-title}},
  commit = {COMMIT}
}
```

**Comment by vellamike** [comment]
P.S if you use a prebuilt binary instead of source, you can also add the version number and provide a link to the binary if you wish
