### ISSUE TITLE
Clarification on the deprecation of the ```260 bps``` option as of ```MinKNOW``` version 23.04

### ISSUE THREAD

**Issue by drivenbyentropy** [nanoporetech/dorado#462]
My apologies if this is not the right location to ask this. My questions concerns the translocation speed and subsequent model selection in ```dorado```.

We are currently moving from the ```MinION``` platform to the ```PromethION 24``` sequencer and I am trying to ensure that we select the appropriate settings for an optimal computational analysis downstream. Under the `Decoding Dorado model names` section, the [dorado readme](https://github.com/nanoporetech/dorado#decoding-dorado-model-names) states 

> Translocation Speed (400bps): This parameter, selected at the run setup in MinKNOW, refers to the speed of translocation. Prior to starting your run, a prompt will ask if you prefer to run at 260 bps or 400 bps. The former yields more accurate results but provides less data. ___As of MinKNOW version 23.04, the 260 bps option has been deprecated.___

Issue [214](https://github.com/nanoporetech/dorado/issues/214#issuecomment-1573674798) also mentions this and links to a [software release note](https://community.nanoporetech.com/posts/software-release-23-04-5-f-12294) with further details. However, this release note is specific to the ```MinION Mk1C``` release of ```MinKNOW``` and I was not able to find an equivalent release note for the ```PromethION``` platforms stating the same. 

Am I correct in assuming that the 260pbs option has been or will be deprecated on all future platforms including the ```PromethION 24```? Any clarification on this matter would be greatly appreciated.

Thank you!

**Comment by susie-ont** [comment]
Hi @drivenbyentropy - thank you for your question. Yes, the 260bps option was also deprecated on the PromethION 24 as of MinKNOW 23.04. Here is the equivalent 23.04 software release note for PromethION: https://community.nanoporetech.com/posts/software-release-23-04-5-f-12293
I hope this helps!

**Comment by drivenbyentropy** [comment]
@susie-ont , thank you very much for confirming this!
