### ISSUE TITLE
[error] Sample rate for model (4000) and data (6024) are not compatible.

### ISSUE THREAD

**Issue by flokraft85** [nanoporetech/dorado#463]
Hi dorado Team,
I have some issues with old data converted to pod5. I had a lot of data set which I currently coverting to pod5 for re-basecalling with dorado. However, for some of the sample, althoug the conversion worked fine, dorado print the following error:
[error] Sample rate for model (4000) and data (6024) are not compatible.
As all of the data was produced by the LSK-108 kit together with the R9.4.1 FC and run on the same GridION with same protocol, I did not understand, why the sampling rate should be different. All the FAST5 files, also that where dorado complaining the wrong sampling rate, are basecalled with guppy without any issue. I'm not 100% sure, if the error is related to dorado or maybe to pod5.

Best wishes,
Florian

**Comment by tijyojwad** [comment]
Hi @flokraft85 - thanks for reporting the issue! The sampling frequency detected looks wrong. Could you run `pod5 inspect summary <failing pod5 file>`? that'll give us some more context on the original experiment

Would you also be able to upload the original fast5 that led to this offending pod5?

**Comment by flokraft85** [comment]
Hi,
thanks for the immediate response. pod5 inspect was a good idea. It seems that the runs were made on R9.5 flow cells, which should explain the other sampling rate and therefore the issue with dorado. Hence the error is not related to dorado. So we have to switch to guppy for this runs.
Thanks agian!
