### ISSUE TITLE
basecaller dorado-0.4.2-linux-x64 progress bar freeze at 50%

### ISSUE THREAD

**Issue by husamia** [nanoporetech/dorado#465]
I am running the latest dorado build for linux using gpu on Windows 11 with GPU and Nvidia support within WSL

After about 50% the progress bar stops updating, although the output file and the nvidia GPU utilization shows the basecalling is still ongoing! 

/mnt/c/dorado-0.4.2-linux-x64/bin$ ./dorado basecaller --batchsize 96 --recursive --device cuda:all dna_r10.4.1_e8.2_400bps_sup@v4.2.0/ /mnt/d/ONT/PGx_Twist_UDI/raw_combined_pod5/ > /mnt/d/ONT/PGx_Twist_UDI/dorado-0.4.2_dna_r10.4.1_e8.2_400bps_sup@v4.2.0.bam
[2023-11-03 11:10:58.192] [info] > Creating basecall pipeline
[2023-11-03 11:12:06.643] [warning] - set batch size for cuda:0 to 128
[███████████████▏              ] 50% [05d:22h:30m:11s<05d:19h:42m:50s]

**Comment by tijyojwad** [comment]
Hi @husamia - are you still running into this issue?

* When you said GPU utilization says basecalling is going on, do you see consistency high GPU + power utilization?
* How large is your dataset? Hav you tried with smaller dataset to see if that runs through?
* To rule out I/O issue, can you redirect the output to `/dev/null` and check if the same dataset completes?

**Comment by husamia** [comment]
@tijyojwad I am running into the issue still this is related https://github.com/nanoporetech/dorado/issues/400 

at around 50% it seems the updating stops but the GPU high + power utilization 
POD5 data is about 57GB in size (I did test it with lower data amount the problem didn't occur) but I am not sure it helps at all

**Comment by tijyojwad** [comment]
Hi @husamia can you try with a more recent version v0.7.x to see if the issue prevails?
