### ISSUE TITLE
Methylation motifs detection criteria

### ISSUE THREAD

**Issue by BioRB** [nanoporetech/dorado#466]
I'm working with bacteria and want to study methylation profiles using ONT and Dorado. As an example using the 5mC model, it identifies several sites. How these sites are 'selected'? With what criteria?
I have read another issue where a user asked if it was possible to define the methylation motifs to be detected. Thus I have a more general question: how Dorado define the motifs? or it identify any C and evaluate the methylation?

**Comment by marcus1487** [comment]
The all-context modified base models make a prediction of the modified state for each applicable canonical base (cytosines for 5mC and 5mC+5hmC models and adenines for 6mA model). The `--modified-bases-threshold` dorado parameter will filter some of these calls to save on disk space. These skipped call are defined as "inferred canonical" as per the SAM format specification and can be assumed to be canonical. 

For downstream motif analysis, we provide the [modkit tool](https://github.com/nanoporetech/modkit). Modkit provides a number of commands for the analysis of specific motifs. If there is a specific analysis in which you are interested and you don't see an applicable command in the modkit suite, please raise an issue there.
