### ISSUE TITLE
Redo basecalling?

### ISSUE THREAD

**Issue by austinchipps** [nanoporetech/dorado#467]
I recently inherited nanopore sequencing data that was basecalled in real time with Guppy in MinKnow using the "Fast" basecalling model. This was MinKnow v21.11.9 and Guppy v5.1.15. My question is: is it possible to redo the basecalling using dorado's models on this data? I'm hoping to redo basecalling to make it more accurate. Thank you in advance!

**Comment by vellamike** [comment]
Hi, yes, if you have the raw data in FAST5 POD5 format you can rebasecall with a HAC or SUP model and it will be more accurate. The Readme has details on how to do this.
