### ISSUE TITLE
downstream analysis with --modified-bases

### ISSUE THREAD

**Issue by eesiribloom** [nanoporetech/dorado#469]
Are the unaligned bams produced from dorado basecaller --modified-bases suitable for downstream analyses such as structural variant calling or reconstruction of SV events or do I need to run without the modified base option. 

It would be ideal for time and resources if I could avoid having to run basecalling twice if I want to perform variant analysis and investigate DNA methylation in the same data.

**Comment by tijyojwad** [comment]
They should be suitable for downstream analyses. The additional tags generated by modified basecalling are official tags supported by the SAM format.

If you see otherwise, please let us know.
