### ISSUE TITLE
How to use Dorado model in Guppy

### ISSUE THREAD

**Issue by juanjo255** [nanoporetech/dorado#470]
Hello!

I'm trying to use a dorado model in guppy using the flag `--dorado_model_path`, but guppy is asking for a `--model_file `which is a path to a JSON model file. file format that I don't find in the folder of the downloaded Dorado model (dna_r9.4.1_e8_sup@v3.6).

What do I have to do?

Thanks you very much,

Juan

**Comment by tijyojwad** [comment]
Hi @juanjo255 - may I ask why you're using guppy and not dorado?

**Comment by juanjo255** [comment]
@tijyojwad,

Thanks for the reply.

I have a barcoded sequencing, and I like the nested folders layout returned by Guppy which separates the fastq per barcode, but I would like to use a more updated model like dorado's models :)

**Comment by tijyojwad** [comment]
`dorado` now supports barcode classification and demuxing as well. https://github.com/nanoporetech/dorado#barcode-classification 

If you want your data demuxed by barcode, you can run
```
dorado basecaller <model> <data> --kit-name <kit_name> | dorado demux --no-classify --output-dir <base_output_dir>
```
This will baseball + classify each read in the first cmd, and then demux the reads into separate BAM files (or fastq if you pass `--emit-fastq`) per barcode.

If you have some basecalled data already that's not classified, you can run
```
dorado demux --kit-name <kit_name> --output-dir <base_output_dir> unclassified.bam
```
to classify all reads in the `unclassified.bam` file (it also accepts sam and fasts files).

**Comment by juanjo255** [comment]
Awesome. Thanks!!
