### ISSUE TITLE
modification model for rna002

### ISSUE THREAD

**Issue by icemduru** [nanoporetech/dorado#475]
Hi,

I am wondering if there are any plans to publish the modification model for rna002. If not, what is the best way to detect RNA methylation in non-model organisms with rna002 ?

Regards
Ilhan Cem Duru

**Comment by iiSeymour** [comment]
Hey @icemduru 

No, but there are some great community options for RNA002 that you could check out:

 - https://www.biorxiv.org/content/10.1101/2023.11.13.566801v1
 - https://github.com/GoekeLab/m6anet
