### ISSUE TITLE
 Issue with dorado-0.4.3 on Apple M2 Max - Weird repeated deletions

### ISSUE THREAD

**Issue by flucasmelo** [nanoporetech/dorado#477]
Hey there,

I've run into a weird problem with **dorado-0.4.3-osx-arm64** on my **Apple M2 Max**. The same thing happens with the previous version too. When I'm using the SUP and DUPLEX models, I'm seeing some strange data deletions that just don't happen when I do the same thing on a Linux system.

Here's what I'm talking about: 
1. ![Data issue 1](https://github.com/nanoporetech/dorado/assets/151174764/0d1c0c58-0084-421e-885e-aa8ba895bb97)
2. ![Data issue 2](https://github.com/nanoporetech/dorado/assets/151174764/d1497ae9-fbcf-4d85-b52e-83c46964fb7f)
3. ![Data issue 3](https://github.com/nanoporetech/dorado/assets/151174764/4f37c32d-a3d9-48d0-9f91-255c007778f4)

Has anyone else had this kind of issue with dorado on an M2 Max, or is it just me? Maybe I'm missing something?

Thanks,

Fernando

**Comment by flucasmelo** [comment]
Dear Dorado Developers,

I wanted to follow up on an issue I reached out about two weeks ago. I'm still facing challenges with basecalling my data and I'm not sure if it's a dorado's bug on M2 or something I'm doing wrong.

I would greatly appreciate your assistance or any insights you might have on this matter.

Thank you in advance for your help!

Best regards,

Fernando

**Comment by tijyojwad** [comment]
Hi @flucasmelo - apologies for the delay in responding.

We've noticed in the past that for SUP model with duplex, some of the kernel invocations can time out causing missing basecalls. However, we did a quite of work to report any such occurrences in the logs. Do you have the `stderr` from this runs available to share?

**Comment by StuartAbercrombie** [comment]
It would also be useful to know how much memory the system has.

There is a known issue with high memory usage that means on some systems simplex alone will perform much more slowly than it should, which appears to exacerbate GPU error conditions associated with duplex, perhaps contributing to the bad output.

Future dorado releases will use less memory, but memory usage can be reduced in the meantime by specifying a smaller batch size.  If this is an M2 Max system with the full 30 cores, the automatically selected batch size will be 1444.   This is likely to perform poorly on many typical memory configurations.  I'd suggest trying much smaller batch sizes with the -b option.  Any multiple of 48 should work.  We're working on improving the automatic batch size selection.

If hac is an option, that is likely to work better.

**Comment by flucasmelo** [comment]
Hi @StuartAbercrombie and @tijyojwad,

Thank you for your responses. To address your points:

@StuartAbercrombie, you inquired about the system's memory. The system has 96 GB of memory. I appreciate your suggestion to try smaller batch sizes, especially considering the high memory usage issue you mentioned. I'll explore this option further.

@tijyojwad, regarding your point on the SUP model with duplex and kernel timeouts, I have reviewed the and stderr.log (https://github.com/nanoporetech/dorado/files/13520070/stderr.log), and apparently no errors were recorded (at least I think not).

Thank you both for your guidance.

**Comment by flucasmelo** [comment]
Hi @StuartAbercrombie and @tijyojwad,

I've conducted further testing based on your suggestion regarding batch sizes in dorado-0.4.3 on my M2 Max 12 core 38 GPU 96GB RAM. I experimented with various smaller batch sizes, including 48, 960, 1200, 1248, 1296, 1344, and 1440. My observations indicated that no deletions were observed when using batch sizes ranging from 48 to 1248.

This finding underscores the importance of **proper batch size estimation** in dorado. To assist users, I suggest **adding a note or warning in the documentation about potential errors caused by improper batch size estimation**. If this point is already addressed elsewhere, please disregard this suggestion.

I hope this information helps in improving dorado's performance and user experience.

Cheers, 

Fernando

**Comment by StuartAbercrombie** [comment]
dorado 0.5.0 has the improvements I mentioned above.
