### ISSUE TITLE
Minimal requirements for NVIDIA GeForce RTX 2080ti?

### ISSUE THREAD

**Issue by Saraal** [nanoporetech/dorado#478]
Hi,

I was  forwarded to the github by the nanopore community pages. I have been basecalling using guppy on a 4 node gpu cluster, controlled by slurm. I am now switching to Dorado, however when running this, I get the error "[Error] CUDA device requested but no devices found". I tried running both with CUDA 10.2 (what I have been using for guppy) and CUDA 11.7. Is there a minimum requirement for Dorado, both for CUDA version and CUDA/NVIDIA driver? I have looked at the documentation, and as far as I can see, I am above the minimum requirements, but it is not entirely clear to me.

Thanks,

Best, Mathijs

**Comment by ymcki** [comment]
Is your Nvidia driver meets minimum requirement ?

**Comment by Saraal** [comment]
> Is your Nvidia driver meets minimum requirement ?

That is what I'm trying to find out. Currently we have CUDA version 12.0 driver driver 525.85.12.

**Comment by ymcki** [comment]
On paper you met the minimal requirements. Can you run the following command and see if your slurm is configured for gpus?

srun -w [your node name]  --cpus-per-task 1 --mem-per-cpu=1G --gpus=4  --pty "nvidia-smi"

**Comment by HalfPhoton** [comment]
Closing this issue as there have been no replies to questions.
Please re-open this issue if you have more information.
