### ISSUE TITLE
pychopper and --barcode-both-ends

### ISSUE THREAD

**Issue by MustafaElshani** [nanoporetech/dorado#479]
I wanted to ask if `--barcode-both-ends` is used in dorado , is there still a requirement to use [pychopper ](https://github.com/epi2me-labs/pychopper)?

Does dorado apply any orientation ? Currently using SQK-PCB111-24 kit

**Comment by tijyojwad** [comment]
Dorado doesn't apply any orientation yet. During barcode `--barcode-both-ends` is only used to increase specificity of classification by ensuring both ends of the read have a barcode hit.
