### ISSUE TITLE
PromethION-MinION models

### ISSUE THREAD

**Issue by lucapandolfini** [nanoporetech/dorado#48]
I would like to know whether we can use the currently available dorado models for both PromethION and MinION runs, since I don't see any distinguishing tag (e.g. "_prom" in guppy). Or are they specific for either platform?
Thank you very much!

**Comment by vellamike** [comment]
Yes! there yes no difference and you can use the models for both PromethION and MinION data.

**Comment by lucapandolfini** [comment]
Awesome thanks!
