### ISSUE TITLE
Modifications lost in demux

### ISSUE THREAD

**Issue by olawa** [nanoporetech/dorado#480]
Hi,

I am running dorado demux on a dorado fastq with modification tags but the tags are lost in the demultiplexed bam/fastq files. I can not find any setting to output all tags and also can not se a reason for not keeping these?

**Comment by tijyojwad** [comment]
Hi @olawa - Can you post what command you are running? Are you classifying as well or just demuxing?

**Comment by tijyojwad** [comment]
ping @olawa

**Comment by olawa** [comment]
Hi @tijyojwad , I checked this now with v 0.5 and the bam from demux now has the mods but but running demux with --emit-fastq gives a fastq without mods, it would be good if it could output the full fastq since minimpa2 only takes fastq as input (and also older versions of samtools fails silently with samtools fastq -T '*').
