### ISSUE TITLE
Dorado taking a long time in basecalling

### ISSUE THREAD

**Issue by indianAppl** [nanoporetech/dorado#482]
Dear Admin,

I am trying to basecall from POD5 files of one MiniION run. We have run a single cell line genome on Adaptive Sampling mode showing 5gb of total acquired data and now basecalling from the POD5. The run is being conducted on a 64 core server without GPU, hence I have run it on '-x cpu' and it has taken more than 6 hours and produced no reads. 

How long does it take per 1 Gb basecall without GPU ?

Best regards
Sangramjit

**Comment by sklages** [comment]
Well, do not use CPUs for basecalling. 

I tested this somewhere around 0.3.x with a single POD5 file (4K sequences). A full 40GB A100 took two minutes to basecall this set, CPU-bound basecalling took more than six hours!

You cannot control CPU threads for basecalling, just for alignment step. So dorado uses five CPUs on average over the time.

**Comment by tijyojwad** [comment]
Hi @indianAppl @sklages - the number of threads also depends on the available host memory and the model used.

In general, CPU basecalling will be very slow for any reasonable size dataset, so GPU acceleration is highly recommended.
