### ISSUE TITLE
Sample rate for model (5000) and data (4000) are not compatible

### ISSUE THREAD

**Issue by 1Wencai** [nanoporetech/dorado#484]
Hello

I need to detect DNA 6mA singal

my command：
"dorado basecaller ./dna_r10.4.1_e8.2_400bps_sup@v4.2.0 ./fast5_2_pod5/output.pod5 --modified-bases 6mA > sample1_cell1_6mA.bam"

[2023-11-23 08:38:48.500] [info] > Creating basecall pipeline
[2023-11-23 08:38:48.503] [error] Sample rate for model (5000) and data (4000) are not compatible.

Is there the 4kHz model for 6mA?

Best regards
Wen-Cai

**Comment by ymcki** [comment]
dna_r10.4.1_e8.2_260bps_fast@v4.1.0                dna_r10.4.1_e8.2_400bps_sup@v4.1.0_5mCG_5hmCG@v2  dna_r9.4.1_e8_fast@v3.4_5mCG_5hmCG@v0
dna_r10.4.1_e8.2_260bps_hac@v4.1.0                 dna_r10.4.1_e8.2_400bps_sup@v4.2.0                dna_r9.4.1_e8_hac@v3.3
dna_r10.4.1_e8.2_260bps_sup@v4.1.0                 dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mC@v2         dna_r9.4.1_e8_hac@v3.3_5mCG@v0.1
dna_r10.4.1_e8.2_400bps_fast@v4.1.0                dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v2  dna_r9.4.1_e8_hac@v3.3_5mCG_5hmCG@v0
dna_r10.4.1_e8.2_400bps_fast@v4.1.0_5mCG_5hmCG@v2  dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v3  dna_r9.4.1_e8_sup@v3.3
dna_r10.4.1_e8.2_400bps_fast@v4.2.0                dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mC_5hmC@v1    dna_r9.4.1_e8_sup@v3.3_5mCG@v0.1
dna_r10.4.1_e8.2_400bps_fast@v4.2.0_5mCG_5hmCG@v2  dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v2         dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0
dna_r10.4.1_e8.2_400bps_hac@v4.1.0                 dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v3         rna002_70bps_fast@v3
dna_r10.4.1_e8.2_400bps_hac@v4.1.0_5mCG_5hmCG@v2   dna_r10.4.1_e8.2_4khz_stereo@v1.1                 rna002_70bps_hac@v3
dna_r10.4.1_e8.2_400bps_hac@v4.2.0                 dna_r10.4.1_e8.2_5khz_stereo@v1.1                 rna004_130bps_fast@v3.0.1
dna_r10.4.1_e8.2_400bps_hac@v4.2.0_5mCG_5hmCG@v2   dna_r9.4.1_e8_fast@v3.4                           rna004_130bps_hac@v3.0.1
dna_r10.4.1_e8.2_400bps_sup@v4.1.0                 dna_r9.4.1_e8_fast@v3.4_5mCG@v0.1                 rna004_130bps_sup@v3.0.1


These are possible models. Unfortunately, there is no 6mA model for 4kHz.

**Comment by 1Wencai** [comment]
Thank you very much for your reply. Next we will use r10 flow cell to generate data.
Do you have any plans to generate a 6mA model suitable for 4kHz data?

**Comment by 1Wencai** [comment]
Hello，

dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v2 and  dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v3 rna002_70bps_fast@v3
are  6mA model for 5kHz.

Are these two models species-specific? Are these two models  suitable for prokaryotes and eukaryotes？

Best regards
Wen-Cai

**Comment by marcus1487** [comment]
The 4kHz 6mA model was only released as a research model in [Rerio and is available there](https://github.com/nanoporetech/rerio/tree/master?tab=readme-ov-file#dorado-models). 

There are no plans to add this model to Dorado at this time.

These models are not species-specific. The vast majority of training data was synthetic randomer strands. See the various talks over the past 2 years at NCM or LC for high level descriptions of the training data or express interest in the Betta program on the community for more details.
