### ISSUE TITLE
Does the Modified basecalling in Dorado present preference for species applicability

### ISSUE THREAD

**Issue by yanyew** [nanoporetech/dorado#485]
I wonder whether Modified basecalling in Dorado keep the same performace in both plants and animals? Is the training of the models based on both animal and plant data?

**Comment by ymcki** [comment]
Biochemically, is there any difference between 5mC in plant and 5mC in animal? If no, then I would say it doesn't matter.

On the other hand, while 6mA should be the same thing biochemically for prokaryotes and eukaryotes, they are significantly more prevalent in prokaryotes than eukaryotes. So probably 6mA models should be trained on prokaryotes data and expect to also work for eukaryotes. Are 6mA models trained on prokaryotes model? Or on synthetic DNA?

But there isn't a big difference in frequency for 5mC in plant and animal, so this should not be a concern.

**Comment by marcus1487** [comment]
As @ymcki states, biochemically the modified bases are the same. The vast majority of the training data for the model is synthetic so we hope that there is little if any organism specific bias in the model performance. It is possible that the model may vary in performance given the canonical and modified base context, so this may manifest as an apparent organism specific performance metrics (where alternative validation is available). For example, a read with many modified bases in close proximity may show degraded performance as this will start to effect signal scaling and we do not currently have production models to handle this case (though we are looking into this in research). Additionally many modified bases in close proximity are included in training, but only to a limited extent. So degraded performance may be observed here as well.

Another way to look at this would be to view the biological problem and adjust the modified base filtering using modkit to adjust the balance between FPR and FNR. For advice on this please see the modkit documentation or open an issue there if the documentation does not sufficient address the question.
