### ISSUE TITLE
CUDA device requested but no devices found Error in WSL

### ISSUE THREAD

**Issue by kusonahikari** [nanoporetech/dorado#486]
Dear developers,
I have installed Dorado in our WSL and tried to run basecaller but encountered the error. 
<img width="698" alt="cuda0" src="https://github.com/nanoporetech/dorado/assets/18393926/bdb4dc15-68b2-4e7a-8ed4-c5cc4e2547ca">
I have tried to find the CUDA devices and resulted:
<img width="502" alt="GPU" src="https://github.com/nanoporetech/dorado/assets/18393926/5157d4c0-b971-4f32-be5b-77d70c7a19c0">
output of `nvcc --version`
<img width="358" alt="ncvv" src="https://github.com/nanoporetech/dorado/assets/18393926/309336e2-9a73-4377-b54a-d884f43286da">
The current Dorado version is `0.4.3+656766b5`
with my limited experiences, I suppected there some conficts between the library paths but don't know where to start. 
Please kindly let me know how to solve this problems.

**Comment by tijyojwad** [comment]
Are you able to run any other CUDA application? I suggest trying one of the NVIDIA CUDA samples https://github.com/NVIDIA/cuda-samples

**Comment by chlo0423** [comment]
Hi, 

I am having this exact same issue. I have tried to get it working on both a laptop and my desktop but no success. 

Any help would be much appreciated. 

Thanks

**Comment by tijyojwad** [comment]
Hi @chlo0423 - are you able to run other CUDA applications too, such as the CUDA samples?

Can you also run `ldd dorado` from WSL, as well as `nvidia-smi` from WSL?

**Comment by kusonahikari** [comment]
> Are you able to run any other CUDA application? I suggest trying one of the NVIDIA CUDA samples https://github.com/NVIDIA/cuda-samples

Hi @tijyojwad , I have tried run CUDA samples and none of them works.
Attached the outputs of some commands.

![Screenshot 2023-11-29 at 15 01 17](https://github.com/nanoporetech/dorado/assets/18393926/1a0ceaaf-3cfd-4ab0-9b48-5fc3ec1d074d)
![Screenshot 2023-11-29 at 15 00 14](https://github.com/nanoporetech/dorado/assets/18393926/aa25855e-3a45-4d57-81d9-12c535111ecc)

**Comment by tijyojwad** [comment]
In that case I don't think your WSL is setup properly for CUDA. Once the samples work, I expect dorado would just work too.

I haven't personally tried setting up WSL with CUDA, but this link seems helpful - https://developer.nvidia.com/cuda/wsl

**Comment by kusonahikari** [comment]
I installed CUDA for WL following this guide https://docs.nvidia.com/cuda/wsl-user-guide/index.html. 
Tried to run Dorado in Window without WSL and it worked.  I will try to install from developer version then configure the lib path of CUDA.

**Comment by tijyojwad** [comment]
Sounds good, I'll close this for now since this isn't a dorado issue. If dorado still doesn't run after other CUDA apps are successfully working in WSL, please re-open and we'll investigate.

**Comment by kusonahikari** [comment]
Hi, I have successful set up WSL so CUDA can work properly. However, I encountered another error, have created new issue via #523 .
Open this again to anyone whom having the same problem as I had.
So my desktop is Window 10 which we have to enable Window Insider Program and switch to WSL 2. 
You can follow the steps in this blog, https://ubuntu.com/blog/getting-started-with-cuda-on-ubuntu-on-wsl-2.
Afterwards, you can install CUDA follow this guide  https://docs.nvidia.com/cuda/wsl-user-guide/index.html.
Finally, you can run `cuda-sample` to test the CUDA device.
Hope this help.
