### ISSUE TITLE
Modified basecalling on RNA-seq

### ISSUE THREAD

**Issue by abcdtree** [nanoporetech/dorado#487]
Hi naoporetech team,

I am trying to run modified basecalling using dorado on some old rna-seqs. I found out the only model for rna modified basecalling is **rna004_130bps_sup@v3.0.1**. However, the sample rate for my old sequences are 70bps.

Is there any method I can make the modified basecalling work on my 70bps sequences?

Thanks,

**Comment by malton-ont** [comment]
See the comment from @iiSeymour on [this issue](https://github.com/nanoporetech/dorado/issues/475#issuecomment-1814503426) for info on some community options.
