### ISSUE TITLE
About the RNA04 data to train the model

### ISSUE THREAD

**Issue by charlesxu90** [nanoporetech/dorado#489]
Dear @rmp @snurk @tijyojwad @jorj1988 @vellamike,

Thanks for the nice work. In the recent releases, RNA004 is supported by Dorado. I think it was very interesting and we have purchased RNA004 kit for our sequencing task. In addition, we are developing a selective sequencing method for direct RNA sequence, so I hope to use the dataset you trained for the Dorado model for our development task.

Could you please share the link to the RNA004 dataset that you train the model on? I searched online, but cannot find it. I believe RNA004 will be the new standard for direct RNA sequence, it has different data distributions so developing methods based on RNA004 should be a must.

Thanks a lot for the nice work.

Best regards，

**Comment by vellamike** [comment]
Hi @charlesxu90 , thank you for your kind words.

RNA004 is indeed the new standard for RNA and does have different signal characteristics. Unfortunately we currently do not plan to publicly release RNA004 training data.
