### ISSUE TITLE
How do I know which dorado is dorado basecall server using?

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#493]
We recently bought a data acquisition unit from you guys. 

The server seems to only have dorado basecall server executable but no dorado executable.

The version of this server is 7.1.4+d7df870c0. How do I know which version of dorado it is using or based on?

**Comment by susie-ont** [comment]
Hi @ymcki & @Psy-Fer - currently versions of the Dorado basecall server are not pinned to a specific Dorado version, but Dorado basecall server 7.1.4 was between Dorado 0.3.4 and 0.4.0. Apologies for any inconvenience, we hope to simplify this mapping in the future. 

We typically post a release note to the Nanopore Community when a new version of Dorado server is released. Here is the release note for 7.1.4 which has some more details about what was included in that release: https://community.nanoporetech.com/posts/dorado-basecall-server-7-1
