### ISSUE TITLE
Excess barcodes in demux

### ISSUE THREAD

**Issue by asad-869** [nanoporetech/dorado#495]
Hi,
Can somebody help me please!
I am getting strange outputs after demultiplexing my called reads. I used 8 barcodes but the output command generates 24 output files. However when I use --barcode-both-ends, I get barcodes1-8, barcode11 and unclassified file. Is there any issue with the dorado demux command or something wrong on my end.

I used the following commands:
$HOME/dorado-0.4.3-linux-x64/bin/dorado basecaller dna_r9.4.1_e8_sup@v3.6 $HOME/path_to_pod5s/ > calls.bam

$HOME/dorado-0.4.3-linux-x64/bin/dorado demux --kit-name EXP-NBD104 --output-dir $HOME/path_to_output_demux/ $HOME/path_to_calls.bam

Barcode kit used: EXP-NBD104
Ligation Kit used: SQK-LSK109
Flowcell: FLO-MIN106

**Comment by tijyojwad** [comment]
Hi @asad-869 - this is likely because `dorado` is mis-classifying some reads into barcodes that don't exist. I suspect those reads to be quite few in number. Once you select `--barcode-both-ends`, the false positives are reduced (e.g now you mostly see 1-8, and some 11) but false negatives can go up (more unclassified).

Since you know only 8 barcodes are being used, we're releasing a new version of dorado soon that will allow custom barcodes to be defined. So you can restrict your barcodes to sequences 1-8 in `EXP-NBD104` and that will ensure only those are checked during classification. We'll be releasing this within the next few days.

**Comment by asad-869** [comment]
Hi @tijyojwad,
Thank you so much for the clarification.
I would like to share the details of some more analysis I did. I changed the dna model to 3.3 hac, got the same of data basecalled but when demux with --barcode-both-ends a significant data is added to unclassified.fastq and I am left with only 10% of the files as obtained with the above parameters.
So you suggest we wait for the next release to get accurate demux results?

**Comment by malton-ont** [comment]
As of version 0.4.3, `dorado` supports the use of sample sheets to restrict barcode matching to only those present in the sample. If you are seeing a lot of false positives you could try using this feature.

**Comment by phpeters** [comment]
Hej @tijyojwad ,

Thanks for helping! If you don't mind, I would add a related question here: 
Do you have any approximate numbers for how many reads go into the unclassified-bin when using `--barcode-both-ends`? I know that there are many factors playing a role, but are @asad-869 's 10% left-over reads a rather typical figure or should this number rather be let's say a 50%?

Thanks and all the best!
Philipp

**Comment by gearhq** [comment]
@tijyojwad Could you provide more details about custom barcodes? I have a custom demultiplex solution that is very inefficient. I'm using a board with unique Illumina barcodes for the start and end of the sequence (i5 and i7 from the IDT UDI plate, they are unique, so any detection would put the sequence read into the correct demultiplexed file). But I don't understand if the barcode sequences should be in a toml file or a separate file. I also have multiple i5 and multiple i7, should I put them in the same fasta file? In which order?

**Comment by tijyojwad** [comment]
Hi @phpeters 

> 10% left-over reads a rather typical figure or should this number rather be let's say a 50%

this is on the lower end. I would expect >50% with barcode both ends enabled. If it's <10%, then I would think the single end check is likely seeing a lot of false positive hits...

**Comment by tijyojwad** [comment]
Hi @asad-869 - closing this ticket for now since there hasn't been much activity. if you have more questions please re-open and I'd be happy to take a look
