### ISSUE TITLE
progress bar in dorado 0.5 just counting up!

### ISSUE THREAD

**Issue by mattloose** [nanoporetech/dorado#503]
When running dorado 0.5 with basecaller and recursive flag set the progress bar is simply a clock ticking up.

e.g:

[                              ] 0% [06m:41s<06m:41s]
[                              ] 0% [06m:51s<06m:51s]
[                              ] 0% [06m:59s<06m:59s]

Something seems broken?

Thanks

**Comment by mattloose** [comment]
ok - so with a little patience(!) it does start to behave:

[█▊                            ] 5% [01h:27m:22s<22h:48m:52s]

**Comment by mattloose** [comment]
I'll leave this open for now just so it is seen!

**Comment by tijyojwad** [comment]
Hi @mattloose - did the progress bar jump to 5% after a while, or slowly creep up to it?

**Comment by mattloose** [comment]
Afraid to say that I wasn't watching at that resolution - I've seen it again though processing a dataset where they've sat at the same values for at least 25 minutes before changing - but I don't know if it suddenly jumped or not.

**Comment by tijyojwad** [comment]
Hmm is this with simplex or duplex? Is the dataset really big?

**Comment by mattloose** [comment]
Simplex - dataset is of the order of 70-100 Gb.

**Comment by HalfPhoton** [comment]
Closing this ticket as resolved.
There have been a number of changes to the progress bar in Dorado 0.6.0. Please re-open if you have further issues.
