### ISSUE TITLE
Unknown flowcell_product_code

### ISSUE THREAD

**Issue by damientully** [nanoporetech/dorado#505]
Hi when trying the new auto model selection I get the following mesage
```

./dorado basecaller hac Run12/ > Run12.bam
[2023-12-06 15:51:37.035] [error] Unknown flowcell_product_code: 
```

Thanks
Damien

**Comment by HalfPhoton** [comment]
Hi @damientully , 

I appears as though your POD5 doesn't have a `flowcell_product_code` set or it is not being detected correctly. 

Could you please run the following `pod5` command and report what you see?

```bash
pod5 inspect debug <data.pod5> | grep -E "flow_cell_product_code|sequencing_kit"
        flow_cell_product_code: <flowcell_product_code>
        sequencing_kit: <sequencing_kit>
```

To install pod5: ```pip install pod5```

Kind regards, 
Rich

**Comment by damientully** [comment]
Thanks @HalfPhoton for your quick response. Yes you are indeed correct as when I run the following pod5 command I get simply: 

```
	flow_cell_product_code: 
	sequencing_kit: 
	flow_cell_product_code: 
	sequencing_kit: 

```
These were from old fast5 files which was a single read fast5 file that had to be converted to multi fast5 using the single_to_multi_fast5 from `ont_fast5_api` so I wonder if this information was not captured or lost through this process?  I'm assuming if it is absent then in this line then it doesnt look anywhere else such as the context_tags: which includes things like 'template_r9.4_450bps_5mer'

Best,
Damien

**Comment by HalfPhoton** [comment]
@damientully, This is very useful, thanks for the detail.

We'll look into this as an issue with the single to multi conversion tool. 

Would you like a solution to replace the metadata in the pod5 file to enable auto model selection or are you happy to continue with the model path method for this dataset? 

Kind regards,
Rich

**Comment by tijyojwad** [comment]
Hi @kristinrma - can you share what RNA data are you working with? The m6A DRACH mod basecalling is only available for RNA004.

**Comment by kristinrma** [comment]
Hi @tijyojwad,

I see, I realized I was previously working with RNA002 data. However, I just tried using RNA004 data and get this error message. [error] No supported chemistry for Flowcell:'FLO-PRO002', Kit:'SQK-RNA002' and Sampling Rate:4000
[2023-12-11 02:31:07.235] [error] Could not resolve chemistry from data

Do you know what could be causing this? The data is generated using the pre-release RNA004 kit, not sure if this might be a factor.

**Comment by tijyojwad** [comment]
thanks @kristinrma 

we will look into why the auto model selection isn't working. for now, you can run basecalling directly by running

1. `dorado download --model rna004_130bps_sup@v3.0.1`
2. `dorado basecaller rna004_130bps_sup@v3.0.1/ <pod5> --modified-bases m6A_DRACH > output.bam`

**Comment by kristinrma** [comment]
this command works thanks @tijyojwad!

**Comment by HalfPhoton** [comment]
Hi @kristinrma, 
Following up on your question:

> I see, I realized I was previously working with RNA002 data. However, I just tried using RNA004 data and get this error message. [error] No supported chemistry for Flowcell:'FLO-PRO002', Kit:'SQK-RNA002' and Sampling Rate:4000 [2023-12-11 02:31:07.235] [error] Could not resolve chemistry from data
> 
> Do you know what could be causing this? The data is generated using the pre-release RNA004 kit, not sure if this might be a factor.

I can confirm, the *pre-release* RNA004 condition is not a recognised condition for the purposes of auto-model selection in dorado 0.5.0. 

Kind regards,
Rich
