### ISSUE TITLE
dorado download models

### ISSUE THREAD

**Issue by pkerbs** [nanoporetech/dorado#506]
Hi,
the problem with setting the proxy for downloading the models was already described here: #266 
However, I still have issues downloading models (tested with v0.4.3 and v0.5.0).

When I don't set `dorado_proxy` and `dorado_proxy_port` then dorado sticks for ages in line 3 until it finally fails and successfully downloads it with curl.
When I set the dorado proxy variables it quickly skips the `httplib` step and directly downloads it with curl.
Why is this happening and can't the `httplib` step just be omitted?

It also would be nice if you could provide a link to a repository where models can be browsed and downloaded without having to use the `dorado download` command.

Best wishes,
Paul

```
1  $ dorado download --model dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mC_5hmC@v1 --directory models
2  [2023-12-06 17:21:48.049] [info] Assuming cert location is /etc/ssl/certs/ca-bundle.crt
3  [2023-12-06 17:21:48.053] [info]  - downloading dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mC_5hmC@v1 with httplib
4  [2023-12-06 17:30:17.033] [error] Failed to download dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mC_5hmC@v1: Could not establish connection
5  [2023-12-06 17:30:17.033] [info]  - downloading dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mC_5hmC@v1 with curl
6  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
7                                 Dload  Upload   Total   Spent    Left  Speed
8  100 18.4M  100 18.4M    0     0  23.3M      0 --:--:-- --:--:-- --:--:-- 23.4M
```

**Comment by tijyojwad** [comment]
Hi @pkerbs - I think the `httplib` download is timing out before moving on to `curl`. Looks like the default timeout is currently 5 mins, so that's probably what you're seeing. We can look into reducing the timeout. Thanks for raising that!

**Comment by pkerbs** [comment]
Thank you for looking into that.
5 mins seems pretty long for a timeout. It will wait 5 mins for each model before it starts to download it with curl.
Maybe a parameter with which one can choose between curl and httplib could help?

**Comment by tijyojwad** [comment]
Hi @pkerbs - we've reduced the timeout to 20s with v0.5.1 (https://github.com/nanoporetech/dorado#installation)
