### ISSUE TITLE
duplex read question

### ISSUE THREAD

**Issue by Yijun-Tian** [nanoporetech/dorado#508]
Hello there,

With the new dna stereo model, I have run a duplex basecall run with some R10 POD5. Is there a tag or a way that I can identify pairs of strands (positive and negative) from the BAM file? Were the two strands suppose to map by the same left-most coordinate in the reference? Or will they be sequenced in nearest time (st:Z:) but on the same channel (ch:i:)?

Thanks,

**Comment by vellamike** [comment]
Hi, if you look at the duplex read IDs you will notice they are a compound of the two original simplex IDs - they have the format `readID1;readID2` - The first read ID is the template strand of the duplex pair and the second is the complement, you can use these IDs to find the original simplex read in your BAM file - is this what you need?

**Comment by Yijun-Tian** [comment]
That's exactly what I need! Thanks for reminding that!
