### ISSUE TITLE
[error] [error] key "qscore" not found in the top-level table while trying to perform basecalling with 5mCG models 

### ISSUE THREAD

**Issue by Daniel-Tichy** [nanoporetech/dorado#51]
Hi, I am writing to check if I am doing something wrong, I have tried to look up for more documentation but it seems this github is all that there is about dorado.

I installed dorado in a Windows 10 PC and it works fine with the normals models 10.4 fast, hac and sup. But when I try to perform the same process over the same data but with the modified bases models I get this error. 
```

PS C:\Users\phage\OneDrive\Escritorio\dorado-0.0.2+acbca36-win64\bin> ./dorado basecaller .\dorado_trained_models\dna_r10.4.1_e8.2_400bps_fast@v3.5.2_5mCG@v2\ C:\Users\phage\OneDrive\Escritorio\Salida\NGS_012\NGS_012_30_08_2022\Pool_NGS012\20220830_1143_MN40787_FAT72720_85d0306f\fast5_pass\barcode15\
[2022-11-29 14:38:57.517] [info] > Creating basecall pipeline
[2022-11-29 14:38:57.628] [error] [error] key "qscore" not found in the top-level table
 --> .\dorado_trained_models\dna_r10.4.1_e8.2_400bps_fast@v3.5.2_5mCG@v2\config.toml

   |

 1 | [general]

   | ^--- the top-level table starts here

```
Thank you in advance for your help and I am sorry if this error its because I am not running the program properly.

**Comment by iiSeymour** [comment]
Hi @Daniel-Tichy 

The modification models augment the canonical model. You need specific a canonical model as the first argument and the mods model with `--remora-models`. This API will be simplified soon, see https://github.com/nanoporetech/dorado/issues/38#issuecomment-1310566995 for more details.
 
HTH

**Comment by iiSeymour** [comment]
Mods can now be specified with --modified-bases`.
