### ISSUE TITLE
Better documentation about the models?

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#512]
0.5 is released together with dna_r10.4.1_e8.2_400bps_sup@v4.3.0 basecalling model. So we need to think about whether to switch or not.

Based on the limited documentation, I only know it is faster than 4.2.0. But is the base quality better or worse than 4.2.0???

Since we always do 5mCG_5hmCG calling, a big problem with 4.3.0 model is that it only supports remora model dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1. On the other hand, the old 4.2.0 supports dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v3.1

However, the documentation regarding the remora models is even weaker. So I don't know if v3.1 is only a speed up of v1 or there is an accuracy improvement. If v3.1 is just a speed up and no accuracy improvement, then I am ok with upgrading to v4.3.0. Otherwise, I should just stick with 4.2.0. Is it possible to have a centralized place such that I can know what's going on with these models?

Thanks a lot in advance.

**Comment by tijyojwad** [comment]
Hi @ymcki - ack on the limited documentation on our model updates and the version numbers since they can be confusing. We are working on putting something together and will publish soon.

To answer your question - 

>  is the [v4.3.0] base quality better or worse than 4.2.0

v4.3.0 basecalling accuracy is better as well. For SUP there's almost 1 q-point improvement over v4.2.0. v4.3.0 is also better at calling low complexity regions and bacterial isolates.

The modbase model versions are conditioned on the basecaller version. So `dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1` is the first release of the `5mCG_5hmCG` modbase model for the v4.3.0 basecaller model. If the baseline basecaller model changes (e.g. from v4.2.0 to v4.3.0), then the modbase model versions reset.

`dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1` is the latest and greatest 5mCG_5hmCG model as it benefits from both canonical base call improvements + modbase improvements. So our strong recommendation is to move over to the newest models.

**Comment by jorisbalc** [comment]
Hi. Got some questions as well on that regard. Is it possible to run the remora tied basecalling models such as sup@v4.3.0_5mCG_5hmCG along custom remora models via --modified-bases-models? For the purpose of differentiating three unique modified bases in the same context for example

**Comment by tijyojwad** [comment]
Hi @jorisbalc - those options cannot be used together. If you want to run SUP@v4.3 5mCG_5hmCG and a custom remora model, you'll need to download the 5mCG model first and pass it through the `modified-bases-models` option as well
```
$ dorado download --model dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1
$ dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.3.0 <data> --modified-bases-models dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1 <custom_model> > out.bam
```

**Comment by jorisbalc** [comment]
Thanks for the clarification. Should I be retraining my remora model with updated basecalls whenever a new version of a basecaller model is released? Or is a remora model trained on v4.2.0 compatible with the v4.3.0 basecall model?

**Comment by ymcki** [comment]
> Hi @ymcki - ack on the limited documentation on our model updates and the version numbers since they can be confusing. We are working on putting something together and will publish soon.
> 
> To answer your question -
> 
> > is the [v4.3.0] base quality better or worse than 4.2.0
> 
> v4.3.0 basecalling accuracy is better as well. For SUP there's almost 1 q-point improvement over v4.2.0. v4.3.0 is also better at calling low complexity regions and bacterial isolates.
> 
> The modbase model versions are conditioned on the basecaller version. So `dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1` is the first release of the `5mCG_5hmCG` modbase model for the v4.3.0 basecaller model. If the baseline basecaller model changes (e.g. from v4.2.0 to v4.3.0), then the modbase model versions reset.
> 
> `dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1` is the latest and greatest 5mCG_5hmCG model as it benefits from both canonical base call improvements + modbase improvements. So our strong recommendation is to move over to the newest models.

Thanks for your reply. It would be great if the new documentation will have numbers like running time and accuracy for each model such that we can make our decision on which one to pick for our application.

**Comment by tijyojwad** [comment]
@jorisbalc 

> How do you avoid the `[error] Maximum number of positional arguments exceeded` when adding multiple models via --modified-bases-models? 

can you share what cmd you're using?

> Also, should I be retraining my remora model with updated basecalls whenever a new version of a basecaller model is released? Or is a remora model trained on v4.2.0 compatible with the v4.3.0 basecall model?

Remora is trained with updated basecalls usually. The is better asked in the remora github repo though - https://github.com/nanoporetech/remora/issues

**Comment by jorisbalc** [comment]
@tijyojwad 

Forgot to add it with the post but here it is: 

```
v313@v313-GP66-Leopard-11UH:~$  dorado basecaller /home/v313/Dorado/models/dna_r10.4.1_e8.2_400bps_sup@v4.3.0 /media/v313/T7\ Shield/2023_12_06_FAT_PL/bc14/ --modified-bases-models /home/v313/Dorado/models/dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1 /media/v313/Dorado/models/remora/odyC_v1.0/ --reference /home/v313/ref-seqs/gm119_ref.fasta > calls_mC_hmC_odyC.bam
```

This should work according to the cmd you wrote, unless I'm missing something? The remora model was exported to dorado and works with the same cmd if it runs alone. I'm sure it's the positioning that I'm just not getting the hang of

**Comment by HalfPhoton** [comment]
Hi @jorisbalc ,

So to clairfy your command works without the `<custom_model>` but not with?
```
v313@v313-GP66-Leopard-11UH:~$  dorado basecaller  
/home/v313/Dorado/models/dna_r10.4.1_e8.2_400bps_sup@v4.3.0 
/media/v313/T7\ Shield/2023_12_06_FAT_PL/bc14/ 
--modified-bases-models 
/home/v313/Dorado/models/dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1 
<custom_model>
--reference 
/home/v313/ref-seqs/gm119_ref.fasta 
> calls_mC_hmC_odyC.bam
```

**Comment by jorisbalc** [comment]
Correct, adding a second model after `--modified-bases-models ` treats it as third argument.

Example:
`dorado basecaller <model> --modified-bases-models <model_mC_hmC>  > calls.bam` works
`dorado basecaller <model> --modified-bases-models <model_mC_hmC>  <custom model> > calls.bam` does not work

**Comment by HalfPhoton** [comment]
I've tested locally and had the same issue.

Fortunately, the solution is as easy as it is easy to miss! We require a comma separated list of modbase models.

```bash
dorado basecaller --help
...
  --modified-bases-models       a comma separated list of modified base models [default: ""]
...
```

```bash
dorado basecaller <model> --modified-bases-models <model_mC_hmC>,<custom model> > calls.bam
```

Kind regards,
Rich

**Comment by jorisbalc** [comment]
Seems that I have overlooked this. Works fine now, thanks for the replies!

**Comment by tijyojwad** [comment]
my bad @jorisbalc I missed the `,` as well! thanks @HalfPhoton for looking into this!

**Comment by habibsaky** [comment]
I am new...can someone help me to solve this error---Thank you
(base) [mmolla@node304 ~]$ dorado basecaller /gpfs2/scratch/mmolla/Pod*.pod5 dna_r10.4.1_e8.2_400bps_hac@v4.3.0 --modified-bases-models >/gpfs2/scratch/mmolla/HL3/calls.bam
[2024-04-15 12:56:19.354] [info] Running: "basecaller" "/gpfs2/scratch/mmolla/Pod*.pod5" "dna_r10.4.1_e8.2_400bps_hac@v4.3.0" "--modified-bases-models"
[2024-04-15 12:56:19.400] [info] > Creating basecall pipeline
[2024-04-15 12:56:19.414] [error] toml::parse: file open error -> /gpfs2/scratch/mmolla/Pod*.pod5/config.toml
(base) [mmolla@node304 ~]$ dorado basecaller /gpfs2/scratch/mmolla/Pod*.pod5 dna_r10.4.1_e8.2_400bps_hac@v4.3.0 --modified-bases-models >/gpfs2/scratch/mmolla/HL3/calls.bam

**Comment by habibsaky** [comment]
dorado basecaller /gpfs2/scratch/mmolla/Pod/*.pod5 dna_r10.4.1_e8.2_400bps_hac@v4.3.0 --modified-bases-models  > /gpfs2/scratch/mmolla/HL3/calls.bam

**Comment by malton-ont** [comment]
@habibsaky, I've split this into a separate issue for you - https://github.com/nanoporetech/dorado/issues/749.

**Comment by HalfPhoton** [comment]
Closing this ticket as there has been changes to the models documentation and other issues have been resolved or moved to new issues.
