### ISSUE TITLE
Dorado trim can't read fastq header

### ISSUE THREAD

**Issue by bernardo-heberle** [nanoporetech/dorado#516]
Hello,

I am trying to trim adapters from a direct RNA sequencing ".fastq" file that I previously basecalled with Guppy. I am using the `dorado trim` functionality, but I keep getting the error `Could not read header from file: 2022-06-06_PAO91279_directRNAseq.fastq`.

Any idea what this could be? I checked and the header of the fastq file is completely normal. I imagine this might be a compatibility issue with files basecalled using `guppy`, but the documentation does not specify that this would be an issue.

Thank you for your time,
Bernardo

**Comment by tijyojwad** [comment]
Hi @bernardo-heberle - I will take a look at this issue, but based on your file name it looks like you're doing dRNA sequencing. for dRNA, the `dorado trim` command doesn't work (it's only applicable to DNA right now). we will update the documentation with that.

RNA adapter trimming is done in signal space, so if you re-basecall the dataset with the latest `dorado` the adapters will be trimmed

**Comment by tijyojwad** [comment]
I think I know what's going on - does your FASTQ file have `U` instead of `T`? `dorado` doesn't support reading/generating `U` for RNA, so that's what is throwing the FASTQ processing off. We will clarify that such FASTQs are not supported by `dorado`.

**Comment by bernardo-heberle** [comment]
You are correct, thank you for the quick reply. Also, here is a script that converts all the `U` to `T` in a given fastq file.

```
#!/usr/bin/env python3

import sys


def convert_u_to_t_in_sequence(input_file, output_file):
    """
    This function reads a FASTQ file, replaces all occurrences of 'U' with 'T'
    in the sequence lines only, and writes the modified content to a new file.
    """
    try:
        with open(input_file, 'r') as infile, open(output_file, 'w') as outfile:
            line_counter = 0  # To keep track of line numbers

            for line in infile:
                line_counter += 1
                # In FASTQ format, the sequence line is every 2nd line out of sets of 4 lines
                if line_counter % 4 == 2:
                    # Replace 'U' with 'T' in the sequence line
                    line = line.replace('U', 'T')

                outfile.write(line)

                # Reset the line counter after every set of 4 lines
                if line_counter == 4:
                    line_counter = 0

        return "Conversion successful. Output file created: " + output_file
    except Exception as e:
        return "An error occurred: " + str(e)


# Example usage
input_fastq = sys.argv[1]  # First input from the command line, the input fastq file
output_fastq = sys.argv[2] # Second input from the command line, the name of the output fastq file

# Call the function and print the result
convert_u_to_t_in_sequence(input_fastq, output_fastq)
```

If you save this script as `convert_U_to_T.py` you can call it in the command line with the following command:

`./convert_U_to_T.py <input.fastq> <output.fastq>`

**Comment by tijyojwad** [comment]
Thank you @bernardo-heberle for posting the script!
