### ISSUE TITLE
README missing output pipelines

### ISSUE THREAD

**Issue by skranz0** [nanoporetech/dorado#517]
Apparently a little copy paste error happened in the README.md
While the basecalling says `$ dorado basecaller hac pod5s/ > calls.bam`  the aligner only states `$ dorado aligner <index> <reads>`

So I just started the aligner like that, walked away shortly and came back to unreadable BAM output flashing through my terminal.

A humble `>` is missing here and possible in other spots. Adding it could save unaware users a lot of wasted time.

**Comment by tijyojwad** [comment]
Hi @skranz0 - thank you for flagging that :) . indeed an oversight on our part, will fix that!

**Comment by tijyojwad** [comment]
Hi @skranz0 - we've updated our READMEs to have the missing `>`
