### ISSUE TITLE
Empty sequence and qstring error on dorado-0.5.0

### ISSUE THREAD

**Issue by drk0311** [nanoporetech/dorado#518]
I tried to basecall from pod5 files obtained by running PCR-barcoded library (SQK-LSK114 + EXP-PBC096), but it gets terminated with an error of "Empty sequence and qstring provided for read id XXXX".

The command I threw was  
dorado basecaller ~/local/dorado_models/dna_r10.4.1_e8.2_400bps_sup@v4.3.0/ POD5/ --kit-name EXP-PBC096 -x cuda:all > BASECALL.bam

When I tried the same thing with dorado-0.4.1, it works fine.
~/dorado-0.4.1-linux-x64/bin/dorado basecaller ~/local/dorado_models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0/ POD5 --kit-name EXP-PBC096 -x cuda:all > BASECALL.bam

So is it a bug of dorado-0.5.0 when it encounters a read of 0 bp?

**Comment by tijyojwad** [comment]
there are 2 things changing in your examples - the version of dorado and the model version. can you try to run the v4.2.0 model with the latest dorado build (v0.5.0) and see if the problem persists? just trying to narrow down what the cause could be.

**Comment by drk0311** [comment]
Ah, dorado-0.5.0 with v4.2.0 model seems to work fine.

I also note that dorado-0.5.0 with v4.3.0 model worked fine when I tried non-barcoded LSK114 data and RBK114.96 data.

**Comment by tijyojwad** [comment]
Thanks for the update! Can you check if you also see this issue when running 0.5.0 with v4.3 model _without_ `--kit-name`?

> dorado-0.5.0 with v4.3.0 model worked fine when I tried non-barcoded LSK114 data and RBK114.96 data.

I'm not sure I followed this - `when I tried non-barcoded LSK114 data and RBK114.96 data`. RBK114.96 is a barcoding kit right? Do you mean your RBK barcoded data basecalled fine but the `EXP-PBC096` saw the issue?

**Comment by tijyojwad** [comment]
@drk0311 can you also try to run the same command that was failing with `--no-trim`?

**Comment by drk0311** [comment]
With `--no-trim ` option,  it doesn't fail. 
Basecall without `--kit-name ` also is proceeding well.

For your question about RBK114.96, I was talking about the pod5 files obtained from a library prepared with Rapid-barcoding kit. The following basecall with v4.3 model with `--kit-name  SQK-RBK1114-96` finished without error.

**Comment by tijyojwad** [comment]
thanks @drk0311 ! I think we've found one source of the problem, and will be pushing a fix for it in a patch release scheduled this week.

**Comment by drk0311** [comment]
I'm trying  `0.5.1` and seems fine.
Thank you!
