### ISSUE TITLE
5mC_5hmC vs 5mCG_5hmCG

### ISSUE THREAD

**Issue by pustoshilov-d** [nanoporetech/dorado#519]
Hi!
Sorry for a silly question, but do we correctly understand that the 5mCG_5hmCG modes are a subset of 5mC_5hmC?
And if so, is the prediction quality of 5mCG_5hmCG mods in sup@v4.3.0_5mC_5hmC@v1 and pure sup@v4.3.0_5mCG_5hmCG@v1 models the same?

Best regards

**Comment by ArtRand** [comment]
Hello @pustoshilov-d,

The 5mCG_5hmCG model will make base modification calls at CG motifs in the basecalled sequence, this is a subset of the sites that the 5mC_5hmC model will make calls (at every basecalled cytosine). As you can imagine, running the modification model at every cytosine is more compute intensive than only running it at every CG. Both models will have the same predictions at CG dinucleotides.

**Comment by pustoshilov-d** [comment]
@ArtRand thank you so much!

**Comment by pustoshilov-d** [comment]
Solved
