### ISSUE TITLE
How to run RNA004 m6A_DRACH model

### ISSUE THREAD

**Issue by kenneditodd** [nanoporetech/dorado#521]
Hello, 

I am still unsure, even after reading the documentation, how to run the RNA004 m6A DRACH model.

I have been able to successfully basecall with the command below
```
model=/tools/dorado-0.5.0-linux-x64/downloads/rna004_130bps_sup@v3.0.1
dorado basecaller --min-qscore 10 --verbose --emit-fastq --emit-moves $model sample1_merged.pod5 > sample1_q10.fastq
```

However, I am unsure how to then specify m6A_DRACH modifications with the rna004_130bps_sup@v3.0.1_m6A_DRACH@v1 model. I have tried a couple different combinations and can't get the command to run.

**Comment by tijyojwad** [comment]
dorado basecaller --min-qscore 10 --verbose --emit-fastq --emit-moves --modified-bases m6A_DRACH $model sample1_merged.pod5 > sample1_q10.fastq

**Comment by kenneditodd** [comment]
> dorado basecaller --min-qscore 10 --verbose --emit-fastq --emit-moves --modified-bases m6A_DRACH $model sample1_merged.pod5 > sample1_q10.fastq

The command I ran
```
model=/research/labs/neurology/fryer/m214960/tools/dorado-0.5.0-linux-x64/downloads/rna004_130bps_sup@v3.0.1
dorado basecaller --min-qscore 10 \
                  --verbose \
                  --emit-fastq \
                  --emit-moves \
                  --modified-bases m6A_DRACH \
                  $model sample1_merged.pod5 > sample1_q10_m6A_DRACH.fastq
```

I get the error message below
```
[2023-12-12 14:56:47.037] [error] '/tools/dorado-0.5.0-linux-x64/downloads/rna004_130bps_sup@v3.0.1' is not a supported modification please select from 6mA, 5mC, m6A_DRACH, 5mCG_5hmCG, 5mCG, 5mC_5hmC
```

**Comment by tijyojwad** [comment]
my bad, since the `--modified-bases` can take multiple options we can't have the positional args just after it. this should work

`dorado basecaller --min-qscore 10 --verbose --emit-moves m6A_DRACH $model sample1_merged.pod5 --modified-bases > sample1_q10.fastq`

note that I removed `--emit-fastq` since we only support outputting move tables/mod base tags to BAM/SAM

**Comment by kenneditodd** [comment]
> my bad, since the `--modified-bases` can take multiple options we can't have the positional args just after it. this should work
> 
> `dorado basecaller --min-qscore 10 --verbose --emit-moves m6A_DRACH $model sample1_merged.pod5 --modified-bases > sample1_q10.fastq`
> 
> note that I removed `--emit-fastq` since we only support outputting move tables/mod base tags to BAM/SAM

The command I ran.
```
model=/tools/dorado-0.5.0-linux-x64/downloads/rna004_130bps_sup@v3.0.1
dorado basecaller --min-qscore 10 \
                  --verbose \
                  --emit-moves \
                  --modified-bases m6A_DRACH \
                  $model sample1_merged.pod5 > sample1_q10_m6A_DRACH.bam
```

Same error message.
```
[2023-12-12 16:02:23.053] [error] '/tools/dorado-0.5.0-linux-x64/downloads/rna004_130bps_sup@v3.0.1' is not a supported modification please select from 6mA, 5mC, m6A_DRACH, 5mCG_5hmCG, 5mCG, 5mC_5hmC
```
