### ISSUE TITLE
CUDA error: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. 

### ISSUE THREAD

**Issue by kusonahikari** [nanoporetech/dorado#523]
Dear developers,
I tried to run dorado on our window 10 desktop via wsl then encountered this error: 
<img width="947" alt="new_cuda0" src="https://github.com/nanoporetech/dorado/assets/18393926/7a6096ef-18d0-4589-925e-aae04b8bf737">
Tried to run `cuda-sample` to check whether CUDA was set up properly or not. 
<img width="629" alt="cuda-sample" src="https://github.com/nanoporetech/dorado/assets/18393926/1e95ec81-3fa5-46af-b478-c9947cf7bb5b">
Output of `nvidia-smi`
<img width="523" alt="nvidia-smi" src="https://github.com/nanoporetech/dorado/assets/18393926/87b90416-7dbf-4e86-add4-ddca07be1d85">
Installed dorado version is `0.5.0+0d932c0`.
Please kindly let me know how to solve this problems.

**Comment by tijyojwad** [comment]
Hi @kusonahikari - unfortunately the error from CUDA is not very informative...

1. Can you try to run one of the samples that executes a CUDA kernel, like `vectorAdd`?
2. One of my colleagues saw this error a few weeks ago and it went away after re-installing the driver. So maybe that's worth a try too

**Comment by kusonahikari** [comment]
Hi @tijyojwad,
Thank you so much. Dorado ran smoothly after re-installing the driver.
Best wishes and happy holiday.
