### ISSUE TITLE
Adapter trimming

### ISSUE THREAD

**Issue by Yoon90** [nanoporetech/dorado#524]
Hello!
I've read a thread: https://github.com/nanoporetech/dorado/issues/347 and it was pretty impressive.

I've tried to find the RNA adapter sequence in 

https://github.com/nanoporetech/dorado/tree/master/dorado/read_pipeline 
and
https://github.com/nanoporetech/dorado/tree/master/dorado/splitter

but i could not find it.  Could you provide the link or document of the adapter sequences that i can look into?

The only sequence that i found is https://github.com/nanoporetech/dorado/tree/master/dorado/splitter and i guess it's only for the DNA sequencing.

![image](https://github.com/nanoporetech/dorado/assets/134576692/1682126a-b3a6-4c9f-acbd-e36fa82fd66e)

As far as i know, adapter/primer sequence(forward/reverse) were noted on the guppy barcoder/trimming. where can i find those adapter sequence info in Dorado?(I found barcode sequences: https://github.com/nanoporetech/dorado/blob/master/dorado/utils/barcode_kits.cpp)

**Comment by tijyojwad** [comment]
Hi @Yoon90 - currently `dorado` supports adapter trimming for RNA but in signal space only. So RNA adapters are trimmed during basecalling, and can't be trimmed post basecall.

**Comment by Yoon90** [comment]
> Hi @Yoon90 - currently `dorado` supports adapter trimming for RNA but in signal space only. So RNA adapters are trimmed during basecalling, and can't be trimmed post basecall.

Thank you for the reply. in that case, it works like read_until(https://github.com/nanoporetech/read_until_api) does in terms of detect raw signal?

Since i don't have any sequence generated from rna-002 or rna-004, I used rna sequence from https://github.com/nanoporetech/dorado/tree/master/tests/data/pod5/rna004_130bps to test trimming options on Dorado but there was whether turning the trimming option or not. Does this sequence have no head adapter?

One more thing, could you provide codes or information about the adapter trimming for RNA that i can take a look in more detail?

**Comment by tijyojwad** [comment]
For RNA adapter trimming dorado analyzes the raw signal and trims the adapter portion of the signal before basecalling the remaining signal.

The test data has likely been minimized to save on space. So it may not be representative of real data. RNA adapter trimming is enabled by default and can't be turned off.

The trimming code is in the `ScalerNode.cpp` file
