### ISSUE TITLE
Modified basecalling and fastq format output

### ISSUE THREAD

**Issue by bernardo-heberle** [nanoporetech/dorado#525]
Is is possible to get DNA/RNA modifications when using the `--emit-fastq` option to output a `fastq` file using `dorado basecaller`?

**Comment by tijyojwad** [comment]
Hi @bernardo-heberle - no we only support outputting modification information to SAM/BAM files, following the tags defined in the SAM spec.

**Comment by bernardo-heberle** [comment]
Thank you for the quick response @tijyojwad
