### ISSUE TITLE
libkoi Linux ppc64le

### ISSUE THREAD

**Issue by mwtorres** [nanoporetech/dorado#526]
I'm trying to compile dorado on a Linux ppc64le with V100 GPUs. The install breaks when trying to install libkoi, because there doesn't exist a pre-built libkoi-0.4.3-Linux-ppc64le-cuda-11.8. I saw that my other Linux x86_64 option with P100 GPUs will definitely not be supported.

1. Would it be possible to provide a pre-built binary for libkoi-0.4.3-Linux-ppc64le-cuda-11.8?
2. Or a pre-built binary dorado for Linux ppc64le?
3. Are there plans to support AMD gpus? I saw there were no plans as of last Oct 2022: [What about AMD cards?](https://github.com/nanoporetech/dorado/issues/30).

**Comment by tijyojwad** [comment]
Hi @mwtorres - 

We currently don't have plans to support the `ppc64le` architecture. Do you have an option to move the V100 GPU to your Linux x86_64 machine?

> Are there plans to support AMD gpus? 

Not yet
