### ISSUE TITLE
Train my own data

### ISSUE THREAD

**Issue by comtigo** [nanoporetech/dorado#527]
Hello:
    I have read the readme, dorado can be trained with its own data. I want to know how should I process my sequencing data if I want to train a 5mc methylation model. Do I need to methylate the position of C? Do I need to train the remora model at the same time? Thank you very much.

**Comment by tijyojwad** [comment]
Hi @comtigo - this is a better question for the remora repository - https://github.com/nanoporetech/remora/issues
