### ISSUE TITLE
ideal parameters for NVIDIA 48Gb VRAM

### ISSUE THREAD

**Issue by avilella** [nanoporetech/dorado#528]
I am running latest dorado downloaded today with the following parameters:

```
dorado basecaller --device cuda:0 $HOME/dorado/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 --emit-moves fast5/ > calls.bam
```
It's automatically set the batch to 640, but it's using around half the VRAM available:

![image](https://github.com/nanoporetech/dorado/assets/158007/28911552-326b-455b-a237-6b2b54725995)

See nvidia-smi:

![image](https://github.com/nanoporetech/dorado/assets/158007/bf39f7fb-e4ad-451b-abfe-41575ca88de1)

Would it be possible to optimize the parameters to speed it up? This is on fast5/ folder, not pod5.

**Comment by sklages** [comment]
I'd really go for pod5 when it comes to dorado basecalling. This will probably run more efficiently. 

Apart from that you can set/increase the batchsize manually by specifying _--batchsize INT_ with INT ideally being a multiple of 64.

**Comment by avilella** [comment]
Thanks. And what's the recommended fast5 to pod5 command these days?

**Comment by tijyojwad** [comment]
Hi @avilella here are some instructions to convert - https://pod5-file-format.readthedocs.io/en/latest/docs/tools.html#pod5-convert-fast5

As for the batch size, `dorado` does auto batch size calculation based on performance characteristics of different batch sizes. It's usually pretty close to the optimal you would get from your GPU, even if it's not using the full VRAM available. But as @sklages , you can also use the `-b` option to tune it further!

**Comment by aljazdzy** [comment]
> Hi @avilella here are some instructions to convert - https://pod5-file-format.readthedocs.io/en/latest/docs/tools.html#pod5-convert-fast5
> 
> As for the batch size, `dorado` does auto batch size calculation based on performance characteristics of different batch sizes. It's usually pretty close to the optimal you would get from your GPU, even if it's not using the full VRAM available. But as @sklages , you can also use the `-b` option to tune it further!

I have a question, I'm currently running what I consider quite a bit of data through sup (I had never been able to get this much through the minion before!  10.5 billion basepairs!) and it's already batched it to 640, but I'm not really sure what this means.  640 pod5 files? 640 threads? It seems like it's going to take at least 10 hours to run batch 1 so I was wondering if there might be a way for me to calculate how many batches will be.
