### ISSUE TITLE
Can't open model file? 

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [nanoporetech/dorado#53]
Anything I can do? All file permissions seem fine. 

```
`$ ./dorado basecaller --emit-fastq dna_r10.4.1_e8.2_260bps_hac@v4.0.0 /home/exouser/reads
[2022-12-07 03:30:05.329] [info] > Creating basecall pipeline
[2022-12-07 03:30:08.138] [error] toml::parse: file open error -> dna_r10.4.1_e8.2_260bps_hac@v4.0.0/config.toml
```

**Comment by vellamike** [comment]
Hi Jason, have you  downloaded the models using the  dorado download
command?

**Comment by vellamike** [comment]
Can you confirm that the model is downloaded to the  working directory
where you are running Dorado from (using ls) ?

**Comment by JasonJWilliamsNY** [comment]
Thanks @vellamike ! It wasn't obvious to me that I needed to specify that path (from the given doc string, I assumed it would either pull the model or look to the directory it downloaded to. I think I have it working.
