### ISSUE TITLE
duplex basecalling

### ISSUE THREAD

**Issue by sgujjaBebio** [nanoporetech/dorado#531]
Hi,
Just wanted to clarify if duplex base calling returns a merged read sequence for the pairs.
Thanks

**Comment by tijyojwad** [comment]
Hi @sgujjaBebio - you can consider it "merged" in way - the duplex algorithm looks like at signal, bases and qscores of overlapping bases from the template and complement reads and determines a corrected base for each position.

**Comment by sgujjaBebio** [comment]
Thank you for the reply. I am trying to understand why in some cases the primer is trimmed from either template or complement sequence in generating the duplex read While in some cases they are both present. Can you shed some light on this?

**Comment by tijyojwad** [comment]
Hi @sgujjaBebio - my guess is that could be dependent on whether the primer ligated and was sequenced properly on both ends or not. If it was, then when we look for overlaps within potential pairs the overlap could extend to cover the primer too. And if only one of the strands had it (or if primer quality wasn't good) then it would not get included in the overlap.

**Comment by tijyojwad** [comment]
Hi @sgujjaBebio - I'm closing this issue for now. If you have follow up question, please feel free to re-open the issue!
