### ISSUE TITLE
Failed to load metallib library

### ISSUE THREAD

**Issue by MagpiePKU** [nanoporetech/dorado#533]
Hi, I installed dorado by downloading the precompiled executable on a Mac (M1) and it runs like

```
/my_dorado_dir/bin/dorado \
basecaller \
hac@v3.3,5mCG_5hmCG \
my_pod5_dir
``` 

and it emits: 

[2023-12-18 01:22:16.729] [info] > Creating basecall pipeline
[2023-12-18 01:22:16.994] [error] Failed to load metallib library.

Tried using the `-x cpu` option and dorado works but I just would like to know why it cannot find the `default.metallib` file. 

Tried several ideas: 
1. link it to the working directory (failed) 
2. copy it to the working directory (failed)
3. copy it to a "lib" directory under the working directory (failed)
4. copy it to a "lib" directory above the working directory (failed)
5. exporting the lib directory to LD_LIBRARY_PATH (failed)
6. exporting the lib directory to DYLD_LIBRARY_PATH (failed) 

The machine is an Mac on:
M1 Pro (10 cores, 16Gb RAM, GPU = 16 cores Metal 3) with a system version 14.2 (23C64)

**Comment by MagpiePKU** [comment]
dorado-0.5.0-osx-arm64

> which version of dorado are you using?

**Comment by theJasonFan** [comment]
@MagpiePKU I had a similar issue after I moved (actually soft-linked) the `dorado` binary to a folder in my path variable.

If you execute the dorado binary directly in the unzipped archive do you still get the same error? My best guess is that the binary expects the `.metallib` library to be located by a specific relative path (`../lib/default.metallib`).

**Comment by MagpiePKU** [comment]
@theJasonFan Yes I tried running it directly in the unzipped archive. Still not working. I looked at the permissions of `../lib/default.metallib` and it seemed fine. So very strange.

**Comment by StuartAbercrombie** [comment]
`default.metallib` is not a normal shared library containing CPU code, so things like `DYLD_LIBRARY_PATH` don't relate to it.  (It's a semi-compiled form of GPU code that gets loaded and  turned into executable GPU code at runtime.)

In dorado we first try to to get the library by calling the Metal API `newDefaultLibrary`, but I believe this will only work when the file has been embedded via XCode, which is not the case for the dorado binary you have.

The fallback path makes an assumption about the location of `default.metallib` relative to the dorado executable (as suggested above).  It obtains the executable path and then looks for `<executable path>/../lib/default.metallib`.  In the binary release we have `<dorado path>/bin/dorado` and `<dorado path>/lib/default.metallib`, so this works.

It sounds like so far you've experimented with `default.metallib` in a directory unrelated to the location of the dorado executable?  Have you tried with `/my_dorado_dir/lib` containing `default.metallib`?

**Comment by HalfPhoton** [comment]
Closing as there has been no response in a while and the advice given by Stuart has worked for a similar issue.
