### ISSUE TITLE
Q: dorado basercaller | demux -> output by alias and/or barcode?

### ISSUE THREAD

**Issue by sklages** [nanoporetech/dorado#535]
I do have:
- one pool, `SAMPLE_NAME`
- .. this is basically four barcodes (9-12, SQK-NBD114-96)
- named ALIAS_NAME1 to 4
- data from two runs

My samplesheet looks like:
```
flow_cell_id,kit,sample_id,experiment_id,barcode,alias
PAOxxxxx,SQK-NBD114-96,SAMPLE_NAME,231212_PAOxxxxx_Custom-NBD,barcode09,ALIAS_NAME1
PAOxxxxx,SQK-NBD114-96,SAMPLE_NAME,231212_PAOxxxxx_Custom-NBD,barcode10,ALIAS_NAME2
PAOxxxxx,SQK-NBD114-96,SAMPLE_NAME,231212_PAOxxxxx_Custom-NBD,barcode11,ALIAS_NAME3
PAOxxxxx,SQK-NBD114-96,SAMPLE_NAME,231212_PAOxxxxx_Custom-NBD,barcode12,ALIAS_NAME4
```

I called the data with base modifications:
```bash
dorado basecaller \
    sup,5mCG_5hmCG \
    $POD5_TMPDIR \
    --device cuda:all \
    --batchsize 0 \
    --trim all \
    --kit-name SQK-NBD114-96 \
    --barcode-both-ends \
    --sample-sheet smpl.csv \
    > $BAM_OUT
```

After that I called `dorado demux` to extract demux'ed data:
```bash
    dorado demux \
      --output-dir demux-SAMPLE_NAME \
      --no-classify \
      $BAM_OUT
```

Surprisingly I got 2x4 BAM files, with different sizes (NAME1 <-> barcode09 etc):
```
Size   Name
5.9 GB ALIAS_NAME1.bam
3.7 GB ALIAS_NAME2.bam
6.9 GB ALIAS_NAME3.bam
6.3 GB ALIAS_NAME4.bam

3.9 GB SQK-NBD114-96_barcode09.bam
2.5 GB SQK-NBD114-96_barcode10.bam
4.5 GB SQK-NBD114-96_barcode11.bam
4.2 GB SQK-NBD114-96_barcode12.bam

 15 GB unclassified.bam
```

So I am a bit puzzled .. what's going wrong here? Or probably better, what do I miss here? 
I would have expected four named BAMs only ..
.. and the `unclassified.bam` is quite large ..

```bash
dorado --version
0.5.0+0d932c05
```

**Comment by sklages** [comment]
addendum:

I do see that in the basecalled BAM file, I have two read groups for each library, one for each each run.
But one has the barcode name as part of the RG-ID, the other one the alias name:

```
@RG ID:4d12893e8968cbfc4b3b840def3eb32819dd60db_dna_r10.4.1_e8.2_400bps_sup@v4.3.0_ALIAS_NAME1            
@RG ID:5a948a0d13287f42fb4e8fabf3b732e927ae4565_dna_r10.4.1_e8.2_400bps_sup@v4.3.0_SQK-NBD114-96_barcode09
```

.. the rest is identical.

**Comment by sklages** [comment]
@tijyojwad - @iiSeymour 

### Background: 
this P2solo run (on position A) was stopped after 24h (after reloading), because resuming failed, without errors. Flowcell was moved from position A to B and a new run was started (same flowcell, same library). For both runs MinKNOW was started with fast basecalling and demux'ing, so the resulting POD5 files in the final run folders are "pre-sorted".

To make it more clear, I have cut down the datasets to just two POD5 files (classified as barcode12 by MinKNOW).

One from position A and one from position B, both linked into the same folder, say 'pod5'.

```
dorado \
  basecaller \
  sup,5mCG_5hmCG \
  /path/to/pod5 \
  --trim all \
  --kit-name SQK-NBD114-96 \
  --barcode-both-ends \
  --sample-sheet /path/to/samplesheet.csv \
  > BAM_bc.bam
```

The `samplesheet.csv` looks like:

```
flow_cell_id,kit,sample_id,experiment_id,barcode,alias
PAO60283,SQK-NBD114-96,S30238,231212_PAO60283_Custom-NBD_X30238,barcode12,SampleAliasBC12
```

Then demux'ing:
```
dorado \
  demux \
  --output-dir demux_sample \
  --no-classify \
  BAM_bc.bam
```

The results look like:
```
 size     name
 1199157  SampleAliasBC12.bam
 1151883  SQK-NBD114-96_barcode12.bam
  722429  unclassified.bam
```
 .. with both BAM files being different in size and number of records .. why?

The sum of all records of these three BAM files is `3221+3137+1654=8012`, so actually *approximately* the sum of all sequences of the input POD5 files (4000+4000)


BAM headers are identical (except for one PG line), I get four read groups tags (RG):
```
@RG ID:4d12893e8968cbfc4b3b840def3eb32819dd60db_dna_r10.4.1_e8.2_400bps_sup@v4.3.0  PU:PAO60283 PM:dory DT:2023-12-12T09:57:37.418+00:00    PL:ONT  DS:basecall_model=dna_r10.4.1_e8.2_400bps_sup@v4.3.0 modbase_models=dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1 runid=4d12893e8968cbfc4b3b840def3eb32819dd60db LB:X30238   SM:X30238
@RG ID:5a948a0d13287f42fb4e8fabf3b732e927ae4565_dna_r10.4.1_e8.2_400bps_sup@v4.3.0  PU:PAO60283 PM:dory DT:2023-12-13T13:30:20.411+00:00    PL:ONT  DS:basecall_model=dna_r10.4.1_e8.2_400bps_sup@v4.3.0 modbase_models=dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1 runid=5a948a0d13287f42fb4e8fabf3b732e927ae4565 LB:X30238   SM:X30238
@RG ID:4d12893e8968cbfc4b3b840def3eb32819dd60db_dna_r10.4.1_e8.2_400bps_sup@v4.3.0_SampleAliasBC12 PU:PAO60283 PM:dory DT:2023-12-12T09:57:37.418+00:00    PL:ONT  DS:basecall_model=dna_r10.4.1_e8.2_400bps_sup@v4.3.0 modbase_models=dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1 runid=4d12893e8968cbfc4b3b840def3eb32819dd60db LB:X30238   SM:X30238   BC:TCCGATTCTGCTTCTTTCTACCTG
@RG ID:5a948a0d13287f42fb4e8fabf3b732e927ae4565_dna_r10.4.1_e8.2_400bps_sup@v4.3.0_SQK-NBD114-96_barcode12  PU:PAO60283 PM:dory DT:2023-12-13T13:30:20.411+00:00    PL:ONT  DS:basecall_model=dna_r10.4.1_e8.2_400bps_sup@v4.3.0 modbase_models=dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1 runid=5a948a0d13287f42fb4e8fabf3b732e927ae4565 LB:X30238   SM:X30238   BC:TCCGATTCTGCTTCTTTCTACCTG
```

I expect my data to be demux'ed by "alias" solely.

What am I overseeing here? Any hints to point me in the right direction?

**Comment by tijyojwad** [comment]
Hi @sklages - this looks like some untested logic on our end. We'll take a look and get back to you.

**Comment by tijyojwad** [comment]
Hi @sklages - your dataset has 2 experiment IDs, and looks like your sample sheet has aliasing setup for only one of them. So one of them is being named by the alias, and the other using the default naming scheme for barcodes.

You can fix this by making a copy of your first experiment in the sample sheet and changing the experiment ID name so both experiments are captured by aliasing.

**Comment by sklages** [comment]
thanks @tijyojwad - that's embarrassingly simple :-) 

```
flow_cell_id,kit,sample_id,experiment_id,barcode,alias
PAO60283,SQK-NBD114-96,S30238,231212_PAO60283_Custom-NBD_X30238,barcode12,SampleAliasBC12
PAO60283,SQK-NBD114-96,S30238,20231213_PAO60283_Custom-NBD_X30238,barcode12,SampleAliasBC12
```
.. but `dorado` complains and then fails:
```
[2023-12-19 16:56:36.706] [error] Sample sheet file /path/to/samplesheet contains more than one experiment_id
```

**Comment by tijyojwad** [comment]
Ah my bad, yes sample sheet spec only allows one experiment id!

So I think there are 2 ways forward (both I agree not super great)
* separate the dataset by experiment id (e.g. using pod5 tooling) and run each of them through dorado with their own sample sheet. the results can then be combined by alias name downstream.
* run dorado with barcoding using the normalized (un-aliased) names. then rename them manually downstream using the same mapping being used in the sample sheet (normalized names have the barcode number in them, so the mapping should be easy to determine)

**Comment by sklages** [comment]
@tijyojwad - well, yes, I am currently heading for the second approach: running demux on barcodes only (without samplesheet) and then rename files afterwards. Not a big deal as there are only four libraries/barcodes. 

Would be nice to have the samplesheet specs a bit more permissive/flexible though ..
