### ISSUE TITLE
Unable to find SQK-LSK109 in pre-built or custom kits

### ISSUE THREAD

**Issue by sandeepkasaragod** [nanoporetech/dorado#537]
Hi,

I am having following issue, it looks this kit-name is not added in the dorado. Is it possible to add SQK-LSK109 in the next update.

Command error:
  [2023-12-18 22:52:29.357] [info] Barcode for SQK-LSK109
  [2023-12-18 22:52:29.358] [info] > starting barcode demuxing
  terminate called after throwing an instance of 'std::runtime_error'
    what():  Could not find SQK-LSK109 in pre-built or custom kits

**Comment by ymcki** [comment]
Well, if you flowcell is R9.4.1, then it should be supported by a model like dna_r9.4.1_e8_sup@v3.3 as SQK-LSK109 is covered by E8.

However, if your data is from R10.3 (aka FLO-MIN111 or FLO-PRO111, then there is no luck

**Comment by malton-ont** [comment]
Hi @sandeepkasaragod. It looks like you've specified `--kit-name SQK-LSK109`. This parameter is for specifying the barcoding kit to use for demux, but SQK-LSK109 is not a barcoding kit. If you're not attempting to demux then you can leave this parameter out.

**Comment by sandeepkasaragod** [comment]
Thanks @ymcki and @malton-ont for the reply. Let me have a look on this.

**Comment by HalfPhoton** [comment]
@sandeepkasaragod, is this issue resolved?

**Comment by tijyojwad** [comment]
Hi @sandeepkasaragod - closing this issue since we haven't heard back from you. Let us know if you have any more questions.
