### ISSUE TITLE
Feature request: Add option to allow spliced alignment and junction bed for alignment

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/dorado#546]
Minimap2 allows you to use -ax splice mode for spliced alignment and a way to add junction bed notations. As far as I can tell this isn't included in the current dorado release. Are there plans to enable this?

**Comment by pre-mRNA** [comment]
Bumping this.

**Comment by tijyojwad** [comment]
Hi all - I believe this is now available in dorado v0.7.1. you can set `splice` as the preset and pass in a junction bed file
