### ISSUE TITLE
RNA split on adapter?

### ISSUE THREAD

**Issue by itslittman** [nanoporetech/dorado#547]
In the readme it says, "Adapters for RNA002 and RNA004 kits are automatically trimmed during basecalling." 
Is there a way to not only have Dorado search the ends of reads for adapters, but also in the middle of reads? I'm trying to split concatenated RNA reads. For most these are not an issue but I look at fusion genes and false-positives, as obvious as they may be in IGV, are hard to filter out and make the analysis much more tedious.

**Comment by tijyojwad** [comment]
Hi @itslittman - thanks for reporting! RNA reads should be getting split during basecalling as well. It's possible that some of the reads are not getting split correctly. Would you be comfortable sharing a sample pod5 with one read where you see unspilt reads?

**Comment by itslittman** [comment]
@tijyojwad okay will do - just to check and make sure, it should do that automatically, right? I don't have to specify any additional parameters in the basecalling script?

**Comment by tijyojwad** [comment]
correct splitting is enabled by default
