### ISSUE TITLE
Future of model training by users

### ISSUE THREAD

**Issue by touala** [nanoporetech/dorado#55]
Hello everyone,

I'd like to know what is the future of custom model training by users? I've used [taiyaki](https://github.com/nanoporetech/taiyaki) and from my understanding the software is not developed anymore. I've not seen mentions of SUP model training, nor [dorado](https://github.com/nanoporetech/dorado) V4 training, and I believe only [remora](https://github.com/nanoporetech/remora) training commands are available for the new generation of software presented at NCM22.

Is there any replacement for custom basecaller training? Are there any plan?

Best,

Alan

**Comment by iiSeymour** [comment]
Hey @touala model training will continue to be provided by bonito and we have no plans to bring training to dorado. V4 models for dorado were produced in bonito.

**Comment by touala** [comment]
Thank you very much @iiSeymour for the information. I also missed that duplex was supported by bonito.
