### ISSUE TITLE
Issues when installing dorado with cmake - help?

### ISSUE THREAD

**Issue by riej10** [nanoporetech/dorado#555]
Hello.

I am trying to install dorado on my ubuntu 22.04.

It says the following when i write " cmake -S . -B cmake-build

-- Build type: Release
-- Found CUDA 11.5.119 (/usr -> /usr)
-- Submodule update
-- Found libkoi-0.4.3-Linux-x86_64-cuda-11.3
-- Found pod5-0.2.2-Linux
CMake Warning (dev) at cmake/Torch.cmake:26 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:86 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found torch-2.0.0-ont.2-cxx11-abi-static-Linux
CMake Warning at dorado/3rdparty/torch-2.0.0-ont.2-cxx11-abi-static-Linux/libtorch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library foxi_loader_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  dorado/3rdparty/torch-2.0.0-ont.2-cxx11-abi-static-Linux/libtorch/share/cmake/Torch/TorchConfig.cmake:106 (append_torchlib_if_found)
  cmake/Torch.cmake:188 (find_package)
  CMakeLists.txt:86 (include)

CMake Warning at dorado/3rdparty/torch-2.0.0-ont.2-cxx11-abi-static-Linux/libtorch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library fmt_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  dorado/3rdparty/torch-2.0.0-ont.2-cxx11-abi-static-Linux/libtorch/share/cmake/Torch/TorchConfig.cmake:106 (append_torchlib_if_found)
  cmake/Torch.cmake:188 (find_package)
  CMakeLists.txt:86 (include)

CMake Warning at dorado/3rdparty/torch-2.0.0-ont.2-cxx11-abi-static-Linux/libtorch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library eigen_blas_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  dorado/3rdparty/torch-2.0.0-ont.2-cxx11-abi-static-Linux/libtorch/share/cmake/Torch/TorchConfig.cmake:113 (append_torchlib_if_found)
  cmake/Torch.cmake:188 (find_package)
  CMakeLists.txt:86 (include)

CMake Warning at dorado/3rdparty/torch-2.0.0-ont.2-cxx11-abi-static-Linux/libtorch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library mkldnn_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  dorado/3rdparty/torch-2.0.0-ont.2-cxx11-abi-static-Linux/libtorch/share/cmake/Torch/TorchConfig.cmake:120 (append_torchlib_if_found)
  cmake/Torch.cmake:188 (find_package)
  CMakeLists.txt:86 (include)

CMake Warning at dorado/3rdparty/torch-2.0.0-ont.2-cxx11-abi-static-Linux/libtorch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library asmjit_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  dorado/3rdparty/torch-2.0.0-ont.2-cxx11-abi-static-Linux/libtorch/share/cmake/Torch/TorchConfig.cmake:123 (append_torchlib_if_found)
  cmake/Torch.cmake:188 (find_package)
  CMakeLists.txt:86 (include)

-- TORCH_BUILD_VERSION: 2.0.0-ont
-- Found openssl3-Linux-x86_64
-- Setting up htslib build
-- Done Building htslib
-- Build spdlog: 1.12.0
-- Build type: Release
CMake Error at CMakeLists.txt:139 (add_subdirectory):
  The source directory

    /home/riej/dorado/dorado/3rdparty/elzip

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:142 (add_subdirectory):
  The source directory

    /home/riej/dorado/dorado/3rdparty/ont-minimap2

  does not contain a CMakeLists.txt file.

-- build minimap2 exe: OFF
-- build minimap2 lib: 
CMake Deprecation Warning at dorado/3rdparty/edlib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

Setting warning flags
-- CUDA VERSION ALREADY SET TO 11.5
CMake Error at cmake/VbzPlugin.cmake:30 (add_subdirectory):
  The source directory

    /home/riej/dorado/dorado/3rdparty/hdf_plugins

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:299 (add_hdf_vbz_plugin)

CMake Error at CMakeLists.txt:458 (get_filename_component):
  get_filename_component called with incorrect number of arguments

-- Configuring incomplete, errors occurred!

**Comment by malton-ont** [comment]
Hi @riej10. It looks like you haven't initialized the submodules, so some of the dependencies are missing. Try running:
```
git submodule update --init --recursive
```
in the root of the project.

It also looks like you have CUDA 11.5. I think you'll need a later version than that (we build with CUDA 11.8), so if you still have issues after initializing the submodules then try updating your CUDA toolkit.

You should also be aware that there are pre-built binaries available if there's no specific reason you're building from source - see https://github.com/nanoporetech/dorado?tab=readme-ov-file#installation
