### ISSUE TITLE
Basecalling/Mods versioning comparison

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/dorado#556]
Should we always use the "latest" basecalling/mods model when possible, even when the versioning of the mods version looks to be one behind?

Eg. dna_r10.4.1_e8.2_400bps_sup@**v4.3.0** has 5mCG_5hmCG at **v1**, but dna_r10.4.1_e8.2_400bps_sup@**v4.2.0** has 5mCG_5hmCG at **v3.1**. Similarly, dna_r10.4.1_e8.2_400bps_sup@**v4.3.0** has 6mA at **v1**, but dna_r10.4.1_e8.2_400bps_sup@**v4.2.0** has 6mA at **v3**.

Do the mods versioning mean anything here or are they actually meaningful? Eg. If we are going for the best mods accuracy which should we use?

**Comment by tijyojwad** [comment]
Hi @billytcl - this reply [here](https://github.com/nanoporetech/dorado/issues/512#issuecomment-1847587827) should help

**Comment by billytcl** [comment]
Got it! Thanks!
