### ISSUE TITLE
Request: Enable all context 5mC/5mC_5hmC for 4kHz models

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/dorado#557]
We have a bunch of R10 4kHz data (The new data acquisition mode is less than a year old! Many labs still have 4khz data) -- it would be nice to have the all-context 5mC and 5mC_5hmC models on standalone dorado. It's supported in dorado-server as of v7.0.8. Otherwise, it would be kind of annoying to go back to dorado-server to call the older data and use dorado standalone for the 5khz datasets.

**Comment by ymcki** [comment]
Is it possible to just run the standalone dorado with the model files used by dorado server in the compute unit? I think whether you can run all context models depends only on the model not on the software. Of course, if dorado server uses different format of models or the models it uses are built-in, then there is nothing you can do.

**Comment by MarkBicknellONT** [comment]
Hi @billytcl,

There haven't been any all-context 5mC or 5hmC models released for 4khz R10 data.  The configs in dorado_basecall_server for 4khz are all CG context only (i.e. they are either `dna_r10.4.1_e8.2_<speed>_modbases_5hmc_5mc_cg_<accuracy>.cfg` or `dna_r10.4.1_e8.2_<speed>_modbases_5mc_cg_<accuracy>.cfg`).

For any configuration file in the dorado_basecall_server release you can take a look inside the file to see the dorado standalone models that the config uses.  For example dna_r10.4.1_e8.2_400bps_modbases_5mc_cg_sup.cfg in version 7.0.8 uses:
```
dorado_model_path                   = dna_r10.4.1_e8.2_400bps_sup@v4.1.0
dorado_modbase_models               = dna_r10.4.1_e8.2_400bps_sup@v3.5.2_5mCG@v2
```

We don't have any current plans to release any further models (including all-context modbase models) for R10.4.1 4khz data.  You can continue to use the existing CG-context models for your 4khz data however.

Kind regards,
Mark

**Comment by billytcl** [comment]
Ah, got it! I missed the CG in the model name!
