### ISSUE TITLE
flag issue when using --modified-bases on osx

### ISSUE THREAD

**Issue by dithiii** [nanoporetech/dorado#56]
I can successfully run dorado 0.1.0 on an apple silicon M1 Max chip with the following
`./dorado-0.1.0+4b0e9a6-Darwin/bin/dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.0.0 pod5dir > calls.sam `

However when I add `--modified-bases 5mCG` to the command, per instructions, it fails. Looks like a flag parsing error?
```
./dorado-0.1.0+4b0e9a6-Darwin/bin/dorado basecaller --modified-bases 5mCG dna_r10.4.1_e8.2_400bps_sup@v4.0.0 pod5dir > calls.sam 
[2022-12-07 15:06:25.351] [error] 'dna_r10.4.1_e8.2_400bps_sup@v4.0.0' is not a supported modification please select from 5mCG, 5mCG_5hmCG
```

**Comment by iiSeymour** [comment]
Hey @dithiii 

There are a few things to unpack here. First, the error you are seeing is because `--modified-bases` takes multiple arguments i.e. `5mCG 6mA` *(example only - 6mA models are not available in dorado just yet)* so you can't use `--modified-bases` before the positional arguments.

```
$ dorado basecaller --help
Usage: dorado [-h] [--device VAR] [--max-reads VAR] [--batchsize VAR] [--chunksize VAR] [--overlap VAR] [--num_runners VAR] [--modified-bases VAR...] [--modified-bases-models VAR] [--emit-fastq] [--emit-moves] model data

Positional arguments:
  model                         the basecaller model to run. 
  data                          the data directory. 

Optional arguments:
  -h, --help                    shows help message and exits 
  -v, --version                 prints version information and exits 
  -v, --verbose          
  -x, --device                  device string in format "cuda:0,...,N", "cuda:all", "metal" etc.. [default: "metal"]
  -n, --max-reads               [default: 0]
  -b, --batchsize               if 0 an optimal batchsize will be selected [default: 0]
  -c, --chunksize               [default: 10000]
  -o, --overlap                 [default: 500]
  -r, --num_runners             [default: 2]
  --modified-bases              [nargs: 1 or more] 
  --modified-bases-models       a comma separated list of modified base models [default: ""]
  --emit-fastq           
  --emit-moves    
```

The usage string does suggest you can do this and the error message clould be clearer here. I will raise it with the upstream argument parsing library we are using.

Secondly, for the v4.0.0 simplex models `5mCG_5hmCG` is now standard so you'll want: 

```
$ dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.0.0 pod5dir --modified-bases 5mCG_5hmCG > calls.sam
```

Thirdly, and most importantly I've just seen we have a bug in the device handling with mods on osx so we need to get that sorted 🤦🏻 

```
$ dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.0.0 pod5dir --modified-bases 5mCG_5hmCG > calls.sam
[2022-12-08 22:08:15.246] [info] > Creating basecall pipeline
[2022-12-08 22:08:15.341] [error] Pinned memory requires CUDA. PyTorch splits its backend into two shared libraries
```

**Comment by dithiii** [comment]
Yes that syntax works, with the `--modified-bases` at the end. The dorado front page usage example should be changed to reflect that order. 

Of course by "works" I mean, it then proceeded to fail on the next issue, the device handling. :) But we are making progress! Thank you.

**Comment by iiSeymour** [comment]
> The dorado front page usage example should be changed to reflect that order.

Great point! I have updated the readme.

**Comment by dbl03069** [comment]
> Hey @dithiii
> 
> There are a few things to unpack here. First, the error you are seeing is because `--modified-bases` takes multiple arguments i.e. `5mCG 6mA` _(example only - 6mA models are not available in dorado just yet)_ so you can't use `--modified-bases` before the positional arguments.
> 
> ```
> $ dorado basecaller --help
> Usage: dorado [-h] [--device VAR] [--max-reads VAR] [--batchsize VAR] [--chunksize VAR] [--overlap VAR] [--num_runners VAR] [--modified-bases VAR...] [--modified-bases-models VAR] [--emit-fastq] [--emit-moves] model data
> 
> Positional arguments:
>   model                         the basecaller model to run. 
>   data                          the data directory. 
> 
> Optional arguments:
>   -h, --help                    shows help message and exits 
>   -v, --version                 prints version information and exits 
>   -v, --verbose          
>   -x, --device                  device string in format "cuda:0,...,N", "cuda:all", "metal" etc.. [default: "metal"]
>   -n, --max-reads               [default: 0]
>   -b, --batchsize               if 0 an optimal batchsize will be selected [default: 0]
>   -c, --chunksize               [default: 10000]
>   -o, --overlap                 [default: 500]
>   -r, --num_runners             [default: 2]
>   --modified-bases              [nargs: 1 or more] 
>   --modified-bases-models       a comma separated list of modified base models [default: ""]
>   --emit-fastq           
>   --emit-moves    
> ```
> 
> The usage string does suggest you can do this and the error message clould be clearer here. I will raise it with the upstream argument parsing library we are using.
> 
> Secondly, for the v4.0.0 simplex models `5mCG_5hmCG` is now standard so you'll want:
> 
> ```
> $ dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.0.0 pod5dir --modified-bases 5mCG_5hmCG > calls.sam
> ```
> 
> Thirdly, and most importantly I've just seen we have a bug in the device handling with mods on osx so we need to get that sorted 🤦🏻
> 
> ```
> $ dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.0.0 pod5dir --modified-bases 5mCG_5hmCG > calls.sam
> [2022-12-08 22:08:15.246] [info] > Creating basecall pipeline
> [2022-12-08 22:08:15.341] [error] Pinned memory requires CUDA. PyTorch splits its backend into two shared libraries
> ```

Thanks for clarifying this! I managed to run the regular basecalling but (not surprisingly) failed to run modified basecalling. As I am highly interested in modified basecalling, I would greatly appreciate if you could get this to work on the Apple M1 platform.

**Comment by iiSeymour** [comment]
The latest release _(v0.2.1)_ has mod calling on M1.
