### ISSUE TITLE
Issue with aligner (AlignerNode validation error checking minimap options)

### ISSUE THREAD

**Issue by smaegol** [nanoporetech/dorado#560]
Recently I encountered an error with dorado v0.5.0 and v.0.5.1. When running basecalling with provided reference (--reference option), dorado throws an error 

```
[error] AlignerNode validation error checking minimap options)
```

When running dorado aligner with the same reference the error is :
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  AlignerNode validation error checking minimap options
Aborted (core dumped)
```

The error is present:
1. no matter if fasta or mmi file is provided as reference
2. both for dorado basecaller and dorado aligner
3. the localization of reference file does not matter (on mounted NAS share or local)

This error does not show up in dorado 0.4.3 (only in 0.5.0 and 0.5.1 tested), using the same files/settings.

I'm using binaries downloaded from the links provided in the documentation (linux-64), on Ubuntu 22.04 system. 

Although this error message suggests some mistake in he minimap2 options provided it turns out it is related to minimap2 index loading (https://github.com/nanoporetech/dorado/blob/a7fb3e3d4afa7a11cb52422e7eecb1a2cdb7860f/dorado/read_pipeline/AlignerNode.cpp#L26C1-L27C91) so I would suggest also more meaningful error message. 

How can I deal with this problem?

**EDIT**
This seem to be somehow specific to my system setup, as I tested on different machine (Ubuntu 20.04) and everything works fine. Something I did not mention before is the additional error: 
```
[ERROR] with '-rNUM1,NUM2', NUM1 (500200) can't be larger than NUM2 (20000)
``` 
showing up before AlignerNode error when executing dorado basecaller. But this occurs also for dorado 0.4.3 and does not cause any problems for basecalling and mapping.

**Comment by tijyojwad** [comment]
Hi @smaegol I think this is an issue we've run into before and it's related to locale. Can you post your `locale` settings?
```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

This workaround from another post should help if that's the issue - https://github.com/nanoporetech/dorado/issues/432#issuecomment-1787085501

**Comment by smaegol** [comment]
Yes, that was the locale issue. I already fixed that by setting --bandwidth option for dorado manually.
