### ISSUE TITLE
Unusual read length distribution peak using Dorado which is not occuring when using Guppy 

### ISSUE THREAD

**Issue by termithorbor** [nanoporetech/dorado#563]
Hi all,

when I use Dorado with the following commands I get an unusual peak around 50 bp when examing the read length dirstribution:

dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.2.0 /pod5 >basecall.bam
dorado demux --kit-name SQK-NBD114-24 --output-dir dorado_demultiplex/ --emit-fastq basecall.bam
dorado trim SQK-NBD114-24_barcode05.fastq --emit-fastq >barcode05_trimmed.fastq

![image](https://github.com/nanoporetech/dorado/assets/66436023/ffc40570-ed38-48c1-8613-00467189427c)

In comparison these are the results when Guppy is used with the following commands:

guppy_basecaller --input_path /pod5 --save_path /basecall --config dna_r10.4.1_e8.2_400bps_5khz_sup.cfg -x "cuda:all:100%"
guppy_barcoder --input_path /basecall/pass --save_path /demultiplex --barcode_kits SQK-NBD114-24 --enable_trim_barcodes --trim_adapters -x "cuda:all:100%" --records_per_fastq 0

![image](https://github.com/nanoporetech/dorado/assets/66436023/577cebbf-8770-464e-9fe5-ab780a46a9a4)

What could cause these differences?

Thanks in advance.

All the best,
Thorben

**Comment by tijyojwad** [comment]
Hi @termithorbor - can you see if the distribution from the original (non-demuxed, non-trimmed) basecalls look okay? I'm wondering if either barcode trimming or adapter trimming is causing this peak.

**Comment by termithorbor** [comment]
Hi @tijyojwad, 
I have done bascalling with the no-trim no demux setting on a small part of my data and there the distribution seems to be okay. The data is from a transposon analysis where we integrated transposons in the genome from Salmonella to check for essential genes. Do those transoposons interfer with Dorado but not with Guppys algorithm?

![image](https://github.com/nanoporetech/dorado/assets/66436023/3fbb60c6-f012-4080-a1c2-b7b8144610d3)

**Comment by tijyojwad** [comment]
Thanks for running this @termithorbor - so either trimming of barcodes or adapters is causing overtrimming. Would it be possible for you to share some data? A fastq with a few reads that were getting overtrimmed would be great.

In the meantime you could use
```
dorado demux --kit-name SQK-NBD114-24 --no-trim --output-dir dorado_demultiplex/ --emit-fastq basecall.bam
```
to get the demuxed output without any trimming. This way you can continue with your experiment but you don't lose good data

**Comment by termithorbor** [comment]
I would not mind to send you some data. How can I do that?

**Comment by tijyojwad** [comment]
Just a few representative reads should be fine (e.g. the ones that you see being trimmed down to ~50 bps). You can put it those in a fastq file, compress it and upload to this GitHub issue

**Comment by tijyojwad** [comment]
Hi @termithorbor just following up to see if you can share the data?

**Comment by termithorbor** [comment]
Hi @tijyojwad sorry for the delayed response. Here are the requested files. I have attached pod5 files, basecall with primer detection and demultiplexing (basecall.bam and demux folder).
Thanks for your help and if you have any further questions please let me know.

[Dorado_data.zip](https://github.com/nanoporetech/dorado/files/14110323/Dorado_data.zip)

**Comment by tijyojwad** [comment]
Hi @termithorbor - thanks for sharing the data! I ran this data through dorado v0.5.2 where we fixed some issues with trimming and I actually don't see much trimming going on anymore. Would you be able to retry with the latest build?

**Comment by tijyojwad** [comment]
Hi @termithorbor - I'm closing this issue since I haven't heard back from you. If you have follow up questions, please feel free to re-open it!
