### ISSUE TITLE
Required key CL not found in header of incomplete bam file 

### ISSUE THREAD

**Issue by careenfoord** [nanoporetech/dorado#565]
After trying to basecall a sample which stopped while basecalling and combining with previously basecalled reads I am getting this error. The incomplete bam file was generated by Picard FastqToSam, note that it is unmapped. How can I generate the key CL in the header of the bam file to finish my basecalling?

```
bin/dorado basecaller --batchsize 64 --device cuda:all dna_r10.4.1_e8.2_400bps_hac@v4.3.0 /media/Expansion/12_21_23_329_Curio_VIS_Exome_LW/no_sample/20231221_2205_1C_PAU51814_d64c6056/pod5/ --resume-from /media/Expansion/12_21_23_329_Curio_VIS_Exome_LW/no_sample/329basecalled_fastqtosam.bam > /home/Desktop/329/329basecalled.bam
[2024-01-05 16:38:54.030] [info] > Creating basecall pipeline
[2024-01-05 17:01:18.615] [info] > Inspecting resume file...
[2024-01-05 17:01:18.681] [error] Required key CL not found in header of /media/Expansion/12_21_23_329_Curio_VIS_Exome_LW/no_sample/329basecalled_fastqtosam.bam

```

**Comment by tijyojwad** [comment]
Hi @careenfoord - was the file you're resuming from also called by dorado? Can you post the BAM header from that file?

**Comment by tijyojwad** [comment]
@careenfoord any updates?

**Comment by HalfPhoton** [comment]
Closing as there have been no updates - please re-open if you're issue is not resolved
