### ISSUE TITLE
More RNA mod models?

### ISSUE THREAD

**Issue by itslittman** [nanoporetech/dorado#568]
The DRACH motif 6mA model is amazing!!! Are there going to be models coming out for pseudo-U and inosine?

**Comment by a-slide** [comment]
Hi @itslittman,
Thank you for your feedback. It is much appreciated by all the people at ONT who participated in this effort.
We do have plans to train more RNA modifications models and add support via Dorado, including the 2 you mentioned above.

**Comment by itslittman** [comment]
@a-slide Amazing to hear! Is there a rough timeline for that/within 2024?

**Comment by a-slide** [comment]
Hard to tell exactly, it is still very much at research stage, and we have high validation standards before open release.
If everything goes to plan, we might have all contexts pseudoU and m6A for Q2 2024.
Other modifications later in the year

**Comment by VBHerrenC** [comment]
@sq101  Also hoping they include N1-methyl pseudoU - I know they presented a slide on a research model for it at the Houston Community Meeting in December, so it looks like they're working on it. Keeping our fingers crossed!
