### ISSUE TITLE
Dorado failure to decompress data corruption error detected

### ISSUE THREAD

**Issue by nbertholdpgc** [nanoporetech/dorado#570]
Hi all,
I've been running into this issue with one of my samples. During the sequencing run on a GridION machine directly following a Dorado update, the run encountered software errors that caused it to need to be restarted a number of times. Ive attempted to do basecalling on several different occasions now and each time encounter n error. 

> sample 10 Dorado basecalling and alignment
> Dorado basecalling and alignment needs to be performed
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>  15 61.1M   15 9656k    0     0  33.9M      0  0:00:01 --:--:--  0:00:01 33.7M
> 100 61.1M  100 61.1M    0     0  70.9M      0 --:--:-- --:--:-- --:--:-- 70.8M
> [2023-12-24 23:42:46.574] [warning] Unknown certs location for current distribution. If you hit download issues, use the envvar `SSL_CERT_FILE` to specify the location manually.
> [2023-12-24 23:42:46.578] [info]  - downloading dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0 with httplib
> [2023-12-24 23:42:46.597] [error] Failed to download dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0: SSL server verification failed
> [2023-12-24 23:42:46.597] [info]  - downloading dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0 with curl
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>   8 1747k    8  142k    0     0   519k      0  0:00:03 --:--:--  0:00:03  517k
> 100 1747k  100 1747k    0     0  4348k      0 --:--:-- --:--:-- --:--:-- 4337k
> [2023-12-24 23:42:47.151] [info] > Creating basecall pipeline
> [2023-12-24 23:43:18.286] [info]  - set batch size for cuda:0 to 768
> [2023-12-24 23:54:25.647] [error] Failed to get read 338 signal: Invalid: Input data failed to decompress using zstd: (18446744073709551596 Data corruption detected)
> [2023-12-25 00:36:21.943] [error] Failed to get read 858 signal: Invalid: Too few samples in input samples array
> terminate called without an active exception
> /var/spool/slurmd/job365631/slurm_script: line 20: 2768029 Aborted                 (core dumped) dorado basecaller dna_r9.4.1_e8_sup@v3.3 $TmpWD/pod5_pass/ --modified-bases 5mCG_5hmCG --min-qscore 9 -k 15 -w 10 -Y --reference $Ref > $TmpWD/S${num}DoradoWF-O.bam

Would the data corruption have occurred when the software failed? Or would it have been a user error, when transferring from the machine to a differentm server?

Any insight would be greatly appreciated!
Warm regards,

**Comment by tijyojwad** [comment]
Hi @nbertholdpgc - it looks like the pod5s may have been corrupted? can you run `pod5 view input.pod5 --ids --no-header` on the failing pod5 as a sanity check? this should output a list of read ids from the pod5 file

**Comment by nbertholdpgc** [comment]
> Hi @nbertholdpgc - it looks like the pod5s may have been corrupted? can you run `pod5 view input.pod5 --ids --no-header` on the failing pod5 as a sanity check? this should output a list of read ids from the pod5 file

Hi @tijyojwad thanks for the quick response! My only problem is I'm not entirely sure which pod5 file it is coming from. I have 893 files.

**Comment by tijyojwad** [comment]
We can check with just 1 and sanity check.

1. Pick a random pod5 from the dataset
2. run `pod5 view input.pod5 --ids --no-header > ids.txt`
3. run `dorado basecaller <model> <path_to_pod5> --modified-bases 5mCG_5hmCG --min-qscore 9` on that specific pod5 to check if basecalling is working

**Comment by nbertholdpgc** [comment]
Hi @tijyojwad sanity check worked this was the output of the basecalling:

>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>  34 61.1M   34 21.3M    0     0  32.0M      0  0:00:01 --:--:--  0:00:01 31.9M
> 100 61.1M  100 61.1M    0     0  52.4M      0  0:00:01  0:00:01 --:--:-- 52.5M
> [2024-01-10 10:56:42.971] [warning] Unknown certs location for current distribution. If you hit download issues, use the envvar `SSL_CERT_FILE` to specify the location manually.
> [2024-01-10 10:56:42.976] [info]  - downloading dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0 with httplib
> [2024-01-10 10:56:43.062] [error] Failed to download dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0: SSL server verification failed
> [2024-01-10 10:56:43.062] [info]  - downloading dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0 with curl
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100 1747k  100 1747k    0     0  4447k      0 --:--:-- --:--:-- --:--:-- 4447k
> [2024-01-10 10:56:43.607] [info] > Creating basecall pipeline
> [2024-01-10 10:56:59.065] [info]  - set batch size for cuda:0 to 768
> [2024-01-10 10:57:23.655] [info] > Simplex reads basecalled: 3903
> [2024-01-10 10:57:23.656] [info] > Simplex reads filtered: 98
> [2024-01-10 10:57:23.656] [info] > Basecalled @ Samples/s: 4.658000e+06
> [2024-01-10 10:57:23.700] [info] > Finished

**Comment by tijyojwad** [comment]
Great, so dorado is working fine, and the error from your logs is indicative of some file corruption.

Let me see if I can create a build with additional logs to print which pod5 file is being loaded. this can help determine the failure point.

In the meantime, you can loop over each pod5 file in your directory and run dorado on it. The failing runs will highlight the corrupted files.

**Comment by nbertholdpgc** [comment]
Thanks @tijyojwad ! I'll give that a go now :D

**Comment by HalfPhoton** [comment]
@nbertholdpgc, were you able to find the source of the suspected file corruption? 

Kind regards,
Rich

**Comment by tijyojwad** [comment]
Hi @nbertholdpgc - I'm closing this ticket for now since we haven't heard back. Please re-open if you have any follow up questions.
