### ISSUE TITLE
Question GPU

### ISSUE THREAD

**Issue by Taalouane** [nanoporetech/dorado#572]
Dear Colleagues,

Below are the characteristics of the two GPU nodes in a cluster that we want to use to install Dorado. Can you tell us if these characteristics correspond to making dorado work (duplex function on microorganisms) and preferably on which of the two nodes could work well?
Thanks,

Intel gpu node
Number of nodes: 2
Number of cores per node: 40
Processor type: Intel Xeon Gold  2.5GHz
Graphics Card: 4 NVidia Tesla V100 cards in Nvlink
Available memory per node (GB): 192

AMD gpu node
Number of nodes: 1
Number of cores per node: 32
Processor type: AMD Epyc 3GHz
Graphics card: 3 NVidia Tesla V100 cards in PCIe
Available memory per node (GB): 256

**Comment by vellamike** [comment]
Hi, yes Dorado will work on these nodes. The 4xV100 nodes will probably be better.

**Comment by vilnis01** [comment]
Dear Taalouane,
I am also working on a computer cluster and I'm trying to run dorado basecalling on several GPUs simultaneously.
I am attempting to do this by changing the variables in `#PBS -l nodes=1:ppn=1:gpus=1` line and the parameters following "cuda:" in the line here `dorado basecaller hac /mnt/beegfs2/home/vilnis01/scorpionsPOD5/ --device cuda:0 --kit-name SQK-NBD114-96 > output.bam`. I triead increasing the number of GPUs, ppn, accordingly changing cuda: to "all" or "0,1", still I don't see improvement in basecalling speed (although it looks like I am able to activate more than one GPU). Could you post an example of your command line here?

Best regards,
Vilnis
P.S. the nodes I'm working on also use 4 NVIDIA V100 GPUs

**Comment by vellamike** [comment]
Hi @vilnis01  - Dorado will automatically use all available and visible GPUs on the node. You just need to leave the `--device` argument out completely.  Could you give some more detail of what you mean when you say "still I don't see improvement in basecalling speed"

**Comment by vilnis01** [comment]
Thanks anyway, @Taalouane ! I didn't change it to fast as the resources are sufficient to do it in hac or sup.
@vellamike , thanks for getting involved! I mean that It took the same amount of time for the job to complete regardless the GPUs involved, therefore I doubt that I have done it correctly. I will try again as you suggested to see if it improves the outcome.
I guess, besides changing the number of GPUs, do I also have to change the cuda to "all"? Should I increase the nubmer of processors (ppn)?

**Comment by vellamike** [comment]
> therefore I doubt that I have done it correctly

I wouldn't assume that, It's tricky to diagnose this issue but it's possible that you are IO limited here and that data is not reaching the compute nodes fast enough from your networked storage?

**Comment by vilnis01** [comment]
Thanks for the recommendation. I will check it as you described and, if nothing changes, contact the cluster's support.

**Comment by HalfPhoton** [comment]
@vilnis01, do you have any updates about this issue?

**Comment by vilnis01** [comment]
Hi @HalfPhoton ,
I tried what I could and I concluded that probably the dorado software is not designed to use more than one GPU simultaneously on computing clusters. I didn't bother the technical support because I got busy with other stuff. But I will ask them now if they can perform some testing to find out for sure.

**Comment by HalfPhoton** [comment]
Hi @vilnis01, any further updates on this?

> .. probably the dorado software is not designed to use more than one GPU simultaneously on computing clusters

Dorado should run on multiple GPUs in a compute cluster. 

Kind regards,
Rich

**Comment by xgnusr** [comment]
I'm sorry to disagree, but if an application only works well on a single node in a cluster, it is not a cluster application.
Doradodo basecaller only works fine on one node. In other words, it will take the same time to run on one node as on two, only in the latter case, the BAM file will contain duplicate readings. If running on three nodes, BAM file with triplicate readings.
It is NOT a cluster application.

**Comment by vellamike** [comment]
Hi @xgnusr, I think there is some confusion here, Dorado is not advertised as a "cluster application". If you want to run Dorado on multiple nodes of a cluster you should run each instance with separate input POD5s.

**Comment by vilnis01** [comment]
@HalfPhoton @xgnusr 
I believe that there is a misunderstanding. The question is if dorado can run on multiple GPUs, not multiple clusters (but that would be cool if it could). I couldn't make run it quicker on a single cluster which has 2 - 4 GPUs (depending on cluster) regardless the number of GPUs I requested in the script. Maybe I'm was doing something wrong but at least no error messages were produced. What is the optimal CPU number per GPU?

**Comment by xgnusr** [comment]
True, which is a shame. There could be a flag that indicates to the basecalling creation routine that it is a cluster and the threads run on each GPU node...
The definitive basecaller.

**Comment by Taalouane** [comment]
Dear colleagues,
Do you have any idea if dorado worked on H100NVL GPU on Intel platform? Thanks a lot in advance for your answer
