### ISSUE TITLE
what():  unknown simplex model dna_r10.4.1_e8.2_400bps_hac@v4.3.0

### ISSUE THREAD

**Issue by AzlanNI** [nanoporetech/dorado#574]
Hello dear Dorado Team, 

I am using Dorado for the first time to analyze some of our bacterial DNA Data. I want to basecall the pod5 files and also do a mod call for 6mA and 5mC. 

So my Input is looking like this: 
dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.3.0 ./ --modified-bases 5mC 6mA  > 819_non_Aligned.bam

I got the Error: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown simplex model dna_r10.4.1_e8.2_400bps_hac@v4.3.0

Then i tried with specifying the model with --modified-bases-models the input looked like this
dorado basecaller --modified-bases-models dna_r10.4.1_e8.2_400bps_hac@v4.3.0 ./ --modified-bases 5mC 6mA  > 819_non_Aligned.bam
i got the Error: 
[error] 1 argument(s) expected. 0 provided.
I also tried it with the  hac model my input looked like this: 
dorado basecaller hac pod5s/  --modified-bases 5mC 6mA > 819_non_Alignment.bam
I got the Error: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown simplex model hac

I also tried the command line from github on my pod5 files 
dorado basecaller hac ./ > calls.bam

and i got the Error: 
[2024-01-10 17:45:50.787] [info] > Creating basecall pipeline
[2024-01-10 17:45:50.788] [error] toml::parse: file open error -> hac/config.toml 

So now i really am thinking that something went wrong with the installation or the models installation. If yes could u tell me what we could change to get dorado running would love to include it in our analysis. 

So now i am a little bit confused are there no models the tool can call so something went wrong with the installation on out HPC or am i doing something completely wrong? 

We have Version 0.4.3+656766b installed

Appreciate any help! 

Kind regard, 
Azlan Nisar

**Comment by malton-ont** [comment]
Hi @AzlanNI. The @v4.3.0 basecall models were introduced in dorado-0.5.0, so you will need to update to access them. Likewise the automatic model selection (letting dorado select the specific model using `dorado basecaller hac`) is a 0.5.0 feature.

**Comment by AzlanNI** [comment]
Hi @malton-ont thanks u for ur answer! Could i use the v4.2.0 one ? Since we want to check 6mA and 5mC 

like this: 

dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.2.0 ./ --modified-bases 5mC 6mA  > 819_non_Aligned.bam

Or is this also only usable after the update ? I already asked them if they could update the Version. Just looking for some way to continue the work.

**Comment by AzlanNI** [comment]
@malton-ont Thanks for ur reply! I tried 

dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.2.0  ./ --modified-bases 5mC 6mA  > 819_non_Aligned.bam

and got the Error: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown simplex model dna_r10.4.1_e8.2_400bps_sup@v4.2.0

could u help me out ?

**Comment by malton-ont** [comment]
@AzlanNI Have you downloaded the model? Use:
```
dorado download --model dna_r10.4.1_e8.2_400bps_sup@v4.2.0
```
to download the model to the local directory. You can also add `--directory <path>` to put it in a specific location, and use that path when you launch the basecaller:
```
dorado download --model dna_r10.4.1_e8.2_400bps_sup@v4.2.0 --directory /data/models
dorado basecaller /data/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0 ./ --modified-bases 5mC 6mA > 819_non_Aligned.bam
```

**Comment by malton-ont** [comment]
In that case you'll want to just call `dorado download` on a net-connected machine to get _all_ the models and then install those on your HPC.

**Comment by AzlanNI** [comment]
@malton-ont alright i will tell this to our Support Team and give a feedback how it works after! Thanks for ur reply!

**Comment by AzlanNI** [comment]
Hey @malton-ont the Support team did update Dorado to 0.5.1. So now i tried different stuff first i tried following line: 

dorado basecaller dna_r10.4.1_e8.2_400bps_hac /gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Myco_R10/fast5s/819_pod5/Output_pods --modified-bases 5mC 6mA  > 819_non_Aligned.bam

it resulted in the Error: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown simplex model dna_r10.4.1_e8.2_400bps_hac

Then i realised that the support team copied the models into a different directory called /software/dorado/models so i got over there and cp the model i wanted over into my working directory. After that i let the following line run: 
dorado basecaller dna_r10.4.1_e8.2_400bps_hac\@v4.3.0/  /gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Myco_R10/fast5s/819_pod5/Output_pods --modified-bases 5mC 6mA  > 819_non_Aligned.bam

And i got the Error: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  could not find matching modification model for dna_r10.4.1_e8.2_400bps_hac@v4.3.0
[1]+  Getötet                dorado download --model all

So then i tried 
dorado basecaller hac ./ > calls.bam again and it started to work for a while and but then started downloading 
[2024-01-12 14:17:30.306] [info] Assuming cert location is /etc/ssl/certs/ca-bundle.crt
[2024-01-12 14:17:30.358] [info]  - downloading dna_r10.4.1_e8.2_400bps_hac@v4.3.0 with httplib

So i guess the models are copied but not downloaded. Or am i wrong  with something else? 

Thank u for ur help! 

Kind regards,
Azlan

**Comment by malton-ont** [comment]
Hi @AzlanNI. You have a few issues here, all mixed up together.

First, if you're specifying the model, it needs to match a model folder name exactly. `dna_r10.4.1_e8.2_400bps_hac` != `dna_r10.4.1_e8.2_400bps_hac@v4.3.0` - you need to include the version here.

Second, if you've specified a relative path then dorado looks for the model relative to the working directory. You can specify an absolute path if that's easier - `dorado basecaller /software/dorado/models/dna_r10.4.1_e8.2_400bps_hac@v4.3.0` for example.

When you copied the basecall model locally it was being found, but you've asked for 5mC and 6mA modification calling. There is no compatible 5mC model for `dna_r10.4.1_e8.2_400bps_hac@v4.3.0` - there's a 5mC_5hmC though. As far as I can see, the only model with both 5mC and 6mA all-context modifications is `dna_r10.4.1_e8.2_400bps_sup@v4.2.0`. You can see the full list of available models by running `dorado download --list` - remember that modified models must match the basecall model exactly! If you want to make sure you don't download anything during running, I'd also suggest using `--modified-bases-models "<path_to_5mC_model>,<path_to_6mA_model"` rather than just specifying the modifications.

Automatic model detection always downloads the required models into a temporary local folder (and deletes them on exit). If you want to use pre-downloaded models you have to specify the paths.

**Comment by AzlanNI** [comment]
@malton-ont  first of all thanks for ur fast replys! So i did change the code line 

dorado basecaller --modified-bases-models /software/dorado/0.5.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mC@v2,/software/dorado/0.5.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v3 /gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Myco_R10/fast5s/819_pod5/Output_pods > 819_non_Aligned.bam

So i specified the basecallers instead of the modified-bases. Now i am encountering the following: 
[2024-01-15 13:05:22.440] [error] 1 argument(s) expected. 0 provided. 

I guess its not recognizing the input Data so there must be something wrong with the syntax. Thanks for all ur help! 

Kind regards, 
Azlan

**Comment by AzlanNI** [comment]
Ah i forgot the model before data sry my mistake! I will respond if the job runs into a new Error thanks for ur amazing help!

**Comment by AzlanNI** [comment]
Perhaps another question if i wanted to generate an aligned BAM file with a reference could i just sneak in a --reference reference.fas file ?

**Comment by malton-ont** [comment]
Yes, the `--reference` argument is shown under the help for the basecaller command:
```
dorado basecaller --help
Usage: dorado [-h] [--device VAR] [--read-ids VAR] [--resume-from VAR] [--max-reads VAR] [--min-qscore VAR] [--batchsize VAR] [--chunksize VAR] [--overlap VAR] [--recursive] [--modified-bases VAR...] [--modified-bases-models VAR] [--modified-bases-threshold VAR] [--emit-fastq] [--emit-sam] [--emit-moves] [--reference VAR] [--kit-name VAR] [--barcode-both-ends] [--no-trim] [--trim VAR] [--sample-sheet VAR] [--barcode-arrangement VAR] [--barcode-sequences VAR] [--estimate-poly-a] [-k VAR] [-w VAR] [-I VAR] [--secondary VAR] [-N VAR] [-Y] [--bandwidth VAR] model data
...
Optional arguments:
...
  --reference                   Path to reference for alignment. [default: ""]
...
```

**Comment by AzlanNI** [comment]
Yeah i just got terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to write SAM record, error code -1

**Comment by AzlanNI** [comment]
No sure i can open a new one.

**Comment by tijyojwad** [comment]
Closing this issue as the original problem is now resolved
