### ISSUE TITLE
Error using pre-download modified base models :  [error] key "input" not found in the top-level table

### ISSUE THREAD

**Issue by RxLoutre** [nanoporetech/dorado#577]
Hi Dorado team !

I have downloaded a bunch of models with dorado download (curl, not SSL) : 

`dorado download --model dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1
`
Then I am trying to use that model to basecall with : 

`dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1 "/path/to/some/pod5"
`

But I get the following error : 

```
[2024-01-11 14:20:01.792] [info] > Creating basecall pipeline
[2024-01-11 14:20:01.793] [error] [error] key "input" not found in the top-level table
 --> dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1/config.toml
   |
 1 | [general]
   | ^--- the top-level table starts here
```

Same issue with the following models : 

dna_r10.4.1_e8.2_400bps_hac@v4.3.0_5mCG_5hmCG@v1
dna_r10.4.1_e8.2_400bps_sup@v4.3.0_6mA@v1
dna_r10.4.1_e8.2_400bps_hac@v4.3.0_6mA@v1
dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mC_5hmC@v1
dna_r10.4.1_e8.2_400bps_hac@v4.3.0_5mC_5hmC@v1
dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1

(Everything with modified base basically)

But it works for the following models : 

dna_r10.4.1_e8.2_400bps_sup@v4.3.0
dna_r10.4.1_e8.2_400bps_hac@v4.3.0

Any idea what could go wrong ? I am basecaliing on A100.

Best,

**Comment by malton-ont** [comment]
Hi @RxLoutre,

The modified base models are run in addition to the basecall models, not instead of. You need to specify both, like so:
```
dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.3.0 "/path/to/some/pod5" --modified-bases-models dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1
# or
dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.3.0 "/path/to/some/pod5" --modified-bases 5mCG_5hmCG
```

To make this even easier, in dorado-0.5.0+ you can automatically detect and download the models:
```
dorado basecaller sup,5mCG_5hmCG <pod5>
```

**Comment by RxLoutre** [comment]
Dear @malton-ont , thank you for your swift answer ! :) I see, I misunderstood the usage of the models. I will take in account your feedback to change my wrapper. Thank you !

Sadly, because of our bad connection, it proved unefficient to downlaod before each basecall, hence I decided to download them once and for all, and I will stay updated by downloading new models as they come out.

Thank again !

Roxane
