### ISSUE TITLE
Dorado installation on MAC M3PRO

### ISSUE THREAD

**Issue by luisymbio** [nanoporetech/dorado#582]
Hi all, how is possible to install Dorado on Mac? Up to now I always used it on server or locally on linux unfortunately.

**Comment by susie-ont** [comment]
Hi @luisymbio, you can install the latest Dorado using the OSX link in the [Installation](https://github.com/nanoporetech/dorado?tab=readme-ov-file#installation) section of our readme. 
Once downloaded and unzipped, you can either run Dorado directly, for example:

`/path/to/dorado-0.5.1-osx-arm64/bin/dorado basecaller hac pod5s/ > calls.bam`

Or you can add `/path/to/dorado-0.5.1-osx-arm64/bin` to your system path, and you will be able to run: 

`dorado basecaller hac pod5s/ > calls.bam`

Did this work for you?

**Comment by luisymbio** [comment]
Hi @susie-ont, thank you for the reply. I already tried that method, sorry for have not mentioned it before. After that I try to recall the command, both as you suggested or for example dorado -h, the command line gives me an error related to the absence of the library required by dorado. That libraries are present in the folder lib downloaded from the github page, but I'm not able to find a way to tell to the software to recall it from the right position.

**Comment by malton-ont** [comment]
Dorado should be configured to look for the libraries that ship with it. Could you run the following commands and post the output?
```
echo $DYLD_LIBRARY_PATH
otool -l dorado
otool -L dorado
```
This should tell us the paths dorado is expecting to look in as well as which libraries it has found and which it has not.

**Comment by luisymbio** [comment]
Hi @malton-ont ,
`error: /Library/Developer/CommandLineTools/usr/bin/otool-classic: can't open file: dorado (No such file or directory)`

That is the output of 
`otool -l dorado
otool -L dorado`

while the first command give me nothing.

I installed again dorado and now seems that recalling the path 

`/path/to/dorado-0.5.1-osx-arm64/bin/dorado -h`

in that way is working.

I still have the question if the output of otool command line is okay, or if it is a red flag of something that still need to be fixed.

**Comment by malton-ont** [comment]
That just indicates that you don't have `dorado` in your path, so it should have been called as `otool -L /path/to/dorado`. If the dorado command is now working then it just looks like your download was incomplete.

**Comment by luisymbio** [comment]
@malton-ont @susie-ont thank you both for your replies. Probably I modified something without looking it, I'm pretty new in macOs environment.
