### ISSUE TITLE
flawed bam file header in base called bam files

### ISSUE THREAD

**Issue by marianpricecarter** [nanoporetech/dorado#583]
The headers in Dorado base called (simple and duplex) as well as alignmnent bam files are incomplete.  SAMTools quickcheck gives the following error: had no targets in header

**Comment by tijyojwad** [comment]
Hi @marianpricecarter 

simplex and duplex outputs are unaligned BAMs, so you'll need to run it with 
```
samtools quickcheck -u output.bam
```

As for the aligned BAMs, those should work without `-u` and I've checked for that locally. Can you send me a repro case for the aligned BAMs showing up as incomplete?

**Comment by marianpricecarter** [comment]
Thank you Joyjit,

I was able to run the samtools check as you suggested on the Ubuntu computer but I was hoping to work with these on our HPC and just checked.  Perhaps the samtools is older there, because it did not like -u.

On the UBUNTU system the aligned files were OK without the -u but not so on the HPC.

I would like to use different features in Minimap2 and will need to convert the dorado base called bam into a fastq or fasta.  Do you have a preferred way to convert the dorado called bam?

Thanks
Marian

**Comment by tijyojwad** [comment]
I typically use `samtools bam2fq` for that. Note that fastq will result in some metadata from the read records being dropped. Alternatively dorado can also generate fastq via the `--emit-fastq` option in the cmdline.

What features in minimap2 are you using? We could consider adding those to dorado in the future

**Comment by marianpricecarter** [comment]
Hi Joyjit,

I am using the following for mapping GC rich, repetitive mycobacterial DNA to a reference:

minimap2 -a --secondary=no --sam-hit-only

Another question, my data are sorted into separate folders by bar codes when I do preliminary real time base calling during the sequencing.  I have been durado basecalling each separately.  Is there a way to process all of them simultaneously - ie a multiple thread command for Durado?

Thanks and Cheers
Marian

**Comment by tijyojwad** [comment]
> I have been durado basecalling each separately.  Is there a way to process all of them simultaneously - ie a multiple thread command for Durado?

yes you can point dorado to the parent folder and add `-r` to the command line and dorado will recursively find all the pod5 files

**Comment by marianpricecarter** [comment]
Thank you 😊

**Comment by marianpricecarter** [comment]
Hello again Joyjit,

I am base calling again and was trying to use your suggestion of -r for how Dorado base call  multiple barcode sorted folders of pod5 files.  I would like to make different fastq files for each folder.  Will this require some kind of variable in the command?

Path_to_Dorado/dorado duplex sup Path_to_parent_file  --emit-fastq -r > fastqs

Thanks very much for your help
Marian

From: Marian Price-Carter
Sent: Wednesday, January 31, 2024 5:40 PM
To: 'nanoporetech/dorado' ***@***.***>
Subject: RE: [nanoporetech/dorado] flawed bam file header in base called bam files (Issue #583)

Thank you 😊

**Comment by marianpricecarter** [comment]
Hi Joyjit and crew,

My Native ligation pod5 files were not automatically demultiplexed with the last run.  I did not change anything about how I set up the sequencing run so I am assuming this is how this will be from now on?

I am trying to figure out how to demultiplex into separate fastq files while Durado base calling.  Can you please provide a set of commands that will allow me to do this?

Thanks very much in advance for any help you can offer.

Marian

From: Marian Price-Carter
Sent: Monday, March 11, 2024 9:17 PM
To: 'nanoporetech/dorado' ***@***.***>
Subject: RE: [nanoporetech/dorado] flawed bam file header in base called bam files (Issue #583)

Hello again Joyjit,

I am base calling again and was trying to use your suggestion of -r for how Dorado base call  multiple barcode sorted folders of pod5 files.  I would like to make different fastq files for each folder.  Will this require some kind of variable in the command?

Path_to_Dorado/dorado duplex sup Path_to_parent_file  --emit-fastq -r > fastqs

Thanks very much for your help
Marian

From: Marian Price-Carter
Sent: Wednesday, January 31, 2024 5:40 PM
To: 'nanoporetech/dorado' ***@***.******@***.***>>
Subject: RE: [nanoporetech/dorado] flawed bam file header in base called bam files (Issue #583)

Thank you 😊

**Comment by tijyojwad** [comment]
Hi @marianpricecarter 

You can run 

```
$ dorado basecaller <model> <pod5> --kit-name <barcode_kit> > out.bam
$ dorado demux --no-classify --emit-fastq --output-dir <folder> out.bam
```

**Comment by marianpricecarter** [comment]
Thanks Joyjit,

I would like fastq files rather than bam files.  Should this be --output-dir <folder> out.fastq? or will this not work?

Best Wishes
Marian

**Comment by tijyojwad** [comment]
The `--emit-fastq` in the `dorado demux` command will save fastqs in the `--output-dir` folder (one fastq per barcode).

You can also add `--emit-fastq` to the `dorado basecaller` cmd but it's not necessary.

**Comment by marianpricecarter** [comment]
Hi Again,


These commands work when I use basecaller, but not when I try it with duplex.  Is there a command that will facilitate duplex basecalling on these data followed by demux?

$ dorado basecaller <model> <pod5> --kit-name <barcode_kit> > out.bam

$ dorado demux --no-classify --emit-fastq --output-dir <folder> out.bam

Thanks and Best Wishes
Marian
