### ISSUE TITLE
Base calling on DNA with dense N6-methyladenine (6mA) modifications

### ISSUE THREAD

**Issue by ywang285** [nanoporetech/dorado#586]
Hi, I am working on DNA molecules extracted from agarose gel, and each DNA molecule has very dense N6-methyladenine (6mA) modifications (at least 3 or 4 N6-methyladenines per 200 bp). During sequencing on PromethION, I found only ~30% reads have quality score higher than 9 (therefore MinKNOW saved these reads in "pod5_pass" folder). The rest 70% reads were saved in "pod5_fail" folder. I sequenced another sample (also extracted from agarose gel) without 6mA modifications, and got 70% "passed" reads (quality score >9). Therefore, my hypothesis is that 6mA generates weird signals that MinKNOW thinks these 6mA bases are low-quality bases, and gave low quality score to the read. Do you think it could be the case?

I was using Dorado to do basecalling on those "failed" reads:

dorado basecaller --verbose ./models/dna_r10.4.1_e8.2_400bps_sup@v4.3.0 pod5_fail_folder --modified-bases-models ./models/dna_r10.4.1_e8.2_400bps_sup@v4.3.0_6mA@v2 --modified-bases-threshold 0 > calls.bam

Then I used minimap2 -x map-ont to do the mapping. I got very few reads mapped. It seems for those failed reads, canonical bases (i.e., ATCG) were called incorrectly so that minimap2 cannot map those reads. With the above command, does Dorado call ATCG first and then only do the modbase (6mA) calling on adenines? Is there anything I can do to try to figure out the sequence of those failed reads?Thanks!

**Comment by HalfPhoton** [comment]
Hi @ywang285,

Dorado does call the canonical bases before modifications as you said so the addition of mods  basecalling will not have an effect on the canonical base calling.

From your description it appears that there is sufficiently high 6mA content to affect Dorado's ability to call these canonical bases. 

I'll raise this issue internally to hopefully improve our performance in these highly methylated reads in future generations of models. 
Unfortunately, to the best of my knowledge, we have no immediate fix for this issue.

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
Hi @ywang285,
I've discussed this with my colleagues and we were intrigued by your results. We don't observe such a large impact on alignment from samples with the modifications and rates you stated. 

We believe that there could be an issue with your sample which is causing this issue. 

Kind regards,
Rich

**Comment by ywang285** [comment]
Hi @HalfPhoton,
Thank you so much for your reply! I also did more testing and I found it may be caused by very low DNA input during library prep. I typically get around 0.5ng to 1ng DNA sample, and I tried SQK-LSK114, SQK-RAD114 and SQK-NBD114.24 kits. I got low quality score and sometimes very weird read length from the MinKNOW (N50 >300kb, which is impossible for my library). I attached some reports generated by [MinKNOW.]
[MinKNOW Run Report-05-10-2023-PAQ21967.pdf](https://github.com/nanoporetech/dorado/files/14171556/MinKNOW.Run.Report-05-10-2023-PAQ21967.pdf)
[MinKNOW Run Report-22-12-2023-PAS58451.pdf](https://github.com/nanoporetech/dorado/files/14171557/MinKNOW.Run.Report-22-12-2023-PAS58451.pdf)
However, all my sequencing libraries with >100ng DNA input for library prep worked fine (>80% pass reads and expected read length). Do you think if there is a possible reason behind this (i.e., low DNA input for library prep causes a lot of "failed" reads)?

Thanks!

**Comment by HalfPhoton** [comment]
Hi @ywang285, as this is potentially not an issue with dorado could you please raise this issue in the nanopore community pages where a member of the Technical Services team can help you?

Kind regards,
Rich
