### ISSUE TITLE
Doubts about the number and length distribution of reads identified with polyA

### ISSUE THREAD

**Issue by creaturemoon** [nanoporetech/dorado#588]
Hi,
    I used `dorado 0.5.1 a7fb3e3` to run basecalling on DRS data with the following command.
`dorado basecaller rna004_130bps_sup@v3.0.1 raw.pod5  --verbose  --emit-moves  --estimate-poly-a  --modified-bases m6A_DRACH > raw_polya_sup.bam`
    The proportion of reads with polyA is about 19% (6951290 reads) and the average length is 110. The sequencing company's analysts used `dorado 0.4.3` for polyA analysis. They acquired 35227668 reads with polyA (98.33%) with shorter average length. The two results are quite different. The difference in commands is that they did not use `--verbose  --emit-moves` when they ran basecall.
    Does my result look incorrect? Is this caused by version differences or other reasons? Thanks for your attention.
    The attachment contains the first 100 and last 100 lines of the basecall output log and the length distribution of polyA reads obtained by me (a) and the analyst (b). 
[slurm-21983.part.head.out.txt](https://github.com/nanoporetech/dorado/files/13985483/slurm-21983.part.head.out.txt)
[slurm-21983.part.tail.out.txt](https://github.com/nanoporetech/dorado/files/13985486/slurm-21983.part.tail.out.txt)
![a](https://github.com/nanoporetech/dorado/assets/103840889/ca638df6-4441-4194-be9f-d97c3a9c8fd7)
![b](https://github.com/nanoporetech/dorado/assets/103840889/25552f9a-0956-40af-a5af-35f0da6e5b3f)

**Comment by creaturemoon** [comment]
Hi,
    Thank you for the help and response. I will give it a try.

**Comment by tijyojwad** [comment]
Hi @creaturemoon - dorado v0.5.3 was just released which fixes this issue. You can download it from here - https://github.com/nanoporetech/dorado?tab=readme-ov-file#installation
