### ISSUE TITLE
error when basecalling

### ISSUE THREAD

**Issue by adenochemist** [nanoporetech/dorado#59]
Hello, 

when basecalling with dorado I get this error:
no kernel image is available for execution on the device 

I really do not know what to do, I've tried to compile it with no luck.
Ubuntu 22.04, 1050gtx ti

can you help me please,
thanks!

**Comment by iiSeymour** [comment]
Hello @adenochemist 

Unfortunately the 1050gtx ti is a Pascal GPU and below our minimum supported architecture https://github.com/nanoporetech/dorado#platforms.
