### ISSUE TITLE
CUDA device requested but no devices found and another question

### ISSUE THREAD

**Issue by sidi-yang** [nanoporetech/dorado#592]
Dear group,

I'm a beginner dealing with nanopore data and I have just successfully used the docker container (found here: https://hub.docker.com/u/zeunas) pod5tools to convert .fast5 files to .pod5 files on a hpc cluster using singularity. Then I want to use dorado as a basecaller.

- The first question is that I saw all the command lines in this GitHub website show the output is "> calls.bam", which says that the output of dorado from pod5 files is bam files. Just wondering why we don't produce .fastq files and go through QC steps here?

- The second question is that I came with an error when I tried to use the dorado container. And here is my command line:

`#$ -S /bin/bash`
`#$ -l tmem=6G`
`#$ -l h_vmem=6G`
`#$ -l h_rt=1000:00:00`
`#$ -l gpu=true`
`source  /share/apps/source_files/cuda/cuda-11.8.source`

`singularity exec --bind /path/to/my/folder:/mnt/path/to/dorado_v0.4.3.sif bash /mnt/path/dorado_v0.4.3.sh`

And in dorado_v0.4.3.sh:

`#$ -S /bin/bash`
`#$ -l tmem=6G`
`#$ -l h_vmem=6G`
`#$ -l h_rt=1000:00:00`
`#$ -l gpu=true`
`dorado basecaller /opt/dorado/bin/dna_r10.4.1_e8.2_260bps_hac@v4.1.0 /mnt/path/multi_fast5_zip_v3.pod5 > /mnt/path/call.bam`

However, I got the error:

`[2024-01-20 01:01:42.300] [info] > Creating basecall pipeline`
`[2024-01-20 01:01:42.350] [error] CUDA device requested but no devices found.`

And here is my nvidia-smi:

<img width="991" alt="Screenshot 2024-01-22 at 12 54 10" src="https://github.com/nanoporetech/dorado/assets/99621593/f89554c4-56ee-42d6-b485-7c391c1f5765">
<img width="990" alt="Screenshot 2024-01-22 at 12 54 36" src="https://github.com/nanoporetech/dorado/assets/99621593/d9223b49-a5b7-4ef7-9947-a13b49344786">

Just wondering could you please help me with the question and the error?

Thank you,
Sidi

**Comment by tijyojwad** [comment]
> just wondering why we don't produce .fastq files

Dorado can produce fastq files when the `--emit-fastq` option is added to the cmdline. However we recommend against that because the BAM records contain a lot of metadata which is lost with fastqs.

We don't own the docker container you referenced. So I won't be able to debug what's going on exactly. However, I would suggest attempting to run dorado outside of the docker container as well. If that doesn't work, I can help debug what's going on. 

P.S. How many GPUs does your job get? Re-using a suggestion from another post, you can try to add `-x cuda:0` to the cmdline to see if you're able to run with 1 GPU.

**Comment by sidi-yang** [comment]
Hi,

Thank you very much for your reply!

And I tried a new container for dorado from https://hub.docker.com/r/ontresearch/dorado/tags (I used the latest one).
However, I still got the same error:
`[2024-01-23 08:30:42.350] [error] CUDA device requested but no devices found.`

What I have done is that I produced 2 .sh files, the first is used to qsub the job, to go inside the container and run another .sh file (you can find these two .sh files in the first comment I wrote).

I guess the issue here is that the docker image cannot access the GPU. Docker requires an Nvida toolkit which allows the Docker image to access a GPU on the host machine. Without it, an application running inside the Docker container can request a GPU, but will not find any.

Just wondering do you think this is the problem and do you know how to solve this?

Thank you,
Sidi

**Comment by tijyojwad** [comment]
> I guess the issue here is that the docker image cannot access the GPU. Docker requires an Nvida toolkit which allows the Docker image to access a GPU on the host machine. 

yes this seems correct. Unfortunately docker and other infrastructure issues are out of scope for our repository. My recommendation would be to first get `nvidia-smi` working within your job. Once that's working, then try one of the CUDA samples and if those work, then moving on to dorado.

This is the official documentation for docker with NVIDIA GPUs that I've found helpful in the past - https://docs.nvidia.com/ai-enterprise/deployment-guide-vmware/0.1.0/docker.html

I'm closing this issue for now, but please feel free to re-open if you run into more dorado issues!
