### ISSUE TITLE
PolyA estimation and mapping

### ISSUE THREAD

**Issue by Franck-Dumetz** [nanoporetech/dorado#593]
Good morning,

I used dorado to estimate the length of the polyA tail in my dataset. At first, I only did the polyA estimation.
I could see the pt:i tag in the unmapped bam file.
So I tried to map at the same time using the following command line
`/usr/local/packages/dorado-0.5.1/bin/dorado basecaller --device cuda:all --estimate-poly-a --emit-sam  --reference PATH/TO/REF --min-qscore 7 /usr/local/packages/dorado-0.3.4/data/rna002_70bps_hac@v3 PATH/TO/POD5  > FILE.bam`
From that I get a mapped bam file but the pt:i tag is missing.
is it possible to do both at the same time? 
if yes, I missed the pt:i tag, any help to find it? 

thanks in advance,
Franck

**Comment by tijyojwad** [comment]
Hi @Franck-Dumetz - I verified locally that the `pi:i` tag is still there after alignment. However the position of the tags in the record may get updated. How are you fetching the tags from the record?

**Comment by Franck-Dumetz** [comment]
Oh I see, now the `pt:i` tag isn't in last position anymore. 
Just to make sure, it's always after the `RG:Z` tag? 
I just have to change my awk command to isolate the reads with PolyA info.
In my estimation, I have about 10% of polyA reads, I was expecting a bit more. Does that sound coherent with RNA002 chemistry? 

thanks again

**Comment by tijyojwad** [comment]
hi @Franck-Dumetz - there's no guarantee of the ordering of tags. The best approach would be to use an api like pysam to grab the right tag from the record.

10% seems a bit low, but then could also depend on your sample. if the tails are too short then dorado may not identify them. we can debug this further by

1. extacting some read ids without pt:i tags
2. putting those read ids into a file
3. passing that file to dorado as `--read-ids <file>`
4. running dorado again with poly a tail estimation and in verbose mode `-vv`

this will output the polyA detection details to `stderr`. you can route that to a log file and share it and I can have a look

**Comment by Franck-Dumetz** [comment]
I found a quick and dirty way to isolate the reads.
We are now looking at the data and we are wondering what Dorado considers being a polyA? 
When I look at the data it looks like the library prep captures everything that has 2 A and more which could explain why I only get 10% of reads that display a polyA tail

**Comment by tijyojwad** [comment]
Yeah 2As is too short - dorado needs a length of at least 8-10 to be confident about a tail

**Comment by tijyojwad** [comment]
Hi @Franck-Dumetz - does the previous answer help your situation? anything else we can help with?

**Comment by tijyojwad** [comment]
Hi @Franck-Dumetz - we discovered a big in dorado starting from version v0.5.1 where RNA polyA tails were being misclassified. We fixed this bug in a patch release v0.5.3 which was published yesterday - https://github.com/nanoporetech/dorado?tab=readme-ov-file#installation

I think this will improve the quality of your polyA estimates

**Comment by tijyojwad** [comment]
Hi @Franck-Dumetz - closing this ticket since we haven't heard back from you. Please re-open if you have more questions.
