### ISSUE TITLE
Adapter trimming

### ISSUE THREAD

**Issue by pawanchk** [nanoporetech/dorado#595]
Hi,

I have converted the fast5 files to pod5 for Nanopore DNA data using `pod5 convert fast5` tool and then I have used the `wf-basecalling` workflow (https://github.com/epi2me-labs/wf-basecalling) to do base calling, the workflow has used `Dorado` version `0.3.4+5f5cd02` for base calling and `Minimap2` version `2.26-r1175` for obtaining an aligned bam file as I provided the reference sequence while running the  `wf-basecalling` workflow.

I have these queries -
1. whether adapter trimming is done as part of the workflow by default or do I have to do additional steps for adapter trimming ?
2. can the aligned bam file obtained in this step be used for variant calling using `wf-human-variation` workflow ?

**Comment by tijyojwad** [comment]
Hi @pawanchk - this is a better question for the epi2me GitHub page - https://github.com/epi2me-labs/wf-basecalling/issues
