### ISSUE TITLE
Any quality control step?

### ISSUE THREAD

**Issue by sidi-yang** [nanoporetech/dorado#596]
Dear group,

I have already used dorado to do base calling and got a non-alignment .bam file. 

Just wondering do I need to do quality control step and how can I know the quality of my base call? And why dorado doesn't need QC? I'm afraid I'm thinking in a similar way when using Guppy and dealing with Illumina data so it would be really helpful if you could answer this question.

Thank you very much,
Sidi

**Comment by ymcki** [comment]
Well, there is a line in _basecalling.nf in the wf-human-variation pipeline that will spilt the aligned bam into two based on qaulity score and only uses the pass.cram for downstream variant calling analysis

    samtools bam2fq -@ ${params.ubam_bam2fq_threads} -T 1 ${reads} \
        | minimap2 -y -t ${params.ubam_map_threads} -ax map-ont ${mmi_reference} - \
        | samtools sort -@ ${params.ubam_sort_threads} \
        | samtools view -e '[qs] >= ${params.qscore_filter}' --output ${reads.baseName}.pass.cram --unoutput ${reads.baseName}.fail.cram -O CRAM --reference ${reference} -

My understanding is that this takes into the account of the observation that the distribution of read quality has two peaks in most ONT data. One at the high quality side and one at the low quality side. So it makes sense to split the data with a quality filter.

**Comment by HalfPhoton** [comment]
Hi @sidi-yang ,
Was your issue resolved by the recommendations from @ymcki? 

Kind regards,
Rich
