### ISSUE TITLE
 Failed to load metallib library

### ISSUE THREAD

**Issue by stephrom** [nanoporetech/dorado#597]
I'm trying to run dorado (version 0.5.2+7969fab3) on an apple M1-max, but I get the error that the metallib fails to load.
My macos version is : sonoma 14.2.1 (23C71)

[2024-01-25 14:35:47.926] [info] > Creating basecall pipeline
[2024-01-25 14:35:48.191] [error] Failed to load metallib library.

What can I do to get that fixed?

**Comment by tijyojwad** [comment]
this issue may help - https://github.com/nanoporetech/dorado/issues/533

**Comment by stephrom** [comment]
I seem to have solved the problem...

important is that I installed dorado using brew
' arch -arm64 brew install dorado '

then dorado gets installed in ' /opt/homebrew/Caskroom/dorado/0.5.2/dorado-0.5.2-osx-arm64 '
in which one will find the **bin** and **lib** subdirectories.
but the executable dorado is softlinked to ' /opt/homebrew/bin/dorado ' which is a path for executables and is from where it starts.
Now if dorado looks for default.metallib in <dorado exec path>/../lib/   it won't find the metallib file.

the solution was to create a softlink in /opt/homebrew/lib/default.metallib pointing to '/opt/homebrew/Caskroom/dorado/0.5.2/dorado-0.5.2-osx-arm64/lib/default.metallib '

**Comment by tijyojwad** [comment]
thanks for posting the solution! In general I would recommend using the pre-built dorado folder published on our GitHub. other installation mechanisms aren't officially supported by us
