### ISSUE TITLE
stereo duplex models not getting downloaded?

### ISSUE THREAD

**Issue by femiliani** [nanoporetech/dorado#60]
Very excited about all the progress with dorado, just tried basecalling and simplex works a charm, but I can't get the new stereo duplex to work. When I run it I get the following error:
```
[2022-12-14 11:15:29.512] [error] toml::parse: file open error -> /home/f002sd4/ont-dependencies/dorado/models/dna_r10.4.1_e8.2_400bps_sup@v4.0.0/dna_r10.4.2_e8.2_4khz_stereo@v1.0/config.toml
```

I do not get a the `dna_r10.4.2_e8.2_4khz_stereo@v1.0` directory when i download the model. And that appears to be true in all models if i try to download them all. 

Thanks again for all the work, can't wait until dorado officially replaces guppy!

**Comment by femiliani** [comment]
Apologies I didn't see that the download all actually does download a separate model altogether for duplex. 
For those of you looking for it it's `dna_r10.4.2_e8.2_4khz_stereo@v1.0` and not a subdirectory.

**Comment by iiSeymour** [comment]
Thanks @femiliani but please note that when duplex calling the stereo model gets applied after the simplex model automatically so it's actually the simplex model that you need to specify i.e.

```
$ dorado duplex dna_r10.4.1_e8.2_400bps_sup@v4.0.0 pod5s/ --pairs pairs.txt > duplex.sam
```
