### ISSUE TITLE
unknown simplex model rna004_130bps_sup@v3.0.1

### ISSUE THREAD

**Issue by wdecoster** [nanoporetech/dorado#609]
Hi,

Using dorado 0.5.1+a7fb3e3, I am trying some RNA004 basecalling with m6A modifications:

`../dorado basecaller --recursive rna004_130bps_sup@v3.0.1 $fast5dir --modified-bases m6A_DRACH > ${fast5dir/_fast5/.bam}`

But this results in:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown simplex model rna004_130bps_sup@v3.0.1
Aborted (core dumped)
```

Am I specifying the model incorrectly?

**Comment by HalfPhoton** [comment]
Hi @wdecoster,

Is `rna004_130bps_sup@v3.0.1` a model directory in your working directory or are you expecting this to automatically download?

If it's the latter, please simply specify the model speed (sup) 
```
dorado basecaller sup $fast5dir ... 
```

Kind regards,
Rich

**Comment by wdecoster** [comment]
I tried something similar, but that requires pod5 files, no? I can convert it if there is no other way.

**Comment by HalfPhoton** [comment]
Ah of course, yes it does require pod5 files - apologies for not picking up on that here. 

We do encourage pod5 files but this shouldn't be necessary here. 

Are there any pod5 files in this directory at all?

If there are any the model path you give here will be interpreted as a [model complex](https://github.com/nanoporetech/dorado?tab=readme-ov-file#automatic-model-selection-complex).

**Comment by HalfPhoton** [comment]
@wdecoster, I've tested locally on dorado-0.5.2 and can reproduce the bug.

To unblock your work, please download the m6A_DRACH model manually and use `--modified-bases-models <path>` instead of `--modified-bases`

```
../dorado download --model rna004_130bps_sup@v3.0.1_m6A_DRACH@v1
../dorado basecaller --recursive rna004_130bps_sup@v3.0.1 $fast5dir --modified-bases-models rna004_130bps_sup@v3.0.1_m6A_DRACH > ${fast5dir/_fast5/.bam}
```

We'll look into fixing this for the next release.

Kind regards,
Rich

**Comment by wdecoster** [comment]
Hi Rich,

Thanks for the quick follow-up. The command you suggest results in

```
[2024-02-01 19:33:00.446] [info] > Creating basecall pipeline
[2024-02-01 19:33:00.460] [error] toml::parse: file open error -> rna004_130bps_sup@v3.0.1/config.toml
```

That folder indeed doesn't exist. Attempting to solve that, I additionally download the model without modifications with
`../dorado download --model rna004_130bps_sup@v3.0.1`.

Rerunning dorado then returns another error:

```
[2024-02-01 19:35:34.958] [info] > Creating basecall pipeline
[2024-02-01 19:35:34.959] [error] filesystem error: cannot make canonical path: No such file or directory [rna004_130bps_sup@v3.0.1_m6A_DRACH]
```

Which I think I solved by changing your command to include the `@v1` part.

```
../dorado basecaller --recursive rna004_130bps_sup@v3.0.1 $fast5dir --modified-bases-models rna004_130bps_sup@v3.0.1_m6A_DRACH@v1 > ${fast5dir/_fast5/.bam}
```

Can you confirm that that command, with downloading the additional model, is still what I should for m6A modcalling?

By the way, I would have preferred pod5 (and could convert), but the PromethION, by default, generated fast5 for an RNA004 run, or so I've been told.

**Comment by HalfPhoton** [comment]
You'll get significantly better performance from pod5 yes. 

I think that command is what you wanted now that both models are downloaded and available locally.

I'll raise this fast5 output with RNA issue internally.

Best regards,
Rich

**Comment by wdecoster** [comment]
Thank you!
