### ISSUE TITLE
Poly(A) issue about RNA004

### ISSUE THREAD

**Issue by Yang990-sys** [nanoporetech/dorado#613]
Hello,

The same data and script show a significant difference in the number of polyA recognition between 0.4.3 and 0.5.2. Dorado 0.4.3 detected 99% polyA , while Dorado 0.5.2 only detected 20% of the total data, which is very similar to issue #588 . 

At the same time, I found that although Dorado's documentation mentioned RNA adapters are always trimmed, in the basecall result of 0.5.2, the adapters were not completely trimmed, which is different from the result of 0.4.3. Will this be the reason for the low detection rate in 0.5.2 ?  Which result should I use? 

0.5.2 reads:
![企业微信截图_17068453579782](https://github.com/nanoporetech/dorado/assets/54176741/97201915-1b8e-41f3-8de1-ebd52c8b74a8)
0.4.3 reads:
![企业微信截图_17068454516884](https://github.com/nanoporetech/dorado/assets/54176741/284eaa9d-9599-4cff-b691-641d195e7238)

0.5.2 polyA rate: 22%
![image](https://github.com/nanoporetech/dorado/assets/54176741/92a2bc9d-c055-4f5d-a9e1-e5917f9539e0)
0.4.3 polyA rate 99%
![image](https://github.com/nanoporetech/dorado/assets/54176741/e5919378-e813-4ce1-a4fb-ca9f527de7bd)

0.5.2 bascall scripts:
 ~/soft/dorado-0.5.2-linux-x64/bin/dorado basecaller -x cuda:3  --estimate-poly-a ~/soft/model/rna004_130bps_sup@v3.0.1 pod5_pass/ --modified-bases-models  ~/soft/model/rna004_130bps_sup@v3.0.1_m6A_DRACH@v1 >pass.bam
0.4.3 bascall scripts:
 ~/soft/dorado-0.4.3-linux-x64/bin/dorado basecaller -x cuda:3  --estimate-poly-a ~/soft/model/rna004_130bps_sup@v3.0.1 pod5_pass/ --modified-bases-models  ~/soft/model/rna004_130bps_sup@v3.0.1_m6A_DRACH@v1 >pass.bam

**Comment by tijyojwad** [comment]
Hi @Yang990-sys thank you for reporting this. Nothing should have changed between 0.5.2 and 0.4.3 for RNA. I will have a look at this tomorrow and get back to you. This clearly looks like a regression.

**Comment by tijyojwad** [comment]
Hi @Yang990-sys - I think I've found the bug. We have an issue with trimming. Can you run your new dataset with dorado v0.5.0? That shouldn't have the problem and will confirm my suspicion.

**Comment by Yang990-sys** [comment]
> Hi @Yang990-sys - I think I've found the bug. We have an issue with trimming. Can you run your new dataset with dorado v0.5.0? That shouldn't have the problem and will confirm my suspicion.

You're right. dorado v0.5.0 does not have this issue.

**Comment by tijyojwad** [comment]
Thank you for confirming! We're working on a patch fix and will release is in a couple of days.

**Comment by tijyojwad** [comment]
Hi @Yang990-sys - dorado v0.5.3 was just released which fixes this issue. You can download it from here - https://github.com/nanoporetech/dorado?tab=readme-ov-file#installation . Thank you for your patience!

**Comment by tijyojwad** [comment]
Hi @Papareddy - would you be able to call this dataset with dorado v0.5.0 as well? 0.5.3 should have fixed a regression we introduced but wondering if there's something more nuanced going on there - 

Here's where you can download those binaries -

 - [dorado-0.5.0-linux-x64](https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.5.0-linux-x64.tar.gz)
 - [dorado-0.5.0-linux-arm64](https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.5.0-linux-arm64.tar.gz)
 - [dorado-0.5.0-osx-arm64](https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.5.0-osx-arm64.zip)
 - [dorado-0.5.0-win64](https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.5.0-win64.zip)

**Comment by Papareddy** [comment]
Hi @tijyojwad  Thanks much for your fast response.

Showing sample -2 here and these result seemed to be the same with dorado 0.5. Low number of reads are called for Poly A tails. And the distribution looks the same as above.

The most parsimonious reason I am thinking of most of the reads are derived from ribosomal RNA (IGV for one of the most abundant rRNA loci attached) when I use total RNA as input. Some how I assume the protocol should eliminate non-Poly A RNA ?!  Could you please direct me to home I can direct this question.


Many Thanks 


Hi @tijyojwad,

Thanks again for your quick response!

I'm attaching information for sample -2, and, the results appear similar to the dorado 0.53. We're still seeing a low number of reads with poly(A) tails and a bimodal distribution like before (attached).

It appears ribosomal RNA (rRNA) derived reads are in substantial numbers . For reference, I've attached an IGV view showing one of the highly abundant rRNA loci. I was under the impression only poly A RNAs are enriched with oligo DT priming even when using total RNA in RNA004 kit.  While this could (perhaps) explain the low number of  poly A reads it doesn't explain the distribution!

Could you please give me you thoughts on this 

I appreciate your continued help!

Sincerely,

Ranj

rRNA locus
![Screenshot 2024-02-14 at 18 23 13](https://github.com/nanoporetech/dorado/assets/33577042/7ccfab15-f782-44e2-83ff-145d241f0c64)

Distribution
![Distribution](https://github.com/nanoporetech/dorado/assets/33577042/a6938ed1-b3da-4af7-9292-8057570b542f)

metrics 
![PolyA_dorado_0 5](https://github.com/nanoporetech/dorado/assets/33577042/5d35a22a-99e9-452f-baa0-4c97c30499d9)

![dorado0 5](https://github.com/nanoporetech/dorado/assets/33577042/ebbb642d-9eb7-45f1-a2cf-9de58ad5683b)

**Comment by tijyojwad** [comment]
Looking at the logs, it looks like dorado isn't calling 80% of the tails. This is much higher than what we'd expect (that number should be < 5% or so). 

Is only a portion of your data expected to have tails? Since you're seeing the same distribution across samples there might actually be a peak around 100. Would you be open to sharing a pod5 with a few samples from the ~100 population and the ~10 population?

**Comment by tijyojwad** [comment]
> While this could (perhaps) explain the low number of poly A reads it doesn't explain the distribution!

Yep I'm somewhat dubious of the first peak as well, and I suspect it may have something to do with our RNA adapter detection mechanism. We have made some improvements internally that we hope to release soon, and it's possible that first peak is already taken care of. If you are able to share a few reads that show up from the first peak, I can verify that

**Comment by Papareddy** [comment]
With the exception of ribosomal RNA, all of my messenger RNAs (mRNAs) are anticipated to possess poly A tails! I employed dorado recursively on a directory of pod5 files, and presently, I'm uncertain about which pod files contain reads with low poly A tail lengths. I will extract the reads based on these sizes and provide them to you. Thank you very much Joyjit  for your consistently prompt responses!

Cheers,
Ranj

**Comment by tijyojwad** [comment]
thanks @Papareddy - you can determine the pod5 name from the BAM record. Each record will have a `fn:Z` tag which has the name of the POD5 from which that read came. So if you can send me a few reads where `pt:i` tag < 20 that would be great.

**Comment by Yang990-sys** [comment]
> With the exception of ribosomal RNA, all of my messenger RNAs (mRNAs) are anticipated to possess poly A tails! I employed dorado recursively on a directory of pod5 files, and presently, I'm uncertain about which pod files contain reads with low poly A tail lengths. I will extract the reads based on these sizes and provide them to you. Thank you very much Joyjit for your consistently prompt responses!
> 
> Cheers, Ranj

Hello Ranj, 

I guess the difference may come from your sample itself. I am the company analyst in the issue #588. After reanalyzing the data using dorado v0.5.3, both the detection rate and length of polyA have been resolved. The following figure shows the distribution of polyA length after reanalysis, which is consistent with the results of dorado v0.4.3 in issue #588.

![image](https://github.com/nanoporetech/dorado/assets/54176741/2511b935-71ba-4d48-a118-432c868dc1fb)

**Comment by Yang990-sys** [comment]
And This is my trim code
![image](https://github.com/nanoporetech/dorado/assets/54176741/926e9fda-70f3-4de2-9557-873d5393a255)
