### ISSUE TITLE
current index error in move_table of version 0.5.2 

### ISSUE THREAD

**Issue by JeremyQuo** [nanoporetech/dorado#614]
# Issue Report

## current index error in move_table of version 0.5.2

We found an issue in that the signal length in the move table is different from the signal length in pod5.

We discussed it below,
https://github.com/hiruna72/squigualiser/issues/53

Here is my command,

`dorado basecaller dna_r9.4.1_e8_sup@v3.6/ basecall.pod5 --emit-moves >basecall.bam`

But in v4.3.0 the signal length is the same as in pod5.

My test data is R941 DNA, the read I tested is `0347e4bc-1f7d-4f04-8d89-3af903358f0f`
[sample.zip](https://github.com/nanoporetech/dorado/files/14160177/sample.zip)

**Comment by HalfPhoton** [comment]
Hi @JeremyQuo ,

Thanks for reporting this issue and providing example data! 
We've done some investigation and have found the cause of the issue. We'll apply a fix which should be available in the next release of dorado.

Kind regards,
Rich
