### ISSUE TITLE
CUDA OUT OF MEMORY (Dependent on # of GPUs)

### ISSUE THREAD

**Issue by ericmsmall** [nanoporetech/dorado#615]
# Issue Report

## Please describe the issue: CUDA OUT OF MEMORY pyTorch ERROR (Dependent on # of GPUs)

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*
pyTorch fails to allocate memory (even though memory is available in excess per nvidia-smi output) when initializing Dorado across more than 1 A4000 GPU. I would expect Dorado to be able to utilize the two GPUs in parallel without having to limit memory usage manually via batchsize.

## Steps to reproduce the issue:

When initializing Dorado with 2X GPUs either by allowing Dorado to automatically detect GPUs, or passing --device cuda:0,1 or passing pyTorch (CUDA_VISIBLE_DEVICES=0,1) pyTorch presents error "CUDA OUT OF MEMORY" occurs. However, if only one GPU is utilized the error does not occur (--device cuda:0 or --device cuda:1). Moreover, limiting batchsize (--batchsize 250) allows Dorado to run to completion. Finally, when we try to switch to the SUP model, we have not found a batchsize which will allow Dorado to run across the 2 GPUs. Note: A4000 GPUs have 16GB of RAM each.

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version: 0.5.2
- Cuda version: 12.3
   The paths to all libraries included with 0.5.2 are explicitly defined. 
- Dorado command: dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.3.0 pod5s/ -v  --modified-bases 6mA 5mC_5hmC --reference AssemblyScaffolds.fasta --kit-name SQK-NBD114-96 >calls.bam
- Operating system: RHEL 8
- Hardware (CPUs, Memory, GPUs): Intel Xeon Gold 36 core, 96GB RAM, 2X A4000 Nvidia GPUs
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location (on device or networked drive - NFS, etc.): local SSD
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): ~300GB
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset): 
I will followup with specific errors when my machine is brought back online.

Currently unavailable, will update when possible.

**Comment by HalfPhoton** [comment]
Hi @ericmsmall, thanks for the detailed report.

> When initializing Dorado with 2X GPUs...

Just to clarify - Does the error occur before basecalling starts i.e. during auto batch size selection?

We're continuously working on improving the auto batch size algorithm to get the best out of the hardware to deliver the best basecalling performance while being stable. I'll report your specific hardware configuration back to the team to see what we can do in a future release of Dorado.

The `-v` verbose output now shows much more information about the auto batch size calculation. This should help guide you to the optimal batch size for your hardware if you wish to experiment further around your known good `-b 250` value.

Kind regards,
Rich

**Comment by ericmsmall** [comment]
At first I thought that might be the case as well, but until dorado is started the GPUs are idle and no memory is being used.
Like this: 
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A4000               Off | 00000000:65:00.0 Off |                  Off |
|  0%   37C    P0               7W / 140W |      0MiB / 16376MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A4000               Off | 00000000:B3:00.0 Off |                  Off |
|  0%   39C    P0               8W / 140W |      0MiB / 16376MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**Comment by tijyojwad** [comment]
Hi @ericmsmall 

Can you try setting the following environment variable and see if it helps?
```
PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:25
```

**Comment by ericmsmall** [comment]
Apologies, I forgot that I had tried this based on other folks posts. Setting this as an environmental variable, or passing directly to pyTorch had no effect.

**Comment by tijyojwad** [comment]
Couple of more things to try to narrow down the issue -

1. Try without the mod bases to see if plain basecalling shows the same problem
2. Try one modbase at a time (instead of both 6mA and 5mC_5hmC
3. manually set the batch size to something smaller, like `-b 1536` or `-b 1792`
4. increase the `max_split_size_mb` to something larger, like 64/128

**Comment by HalfPhoton** [comment]
Closing as there's been no reply.
