### ISSUE TITLE
[error] Unknown flowcell_product_code:

### ISSUE THREAD

**Issue by peterthorpe5** [nanoporetech/dorado#618]
# Issue Report

## Please describe the issue:
[2024-02-08 10:11:41.916] [trace] POD5: /homes/pthorpe001/data/tail_prediction_testing/pod5_test/converted.pod5 flowcell_product_code: '' sequencing_kit: 'sqk-rna002' sample_rate: 3012
[2024-02-08 10:11:41.916] [error] Unknown flowcell_product_code:

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

I have created a small test dataset. this is my command:
~/apps/dorado-0.5.2-linux-x64/bin/dorado  basecaller  --estimate-poly-a  -vv hac@v3 ~/data/tail_prediction_testing/pod5_test/converted.pod5  > test2.bam

The kit would have been RNA002. It seems that the string in the POD5 does not contain the flow cell info ... can we pass it to the software in some way?

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version: dorado-0.5.2-linux-x64
- Dorado command: ~/apps/dorado-0.5.2-linux-x64/bin/dorado  basecaller  --estimate-poly-a  hac@v3 ~/data/tail_prediction_testing/pod5_test/converted.pod5  > test2.bam
- Operating system: Redhat 7 
- Hardware (CPUs, Memory, GPUs): 'NVIDIA A40
- Source data type : POD5
- Source data location (on device or networked drive - NFS, etc.):  networked drive - NFS 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB):  314M
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue): I can share the POD5 if needed. 

## Logs. No log file generated. 

[2024-02-08 09:26:59.368] [info] Estimation of poly-a has been requested, so adapter/primer trimming has been disabled.
[2024-02-08 09:26:59.369] [error] Unknown flowcell_product_code:

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset). 
[2024-02-08 10:11:41.914] [trace] 'hac' found variant: 'hac' and version: 'v3.0.0'
[2024-02-08 10:11:41.915] [info] Estimation of poly-a has been requested, so adapter/primer trimming has been disabled.
[2024-02-08 10:11:41.916] [trace] POD5: /homes/pthorpe001/data/tail_prediction_testing/pod5_test/converted.pod5 flowcell_product_code: '' sequencing_kit: 'sqk-rna002' sample_rate: 3012
[2024-02-08 10:11:41.916] [error] Unknown flowcell_product_code:

**According the lab they used:** Flow cell (R9.4.1) FLO-MIN106D

regards,

Pete

**Comment by HalfPhoton** [comment]
Hi @peterthorpe5 ,
Your pod5 file does not contain the required data (`flowcell_product_code`) to determine the sequencing conditions for automatic model selection.

```
POD5:  <file> flowcell_product_code: '' sequencing_kit: 'sqk-rna002' sample_rate: 3012
[2024-02-08 10:11:41.916] [error] Unknown flowcell_product_code: <blank>
```

Please manually download a the appropriate model `hac@v3  -> rna002_70bps_hac@v3`
```
dorado download --model rna002_70bps_hac@v3
```
and specify the model with a model path instead of the model complex

```
~/apps/dorado-0.5.2-linux-x64/bin/dorado basecaller --estimate-poly-a -vv rna002_70bps_hac@v3 ~/data/tail_prediction_testing/pod5_test/converted.pod5 > test2.bam
```

Kind regards,
Rich

**Comment by peterthorpe5** [comment]
Thank you for your reply Rich, I tried this before and got the following error:

[2024-02-08 11:06:03.315] [trace] Model option: 'rna002_70bps_hac@v3' unknown - assuming path
[2024-02-08 11:06:03.315] [info] Estimation of poly-a has been requested, so adapter/primer trimming has been disabled.
[2024-02-08 11:06:03.315] [info] > Creating basecall pipeline
[2024-02-08 11:06:06.413] [info]  - BAM format does not support `U`, so RNA output files will include `T` instead of `U` for all file types.
[2024-02-08 11:06:25.054] [error] PytorchStreamReader failed reading zip archive: failed finding central directory
Exception raised from valid at /pytorch/pyold/caffe2/serialize/inline_container.cc:178 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x2b6b704789b7 in /cluster/home/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x2b6b699fd115 in /cluster/home/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #2: caffe2::serialize::PyTorchStreamReader::valid(char const*, char const*) + 0x8e (0x2b6b6c49e2de in /cluster/home/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #3: caffe2::serialize::PyTorchStreamReader::init() + 0x9e (0x2b6b6c49e73e in /cluster/home/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #4: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x126 (0x2b6b6c4a1376 in /cluster/home/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #5: torch::jit::import_ir_module(std::shared_ptr<torch::jit::CompilationUnit>, std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&, bool, bool) + 0x2c0 (0x2b6b6d5ee090 in /cluster/home/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #6: torch::jit::import_ir_module(std::shared_ptr<torch::jit::CompilationUnit>, std::string const&, c10::optional<c10::Device>, bool) + 0x7f (0x2b6b6d5ee40f in /cluster/home/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #7: torch::jit::load(std::string const&, c10::optional<c10::Device>, bool) + 0xac (0x2b6b6d5ee4ec in /cluster/home/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #8: torch::serialize::InputArchive::load_from(std::string const&, c10::optional<c10::Device>) + 0x26 (0x2b6b6db70596 in /cluster/home/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #9: /homes/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/dorado() [0xa0ea1a]
frame #10: /homes/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/dorado() [0xa0c1ec]
frame #11: /homes/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/dorado() [0x9966ba]
frame #12: /homes/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/dorado() [0x9ac5ff]
frame #13: /homes/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/dorado() [0x9a86eb]
frame #14: /homes/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/dorado() [0x99e676]
frame #15: /homes/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/dorado() [0x83c3db]
frame #16: /homes/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/dorado() [0x83c18b]
frame #17: <unknown function> + 0x620b (0x2b6bd274420b in /lib64/libpthread.so.0)
frame #18: /homes/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/dorado() [0x83c93f]
frame #19: /homes/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/dorado() [0x83edb0]
frame #20: <unknown function> + 0x1196e380 (0x2b6b773ae380 in /cluster/home/pthorpe001/apps/dorado-0.5.2-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #21: <unknown function> + 0x7ea5 (0x2b6bd2745ea5 in /lib64/libpthread.so.0)
frame #22: clone + 0x6d (0x2b6bd39349fd in /lib64/libc.so.6)

New command:  ~/apps/dorado-0.5.2-linux-x64/bin/dorado  basecaller  -vv --estimate-poly-a  rna002_70bps_hac@v3 ~/data/tail_prediction_testing/pod5_test/converted.pod5  > test.bam

and what is in the directory:

                   dorado_test  pod5_test             **rna002_70bps_hac**@v3        rna004_130bps_hac@v3.0.1  rna004_130bps_sup@v3.0.1_m6A_DRACH@v1  tailfindr.sh
  rna002_70bps_fast@v3  rna004_130bps_fast@v3.0.1  rna004_130bps_sup@v3.0.1                              test2.bam

> ll -h ./rna002_70bps_hac@v3
total 22M
-rw-r----- 1 pthorpe001 barton 1.8K Feb  8 09:13 0.conv.bias.tensor
-rw-r----- 1 pthorpe001 barton 1.9K Feb  8 09:13 0.conv.weight.tensor
-rw-r----- 1 pthorpe001 barton 1.9K Feb  8 09:13 1.conv.bias.tensor
-rw-r----- 1 pthorpe001 barton 3.1K Feb  8 09:13 1.conv.weight.tensor
-rw-r----- 1 pthorpe001 barton 3.3K Feb  8 09:13 2.conv.bias.tensor
-rw-r----- 1 pthorpe001 barton 458K Feb  8 09:13 2.conv.weight.tensor
-rw-r----- 1 pthorpe001 barton 7.8K Feb  8 09:13 4.rnn.bias_hh_l0.tensor
-rw-r----- 1 pthorpe001 barton 7.8K Feb  8 09:13 4.rnn.bias_ih_l0.tensor
-rw-r----- 1 pthorpe001 barton 2.3M Feb  8 09:13 4.rnn.weight_hh_l0.tensor
-rw-r----- 1 pthorpe001 barton 2.3M Feb  8 09:13 4.rnn.weight_ih_l0.tensor
-rw-r----- 1 pthorpe001 barton 7.8K Feb  8 09:13 5.rnn.bias_hh_l0.tensor
-rw-r----- 1 pthorpe001 barton 7.8K Feb  8 09:13 5.rnn.bias_ih_l0.tensor
-rw-r----- 1 pthorpe001 barton 2.3M Feb  8 09:13 5.rnn.weight_hh_l0.tensor
-rw-r----- 1 pthorpe001 barton 2.0M Feb  8 09:13 5.rnn.weight_ih_l0.tensor
-rw-r----- 1 pthorpe001 barton 7.8K Feb  8 09:13 6.rnn.bias_hh_l0.tensor
-rw-r----- 1 pthorpe001 barton 7.8K Feb  8 09:13 6.rnn.bias_ih_l0.tensor
-rw-r----- 1 pthorpe001 barton 2.3M Feb  8 09:13 6.rnn.weight_hh_l0.tensor
-rw-r----- 1 pthorpe001 barton 2.3M Feb  8 09:13 6.rnn.weight_ih_l0.tensor
-rw-r----- 1 pthorpe001 barton 7.8K Feb  8 09:13 7.rnn.bias_hh_l0.tensor
-rw-r----- 1 pthorpe001 barton 7.8K Feb  8 09:13 7.rnn.bias_ih_l0.tensor
-rw-r----- 1 pthorpe001 barton 512K Feb  8 09:13 7.rnn.weight_hh_l0.tensor
-rw-r----- 1 pthorpe001 barton 2.3M Feb  8 09:13 7.rnn.weight_ih_l0.tensor
-rw-r----- 1 pthorpe001 barton 7.8K Feb  8 09:13 8.rnn.bias_hh_l0.tensor
-rw-r----- 1 pthorpe001 barton 7.8K Feb  8 09:13 8.rnn.bias_ih_l0.tensor
-rw-r----- 1 pthorpe001 barton 2.3M Feb  8 09:13 8.rnn.weight_hh_l0.tensor
-rw-r----- 1 pthorpe001 barton 2.3M Feb  8 09:13 8.rnn.weight_ih_l0.tensor
-rw-r----- 1 pthorpe001 barton 5.8K Feb  8 09:13 9.linear.bias.tensor
-rw-r----- 1 pthorpe001 barton 512K Feb  8 09:13 9.linear.weight.tensor
-rw-r----- 1 pthorpe001 barton  411 Feb  8 09:13 config.toml

Do you understand why this is not working?

regards,

Pete

**Comment by HalfPhoton** [comment]
Hi @peterthorpe5,

Your download appears to have failed somehow - maybe you've run out of disk space.

```
total 22M 25M
 Yours Mine
 1.8K  1.8K 0.conv.bias.tensor
 1.9K  1.9K 0.conv.weight.tensor
 1.9K  1.9K 1.conv.bias.tensor
 3.1K  3.1K 1.conv.weight.tensor
 3.3K  3.3K 2.conv.bias.tensor
 458K  458K 2.conv.weight.tensor
 7.8K  7.8K 4.rnn.bias_hh_l0.tensor
 7.8K  7.8K 4.rnn.bias_ih_l0.tensor
 2.3M  2.3M 4.rnn.weight_hh_l0.tensor
 2.3M  2.3M 4.rnn.weight_ih_l0.tensor
 7.8K  7.8K 5.rnn.bias_hh_l0.tensor
 7.8K  7.8K 5.rnn.bias_ih_l0.tensor
 2.3M  2.3M 5.rnn.weight_hh_l0.tensor
 2.0M  2.3M 5.rnn.weight_ih_l0.tensor << missing data
 7.8K  7.8K 6.rnn.bias_hh_l0.tensor
 7.8K  7.8K 6.rnn.bias_ih_l0.tensor
 2.3M  2.3M 6.rnn.weight_hh_l0.tensor
 2.3M  2.3M 6.rnn.weight_ih_l0.tensor
 7.8K  7.8K 7.rnn.bias_hh_l0.tensor
 7.8K  7.8K 7.rnn.bias_ih_l0.tensor
 512K  2.3M 7.rnn.weight_hh_l0.tensor << missing data
 2.3M  2.3M 7.rnn.weight_ih_l0.tensor
 7.8K  7.8K 8.rnn.bias_hh_l0.tensor
 7.8K  7.8K 8.rnn.bias_ih_l0.tensor
 2.3M  2.3M 8.rnn.weight_hh_l0.tensor
 2.3M  2.3M 8.rnn.weight_ih_l0.tensor
 5.8K  5.8K 9.linear.bias.tensor
 512K  1.6M 9.linear.weight.tensor << missing data
```

Can you try again please?

Kind regards,
Rich

**Comment by peterthorpe5** [comment]
Thank you so much for looking. I will try again.

**Comment by peterthorpe5** [comment]
that worked thank you (although I have issues with the download Proxy server etc ... I downloaded it to another cluster and pulled over). wget doesnt worked for me as your zip files always seems to be broken?...:
> unzip rna002_70bps_hac@v3.zip
Archive:  rna002_70bps_hac@v3.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of rna002_70bps_hac@v3.zip or
        rna002_70bps_hac@v3.zip.zip, and cannot find rna002_70bps_hac@v3.zip.ZIP, period.

**Comment by HalfPhoton** [comment]
Hi @peterthorpe5,
I'm glad that you've got it working again.

So that we can look into this issue further can you explain how you're trying to download these files with wget?

Does this work for you?
```
curl -L https://cdn.oxfordnanoportal.com/software/analysis/dorado/rna002_70bps_hac@v3.zip -o rna002_70bps_hac@v3.zip
unzip rna002_70bps_hac@v3.zip
```

Cheers,
Rich

**Comment by peterthorpe5** [comment]
yes that worked!! Weird. Thank you.

**Comment by HalfPhoton** [comment]
Ok, great! Looks like it was just some weirdness with the download.

Have a great day,
Rich
