### ISSUE TITLE
dorado modified bases basecalling for Minion SQK-LSK109 run

### ISSUE THREAD

**Issue by avilella** [nanoporetech/dorado#623]
# Issue Report

## Please describe the issue:

Running dorado for basecalling including modified bases delivers MM and ML tags, but all MM tags have a '?', e.g. C+h? and C+m?

## Steps to reproduce the issue:
Basecalling with dorado, converting to fastq preserving the tags during minimap2 alignment, then exploring the resulting bam file:
```
dorado basecaller hac,5mCG_5hmCG pod5/ > file.bam
samtools_1_16 fastq -T '*' file.bam | minimap2 -y ... > aligned.bam
samtools view aligned.bam
```
Reading the SAM specification, I was expecting not to see the '?' marks, as `When the ‘?’ flag is present the tag ‘C+m?,5,12,0;’ tells us the modification status of the first five
cytosine bases is unknown`.

## Run environment:
- Dorado version: 0.5.1+a7fb3e3
- Dorado command: `dorado basecaller hac,5mCG_5hmCG pod5/ > file.bam`
- Operating system: Ubuntu 22.04.3 LTS
- Hardware (CPUs, Memory, GPUs): 13th Gen Intel(R) Core(TM) i9-13900K / 125Gi / NVIDIA RTX A6000
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location (on device or networked drive - NFS, etc.): scratch partition ext4
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): FLO-MIN106, FAX56325, SQK-LSK109, 72hrs, MinKNOW 23.11.7
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by tijyojwad** [comment]
Hi @avilella - I checked with the mods team and this is currently expected. A couple of follow ups to try -

1. can you run alignment with `dorado aligner` just to rule out any modbase tags being lost in the pipe (unlikely but just to verify)
2. is your data short read? there might not be a CG contexts there for the model to pick up, so maybe try the all context model as well?

**Comment by malton-ont** [comment]
@avilella - the modification model you are running (`5mCG_5hmCG`) is selecting only `CG` contexts. This means dorado doesn't attempt to analyse any `C` bases that aren't immediately followed by a `G`. So in your example (`C+m?,5`) means that the first 5 `C` bases were not analysed and therefore we have no information on their modification state.
