### ISSUE TITLE
Basecalling and demultiplexing using custom barcodes 

### ISSUE THREAD

**Issue by bxm19** [nanoporetech/dorado#626]
Hi, 
I am currently trying to basecall and demultiplex my reads which were sequenced using custom barcodes. So far I have tried a lot of different options for basecalling and demultiplexing using Dorado, but most of my reads (99%) always end up as unclassified. When I check these reads myself I can find the barcodes back perfectly fine. Could you please have a look at my toml file and scoring options to hopefully give a solution to make it work? For the scoring options I have tried a lot of different scorings, but they don't seem to change anything.

I use Dorado version 0.5.2 on linux, using pod5 files as input.

Below my toml file:

```
[arrangement]
name = "Primer_tagged_custom_BC"
kit = "Primer_tagged_custom_BC" 

mask1_front = ""
mask1_rear = ""
mask2_front = ""
mask2_rear = ""

# Barcode sequences
barcode1_pattern = "Primer_tagged_fwBC%02i"
barcode2_pattern = "Primer_tagged_revBC%02i"
first_index = 1
last_index = 96

## Scoring options
[scoring]
min_soft_barcode_threshold = 0.3
min_hard_barcode_threshold = 0.2
min_barcode_score_dist = 0.1
```
The command I use for basecalling:
`./dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.3.0 /home/Sequencing_runs/2024/Seq1/Raw_data/ -r --barcode-sequences /home/Dorado_test/Sequence_files/Sequence_file_1_96.fa --barcode-arrangement /home/Dorado_test/Dorado_arrangement_files/Dorado_arrangement_file_barcode_01_96.toml --min-qscore 10 > /home/Sequencing_runs/2024/Seq1/Basecalled.bam`

After that I run demux:
`./dorado demux /home/Sequencing_runs/2024/Seq1/Basecalled.bam --no-classify --emit-fastq --output-dir /home/Sequencing_runs/2024/Seq1/Demux/`

I have tried a lot of different flags and settings; with and without trim, barcode both ends, just basecalling and using the toml file and fasta file while performing the demultiplexing, different scorings. But no matter what I change in the order or flags it doesn't drastically change the amount of unclassified reads.

----------------------------------------------------------------------
I also have some other questions:
1) We are using 13 bases for our barcodes, which have the same sequence attached to the forward and reversed primer. Do I need to specify this in my fasta file? Or can I just name the barcode only once because Dorado will automatically look for the reverse complement sequence? See an example below of two barcodes being used for fw and rev primer:
```
>Primer_tagged_fwBC01
ATCCGGTCGGAGA
>Primer_tagged_revBC01
TCTCCGACCGGAT
>Primer_tagged_fwBC02
CTGAGGTGATCAG
>Primer_tagged_revBC02
CTGATCACCTCAG
```
2) How are the scoring options exactly calculated for the toml file? If there is a 3 out of 13 nucleotides difference between two barcodes, is the min_barcode_score_dist that I could use then 0.23?

3) How to calculate and use the barcode and flank scores if I only have a barcode of 13 bases used in my experiment? The explanation on github: "Dorado calculates a separate score for the barcode flanks and the barcode sequence itself. The score is roughly 1.0f - edit_distance / length(target_seq), where the target_seq is either the reference flank or reference barcode sequence." So this means if I accept 1 mistake out of 13 bases in the barcode sequence it's: 1 - 0.0769 = 0.92. But since the standard scores of Nanopore are much lower (see below), I feel like I'm not understanding how to calculate these scores. Could this be further clarified? 
```
min_soft_barcode_threshold = 0.2
min_hard_barcode_threshold = 0.2
min_soft_flank_threshold = 0.3
min_hard_flank_threshold = 0.3
```

4) Is the trim function not working in Dorado version 0.5.2? 

---------------------------------------------------------------------------

I would really appreciate comments or suggestions to help me get this to work and also answers to my above questions. Thank you in advance.

**Comment by tijyojwad** [comment]
Hi @bxm19 - Dorado needs the flank sequences of the barcodes to detect the barcode location. In your config you have 
```
mask1_front = ""
mask1_rear = ""
mask2_front = ""
mask2_rear = ""
```
these need to be added. We will add some error checking in dorado which will ensure that barcode flanks can't be empty.

Your understanding of the scores is correct. If you only accept 1 error, then 0.92 should be your threshold.

Dorado will automatically use the reverse complements of the barcodes. if you have different front and rear barcodes, then you need to specify different barcode patterns for each. If the same barcode (just reverse complemented) occurs on both ends, use the same pattern.

**Comment by bxm19** [comment]
Hi @tijyojwad thank you for your reply.
Maybe it's stupid, but to me it is not clear what I should fill in at these masks. Could that be part of my primer that the barcode is attached to? Could you elaborate on that? Also since in the description of Dorado "can be an empty string" is mentioned (even at mask 1 which also says required (a bit confusing)), it was not clear to me that it should be filled.
![image](https://github.com/nanoporetech/dorado/assets/160014905/3ed5d25c-3057-4ea3-9de0-897a3f8b05dd)

**Comment by tijyojwad** [comment]
yep that's poor and confusing documentation on our end, sorry about that. I'm fixing it now and we'll push an update soon. The mask_1* is required and can't be empty (I believe one of them can be, but providing both will give best results).

Is your barcode sequence starting right after the primer? or is there any other filler in between the primer and barcode? the `mask_1_front` and `mask_2_rear` are what immediately precede/succeed the actual barcode sequence

**Comment by dmgr90** [comment]
Hi! 
Thank you for the very useful discussion! 

So, if I am using symmetrical tags directly attached to the primer what should be written in mask_1_front and mask_2_rear? The F and R primer sequences themselves? 

Thank you very much for the help.

**Comment by bxm19** [comment]
Hi @tijyojwad I have tried putting my forward primer as mask_1_front and my reversed primer as mask_2_rear as you said, but it should actually be filled at mask_1_rear and mask_2_rear.
It's also mentioned in the custom barcodes description the way it worked for me, so that's documented right (https://github.com/nanoporetech/dorado/blob/release-v0.5.3/documentation/CustomBarcodes.md):
`5' ---- ADAPTER/PRIMER ---- LEADING_FLANK_1 ---- BARCODE_1 ---- TRAILING_FLANK_1 --- READ --- RC(TRAILING_FLANK_2) --- RC(BARCODE_2) --- RC(LEADING_FLANK_2) --- 3'`

Dorado is now working for our custom barcodes, thanks for the help. After basecalling and demux I only noticed some reads are still attached and not split into 2 (or more) reads. Automatically read splitting should be done by Dorado, right? When I look at some of the reads that are attached to each other they do all have the primers and also the same barcode at both ends of the read, so then I would expect it to be split and put in the right barcode file. Is that still being further worked on to improve?

**Comment by bxm19** [comment]
Hi @dmgr90 you should fill in your forward primer at mask_1_rear and your reversed primer to mask_2_rear, like I mentioned above. 
Concerning the adapter trimming, I used `--no-trim` in my command for Dorado basecalling so nothing would be trimmed. I used the toml and fasta file for the custom barcodes during basecalling, so the reads are classified into their barcode groups during basecalling already. You don't have to fill in the adapter sequences in the toml file (at least I didn't do that and that worked for me). 
When I used the Dorado demux command, I mentioned the `--no-classify` and `--no-trim-primers` (so only adapters would be trimmed) since I don't need these in my sequences anymore. I don't trim my primers, because later during the processing of my sequencing data I will remove my primers and with that also my barcodes. I guess you could fill in `--trim all` if you want to remove them already. Just letting you know how I ran Dorado and how it worked for me, hopefully it can be of any help to you as well.

**Comment by tijyojwad** [comment]
Yes dorado should be doing read splitting - if it's missing some obvious cases perhaps we can improve our algorithm. Can you share a sample pod5 with a read that should be split but isn't?

Also, in general we recommend using `--no-trim` during basecalling if the intention is to demux later. This ensures that we maintain the best barcode performance, as trimming adapters can sometimes overtrim sequences a bit and result in lost barcode information.

**Comment by tijyojwad** [comment]
Hi @bxm19 - closing this ticket for now since I haven't heard back. If you're able to share a pod5 file with the unspilt reads we can take a look.

**Comment by Jia-Xiu** [comment]
[Issues of demultiplexing using custom barcodes.docx](https://github.com/nanoporetech/dorado/files/15093816/Issues.of.demultiplexing.using.custom.barcodes.docx)

**Comment by tijyojwad** [comment]
Hi @Jia-Xiu - right now dorado only support unique barcodes on either end. Repeated barcodes will result unclassified reads. However this feature is becoming increasingly important and asked for often so we're planning to add support for it.

**Comment by Jia-Xiu** [comment]
> Hi @Jia-Xiu - right now dorado only support unique barcodes on either end. Repeated barcodes will result unclassified reads. However this feature is becoming increasingly important and asked for often so we're planning to add support for it.

Hi @tijyojwad Thanks for your reply. I am looking forward to seeing when the support is added.

**Comment by willros** [comment]
@Jia-Xiu 

Hi,

I encountered the same problem with dual barcodes and had to come up with a solution.

I made this small package:
https://github.com/willros/nanomux

Which adress the problem. 
You can choose between matching barcodes greedy or fuzzy. Greedy is much faster than fuzzy, but requires the barcode to be exactly the same as they are specified. 

Hope that it can help while you are waiting!

Regards,
William

**Comment by Jia-Xiu** [comment]
> @Jia-Xiu
> 
> Hi,
> 
> I encountered the same problem with dual barcodes and had to come up with a solution.
> 
> I made this small package: https://github.com/willros/nanomux
> 
> Which adress the problem. You can choose between matching barcodes greedy or fuzzy. Greedy is much faster than fuzzy, but requires the barcode to be exactly the same as they are specified.
> 
> Hope that it can help while you are waiting!
> 
> Regards, William
Hi @willros, thanks for the package! I'm happy to try it out.
Best,
Xiu

**Comment by Jia-Xiu** [comment]
Hi @willros, thanks for the package! I'm happy to try it out.
Best,
Xiu
> @Jia-Xiu
> 
> Hi,
> 
> I encountered the same problem with dual barcodes and had to come up with a solution.
> 
> I made this small package: https://github.com/willros/nanomux
> 
> Which adress the problem. You can choose between matching barcodes greedy or fuzzy. Greedy is much faster than fuzzy, but requires the barcode to be exactly the same as they are specified.
> 
> Hope that it can help while you are waiting!
> 
> Regards, William

**Comment by willros** [comment]
@Jia-Xiu, let me know if you encounter any problem and let me know how it works out for you!

Thanks,
William
