### ISSUE TITLE
how important is subsetting by channel to duplex mode

### ISSUE THREAD

**Issue by wilsonte-umich** [nanoporetech/dorado#627]
I understand the logic of the new instructions to subset reads by channel when applying duplex mode to batches of POD5 files, as I do.  However, as I queried on the pod5 repo, subsetting is slow to point of being impractical.

My question here: how important is it?  I might have thought most duplexes passed through pores close together in time, so that processing similarly timed files (as they are output during a run), might get you most of the way there?  This is certainly true comparing POD5 files from early and late in a run assuming the flow cell was reloaded. Any insight how often true duplexes are detected where strands are widely separated in time?

Thanks for any insight, trying to understand how critical subsetting is given that it is proving computationally (at least in wall time) very expensive.

**Comment by HalfPhoton** [comment]
Hi @wilsonte-umich,

As described in the readme - we suggest subsetting pod5s by channel to improve duplex basecalling performance especially when working over networked file storage. 
> Duplex basecalling is an IO-intensive process and can perform poorly if using networked storage or HDD. This can generally be improved by splitting up POD5 files appropriately.

It sounds like your in a difficult situation with limited access to higher performance local drives from your pod5 issue https://github.com/nanoporetech/pod5-file-format/issues/112. 

As performance is dependent on your specific system might I suggest that you experiment on a selection of your data ~ 500 pod5 files - and see if the pod5 subset -> duplex basecall is faster than direct duplex basecalling?

Kind regards,
Rich

**Comment by wilsonte-umich** [comment]
I commented in the pod5 issue about resolving the subset task.

Can you inform my question here about they dynamics of duplex read acquisition over time?  The reason to subset by channel prior to batch processing by `duplex` would be to ensure that the all potential duplex read pairs are in the same batch of files, correct? In other words, batching confers the dorado performance boost (which I can verify), but adds the requirement for batching by channel - IF it is true that duplex read pairs can end up anywhere in a set of time-series MinKnow files...

**Comment by HalfPhoton** [comment]
Hi @wilsonte-umich, 
I believe that the pairing algorithm makes no assertions as to the order of the reads in a dataset as there's no guarantee that files or records in a file are sorted by time. Files directly from Minknow are more likely to be ordered (and this may be guaranteed) but another user could supply any data in any order. 

Kind regards,
Rich

**Comment by wilsonte-umich** [comment]
Thanks, not quite what I'm asking.  I wouldn't expect dorado itself to have expectations about POD5 file ordering (but files generated by MinKnow during a run are a time series - info a user might invoke when making calls to dorado).

I'm asking if anyone at ONT has done a post-hoc analysis of duplex recovery during flowcell runs. After duplex calling has been done, one could use read ids to go back to POD5 timestamps to calculate the time differential between the two sequencing events that led to duplex calls. Any data like that? How far in time can they be? I would find it interesting (although as I'll post soon on the other thread, I've solved the underlying workflow problem).

**Comment by wilsonte-umich** [comment]
I just posted code details at <https://github.com/nanoporetech/pod5-file-format/issues/112>, so am closing this issue, but would still love to hear any insight on the temporal dynamics of duplex read sequencing above. Thanks!
