### ISSUE TITLE
Info regarding tail prediction method please

### ISSUE THREAD

**Issue by peterthorpe5** [nanoporetech/dorado#628]
Dear Dorado,

Thank you for your recent help. I now have tail prediction runing. 

**Question**(s): Does the method for tail prediction differ from Nanopolish, is it a new approach, altered or the same algorithm? 

regards,

Pete

**Comment by tijyojwad** [comment]
Hi @peterthorpe5 - it's a different implementation than Nanopolish and I don't think it's using the same algorithm (I haven't looked into nanopolish code though)

**Comment by peterthorpe5** [comment]
Thank you for your reply. Would it be possible to describe how Dorado works out the poly A length? (adding this to the docs would also be great).

**Comment by smaegol** [comment]
HI @peterthorpe5 

Dorado's approach is definitely different than Nanopolish (unfortunately, cause I find their solution for poly(A) really great), It's similar to tailfindr. 

Some info can be found in the comments in the source code: [here](https://github.com/nanoporetech/dorado/blob/d9af343c0097e0e60503231e036d69e6eda2f19a/dorado/read_pipeline/PolyACalculator.cpp#L31), [here](https://github.com/nanoporetech/dorado/blob/d9af343c0097e0e60503231e036d69e6eda2f19a/dorado/read_pipeline/PolyACalculator.cpp#L207C1-L213C13) or [here](https://github.com/nanoporetech/dorado/blob/d9af343c0097e0e60503231e036d69e6eda2f19a/dorado/read_pipeline/PolyACalculator.cpp#L323C14-L327C50)
