### ISSUE TITLE
Low demultiplexing yield for duplex

### ISSUE THREAD

**Issue by olawa** [nanoporetech/dorado#629]
Hi,

duplex calling has no --no-trim option but despite this demux works well for simplex reads. Many duplex reads ends up in unclassified even though template reads are classified correctly. Are adaptors trimmed only by the stereo pipeline or is this due to poor overlap at ends? In any case, it would be great if demux could handle this and use the barcode info from template reads, and of course only output one read per sequenced molecule as the default option.

**Comment by tijyojwad** [comment]
Here's an example of how a read is sequenced -

```
Template:                 ADAPTER ---       READ    ---
Complement:           ADAPTER ---  RC(READ) ---
```

During duplex this is the overlap that will be found
```
Template:                 ADAPTER ---  READ  ---
RC(Complement):                     ---  READ  --- RC(ADAPTER) ---
```

So the adapter/primer/barcode regions will not overlap and get trimmed.

> it would be great if demux could handle this and use the barcode info from template reads

yes we intend to add this support into dorado in a future release

**Comment by tijyojwad** [comment]
closing because duplex barcoding as a feature request is being tracked separately
