### ISSUE TITLE
Basecalling on GPU doesn't start

### ISSUE THREAD

**Issue by gaberoo** [nanoporetech/dorado#632]
# Issue Report

## Please describe the issue:

Basecalling on the GPU does not go beyond the `Creating basecall pipeline` step:

```
$ ~/Software/dorado-0.5.3-linux-x64/bin/dorado basecaller sup converted.pod5 --kit-name SQK-RAB204 -vv > calls.bam
[2024-02-16 13:28:59.489] [trace] 'sup' found variant: 'sup' and version: 'latest'
[2024-02-16 13:28:59.490] [trace] POD5: converted.pod5 flowcell_product_code: 'FLO-FLG001' sequencing_kit: 'sqk-rab204' sample_rate: 4000
[2024-02-16 13:28:59.490] [trace] Searching for: chemistry: dna_r9.4.1_e8, model_variant: sup
[2024-02-16 13:28:59.490] [trace] Reject dna_r9.4.1_e8_fast@v3.4 on model type: sup
[2024-02-16 13:28:59.490] [trace] Reject dna_r9.4.1_e8_hac@v3.3 on model type: sup
[2024-02-16 13:28:59.490] [trace] Found 2 model matches:
[2024-02-16 13:28:59.490] [trace] - dna_r9.4.1_e8_sup@v3.3
[2024-02-16 13:28:59.490] [trace] - dna_r9.4.1_e8_sup@v3.6
[2024-02-16 13:28:59.491] [info]  - downloading dna_r9.4.1_e8_sup@v3.6 with httplib
[2024-02-16 13:29:01.972] [info] > Creating basecall pipeline
```

The process seems to be correctly started on the GPU, but nothing happens.

```
$ nvidia-smi
Fri Feb 16 13:30:18 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 ...    On  | 00000000:0B:00.0  On |                  N/A |
| 23%   64C    P0              80W / 250W |     13MiB /  8192MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      7404      C   ...e/dorado-0.5.3-linux-x64/bin/dorado       10MiB |
+---------------------------------------------------------------------------------------+
```

Running on the CPU easily passes beyond that step:

```
$ ~/Software/dorado-0.5.3-linux-x64/bin/dorado basecaller sup converted.pod5 --kit-name SQK-RAB204 -v -x cpu > calls.bam
[2024-02-16 13:31:43.290] [info]  - downloading dna_r9.4.1_e8_sup@v3.6 with httplib
[2024-02-16 13:31:45.760] [info] > Creating basecall pipeline
[2024-02-16 13:31:45.761] [debug] - CPU calling: set batch size to 128, num_cpu_runners to 1
[2024-02-16 13:31:45.963] [debug] Creating barcoding info for kit: SQK-RAB204
[2024-02-16 13:31:45.963] [info] Barcode for SQK-RAB204
[2024-02-16 13:31:45.974] [debug] Load reads from file converted.pod5
[2024-02-16 13:34:21.133] [debug] > Kits to evaluate: 1
[                              ] 0% [00m:00s<00m:00s]
```

Currently, I have the nvidia 545 driver installed, but I've also tried downgrading to 535 or 470 with no effect. I have CUDA 11.8 installed (also tried with 11.7).

Interestingly, the same thing happens with `guppy_basecaller`.

## Run environment:
- Dorado version: 0.5.3
- Dorado command: dorado basecaller sup converted.pod5 --kit-name SQK-RAB204
- Operating system: Ubuntu 22.04 (also occurred on 20.04, I tried to distupgrade to see if that would help)
- Hardware (CPUs, Memory, GPUs): AMD Ryzen 7 3800X 8-Core, 32GB RAM, NVIDIA GeForce RTX 2080 8GB
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5 (also happens with fast5)
- Source data location (on device or networked drive - NFS, etc.): on device
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): flongle, RAB204, 50M reads
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by HalfPhoton** [comment]
Hi @gaberoo,
Does the same happen on `fast` or `hac` models?

Kind regards,
Rich

**Comment by gaberoo** [comment]
Hi Rich,
Yes, I tried the other models too, same problem. I can run the fast model on the CPU to completion though.

**Comment by HalfPhoton** [comment]
@gaberoo, do you have progress with the sup model without barcoding?

**Comment by gaberoo** [comment]
Hi @HalfPhoton,
Unfortunately I do not, but right now I think this might be a driver and/or hardware issue with the GPU. I tried a PyTorch example script and this also doesn't run.
So I'm chasing that lead for now and will close this issue. But if the problem comes back, then I might reopen. Thanks for the fast feedback and help.
