### ISSUE TITLE
Bam index failure after dorado aligner

### ISSUE THREAD

**Issue by marija-kra** [nanoporetech/dorado#633]
Hello,

I ran modified basecalling using dorado, then aligned it using dorado aligner, with the intention to then analyse it using modkit. However, dorado aligner seems to have produced a bam file that I cannot index using samtools (so modkit does not accept it). I'm wondering if I'm missing something / doing something wrong. Also, only about half of the reads appear to align to the reference, whereas we would have exptected much closer to 100%.

Data: R9.4.1, LSK110, GridION, converted to pod5 using pod5 tool
Dorado version: 0.5.3 Linux x64
Samtools version: 1.19.2
System: HPCC based on Centos

Examples of what I ran:

dorado basecaller sup@v3.3,5mCG_5hmCG --emit-moves pod5/ > output.bam
samtools index output.bam
dorado aligner reference.fasta output.bam  > aligned.bam

log for dorado align:
>[2024-02-16 16:28:30.848] [info] > loading index reference.fasta
>[2024-02-16 16:28:31.801] [info] > starting alignment
>[2024-02-16 20:16:30.371] [info] > Simplex reads basecalled: 2884000
>[2024-02-16 20:16:30.374] [info] > finished alignment
>[2024-02-16 20:16:30.374] [info] > total/primary/unmapped 3386944/1199244/1697382

and then when I try to run samtools index on the aligned file, I get:

>[E::hts_idx_push] NO_COOR reads not in a single block at the end 21 -1
>[E::sam_index] Read '03e24fd0-459a-43b4-b048-18fca18c464f' with ref_name='Chr.22', ref_length=716602, flags=0, >pos=143410 cannot be indexed
>samtools index: failed to create index for "aligned.bam"

And if I try running modkit pileup on it, it complains about the lack of index file of course:
> Error! unable to open SAM/BAM/CRAM index for aligned.bam; please create an index

Any suggestions would be appreciated, thanks!

Marija

**Comment by HalfPhoton** [comment]
Hi @marija-kra, 
The samtools index tool requires a sorted bam input ([docs](https://www.htslib.org/doc/samtools-index.html)). Have you sorted the aligned.bam first? 

Kind regards,
Rich

**Comment by marija-kra** [comment]
Gosh, you are correct. Thank you, @HalfPhoton!

**Comment by HalfPhoton** [comment]
No problem, happy basecalling @marija-kra

**Comment by JefferFoo** [comment]
```shell
samtools index NEMO_output/dorado_NEMO_mod_calls.bam
[E::hts_idx_push] NO_COOR reads not in a single block at the end 0 -1
[E::sam_index] Read '018a0a65-e96c-4157-8e03-5fbcac40b5c6' with ref_name='MT', ref_length=16299, flags=16, pos=9313 cannot be indexed
samtools index: failed to create index for "NEMO_output/dorado_NEMO_mod_calls.bam": No such file or directory
```
I use a model named NEMO to basecall it by dorado. But when I try to index it by samtools. It just tells me that it can't build index for it. How this happened? Whether it was caused structure of bam file?

**Comment by mpodio81** [comment]
Hi,
Im having the same problem. The samtools index: failed to create index for "aligned.bam". I did the sort with SAMtools but still the index can not be created. How could it be resolved? Thank you
