### ISSUE TITLE
Read tags from dorado are inconsistent with signal length in pod5 file

### ISSUE THREAD

**Issue by patbohn** [nanoporetech/dorado#635]
When basecalling RNA002 data with dorado 0.5.3 (hac model), the ns (number of samples), and sp (start of subread in parent read signal) tags do not fit the expected range of values as defined by the num_samples property of the read in the pod5 file. I confirmed that the num_samples parameter is indeed the same length as the actual signal in the pod5 file. 

Specifically, with non-split reads, ns tag is almost always larger than the num_samples property of the read in the pod5 file. 

In addition, with split reads, the value of the sp tag of the second split read can be smaller than the ns tag value of the first read, suggesting overlap of signal? 

Finally, when adding the value of the sp tag and ns tag of the last split read, the resulting signal position is larger than the num_samples parameter of the parent read in the corresponding pod5 file. 

If this is not a bug, how are the ns and sp tags actually determined, and (how) can they be mapped to the actual raw signal?

**Comment by patbohn** [comment]
To help evaluating this issue I'm uploading a subset of the dorado 0.5.3 basecalling output and corresponding pod5 files (same dataset as in my other issue about reassigned read_ids https://github.com/nanoporetech/dorado/issues/636). 

Here is a bar chart of the issue, where one can see that the ns tag of reads becomes larger than num_samples of the (parent) read_id when trimming is applied (note that this is independent of whether the read_id changed or not, and that this comparison of ns tag with length of parent read id is not informative for reads that have been split): 

![image](https://github.com/nanoporetech/dorado/assets/62295512/b5ef2b1d-e634-467b-8db9-77c0c29a6ee4)

And here is the bar chart where I calculated the proposed signal end position of the parent read by adding the ns tag to the sp tag, and comparing that to the actual num_samples of the parent read in the pod5 file: 

![image](https://github.com/nanoporetech/dorado/assets/62295512/66834230-680f-4d84-8237-91e2ecc7bb7f)

[subsampled_data.zip](https://github.com/nanoporetech/dorado/files/14363434/subsampled_data.zip)

(Of note, I am working on this to develop a tool that splits reads in the pod5 file according to how dorado has split them during basecalling - as far as I am aware there is no tool that can do this currently, or?)

**Comment by patbohn** [comment]
Update: Looking through the dorado source code, I found some math that could potentially explain this observation: 

https://github.com/nanoporetech/dorado/blob/d9af343c0097e0e60503231e036d69e6eda2f19a/dorado/read_pipeline/ReadPipeline.cpp#L51 

Here the trimmed samples are added to the length of the raw signal. I noticed that when running RNA basecalling with the poly-a-estimate option enabled (which I did), the trimming detection does still run, i.e. the ts tag is not always 0. I suspect that the raw data is not actually trimmed though, and so when calculating the ns tag the ts value is inadvertently added.

**Comment by patbohn** [comment]
Another update: Assuming that the above hypothesis is correct, the correct value of ns should just be ns-ts (since the trimming is not actually applied to raw_data_samples). When I do this calculation, ns-ts is <= num_samples of pod5, and those reads where it is smaller than num_samples have had their read_id changed, so were trimmed by the pore detection algorithm. 

![image](https://github.com/nanoporetech/dorado/assets/62295512/1a8a7a5a-090d-4709-b81f-b95f42ce596f)

Thus I suppose when supplying the --no-trim / --estimate-poly-a option, either trimming should be disabled completely (e.g. num_trimmed_samples should always be 0), or there should be a check in ReadPipeline to ignore num_trimmed_samples when the option is set. The latter option might be helpful with debugging or post-run trimming.

**Comment by skovaka** [comment]
This also caused problems in Uncalled4, which uses these tags to guide signal alignment (https://github.com/skovaka/uncalled4/issues/4). I added a temporary optional workaround to set ts=0, which appears to correct the issue. Thank you @patbohn, that would have taken me forever to figure out!

**Comment by tijyojwad** [comment]
Hi @patbohn - a fix for this has been released with v0.6.0
