### ISSUE TITLE
A large number of reads get re-assigned a different read_id, even though they are single childs

### ISSUE THREAD

**Issue by patbohn** [nanoporetech/dorado#636]
When performing basecalling of direct RNA sequencing data (Kit 2) with dorado 0.5.3, reads will be split automatically. This will lead to re-assigned read_id's for around 50% of reads. Of these re-assigned read_id reads, a large number (~50%) do not have a second child, meaning they are not actually split into two reads. All of those have a start signal (sp) tag of 0. 

This is an issue when attempting to perform read-level signal analysis, i.e. when attempting to combine basecalled sequence with raw signal. 

Is this a bug or working as intented, e.g. are these single child reads with re-assigned read_id's substantially different from their parent reads, even though they all start at sample position 0?

**Comment by malton-ont** [comment]
Hi @patbohn,

It's certainly possible for reads to be "split" into a single subread but, especially for RNA, I would expect that this would involve discarding some early samples of the read, which should lead to the split point tag being > 0. Would it be possible for you to isolate a few reads that show this characteristic? We can then investigate further and determine what is happening here.

Many thanks,
Steve

**Comment by patbohn** [comment]
Hi Steve, 

of course! I took a subset of 40 parent read ids of which 22 had their read id replaced, where 8 are single childs. All of the single childs have a ts of >0, but an sp of 0. However, also the majority of reads where the read_id didn't change have a ts>0 (see bar chart below). 

![image](https://github.com/nanoporetech/dorado/assets/62295512/1b3049e4-4396-4cee-a334-b11101232953)

I have uploaded a zip file with the corresponding pod5 file, dorado basecalling output of all child reads coming from the selected parent read ids, and a csv file of parsed pi, ns, ts, sp tags for easier plotting. Hope this helps identifying what is going on! 

Best wishes, 
Patrick

[subsampled_data.zip](https://github.com/nanoporetech/dorado/files/14363386/subsampled_data.zip)

**Comment by malton-ont** [comment]
Hi @patbohn,

Thanks for the data, very useful! There do look to be a couple of things happening here, but I _think_ the single-split reads themselves are working as intended.

The first thing that usually happens in RNA is that we attempt to find and trim the adapter signal. This gives the `ts` value - 0 means we didn't trim it at all.

After basecalling, the RNA splitter looks for regions of open-pore signal and discards them. In your case many of these reads have open-pore at the end of the signal but no secondary read signal afterwards, so the splitter simply discards that section of the read. As the split point indicates the start of the split read (in the trimmed signal) this is set to 0, and the number of samples reported (`ns`) is reduced. We then update the read-id to indicate that we've made changes to the original data.

I may ask @snurk to comment as well, in case I've missed anything here.

**Comment by patbohn** [comment]
Hi Steve, 

ah great, that does explain it! I can confirm now that all reads with changed id are trimmed on the right side while those that aren't trimmed are not (by comparing the value of ns-ts to the length of the parent_id - regarding the value of ns itself, I have opened a second issue that I mentioned above). 

So essentially, to update the pod5 file to match the basecaller output for these reads I just need to update the read_id and trim off the signal > ns?

**Comment by malton-ont** [comment]
Yes, I believe so.

**Comment by patbohn** [comment]
Thank you for clearing up my confusion!
