### ISSUE TITLE
Barcode Q-score Tag in demultiplexed bams

### ISSUE THREAD

**Issue by teodorabu** [nanoporetech/dorado#643]
Hi Dorado Team,

I was wondering if it would be possible to add information about the quality of barcode when demultiplexing, more specific to add the quality of the barcode for each demultiplexed bam file. It would be useful to be able to assess the quality of the barcode itself along with the read quality when analysing the results.

Thanks!

**Comment by HalfPhoton** [comment]
Hi @teodorabu, We're are discussing this change internally. 

This feature is also linked with this feature request: https://github.com/nanoporetech/dorado/issues/639

Kind regards,
Rich

**Comment by teodorabu** [comment]
Thanks!

**Comment by tijyojwad** [comment]
Hi @teodorabu we don't plan to add this feature right now. But if things change we will update you.
