### ISSUE TITLE
modified basecalling on cluster: cannot download models with curl/httplib

### ISSUE THREAD

**Issue by teodorabu** [nanoporetech/dorado#645]
Dear Dorado team,

I am attempting to run basecalling with --modified-bases option on a pod5 dataset. I am running dorado on the cluster using the following command, where the $model points to the folder containing dna_r10.4.1_e8.2_400bps_sup@v4.3.0 and input to $pod5. 

$dorado_version basecaller $model $input --modified-bases 5mCG_5hmCG  > $output_bam

This results in dorado output:
[2024-02-21 11:56:02.691] [info] Assuming cert location is /etc/ssl/certs/ca-bundle.crt
[2024-02-21 11:56:02.724] [info]  - downloading dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1 with httplib
[2024-02-21 11:57:22.997] [error] Failed to download dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1: Could not establish connection
curl: (7) Failed to connect to 2600:9000:2250:a800:1d:5478:3f00:93a1: Network is unreachable
[2024-02-21 12:02:01.429] [error] Failed to download dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1: ret=1792, errno=0

I have had this problem before, when doing unmethylated basecalling, and I resolved it by downloading the models locally and then moving them to the cluster and pointing dorado to the specific model folder. I have downloaded from dorado the model dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1 in the hope that I can circumvent the downloading problem again, however dorado fails to notice that the model is already provided (in the same dir where my bash script for running dorado is) and still proceeds with the downloading step.

I would be very thankful for any advice on this matter!
Cheers,
Teodora

**Comment by HalfPhoton** [comment]
Hi @teodorabu,
If you already have the mods model downloaded you can specify a path to it using `--modified-bases-models` which takes a path instead of `--modified-bases` which performs the download.

Kind regards,
Rich

**Comment by teodorabu** [comment]
Thanks for the prompt response, this fixed the issue!
