### ISSUE TITLE
T instead of U

### ISSUE THREAD

**Issue by mocherry** [nanoporetech/dorado#646]
Dear all,

when doing modified RNA base calling with Dorado (m6A) it says that neither BAM nor fastq supports modified bases. Does this matter in downstream analyses, e.g. when using eventalign and nanopolish in Galaxy? Is there a file format or modification of the command line which reports Us?

Thanks and best,
Matthias

**Comment by HalfPhoton** [comment]
@mocherry, is your issue resolved?
