### ISSUE TITLE
Preserving the order of reads when using demux

### ISSUE THREAD

**Issue by Shians** [nanoporetech/dorado#647]
Using dorado 0.5.2, I find that when I use demux on a fully sorted file, the outputs are not guaranteed to also be sorted. The frustrating thing is that they also appear to be *almost* sorted, with just a single stray read causing `samtools index` to fail.

It feels to me like there shouldn't be a big reason why input order and output order can't be made consistent, thus preserving sorted properties of input files.

**Comment by tijyojwad** [comment]
Hi @Shians - there's now a `--sort-bam` feature in dorado demux which outputs sorted BAMs if the input is sorted. Note that this only works if the `--no-trim` option is used since trimming changes the reads which then invalidates the alignments.
