### ISSUE TITLE
Request: example dataset for RNA-004

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/dorado#649]
I'm not sure if this is the right place to ask, since I couldn't find a proper epi2me github page to post this (it didn't have a "new issue" button) -- it would be great if the epi2me labs page had more example datasets on top of regular genomic WGS. In particular, things like example data for RNA004. Where is the proper place to ask for this?

**Comment by HalfPhoton** [comment]
Hi @billytcl,
Sorry to have taken so long to reply. 
This request is probably best asked on the nanopore community where they might have datasets prepared.
Best regards,
Rich
