### ISSUE TITLE
Chunk size

### ISSUE THREAD

**Issue by itslittman** [nanoporetech/dorado#65]
Is a bigger chunk size always going to result in faster performance? I’m using the RNA SUP model, if it makes a difference.

**Comment by incoherentian** [comment]
I'm having trouble determining levels of similarity to guppy, but if dorado is anything like it RE:chunk size, don't lower it! You may as well run a lower-compute, lower-accuracy model at that point.
If DCGM or nvidia-smi etc. indicate you have poorly saturated VRAM, you could try to speed things up with more chunks per runner. I wouldn't tinker with that subset of settings other than that.

**Comment by itslittman** [comment]
@incoherentian does processor make a difference? I’m using Apple M1 Max.

**Comment by incoherentian** [comment]
> @incoherentian does processor make a difference? I’m using Apple M1 Max.

I'd expect parameters which impact a model's output quality, like lowering chunk size, to have a negative impact on quality irrespective of what silicon is providing the compute.

I don't have a direct link to hand but it should be pretty easy to locate info on "don't edit chunk size" from either the ONT community or some of Miles Benton's older (but still largely relevant) work.

**Comment by itslittman** [comment]
@incoherentian okay interesting, I assumed chunk size just denoted how much of the raw data would be read into memory at once. I raised the chunk size from the default on my last basecalling run, is that bad?

Noah

**Comment by zwets** [comment]
There's an explanation in the "Guppy Protocol" document. It is usually linked from the release updates published on the community site.
