### ISSUE TITLE
basecall model for R10.4 flowcell

### ISSUE THREAD

**Issue by sahoo-rk** [nanoporetech/dorado#650]
Hello team:
While running a basecall with 'Dorado', (```dorado basecaller hac,5mCG ./pod5_dir/ -v --reference $assembly > mod_basecalled.bam```) the error file reads as follows.

```
 No supported chemistry for Flowcell:'FLO-PRO112', Kit:'SQK-LSK112' and Sampling Rate:4000
 Could not resolve chemistry from data
```

Which model is appropriate for this data? Please suggest.

**Comment by ymcki** [comment]
As far as I know, I think ONT made the decision not to generate dorado models for experimental flowcells like R9.5, R10.3, R10.4. You better try guppy instead of dorado.
