### ISSUE TITLE
After basecalling using dorado and getting .bam file per barcode, the downstream analysis (QC, assembly) always failed.

### ISSUE THREAD

**Issue by JWang52md** [nanoporetech/dorado#651]
firstly, I run dorado basecaller:    ./dorado basecaller sup /rsrch5/home/hlth_prof/jwang52/pod5_test/ --kit-name SQK-RBK114-24 > calls.bam
Then, I run dorado demux:     ./dorado demux --output-dir /rsrch5/home/hlth_prof/jwang52/pod5_2023/output_basecalled --no-classify calls.bam
I got the .bam file per barcode with file size about 1G per barcode.  (please see the attachment)
<img width="868" alt="doradobasecalled" src="https://github.com/nanoporetech/dorado/assets/153654375/641564ff-2fc6-4845-9cbc-954e07918902">

However, when I do the nanoplot or do canu assembly, it always failed. Are there something wrong with basecalling progress?

**Comment by sklages** [comment]
How did you run nanoplot and canu? Which error messages do you get?

**Comment by JWang52md** [comment]
Thank your sklages, I rerun the basecalling and demux, maybe because of I wrongly used the GPU instead of CPU during demux process, after that, it works. I can do the downstream analysis. Thank you again.!
