### ISSUE TITLE
Discrepancy between MinKNOW and dorado

### ISSUE THREAD

**Issue by tnn111** [nanoporetech/dorado#652]
I sequenced 48 isolates using kit SQK-RBK114-96. At first, I used basecalling on the PromethION device (P24; Joint Genome institute) and all looked good. However, it was version 4.12 of the model and I wanted to see if I could do better using 4.3. Also, I wanted methylation which I didn't ask for in the first place.

All looked good until I realized that when using dorado standalone, I got only a tiny fraction of the total reads demultiplexed. Most ended up in the unclassified bucket.

Am I missing something obvious here?

Thanks, Torben

**Comment by tijyojwad** [comment]
Hi @tnn111 - as @HalfPhoton can you post the cmd you ran and the version of dorado used?

Also, was demultiplexing and barcode trimming enabled in MinKNOW? Can you check the experiment logs?

**Comment by tijyojwad** [comment]
@tnn111 do you have any updates?
