### ISSUE TITLE
Error with demultiplexed bam file with modified bases

### ISSUE THREAD

**Issue by teodorabu** [nanoporetech/dorado#656]
Hello,

I am encountering a problem with my current dataset.  I am basecalling my pod5 files with the following command:
$dorado_version basecaller $model $input --modified-bases-models $mod_model  > $output_bam

where dorado_version is 0.5.2, the model is dna_r10.4.1_e8.2_400bps_sup@v4.3.0 and mod_model is dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mC_5hmC@v1

After I get my output_bam file, I am demultiplexing it using:
$dorado_version demux --kit-name $kitname --output-dir $demux_dir $output_bam, where I specify the kit and output directory. 

However, once the demultiplexing step is completed (successfully), I cannot align my barcoded bams to the reference (using dorado aligner), as I get the following error:
[2024-02-28 18:19:02.255] [info] > loading index ref_methyl.fna
[2024-02-28 18:19:02.309] [info] > starting alignment
terminate called after throwing an instance of 'std::runtime_error'
  what():  MN tag and sequence length are not in sync.

This error appears for all the demultiplexed bam files.
I hope you can let me know if anything can be done here.

Thanks for your help!

**Comment by malton-ont** [comment]
Hi @teodorabu. This looks to be the same issue as https://github.com/nanoporetech/dorado/issues/631. A fix has been implemented for the next release.

**Comment by teodorabu** [comment]
thanks for letting me know!

**Comment by tijyojwad** [comment]
Hi @teodorabu - this is now fixed in the v0.6.0 release.
