### ISSUE TITLE
c10::Error on simplex basecalling

### ISSUE THREAD

**Issue by cocvincent** [nanoporetech/dorado#658]
Hello,

I am currently experiencing a problem with simplex basecalling.

I'm trying to basecall with the dna_r10.4.1_e8.2_400bps_sup@v4.3.0 model.

![fonction_erreur_29-02-24](https://github.com/nanoporetech/dorado/assets/161732564/3edde52e-9358-41d4-a866-dd3ecf112d90)

After 23 hours of processing, I get the error c10::error

![Code_erreur_29-02-24](https://github.com/nanoporetech/dorado/assets/161732564/732ecbfc-e1bc-488b-8b55-56b0e5cad922)

I also have a "bam" file in my output folder, but I'm not sure it's complete.

I'm using 100G of memory with A100/V100 GPU on a computing cluster.

I hope you can help me, thanks.

**Comment by cocvincent** [comment]
Hello, 
thank you for your reply.

I'm sure I'm using 100g of RAM. I could see that this threshold had been exceeded.
![qstat-fx-29-02-24](https://github.com/nanoporetech/dorado/assets/161732564/411c40d8-09b1-49c9-a7f9-1b8c8e53dc35)

I tried with 160g of RAM (the maximum I can allocate). Same problem.
![qstat-fx-01-03-24](https://github.com/nanoporetech/dorado/assets/161732564/f9dcb36e-6826-4311-9bdc-bb1c00293d48)
![Code_erreur_01-03-24](https://github.com/nanoporetech/dorado/assets/161732564/d92f3a30-002b-4f9c-89a2-93d69678b64e)

I'm currently testing without multiplexing, waiting for the results.

Is it possible to reduce the amount of RAM used by Dorado knowing that Guppy doesn't encounter this type of problem?

Thanks.

**Comment by cocvincent** [comment]
Hello,
I had the same problem without multiplexing
![qstat-fx-04-03-24](https://github.com/nanoporetech/dorado/assets/161732564/0787e341-d72b-4786-952a-dc34ffc8ba55)
![Code_erreur_04-03-24](https://github.com/nanoporetech/dorado/assets/161732564/612184b5-7f4c-415b-8e2e-c8f798805a05)

**Comment by cocvincent** [comment]
Hello,

The basecalling worked surprisingly well by splitting the dataset (pod5 list) in 2 parts to reduce the memory.

Thanks you for your help.

**Comment by HalfPhoton** [comment]
Thanks for the update @cocvincent. I'll close this ticket as resolved and we'll continue to work on improving stability of Dorado
