### ISSUE TITLE
Setting q-score thresholds in dorado?

### ISSUE THREAD

**Issue by incoherentian** [nanoporetech/dorado#66]
Hello Dorado Team,

I'd like to know how to specify a minimum quality score threshold for "passed" (vs "failed") basecalling in dorado. I've had no success asking on the ONT forums, so asking here despite this not really being a discussion forum.

BR,
Ian

Background: 

First, I don't know where dorado points to for the equivalent of guppy's .cfg files. Normally I would adjust the q-score threshold there by editing the "min_qscore" parameter e.g. 
`min_qscore                          = 9.0`

The closest candidates I could find were the config.toml files (which contained no min_qscore) when downloading either of these:

```
dorado download --model dna_r9.4.1_e8_hac@v3.3
dorado download --model dna_r9.4.1_e8_fast@v3.4
```

For the SUP model the presumed config.toml seems to go somewhere else. (e.g. dna_r9.4.1_e8_hac@v3.3 creates new files and folders including [...]/dorado-0.1.1/dna_r9.4.1_e8_hac@v3.3/config.toml, whereas dna_r9.4.1_e8_sup@v3.3 has no [...]/dorado-0.1.1/dna_r9.4.1_e8_sup@v3.3/config.toml.) In case this is relevant to min_qscore thresholds, where does the config.toml for dna_r9.4.1_e8_sup@v3.3 go?

Since I couldn't find the "min_qscore"-containing equivalent of guppy's .cfg files, I also had a go at checking if dorado carried over guppy's command-line "--min_qscore" parameter. This, unsurprisingly, failed as an unknown argument:

```
[user@node ~]$ dorado basecaller dna_r9.4.1_e8_sup@v3.3 --min_qscore 9 --emit-fastq --device cuda:all /scratch/c.medib/FAS49654/barcode60 >/scratch/c.medib/FAS49654/dorado011out/barcode60_Q9/barcode60_Q9.fastq
[2022-12-21 16:13:32.570] [error] Unknown argument: --min_qscore
Usage: dorado [-h] [--device VAR] [--max-reads VAR] [--batchsize VAR] [--chunksize VAR] [--overlap VAR] [--num_runners VAR] [--modified-bases VAR...] [--modified-bases-models VAR] [--emit-fastq] [--emit-moves] model data

Positional arguments:
  model                         the basecaller model to run.
  data                          the data directory.

Optional arguments:
  -h, --help                    shows help message and exits
  -v, --version                 prints version information and exits
  -v, --verbose
  -x, --device                  device string in format "cuda:0,...,N", "cuda:all", "metal" etc.. [default: "cuda:all"]
  -n, --max-reads               [default: 0]
  -b, --batchsize               if 0 an optimal batchsize will be selected [default: 0]
  -c, --chunksize               [default: 10000]
  -o, --overlap                 [default: 500]
  -r, --num_runners             [default: 2]
  --modified-bases              [nargs: 1 or more]
  --modified-bases-models       a comma separated list of modified base models [default: ""]
  --emit-fastq
  --emit-moves

[user@node ~]$
```
Is there a correct one?

Thanks for any help!

**Comment by incoherentian** [comment]
I managed to find prior guidance (https://github.com/nanoporetech/dorado/issues/53) which helped me resolve the following uncertainty:

> ```
> dorado download --model dna_r9.4.1_e8_hac@v3.3
> dorado download --model dna_r9.4.1_e8_fast@v3.4
> ```
> 
> 
>     
>   
> 
> For the SUP model the presumed config.toml seems to go somewhere else. (e.g. dna_r9.4.1_e8_hac@v3.3 creates new files and folders including [...]/dorado-0.1.1/dna_r9.4.1_e8_hac@v3.3/config.toml, whereas dna_r9.4.1_e8_sup@v3.3 has no [...]/dorado-0.1.1/dna_r9.4.1_e8_sup@v3.3/config.toml.) In case this is relevant to min_qscore thresholds, where does the config.toml for dna_r9.4.1_e8_sup@v3.3 go?

So the model is downloaded to whatever your current directory is when using `dorado download --model [model]`

When your current directory does not contain the downloaded model files, is there a less clunky way to access models than specifying the full path of downloaded models? e.g. is there a folder proximal to /dorado-n.n.n/bin/ which dorado can fall back to when specifying a model (sans path)?

**Comment by incoherentian** [comment]
> I couldn't find the "min_qscore"-containing equivalent of guppy's .cfg files

Given the lack of any feedback here, I'm concluding the long term intent is leaving q-score thresholds out to encourage use of better downstream tools like filtlong or nanofilt. Which is fine!

**Comment by iiSeymour** [comment]
qscore filtering on the writer node should be a smaller patch - I can look at sorting this next week.

**Comment by iiSeymour** [comment]
https://github.com/nanoporetech/dorado/commit/a8ec89510b3f7208e43d41757bc3b025eb28e0b3 adds qscore filtering:

```
$ dorado basecaller --min-qscore 10 dna_r10.4.1_e8.2_260bps_hac@v4.0.0 pod5s/ > calls.sam
```

**Comment by cjw85** [comment]
@incoherentian,

I'm sure @iiSeymour and team are working on it, but if you want a way to get both pass and fail a la Guppy you can do something like:

```
THREAD=4
QFILTER=10
OUTPUT=reads
dorado ... \
        | samtools bam2fq -@ ${THREADS} -T 1 \
        | tee >(samtools view -e '[qs] < ${QFILTER}}' -o ${OUTPUT}.fail.bam - ) \
        | samtools view -e '[qs] >= ${QFILTER}' -o ${OUTPUT}.pass.bam -
```

which is not pretty, but does the job without resorting to writing any code. If you want you can get fancy and pipe into minimap2 before samtools to do alignments first.

**Comment by isabelluo** [comment]
@cjw85 
but if I would like to emit fastq file directly I suppose I could not pipe into samtools view any more correct? so how can I filter the qscore and assign fail and pass folders if I would like the output format to be fastq?

**Comment by cjw85** [comment]
You would need additional pipes to convert each of the filtered BAM streams to fastq.

**Comment by incoherentian** [comment]
Just noticed this was added per [b2af21b40b511cd77b90b171c78a7433026310ff](https://github.com/nanoporetech/dorado/blob/master/CHANGELOG.md#030-18-may-2023) so closing.

**Comment by andzandz11** [comment]
Is this mean or median q score?
I could not find a link to a manual on the GitHub page.

If I use the sup 10.4 model and Q20 filter almost all of my reads get filtered.
[2023-07-22 17:40:35.219] [info] > Reads basecalled: 639
[2023-07-22 17:40:35.219] [info] > Reads filtered: 32804

**Comment by tijyojwad** [comment]
This is the mean qscore of the bases in the read

**Comment by ymcki** [comment]
> This is the mean qscore of the bases in the read

Are you sure it is a mean qscore? If so, how is it calculated?
I average the sum of phred score by length but the avg_qscore calculated this way is only roughly correlates with qs.

Here is an example

qs      total_phred_score length avg_qscore
14      673204  24006   28.04
16      747982  19887   37.61
17      809222  24118   33.55
17      914390  27282   33.52
18      1060805 28601   37.09
18      245858  7611    32.30
18      301402  8816    34.19
18      573643  17575   32.64
19      1081587 30959   34.94
19      1350858 37969   35.58
19      818301  21477   38.10
19      822968  24613   33.44
19      865576  24782   34.93
19      976378  25128   38.86
19      985435  26799   36.77
20      1010951 27173   37.20
20      1028469 26292   39.12
20      1028866 26720   38.51
20      1118711 30606   36.55
20      1191329 33105   35.99
20      1407808 36545   38.52
20      1787579 47143   37.92
20      572837  14568   39.32
20      582987  15060   38.71
20      674585  17994   37.49
20      847515  23113   36.67
20      985850  25433   38.76
20      989441  26672   37.10
21      1110519 29029   38.26
21      1160528 30425   38.14
21      1207665 31070   38.87
21      1738120 45365   38.31
21      343426  9439    36.38
21      608295  15488   39.28
21      658123  17558   37.48
21      827579  21499   38.49
21      935153  24598   38.02
21      986467  26603   37.08
22      1092451 27112   40.29
22      1142422 29308   38.98
22      1195771 29927   39.96
22      1309646 33707   38.85
22      1463129 37167   39.37
22      554092  14184   39.06
22      556131  13703   40.58
22      778742  20446   38.09
22      801589  21050   38.08
22      869698  23040   37.75
22      903726  23803   37.97
22      904072  22622   39.96
22      960127  25266   38.00
22      960744  24532   39.16
23      1014058 26659   38.04
23      1075007 28209   38.11
23      1084694 27690   39.17
23      1108523 27495   40.32
23      1152335 28741   40.09
23      1152355 29276   39.36
23      474476  11719   40.49
23      600852  15499   38.77
23      842573  21545   39.11
23      858990  21446   40.05
24      1032162 26015   39.68
24      1065771 26677   39.95
24      1172461 29473   39.78
24      1216479 30344   40.09
24      1255045 30750   40.81
24      1379580 36687   37.60
24      1447939 35439   40.86
24      662229  18457   35.88
24      853042  21791   39.15
24      903815  22653   39.90
24      970656  24526   39.58
24      978442  23969   40.82
24      984330  24166   40.73
24      989481  24328   40.67
24      998134  25359   39.36
25      107934  2899    37.23
25      1135100 27762   40.89
25      1141000 27721   41.16
25      1168762 30637   38.15
25      1292162 31746   40.70
25      131333  3221    40.77
25      1381929 33260   41.55
25      1457809 35028   41.62
25      491676  11873   41.41
25      600125  15122   39.69
25      848442  20413   41.56
25      979054  25734   38.05
26      1009691 25469   39.64
26      1118053 28917   38.66
26      120799  2981    40.52
26      1303736 32513   40.10
26      995148  23991   41.48
27      1445373 35854   40.31
31      1539164 36285   42.42

**Comment by tijyojwad** [comment]
This is the mean Q score calculation - https://github.com/nanoporetech/dorado/blob/release-v0.5.3/dorado/utils/sequence_utils.cpp#L132
