### ISSUE TITLE
live basecalling on our cluster with ont_basecall_client and ont_dorado_server

### ISSUE THREAD

**Issue by gerald2545** [nanoporetech/dorado#663]
Hi,
we would like to be able to basecall our pod5 files on our slurm cluster using ont_basecall_client and ont_dorado_server 7.2.13.
I managed to run client, communicate with server using local socket on our GPU instances through slurm, to basecall some pod5 files present in a folder. No problem.

But now I would like to mimic MinKnow to automate all steps : 

- identify new pod5 available to be basecalled
- call ont_basecall_client with this new set of pod5
- at the end of sequencing, after all pod5 files are basecalled, merge bam files

Did someone implement such a workflow? Would you be OK to share your work?

Thank you for your help

Gérald

**Comment by HalfPhoton** [comment]
Hi @gerald2545, 
Have you seen the [Epi2Me wf-basecalling](https://labs.epi2me.io/workflows/wf-basecalling/) pipeline? I believe this is configurable to work on a cluster and might do what you want. 

Kind regards,
Rich

**Comment by gerald2545** [comment]
Thank you for your answer. Yes we identified this workflow, but it is based on the standalone dorado (current version uses 0.5.2) not ont_basecall_client.
If no other resource is available, the aim would be to adapt this workflow to use ont_basecall_client

**Comment by HalfPhoton** [comment]
@gerald2545, to the best of my knowledge we don't have a workflow like this unfortunately.
We commonly use dorado standalone and create parallel jobs on our cluster and merge the output bams afterwards but we don't have one specifically using dorado basecall server.
Sorry about that.
Kind regards,
Rich

**Comment by gerald2545** [comment]
Thank you for your messages

**Comment by aetobatus-narinari** [comment]
Hi @gerald2545 , I am in a new team of bioinformaticians and very new to computing.. but I want something similar as you already did.. I think.
We have a HPC, we can use - we want to basecall pod5 files there and not on Gridion computer and we want to use ont_basecall_client to do all of these.

May I ask how you managed to do this in a bit more detail?
_I managed to run client, communicate with server using local socket on our GPU instances through slurm, to basecall some pod5 files present in a folder. No problem._

Thanks in advance
