### ISSUE TITLE
Methylation patterns

### ISSUE THREAD

**Issue by Angelluigiguarnizo** [nanoporetech/dorado#668]
Dear authors,

I have a question regarding the detection of methylations.  I am not quite sure how it detects gold methylations, i.e. is it based on already existing methylation patterns (motifs) and then I can only detect those motifs, or can I detect new motifs based on the 4 existing methylation types. And, if I knew that motif but it is not in the training model, could I use it?

Thank you very much

**Comment by ArtRand** [comment]
Hello @Angelluigiguarnizo,

Could you explain in detail what you mean by "gold methylations"? For DNA we have modified base models for 5mC/5hmC at any cytosine and 6mA at adenine. Meaning that all Cs or As will get a base modification prediction. For RNA we currently have a m6A modification model that works in DRACH motifs (for the center 'A'). Additionally, there is a 4mC research model. Maybe if you tell me a little more about your use case I can help you decide which model to use.

**Comment by Angelluigiguarnizo** [comment]
ChatGPT 3.5

User
Traduce al inglés científico. Buenas,

Siento no haberme explicado bien, ha sido un error ya que no quería decir gold sino all.

Voy a intentar explicarlo mejor. En nuestro grupo queremos detectar metilaciones en varios genomas bacterianos.

He podido leer que hay varios programas como mcaller, megalodom, nanopolish que empleando modelos de entrenamiento son capaces de detectar diferentes metilaciones (secuenciado el DNA nativo), pero que requieren de conocer el motivo en el que ocurre esa metilación.

Hay otros como nanodisco, en los que secuenciando el DNA nativo y el WGA pueden detectar nuevos motivos en los que ocurre la metilación. El problema de este es que requiere secuenciar dos veces y eso incrementa el coste.

Mi pregunta es si Dorado es capaz de detectar nuevos motivos de metilación sin tener que secuenciar el WGA, yo estoy interesado en las adeninas. Asi mismo, por pacbio yo conozco el motivo que se metila, así que no sé si también se podría decir a dorado el motivo que estoy buscando.

Espero que ahora me haya explicado mejor, soy recientemente nuevo en el mundo del nanoporo.

Muchas gracias

ChatGPT
Hello,

I apologize for not explaining myself clearly earlier; it was a mistake as I didn't mean gold but all.

I will try to explain it better now. In our group, we want to detect methylations in various bacterial genomes.

I have read that there are several programs like mcaller, megalodom, and nanopolish that, using training models, are capable of detecting different methylations (sequencing native DNA), but they require knowing the motif in which that methylation occurs.

There are others like nanodisco, in which by sequencing native DNA and WGA, they can detect new motifs where methylation occurs. The problem with this is that it requires sequencing twice, which increases the cost.

My question is if Dorado is capable of detecting new methylation motifs without having to sequence the WGA, I am interested in adenines. Also, through pacbio, I know the motif that is methylated, so I don't know if I could also tell dorado the motif I am looking for.

I hope I have explained myself better now; I am recently new to the nanopore world.

Thank you very much



User
Buenas,

Siento no haberme explicado bien, ha sido un error ya que no quería decir gold sino all.

Voy a intentar explicarlo mejor. En nuestro grupo queremos detectar metilaciones en varios genomas bacterianos.

He podido leer que hay varios programas como mcaller, megalodom, nanopolish que empleando modelos de entrenamiento son capaces de detectar diferentes metilaciones (secuenciado el DNA nativo), pero que requieren de conocer el motivo en el que ocurre esa metilación.

Hay otros como nanodisco, en los que secuenciando el DNA nativo y el WGA pueden detectar nuevos motivos en los que ocurre la metilación. El problema de este es que requiere secuenciar dos veces y eso incrementa el coste.

Mi pregunta es si Dorado es capaz de detectar nuevos motivos de metilación sin tener que secuenciar el WGA, yo estoy interesado en las adeninas. Asi mismo, por pacbio yo conozco el motivo que se metila, así que no sé si también se podría decir a dorado el motivo que estoy buscando.

Espero que ahora le haya podido quedar más claro, soy recientemente nuevo en el mundo del nanoporo.

Muchas gracias

ChatGPT
Hello,

I apologize for not understanding your previous message correctly. I'll do my best to clarify. In our group, we aim to detect methylations in various bacterial genomes.

I've learned that there are several programs like mcaller, megalodom, and nanopolish that, using training models, can detect different methylations (by sequencing native DNA), but they require knowledge of the motif in which methylation occurs.

Others like nanodisco can detect new methylation motifs by sequencing both native DNA and WGA. However, this method requires sequencing twice, increasing the cost.

My question is whether Dorado can detect new methylation motifs without sequencing the WGA. I'm specifically interested in adenines. Additionally, through PacBio, I know the motif that is methylated, so I'm unsure if I can also inform Dorado about the motif I'm seeking.

I hope this clarification helps. I'm new to the nanopore world, so thank you for your understanding.

**Comment by Angelluigiguarnizo** [comment]
ChatGPT 3.5

User
Traduce al inglés científico. Buenas,

Siento no haberme explicado bien, ha sido un error ya que no quería decir gold sino all.

Voy a intentar explicarlo mejor. En nuestro grupo queremos detectar metilaciones en varios genomas bacterianos.

He podido leer que hay varios programas como mcaller, megalodom, nanopolish que empleando modelos de entrenamiento son capaces de detectar diferentes metilaciones (secuenciado el DNA nativo), pero que requieren de conocer el motivo en el que ocurre esa metilación.

Hay otros como nanodisco, en los que secuenciando el DNA nativo y el WGA pueden detectar nuevos motivos en los que ocurre la metilación. El problema de este es que requiere secuenciar dos veces y eso incrementa el coste.

Mi pregunta es si Dorado es capaz de detectar nuevos motivos de metilación sin tener que secuenciar el WGA, yo estoy interesado en las adeninas. Asi mismo, por pacbio yo conozco el motivo que se metila, así que no sé si también se podría decir a dorado el motivo que estoy buscando.

Espero que ahora me haya explicado mejor, soy recientemente nuevo en el mundo del nanoporo.

Muchas gracias

ChatGPT
Hello,

I apologize for not explaining myself clearly earlier; it was a mistake as I didn't mean gold but all.

I will try to explain it better now. In our group, we want to detect methylations in various bacterial genomes.

I have read that there are several programs like mcaller, megalodom, and nanopolish that, using training models, are capable of detecting different methylations (sequencing native DNA), but they require knowing the motif in which that methylation occurs.

There are others like nanodisco, in which by sequencing native DNA and WGA, they can detect new motifs where methylation occurs. The problem with this is that it requires sequencing twice, which increases the cost.

My question is if Dorado is capable of detecting new methylation motifs without having to sequence the WGA, I am interested in adenines. Also, through pacbio, I know the motif that is methylated, so I don't know if I could also tell dorado the motif I am looking for.

I hope I have explained myself better now; I am recently new to the nanopore world.

Thank you very much



User
Buenas,

Siento no haberme explicado bien, ha sido un error ya que no quería decir gold sino all.

Voy a intentar explicarlo mejor. En nuestro grupo queremos detectar metilaciones en varios genomas bacterianos.

He podido leer que hay varios programas como mcaller, megalodom, nanopolish que empleando modelos de entrenamiento son capaces de detectar diferentes metilaciones (secuenciado el DNA nativo), pero que requieren de conocer el motivo en el que ocurre esa metilación.

Hay otros como nanodisco, en los que secuenciando el DNA nativo y el WGA pueden detectar nuevos motivos en los que ocurre la metilación. El problema de este es que requiere secuenciar dos veces y eso incrementa el coste.

Mi pregunta es si Dorado es capaz de detectar nuevos motivos de metilación sin tener que secuenciar el WGA, yo estoy interesado en las adeninas. Asi mismo, por pacbio yo conozco el motivo que se metila, así que no sé si también se podría decir a dorado el motivo que estoy buscando.

Espero que ahora le haya podido quedar más claro, soy recientemente nuevo en 
Hello,

I apologize for not understanding your previous message correctly. I'll do my best to clarify. In our group, we aim to detect methylations in various bacterial genomes.

I've learned that there are several programs like mcaller, megalodom, and nanopolish that, using training models, can detect different methylations (by sequencing native DNA), but they require knowledge of the motif in which methylation occurs.

Others like nanodisco can detect new methylation motifs by sequencing both native DNA and WGA. However, this method requires sequencing twice, increasing the cost.

My question is whether Dorado can detect new methylation motifs without sequencing the WGA. I'm specifically interested in adenines. Additionally, through PacBio, I know the motif that is methylated, so I'm unsure if I can also inform Dorado about the motif I'm seeking.

I hope this clarification helps. I'm new to the nanopore world, so thank you for your understanding.

**Comment by Angelluigiguarnizo** [comment]
Hello again,

Sorry if I didn't manage to explain myself better in my previous messageI did not mean gold, but all. I'll try to explain it better.

 In our group, we aim to detect methylations in various bacterial genomes.

I've learned that there are several programs like mcaller, megalodom, and nanopolish that, using training models, can detect different methylations (by sequencing native DNA), but they require knowledge preciois of the motif in which methylation occurs.

Others like nanodisco can detect new methylation motifs by sequencing both native DNA and WGA. However, this method requires sequencing twice, increasing the cost.

My question is whether Dorado can detect new methylation motifs without sequencing the WGA. I'm specifically interested in adenines. Additionally, through PacBio, I know the motif that is methylated, so I'm unsure if I can also inform Dorado about the motif I'm seeking.

I hope this clarification helps. I'm new to the nanopore world, so thank you for your understanding.

Thanks

**Comment by ArtRand** [comment]
Hello @Angelluigiguarnizo,

The adenine (6mA) model and cytosine (5hmC/5mC, 4mC/5mC) models are all "all-context" models. This means that you don't need to know the motif _a priori_, all As or Cs will have a base modification probability. **N.b.** that the 4mC model is a "research model" provided through [rerio](https://github.com/nanoporetech/rerio/blob/master/dorado_models/res_dna_r10.4.1_e8.2_400bps_sup%40v4.3.0_4mC_5mC%40v1_url).

**Comment by angelluigi** [comment]
Hello ArtRnad,

Thanks about your response. 

I have got a new question. I did the sequencing, using flow cell R9 version ¿Could i get 6mA, using dna_R10? I have not seen any dna_R9 that says it can detect 6mA.

Thaks

**Comment by ArtRand** [comment]
Hello @angelluigi,

You should not try and use the dna_R10 models with R9 data, the sensor is fundamentally different. There is a R9 flip-flop all-context model on [rerio](https://github.com/nanoporetech/rerio/tree/master/basecall_models#flip-flop-modified-base-models) that will call 6mA (and 5mC). The caveat is these models are somewhat old at this point so the performance will not be as high as the current offerings.
