### ISSUE TITLE
samplesheet contains invalid column flow_cell_id

### ISSUE THREAD

**Issue by timternetnet** [nanoporetech/dorado#674]
# Issue Report

## Please describe the issue:

When running dorado basecaller, it complains about a column which should be there.

## Steps to reproduce the issue:

Samplesheet has the following format:

```
flow_cell_id,kit,sample_id,experiment_id,barcode,alias
FAXxxxxx,SQK-NBD114-96,XXX,240306_AMP_XXX,barcode01,VLIZ01
```

## Run environment:
- Dorado version: `0.5.1`
- Dorado command: `dorado basecaller sup 00_raw --barcode-both-ends --kit-name SQK-NBD114-96 --sample-sheet 01_basecalling/16SNanoporeSampleList.csv > 01_basecalling/calls.bam`
- Operating system: RHEL8
- Hardware (CPUs, Memory, GPUs): plenty, without a sample sheet it works fine, it's a HPC
- Source data type: `pod5`
- Source data location (on device or networked drive - NFS, etc.): on device

## Logs
Output:

Sample sheet contains invalid column `flow_cell_id`

Any pointers? :)

**Comment by HalfPhoton** [comment]
@timternetnet, 
Can you explain what's complaining specifically? Do you have an error message?
Does your sample sheet meet the specifications [SampleSheets.md](https://github.com/nanoporetech/dorado/blob/release-v0.5.3/documentation/SampleSheets.md)?
Kind regards,
Rich

**Comment by timternetnet** [comment]
Dear @HalfPhoton ,
I didn't see anything obvious wrong with my samplesheet, but now trying to prove what went wrong it seems to work when I reduce the sample sheet to a couple of lines (I had 96 samples). So I'll test further and try to track down why it didn't work the first time around, perhaps I missed a weird character somewhere.

Thanks for getting back to me! I'll close this one for now.

**Comment by hjarnek** [comment]
Hi,

I get the same issue, with the `position_id` column. Error message reads:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Sample sheet /path/sample_sheet.csv contains invalid column "position_id"
Aborted (core dumped)
```
and my sample sheet looks like this:

position_id | experiment_id | kit | flow_cell_product_code | barcode | alias | type
-- | -- | -- | -- | -- | -- | --
X1 | 73cc697e75703b5d465e69211bbb56118971c387 | SQK_LSK114 EXP-PBC096 | FLO-MIN114 | barcode01 | Sample01 | test_sample
X1 | 73cc697e75703b5d465e69211bbb56118971c387 | SQK_LSK114 EXP-PBC096 | FLO-MIN114 | barcode02 | Sample02 | test_sample

+26 more samples. Doesn't matter whether I only put a couple of samples though, as OP tried.

* Dorado version: `1.0.2`
* Dorado command: `dorado demux /path/concatenated.gz --output-dir /path/demuxed --kit-name EXP-PBC096 --sample-sheet /path/sample_sheet.csv`
* Source data type: A gzipped FASTQ file

Any ideas?

Ping @HalfPhoton

**Comment by HalfPhoton** [comment]
@hjarnek - can you send the actual sample sheet as an attachment please?

**Comment by hjarnek** [comment]
[sample_sheet.csv](https://github.com/user-attachments/files/20930021/sample_sheet.csv)

**Comment by HalfPhoton** [comment]
@hjarnek 

Your samplesheet doesn't conform to the specification because all fields are wrapped in quotation marks which is not valid.

```text
"position_id","experiment_id","kit","flow_cell_product_code","barcode","alias","type"
```

Please remove them and your issue will be resolved. 

Kind regards,
Rich

**Comment by hjarnek** [comment]
@HalfPhoton 

You're right, thanks. Now it works. Stupid Excel putting those quotes in there without showing so. Although, I can imagine it's not uncommon that people use Excel for the purpose of creating those sample sheets. Perhaps it could be worthwhile to throw in a specific warning message when fields are quoted? Because the error message `Sample sheet /path/sample_sheet.csv contains invalid column "position_id"` makes no sense at all if you don't know that it isn't the error message that puts those quotes there. Or alternatively, you could perhaps even allow quoted fields.

**Comment by HalfPhoton** [comment]
We'll improve this error message 👍
