### ISSUE TITLE
no rule to make target '/usr/lib64/libcufft_statis_nocallback.a'

### ISSUE THREAD

**Issue by DKTMPELRN** [nanoporetech/dorado#675]
#Dorado not finding /usr/lib64/libcufft_statis_nocallback.a

I'm using dorado for the first time, going along with the documentation quick installation instructions. I made it to the line `cmake --build cmake-build --config Release -j 4`, but it gives:

```
[  6%] Built target htslib_project
[  7%] Built target streamvbyte
[  8%] Built target edlib
[  9%] Built target dorado_torch_lib
[ 15%] Built target vbz
[ 15%] Built target spdlog
[ 16%] Built target vbz_hdf_plugin
[ 22%] Built target minizip
[ 31%] Built target minimap2
[ 32%] Built target elzip
[ 33%] Built target dorado_pch
[ 43%] Built target dorado_utils
[ 47%] Built target dorado_modbase
[ 52%] Built target dorado_basecall
[ 69%] Built target dorado_lib
[ 71%] Built target dorado_models_lib
[ 73%] Built target dorado_io_lib
gmake[2]: *** No rule to make target '/usr/lib64/libcufft_static_nocallback.a', needed by 'bin/dorado'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:456: CMakeFiles/dorado.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake[2]: *** No rule to make target '/usr/lib64/libcufft_static_nocallback.a', needed by 'tests/dorado_smoke_tests'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:987: tests/CMakeFiles/dorado_smoke_tests.dir/all] Error 2
gmake[2]: *** No rule to make target '/usr/lib64/libcufft_static_nocallback.a', needed by 'tests/dorado_tests'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:947: tests/CMakeFiles/dorado_tests.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
```

All the dependency packages installed and are updated. 

## Steps to reproduce the issue:

Follow along with the installation tutorial in WSL. 

## Run environment:
- Dorado version: 0.5.3
- Dorado command: cmake --build cmake-build --config Release -j 4
- Operating system: WSL
- Hardware (CPUs, Memory, GPUs): No GPUs, 16 GB ram
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.): 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by HalfPhoton** [comment]
Hi @DKTMPELRN,
What version of `cmake` do you have? 

Kind regards,
Rich

**Comment by janka000** [comment]
Hello, 
I think I have a very similar issue.
I am using WSL too, this is the log:
```
Consolidate compiler generated dependencies of target dorado_torch_lib
[  1%] Built target dorado_torch_lib
[  5%] Built target htslib_project
[  8%] Built target streamvbyte
Consolidate compiler generated dependencies of target vbz
[ 10%] Built target vbz
Consolidate compiler generated dependencies of target vbz_hdf_plugin
[ 11%] Built target vbz_hdf_plugin
Consolidate compiler generated dependencies of target spdlog
[ 15%] Built target spdlog
Consolidate compiler generated dependencies of target minimap2
[ 24%] Built target minimap2
Consolidate compiler generated dependencies of target edlib
[ 25%] Built target edlib
Consolidate compiler generated dependencies of target dorado_pch
[ 26%] Built target dorado_pch
Consolidate compiler generated dependencies of target dorado_utils
[ 36%] Built target dorado_utils
Consolidate compiler generated dependencies of target dorado_basecall
[ 40%] Built target dorado_basecall
Consolidate compiler generated dependencies of target dorado_modbase
[ 44%] Built target dorado_modbase
Consolidate compiler generated dependencies of target dorado_lib
[ 62%] Built target dorado_lib
Consolidate compiler generated dependencies of target minizip
[ 68%] Built target minizip
Consolidate compiler generated dependencies of target elzip
[ 69%] Built target elzip
Consolidate compiler generated dependencies of target dorado_models_lib
[ 71%] Built target dorado_models_lib
Consolidate compiler generated dependencies of target dorado_io_lib
[ 73%] Built target dorado_io_lib
Consolidate compiler generated dependencies of target dorado
gmake[2]: *** No rule to make target '/usr/lib64/libcufft_static_nocallback.a', needed by 'bin/dorado'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:456: CMakeFiles/dorado.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
```

I have cmake version 3.22.1

**Comment by iiSeymour** [comment]
@janka000 you don't need to compile dorado from source as we provide binaries here https://github.com/nanoporetech/dorado?tab=readme-ov-file#installation

**Comment by ChengzheDuan** [comment]
@iiSeymour Sorry in advance if my question is too obvious. I encountered the same error described above when installing Dorado on a Linux machine. I then downloaded the binary "dorado-0.5.3-linux-x64" but I'm not sure where to place the "bin" and "lib" folders so that I can use Dorado in MinKNOW. Any advice would be greatly appreciated!

**Comment by malton-ont** [comment]
@ChengzheDuan,

MinKNOW uses the `dorado_basecall_server` for basecalling. This is a different (non-public) project which utilises dorado code as a submodule but is not the same executable. You can't drop just dorado into MinKNOW I'm afraid.

@janka000, @DKTMPELRN - if you want to build from source, please update to CMake >= 3.23. We will update dorado in a future release to correctly enforce this requirement.
