### ISSUE TITLE
All context 5mC model 5kHz in dorado

### ISSUE THREAD

**Issue by jasmatth** [nanoporetech/dorado#678]
Input code:
dorado basecaller res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1 pod5_directory --modified-bases-models res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1_5mC@v2 > output.bam

When running this code I get following error:
[error] Sample rate for model (4000) and data (5000) are not compatible.

I know this is related to the fact that the model is in 4kHz and the data is in 5kHz, but there is no model for all context 5mC in 5kHz.
Are there any suggestions on how to deal with this issue?

**Comment by HalfPhoton** [comment]
@jasmatth, has this answered your question?

**Comment by jasmatth** [comment]
Hi, yes, thanks for the help!
