### ISSUE TITLE
Duplex basecalling without cutting/trimming adaptors

### ISSUE THREAD

**Issue by pclavell** [nanoporetech/dorado#679]
I'd like to perform a duplex basecalling without trimming the adaptors as I later want to use a linker contained after the 5' adaptor to demultiplex. However, the parameter --no-trim is not available for dorado duplex function. Is there any workaround for this?

**Comment by tijyojwad** [comment]
Hi @pclavell - the way our duplex pairing heuristics work will result in the adapter getting trimmed off.

However, each duplex read tracks the parent reads they came from (the read id is `parent_read1;parent_read2`). So you can demultiplex the parent simplex read (which won't be trimmed in the duplex pipeline) and use that information to then demux the duplex offspring.

**Comment by pclavell** [comment]
Hi @tijyojwad , so I understand that in `dorado duplex`, by default, all simplex reads (independently of having a pair read, and therefore an associate duplex) are not trimmed and they preserve ONT adapters and any other adjacent primer.

**Comment by tijyojwad** [comment]
yes that's correct
