### ISSUE TITLE
CPP equivalent for ont-pyguppy-client-lib

### ISSUE THREAD

**Issue by maximilianmordig** [nanoporetech/dorado#684]
I am looking for a cpp equivalent of `ont-pyguppy-client-lib` which seems to be mostly closed-source for live basecalling from cpp. Is it available? If not, what it the message format that the basecall server (guppy or dorado) expects? Also, I guess you use zeromq rather than protobuf.

**Comment by MarkBicknellONT** [comment]
Hi @maximilianmordig,

We don't currently provide a C++ client library for use with the basecall server.  Can you let me know a little bit about what you are trying to do?  We could look into making a C++ library available for external users in future, but there has not been any demand for it up until now.

The communication layer between the client and server is indeed using ZeroMQ. The low level communication protocol is not straightforward, so I wouldn't recommend trying to interface with the basecall server directly.

Kind regards,
Mark
