### ISSUE TITLE
Manually select simplex and stereo models for duplex basecalling

### ISSUE THREAD

**Issue by pclavell** [nanoporetech/dorado#685]
I am running `dorado duplex` in a cluster without internet connection and therefore I have to manually provide the models for the simplex and stereo duplex basecalling. However, in the documentation there is only the specification for simplex model+modified bases models (which are basically separated by ",") and this doesn't work for simple model + duplex model and the following error is outputed.

````
Unknown modification variant: 'dna_r10.4.1_e8.2_4khz_stereo@v1.1' - Choices: 6mA, 5mC, m6A_DRACH, 5mCG_5hmCG, 5mCG, 5mC_5hmC
[error] Failed to parse model argument. Failed to parse modified model arguments
````

**Comment by HalfPhoton** [comment]
Related: https://github.com/nanoporetech/dorado/issues/681

As long as the stereo model and simplex model reside in the same directory the stereo model should be discovered without needing to be downloaded. 

You cannot specify the stereo model in the simplex model path this will not work and is why you're seeing the above error. Please omit this path. 

Kind regards,
Rich
