### ISSUE TITLE
Do you have any suggestion on getting some summary QC on mapped bam file?

### ISSUE THREAD

**Issue by sidi-yang** [nanoporetech/dorado#688]
Dear team,

I have used Sequencing Summary function of dorado, and I find the metrics I got from this function is from each read (each row indicates each read), but I cannot get an overall QC summary of the mapped bam file, like some parameters of mapping rate, coverage depth, GC content, Read length distribution and MapQ. 

I'm writing this issue to ask whether you have any suggestion on how to get an overall QC summary of the mapped bam file? Any software you suggest?  

Thank you very much,
Sidi

**Comment by sidi-yang** [comment]
Thank you very much!

**Comment by juanjo255** [comment]
Hello @sidi-yang,

I recommend you [Cramino](https://github.com/wdecoster/cramino) and [Nanoplot](https://github.com/wdecoster/NanoPlot). 

I hope it helps,

Juan.

**Comment by sidi-yang** [comment]
Thank you very much! I'll give it a try!
