### ISSUE TITLE
m6A RNA004 models

### ISSUE THREAD

**Issue by dweemx** [nanoporetech/dorado#689]
# Issue Report

## Please describe the issue:

Are you planning in the near future, to have a Dorado model to basecall m6A modifications (not constrained by the DRACH motif) ? And if so, do you have a broad idea when ? 

## Steps to reproduce the issue:

None

## Run environment:

- Dorado version: `>= 0.5.3`

## Logs

N.A.

**Comment by marcus1487** [comment]
Yes. We are planning an all-context m6A RNA model. This model is planned for inclusion in the next Dorado release.
