### ISSUE TITLE
Error undefined symbol cublasGetSmCountTarget from libcublas.so.11

### ISSUE THREAD

**Issue by dithiii** [nanoporetech/dorado#69]
Running dorado 0.1.1 with any model on a fresh install of ubuntu 22.04 gives the following error. However, the base calling still appears to be working despite this error. Any fix?
`[2022-12-30 09:46:27.264] [info] > Creating basecall pipeline
Could not load symbol cublasGetSmCountTarget from libcublas.so.11. Error: /home/cfaulk/Desktop/dorado-0.1.1+eb48766-Linux/bin/../lib/libcublas.so.11: undefined symbol: cublasGetSmCountTarget`

**Comment by dithiii** [comment]
Update. This error only appears when `--modified-bases` is used. 

Also, when run with --modified-bases, the process eventually crashes non-deterministically, at about 22 Gb of output. I've tried using various inputs, fast5s, monolithic pod5s, and individually converted pod5s. Same result. Looks like something is going wrong with modified base calling.

**Comment by dithiii** [comment]
Different issue, but maybe related? I'm trying to compile from the github and cannot complete due to the following error. 
`[ 31%] Completed 'streamvbyte'
[ 31%] Built target streamvbyte
gmake: *** [Makefile:166: all] Error 2`

**Comment by dithiii** [comment]
On the build problem, I installed h5py and autoconf (version 2.6.9 is needed), and a few other undocumented dependencies, but now I'm stuck at the following error. I did install htslib with libdeflate (both compiled and with apt).

`[100%] Linking CXX executable bin/dorado
/usr/bin/ld: 3rdparty/htslib/lib/libhts.a(cram_io.o): in function libdeflate_deflate':`
`/home/cfaulk/Desktop/monkeymeth/dorado/dorado/3rdparty/htslib/cram/cram_io.c:1118: undefined reference to libdeflate_alloc_compressor'`
`/usr/bin/ld: /home/cfaulk/Desktop/monkeymeth/dorado/dorado/3rdparty/htslib/cram/cram_io.c:1133: undefined reference to libdeflate_gzip_compress'`
`/usr/bin/ld: /home/cfaulk/Desktop/monkeymeth/dorado/dorado/3rdparty/htslib/cram/cram_io.c:1134: undefined reference to libdeflate_free_compressor'`
`/usr/bin/ld: /home/cfaulk/Desktop/monkeymeth/dorado/dorado/3rdparty/htslib/cram/cram_io.c:1129: undefined reference to libdeflate_free_compressor'`
`/usr/bin/ld: 3rdparty/htslib/lib/libhts.a(cram_io.o): in function uint7_decode_crc64':`

**Comment by rainwala** [comment]
Hi dithii, I have this same issue on the epi2me human variation workflow, using Ubuntu 20.04. DId you ever solve this?
