### ISSUE TITLE
Troubleshooting Demultiplexing Consistency in Multiplexed Libraries

### ISSUE THREAD

**Issue by VahidJavaran** [nanoporetech/dorado#690]
Hi there,
I’ve come across a bit of a puzzle with my sequencing work. I ran three libraries on R10 flowcells and six on flongles, all multiplexed. Here’s the head-scratcher: every time I’ve basecalled POD5 and dug into the analysis, each sample flags the exact same pathogens. It’s strange because I’ve got some of these samples sequenced on a MiSeq as well, and those results different from nanopore results.

For basecalling, I used:

./dorado basecaller sup .../pod5 --verbose --min-qscore 7 --kit-name SQK-NBD114-96 > ...bam

And for demuxing:

./dorado demux --output-dir ..... --verbose ...bam --no-classify --emit-fastq

I'm scratching my head over what to do next. I did try --barcode-both-ends once, but it ended up with a lot of reads dropping into the unclassified file. Now I'm pondering if the read length has anything to do with it since the cDNA datasets are about 1 kb on average. Do you think the process of basecalling gets affected when it's done in the mix of multiplexing step versus going solo?
Any advice or thoughts would be a lifesaver.
Best,

**Comment by tijyojwad** [comment]
> Do you think the process of basecalling gets affected when it's done in the mix of multiplexing step versus going solo?

No, basecalling results aren't affected by in-line demultiplexing. You can run the `basecaller` cmd with `--no-trim` if you want to keep the entire sequence and demux again at a later stage.

>  every time I’ve basecalled POD5 and dug into the analysis, each sample flags the exact same pathogens

Can you explain this a bit more? Are you seeing that after demultiplexing, the contents of each barcode is the same pathogen when they should all be different?

Do you have references for each pathogen? If so, anything thing to try would be to align the basecalled results (no --kit-name provided) reads against each reference and see if you recover the different pathogens?

**Comment by VahidJavaran** [comment]
> > Do you think the process of basecalling gets affected when it's done in the mix of multiplexing step versus going solo?
> 
> No, basecalling results aren't affected by in-line demultiplexing. You can run the `basecaller` cmd with `--no-trim` if you want to keep the entire sequence and demux again at a later stage.
> I did that. The results were same.
> > every time I’ve basecalled POD5 and dug into the analysis, each sample flags the exact same pathogens
> 
> Can you explain this a bit more? Are you seeing that after demultiplexing, the contents of each barcode is the same pathogen when they should all be different?
> As an example, let's consider a library with 6 different samples, such as bell peppers, blueberries, carrots, or raspberries. For this library, I spiked DCS control DNA, except for the Bellpepper sample. I considered the bellpepper to be a negative control. As a result of basecalling and demultiplexing, I removed the host reads, and then mapped my reads on a local viral database. I checked all samples. They also have bellpepper virus in addition to their specific viruses. Even though I did not use DCS control for Bellpepper sample, it contains DCS control after analysis. The N50 of this pooled library was 3.2kb. 

There is also another library with N50 1kb. This library's samples have exactly the same virus detection list. There are however differences in the number of reads that map to each virus across samples. The true positive viruses have more mapped reads than the false positives. Does the diversity in length size of my datasets affect the demultiplexing?

> Do you have references for each pathogen? If so, anything thing to try would be to align the basecalled results (no --kit-name provided) reads against each reference and see if you recover the different pathogens?
Yes, I do have reference sequences for each virus I'm expecting to find in the respective host plants. However, the situation is a bit perplexing. In theory, each plant species in my samples should be infected with its specific viruses. But according to my results, all samples—including those from different plant species—are showing reads for a virus that should only be present in the bellpepper samples. 
please see this picture:
![photo1710523720](https://github.com/nanoporetech/dorado/assets/135045846/e7e86d04-ec64-4aac-81a7-f2302774bba7)
In this carrot sample, Bellpepper virus should not be in my sample.

**Comment by VahidJavaran** [comment]
An update:
After basecalling and demultiplexing using the --no-trim option, I aligned the reads against a viral genome that shouldn't have been present in my samples. Out of this, I identified 153 sequences corresponding to the virus.

I then proceeded to trim the reads, retaining only the first 500bp of each. Surprisingly, when these trimmed reads were aligned against the barcode references, 70 of them matched exactly with a particular barcode sequence. These were expected to be tagged with barcode 20, but were instead associated with barcode 19. Despite this mislabeling, they covered 98% of the viral genome, leading to a significant false positive result.

![image](https://github.com/nanoporetech/dorado/assets/135045846/3610274b-c14d-4eba-9720-d51e614d20a3)


This raises a question: Could this mislabeling issue stem from our library preparation protocol, or might it be related to the basecalling and multiplexing processes? Our protocols have been refined based on previous direct cDNA sequencing experiences using R9 flowcells, and we have not previously encountered such discrepancies in our sequencing efforts.

Additionally, I've observed that any R10 flowcell and flongle loaded with our V14 chemistry-based libraries have consistently presented these peculiar and odd false-positive events. This pattern is causing concern, as it suggests a potential issue that is specific to the new chemistry and/or flowcell technology.

**Comment by VahidJavaran** [comment]
****

**Comment by tijyojwad** [comment]
Hi @VahidJavaran thanks for continuing to investigate the issue! From your most recent update, it doesn't sound like a basecalling/demultiplexing issue. The basecaller errors would look like random error, but since your reads align well to the bell pepper virus I doubt the basecaller is doing something unexpected. Same for demux - I expect the reads where you found barcode19 sequences were correctly classified as barcode 19 by dorado? However if they were supposed to be barcode20, perhaps there's some contamination is at play...

**Comment by VahidJavaran** [comment]
Hi @tijyojwad It seems the issue is related to library preparation, not dorado. I basecalled my POD5 files also by Guppy. Same issue was also observed.

**Comment by tijyojwad** [comment]
Appreciate the update! I'll close this ticket for now, feel free to re-open it if you see any SW issues with dorado basecaller/demux!
