### ISSUE TITLE
dorado 0.3.x doesn't support newer methylation models?

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#691]
# Issue Report

## Please describe the issue:
I am getting this error when running dorado 0.3.4 with this command:
./dorado basecaller -r --modified-bases-models dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v3.1 dna_r10.4.1_e8.2_400bps_sup@v4.2.0 pod5/ > sample.ubam"

 --> dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v3.1/config.toml
    |
 11 | mod_bases = [ "h", "m",]
    |             ~~~~~~~~~~~~ the actual type is array

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*
I tried 
./dorado basecaller -r --modified-bases-models dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1 dna_r10.4.1_e8.2_400bps_sup@v4.3.0 pod5/ > sample.ubam"

and getting the same error but it works fine if I use dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v2.

By simply cat the config.toml for these three models, I noticed that for 4.2.0@v2, that line is simply
mod_bases = "hm"
I also notice the newer config.toml has an extra line of
reverse_signal = false
and chunk_context_0 and chunk_context_1 from 50 to 100

If I simply replace the mod_base line in the newer config.toml with mod_bases ="hm". Can I expect meaningful result with 4.3.0@v1 and 4.2.0@v3.1 methylation models?

## Run environment:
- Dorado version: 0.3.4
- Dorado command: ./dorado basecaller -r --modified-bases-models dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v3.1 dna_r10.4.1_e8.2_400bps_sup@v4.2.0 pod5/ > sample.ubam"
- Operating system: Ubuntu 20.04
- Hardware (CPUs, Memory, GPUs): 4xA100 80GB

**Comment by sklages** [comment]
0.3.x is quite old. Go for 0.5.3 and give it a try 🙂

**Comment by ymcki** [comment]
I am benchmarking 0.3.x, 0.4.x and 0.5.x with 4.2.0 and 4.3.0 models, so ideally it would be great if 0.3.x can also work with 4.3.0 models.

**Comment by tijyojwad** [comment]
Hi @ymcki - v4.3 model compatibility was officially only added with 0.5.x (I believe there was experimental support for it in 0.4.3 but it was not optimized).

In general we don't guarantee backwards compatibility for newer models.
