### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by VandaLovejoy** [nanoporetech/dorado#694]
# Issue Report

## Please describe the issue:

Hello,
I'm trying to run dorado basecaller using a slurm scheduler. For some reason, I dont get any output. The same command line works on a local linux computer.

## Steps to reproduce the issue:

Tried removing different parameters, tried with more or less memory but still no output

## Run environment:
- Dorado version: 0.5.3
- Dorado command: dorado basecaller --kit-name "SQK-NBD114-24" --barcode-both-ends --no-trim --recursive --verbose dna_r10.4.1_e8.2_400bps_sup@v4.3.0 /scratch/vanda21/Danny/20230727_1614_3G_PAK96750_e8eb9c25/pod5_folder
- Operating system: Linux CenOs7
- Hardware (CPUs, Memory, GPUs): --gpus-per-node=2 --time=02:00:00 --mem=128GB
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location :NFS 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

[2024-03-15 17:24:43.723] [info] > Creating basecall pipeline

**Comment by sklages** [comment]
What was the actual problem? And what was the solution?

**Comment by VandaLovejoy** [comment]
dorado seemed to be stalling for hours at this stage "> Creating basecall pipeline". Had to run it with the data split in two.

**Comment by tijyojwad** [comment]
Hi @VandaLovejoy - how big is your dataset? Dorado reads the pod5 metadata to determine some high level stats before basecalling, and since your data is on NFS I expect the read I/O is a bottleneck.
