### ISSUE TITLE
RNA004 Trim question with Dorado v0.5.3

### ISSUE THREAD

**Issue by Yang990-sys** [nanoporetech/dorado#696]
Hello, 

I used dorado v0.5.3 to identify the length of poly(A)，then I found,

![image](https://github.com/nanoporetech/dorado/assets/54176741/2f355038-7f9d-4f8a-a673-5c69527dc429)

does this mean that I still need to trim adapter ? And after trimming with `dorado trim` , the redundant sequence after poly(A) has not been trimmed，which is different with dorado v0.4.3 in issue #613  . But the bam file is indeed different. How can I obtain the correct trimmed sequence without rebasecalling ？
![image](https://github.com/nanoporetech/dorado/assets/54176741/1e1c1f54-8ab7-4f02-8873-015976be5391)

And This is my trim code：
![image](https://github.com/nanoporetech/dorado/assets/54176741/2974250b-bdde-4b98-9c05-732ef32f0889)

**Comment by tijyojwad** [comment]
Hi @Yang990-sys - right now `dorado trim` only supports trimming DNA sequences, not RNA. When we do poly A tail estimation, we indeed turn off adapter trimming (to keep that behavior consistent between cDNA and dRNA). So for now there's no way to do this with `dorado`.

Do you observe the reads being slightly different after running `dorado trim`? I think what's happening is perhaps some variation of the DNA adapter sequence is being detected and the tool is trimming that. Should be quite rare I would think. Unless the difference in BAMs is only coming from ordering of reads and not actual read content differences

**Comment by Yang990-sys** [comment]
> Hi @Yang990-sys - right now `dorado trim` only supports trimming DNA sequences, not RNA. When we do poly A tail estimation, we indeed turn off adapter trimming (to keep that behavior consistent between cDNA and dRNA). So for now there's no way to do this with `dorado`.
> 
> Do you observe the reads being slightly different after running `dorado trim`? I think what's happening is perhaps some variation of the DNA adapter sequence is being detected and the tool is trimming that. Should be quite rare I would think. Unless the difference in BAMs is only coming from ordering of reads and not actual read content differences

Hello @tijyojwad , I have read the original code and found that the adapter position of RNA004 is determined and cut off through signal changes. Does this mean that it cannot be removed well only through sequence alignment and trimming?

**Comment by tijyojwad** [comment]
Hi @Yang990-sys - the adapter region of RNA is not basecalled very well, so it's harder to trim using sequence only. However, we do expect the Q score to be lower in that region so it may be possible for you to devise something heuristic that works on some sort of Q score thresholding. We hope to improve this in the future.

**Comment by gowgowuk** [comment]
Hello,
I am trying to do RNA basecalling without any trimming. Just to confirm, are you saying that even without the --no-trim option, no trimming is done? Thanks

**Comment by tijyojwad** [comment]
Hi @gowgowuk - sorry for the confusion. For RNA, the `--no-trim` works as expected - if it is supplied, RNA adapters are not trimmed. Otherwise they are. The only exception is if basecalling is run with `--estimate-poly-a` then adapter trimming is _disabled_.
