### ISSUE TITLE
5mC calling in samples with other modified nucleotides

### ISSUE THREAD

**Issue by JuandeBarba** [nanoporetech/dorado#697]
Hello,

we are stablishing 5mC identification using R10 flowcells and using the 5CG models. However, our samples will surely contain other types of modified nucleotides (EdU and Brdu for instance). Is it known if the methylation calling is affected by these?

Thanks.

**Comment by marcus1487** [comment]
We have not specifically tested for an effect from EdU or BrdU. And we have not included these bases in any model training. Any modified bases not found in common samples (5mC, 5hmC, 4mC, 6mA) could certainly have an effect on results given that the basecalling model and modified base calling models have not encountered signal from these bases.
