### ISSUE TITLE
bacterial sequence for R9.4

### ISSUE THREAD

**Issue by sahoo2000** [nanoporetech/dorado#698]
I have bacterial genomic sequences produced by R9.4 type flowcells. My goal here is to detect 6mA, 4mC and 5mC modifications. I am not able to find any model that satisfies the above criteria to perform modified basecalling. Is it possible to suggest something here?

**Comment by vellamike** [comment]
Hi @sahoo2000 ,

The 5mCG_5hmCG model is available for R9. However a 6mA model is not available, if you want to detect 6mA you will need to resequenced your data using R10 Flowcells. 4mC mod base models currently are not available for any condition.

Mike
