### ISSUE TITLE
Could Dorado provide the ployA start and end index?

### ISSUE THREAD

**Issue by guangzhaocs** [nanoporetech/dorado#700]
1. I add `--estimate-poly-a` to the basecaller command. In the `bam` resluts, I get `pt:i` tag for some reads. But I could NOT find the ployA start and end index according to the raw signal. So in the current version, could Dorado only provide the length of ployA?

2. When I add `--estimate-poly-a --emit-fastq` to the basecaller command, in the final `fastq` file I can NOT find the `pt:i` tag. So could Dorado only provide the length of ployA in `bam/sam` format?

Thanks a lot.

**Comment by tijyojwad** [comment]
> So in the current version, could Dorado only provide the length of ployA?

yes that's right - we plan to add boundaries of the signal in a subsequent release.

> So could Dorado only provide the length of ployA in bam/sam format?

yes correct

**Comment by guangzhaocs** [comment]
Thanks very much, I don't have other questions about this.
