### ISSUE TITLE
Reads number in bam/sam resluts

### ISSUE THREAD

**Issue by guangzhaocs** [nanoporetech/dorado#701]
In my original pod5 files, I have 63886 reads. I run `dorado basecaller` and get the bam file. Then I use `samtools`  to convert it to `sam` file. I counted the reads number in the `sam` file and found that contains 67690 reads. I do not know why. 

I compared the read id in the original pod5 files and the sam file, and found that the sam file has some reads that do not exist in the pod5 file.

![image](https://github.com/nanoporetech/dorado/assets/85612159/3b148da3-2abf-4aea-a76e-5c1353fb29ad)

## Run environment:
- Dorado version: 0.5.3
- Dorado command: dorado basecaller models/rna002_70bps_hac@v3/ multi_pod5 --estimate-poly-a > res.bam 
- samtools view -h -o res.sam  res.bam

**Comment by HalfPhoton** [comment]
@guangzhaocs - These new read ids from the read splitting of concatemers.

**Comment by guangzhaocs** [comment]
Hi, could I prevent the splitting using some parameters?
