### ISSUE TITLE
NVIDIA error for running dorado

### ISSUE THREAD

**Issue by dfv** [nanoporetech/dorado#703]
# Issue Report

## Please describe the issue:

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version:
- Dorado command:
- Operating system:
- Hardware (CPUs, Memory, GPUs):
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.): 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by dfv** [comment]
Hi,
I am trying to run dorado basecaller by using command:
dorado basecaller --estimate-poly-a /Path-to-file/dna_r10.4.1_e8.2_400bps_hac@v4.2.0 /Path-to-files/Sample1_barcode49/ --device cuda:0,2
I am getting below error:
 [info] Estimation of poly-a has been requested, so adapter/primer trimming has been disabled.
 [info] > Creating basecall pipeline
 [error] The NVIDIA driver on your system is too old (found version 9020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
Exception raised from device_count_impl at /pytorch/pyold/c10/cuda/CUDAFunctions.cpp:46 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7fd6befec9b7 in /ncbs_gs/nlsas_data/usershares/dasaradhip/aankit/FLAM-seq_data/dorado-0.5.3-linux-x64/bin/../lib/libdorado_torch_lib.so)

Is it possible to know how to resolve it ?
Thanks.

Regards
Ankit

**Comment by HalfPhoton** [comment]
Hi @dfv,

As the error suggests your GPU drivers appear to be too old. Have you tried updating the GPU drivers by following the link: http://www.nvidia.com/Download/index.aspx ?

Kind regards,
Rich

**Comment by dfv** [comment]
Hi Rich,

Thanks for your reply.

Actually I installed PyTorch version that has been compiled with your version of the CUDA driver. But still the error persists.

**Comment by HalfPhoton** [comment]
Assuming you're using a dorado binary from our distributions - Updating your version of the torch library will not work as dorado has been compiled (by us) using a different version which is tied to a minimum CUDA version. You'll either need to recompile dorado yourself with your version of torch or update your CUDA drivers. 

Kind regards,
Rich

**Comment by dfv** [comment]
I have the checked our cluster it has:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00 Driver Version: 418.87.00 CUDA Version: 10.1 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 Tesla K40m Off | 00000000:02:00.0 Off | 0 |
| N/A 25C P0 64W / 235W | 0MiB / 11441MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 1 Tesla K40m Off | 00000000:82:00.0 Off | 0 |
| N/A 29C P0 65W / 235W | 0MiB / 11441MiB | 99% Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|
| No running processes found |

But with CUDA 10.1 driver it's still showing the error. Any idea which CUDA driver version it require ?

**Comment by HalfPhoton** [comment]
From [dorado supported platform documentation](https://git.oxfordnanolabs.local/machine-learning/dorado#platforms) we want ```CUDA Driver ≥450.80.02``` (I'm assuming your system is linux x86_64) which is CUDA 11.x based on the [nvidia version compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#minor-version-compatibility).

We use CUDA11.8

Kind regards,
Rich

**Comment by dfv** [comment]
Yes, its linux (x86_64). Could I try with CUDA12.4 in my system to resolve the error ? Currently it's running CUDA10.1

**Comment by HalfPhoton** [comment]
It should work 🤞

**Comment by HalfPhoton** [comment]
@dfv  
Apologies - I was incorrect before. The K40m GPU's you have are using the Kepler architecture which isn't supported by Dorado. 

Kind regards,
Rich
