### ISSUE TITLE
lots of mutations found in direct RNA sequencing and dorado basecaller

### ISSUE THREAD

**Issue by yul96** [nanoporetech/dorado#707]
# Issue Report

## Please describe the issue:

We found a lot of mutations in the base called RNA reads using Dorado 0.5.3, the RNA is the product of in vitro transcription and the reads are mapped back to the template to evaluate mutations. There are a lot of non-random mutations in the reads. Is this expected for the current Dorado basecaller?

We ran six  independent samples and these mutations are not expected.

## Steps to reproduce the issue:
mRNA is produced by in vitro T7 transcription

direct RNA sequencing is used to generate the raw data according to the manual (SQK-RNA004)

dorado 0.5.3 is used to do the base call, command as below:

...../dorado-0.5.3-linux-x64/bin/dorado basecaller --estimate-poly-a --verbose ...../dorado-0.5.3-linux-x64/bin/rna004_130bps_sup@v3.0.1 pod5 >  dorado.calls.sam

## Run environment:
- Dorado version: 0.5.3
- Dorado command: see above
- Operating system: Red Hat 7 and 8
- Hardware (CPUs, Memory, GPUs): GPU, 64GB
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location (on device or networked drive - NFS, etc.):  NFS
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 1 million reads
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)
<img width="1226" alt="Screenshot 2024-03-25 at 2 27 37 PM" src="https://github.com/nanoporetech/dorado/assets/107077700/45a474c1-f3c6-49d0-9524-ee541c1db285">

**Comment by VBHerrenC** [comment]
Is it possible that you are using some kind of modified base in your IVT? Some modified bases are often miscalled as C's.

**Comment by yul96** [comment]
@VBHerrenC I think you are right, I spoke to the team and they used modified bases. thanks

**Comment by HalfPhoton** [comment]
Thanks for contributing to this issue @VBHerrenC.
