### ISSUE TITLE
--Device flag specifications

### ISSUE THREAD

**Issue by jadeaver** [nanoporetech/dorado#710]
# Issue Report

## Please describe the issue: 

I have a multi-GPU system and I am unable to assign the correct GPU to use with the --device flag. The NVIDIA GPU are listed as device 0 so I have tried using the flag --device cuda:0, --device cuda:0,2, and --device CPU. I know using CPU will be slow and is not recommended, but I tried it to see if it would give the same error. It does not give any error. I have assigned Dorado to use the NVIDIA GPU as default on my system, still no

 luck. I feel like I may not be setting up the -device argument correctly, but I am not sure? 

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version: 0.5.3
- Dorado command: dorado basecaller sup POD5s/ --device cpu --emit-fastq --kit-name SQK-NBD114-24 --trim all > calls.bam
- Operating system: Windows 10
- Hardware (CPUs, Memory, GPUs): Intel(R) Core(TM) i7-8700 CPU, 16 GB RAM, Intel(R) UHD Graphics 630 *AND* NVIDIA GeForce GT 730 (Driver version 473.78 and CUDA version 11.4)
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location (on device or networked drive - NFS, etc.):  on device
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): SQK-114-24, FLO-MIN114
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

<img width="959" alt="error message" src="https://github.com/nanoporetech/dorado/assets/50833645/1460486d-2ab4-4013-b4c8-a2f111b61d65">

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by HalfPhoton** [comment]
Hi @jadeaver,
Unfortunately Dorado does not support the GeForce GT 730 (Kepler) GPU architecture which is why you're seeing errors.

Kind regards,
Rich

**Comment by jadeaver** [comment]
Ah that would do it. Thank you!
