### ISSUE TITLE
Dorado Alignment circular sequences

### ISSUE THREAD

**Issue by Macdot3** [nanoporetech/dorado#712]
Hello everyone, 
I wanted to ask a question about alignment with Dorado. I'm analyzing circular mtDNA sequences and I was wondering if it's possible for Dorado to recognize such sequences as circular without any issues of read shifting at the end and beginning once aligned, or even worse, loss of information. It would be very helpful for us working with these sequences.                   Alternatively, is there a way to overcome this? Thank you very much for any advice.

**Comment by beppybeeps** [comment]
Hi,
I'm not aware of any aligner that handles circular sequences well but I work around the issue by copying the entire sequence and appending it to the end. This way a full length read can start from any point and always has somewhere to map continuously. It does make downstream analysis a bit more complicated though so I'd be happy to hear about a better option.
