### ISSUE TITLE
Command "conda install hcc::dorado" and error, "PackagesNotFoundError: The following packages are not available from current channels:"

### ISSUE THREAD

**Issue by HyojeenLee** [nanoporetech/dorado#713]
Hello, I am a M1 Mac book air user. 
Using conda environment, I made my environment name "Dorado", and started downloading "Dorado, version  0.4.2" from hcc like below. However confronted the error like the below. 
What should I do to overcome this error?

(Dorado) [~]$ conda install hcc::dorado
Channels:
 - defaults
 - hcc
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - hcc::dorado

Current channels:

  - defaults
  - https://conda.anaconda.org/hcc
  - https://repo.anaconda.com/pkgs/free

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by malton-ont** [comment]
Hi @HyojeenLee,

According to https://anaconda.org/hcc/dorado, the conda package `hcc::dorado` is only available for linux-x64. I'm not clear who is maintaining the conda package but I guess this needs to be updated to reflect the fact that dorado builds on mac and windows as well.

**Comment by tijyojwad** [comment]
Hi @HyojeenLee - that is not an official ONT channel. Our recommendation is to fetch the latest dorado binaries from GitHub - https://github.com/nanoporetech/dorado?tab=readme-ov-file#installation
