### ISSUE TITLE
Preprocessing of raw signal data

### ISSUE THREAD

**Issue by denisbeslic** [nanoporetech/dorado#715]
Hi,

I have a question regarding the preprocessing of the raw signal data. I was wondering if the raw signal data is just scaled or if you perform some form of additional normalization (per read) before model training / inference. 
The provided [k-mer models](https://github.com/nanoporetech/kmer_models/blob/master/dna_r10.4.1_e8.2_400bps/9mer_levels_v1.txt) are given as expected values (normalized), so I wanted to know if the basecalling process was done in a similar manner.

**Comment by tijyojwad** [comment]
Hi @denisbeslic - the dorado raw signal processing code can be found here - https://github.com/nanoporetech/dorado/blob/release-v0.6.0/dorado/read_pipeline/ScalerNode.cpp#L178
