### ISSUE TITLE
error building `v0.6.0`: dorado/splitter/myers.cpp

### ISSUE THREAD

**Issue by sklages** [nanoporetech/dorado#718]
Building crashes, make output attached. 
Linux, in-house developed, no build issues before until current release.
Can you help?

[log.v0.6.0-Release.log](https://github.com/nanoporetech/dorado/files/14848324/log.v0.6.0-Release.log)

**Comment by malton-ont** [comment]
Hi @sklages,

This looks like a bug in gcc12 - it appears not to be detecting that all dereferences of the `std::optional` are guarded by a call to `std::optional::has_value`. We haven't seen this issue as our toolchain uses gcc11. You have a few options:

1. Build with gcc11
2. Add `-Wno-maybe-uninitialized` to `cmake/Warnings.cmake:15` to disable that warning entirely
3. Edit the offending file `dorado/splitter/myers.cpp` to work around the issue
 
For option 3, replacing the optional with a plain type and guarding access with a bool appears to work.

You'll also need to add `#include <stdexcept>` into `dorado/demux/parse_custom_sequences.cpp` if you use gcc12.

We'll look to patch this in a future release.

**Comment by sklages** [comment]
@malton-ont - thanks for the information.

I seem to run into the same problem with `gcc11` (gcc (GCC) 11.1.0),
[log.v0.6.0-Release-gcc11.log](https://github.com/nanoporetech/dorado/files/14851106/log.v0.6.0-Release-gcc11.log)

.. when choosing (1). Maybe there is something I missed?

**Comment by malton-ont** [comment]
@sklages, apologies, I was thinking of a different project! I meant gcc9 there - specifically we use gcc-9.4.0.

**Comment by sklages** [comment]
@malton-ont -- yes, I now used `gcc (GCC) 9.3.0` and it worked just fine :-)

```
<..>
Finished building Dorado version 0.6.0+d67b2d30
```
