### ISSUE TITLE
--resume mode

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/dorado#72]
Hi
In case Dorado crashes during basecalling it would be convenient to have a - - resume option to avoid basecalling reads several times.

Best regards Rasmus

**Comment by olawa** [comment]
Hi,

this would indeed be good to have.  Also having an option to take a list of read id:s to either basecall or skip could be useful.

**Comment by billytcl** [comment]
+1 on the resume feature! It's really useful for HPC sessions that have a time limit.

**Comment by vellamike** [comment]
This feature unfortunately didn't make 0.3.0 bunt is definitely planned.

**Comment by tijyojwad** [comment]
> Also having an option to take a list of read id:s to either basecall or skip could be useful.

@olawa this particular feature is already available through the `--read-ids` option in dorado. This is of course not checkpointing, but could be useful in rerunning on a subset of the original dataset.

**Comment by tijyojwad** [comment]
Resume mode is now available for simplex in dorado v0.3.1. Details are available at https://github.com/nanoporetech/dorado#simplex-basecalling

**Comment by jdemeul** [comment]
would this be an option too for duplex mode? 
As this mode is a good bit slower than simplex, would be doubly good to have the `--resume` option there.

**Comment by avilella** [comment]
This is a great feature to have, it's `--resume-from my.bam` and outputs sam, which I then pipe into .fastq.gz myself. Thanks for implementing it.
