### ISSUE TITLE
Installing dorado

### ISSUE THREAD

**Issue by CHoeeghGuldberg** [nanoporetech/dorado#721]
# Issue Report

## Please describe the issue: 

I cannot get dorado installed correctly so that it will run. I keep getting the error "dorado: command not found".

## Steps to reproduce the issue:
 After downloading the .tar archive (dorado-0.6.0-linux-arm64.tar.gz) I unpacked the archive using: 

tar -xf dorado-0.6.0-linux-arm64.tar.gz

After that I tried to run: 

dorado -h 

However I get the error message "dorado: command not found". 

## Run environment:
- Dorado version: 0.6.0
- Dorado command: dorado -h
- Operating system: Linux
- Hardware (CPUs, Memory, GPUs):
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.): 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

(base) cguld@node1:~/barcodes/dorado$ dorado -v
dorado: command not found

**Comment by HalfPhoton** [comment]
@CHoeeghGuldberg,
Has dorado been added to your `$PATH`?
Can you try `./dorado -v` please?

Kind regards,
Rich

**Comment by malton-ont** [comment]
Hi @CHoeeghGuldberg,

The dorado executable is not included with guppy 6.5. If you want the latest dorado you should download the binary package as described in https://github.com/nanoporetech/dorado/blob/release-v0.6.0/README.md#installation

**Comment by CHoeeghGuldberg** [comment]
> @CHoeeghGuldberg, Has dorado been added to your `$PATH`? Can you try `./dorado -v` please?
> 
> Kind regards, Rich

Hi Rich, I tried what you suggested and this is what came up. 

(base) cguld@node1:~/barcodes/dorado/dorado-0.6.0-linux-arm64/bin$ ./dorado -v
bash: ./dorado: cannot execute binary file: Exec format error

**Comment by malton-ont** [comment]
@CHoeeghGuldberg,

You have downloaded the arm64 version - is that correct for your system? The error message suggest perhaps you need the x86-64 build.
