### ISSUE TITLE
No supported chemistry for Flowcell on 

### ISSUE THREAD

**Issue by osvatic** [nanoporetech/dorado#729]
I converted R9.4.1 fast5s to pod5s and am trying to generate a bam with modified base calls. 

I am using dorado v0.5.3+d9af343. The dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0 model seems to be the correct chemistry with modified base calls. 

I ran the following command:
```
dorado basecaller dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0 pod5/ --kit-name SQK-RBK110-96 --reference ref.fa.gz --min-qscore 15 --emit-moves --modified-bases 5mC_5hmC 5mCG_5hmCG > base_mods.bam
```
The error porduced:
```
[2024-04-04 14:17:34.907] [error] No supported chemistry for Flowcell:'FLO-PRO002', Kit:'SQK-RBK110-96' and Sampling Rate:4000
[2024-04-04 14:17:34.907] [error] Could not resolve chemistry from data
```

I have also tried specifying "sup" instead of a model.

What is the issue? Are modified base calls not supported for this version?

**Comment by HalfPhoton** [comment]
Hi @osvatic, 
Your chemistry isn't one recognised by Dorado for automatic selection-  you can overcome this by specifying a model **path**.  Note: Your also setting a modified bases model in the simplex model positional argument.

This can be done by downloading the simplex model first.
```
dorado download --model dna_r9.4.1_e8_sup@v3.3
dorado basecaller dna_r9.4.1_e8_sup@v3.3 pod5 --kit-name SQK-RBK110-96 --reference ref.fa.gz --min-qscore 15 --emit-moves --modified-bases 5mC_5hmC 5mCG_5hmCG > base_mods.bam
```
The modified bases models should be auto downloaded.

Kind regards,
Rich

**Comment by osvatic** [comment]
Thank you for the comment. 
I was able to get that to run with a single modified base. Trying to run both (5mCG and 5mCG_5hmCG) mentions that only 1 can be run at once because of the overlapping motif.
```
[2024-04-04 16:31:07.766] [info] > Creating basecall pipeline
[2024-04-04 16:31:07.854] [error] Following are incompatible modbase models. Please select only one of them to run:
/lisc/scratch/jmf/internal/Analyses_Jay/methylationtesting/models/dna_r9.4.1_e8_sup@v3.3_5mCG@v0.1 and /lisc/scratch/jmf/internal/Analyses_Jay/methylationtesting/models/dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0 have overlapping canonical motif: C
```
This error does not show up when running a similar command on R10.4.1 chemistry. Is there a way to run both at once or is this a limitation of earlier chemistry?

**Comment by HalfPhoton** [comment]
You only need the latter as `5mCG` motif is detected in `5mCG_5hmCG` along with `5hmCG`

**Comment by osvatic** [comment]
Thank you for the explanations.
