### ISSUE TITLE
dorado to output status like guppy

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/dorado#73]
Hi

It would be very nice if dorado posted something during the basecalling like guppy to keep track of progress instead of just when it is finished.

Guppy:

```
Found 1 input read file to process.
Init time: 6010 ms

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Dorado
dorado basecaller models/dna_r10.4.1_e8.2_400bps_sup@v4.0.0 pod5s/ > calls.sam
[2022-12-06 14:47:03.608] [info] > Creating basecall pipeline
[2022-12-06 14:51:46.040] [info] > Reads basecalled: 10000
[2022-12-06 14:51:46.040] [info] > Samples/s: 3.256044e+06
[2022-12-06 14:51:46.040] [info] > Finished
```
Best regards
Rasmus

**Comment by vellamike** [comment]
Hi @Kirk3gaard, this is [now done](https://github.com/nanoporetech/dorado/commit/a93ae2cbeb8ea325b009b3932e798ff007284ee6). It is available if you compile from source and will be included in the next Dorado release binary.
