### ISSUE TITLE
fastq encoding

### ISSUE THREAD

**Issue by Andreas-Bio** [nanoporetech/dorado#731]
# Issue Report

## Please describe the issue:

Is there a specific reason the fastq encoding changed?
Notepad++ tells me it is now UTF-16.
I am running into a lot of compatibility issues, especially with some R packages which can not take the encoding="" argument to the read function. Not sure when it changed, never had a problem in the past. 

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version: 0.6.0
- Dorado command: E:\ONT\dorado-0.6.0-win64\bin\dorado.exe basecaller E:\ONT\dorado-0.6.0-win64\bin\dna_r10.4.1_e8.2_400bps_sup@v4.3.0 "E:\ONT\RUN16 Georgia20\pod5_run2\pod5" --min-qscore 7 --emit-fastq --device cuda:all > "E:\ONT\RUN16 Georgia20\basecalled_run2.fastq"
- Operating system: Win 10
- Hardware (CPUs, Memory, GPUs): Nvidia 3070
- Source data type: pod5
- Source data location (on device or networked drive - NFS, etc.): local drive
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): not relevant

**Comment by vellamike** [comment]
Hi @Andreas-Bio,

Are you running your command in PowerShell? Also, are you certain that when you've run this in the past and seen it work it has been in exactly the same environment? This might be caused because Windows PowerShell uses the Unicode [UTF-16LE](https://wikipedia.org/wiki/UTF-16) encoding by default.

**Comment by Andreas-Bio** [comment]
Yeah you are right. It was because of the Power Shell. It should come with a warning because the fastq is incompetible with almost all R packages.
