### ISSUE TITLE
Combine modified bam files rather than re-basecalling

### ISSUE THREAD

**Issue by samuelmontgomery** [nanoporetech/dorado#732]
Hi, 

Just wondering if it is possible to combined multiple bam files where multiple models have been used to call modifications on the same reads?
I have basecalled my data using 5mC_5hmC and 6mA - but would like to add in the 4mC model from Rerio without re-basecalling with all three models (as just the two takes ~4 days to complete)
Is it possible to merge them after basecalling?

Cheers

**Comment by HalfPhoton** [comment]
Hi @samuelmontgomery,
I think you'll potentially run into issues with duplicate reads in the output. 
I'll ask the mods team if they have a recommendation as there maybe a way to merge mods tags assuming the canonical basecalls are identical.

**Comment by HalfPhoton** [comment]
After discussing this with the mods team merging the outputs from two modbase models sharing the same underlying base (C in this case) would invalidate the output.

**Comment by samuelmontgomery** [comment]
Thanks very much - as we're doing bacterial genomes, the 6mA and 4mC are obviously pretty important, but didn't want to miss out on any 5mC/5hmC
I will just run the 4mC_5mC and 6mA models in the future!
