### ISSUE TITLE
Dorado demultiplexing and demuxing for classification of barcoded reads

### ISSUE THREAD

**Issue by AMBL-CW** [nanoporetech/dorado#739]
Hello! I'm always using dorado 0.5.0 for analyzing ONT reads from bacterial genome on the Linux environment.

Currently, I am trying to demultiplex my barcoded genomic reads, which have 5 unique barcodes and they do not belong to any kit, just used SQK-LSK114 and Tn5 transposase-based tagmentation for sequencing library prep.

So I used the --barcode-arrangement and --barcode-sequences option. All barcodes are 27-mer long and flanked by the prefix "ACTGA" and suffix "AGATGTGTATAAGAGACA" as shown below:

ACTGANNNNNNNNNNNNNNNNNNNNNNNNNNNAGATGTGTATAAGAGACA

After basecalling, I'm still getting mostly unclassified bam file.

This is my command for basecalling and demultiplexing:

./dorado-0.6.0-linux-x64/bin/dorado basecaller --no-trim dna_r10.4.1_e8.2_400bps_sup@v4.3.0 --barcode-arrangement custom_barcode.toml --barcode-sequences custom_barcode.fasta /home/cw/S_aureus_gDNA/pod5/ > barcoded_gDNA_S_
aureus.bam

[info] > Creating basecall pipeline
[info] cuda:0 using chunk size 9996, batch size 896
[info] cuda:1 using chunk size 9996, batch size 896
[info] cuda:0 using chunk size 4998, batch size 1024
[info] cuda:1 using chunk size 4998, batch size 1024
[info] > Simplex reads basecalled: 150767
[info] > Simplex reads filtered: 17
[info] > Basecalled @ Samples/s: 2.262585e+07
[info] > 151098 reads demuxed @ classifications/s: 5.842856e+02
[info] > Finished

./dorado-0.6.0-linux-x64/bin/dorado demux --output-dir /home/cw/barcode --emit-summary --no-trim --barcode-arrangement custom_barcode.toml --barcode-sequences custom_barcode.fasta /home/cw/barcoded_gDNA_S_aureus.bam

[info] num input files: 1
[info] > starting barcode demuxing
[info] > Simplex reads basecalled: 151098
[info] > 151098 reads demuxed @ classifications/s: 2.012761e+04
[info] > finished barcode demuxing
[info] > generating summary file
[info] > summary file complete.

I have also attached the content of custom_barcode toml and fasta files.

custom_barcode.toml

[arrangement]
name = "custom_barcode"
kit = "BC"

mask1_front = "ACTGA"
mask1_rear = ""
mask2_front = ""
mask2_rear = "AGATGTGTATAAGAGACA"

# Barcode sequences
barcode1_pattern = "BC%02i"
barcode2_pattern = "BC%02i"
first_index = 1
last_index = 5

## Scoring options
[scoring]
min_soft_barcode_threshold = 0.2
min_hard_barcode_threshold = 0.2
min_soft_flank_threshold = 0.3
min_hard_flank_threshold = 0.3
min_barcode_score_dist = 0.1

custom_barcodes.fa
>BC01
CCAGTAGCGCCTTTCCAAGCAACCAGT
>BC02
GATATTAAGGACCAACACCAGCGCCTA
>BC03
AACATGCGGTCGGGTTCCACTTGATAG
>BC04
ACTAACCAGAGGAAACCGCCAGTGAGA
>BC05
TTGCGTTACTAGGAGCCAACTACAATG

I added 5 barcode sequence containing unique 27nt sequence to the custom_barcodes.fasta file.

I want to distinguish whole reads based on 5 unique barcode sequences. How can I do that? 

I would really appreciate it if you could provide some guidance.

**Comment by malton-ont** [comment]
Hi @AMBL-CW,

I think you've got your leading/trailing and mask1/2 mixed up - given the barcode you describe, what you currently have as `mask_2_rear` should be `mask_1_rear`, and you can leave out mask_2 entirely.
```
mask1_front = "ACTGA"
mask1_rear = "AGATGTGTATAAGAGACA"
```
See [here](https://github.com/nanoporetech/dorado/blob/v0.5.0/documentation/CustomBarcodes.md) for a description (and be aware that there are typos in that version of the document - your current variable names are correct!)

**Comment by AMBL-CW** [comment]
Thank you for reply, malton!

As your guidance, I edited my custom_barcode.toml as below:

mask1_front = "ACTGA"
mask1_rear = "AGATGTGTATAAGAGACA"

And, I updated dorado version 0.6.0 (latest release), however, there was an error.

./dorado-0.6.0-linux-x64/bin/dorado basecaller --no-trim dna_r10.4.1_e8.2_400bps_sup@v4.3.0 --barcode-arrangement custom_barcode.toml --barcode-sequences custom_barcode.fasta /home/cw/S_aureus_gDNA/pod5/ > barcoded_gDNA_S_aureus.bam

[info] Running: "basecaller" "--no-trim" "dna_r10.4.1_e8.2_400bps_sup@v4.3.0" "--barcode-arrangement" "custom_barcode.toml" "--barcode-sequences" "custom_barcode.fasta" "/home/cw/S_aureus_gDNA/pod5/"
[info] > Creating basecall pipeline
[info] cuda:1 using chunk size 9996, batch size 896
[info] cuda:0 using chunk size 9996, batch size 896
[info] cuda:0 using chunk size 4998, batch size 1024
[info] cuda:1 using chunk size 4998, batch size 1856
**[error] For double ended barcodes, mask2_front mask2_rear and barcode2_pattern must all be set.**

For this reason, I tried creating a new custom_barcode.toml file as below, and proceeded with the same command, but there are still too many unclassified BAMs.

mask1_front = "ACTGA"
mask1_rear = "AGATGTGTATAAGAGACA"
mask2_front = "ACTGA"
mask2_rear = "AGATGTGTATAAGAGACA"

**Comment by malton-ont** [comment]
Hi @AMBL-CW,

If you don't have barcodes at both ends, remove the `mask2_front`, `mask2_rear`  and `barcode2_pattern` entries - these are not required, but if one is present then all must be present.

Note that if you have updated to dorado 0.6.0 then the barcoding scoring parameters have changed - please see the latest version of the [CustomBarcode documentation](https://github.com/nanoporetech/dorado/blob/release-v0.6.0/documentation/CustomBarcodes.md).

**Comment by tijyojwad** [comment]
Hi @AMBL-CW were you able to get past the error?

**Comment by tijyojwad** [comment]
Hi @AMBL-CW - closing since we haven't heard from you. Please re-open if you have further questions.
