### ISSUE TITLE
c10::OutOfMemoryError on simplex basecalling, dorado v0.6.0

### ISSUE THREAD

**Issue by cocvincent** [nanoporetech/dorado#740]
Hello

I'm having a memory problem with dorado 0.6.0 that looks like the one I had here: #658 
The latter could have been solved by splitting the pod5 dataset into 2, and running dorado separately on the 2 dataset subsets, but not with dorado 0.6.0.
I tried splitting the dataset into 4 and then 8, basecalling 265 pod5 files at a time, without success.
This time the output bam file is empty.

I'm working with GPU A100/V100 on a compute cluster. I've allocated the maximum memory available on the cluster (160G). 

Here is the code: 
![fonction_erreur_v0 6 0_11-04-24](https://github.com/nanoporetech/dorado/assets/161732564/8d17a128-0c8e-4239-b1e3-b1650937db43)
![code_erreur_v0 6 0-11-04-24](https://github.com/nanoporetech/dorado/assets/161732564/37305c5e-617b-44d8-9265-345dda821c96)

Thank you for your time.

**Comment by HalfPhoton** [comment]
@cocvincent, 
Could you please try reducing the `--batchsize` to say `1024` or  `896`. The sweet-spot for stability / performance will depend on the GPU V100/A100. 
This should improve stability regarding  CUDA OoM.

Kind regards,
Rich

**Comment by tijyojwad** [comment]
Hi @kubek78 - the 2 chunks sizes and 2 batch sizes are an internal detail - they are there to deal with differently sizes reads.

**Comment by cocvincent** [comment]
Hello, sorry for not replying earlier. It worked well reducing batch size.
Thanks !
