### ISSUE TITLE
Issue about merge multiple pod5 files

### ISSUE THREAD

**Issue by xiangpingyu** [nanoporetech/dorado#743]
Dear developers,

Initially, we obtain multiple pod5 files from a single run. Should we merge these files into one pod5 file before proceeding with the Dorado analysis? For example, would we use the command $ dorado basecaller sup m6A merged.pod5 > calls.bam to perform this analysis? Or Could we use the command $ dorado basecaller sup m6A ./ > calls.bam,  without the merge process.

Thank you for your guidance.
Sophia

**Comment by tijyojwad** [comment]
You can run without merging as well. You'll need to add `-r` (for recursive) to the cmdline.

i.e. `$ dorado basecaller sup m6A ./ -r > calls.bam`

provided all yours file are in `./`

**Comment by xiangpingyu** [comment]
@tijyojwad thank you! if i want to use GPU but not CPU to run this command, which parameter do I need to add?

Best,
Sophia

**Comment by tijyojwad** [comment]
Hi @xiangpingyu if you have an NVIDIA GPU dorado should by default run on it. What do you see when you run `nvidia-smi`?

In general you can choose the gpu you want to use with `-x "cuda:0"` to run it on the first GPU on nvidia-smi list

**Comment by xiangpingyu** [comment]
@tijyojwad I'm currently running the basecaller with the -x "cuda:0" option because the initial execution seemed very slow. It appears that overnight, it has processed only about 3% of the data. Is this a normal processing speed? What speed should I typically expect when running the basecaller? thank you!

**Comment by tijyojwad** [comment]
How much data do you have (e.g. size of POD5 dataset, or number of reads/average read length), and what GPU are you using? Is your data on a local disk or are you reading over a network drive? Do you have multiple GPUs?

**Comment by xiangpingyu** [comment]
@tijyojwad  
1) the size of one dataset is about 80.0GB, and it's stored on a local disk; 
2) when utilizing the -x "cuda:0", and monitoring through the task manager, the following image is observed.
<img width="931" alt="image" src="https://github.com/nanoporetech/dorado/assets/35753770/b4a6a276-9269-42f3-a7b9-676e621c3606">
<img width="926" alt="image" src="https://github.com/nanoporetech/dorado/assets/35753770/20ab002c-1cd5-45d6-8b98-9d479d0439f4">

thank you!
