### ISSUE TITLE
Values of the mean_qscore_template field in sequencing_summary.txt files are integers instead of floats

### ISSUE THREAD

**Issue by jourdren** [nanoporetech/dorado#747]
# Issue Report

## Please describe the issue:

Values of the **mean_qscore_template** field in `sequencing_summary.txt`  files are integers while floats are expected for means like with Guppy.

With integers instead of floats, PHRED score distribution may look not continuous with some QC tools like ToulligQC (I am one of the developer of ToulligQC) as you can see in the following screenshot.
![Screenshot](https://github.com/nanoporetech/dorado/assets/3381031/e9ebc1c6-7c77-48aa-8c3a-5f62e2af39a7)

## Steps to reproduce the issue:

Just launch the `dorado summary` command.

## Run environment:
- Dorado version: 0.6.0
- Dorado command: dorado summary mybam.bam
- Operating system: Linux

**Comment by wzboy1984** [comment]
I encounter the same problem in drawing mean qscore distribution.
In dorado source code: dorado/read_pipeline/ReadPipeline.cpp
In function: ReadCommon::generate_read_tags
    int qs = static_cast<int>(std::round(calculate_mean_qscore()));
    bam_aux_append(aln, "qs", 'i', sizeof(qs), (uint8_t *)&qs);

It seemed that mean qscore were transformed to integer by std::round before writting to bam.

**Comment by HalfPhoton** [comment]
This has been resolved in Dorado [0.7.0](https://github.com/nanoporetech/dorado/releases/tag/v0.7.0). 

Happy basecalling!
