### ISSUE TITLE
M1 Max -b 0 doesn’t seem to pick actual optimal batch size

### ISSUE THREAD

**Issue by itslittman** [nanoporetech/dorado#75]
When I manually set a batch size of -b 528, my SUP RNA basecalling run goes around 1.5x as fast as when I used the default batch size. How does -b 0 choose “optimal” batch size and why might it not pick the best one?

**Comment by iiSeymour** [comment]
Currently `-b 0` is optimal for nvidia devices and we will have this improved on metal devices soon.

**Comment by iiSeymour** [comment]
@itslittman the optimal batch size detection is now improved in the latest release.

**Comment by itslittman** [comment]
@iiSeymour I’m trying the RNA SUP model now with the new precompiled binary. The performance seems good with -b 480 but the default -b 0 still seems to cause problems. When I tried the same input with the default, it processed 100 reads and seemed to stall/crash. I mean it’s definitely not a big deal, it’s not too difficult to type -b. It is interesting that it keeps causing issues though.

Noah
