### ISSUE TITLE
Remora model support

### ISSUE THREAD

**Issue by jorisbalc** [nanoporetech/dorado#750]
Dear dorado team,

Are custom remora models no longer supporter and can only be run via bonito? Will they be supported again in future versions? Thank you in advance!

Edit: I understand that bonito is just as capable, however dorado is a few thousand times faster on my machine.

**Comment by marcus1487** [comment]
Hi @jorisbalc , custom Remora models are still supported in Dorado. There are some (not well documented) cases where a model will not be transferrable. These include changes to the neural network architecture, models targeted at multiple motifs as well as some other options available in Remora, but only on research models. If you have a specific model that is incompatible there may be a workaround. Could you expand on any issues you are having with exporting a Remora model for use in Dorado?

**Comment by jorisbalc** [comment]
Thanks for the reply marcus and thank you for reassuring. I've managed to pin down the problem to a simple typo I made while experimenting, which I managed to miss multiple times...
