### ISSUE TITLE
What does `--emit-moves` in the basecaller do?

### ISSUE THREAD

**Issue by skranz0** [nanoporetech/dorado#751]
# Issue Report

I am basecalling Nanopore data for methylation calling with [DeepMod2](https://github.com/WGLab/DeepMod2) which tells me to use the `--emit-moves` flag with dorado aligner. I'm struggling to find what this actually does. In the list output by `dorado aligner --help` the according field is just blank.

Can someone help me understand what the moves table is?

## Run environment:
- Dorado version: 0.6.0
- Dorado command: 
- Operating system: Ubuntu 22.04
- Source data type: POD5

**Comment by HalfPhoton** [comment]
Please see https://github.com/nanoporetech/dorado/issues/110 which discussed the move table definition.

Kind regards,
Rich

**Comment by skranz0** [comment]
That was very helpful, thanks! I would like to have a short explanation with `dorado base caller --help` instead of just a blank line nonetheless.
