### ISSUE TITLE
How to live basecall with methylation but output be uBAM

### ISSUE THREAD

**Issue by ethan-mcq** [nanoporetech/dorado#755]
# Issue Report

## Please describe the issue:

When running the Dorado executable, running basecalling with methylation works great; however, when trying to live basecall with MinKNOW UI and running with live basecalling and modified bases ON, we receive fastq files which do not contain MM and ML information. We specifically do not want to align these sequences either. As such, we are looking for live basecalling solutions and keeping these tags by creating a uBAM or similar. Does anyone have any ideas?

## Steps to reproduce the issue:
MinKNOW 24.02.10

**Comment by malton-ont** [comment]
Hi @ethan-mcq,

MinKNOW 24.02.10 should automatically generate BAM output (possibly in addition to fastq) when modified basecalling is selected. Can you check your file output settings? They should look something like this (note the BAM setting):
![data_saved_as](https://github.com/nanoporetech/dorado/assets/102533216/32da97d8-cd94-4e88-b808-fb3f07450855)
![basecall_output_options](https://github.com/nanoporetech/dorado/assets/102533216/fd7b393f-c69d-41c1-a105-9ee7e68cfbb9)
