### ISSUE TITLE
Is it possible to set demux to use only barcodes present in  sample sheet ? 

### ISSUE THREAD

**Issue by olawa** [nanoporetech/dorado#756]
I am trying demux with sample sheet and get the following error when only the barcodes in use are included:

 what():  Row in sample sheet file samplesheet.txt has incorrect number of entries

It took a while to figure out that all 12 barcodes need to be present in the sheet. Perhaps you could add a few example sheets to the repo.

What I would like to be able to do is:
1. demux to use the kit specified in sample sheet 
2. only classify reads present in the run (ideally with a tag specifying if it was found on both ends)
3. write reads with more than one of the specified barcodes to a separate file (unless demux can split it on internal adaptors) to be able to identify ligation chimeras
4. option to only split on barcode (if more than one flowcell was used)

Is any of this possible with the current demux?

**Comment by malton-ont** [comment]
Hi @olawa,

That error indicates that one or more of the rows had a different number of entries to the number of column headings. Samples sheets should absolutely work with only a subset of the barcodes from the kit. Note that a sample sheet should be defined with comma-separated variables, and empty columns must still be included. See the documentation [here](https://github.com/nanoporetech/dorado/blob/release-v0.6.0/documentation/SampleSheets.md) for more information.

**Comment by olawa** [comment]
Hi @malton-ont @tijyojwad , thanks for the clarification. I got it to work as intended with dorado 0.6 now, could have been an extra comma in the header from converting tabs. 

>only classify reads present in the run

I meant barcodes. I am sequencing short reads with PBC96, they are amplified so should then have barcodes on both ends. --barcode-both-ends gives much lower classification rate. I am guessing it could be improved if one could exclude only reads were two different barcodes from the list is found, assuming the issue is either poor basecalling at the ends or chimeric ligation products.

Is the dorado split during basecall supposed to split on internal barcode/primers or is it just able to split Minknow chimeras?

One example here where a female sample has alignment to chrY from what appears to be a ligation concatemer. If I have to use guppy (or perhaps pychopper) to split on internal primers that is fine but I cant't find any documantation on it.

<img width="1204" alt="Skärmavbild 2024-04-23 kl  11 48 10" src="https://github.com/nanoporetech/dorado/assets/24351867/13f38f12-4025-4ee3-9586-577baee3bafd">

**Comment by tijyojwad** [comment]
> Is the dorado split during basecall supposed to split on internal barcode/primers or is it just able to split Minknow chimeras?

It doesn't split on internal barcodes, just on sequencing adapters. So it'll catch chimeras, but not ligation concatemers.

I believe guppy did have an option to split on internal adapters. We can look into adding that to dorado in a subsequent release.

**Comment by malton-ont** [comment]
Demux not respecting limiting barcodes via sample sheet raised again in https://github.com/nanoporetech/dorado/issues/1162

**Comment by malton-ont** [comment]
Thanks for your patience. Dorado demux in 0.9.0 now properly respects the sample sheet restriction on available barcodes.
