### ISSUE TITLE
Error! unable to open SAM/BAM/CRAM file at /gpfs2/scratch/mmolla/Z/

### ISSUE THREAD

**Issue by habibsaky** [nanoporetech/dorado#757]
# Issue Report

## Please describe the issue:

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version:
- Dorado command:
- Operating system:
- Hardware (CPUs, Memory, GPUs):
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.): 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by habibsaky** [comment]
(base) [mmolla@dg-gpunode05 ~]$ modkit pileup /gpfs2/scratch/mmolla/Z/ output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log
> Error! unable to open SAM/BAM/CRAM file at /gpfs2/scratch/mmolla/Z/
(base) [mmolla@dg-gpunode05 ~]$

**Comment by malton-ont** [comment]
Hi @habibsaky,

Modkit is a separate project, but from a quick look I believe it requires a single bam file as an argument, not a folder. You'll get better answers on this over at [their github](https://github.com/nanoporetech/modkit) though.

**Comment by habibsaky** [comment]
yes when I try to run it on Modkit it said..Error! unable to open .. Can you please help me to solve it

(base) [mmolla@dg-gpunode05 ~]$ modkit pileup /gpfs2/scratch/mmolla/Z/ /gpfs2/scratch/mmolla/HL3/> Error! unable to open SAM/BAM/CRAM file at /gpfs2/scratch/mmolla/Z/

**Comment by habibsaky** [comment]
this folder has bam file and it should automatically catch it .
base) [mmolla@dg-gpunode05 ~]$ modkit pileup /gpfs2/scratch/mmolla/Z/calls.bam /gpfs2/scratch/mmolla/HL3/
> Error! unable to open SAM/BAM/CRAM index for /gpfs2/scratch/mmolla/Z/calls.bam; please create an index
(base) [mmolla@dg-gpunode05 ~]$

**Comment by HalfPhoton** [comment]
@habibsaky,
I think @malton-ont is saying that the input is a **file** and not a **directory**.
Modkit does not accept a directory as an input.
```bash
modkit pileup /gpfs2/scratch/mmolla/Z/YOUR_FILE.bam output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log
```

Make sure to replace `YOUR_FILE.bam` with a the name of the bam file in your `/gpfs2/scratch/mmolla/Z/` directory.

Kind regards,
Rich

**Comment by habibsaky** [comment]
yes, there have bam file but why it shows...


(base) [mmolla@dg-gpunode05 ~]$ modkit pileup /gpfs2/scratch/mmolla/Z/calls.bam output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log
> Error! unable to open SAM/BAM/CRAM index for /gpfs2/scratch/mmolla/Z/calls.bam; please create an index
(base) [mmolla@dg-gpunode05 ~]$

**Comment by HalfPhoton** [comment]
You have to create a index file first.

Please refer to the documentation of [samtools index](https://www.htslib.org/doc/samtools-index.html) for more instructions, but you'll need to run something similar to 
```bash
samtools index calls.bam
```

**Comment by habibsaky** [comment]
yes i did but i got error like this--
(base) [mmolla@dg-gpunode05 ~]$ modkit pileup /gpfs2/scratch/mmolla/Z/calls.bam output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log
> Error! unable to open SAM/BAM/CRAM index for /gpfs2/scratch/mmolla/Z/calls.bam; please create an index
(base) [mmolla@dg-gpunode05 ~]$ modkit pileup samtools index /gpfs2/scratch/mmolla/Z/calls.bam output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log
error: unexpected argument '/gpfs2/scratch/mmolla/Z/calls.bam' found

Usage: modkit pileup [OPTIONS] <IN_BAM> <OUT_BED>

For more information, try '--help'.
(base) [mmolla@dg-gpunode05 ~]$

**Comment by malton-ont** [comment]
@habibsaky,

You need to sort the bam file. Then index the bam file. Then you can call the file via modkit.
```
samtools sort calls.bam > calls_sorted.bam
samtools index calls_sorted.bam
modkit pileup calls_sorted.bam pileup.bed
```

This is a modkit issue, so I'm going to close this one. If you have any further issues with this, please raise them on the modkit github.
