### ISSUE TITLE
Can't open dorado (Closes immediately) 

### ISSUE THREAD

**Issue by Ceres90** [nanoporetech/dorado#758]
I am probably doing something dumb but after I download and extract the dorado folder , when I try to click on the dorado application it opens for half a second and then immediately closes (Not enough time to see an error message or anything useful) 

I downloaded the version for windows I have an RTX3070  and a AMD Ryzen 9 5900

Any advice? thanks!

**Comment by malton-ont** [comment]
Hi @Ceres90,

Dorado is a command line application, not a GUI. You will need to run it in a terminal (cmd, gitbash, Powershell). See [the docs](https://github.com/nanoporetech/dorado?tab=readme-ov-file#running) for more information.

**Comment by Ceres90** [comment]
lol thanks thought it was something stupid
