### ISSUE TITLE
terminate called without an active exceptions

### ISSUE THREAD

**Issue by selmapichot** [nanoporetech/dorado#764]
Hi 
I am having this error message in the middle of a basecall + alignment process : terminate called without an active exceptions<02m:51s] ./alignment_t1_gr38.sh: line 6: 1074057 Aborted. 

Any advice on what might have caused this ? and how to work around it ? Many thanks
All the best,
Selma.

**Comment by HalfPhoton** [comment]
@selmapichot, please complete the [issue template](https://github.com/nanoporetech/dorado/issues/new?assignees=&labels=&projects=&template=dorado-issue-template.md&title=).

**Comment by HalfPhoton** [comment]
No response from OP - Please re-open issue with a completed template
