### ISSUE TITLE
How to apply the 5K 6mA model under a 4K data sampling frequency?

### ISSUE THREAD

**Issue by LuckyJao** [nanoporetech/dorado#771]
# Issue Report
The MinION MK1C software I was using at the time did not have an upgrade, and all the R10 chips used resulted in 4K sampling rate data. So what should I do if I can't use the latest 6mA model now? I want to use the 6mA model，but it is 5k.

**Comment by vellamike** [comment]
Hello @LuckyJao ,

If you want to detect 6mA data you will need 5kHZ data. Unfortunately there is no easy solution for this.

Mike
