### ISSUE TITLE
Install error in M1 mac

### ISSUE THREAD

**Issue by junjunxy** [nanoporetech/dorado#774]
**# Issue Report**

Problem at 

cmake --build cmake-build --config Release -j

**## Please describe the issue:**

[100%] Built target dorado_tests
Checking linked libs...
	/opt/homebrew/opt/libaec/lib/libsz.2.dylib (compatibility version 2.0.0, current version 2.0.1)
make[2]: *** [bin/dorado] Error 1
make[2]: *** Deleting file `bin/dorado'
make[1]: *** [CMakeFiles/dorado.dir/all] Error 2
make: *** [all] Error 2

***Please provide a clear and concise description of the issue you are seeing and the result you expect.***

Hi, I am struggling at building dorado in M1 mac.
I had installed autoconf 2.69 and followed instruction, but error arose at the end of the building process. 
I have looked into the other issues, but could not find the similar issues. 
could you help me to solve this issue? 

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

This is the spec of computer and version of cmake

% sw_vers
ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83

% cmake --version
cmake version 3.29.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).

%which cmake
/opt/homebrew/bin/cmake

% Model ientifier: M1 Mac mini, 2020
Chip Apple M1
Memory 16 GB

## Run environment:
- Dorado version:
- Dorado command:
- Operating system:
- Hardware (CPUs, Memory, GPUs):
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.): 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by malton-ont** [comment]
Hi @junjunxy,

The dorado build should use a static version of `libhdf5.a` that is pulled from our CDN. This looks like you've picked up a shared library from homebrew (an error that we catch as of v0.6.1). You can avoid this by simply uninstalling hdf5 and libaec from your brew installation (assuming they're not required for anything else):
```
brew uninstall hdf5 libaec
```

**Comment by junjunxy** [comment]
Hi @malton-ont 

dorado is successfully installed. 
Thank you so much :)
