### ISSUE TITLE
Call standalone Dorado from minKNOW installation

### ISSUE THREAD

**Issue by mgperry** [nanoporetech/dorado#778]
# Issue Report

## Please describe the issue:

Hi, I was wondering if it is possible to access the standalone dorado executable using just the minKNOW installation? ie without having to install dorado twice on the same machine. I can't find the binary anywhere in the `/opt/ont/` folder.

Apologies if this is the wrong place, I can't find a separate repository for `dorado_basecall_server`.

## Steps to reproduce the issue:

Fresh install of minKNOW using instructions online for `apt`.

## Run environment:

minKNOW:
Package: minknow-core-minion-nc
Version: 5.9.7

Running on Ubuntu 22.04

**Comment by malton-ont** [comment]
Hi @mgperry,

The standalone dorado executable is not included in the minknow 5.9 installation. MinKNOW performs all basecalling via the dorado_basecall_server. It is safe to install the standalone package separately, but you will need to run it directly from the command line
