### ISSUE TITLE
samplesheet.csv contains invalid column ﻿experiment_id

### ISSUE THREAD

**Issue by mbacino** [nanoporetech/dorado#781]
I have tried the sample sheet in multiple formats:

experiment_id,kit ,barcode
hit,SQK-RBK114-96,barcode01

flow_cell_product_code,kit,sample_id,experiment_id,barcode,alias
FLO-MIN114,SQK-RBK114-96,hit ,04_04_24,barcode01,A1

**Comment by HalfPhoton** [comment]
@mbacino, 
Please complete the issue template.

Does your sample sheet comform to the [specification](https://github.com/nanoporetech/dorado/blob/release-v0.6/documentation/SampleSheets.md#sample-sheet-specification)?

**Comment by HalfPhoton** [comment]
Specifically:

> At a minimum a sample sheet must contain kit, experiment_id and one of position_id or flow_cell_id. All rows in a sample sheet must contain the same experiment_id.

**Comment by mbacino** [comment]
I have tried that and get an error.  I have a log of over 10 failed runs where I have made slight changes to the sample sheet.

best, Margôt
Margôt Bacino
PhD Candidate
School of Dentistry, Oral and Craniofacial Sciences
University of California, San Francisco
Pronouns: she, her, hers

________________________________

**Comment by malton-ont** [comment]
Closing, duplicate of #782
