### ISSUE TITLE
I have failed to install pod5

### ISSUE THREAD

**Issue by Sekuwanda** [nanoporetech/dorado#785]
# Issue Report

## Please describe the issue:

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version:
- Dorado command:
- Operating system:
- Hardware (CPUs, Memory, GPUs):
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.): 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by Sekuwanda** [comment]
ERROR: Could not find a version that satisfies the requirement pod5 (from versions: none)
ERROR: No matching distribution found for pod5

**Comment by malton-ont** [comment]
Hi @Sekuwanda,

You appear to be trying to install the pod5 python package. This is not a dorado issue, please raise it at https://github.com/nanoporetech/pod5-file-format/issues
