### ISSUE TITLE
Support for Standalone 5mC and/or 5mCG in Basecalling Model Version 4.3.0

### ISSUE THREAD

**Issue by wietingj** [nanoporetech/dorado#788]
Hello everyone, 

as of basecalling model version 4.3.0, only 5mC_5hmC or 5mCG_5hmCG modified bases are supported, not 5mC or 5mCG alone. This leads to problems in the downstream analysis, especially in the statistical evaluation of differential methylation, as 5mC and 5hmC are then combined into one count. modkit (recommended by Oxford Nanopore) addresses this issue in its limitations (https://nanoporetech.github.io/modkit/limitations.html), but the same problem exists in e.g. NanoMethViz / DSS etc. as well. 

As far as I know, there is currently no option for separate statistical evaluation of the respective modifiers from a combined 5mC_5hmC modbam file, so it would be desirable if standalone 5mC could also be supported in the current model versions. Or is there an option I am missing?

Thanks for your feedback.

**Comment by tijyojwad** [comment]
Hi @wietingj - thank you for the question. I think this is better suited for the https://github.com/nanoporetech/remora/issues repo. Can you post it there?
