### ISSUE TITLE
pod5 files in multiple directories

### ISSUE THREAD

**Issue by lzhangLIH** [nanoporetech/dorado#789]
I wondered if dorado can do basecalling on pod5s in multiple directories. Thank you!

**Comment by vellamike** [comment]
Hi @lzhangLIH , if you use the `-r` flag in Dorado it will recursively basecall every pod5 in the directory tree. Is this what you need?

**Comment by HalfPhoton** [comment]
You can use the `-r` option after arranging a new directory with all the subdirectories symbolically linked.

```bash
mkdir all_data
ln -s /path/to/pod5_dir_1 all_data/
ln -s /path/to/pod5_dir_2 all_data/
...

dorado basecaller $model all_data/ -r ...
```

**Comment by lzhangLIH** [comment]
Hi, it is exactly what I need. I missed this flag. Thank you!

**Comment by shenker** [comment]
@HalfPhoton I tried exactly this and it did not work with dorado 0.7.2.

```
mkdir all_pod5
ln -s $PWD/../20240703_1120_3B_PAW62130_860ce00c/pod5 all_pod5/pod5.1
ln -s $PWD/../20240708_1038_3B_PAW62130_495aac59/pod5 all_pod5/pod5.2
ls all_pod5/*/*.pod5 # lists lots of pod5 files
dorado basecaller -r dna_r10.4.1_e8.2_400bps_sup@v5.0.0 all_pod5/ > simplex.bam
```
terminates with
```
[2024-07-11 11:39:43.545] [info] Running: "basecaller" "dna_r10.4.1_e8.2_400bps_sup@v5.0.0" "all_pod5/" "-r"
[2024-07-11 11:39:44.227] [info] > Creating basecall pipeline
[2024-07-11 11:39:44.228] [error] No POD5 or FAST5 data found in path: all_pod5/
```

**Comment by HalfPhoton** [comment]
@shenker 
Just checking that your staged symlinks don't have file extensions like `.N` (e.g. `.pod5.1`) this is what you show in your examples.

Kind regards,
Rich
