### ISSUE TITLE
poly-A estimation and adapter trimming on direct RNAseq data

### ISSUE THREAD

**Issue by lzhangLIH** [nanoporetech/dorado#790]
# Issue Report

## Please describe the issue:

I want to estimate poly-A during basecalling for direct RNA-seq data and have bam file with adapter-trimmed reads as output. But using option --estimate-poly-a disabled the trimming and the RNA adapter cannot be trimmed post-basecalling using dorado trim. Do you have a solution to avoid running twice dorado basecaller to have poly-A estimation and trimmed reads in bam file?

## Run environment:
- Dorado version: 0.6.0+7a6ab9a
- Dorado command: dorado basecaller --min-qscore 7 --estimate-poly-a sup,m6A_DRACH $pod5_file --reference $reference > $out_file
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5

**Comment by tijyojwad** [comment]
Hi @lzhangLIH - yes we are planning to enable this for the next release.

**Comment by tijyojwad** [comment]
Hi @lzhangLIH - this is now available in dorado v0.7.0 onwards, and is the default mode of operation (i.e. adapters are trimmed)
