### ISSUE TITLE
demultiplex

### ISSUE THREAD

**Issue by Sekuwanda** [nanoporetech/dorado#791]
# Issue Report

## Please describe the issue:

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version:
- Dorado command:
- Operating system:
- Hardware (CPUs, Memory, GPUs):
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.): 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by Sekuwanda** [comment]
How do you de multiplex duplex call in dorado?

Thank you

**Comment by tijyojwad** [comment]
Hello @Sekuwanda - `dorado duplex` currently doesn't support barcode demultiplexing. However, there are a couple of discussion on GitHub where alternative methods have been proposed. You can have a look at https://github.com/nanoporetech/dorado/issues/600 and https://github.com/nanoporetech/dorado/issues/522

**Comment by tijyojwad** [comment]
Closing as duplicate. You can subscribe to one of those tickets so that you're automatically informed of any updates.

**Comment by Sekuwanda** [comment]
Thank you @tijyojwad
