### ISSUE TITLE
Question: BAM vs FASTQ basecalling outputs

### ISSUE THREAD

**Issue by damioresegun** [nanoporetech/dorado#792]
Hi, I'm trying out v0.6.0 as part of making a cDNA transcript detection pipeline. I'm roughly following the wf-transcriptome pipeline. Due to the data being multiplexed, I am thinking that I need to use the "--no-trim" option to preserve the primers I will need for pychopper downstream. 
I've currently opted to emit FASTQs from the basecalling and demultiplexing steps. I know you recommend using BAMs as outputs and I was wondering what you see as the pros of emitting BAMs in contrast to FASTQs. Additionally, what information is being preserved in FASTQ outputs that are present in BAMs. This is because one of the messages emitted to stdout is "FASTQ output is not recommended as not all data can be preserved."

Thanks!

**Comment by tijyojwad** [comment]
> I need to use the "--no-trim" option to preserve the primers I will need for pychopper downstream

yes that's correct

>  the pros of emitting BAMs in contrast to FASTQs

The BAM files contain a lot more metadata per read and for the run itself. e.g. BAM records track methylation information (if you requested mod base calling), barcode information, signal trimming and transformation, alignment information, etc. When you go to FASTQ, none of that is retained per record other than the read group info, experiment start time and what GPU was used to run basecalling.

**Comment by tijyojwad** [comment]
`dorado demux` uses the `BC:Z` tag in the BAM records to split after classification, so currently that doesn't work with fastqs.

**Comment by damioresegun** [comment]
Okay great, thanks! I'll stick with generating BAMs and converting it to fastqs then! I'll have to update 0.6.1 to make sure the unclassified/samtools bug doesn't affect me downstream.

Closing this for now. :)
