### ISSUE TITLE
Basecaller with --modified-bases-models option

### ISSUE THREAD

**Issue by wtulle** [nanoporetech/dorado#793]
# Issue Report

## Please describe the issue:

I'm tryng to run basecaller with --modified-bases-models option. 
But I keep getting this error: [error] 1 argument(s) expected. 0 provided

## Steps to reproduce the issue:

Download the models dna_r9.4.1_e8_sup@v3.3 and dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0
Run: 
dorado basecaller --modified-bases-models ~/apps/dorado-0.6.1-linux-x64/models/dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0 -x cpu ~/apps/dorado-0.6.1-linux-x64/models/dna_r9.4.1_e8_sup@v3.3 ./myFile.pod5 > ./myFile.bam

Thanks!!

Also tried: 
dorado basecaller ~/apps/dorado-0.6.1-linux-x64/models/dna_r9.4.1_e8_sup@v3.3 ./myFile.pod5 -x cpu -modified-bases-models ~/apps/dorado-0.6.1-linux-x64/models/dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0 > ./myFile.bam

Same error:
[error] 1 argument(s) expected. 0 provided

## Run environment:
- Dorado version: dorado-0.6.1
- Dorado command: dorado basecaller
- Operating system: Ubuntu 20.04
- Hardware (CPUs, Memory, GPUs): AMD EPYC 7452 32-Core Processor, 512GB, no GPU
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location (on device or networked drive - NFS, etc.): on device
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

**Comment by tijyojwad** [comment]
Your second command should work, but it looks like it's missing a `-` in the modified-bases-models option. The text above says `-modified-bases-models` whereas it should be `--modified-bases-models`. Can you try that? i.e.

```
dorado basecaller ~/apps/dorado-0.6.1-linux-x64/models/dna_r9.4.1_e8_sup@v3.3 ./myFile.pod5 -x cpu --modified-bases-models ~/apps/dorado-0.6.1-linux-x64/models/dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0 > ./myFile.bam
```

**Comment by wtulle** [comment]
Hi, you are right! My mistake. Thank you!
