### ISSUE TITLE
CUDA device requested but no devices found

### ISSUE THREAD

**Issue by mpizzagalli777** [nanoporetech/dorado#794]
# Issue Report

## Please describe the issue:

Hi, I just installed Dorado on my workstation. I am running into trouble having it run successfully due to an unknown CUDA error. I ahve been unable to find a solution to this issue in other posts. Running nvidia-smi gives the following results. I am aware that we do not have the A100, but I read that the A6000 should work as well (although it might be a little slower). 
![NVIDIA-smi](https://github.com/nanoporetech/dorado/assets/154617296/e454286f-a243-4031-aa57-6ce8b28de203)

Here is the output of ldd dorado 
![ldd_dorado](https://github.com/nanoporetech/dorado/assets/154617296/0c5c3bfd-ac50-4a20-b5a1-1b451ef532c7)

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version: 0.6.1
- Dorado command: dorado basecaller hac pod5/ > ./basecalling/GB2_p22_dorado_hac.bam
- Operating system: Linux
- Hardware (CPUs, Memory, GPUs):
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location (on device or networked drive - NFS, etc.): on device

Please let me know if there is any other information that might be useful.

**Comment by tijyojwad** [comment]
Hi @mpizzagalli777 - are you able to run any other CUDA application? Can you try to run the CUDA samples from https://github.com/NVIDIA/cuda-samples ? This will help rule out if it's a setup issue or not

**Comment by mpizzagalli777** [comment]
I ran CUDA samples and got an error there as well (CUDA error at ../../../Common/helper_cuda.h:801 code=999(cudaErrorUnknown) "cudaGetDeviceCount(&device_count)") do you happen to know what the issue could be or how i can go about troubleshooting this further?

**Comment by mpizzagalli777** [comment]
Sorry about the messaging mess. I ran the CUDA samples and got the following error:

CUDA error at ../../../Common/helper_cuda.h:801 code=999(cudaErrorUnknown) "cudaGetDeviceCount(&device_count)"

Do you happen to know what might be causing this? I tried reinstalling CUDA toolkit (12.4). Not sure if you might know how to troubleshoot this further

**Comment by tijyojwad** [comment]
Hi, posting on the cuda samples GitHub might be helpful! I've also found from personal experience that sometimes restarting after a CUDA driver install/upgrade helps too.

I'm closing this issue for now, since it's not particular to dorado.

**Comment by mpizzagalli777** [comment]
Thanks so much for your help. In case someone else has the same issue, I followed the download instructions here:
https://developer.nvidia.com/cuda-downloads
And after restarting my computer, was able to successfully run the cuda-samples test.
