### ISSUE TITLE
Basecall process 100% but memory is still occupied for a long time

### ISSUE THREAD

**Issue by Yang990-sys** [nanoporetech/dorado#795]
Hello,

I am using Dorado v0.5.3  for  RNA004 basecalling , but I frequently encounter issues with progress bars reaching 100% but memory not being released for a long time, lasting from 20 minutes to 5 hours. Is this a normal situation or a bug?

Memory is still occupied:
![image](https://github.com/nanoporetech/dorado/assets/54176741/5a695e82-749c-4e78-a197-cb63aaa6a938)
The progress bar reached 100% 5 hours ago :
![image](https://github.com/nanoporetech/dorado/assets/54176741/6502f2f0-5697-495b-bf92-295f56c08ae2)

**Comment by malton-ont** [comment]
Hi @Yang990-sys,

Can you please fill out the issue template? In particular, the command you are using to run dorado would be very helpful here.

**Comment by Yang990-sys** [comment]
# Issue Report
## Please describe the issue:
As above 

## Steps to reproduce the issue:
copy pod5 and basecall

## Run environment:
- Dorado version: v0.5.3
- Dorado command: soft/dorado-0.5.3-linux-x64/bin/dorado basecaller -r --resume-from ./pre.basecalled.bam --batchsize 3072 --estimate-poly-a -x "cuda:${cuda}" --modified-bases-models /data/user/jiangmian/soft/model/rna004_130bps_sup@v3.0.1_m6A_DRACH@v1 /data/user/jiangmian/soft/model/rna004_130bps_sup@v3.0.1  ./pod5 > basecalled.bam
- Operating system:
- Hardware (CPUs, Memory, GPUs):  4  NVIDIA A800 80GB PCIe
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location (on device or networked drive - NFS, etc.):  device
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): RNA004, many kits has 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):
I don't know if small-scale data will encounter such problems, but I killed the program that ran to 100% pause and ran it again (theoretically, there is very little data that needs to continue running), and it will still pause at 100% for a long time. 
## Logs
https://private-user-images.githubusercontent.com/54176741/328376096-6502f2f0-5697-495b-bf92-295f56c08ae2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMTc2NjYsIm5iZiI6MTcxNTIxNzM2NiwicGF0aCI6Ii81NDE3Njc0MS8zMjgzNzYwOTYtNjUwMmYyZjAtNTY5Ny00OTViLWJmOTItMjk1ZjU2YzA4YWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAxMTYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YWU3NDk4MDJlMzBhMzc1MjE4OWYxYjZmOTMxM2EzNTQwYTdkN2I3ZmFkZWE4YzNlNWRjYzlkNzBiYjk1NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HJX7nJGpO4YgUkBjyVx6ct0lXbci_jd3e5AYOtbDGG4

————————————————
I guess it's because I set the batch size too large? The default batch size of the program can only use 85% of GPU memory. In order to speed up progress and not waste resources, the batch size is intentionally set to be too large, and the program will prompt to be too large, adjusting it to a value that can fill up memory without crashing. I don't know if this operation is meaningful and if it will cause the above bug?

**Comment by malton-ont** [comment]
Hi @Yang990-sys,

The default batch size is determined by performing a timing sweep of different batch sizes to determine the most efficient value - this may not be the same as the value that uses the maximum GPU memory (or we'd just have picked the max value as the default!). Having said that, I don't see how that would cause a long delay in shutdown, except that dorado needs to deallocate the memory at the end.

For a 13 hour run, that's a lot of data - 100% may not be exactly 100% and more processing may still be occurring. Are you able to run a process monitor such as `htop`? Additional processing such as the poly-a estimation occurs on the CPU, and so will not show as GPU activity.

**Comment by Yang990-sys** [comment]
You are right, even if the GPU usage is 0, there are still some threads running on the CPU; Thank you for your clarification!
![image](https://github.com/nanoporetech/dorado/assets/54176741/c85c5b48-9cbb-4a97-a725-f7acaec766b3)
