### ISSUE TITLE
Empty values for columns "template_start" and "template_duration" in summary for barcoded reads

### ISSUE THREAD

**Issue by luigilamparelli** [nanoporetech/dorado#796]
# Issue Report

## Please describe the issue:

Hello, I've noticed that, after demultiplexing, some reads have missing values for the columns "template_start" and "template_duration" in the summary produced by dorado summary. The same read but before barcoding have the columns filled and I expect the same after barcoding and demultiplexing.

## Steps to reproduce the issue:

1. Basecalling without barcoding: `dorado basecaller -vv dna_r10.4.1_e8.2_400bps_sup@v4.1.0 ${pod5} > ${bam}`
2. Demultiplexing: `dorado demux -vv --output-dir ${out_dir}/ --kit-name SQK-NBD114-96 --emit-summary ${bam}`
3. Summary on barcoded reads: `dorado summary ${out_dir}/${barcoded_bam} > summary_barcoded.txt` 
4. Summary on the original not barcoded reads: `dorado summary ${bam} > summary_not_barcoded.txt`

## Run environment:
- Dorado version: 0.6.1+79b5da5

## Logs
You will find attached the log files for the 3 dorado commands. 
In addition to these, I would like to share with you the tags of one of the reads which fails (0a0eb075-0cd0-41f6-9244-f9b5c4d17e61), both before and after barcoding. There is a difference in two tags:

- `ns:i:`: this is 171575 in the not barcoded and 0 in the barcoded. The missing value may be caused by a division by 0; changing this to any other positive integer will make dorado summary write numbers in the above mentioned columns.
- `ts:i:`: this is 0 in both files, but in the barcoded is moved to the end. I don't think this is relevant to this issue.

[bam_tags_barcoded.txt](https://github.com/nanoporetech/dorado/files/15235313/bam_tags_barcoded.txt)
[bam_tags_not_barcoded.txt](https://github.com/nanoporetech/dorado/files/15235315/barm_tags_not_barcoded.txt)
[dorado_basecaller.log](https://github.com/nanoporetech/dorado/files/15235316/dorado_basecaller.log)
[dorado_demux.log](https://github.com/nanoporetech/dorado/files/15235317/dorado_demux.log)
[dorado_summary.log](https://github.com/nanoporetech/dorado/files/15235318/dorado_summary.log)

Here are the summary files obtained:
[summary_barcoded.txt](https://github.com/nanoporetech/dorado/files/15235319/summary_barcoded.txt)
[summary_not_barcoded.txt](https://github.com/nanoporetech/dorado/files/15235320/summary_not_barcoded.txt)

Thanks for the help!

**Comment by malton-ont** [comment]
Hi @luigilamparelli,

Thanks for raising this. This looks like an issue in calculating the new number of samples in the read after barcode trimming in the `demux` subcommand - as we're missing the move table at this point, we end up calculating the length as zero.

You can avoid this for now by performing the demux in line with basecalling (by providing the `--kit-name` parameter during basecalling) or by including the move table in the basecalling output (using the `--emit-moves` flag). Or you can skip trimming entirely with the `--no-trim` option.

We'll investigate the best way to resolve this properly for a future release.

**Comment by tijyojwad** [comment]
Hi @luigilamparelli - a fix for this has been released with dorado v0.7.0 and newer.
