### ISSUE TITLE
Problem building with cmake on an intel macbook pro 2020.

### ISSUE THREAD

**Issue by ddrazoh** [nanoporetech/dorado#798]
I have an intel macbook pro 2020 but have failed to make the dorado build.

**Comment by ddrazoh** [comment]
> I have an intel macbook pro 2020 but have failed to make the dorado build.
<img width="661" alt="Screenshot 2024-05-08 at 12 46 40" src="https://github.com/nanoporetech/dorado/assets/94168380/2da8984d-af00-435c-998e-8bbe85a10774">

**Comment by HalfPhoton** [comment]
@ddrazoh, 
You can get dorado pre-built for Mac from the [installation](https://github.com/nanoporetech/dorado?tab=readme-ov-file#installation) documentation.
Do you have a specific reason for compiling?

Kind regards,
Rich

**Comment by ddrazoh** [comment]
Dear Richard,

Thank you for reaching out. I was compiling because I have an intel mac but not one with a silcon chip.

Regards,
Drake

From: Richard Harris ***@***.***>
Reply to: nanoporetech/dorado ***@***.***>
Date: Wednesday, 8 May 2024 at 13:05
To: nanoporetech/dorado ***@***.***>
Cc: ddrazoh ***@***.***>, Mention ***@***.***>
Subject: Re: [nanoporetech/dorado] Problem building with cmake on an intel macbook pro 2020. (Issue #798)


@ddrazoh<https://github.com/ddrazoh>,
You can get dorado pre-built for Mac from the installation<https://github.com/nanoporetech/dorado?tab=readme-ov-file#installation> documentation.
Do you have a specific reason for compiling?

Kind regards,
Rich

**Comment by ddrazoh** [comment]
Dear Rich, This is the error I get with the  pre-buit for mac.
I am running an intel macbook pro 2020. Not M1/2 silcon chip.
***@***.***

Thank you.

Drake

From: Richard Harris ***@***.***>
Reply to: nanoporetech/dorado ***@***.***>
Date: Wednesday, 8 May 2024 at 13:05
To: nanoporetech/dorado ***@***.***>
Cc: ddrazoh ***@***.***>, Mention ***@***.***>
Subject: Re: [nanoporetech/dorado] Problem building with cmake on an intel macbook pro 2020. (Issue #798)


@ddrazoh<https://github.com/ddrazoh>,
You can get dorado pre-built for Mac from the installation<https://github.com/nanoporetech/dorado?tab=readme-ov-file#installation> documentation.
Do you have a specific reason for compiling?

Kind regards,
Rich

**Comment by malton-ont** [comment]
Hi @ddrazoh,

This looks like an issue checking out the git submodules, rather than an issue with dorado per se. Try removing the `dorado/3rdparty/indicators` folder and then run:
```
git submodule update --init --recursive
```
