### ISSUE TITLE
Missing library 

### ISSUE THREAD

**Issue by KlaMa2** [nanoporetech/dorado#80]
Hi, 
after running dorado on an Apple M1 Ultra Studio Mac (OSX 12.3.1, Monterey) I get the following error message:

dyld[48349]: Library not loaded: /opt/homebrew/opt/libaec/lib/libsz.2.dylib
  Referenced from: /Users/User/Downloads/dorado-0.1.1+eb48766-Darwin/bin/dorado
  Reason: tried: '/opt/homebrew/opt/libaec/lib/libsz.2.dylib' (no such file), '/usr/local/lib/libsz.2.dylib' (no such file), '/usr/lib/libsz.2.dylib' (no such file)

Apologies, I believe some libraries may need to be installed or referenced in the PATH. Is there a tutorial about installing the prerequisites that need to be done before running dorado?

Best, 
Klaas

**Comment by tnn111** [comment]
I had the same problem. I couldn't stomach doing a lot of symbolic linking so I installed homebrew and then hdf5. That solved the problems. Except for turning off the Apple Gatekeeper......

Now I have a different one. I try to download models and this is what I get:

Moncster ~ % dorado download --model dna_r10.4.1_e8.2_400bps_hac@v4.0.0
[2023-01-19 22:50:35.399] [info]  - downloading dna_r10.4.1_e8.2_400bps_hac@v4.0.0
[2023-01-19 22:52:03.709] [error] Failed to download dna_r10.4.1_e8.2_400bps_hac@v4.0.0

Anyone know how to solve the problem?

**Comment by tnn111** [comment]
PS: It works fine on a Linux system...... It's just the Mac one that can't download.

**Comment by iiSeymour** [comment]
@tnn111 we changed the hosting for the models in the latest release - see https://github.com/nanoporetech/dorado/issues/74#issuecomment-1435969149.

Can you confirm if you see still `[error] Failed to download` on mac?

**Comment by husamia** [comment]
> Hi, after running dorado on an Apple M1 Ultra Studio Mac (OSX 12.3.1, Monterey) I get the following error message:
> 
> dyld[48349]: Library not loaded: /opt/homebrew/opt/libaec/lib/libsz.2.dylib Referenced from: /Users/User/Downloads/dorado-0.1.1+eb48766-Darwin/bin/dorado Reason: tried: '/opt/homebrew/opt/libaec/lib/libsz.2.dylib' (no such file), '/usr/local/lib/libsz.2.dylib' (no such file), '/usr/lib/libsz.2.dylib' (no such file)
> 
> Apologies, I believe some libraries may need to be installed or referenced in the PATH. Is there a tutorial about installing the prerequisites that need to be done before running dorado?
> 
> Best, Klaas

I am having same error with latest version on Mac M1 as well

```
% ./dorado-0.2.4-osx-arm64/bin/dorado
dyld[47047]: Library not loaded: '/opt/homebrew/opt/zstd/lib/libzstd.1.dylib'
  Referenced from: '/Users/husw5y/Sequencing/dorado-0.2.4-osx-arm64/bin/dorado'
  Reason: tried: '/opt/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/usr/local/lib/libzstd.1.dylib' (no such file), '/usr/lib/libzstd.1.dylib' (no such file)
zsh: abort      ./dorado-0.2.4-osx-arm64/bin/dorado
% uname -a
Darwin EA22-00453 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64
```

**Comment by tijyojwad** [comment]
Hi @KlaMa2 @husamia - the missing libraries for Mac are now packaged as part of the release build - https://github.com/nanoporetech/dorado/releases/tag/v0.3.1

**Comment by lucky5sugar** [comment]
@tijyojwad 
I got the same issue even with v0.3.2 on my MacBook (M1 pro).
Installing openssl and hdf5 with homebrew worked well.

**Comment by tijyojwad** [comment]
Hi @lucky5sugar - the libraries are included but we have an issue with setting the rpath on the binary. You can us the shipped libs with the tips here - https://github.com/nanoporetech/dorado#library-path-errors

**Comment by husamia** [comment]
> Hi @KlaMa2 @husamia - the missing libraries for Mac are now packaged as part of the release build - https://github.com/nanoporetech/dorado/releases/tag/v0.3.1

I confirmed v0.3.1 and above doesn't give missing library errors
