### ISSUE TITLE
basecalling with hac v4.2 vs v4.3 model 

### ISSUE THREAD

**Issue by eesiribloom** [nanoporetech/dorado#801]
If I have two "batches" of sequencing data and one is basecalled with:
dna_r10.4.1_e8.2_400bps_hac@v4.2.0 
and the other with: 
dna_r10.4.1_e8.2_400bps_hac@v4.3.0 
Will this greatly affect my results? Should re-do basecalling so all samples are sequenced with the latest/same model? I know the most ideal situation is to have the exact same model flow cell etc. but this isn't always how things work out in real life and I dont want to waste unnecessary compute and time redoing analyses.

**Comment by vellamike** [comment]
Hello @eesiribloom,

v4.3 is slightly more accurate on most data, and considerably more accurate on a native DNA from a number of bacterial genomes. If your data is native bacterial DNA you may see benefits from v4.3. If not, you probably don't need to rebasecall.

**Comment by eesiribloom** [comment]
Is there a difference in basecalling with the same model e.g. dna_r10.4.1_e8.2_400bps_hac@v4.3.0 between dorado basecaller server and the standalone software?

**Comment by HalfPhoton** [comment]
No - the server is effectively using dorado standalone internally. So as long as they're the same version it's the same.
