### ISSUE TITLE
Putting a link to Dorado binaries in a public workflow or document

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/dorado#804]
Hello dorado developers,

I know that for software like Guppy putting a direct link to a Guppy download was not allowed as it was proprietary. 

But given Dorado is open-source, it shouldn't be a problem if we put a direct link to Dorado binaries in a workflow or a document I believe?

Also, what about the doarado-server?

**Comment by tijyojwad** [comment]
Hi @hasindu2008 - yes okay to put direct link to dorado binaries.

I don't think dorado server has an open link?
