### ISSUE TITLE
Read splitting

### ISSUE THREAD

**Issue by guangzhaocs** [nanoporetech/dorado#805]
Previously, I reported a question (get more reads from Dorado). The old question here: https://github.com/nanoporetech/dorado/issues/701

So, could I prevent the splitting using some parameters (e.g., `--no-trim`)? Or how to combine these splitting reads to get the full output corresponding to the original reads? (my data is RNA)

I do not find the introduction of the `the read splitting of concatemers`. Could you provide more information about this?

Thanks a lot

**Comment by tijyojwad** [comment]
Hi @guangzhaocs - there's no way to prevent read splitting in dorado. What is your use case for not wanting them to be split?

You could roughly stitch them back together using the `pi:z` and `sp:i` tags. the `pi` tag mentions the original reads ids, and `sp` is the split point, so sorting by split point and concatenating will approximately get back the unspilt read.

More details on unspilt reads at https://github.com/nanoporetech/dorado/blob/release-v0.6/documentation/SAM.md#split-read-tags

**Comment by guangzhaocs** [comment]
Thanks very much. I do not have other questions.

**Comment by tijyojwad** [comment]
note that by default the adapters in reads are also trimmed off, so each split read will have their adapters removed. to get most of the original read back, you need to run with `--no-trim`

**Comment by guangzhaocs** [comment]
Sorry, I still have some questions about **read splitting**.

As you mentioned above, a single read in the original fast5/pod5 file might consist of concatenated reads (concatemer). Therefore, during Dorado base calling, we need to split it into multiple sub-reads. Is my understanding correct?

Is the concatemer a feature of the latest kit? I didn’t encounter concatemers when using the Guppy basecaller. Could you provide more information or materials on read concatemers in Nanopore sequencing?

Thank you very much!
