### ISSUE TITLE
dorado v7.3.9 adapter trimming

### ISSUE THREAD

**Issue by eesiribloom** [nanoporetech/dorado#807]
does dorado basecaller server v7.3.9 perform adapter /primer trimming by default?

**Comment by malton-ont** [comment]
Hi @eesiribloom,

No, the basecall server doesn't trim by default. You can use the flags `--trim_adapters` and `--trim_primers` (as well as `--enable_trim_barcodes) to set the appropriate trimming. Note that this is different to dorado standalone, which _does_ trim by default.
