### ISSUE TITLE
Pod5 tools don't install on Apple Studio.

### ISSUE THREAD

**Issue by tnn111** [nanoporetech/dorado#81]
I'm trying to install pod5 tools on a new Apple studio and it fails as shown below. Anyone solve that problem? I've spent my evening installing homebrew to get the dorado libraries and now I'm mostly stuck on getting a model and converting some fast5 files to pod5.

Moncster ~ % pip install pod5
Collecting pod5
  Downloading pod5-0.1.4-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 kB 2.0 MB/s eta 0:00:00
Collecting iso8601
  Downloading iso8601-1.1.0-py3-none-any.whl (9.9 kB)
Collecting jsonschema
  Downloading jsonschema-4.17.3-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.4/90.4 kB 5.3 MB/s eta 0:00:00
Collecting pod5
  Downloading pod5-0.1-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 kB 5.3 MB/s eta 0:00:00
  Downloading pod5-0.0.43-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 2.7 MB/s eta 0:00:00
ERROR: Cannot install pod5==0.0.43, pod5==0.1 and pod5==0.1.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    pod5 0.1.4 depends on lib-pod5~=0.1.4
    pod5 0.1 depends on lib-pod5~=0.1
    pod5 0.0.43 depends on lib-pod5~=0.0.43

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by jorj1988** [comment]
Hi @tnn111 , can you confirm what version of python you are using?

**Comment by tnn111** [comment]
It’s 3.11

**Comment by jorj1988** [comment]
Ah - ok, please retry now we have release pod5 version 0.1.5 - it comes with python 3.11 support for osx.
