### ISSUE TITLE
Dorado basecalling what's next ? Correlation with modkit output and transposable elements

### ISSUE THREAD

**Issue by OceaneMion** [nanoporetech/dorado#810]
Hi all,
I have performed dorado modified basecalling on my data, obtain my assemblies and performed a modkit pileup on them to have my methylation data.

I have filtered my data to have output as follow :
contig_102	0	1	0
contig_102	1	2	0
contig_102	2	3	0
contig_102	3	4	0
contig_102	4	5	0
contig_102	5	6	0
contig_102	6	7	0
contig_102	7	8	0
contig_102	8	9	0
contig_102	9	10	3.45

With the first column being the contig name, the second the start position, the third the ending position, and the last column the methylation probability

I have also perform RepeatModeler and RepeatMasker step to annotate my transposable element, and filtered my data to obtain output as follow :
contig_102	10317	10662	LTR
contig_102	10664	11011	LTR
contig_102	36398	36453	LTR
contig_102	39665	39748	LTR
contig_102	40983	41101	LTR/Gypsy

My question is do you have any code/pipeline on how to obtain a plot similar to this :
![image](https://github.com/nanoporetech/dorado/assets/111916472/20d71802-9dca-446c-ae7d-e61ab3cf4edf)

I know that I can kinda use bedtools intersect to obtain the methylation marks in my transposable elements
Any help will be appreciate, thanks in advance.

**Comment by HalfPhoton** [comment]
Hi @OceaneMion,
Respectfully this is not a dorado issue and as such I'm closing it.
Please seek assistance in a bioinformatics forum where they're likely able to help you.

Kind regards,
Rich

**Comment by OceaneMion** [comment]
Thanks for your anwser I will see with the creator of modkit as it is more
correlated with their work.

Le mer. 15 mai 2024 à 18:42, Richard Harris ***@***.***> a
écrit :
