### ISSUE TITLE
automatic model selection, bps not matching with expected

### ISSUE THREAD

**Issue by aistBMRG** [nanoporetech/dorado#811]
Hi, 

Small question regarding the automatic model selection with dorado.

I ran sequencing at 260 bases per second but dorado appears to select 400bps for basecalling.

Fyi, the POD5 (using inspect command) contains the following: 
'sample_frequency': '4000', 'selected_speed_bases_per_second': '260'

Now, I am running dorado (0.6.2) as follows:

./bin/dorado basecaller sup ./pod5/

This then returns: "downloading dna_r10.4.1_e8.2_400bps_sup@v4.1.0 with foundation"

Would it be possible to clarify? 

Thanks in advance.

Dieter

**Comment by HalfPhoton** [comment]
Are you able to report the flowcell and kit codes from your input data?

```bash
pod5 inspect debug <data.pod5> | grep -E "flow_cell_product_code|sequencing_kit"

# Should look like:
        flow_cell_product_code: <flowcell_product_code>
        sequencing_kit: <sequencing_kit>

```
Kind regards,
Rich

**Comment by aistBMRG** [comment]
Hi Rich,

Please find below the info: 

context_tags: {'barcoding_enabled': '0', 'basecall_config_filename': 'dna_r10.4.1_e8.2_260bps_hac.cfg', 'experiment_duration_set': '4320', 'experiment_type': 'genomic_dna', 'local_basecalling': '1', 'package': 'bream4', 'package_version': '7.4.8', 'sample_frequency': '4000', 'selected_speed_bases_per_second': '260', 'sequencing_kit': 'sqk-lsk114'}
 flow_cell_product_code: FLO-MIN114
 sequencing_kit: sqk-lsk114

Note that this was already base-called in real-time but just testing newer models.

Thanks for your help.

Dieter

**Comment by HalfPhoton** [comment]
Dorado expects the flowcell product code to contain the `_260` suffix for 260bps data.

I'll report this back to understand why this isn't being set - we'll also look into detecting the `'selected_speed_bases_per_second': '260', '` value.

In your case - please manually download and select the appropriate 260bps model as the auto model selection in not working here.

**Comment by aistBMRG** [comment]
Ok, thanks for the clarification.

Best,

Dieter
