### ISSUE TITLE
What is best practice for treating same DNA sample with different sampling rates?

### ISSUE THREAD

**Issue by sahuno** [nanoporetech/dorado#813]
# Issue Report
This is more design issue. The same sample has two pod5 with different sampling rate. what is best modified base calling? 
To do modified basecalling separately for each pod5 file and merge resulting bam files with samtools ? will this affect downstream analysis?
how are people handling this issue? 

thanks in advance for your advice

**Comment by HalfPhoton** [comment]
Basecalling separately is certainly the way forward.

Use the dorado automatic model selection for each data type to get the correct model and modification model respectively. 
If you try to use the dorado auto model selection on the mixed of data it will report an error explaining that data does not have a homogeneous type (e.g. sampling rate) and that it couldn't find the appropriate model for you.

Try something like 
```
dorado hac,5mC data_type_1/ ... > calls1.bam
dorado hac,5mC data_type_2/ ... > calls2.bam
```

Dorado will report the model used to stderr and also write this data into the output bam file for future reference.

Hope this helps

**Comment by sahuno** [comment]
thanks for the insight!
