### ISSUE TITLE
Question on: [warning] Unexpected adapter/primer trim interval

### ISSUE THREAD

**Issue by osilander** [nanoporetech/dorado#814]
# Issue Report

## Please describe the issue:
We had three warnings thrown after the most recent basecalling (of a few **million** reads), all along the lines of:
```
[warning] Unexpected adapter/primer trim interval 36-14 for TGTTATGTCTGGTATTTCGTTCAGTTACGTATTGCTGGCGTCTGCTTGGGTGTTTAACCTTGTTTTAGTTGTTTTAGTTGTTTTAGTTGTTTTAGTTGTTTTAATTGTTTTAGTTGGTTTAGTTGTTTTAGGTTAAACACCGAGCAGGACGCCAGCAATACGTG
```
When/why are these warnings thrown?

## Run environment:
- Dorado version: 0.6.0+7a6ab9a
- Dorado command: dorado basecaller
- Operating system: Linux Ubuntu
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by tijyojwad** [comment]
Hi @osilander - these warnings show up when our adapter trimming algorithm found incorrect bounds for the adapter to be trimmed. We report it as a warning and leave the read unchanged. So your data is fine, but it's useful for debugging to know what happened. e.g. we can check this example sequence to see what's going on
