### ISSUE TITLE
Question: Inline basecalling with alignment

### ISSUE THREAD

**Issue by damioresegun** [nanoporetech/dorado#816]
Hi, 
I'm working on cDNA reads and I'm considering not using a reference during the basecalling and just outputting an unaligned BAM file. Am I correct in thinking that the unaligned BAM file will still have the right `BC` tag that demux needs for demultiplexing? 

I'm also trying to understand what the benefit of using the reference during the basecalling is. Does it use the reference to act as a guide or is it just the the reference is used after basecalling is done and its a 'ease-of-use' thing to immediately optionally just get aligned reads out and it saves a step on the user's side? 

Further to this, is there a way to add some more options to the minimap2 implementation for example adding `--junc-bed` and an associated bed file to the basecaller command? 

Thanks!

**Comment by tijyojwad** [comment]
> Am I correct in thinking that the unaligned BAM file will still have the right BC tag that demux needs for demultiplexing?

yes correct, demultiplexing is independent of alignment. barcodes are also trimmed by default when demultiplexing, so it's always better to demux before alignment (this is the sequence when running `dorado basecaller` with demux and alignment)

> is it just the the reference is used after basecalling is done and its a 'ease-of-use' thing to immediately optionally just get aligned reads out and it saves a step on the user's side

yes, this

> is there a way to add some more options to the minimap2 implementation

yes, we are working on adding this

**Comment by damioresegun** [comment]
Okay great, thanks. That clears things up for me. So that means that there is really no difference (given the same options) if I choose to output an unaligned BAM at the basecalling step, then do demux (--no-trim) vs if I did align with the reference at the basecalling step

**Comment by tijyojwad** [comment]
yes correct. if you're demuxing before aligning, then you can trim barcodes too. either is fine.

**Comment by damioresegun** [comment]
I'm choosing to keep them for now because I want to use pychopper downstream so I want to make sure the primers aren't affected beforehand. Unless you think dorado trim can remove the barcodes without affecting primer sequences?

**Comment by tijyojwad** [comment]
makes sense - I believe primers will get trimmed when trimming barcodes

**Comment by damioresegun** [comment]
Thanks for your help!
