### ISSUE TITLE
Dorado  basecalling

### ISSUE THREAD

**Issue by duhuipeng** [nanoporetech/dorado#818]
Dear author

I'd like to ask you a question，I used megalodon to call methylation and found that in the centromeric region, it showed a hypomethylation state，which corresponds to the peak of CHIP，This is also the expected result，as follow：
![image](https://github.com/nanoporetech/dorado/assets/58722433/43cb389b-c83a-44b2-a9b5-73c61dfcd280)

I'm using dorado right now to call methylation，But the results don't quite fit, as follow：
![image](https://github.com/nanoporetech/dorado/assets/58722433/67167dea-17f3-4ff3-99b7-9cef918e6175)

Now dorado's results are completely skewed, and it doesn't see the low pockets of methylation，I don't know if there's something wrong with my call methylation code，Could you help me find out what the problem is？
My code is as follows：

```bash
dorado  basecaller  dna_r9.4.1_e8_sup@v3.6  ${pod5}/ --modified-bases-models dna_r9.4.1_e8_sup@v3.3_5mCG@v0 --reference $ref > pod5.bam
samtools sort pod5.bam > pod5.sort.bam
samtools index pod5.sort.bam
modkit call-mods pod5.sorted.bam pod5_filter.sorted.bam --filter-threshold A:0.9 --mod-threshold a:0.95 --filter-threshold C:0.97 --threads=90
modkit pileup pod5_filter.sorted.bam pod5.pileup.bed --cpg --ref $ref --combine-strands 
```

Finally, I plot the methylation density of the resulting bed file，The result is the picture just marked with the blue arrow
Looking forward to your reply

Best
HuipengDu

**Comment by marcus1487** [comment]
It looks like there are far fewer calls over this region in the data processed with dorado. Could you provide a browser shot with both runs at this genomic location? This might diagnose what is happening here.

**Comment by duhuipeng** [comment]
Dear author
What dorado did was I filtered the results, and I made the number of methylations that supported this greater than 15,，as follow： cat pod5.pileup.bed |awk '{if ($1~/chr${i}/) print$0}'|awk '{if ($5 > 15) print$0}'|awk '{if ($2 > 53100000 && $3 < 59180000 ) print$1"\t"$2"\t"$3"\t"$11}' > chr${i}.bed
and the graph that came out is what you just saw,
If you use the original result to run, the result is even wrong, I did not put up
I want to know whether I used dorado incorrectly, which led to the problem，the result is directly biased. May I ask how I should operate to get the correct result？

Best
HuipengDu

**Comment by duhuipeng** [comment]
Dear author
The result of megalodon can be matched on all my chromosomes, which is in line with my expectations. However, the result of dorado is very strange, and there is a big difference between the result of megalodon and the result of Dorado. Almost none of the results are matched on chromosomes, which is not in line with my expectations. I hope you can help me look at my code where there is a problem

Best
HuipengDu

**Comment by malton-ont** [comment]
@duhuipeng,

The dorado model you ran performs modbase analysis only in `CG` contexts, is that what you expected? Is that the same as for the model you ran in the other analysis?
