### ISSUE TITLE
Failed to download rna002_70bps_hac@v3: Could not establish connection

### ISSUE THREAD

**Issue by wangguiqian** [nanoporetech/dorado#819]
When I use the dorado-basecaller command to obtain the bam file, my computer server cannot connect to the network in the running node (server security considerations). So when I run the command it happens: Failed to download rna002_70bps_hac@v3
This my command:
dorado basecaller hac,6mA,5mC,m6A_DRACH,5mCG_5hmCG,5mCG 5mC_5hmC ../../sx-90h/pass_data/ --min-qscore 1 --resume-from incomplete.bam >sx-90h_call.bam

But I have downloaded all the models locally:
<img width="1058" alt="image" src="https://github.com/nanoporetech/dorado/assets/48958211/bb9934e3-894b-4f6b-8d95-53cca14ca682">

**Comment by tijyojwad** [comment]
To use downloaded models you will need to pass the model paths manually to dorado. we will add support for using downloaded models with the model complex (i.e. `hac,6mA,...`) in a future release.

For now please run
```
dorado basecaller dna_r10.4.1_e8.2_400bps_hac\@v4.3.0 <pod5> --modified-bases-models dna_r10.4.1_e8.2_400bps_hac\@v4.3.0_6mA\@v1/ dna_r10.4.1_e8.2_400bps_hac\@v4.3.0_5mCG_5hmCG\@v1/ ...
```

**Comment by wangguiqian** [comment]
Sorry, I sent it by mistake. My data is from Direct's direct RNA sequencing model, which is the rna002 chip. What methylation modifications can be obtained?
 
 thank you very much for your help

**Comment by tijyojwad** [comment]
Modification calling is only supported for RNA004.

All RNA modifications are listed here - https://github.com/nanoporetech/dorado?tab=readme-ov-file#rna-models
