### ISSUE TITLE
dorado fails with "CuBLAS error 15"

### ISSUE THREAD

**Issue by tnn111** [nanoporetech/dorado#82]
Anyone know what CuBLAS error 15 is? Here is the output I got:

perlmutter%: dorado basecaller -v ~/soft/models/'dna_r10.4.1_e8.2_400bps_sup@v4.0.0' pod5 > nano.fastq

[2023-01-20 16:25:36.163] [info] > Creating basecall pipeline
[2023-01-20 16:25:37.495] [debug] - available GPU memory 41GB
[2023-01-20 16:25:38.007] [error] CuBLAS error 15

It's on an HPC login node with an A100 attached. The modules loaded are:

Currently Loaded Modules:
  1) craype-x86-milan     3) craype-network-ofi                      5) PrgEnv-gnu/8.3.3   7) cray-libsci/22.11.1.2   9) perftools-base/22.09.0  11) xalt/2.10.2            13) gpu/1.0    15) python/3.9-anaconda-2021.11
  2) libfabric/1.15.2.0   4) xpmem/2.5.2-2.4_3.20__gd0f7936.shasta   6) cray-dsmml/0.2.2   8) craype/2.7.19          10) cpe/22.11               12) craype-accel-nvidia80  14) evp-patch  16) parallel/20210922

**Comment by vellamike** [comment]
Hi @tnn111 , 

Are you compiling from source or using the pre-built binaries? Could you try this with [the latest version of Dorado (0.2.1)](https://github.com/nanoporetech/dorado/releases/tag/v0.2.1)
