### ISSUE TITLE
Redo basecalling on both POD5_pass and fail folders

### ISSUE THREAD

**Issue by Harper19** [nanoporetech/dorado#820]
Wanna redo HAC mode basecalling to obtain more useful data. How could I deal with those 2 folders? Should I directly combine them together into one folder?

Thanks,
Harper

**Comment by HalfPhoton** [comment]
Hi @Harper19,
Using the `--recursive` option you can either basecall the parent directory or a new directory with symbolic links to the two pass / fail folders.

```
dorado basecall hac . --recursive > calls.hac.bam
```

```
mkdir all_data
cd all_data
ln -s ../pod5_pass 
ln -s ../pod5_fail
cd .. 
dorado basecall hac all_data/ --recursive > calls.hac.bam
```

Kind regards,
Rich

**Comment by Harper19** [comment]
Thank you so much!  -Harper
