### ISSUE TITLE
Can dorado call m6A modification on RNA002 sequence data? 

### ISSUE THREAD

**Issue by yinyuanmtu** [nanoporetech/dorado#822]
Or is there any way to do that? Thanks!

**Comment by tijyojwad** [comment]
m6A mod support is only available for RNA004.

This thread may be useful - https://github.com/nanoporetech/dorado/issues/273

**Comment by yinyuanmtu** [comment]
Thanks!
Yinan Yuan, PhD
Assistant Professor in Forest Tree Genetics, Genomics and Biotechnology
College of Forest Resources and Environmental Science
Michigan Technological University
Phone: 906-487-1835
