### ISSUE TITLE
Calling 0 length poly(A) tails

### ISSUE THREAD

**Issue by eschiks** [nanoporetech/dorado#823]
I am interested in using Nano 3PSeq (https://www.nature.com/articles/s41592-022-01714-w) to sequence polyA'd and non-polyA'd transcripts. Previously this protocol used tailfindr for tail length calling, but this is no longer compatible with the new flow cells. I'm wondering if Dorado is capable of flagging transcripts lacking polyA tails and identifying custom adapter sequences like tailfindr was? And if it is not currently, could that functionality be added?

**Comment by tijyojwad** [comment]
Hi @eschiks - finding polyA with custom adapter sequencers was just released with dorado 0.7.0. You can find the documentation here - https://github.com/nanoporetech/dorado/blob/release-v0.7/documentation/PolyTailConfig.md#configuration-options

If dorado doesn't find polyA in a read, the `pt:i` tag will be missing in the output BAM record.
