### ISSUE TITLE
Running Dorado on EXP-NBD104 kit

### ISSUE THREAD

**Issue by lucyintheskyzzz** [nanoporetech/dorado#826]
# Issue Report
Hi I was told that I could run dorado on my previous sequenced pod5 files where I used the older phased out EXP-NBD104 kit , but used the SQK-NBD114-24 kit, because the barcodes have the same sequences between the two kits.  Is this a normal output? Seems like I am getting a large unclassified.bam file:

 
![image](https://github.com/nanoporetech/dorado/assets/71407498/bc9f9685-8a0e-409e-84eb-09543636ad2d)

![image](https://github.com/nanoporetech/dorado/assets/71407498/3660364a-6fcb-4e86-b47a-00a030723900)

## Run environment:
- Dorado version: 0.6.1
- 
- Dorado command:
- ##basecalling
/work/kvigil/Programs/dorado-0.6.1-linux-x64/bin/dorado basecaller /work/kvigil/Programs/dorado-0.6.1-linux-x64/bin/dna_r9.4.1_e8_hac@v3.3 --recursive /work/kvigil/baratariabay/ONR100623_seawater/20231006_1648_MN18851_FAW76720_acec0fdf/pod5_pass --kit-name SQK-NBD114-24 > /work/kvigil/baratariabay/ONR100623_seawater/20231006_1648_MN18851_FAW76720_acec0fdf/hac/ONR100623_seawater.calls.bam

##demux
/work/kvigil/Programs/dorado-0.6.1-linux-x64/bin/dorado demux --output-dir /ddnB/work/kvigil/baratariabay/ONR100623_seawater/20231006_1648_MN18851_FAW76720_acec0fdf/hac/barcodes --no-classify /ddnB/work/kvigil/baratariabay/ONR100623_seawater/20231006_1648_MN18851_FAW76720_acec0fdf/hac/ONR100623_seawater.calls.bam

- Operating system:
8 GPU Compute Nodes, each with:
Two 24-core Intel Cascade Lake (Intel® Xeon® Platinum 8260 Processor) CPUs.
192 GB memory
600 GB HDD
2 NVIDIA Volta V100 GPU's

Thanks! Katie

**Comment by tijyojwad** [comment]
Hi @lucyintheskyzzz - we have a separate `EXP-NBD104` in dorado. Can you try with that instead?

`dorado basecaller model pod5 --kit-name EXP-NBD104 ...`

**Comment by lucyintheskyzzz** [comment]
@tijyojwad thanks I will try this and get back to you!

**Comment by lucyintheskyzzz** [comment]
Hi @tijyojwad Looks like using the correct kit decreased the unclassified.bam. Thanks! 
![image](https://github.com/nanoporetech/dorado/assets/71407498/3841efb0-02e1-4109-91e4-5caa45d335bc)
