### ISSUE TITLE
Is possible to do the joint modification calling of DNA 6mA and CpG methylation on the same time?

### ISSUE THREAD

**Issue by DexinYang1998** [nanoporetech/dorado#827]
Hi,

Thanks so much for your wonderful tools for analyzing nanopore data. I am wondering whether there is a way to do the joint modification calling of DNA 6mA and CpG methylation rather than calling separately. Or, whether it is possible to merge the two types of modification information into the same read.

Thanks.

**Comment by HalfPhoton** [comment]
Hi @DexinYang1998, thank you for the kind words!
You should be able to basecall both mods at the same time. 

Try the model complex `hac,6mA,5mCG_5hmCG` and dorado should automatically find the newest models for you.

**Comment by DexinYang1998** [comment]
Thank you!
