### ISSUE TITLE
dorado correct question

### ISSUE THREAD

**Issue by evandiego83** [nanoporetech/dorado#829]
Thanks for the new release of dorado which features the new correct command. Presumably this will only work for reads whose
length is ≥ 10000bp as I have tried it on a dataset containing viral reads and I get nothing from the output. Given that most of the reads are about 9,000 bp I presume this is why? 

Will a version be made available to correct for shorter reads <10,000 bp?

Thanks
Evan

**Comment by tijyojwad** [comment]
Hi @evandiego83 - thanks for the feedback! dorado correct is indeed designed for datasets with longer reads. While we don't explicitly have minimum read length, it's more a function of the kind of overlaps we see in the dataset and how those compare to a minimum overlap length needed (4096 bases in the current release) for correction.

Can you elaborate on your use case for `dorado correct`?
