### ISSUE TITLE
`max_barcode_cost` not defined

### ISSUE THREAD

**Issue by godotgildor** [nanoporetech/dorado#830]
In the custom barcode TOML description, when defining `min_barcode_penalty_dist` and `min_separation_only_dist` there is a reference to a `max_barcode_cost` parameter. However, I don't see a definition of this parameter in the markdown document nor did I find it referenced in the code. Can anyone point me to more information on this parameter?

https://github.com/nanoporetech/dorado/blob/71cc74429f0daa43f1ca32b203b2af569b1e6386/documentation/CustomBarcodes.md?plain=1#L93-L94

**Comment by tijyojwad** [comment]
good catch! that's a typo in our documentation, it should say `max_barcode_penalty` which is defined in the table.

**Comment by godotgildor** [comment]
Thanks @tijyojwad !
