### ISSUE TITLE
Looking for custom barcodes for both fwd reads and rev complement reads

### ISSUE THREAD

**Issue by godotgildor** [nanoporetech/dorado#832]
I am producing Nanopore libraries where I use two barcodes - one barcode at the front which represents a well on a 96 well plate and another barcode at the back which represents a specific plate. With this setup, all samples from a given plate will have the same barcode at the back, but will have different barcodes at the front. From this discussion [here](https://github.com/nanoporetech/dorado/issues/626#issuecomment-2075216362) it sounds like currently Dorado won't like the duplication of the barcodes in this manner, so I am currently planning on performing a first demux on the well barcodes, and then demuxing the results of each well to a plate (i.e. a two stage approach). 

In setting up my first demux path, I was surprised by the behavior I observed. Since I am just looking for my first barcode which should live at the front of my read, I specified the following in the arrangement file:
```
[arrangement]
name = "fwd"
kit = ""

mask1_front = <8bp of front flank seq>
mask1_rear = <25 bp of rear flank sequence>
barcode1_pattern = "barcode%02i"
first_index = 1
last_index = 96
```

I would have expected demux to look for my barcode at the 5' of my read  OR  look for the reverse complement of my read at the 5' end of the reverse complement of my read. However, that's not what appears to happen. Instead, it just looks at the 5' of my read.

I can get it to find the reverse complement of my barcode when it occurs at the 5' end of the reverse complement of my read by simply adding:
```
mask2_front = <same 8bp sequence of front seq as above>
mask2_rear = <same 25bp sequence of rear seq as above>
barcode2_pattern = "barcode%02i"
```
Note that I did not have to reverse complement the front and rear masks nor the barcode sequence - Dorado was nice and does that for me automatically. But why doesn't Dorado automatically look at the 5' end of the sequence **OR** the 5' end of the reverse complement of the sequence. 

Similarly, if  `mask2_*` sequences are provided, I would have thought Dorado would look for those at the 3' of the sequence **OR** the 3' end of the reverse complement of the sequence?

Maybe I'm misunderstanding how to think about this?

**Comment by tijyojwad** [comment]
HI @godotgildor - that's a good point. The single ended barcode regimen is designed for something like RBK, which only ligates to the 5' end is always oriented the same way. But your setup is actually a double ended barcode with the same flanks on both ends (we have some kits like that, such as RPB114-24). In that case, we look for the barcodes at the 5' and 3' end, and then also reverse complemented.

So what you found through experimentation is the right way to do it - have both mask1 and mask2 info, but the algorithm will only ever find it on one end of the read.

**Comment by godotgildor** [comment]
Thanks @tijyojwad. So it sounds like when just specifying `mask1_*/barcode1_*`, the assumption is that the DNA will only be fed through the pore with the barcode end first.

In my setup, the barcode will only appear on one end of my DNA, but the DNA may enter the pore from either the side with the barcode or the side without the barcode. 

I think with a configuration file that specifies both `mask1_*/barcode1_*` and `mask2_*/barcode2_*` parameters, the demux algorithm will look for the barcode in 4 cases:
* 5' end of read <- valid for my configuration
* 3' end of read <- not valid for my configuration
* 5' end of reverse complement of my read <- valid for my configuration
* 3' end of reverse complement of my read <- not valid for my configuration

It sounds like there currently isn't a way to setup a configuration so that it would just do the two of four cases that would be relevant for my setup - is that right?

**Comment by tijyojwad** [comment]
Yes that's exactly right! There would be som redundant calculation but given that your barcodes only appear on one end of any read it shouldn't affect the classification accuracy.
