### ISSUE TITLE
5mC Calling Issue

### ISSUE THREAD

**Issue by samim2111** [nanoporetech/dorado#84]
Hello!

I've been trying to use Dorado to perform 5mC calling on some data from an R10.4.1 sequencing run and I've been having some trouble. I tried running the basecaller like so:

dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.0.0 /my/directory --modified-bases 5mCG > calls.sam

But I've been getting the following error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  could not find matching modification model for dna_r10.4.1_e8.2_400bps_hac@v4.0.0

I've tried using a few different models as well, but keep getting the same error. Am I just using the wrong model? 

I also have not been able to re-download the models with dorado download (it keeps failing.) Any advice you might have on how to proceed would be much appreciated!

**Comment by sklages** [comment]
you might want to provide the model directly to dorado (omitting `--modified-bases`): 
```
<..> --modified-bases-models /path/to/dna_r10.4.1_e8.2_400bps_hac@v4.0.0_5mCG_5hmCG@v2
```
This eliminated the error in our environment but resulted in a "core dump" on all our A100/A10 systems .. (40G/24G vram).. a "GeForce RTX 2080/8G" worked fine though ...
 
How did you re-download the the models and which error message do you get?

**Comment by samim2111** [comment]
> you might want to provide the model directly to dorado (omitting `--modified-bases`):
> 
> ```
> <..> --modified-bases-models /path/to/dna_r10.4.1_e8.2_400bps_hac@v4.0.0_5mCG_5hmCG@v2
> ```
> 
> This eliminated the error in our environment but resulted in a "core dump" on some systems ...
> 
> How did you re-download the the models and which error message do you get?

I was trying to re-download the models with:

dorado download --model all

Unfortunately, this is blocked by my institution's firewall. 

You're suggestion worked for me, though, so thank you! This is what ended up working for me:

dorado basecaller /path/dna_r10.4.1_e8.2_400bps_fast@v4.0.0/ --modified-bases-models /path/dna_r10.4.1_e8.2_400bps_fast@v4.0.0_5mCG_5hmCG@v2/ /path/to/fast5 > calls.sam
