### ISSUE TITLE
Make longer alias strings possible in demux

### ISSUE THREAD

**Issue by simondrue** [nanoporetech/dorado#840]
Hi,

I'm using the demux tool in Dorado, and I am very happy about the feature to translate barcode IDs to user inputted sample names (aliases) from a sample sheet. However, you have set a max limit on the number of characters one can input:

https://github.com/nanoporetech/dorado/blob/71cc74429f0daa43f1ca32b203b2af569b1e6386/dorado/utils/SampleSheet.cpp#L16

Would it be possible to raise this value or completely get rid of it? For my specific case i want to be able to name a sample e.g. "F001-0003_col5a2-Ex29(c.1976C>T)_wt1_N411-316" which includes information about a specific experiment and the sample ID from out lab. 

Thanks for a great tool,

/Simon

**Comment by HalfPhoton** [comment]
Hi @simondrue, 
Apologies for the late reply - This change will not be implemented as it's is a limit implemented in MinKnow which must be adhered to.

**Comment by simondrue** [comment]
Fair. Hope this might change in the future :)
