### ISSUE TITLE
[E::fai_build3_core] Cannot index files compressed with gzip, please use bgzip

### ISSUE THREAD

**Issue by JWDebler** [nanoporetech/dorado#847]
Turns out `dorado correct` doesn't accept gzip (or pigz) compressed files as input. 
This should probably be mentioned in the readme and help somewhere.

Cheers

**Comment by tijyojwad** [comment]
Hi @JWDebler - yes we're going to be updating the documentation with the patch release coming out this week.

**Comment by tijyojwad** [comment]
Documentation updated with patch 0.7.1
