### ISSUE TITLE
enable proxy settings for download_models 

### ISSUE THREAD

**Issue by Bjoernsen** [nanoporetech/dorado#85]
We cannot run the command `dorado download ...` to download the models. The problem is that we have to use a proxy to access the internet.

Would it be possible to take the env `HTTPS_PROXY` into account if available?

Unfortunately, I am not a C++ developer, but maybe something like this might work?

https://github.com/nanoporetech/dorado/blob/master/dorado/utils/models.cpp#L26

```
if(const char* env_proxy = std::getenv("HTTPS_PROXY"))
      http.set_proxy(str(env_proxy));
```

**Comment by iiSeymour** [comment]
@Bjoernsen I didn't quite get this into the latest release but we have migrated to models to direct URLs - see https://github.com/nanoporetech/dorado/issues/74#issuecomment-1435969149.

**Comment by iiSeymour** [comment]
@Bjoernsen see the patch from @GeorgeNikitinNV
