### ISSUE TITLE
base modifications for mRNA

### ISSUE THREAD

**Issue by yul96** [nanoporetech/dorado#853]
Hi Dorado team,

I have two questions  about the mRNA modifications in the new dorado release 0.7

1. For the pseU modification, is it for pseudouridine or N1-methylpseudouridine? 

2. Is it possible to call multiple base modifications in one run? I have tried "--modified-bases  m6A,pseU"  and it gives me errors on the syntax.

Thank you for the great work!

**Comment by tijyojwad** [comment]
> For the pseU modification, is it for pseudouridine or N1-methylpseudouridine?

pseudouridine

> Is it possible to call multiple base modifications in one run?

yes, please try `--modified-bases pseU m6A` instead

For future reference, please fill out the issue template along with the relevant details (full cmdline, exact error you see, etc.)

**Comment by yul96** [comment]
@tijyojwad Thank you, the switch --modified-bases pseU m6A worked.

Do you have any timeline to make dorado work for the N1-methylpseudouridine modification in mRNA? 

thanks

**Comment by susie-ont** [comment]
Hi @yul96 - we don't currently have a timeline for adding a modification model for N1-methylpseudouridine into Dorado, but we are working on a limited commercial release of a basecalling model for 100% modified N1-methylpseudouridine transcripts. If this is of interest then please get in touch with support@nanoporetech.com with more details of your use case and we can look into options.
