### ISSUE TITLE
What kit to choose for old sequences using the SQK-LSK109

### ISSUE THREAD

**Issue by lucyintheskyzzz** [nanoporetech/dorado#854]
Hi I am running dorado-0.7.0 on my older sequence files where I converted fast5 files to pod5 and I used the SQK-LSK109 sequencing kit for these samples? Is there another kit I can choose from the has the same barcode sequences as the SQK-LSK109 kit?

Thanks!
Katie

**Comment by tijyojwad** [comment]
Hi @lucyintheskyzzz - I'm not exactly sure which one it is, but it's like one of these two - EXP-NBD104, EXP-NBD114 or SQK-NBD114-24 (depending on whether you used barcodes 1-12, 13-24 or 1-24).

Can you try all of these and see what results you get?

**Comment by lucyintheskyzzz** [comment]
hi @tijyojwad I used barcodes 1-12 kit.  I will start with EXP-NBD104 and see what I get. thanks!

**Comment by lucyintheskyzzz** [comment]
Hi the EXP-NBD104 kit worked for these samples thanks!
