### ISSUE TITLE
Error with cmake

### ISSUE THREAD

**Issue by ipatop** [nanoporetech/dorado#857]
# Issue Report

Hi, I am trying to install and get started with dorado (thanks for this amazing tool :) and I am encountering this error when ruining cmake.

`/n/groups/churchman/inp346/scripts/cmake-3.29.3/bin/cmake  -S . -B cmake-build
-- Build type: 
-- Submodule update
fatal: reference is not a tree: 88544847c51397004a31cf2817c334624c6350cf
Unable to checkout '88544847c51397004a31cf2817c334624c6350cf' in submodule path 'dorado/3rdparty/indicators'
CMake Error at cmake/UpdateSubmodules.cmake:18 (message):
  git submodule update --init --recursive failed with 1, please checkout
  submodules
Call Stack (most recent call first):
  cmake/UpdateSubmodules.cmake:25 (git_submodule_update)
  CMakeLists.txt:74 (include)`

And the I get this error when running the submodule update

`git submodule update --init --recursive
fatal: reference is not a tree: 88544847c51397004a31cf2817c334624c6350cf
Unable to checkout '88544847c51397004a31cf2817c334624c6350cf' in submodule path 'dorado/3rdparty/indicators'`

Thanks in advance,

**Comment by malton-ont** [comment]
Hi @ipatop,

This looks to be an error from the `git submodule` command that is invoked as part of our configuration step. That particular submodule is pointed at a commit in a PR that we submitted which has yet to be merged. This should just work. Can you confirm a few details for me?

- Your `git` version
- Your dorado `git clone` command
- The full output of your `cmake` configure command (after deleting your current build folder please)

**Comment by malton-ont** [comment]
We've recently run into this issue ourselves. Updating git resolved it, so I recommend you do likewise.
