### ISSUE TITLE
Requested kits [SQK-LSK109] not supported by barcoding configurations/Fast5 to Pod5 unclassified reads

### ISSUE THREAD

**Issue by lucyintheskyzzz** [nanoporetech/dorado#858]
Hi,

I tried to run dorado 0.7.0 on my older fast5 files converted to pod5 and I am still getting alot of unclassified reads:

![image](https://github.com/nanoporetech/dorado/assets/71407498/d1a82a03-1874-4ace-809c-235c423a10b5)

##ONR012021 sup 
/work/kvigil/Programs/dorado-0.7.0-linux-x64/bin/dorado basecaller /work/kvigil/Programs/dorado-0.7.0-linux-x64/bin/dna_r9.4.1_e8_sup@v3.3 --recursive /ddnB/work/kvigil/sandiego/ONR012021/ONR012021/pod5   --kit-name SQK-PBK004 > /ddnB/work/kvigil/sandiego/ONR012021/ONR012021/pod5/sup/ONR012021.calls.bam

[final_summary_FAP12777_5c9e5cd4.txt](https://github.com/user-attachments/files/15515891/final_summary_FAP12777_5c9e5cd4.txt)

Any thoughts? 

I am currently running Guppy 6.5.7 with the hac model on these samples to see if I still get alot of unclassified reads:
/work/kvigil/Programs/ont-guppy-cpu/bin/guppy_basecaller --input_path /ddnB/work/kvigil/sandiego/ONR012021/ONR012021/fast5_pass/fast5_all --save_path /ddnB/work/kvigil/sandiego/ONR012021/ONR012021/fast5_pass/guppy --config dna_r9.4.1_450bps_hac.cfg --enable_trim_barcodes --barcode_kits SQK-PBK004

Guppy question:

I am getting this error when I try to run Guppy with the hac model using the SQK-LSK109 kit:
[guppy/error] barcoding::BarcoderNode::setup_new_configuration: Exception adding client id '0' to barcoder node: Requested kits [SQK-LSK109] not supported by barcoding configurations.
[guppy/error] main: Requested kits [SQK-LSK109] not supported by barcoding configurations.
[guppy/warning] main: An error has occurred. Aborting.
 
/work/kvigil/Programs/ont-guppy-cpu/bin/guppy_basecaller --input_path /ddnB/work/kvigil/sandiego/ONRserum072621/ONRSerum072621/ONRSerum072621/20210726_1922_MN23650_FAQ78908_dd3e492f/fast5_pass/fast5_all --save_path /ddnB/work/kvigil/sandiego/ONRserum072621/ONRSerum072621/ONRSerum072621/20210726_1922_MN23650_FAQ78908_dd3e492f/fast5_pass/guppy --config dna_r9.4.1_450bps_hac.cfg --enable_trim_barcodes --barcode_kits SQK-LSK109

any suggestions on this?

**Comment by lucyintheskyzzz** [comment]
@malton-ont here is an example of  how I am running my demux:
##demux using dorado

/work/kvigil/Programs/dorado-0.7.0-linux-x64/bin/dorado demux --output-dir /ddnB/work/kvigil/baratariabay/ONR020624_seawater/ONR020624b/ONR020634b/20240209_1215_P2S-01216-B_PAS50263_bafbc4ce/sup/barcodes --no-classify /ddnB/work/kvigil/baratariabay/ONR020624_seawater/ONR020624b/ONR020634b/20240209_1215_P2S-01216-B_PAS50263_bafbc4ce/sup/ONR020624b.calls.bam

**Comment by lucyintheskyzzz** [comment]
@malton-ont For the guppy issue. I have one set of sequencing samples where I used SQK-PBK004 and the rest of my samples I used SQK-LSK109.

**Comment by malton-ont** [comment]
@lucyintheskyzzz,

The second demux command looks correct, but it seems to be using different paths to your basecall command above. Are you certain that the demux there was also performed with `--no-classify`?

SQK-LSK109 is not a barcoding kit. You can sequence the data, but it won't have barcodes.

**Comment by lucyintheskyzzz** [comment]
I use --no-classify for all my samples what I posted was an example of the code I use and I just change the absolute paths on my script for the different samples. The text file I posted is how I figured out what kits were used for this set of samples that were sequenced in 2021. I am trying to re-basecall them using the "sup" model so I can use medaka polishing after Canu which requires hac and higher models.

**Comment by lucyintheskyzzz** [comment]
@malton-ont How do you suggest I run the SQK-LSK109 samples? - how would you change my code below, should I add --no-trim to my basecalling code?

##ONR012021 sup 
/work/kvigil/Programs/dorado-0.7.0-linux-x64/bin/dorado basecaller /work/kvigil/Programs/dorado-0.7.0-linux-x64/bin/dna_r9.4.1_e8_sup@v3.3 --recursive /ddnB/work/kvigil/sandiego/ONR012021/ONR012021/pod5   --kit-name SQK-PBK004 > /ddnB/work/kvigil/sandiego/ONR012021/ONR012021/pod5/sup/ONR012021.calls.bam
##demux using dorado

/work/kvigil/Programs/dorado-0.7.0-linux-x64/bin/dorado demux --output-dir /ddnB/work/kvigil/sandiego/ONR012021/ONR012021/pod5/sup/barcodes --no-classify /ddnB/work/kvigil/sandiego/ONR012021/ONR012021/pod5/sup/ONR012021.calls.bam

**Comment by malton-ont** [comment]
Also, I see your oyster samples are a different kit. Can you run those without `--no-trim` as well for comparison?

**Comment by lucyintheskyzzz** [comment]
Hi @malton-ont so I ran the older samples on Dorado with --no-trim and I still get alot if unclassified.bam
![image](https://github.com/nanoporetech/dorado/assets/71407498/5d0b8eed-9d97-4216-afbb-b2c084ba16f7)

**Comment by malton-ont** [comment]
Ah, I think I see the issue. According to the final_summary file you attached, this data is from a FLO-MIN111 flowcell. This uses R10.3 chemistry, and cannot be basecalled with an R9.4.1 model. Dorado doesn't support basecalling with this chemistry at all I'm afraid - there are no models for it.

**Comment by lucyintheskyzzz** [comment]
ok thanks! I actually re-sequenced these sample In 2024, but I wanted to see if I can re-basecall the older using a higher model in dorado and combine the older reads with the newer reads, but it seems to challenging to figure out at this point. Thanks for your help though! I will probably just use my 2024 re-sequenced samples.

**Comment by lucyintheskyzzz** [comment]
So I used some other sequences and tried the --no-trim and I actually got a little more unclassified.bam went from 4,720,870 to 4,845,476

##ONR100623_seawater sup use this kit EXP-NBD104
/work/kvigil/Programs/dorado-0.7.0-linux-x64/bin/dorado basecaller /work/kvigil/Programs/dorado-0.7.0-linux-x64/bin/dna_r9.4.1_e8_sup@v3.3 --no-trim --recursive /work/kvigil/baratariabay/ONR100623_seawater/20231006_1648_MN18851_FAW76720_acec0fdf/pod5_pass --kit-name EXP-NBD104 > /work/kvigil/baratariabay/ONR100623_seawater/20231006_1648_MN18851_FAW76720_acec0fdf/sup/ONR100623_seawater.calls.bam

##demux using dorado

/work/kvigil/Programs/dorado-0.7.0-linux-x64/bin/dorado demux --output-dir /ddnB/work/kvigil/baratariabay/ONR100623_seawater/20231006_1648_MN18851_FAW76720_acec0fdf/sup/barcodes --no-classify /ddnB/work/kvigil/baratariabay/ONR100623_seawater/20231006_1648_MN18851_FAW76720_acec0fdf/sup/ONR100623_seawater.calls.bam

![image](https://github.com/nanoporetech/dorado/assets/71407498/25381292-c18d-4142-810f-8d8fcd71485a)
