### ISSUE TITLE
dorado 0.7.0      --batch_size  error

### ISSUE THREAD

**Issue by markme123** [nanoporetech/dorado#861]
# Issue Report
dorado 0.7.0     --batch_size  error
## Please describe the issue:
An error was reported when using the dorado --batch_size parameter
*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version:0.7.0
- Dorado command:dorado-0.7.0-linux-x64/bin/dorado basecaller -r   --batchsize 3392  -x "cuda:0"   /data/user/jiangmian/soft/model/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 ../basecalled > basecelled.bam
- Operating system:ubuntu20.04
- Hardware (CPUs, Memory, GPUs):A800
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.): 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs
[2024-06-02 01:39:09.844] [info] Running: "basecaller" "-r" "--batchsize" "2048" "-x" "cuda:0" "/data/user/jiangmian/soft/model/dna_r10.4.1_e8.2_400bps_sup@v5.0.0" "/data/user/benagen/dorado_0.7_test/20240524-SSL0002-PAW65308-P05/basecalled"
[2024-06-02 01:39:09.884] [info] > Creating basecall pipeline
[2024-06-02 01:39:11.520] [warning] cuda:0: Requested batch size 2048 exceeds maximum safe estimated batch size 1024.
[2024-06-02 01:39:11.520] [info] cuda:0 using chunk size 12288, batch size 1024
[2024-06-02 01:39:12.223] [error] CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
Exception raised from gemm<c10::Half> at /pytorch/pyold/aten/src/ATen/cuda/CUDABlas.cpp:427 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f62ab5879b7 in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f62a4b0c115 in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #2: <unknown function> + 0xa8fd141 (0x7f62ab44c141 in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #3: <unknown function> + 0xa915c7d (0x7f62ab464c7d in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #4: at::native::structured_mm_out_cuda::impl(at::Tensor const&, at::Tensor const&, at::Tensor const&) + 0x4a (0x7f62ab465eaa in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #5: <unknown function> + 0xa61213d (0x7f62ab16113d in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #6: <unknown function> + 0xa6121c0 (0x7f62ab1611c0 in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #7: at::_ops::mm::call(at::Tensor const&, at::Tensor const&) + 0x161 (0x7f62a60669c1 in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #8: <unknown function> + 0x49f3b05 (0x7f62a5542b05 in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #9: at::native::matmul(at::Tensor const&, at::Tensor const&) + 0x49 (0x7f62a5542fa9 in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #10: <unknown function> + 0x5a58f30 (0x7f62a65a7f30 in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #11: at::_ops::matmul::call(at::Tensor const&, at::Tensor const&) + 0x161 (0x7f62a616b301 in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #12: torch::nn::LinearImpl::forward(at::Tensor const&) + 0x100 (0x7f62a8bb5f90 in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #13: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0xa22cdc]
frame #14: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0xa2606d]
frame #15: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0xa2c59a]
frame #16: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0xa183dd]
frame #17: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0xa2376a]
frame #18: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0x9fd202]
frame #19: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0xa34699]
frame #20: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0xa347c8]
frame #21: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0xa3374b]
frame #22: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0x95e791]
frame #23: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0x86ced8]
frame #24: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0x86cc8b]
frame #25: <unknown function> + 0x114df (0x7f62a06f14df in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #26: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0x86d2ef]
frame #27: /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/dorado() [0x86f060]
frame #28: <unknown function> + 0x1196e380 (0x7f62b24bd380 in /data/user/jiangmian/soft/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #29: <unknown function> + 0x8609 (0x7f62a06e8609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #30: clone + 0x43 (0x7f629fb40353 in /lib/x86_64-linux-gnu/libc.so.6)

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by HalfPhoton** [comment]
Please remove your batchsize argument to use auto batchisze or reduce the value of the batchsize you're setting. 
The value you're using is too large for the v5 model architecture.
