### ISSUE TITLE
Wrong values in sm & sd SAM tags

### ISSUE THREAD

**Issue by vadanamu** [nanoporetech/dorado#874]
# Issue Report

## Please describe the issue:
After updating to Dorado 0.7.0, the sm and sd tag in the output BAM files contain 'wrong' values.
As far as I understand, sm tag is the mean of the signal and sd tag is the dispersion of the signal.

Previous to Dorado 0.7.0 (In my case, 0.4.3), the sm and sd tags contained values such as:
no.	sm	sd
0	76.47213745117188	17.07990837097168
1	77.17393493652344	16.9936466217041
2	76.5774154663086	16.562335968017578
3	77.08621215820312	15.872238159179688
4	73.68836212158203	14.405781745910645
5	77.355224609375	15.354665756225586
6	77.49559020996094	16.30354881286621
7	75.54226684570312	17.252431869506836
8	78.10965728759766	16.47607421875
9	76.51892852783203	17.07990837097168
10	78.1213607788086	15.268403053283691

These values could be used to normalise the signal.

But in Dorado 0.7.0, the sm and sd tags contain values such as:
no.	sm	sd
0	-796.1599731445312	0.008466074243187904
1	-820.1599731445312	0.008466074243187904
2	-825.1599731445312	0.008466074243187904
3	-820.1599731445312	0.008466074243187904
4	-808.1599731445312	0.008466074243187904
5	-793.1599731445312	0.008466074243187904
6	-808.1599731445312	0.008466074243187904
7	-833.1599731445312	0.008466074243187904
8	-809.1599731445312	0.008466074243187904
9	-806.1599731445312	0.008466074243187904
10	-826.1599731445312	0.008466074243187904

The sm tags seems to have been multiplied by -10, and the sd tags all contain the same value(0.008466..)
I think that this is a bug introduced in 0.7.0.
I'd be grateful for any fix, update, or workaround. 

## Steps to reproduce the issue:
Run RNA004 basecalling on same POD5 data using dorado 0.7.0 and previous versions. 
When you compare the BAM/SAM files, will see the differences in the sm and sd tags.

## Run environment:
- Dorado version: 0.7.0
- Dorado command: dorado basecaller -b 400 --chunksize 12000 -x cuda:all  --min-qscore 0 --emit-moves --estimate-poly-a rna004_130bps_sup@v5.0.0 {my_pod5_directory}
- Operating system: CentOS 7
- Hardware (CPUs, Memory, GPUs): 4xA100, 128 cores, 2TB RAM
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): POD5
- Source data location (on device or networked drive - NFS, etc.): NFS
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by vadanamu** [comment]
After going through the repo, I see that the signal normalisation method has changed for the new basecaller models.
Maybe the dorado/documentation/SAM.md file needs to be updated. 
It still says 'pA to ~0-mean/1-sd', but it's not correct for the new basecaller models.

**Comment by vadanamu** [comment]
Additionally, in my opinion, some documentation, notes, or warning messages regarding this change might be helpful for users who use the sm and sd tags emitted by Dorado.

**Comment by iiSeymour** [comment]
This was a bug and has been fixed in v0.7.2 - thanks @vadanamu.
