### ISSUE TITLE
Dorado correct performance?

### ISSUE THREAD

**Issue by tnn111** [nanoporetech/dorado#883]
Are there any performance numbers for dorado correct? I'm interested in using it to correct ~120 Gbp (a full PromethION flow cell) and it'd be great to have some idea of the performance to expect. Like is it a 100 A100 hours or is it more like 1,000 :-) Thanks!

**Comment by HalfPhoton** [comment]
Dorado read correct performance is dominated by CPU usage during the alignment phase and the GPU is a relatively small part. Your A100 should be more than able to keep up with the GPU load. I would however recommend using a machine with the best CPU for this task even with a slightly weaker GPU. 

We're actively looking at improving the performance of read correction and we will push updates as soon as we're able.

Best regards,
Rich
