### ISSUE TITLE
Dorado "Failed to determine sequencing chemistry from data. Please select a model by path"

### ISSUE THREAD

**Issue by legoscientist** [nanoporetech/dorado#885]
# Issue Report

## Please describe the issue:

Up until now I have been using Dorado 0.6.2 installed locally on my area of our HPC, for basecalling. Yesterday that suddenly stopped working without any change in my script. I have copied my command below. I tried re-extracting dorado from the tar.gz file, and also tried the same with 0.7.1 (latest release). The error I am getting is "[error] Failed to determine sequencing chemistry from data. Please select a model by path"

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version: 0.6.2 and 0.7.1
- Dorado command:  ./dorado basecaller sup --no-trim --kit-name SQK-NBD114-24 --min-qscore 10 --device cuda:0 $IN > $OUT

**Comment by StephDC** [comment]
[Additional Info Needed]

Assuming that you are using pod5 files. Do you know which kit and flowcell is used to generate the data?

There are a few unsupported combinations of kit and flowcell, such as R9 R10 mix-and-match like FLO-FLG001 + SQK-NBD114-24, that would result in such error. These combinations do not make sense and shall never be used together.

Follow the issue report guide and run the dorado basecaller with -v, and paste the output as well. That would be a great help to the troubleshooting process.

**Comment by legoscientist** [comment]
Forgot to update here! I eventually got it running, simply by re-copying and pasting the file path! I wonder if I had got a rogue space in there somewhere. Very odd, but as I say, did get it running with a downloaded, locally stored, model :)

> [Additional Info Needed]
> 
> Assuming that you are using pod5 files. Do you know which kit and flowcell is used to generate the data?
> 
> There are a few unsupported combinations of kit and flowcell, such as R9 R10 mix-and-match like FLO-FLG001 + SQK-NBD114-24, that would result in such error. These combinations do not make sense and shall never be used together.
> 
> Follow the issue report guide and run the dorado basecaller with -v, and paste the output as well. That would be a great help to the troubleshooting process.

**Comment by yesimon** [comment]
I am having this error with latest dorado 0.7.2 on a supported combination: SQK-NBD114-24 with MIN114. I need to download the model separately and specify the full model path for it to work properly.

**Comment by malton-ont** [comment]
@yesimon,

That should indeed be a supported combination. Are you basecalling pod5 files? If so, can you run:
```
pod5 inspect debug <data.pod5> | grep -E "flow_cell_product_code|sequencing_kit"
```
and post the output.

If you are basecalling from fast5 files, automatic model detection is not available and you should convert your data.

**Comment by yesimon** [comment]
```
        flow_cell_product_code: FLO-MIN114
        sequencing_kit: sqk-nbd114-24
```

Here's the actual command and error. It appears that `sup@latest` works now.

```
$ dorado basecaller --kit-name SQK-NBD114-24 dna_r10.4.1_e8.2_400bps_sup@v5.0.0 pod5 > test.bam

[2024-06-27 17:56:52.920] [info] Running: "basecaller" "--kit-name" "SQK-NBD114-24" "dna_r10.4.1_e8.2_400bps_sup@v5.0.0" "pod5"
terminate called after throwing an instance of 'std::runtime_error'
  what():  toml::parse: file open error -> dna_r10.4.1_e8.2_400bps_sup@v5.0.0/config.toml
Aborted (core dumped)

$ dorado basecaller --kit-name SQK-NBD114-24 sup@latest pod5 > test.bam
[2024-06-27 17:58:18.168] [info] Running: "basecaller" "--kit-name" "SQK-NBD114-24" "sup@latest" "pod5"
[2024-06-27 17:58:18.203] [info]  - downloading dna_r10.4.1_e8.2_400bps_sup@v5.0.0 with httplib
[2024-06-27 17:58:20.838] [info] > Creating basecall pipeline
```

**Comment by malton-ont** [comment]
@yesimon,

`dorado` interprets `dna_r10.4.1_e8.2_400bps_sup@v5.0.0` as a path, and therefore expects it to be present in the current working folder. As you've found, if you want to use automatic model detection then you don't need to specify the chemistry. You can find more info on automatic model selection [here](https://github.com/nanoporetech/dorado?tab=readme-ov-file#automatic-model-selection-complex).

**Comment by ZTehrani** [comment]
Hello Dorado Team,

I am getting the same error, running Dorado version 0.7.2. 

Got this after running the above mentioned command: 

pod5 inspect debug <data.pod5> | grep -E "flow_cell_product_code|sequencing_kit"

flow_cell_product_code: FLO-PRO114M
        sequencing_kit: sqk-lsk114


And here is my Dorado command: 

dorado basecaller hac <path to pod5 files/> --device cuda:all > calls.bam

No barcoding kit want to be used for basecalling

**Comment by ZTehrani** [comment]
Hello Dorado Team,

I am getting the same error, running Dorado version 0.7.2.

Got this after running the above mentioned command:

pod5 inspect debug <data.pod5> | grep -E "flow_cell_product_code|sequencing_kit"

flow_cell_product_code: FLO-PRO114M
sequencing_kit: sqk-lsk114

And here is my Dorado command:

dorado basecaller hac --device cuda:all > calls.bam

No barcoding kit want to be used for basecalling

**Comment by pinkfairy57** [comment]
Hey everyone,

I am having a similar issue. I tried using different models to specify the chemistry but was unable to find the right one. So I tried doing the automatic model selection by

dorado basecaller hac --models-directory /path/to/models/ --no-trim /path/to/file.pod5 > /path/to/calls.bam

I also tried hac@latest in the place of hac.

The models directory has all the downloaded models I got from using “dorado download --model all”

The error I am getting is:

Running: "basecaller" "hac" "--models-directory" “/path/to/models/" "--no-trim" “/path/to/file.pod5"
[error] No supported chemistry found for flowcell_code: '__UNKNOWN_FLOWCELL__' sequencing_kit: 'SQK-LSK109' sample_rate: 4000
[error] This is typically seen when using prototype kits. Please download an appropriate model for your data and select it by model path
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not resolve chemistry from data: Unknown chemistry
Aborted (core dumped)

 When I did: pod5 inspect debug <data.pod5> | grep -E "flow_cell_product_code|sequencing_kit" It showed
sequencing_kit': 'sqk-lsk109
flowcell_type': 'flo-min106

Did I write the command correctly? If not, how else do choose an automatic model? Please help me.

**Comment by amirh-hajianpour** [comment]
@ZTehrani, the order of your arguments are not correct. Try the following command: 
`dorado basecaller hac --no-trim --device cuda:all [path to pod5 files/] > calls.bam`

@pinkfairy57 I believe the MODEL argument is mandatory, so your command should look like this:
`dorado basecaller hac --no-trim /path/to/model/  /path/to/file.pod5 > /path/to/calls.bam`

Please let me know if these solutions work.
