### ISSUE TITLE
Whether reads are trimmed adapters when running dorado duplex

### ISSUE THREAD

**Issue by hungweichen0327** [nanoporetech/dorado#889]
Hi,

I would like to confirm whether the reads of the output bam file (e.g. duplex_sup.bam in the below script) are trimmed adapters when running `dorado duplex`.

dorado version: v0.7.0

script:
`dorado duplex "/model/dna_r10.4.1_e8.2_400bps_sup@v5.0.0/" ./pod5/ > duplex_sup.bam`

PS:
If adapters of reads are not trimmed, which kinds of reads below are not trimmed? 
- `dx:i:1` for duplex reads.
- `dx:i:0` for simplex reads which don't have duplex offsprings.
- `dx:i:-1` for simplex reads which have duplex offsprings.

But I think the default of dorado basecaller trimming is enable based on the README as described:
```
By default, dorado basecaller will attempt to detect any adapter or primer sequences at the beginning and ending of reads, and remove them from the output sequence.
```

Thank you.

**Comment by malton-ont** [comment]
Hi @hungweichen0327,

`dorado duplex` does not perform any trimming. The line from the `ReadMe.md` that you quote is specifically regarding the `dorado basecaller` command.
