### ISSUE TITLE
Stereo duplex error on mac M1 ultra and M2

### ISSUE THREAD

**Issue by tgogakos** [nanoporetech/dorado#89]
Hi -- 

I'm trying to perform stereo duplex calling on two Mac computers (one with the M1 ultra and one with the M2 chip) and I get the following error when attetmpting the dorado duplex step:

[error] Stereo Duplex currently unsupported on Metal

dorado basecaller and pair commands run to completion. I'm using fast5 instead of pod5, for now. 

Any ideas for reasons/workarounds? 

Thanks...

**Comment by vellamike** [comment]
Hi @tgogakos , the error is currently accurate - Stereo Duplex has not been implemented for Apple Silicon (M1, M2 etc) but will be added in a future release. In the meantime, it is possible to run Stereo Duplex calling on Nvidia hardware.

**Comment by tgogakos** [comment]
Thanks! Indeed, I was able to stereo call on an NVIDIA GPU. It was a bit slow (8 GB; ran with -b 128 option), so excited for M1/M2 future compatibility.

**Comment by vellamike** [comment]
The most recent version of  Dorado (0.2.1) is substantially faster on  Nvidia hardware. You may wish to try that again?

**Comment by tgogakos** [comment]
Still extremely slow. Actually, duplex basecalling with the sup model does not run despite various -b values tried. Basecalling (simplex and duplex) works only with the fast model.

**Comment by vellamike** [comment]
Which GPU model are you using?

**Comment by tgogakos** [comment]
NVIDIA GeForce RTX 3060 (8 GB) -- I know it's probably too weak for these purposes...
