### ISSUE TITLE
dorado correct output

### ISSUE THREAD

**Issue by katiecdillon** [nanoporetech/dorado#890]
Not an issue but a question. Why does dorado correct output FASTA and not FASTQ? I would like to run NanoPlot (or something similar) to get a quality summary from the dorado correct output. I ultimately want to see how the quality changes between reads not run through dorado correct and reads that were run through dorado correct. Thank you!

**Comment by malton-ont** [comment]
Hi @katiecdillon,

Looking at the [code here](https://github.com/nanoporetech/dorado/blob/release-v0.7/dorado/read_pipeline/CorrectionNode.cpp#L40), it looks like we're not storing a qstring in the corrected record so I'm not sure there'd be much benefit from fastq over fasta anyway.
