### ISSUE TITLE
"dorado correct" failed to stop running

### ISSUE THREAD

**Issue by yzhang-github-pub** [nanoporetech/dorado#891]
I have a down-sampled data of 1000 reads. Read length stat is as follows:

num_seqs    sum_len        min_len      avg_len     max_len      Q1        Q2       Q3            N50       Q20(%)     Q30(%)
1,000           3,484,177         30            3,484.2      24,027      258      1,222    4,174.5       10,036   74.62         54.54

The command is: "dorado correct --model-path herro-v1 reads1000.fastq > reads.fasta"

Within one minute of running the command, the status reached 100%. But the program didn't exit. Instead it kept running seemingly forever (I waited for 60 min and killed the process). The output file modification timestamp and size never changed after the status reached 100%, indicating the program actually finished correction in 1 min, and after that it did nothing. 'nvidia-smi' showed two running processes of dorado:

    0   N/A  N/A     50784      C   ...n/dorado-0.7.1-linux-x64/bin/dorado    11602MiB 
    1   N/A  N/A     50784      C   ...n/dorado-0.7.1-linux-x64/bin/dorado    17172MiB

BTW, the corrected reads looked good.

**Comment by malton-ont** [comment]
Hi @yzhang-github-pub,

Thanks for reporting this issue. I think I can see how this can happen during shutdown, and we'll look to get a fix in for it in a future release. As you've noted, this should only occur after all the reads have been processed, so it shouldn't affect the results.

**Comment by malton-ont** [comment]
Hi @yzhang-github-pub,

Thanks for reporting this! I've been able to reproduce it here, and we'll aim to get a fix out in a future release.

**Comment by yzhang-github-pub** [comment]
@malton-ont Thanks for taking care of this!
