### ISSUE TITLE
Increased system RAM usage with dorado 0.7.1 & v5.0.0 models

### ISSUE THREAD

**Issue by samuelmontgomery** [nanoporetech/dorado#893]
Hi, 

I am seeing a much larger use of system RAM when using the v5.0.0 models with dorado 0.7.1
I have a PC with i7 13700K, 64GB of RAM and an RTX4090, as per the recommended specs for the P2 Solo 
Previously, basecalling would utilise ~20Gb of RAM in addition to the GPU VRAM, but with the new models all 64GB of system ram is being utilised as well

Is this something that will improve with model optimisation? Additionally, is this likely to be a bottleneck for basecalling outside of the GPU? 

Thanks - Samuel

**Comment by samuelmontgomery** [comment]
Thanks - I am running dorado basecaller sup --kit-name SQK-NBD114-96 pod5 >
calls.bam using dorado 0.7.1 on Windows

At the moment it's using 23.9GB of VRAM, and 63.4GB of RAM - weirdly when I
look at processes in Task Manager, dorado is only using ~2GB of RAM and I
cannot see where else it is being used, all other running processes make up
~1GB of RAM

I will have to get back to you later this week with a test dataset -
basecalling a rather large P2 run!

**Comment by samuelmontgomery** [comment]
Hi @malton-ont - have confirmed running v4.3.0 with dorado v0.7.1 only uses ~24GB of system RAM being used in total, with the dorado.exe task reporting specifically that it is using 15GB
When using the v5.0.0 models, Task Manager is reporting all shared GPU memory is being utilised, but is reporting dorado.exe is only used 1-2GB of system RAM as a process

Would just add this is using the Windows binary, and basecalling a large dataset 

This is the command used for v5.0.0 with the output

> C:\dorado_0.7.1\bin\dorado.exe basecaller sup --kit-name SQK-NBD114-96 --recursive C:\Nanopore\NPR008_14JUN24\no_sample > C:\Nanopore\NPR008_14JUN24\no_sample\basecalling\basecalling_sup_v5.0.0.bam
> 
> [2024-06-17 11:33:40.971] [info] Running: "basecaller" "sup" "--kit-name" "SQK-NBD114-96" "--recursive" "C:\Nanopore\NPR008_14JUN24\no_sample"
> [2024-06-17 11:33:41.347] [info]  - downloading dna_r10.4.1_e8.2_400bps_sup@v5.0.0 with httplib
> [2024-06-17 11:33:47.190] [info] > Creating basecall pipeline
> [2024-06-17 11:33:56.583] [info] cuda:0 using chunk size 12288, batch size 128
> [2024-06-17 11:33:56.863] [info] cuda:0 using chunk size 6144, batch size 128
> [==============================] 100% [05d:20h:49m:43s<00m:00s] Basecallingingling
> [==============================] 100% [05d:20h:49m:43s<00m:00s] Sorting output files
> [==============================] 100% [05d:20h:49m:43s<00m:00s] Sorting output files
> [2024-06-23 08:24:45.076] [info] > Simplex reads basecalled: 33280766
> [2024-06-23 08:24:45.077] [info] > Simplex reads filtered: 437
> [2024-06-23 08:24:45.077] [info] > Basecalled @ Samples/s: 3.463994e+06
> [2024-06-23 08:24:45.077] [info] > 33363974 reads demuxed @ classifications/s: 6.580049e+01
> [2024-06-23 08:25:08.156] [info] > Finished


Thanks!

**Comment by malton-ont** [comment]
@samuelmontgomery,

A few questions to follow up:
- Does this happen with a smaller dataset?
- Does this happen if you aren't barcoding?
- I'm confused that dorado would only report using 1-2GB but that your whole system RAM is in use. Are you looking at the "Working Memory" column in Task Manager, or something else?
- Is this memory in use constantly or is this a peak value?
- Can you check the output of running `tasklist` in the cmd line? That may give a better view of what is using the memory.

**Comment by samuelmontgomery** [comment]
- I'm confused that dorado would only report using 1-2GB but that your whole system RAM is in use. Are you looking at the "Working Memory" column in Task Manager, or something else?
  - Looking at the processes tab in Task Manager, the dorado.exe process running through cmd is currently reporting 3.7GB of system RAM in use, but opening Resource Manager reports 7GB of working memory for dorado.exe but 67GB of virtual memory currently reserved
- Is this memory in use constantly or is this a peak value?
  - constantly in use
- Can you check the output of running tasklist in the cmd line? That may give a better view of what is using the memory.
  - tasklist reports the same value as Resource Manager for working memory, not really any other processes using much RAM
- Does this happen with a smaller dataset?
  -  using a subset of 10% of the pod5 files, over the first five minutes the RAM usage slowly climbed until 40GB (~66%) physical memory usage, however this time it is accurately showing the usage for the dorado.exe process in Task Manager. It is still a constant usage though.
- Does this happen if you aren't barcoding?
  - without barcoding on the full dataset it is only utilising ~45GB of memory

**Comment by malton-ont** [comment]
Hi @samuelmontgomery,

Virtual memory shouldn't be an issue, it's only the physical memory I'd be concerned about. If this isn't causing performance issues I don't think it's anything to worry about.

**Comment by samuelmontgomery** [comment]
Thanks @malton-ont - when I originally created the issue it was showin 62.9GB of physical memory in use (out of 64GB), and I wasn't sure if it would have a performance impact on basecalling (and still can't tell as the 5.0.0 models are much slower anyway!)

It's the only thing the machine is being used for, so I will just keep an eye on it
