### ISSUE TITLE
How to use the barcode classification option

### ISSUE THREAD

**Issue by Narmatha99** [nanoporetech/dorado#899]
I want to use my pod5 files to basecall and eventually to assemble a hybrid genome with unicycler. For sequencing I used the FLO-MIN 114 MinION flow cell in combination with the SQK-RBK114-96 kit. How should I input this in the following command to get the right files (basecalled + barcoded) to continue with assembly:
$ dorado basecaller <model> <reads> --kit-name <barcode-kit-name> > calls.bam

My pod5 files are located in the Downloads file of the mac pro so the path to it would be something like: ~/Downloads/ 

Thanks!

**Comment by malton-ont** [comment]
Hi @Narmatha99,

Details of how to run barcoding can be found in the README.md file [here](https://github.com/nanoporetech/dorado?tab=readme-ov-file#barcode-classification).

**Comment by Narmatha99** [comment]
Hi @malton-ont 

Would I then put hac for <model> and the location of my pod5 files for <reads>? also for --kit-name <barcode-kit-name> would I say something like: --kit name <SQK-RBK114-96> ?

Thanks

**Comment by malton-ont** [comment]
@Narmatha99 
The readme says:
```
dorado basecaller <model> <reads> --kit-name <barcode-kit-name> > calls.bam
```
Replace the bits in `<>` with your specific values. So it sounds like you want:
```
dorado basecaller hac ~/Downloads/ --kit-name SQK-RBK114-96 > calls.bam
```

**Comment by Narmatha99** [comment]
@malton-ont 

Okay, that worked thank you. However maybe another question, I translated the calls.bam file to fastq file with samtools ($ samtools bam2fq SAMPLE.bam > SAMPLE.fastq)

How would I continue in unicycler then? Since this only generated one fastq file? 

Thank you

**Comment by malton-ont** [comment]
I'm not aware of `unicycler`, it's not one of our products, but I presume you want to demux the barcodes into separate files? You can do this by running either `samtools split` or `dorado demux --no-classify` on the barcoded bam file, then converting the results to fastq.
