### ISSUE TITLE
what's the GPU memory utilization rate? Does it depend on read length?

### ISSUE THREAD

**Issue by avilella** [nanoporetech/dorado#9]
what's the GPU memory utilization rate? Does it depend on read length?

**Comment by vellamike** [comment]
Hi @avilella - no GPU memory utilisation rate depends on Model, chunk size and batch size but not on read length.

The reason it does not depend on read length is that reads are "chunked" into fixed length segments before being processed by the GPU for performance reasons.

**Comment by avilella** [comment]
That's perfect, thank you. I think I can use the batch size to adjust the
basecalling of runs to our cluster of Nvidia cards with 4GB.

Does dorado know how to assign tasks to different GPU node ids?

**Comment by vellamike** [comment]
@avilella  at the moment (until Multi GPU is fully working) for assigning tasks to GPUs I suggest you use `--device "cuda:0"` and `export CUDA_VISIBLE_DEVICES=ID` where `ID` is the GPU you want to use.

**Comment by vellamike** [comment]
@avilella  at the moment (until Multi GPU is fully working) for assigning tasks to GPUs I suggest you use `--device "cuda:0"` and `export CUDA_VISIBLE_DEVICES=ID` where `ID` is the GPU you want to use.

**Comment by vellamike** [comment]
Closing this issue as I believe it's resolved. @avilella  please reopen it if you have any more queries.

**Comment by avilella** [comment]
I kicked of dorado on a simulated dna_r9.4.1_e8_fast@v3.4 dataset using an NVIDIA RTX A4000 (16GB VRAM) GPU.

The memory usage with the different `--batchsize N` options is shown below:

```
1 = 1664MiB / 16117MiB
100 = 2466MiB / 16117MiB
1000 = 9615MiB / 16117MiB
2000 = 16050MiB / 16117MiB
```

So `--batchsize 2000` is the optimal for a 16Gb VRAM Nvidia GPU. Full command-line:

```
dorado basecaller --device cuda:0 --batchsize 2000 --remora-threads 1 /data/ONT/dorado/dna_r9.4.1_e8_fast@v3.4 . > calls.sam
```

**Comment by vellamike** [comment]
Maximising the utilised VRAM with the biggest possible batch size to increase performance is a good rule of thumb, but not necessarily something which always works. For example it is often the case that good batch sizes are powers of two or integer multiples of powers of two.
