### ISSUE TITLE
Basecalling slow?

### ISSUE THREAD

**Issue by LauraVP1994** [nanoporetech/dorado#90]
Hello!

I have sequenced 5 samples with barcoding on a R10 flow cell resulting in ~284 GB of fast5 data. I want to analyse this data using our GPU servers (see screenshot). 

![2023-02-10 14_47_49-vm-rstudio-02 - Remote Desktop Connection](https://user-images.githubusercontent.com/44169838/218108789-dd0e26a9-9bfa-4fd3-868f-7db8b06c6398.png)

The script that we have used (with slurm) is 

```

#SBATCH -J basecall_sarscov2_R10
#SBATCH --output=sbatch-%x-%j.out # j: job id, x: job name
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1

# Regular simplex basecalling
srun dorado basecaller dna_r10.4.1_e8.2_260bps_sup@v4.0.0 fast5/ --device cuda:all --emit-moves > /simplex_basecalling/unmapped_reads_simplex.sam

# Identifying read pairs
srun duplex_tools pair --output_dir /pairs_from_bam /simplex_basecalling/unmapped_reads_simplex.sam

# Duplex calling for paired reads
srun dorado duplex dna_r10.4.1_e8.2_260bps_sup@v4.0.0 fast5/ --device cuda:all --pairs /pairs_from_bam/pair_ids_filtered.txt > /duplex_basecalling/unmapped_reads_duplex.sam

# Demultiplexing (can be done on simplex / or duplex reads)
srun guppy_barcoder --device cuda:all --compress_fastq --records_per_fastq 0 --input_path simplex_basecalling/ --save_path simplex_guppy_basecalling/ --trim_barcodes

srun guppy_barcoder --device cuda:all --compress_fastq --records_per_fastq 0 --input_path duplex_basecalling/ --save_path duplex_guppy_basecalling/ --trim_barcodes

```

However, after 24 hours of running we only have a sam file for the simplex basecalling of 4.986 GB (coming from a FAST5 folder of 282GB). In a previous run we had a sam file of 4.894 GB for 14 GB of FAST5, so I'm a bit worried that this will takes days/weeks to complete. 

I'm thus hoping that someone can give me pointers how to make this faster without losing the quality of the superaccuracy basecalling. We want to look to low frequency variants so we need the highest quality possible?

Thank you!

**Comment by iiSeymour** [comment]
Hey @LauraVP1994 one immediate thing that jumps out is dorado is only running on one of the four GPUs here. Is this intentional? If not I think you want to increase `--gres=gpu:1`.

**Comment by iiSeymour** [comment]
Better multi-GPU scaling is one of the benefits of dorado. Pod5 is highly recommended for maximum performance, yes.
