### ISSUE TITLE
Rapid adapter trimming

### ISSUE THREAD

**Issue by diego-rt** [nanoporetech/dorado#904]
Hey guys, 

In version v0.6.2, rapid adapter trimming was apparently turned off according to the release notes. 

Has this been re-enabled in the latest v0.7 releases? Apparently II have around 10% adapters (as assessed by cutadapt) in my ULK114 data after running `dorado trim` and I'm wondering whether it is because of that?

Many thanks!

**Comment by HalfPhoton** [comment]
Rapid adapter trimming has not been re-enabled yet.

**Comment by diego-rt** [comment]
And is read splitting also disabled?

**Comment by HalfPhoton** [comment]
No, read splitting is active
