### ISSUE TITLE
Dorado correct killed without explanation

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [nanoporetech/dorado#907]
# Issue Report

## Please describe the issue:

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

I run 'dorado correct -v filtered_simplex_reads.fastq >output.fasta' this seems to run well for a few hours and then is killed. Without any used debug or error message about ~20% in. 

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

As above. 

## Run environment:
- Dorado version: 0.7.2
- Dorado command: correct
- Operating system: Ubuntu 20.04.6 LTS
- Hardware (CPUs, Memory, GPUs): 32 CPU, 125 GB RAM, 1vGPU —NVIDIA A100 SXM4 40GB
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): fastq
- Source data location (on device or networked drive - NFS, etc.): Network drive
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 112GB fastq input 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset). I can't find any logs

**Comment by malton-ont** [comment]
Hi @JasonJWilliamsNY,

I suspect you are running out of memory. From the `dorado correct` [documentation](https://github.com/nanoporetech/dorado?tab=readme-ov-file#read-error-correction):

> The error correction tool is both compute and memory intensive. As a result, it is best run on a system with multiple high performance CPU cores ( > 64 cores), **_large system memory ( > 256GB)_** and a modern GPU with a large VRAM ( > 32GB).

**Comment by JasonJWilliamsNY** [comment]
Thanks. I did get this to run on a much larger system. Without any specific memory error I couldn't be sure what happened.
