### ISSUE TITLE
Does dorado demux support duplex calls? 

### ISSUE THREAD

**Issue by MostafaYA** [nanoporetech/dorado#908]
# Issue Report

## Please describe the issue:

Does `dorado demux` support the duplex calls. Previously you mentioned this was not implemenetd yet #405? 

Thanks  

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version: 0.7.2
- Dorado command: `dorado duplex -r <model> <seq_dir>  > calls.bam && dorado demux calls.bam --sample-sheet  <path> --output-dir <dir> --kit-name SQK-NBD114-24 --emit-fastq`
- Operating system: Linux 
- Hardware (CPUs, Memory, GPUs):
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.): 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by malton-ont** [comment]
Hi @MostafaYA,

No, `dorado duplex` does not currently support the `--kit-name` parameter.

Running `dorado demux` on duplex called data _may_ work, but will likely have a high proportion of unclassified reads (especially for single-ended barcodes). We have not attempted to evaluate this in any detail.

**Comment by mprous1** [comment]
I have done it in two steps, dorado duplex first and then demux. There is quite a lot of unclassified reads, but still acceptable level (I think it was certainly less than 30% and maybe less than 20%). I'm surprised that this has not been evaluated before.

Would it be better to do standard basecalling with --kit-name first, then take the classified read IDs and split the pod5 files according to barcode and then do duplex basecalling separately for the samples? It would be rather annoying though and would mean basecalling everything twice. Might be worth maybe if the unclassified reads will be less than 10% in this way.

**Comment by chrismitbiz** [comment]
Are the full details of this workflow as described by @mprous1 available somewhere? Particularly, the steps from pod5 file splitting for duplex basecalling are unclear to me. 

Are any other polishing steps required once duplex basecalled? 
Thank you

**Comment by JWDebler** [comment]
I have a [script](https://github.com/JWDebler/nanopore_kit14_assembly/blob/main/basecalling.sh) that does pretty much that. 
1. simplex calling
2. simplex demux
3. use info from simplex demux to separate pod5s by barcode
4. duplex call separated pod5s

**Comment by chrismitbiz** [comment]
Thank you @JWDebler

**Comment by mprous1** [comment]
I compared the classification rate between duplex basecalling and standard basecalling (sup accuracy in both cases). At least for my data, the differences seem to be marginal. For two of my datasets, unclassified reads can make up 19% or 36% of the overall data in case of duplex basecalling versus 17% or 35% for standard basecalling, respectively.

Does not seem worthwhile to complicate the workflow and repeat the basecalling. Quite a large proportion of reads will be unclassified either way.
