### ISSUE TITLE
Duplex basecalling using pair list - many pairs ignored?

### ISSUE THREAD

**Issue by Delayed-Gitification** [nanoporetech/dorado#91]
Hi,

I've made Pod5 files and a pairs list to run with dorado duplex.

However, the output seems to ignore many of the pairs in the list, only performing duplex basecalling on a small fraction of them.

I have validated that the pairs are true duplexes.

Is there any reason why this might be? 

Thanks!

Oscar

**Comment by vellamike** [comment]
Hi, could you give some details on the input reads?

1. What is the full command you are using (Just as a sanity check) ?
2. What simplex model are you using to basecall?
3. What does the read length distribution look like?
4. What simplex accuracy are you observing for these reads?

**Comment by iiSeymour** [comment]
Dorado duplex will automatically pair your input reads for you in v0.3.0.
