### ISSUE TITLE
Only mentioned reads in the output in Dorrado correct

### ISSUE THREAD

**Issue by arslan9732** [nanoporetech/dorado#915]
In the Dorrado correct, there is a parameter `-l` which we can use to mention only the reads we want to correct. But the output produces all the reads, regardless of the mentioned reads. Is it possible to only produce the mentioned reads in the output instead of all reads?

**Comment by malton-ont** [comment]
Hi @arslan9732,

Thanks for raising this issue. It appears that parameter is currently not being applied anywhere. We'll look into this and try to get a fix in a future release.

**Comment by HalfPhoton** [comment]
This option has been removed from dorado correct in 0.7.3, it will be added again when the feature is available.
