### ISSUE TITLE
Feature request: output end_reason in BAM records

### ISSUE THREAD

**Issue by lkwhite** [nanoporetech/dorado#919]
We find the reason a read ended to be useful info when looking at direct RNA data. Since some modifications produce higher levels of unblocking events (example: panels K, L, M [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10187680/figure/RNA079290WHIF4/)), we use this information for both library QC and to look at differential 5´ end pileups between reads with different `end_reason` statuses.

While this is pretty straightforward for us to do with samtools and the sequencing summary file (or the pod5 API), this kind of analysis would be simplified (and thus likely to be leveraged by others) if Dorado could include this in a custom BAM field (maybe `ER`?) during basecalling.

**Comment by jayhesselberth** [comment]
I will add it could be interesting to eventually integrate processing such tags into ongoing development efforts in modkit.

**Comment by HalfPhoton** [comment]
Hi @lkwhite,
The decision has been made again not to add this feature as it is possible to use existing tools to perform this task. 

Kind regards,
Rich
