### ISSUE TITLE
Dorado Basecall: Error calling model for R9.4.1 sup quality with methylation

### ISSUE THREAD

**Issue by SouvilleL** [nanoporetech/dorado#922]
# Issue Report

## Please describe the issue:

When basecalling with the classic command format: "dorado basecaller sup,5mCG_5hmCG $in > $out" .
I obtain:

[2024-07-03 16:27:57.372] [info] Running: "basecaller" "sup,5mCG_5hmCG" "2023A257/20240614_1043_MN35911_FAX73231_41d24167/pod5"
[2024-07-03 16:27:57.393] [info]  - downloading dna_r9.4.1_e8_sup@v3.6 with httplib
[2024-07-03 16:27:58.687] [error] Failed to get modification model
[2024-07-03 16:27:58.687] [error] No matches for chemistry: dna_r9.4.1_e8, model_variant: sup, version: v3.6.0, mods_variant: 5mCG_5hmCG

## Steps to reproduce the issue:

If the chemistry is from R9.4.1 and calling methylation, Dorado first select the latest available model (v3.6) then search for modification model who does not exist for the last model.

Forcing version sup@v3.3 solve the issue

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version: 5.3 and 7.2
- Dorado command: dorado basecaller sup,5mCG_5hmCG $in > $out and dorado basecaller sup@v3.3,5mCG_5hmCG $in > $out
- Operating system: ubuntu 22.04
- Hardware (CPUs, Memory, GPUs): Xeon w9-3495X ,768 Go, RTX A6000
- Source data type : POD5
- Source data location (on device or networked drive - NFS, etc.):  on device
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB):  R9.4.1
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue): Any dataset produced on R9.4.1

**Comment by HalfPhoton** [comment]
Hi @SouvilleL,

Thanks for opening the ticket.

This behaviour is documented in the [README#automatic-model-selection-complex](https://github.com/nanoporetech/dorado?tab=readme-ov-file#automatic-model-selection-complex)

> Automatically selected modification models will always match the base simplex model version and will be the latest compatible version unless a specific version is set by the user. Automatic modification model selection will not allow the mixing of modification models which are bound to different simplex model versions.

.. and you found the correct resolution suggested by the error message which was to specify the model version. 

Closing this ticket as resolved as there doesn't seem to be an issue. 

Please re-open this if you believe this not to be the case.
