### ISSUE TITLE
UMI guided duplex or multiplex basecalling ?

### ISSUE THREAD

**Issue by RainerWaldmann** [nanoporetech/dorado#926]
Hi,

In both single-cell and bulk RNA sequencing, we use UMIs (Unique Molecular Identifiers). Two reads with the same UMI correspond to the same cDNA molecule. It would be great if we could feed information on reads corresponding to the same cDNA molecule into Dorado to perform combined basecalling of those reads. Currently, we generate consensus sequences from the basecalled reads. Combined basecalling should yield much higher accuracy. Do you see any way to achieve this?

Rainer

**Comment by HalfPhoton** [comment]
If I understand correctly using your current consensus approach is probably going to give you the best accuracy in the end. Even if you somehow used duplex basecalling in this use case which gave a higher "single-read" accuracy this still achieve the same consensus accuracy. So I don't believe this would be beneficial.

Kind regards,
Rich
