### ISSUE TITLE
Model specification using downloaded models

### ISSUE THREAD

**Issue by desmodus1984** [nanoporetech/dorado#929]
# Issue Report

## Please describe the issue:

I am running dorado in an HPC that doesn't allow connection to the outside.
I did download all the models to just have the mall in case I need them and now dorado tells about a positional argument error.
As mentioned before, output in bam format is senseless because most of the genome assemblers need fastq files, so bam output is useless.

I used the following command:
/home/juaguila/appz/dorado-0.6.2-linux-x64/bin/dorado basecaller sup \
        --emit-fastq /home/juaguila/appz/dorado-0.6.2-linux-x64/bin/ pod5/ > Ju760i10.fastq

And I got the error:
[2024-07-05 14:02:15.454] [info] Running: "basecaller" "sup" "--emit-fastq" "/home/juaguila/appz/dorado-0.6.2-linux-x64/bin/" "pod5/"
[2024-07-05 14:02:15.614] [error] Maximum number of positional arguments exceeded

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment: 
- Dorado version: 0.6.2
- Dorado command: /home/juaguila/appz/dorado-0.6.2-linux-x64/bin/dorado basecaller sup \
        --emit-fastq /home/juaguila/appz/dorado-0.6.2-linux-x64/bin/ pod5/ > Ju760i10.fastq
- Operating system: Linux
- Hardware (CPUs, Memory, GPUs): Titan 128 GB
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location (on device or networked drive - NFS, etc.):  on HPC
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB):  Flow cell 10.4 3 GB
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by HalfPhoton** [comment]
Hi @desmodus1984,

You've added `/home/juaguila/appz/dorado-0.6.2-linux-x64/bin/` into the the command for some reason which is causing the error.

```bash
/home/juaguila/appz/dorado-0.6.2-linux-x64/bin/dorado basecaller sup
--emit-fastq pod5/ > Ju760i10.fastq
```

If you need to find the models please symlink them into the current working directory.

Kind regards,
Rich

**Comment by desmodus1984** [comment]
Hi,

Sorry I don't understand.

According to the help file, the positional argument/code for model selection is:
  model                     	model selection {fast,hac,sup}@v{version} for automatic model selection including modbases, or **path to existing model directory** 

I am providing the path to the model since model directory didn't work before, and it doesn't work either.

/home/juaguila/appz/dorado-0.6.2-linux-x64/bin/dorado basecaller --min-qscore 5 --emit-fastq \
	-x "cpu" --trim \
	**_/home/juaguila/appz/dorado-0.6.2-linux-x64/bin/dna_r10.4.1_e8.2_400bps_sup@v4.3.0 \_**
	/home/juaguila/Ju760-2/20240509_2335_MN45470_FAY72467_160ccff2/pod5 \
	> Ju760.1.fastq

Could you tell how should I do this?
The job I am running is in folder /home/juaguila/Ju760-basecalling.
I don't understand why I need to symlink or how to do it; or which code should I use.
It is confusing whether I should use sup command or not.

Thanks;

**Comment by HalfPhoton** [comment]
You added *both* which is not permitted: 
```bash
/home/juaguila/appz/dorado-0.6.2-linux-x64/bin/dorado 
basecaller 
>>>sup<<<
--emit-fastq 
>>>/home/juaguila/appz/dorado-0.6.2-linux-x64/bin/<<< 
pod5/ 
> Ju760i10.fastq
```

Dorado will find the sup model for your data **without downloading it again** if the model directory (e.g. `dna_r10.4.1_400bps_sup@v4.3.0/`) exists in the current working directory.

You can do with without **copying** the model by creating a symbolic link (which you can google for the best explanation).

Make a symbolic link like this:

```bash
ln -s <target> <destination>

ln -s /path/to/model/dna_r10.4.1_400bps_sup@v4.3.0 dna_r10.4.1_400bps_sup@v4.3.0
```

This will create a new symbolic link named `dna_r10.4.1_400bps_sup@v4.3.0` which is a link to `/path/to/model/dna_r10.4.1_400bps_sup@v4.3.0` which is very cheap to create.
