### ISSUE TITLE
R9 modified basecalling

### ISSUE THREAD

**Issue by AlexanRNA** [nanoporetech/dorado#93]
Hi Dorado team! I am trying to run some modified basecalling using data from r9.4.1 flowcells. I downloaded (hopefully) all models.
Then, when running `dorado basecaller dna_r9.4.1_e8_sup@v3.3  /path/to/pod5/ --modified-bases 5mCG > modcalls.sam`, I get 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  could not find matching modification model for `dna_r9.4.1_e8_sup@v3.3`
``` 
I thus tried to run it with `dna_r9.4.1_e8_sup@v3.4` , since there is model for modified basecalling `dna_r9.4.1_e8_sup@v3.4_5mCG@v0` `dorado basecaller dna_r9.4.1_e8_sup@v3.4  /path/to/pod5/ --modified-bases 5mCG > modcalls.sam`, leading to 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown simplex model dna_r9.4.1_e8_sup@v3.4
```  
which makes sense, since there is no simplex model with that version. Therefore, I wanted to ask if it is possible run dorado using combination of simplex model`dna_r9.4.1_e8_sup@v3.3` and modification model `dna_r9.4.1_e8_sup@v3.4_5mCG@v0`? Or will `dna_r9.4.1_e8_sup@v3.4` simplex model become available at some point? Thanks!

**Comment by sklages** [comment]
You could try to omit `--modified-bases 5mCG` and provide the models with the full path:
```
dorado basecaller \
  $(pwd)/dna_r9.4.1_e8_sup@v3.3 \
  $DATA \
  --modified-bases-models $(pwd)/dna_r9.4.1_e8_sup@v3.4_5mCG@v0 \
  --verbose > basecalls.sam
```

**Comment by AlexanRNA** [comment]
Thanks for your reply! Indeed, that is one option,  but my worry is that `dna_r9.4.1_e8_sup@v3.3` and `dna_r9.4.1_e8_sup@v3.4_5mCG@v0` version models do not match (**v3.3** vs **v3.4**), so I am not sure if that would not lead to suboptimal basecalling accuracy.

**Comment by sklages** [comment]
@AlexanRNA - have you find a solution for you?

**Comment by iiSeymour** [comment]
`dna_r9.4.1_e8_hac@v3.4_5mCG@v0` and `dna_r9.4.1_e8_sup@v3.4_5mCG@v0` are misslabled are do match the `@v3.3` canonical models. I am fixing this now but as @sklages has pointed out you can use `--modified-bases-models`.

**Comment by iiSeymour** [comment]
Fixed in https://github.com/nanoporetech/dorado/commit/ee1e746b768de8abd956306c3c8fb81cd724bf48.
