### ISSUE TITLE
Dorado Modification Calling interpret

### ISSUE THREAD

**Issue by abcdtree** [nanoporetech/dorado#932]
# Issue Report

## Please describe the issue:

Dear Dorado team,

I ran dorado modification basecalling with Model `rna004_130bps_sup@v5.0.0` and `--modified-bases m6A` parameter. Is there any document or steps to help to interpret the output bam file?

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version: 0.7.0
- Dorado command: dorado basecaller ${model_home}/rna004_130bps_sup@v5.0.0 ${data_home}/pod5 --modified-bases m6A > XBB15.bam

I noticed that there are extra information at the end of the output bam file
```
MN:i:1077	MM:Z:A+a.,0,0,0,0,5,0,0,0,0,1,4,0,0,5,1,1,4,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,1,3,0,1,1,3,6,0,0,0,0,1,0,2,3,0,0,0,0,0,0,0,0,0,0,0,5,1,0,3,0,3,1,4,1,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,2,1,1,0,0,0,0,4,0,0,0,0,0,0,2,0,5,2,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,1,0,0,0,0,12,0,0,0,1,10,3,0,0,2,0,2,0,2,2,4,0,2,2,0,3,5,0,0,0,1,9,2,4,1,0,0,0,0,0,0;
ML:B:C,144,25,160,17,164,32,19,88,50,181,219,14,71,55,84,158,134,82,30,95,66,70,220,21,103,56,26,132,187,66,71,78,19,21,16,68,16,60,86,182,86,16,159,100,29,44,72,58,137,93,88,141,16,138,55,32,25,56,23,14,82,41,12,38,22,17,70,32,29,20,52,13,45,16,42,170,125,194,34,62,18,61,50,39,77,27,16,23,149,19,137,27,57,71,78,122,48,66,196,29,15,49,13,163,173,95,90,189,23,20,17,30,15,44,90,34,32,27,159,83,15,25,145,28,122,103,102,49,65,114,22,17,30,24,39,48,12,127,15,52,50,212,162,41,32,19,68,14,166,94,12,240,134,147,171,151,164,130
```
However, I have no idea what is this about.

Thanks,

Josh

**Comment by abcdtree** [comment]
found some documents online about the modification tags, Thanks

**Comment by lucy924** [comment]
@abcdtree Do you mind sharing a link to those documents? This stuff is sometimes difficult to find

**Comment by malton-ont** [comment]
@lucy924,

The modification tags are described in the SAM tags specification document at https://samtools.github.io/hts-specs/SAMtags.pdf. Other ONT-specific tags are described in [the dorado docs](https://github.com/nanoporetech/dorado/blob/release-v0.7/documentation/SAM.md).
