### ISSUE TITLE
Minor Documentation Fix: Parameter Names for Custom Barcodes

### ISSUE THREAD

**Issue by enc-wmatern** [nanoporetech/dorado#935]
I noticed a minor documentation issue.

The parameters list in the table here:
https://github.com/nanoporetech/dorado/blob/release-v0.7/documentation/CustomBarcodes.md#arrangement-options

are not the same as the parameters listed in the example .toml file. The example .toml file has the correct parameter names.

"mask_1_front" should be "mask1_front" etc.

**Comment by malton-ont** [comment]
Hi @enc-wmatern,

Thanks for reporting this! We'll get it fixed for a future release.

**Comment by HalfPhoton** [comment]
This has been updated in the [new documentation](https://dorado-docs.readthedocs.io/en/latest/barcoding/custom_barcodes/).
