### ISSUE TITLE
libkoi error

### ISSUE THREAD

**Issue by Knight-WP** [nanoporetech/dorado#940]
## Please describe the issue:
Hi, when i build dorado, I've encountered a very strange error, can you help me?
![mmexport1721057671607](https://github.com/user-attachments/assets/d05c4681-362e-4fe8-ab5a-0dd40d73882a)

**Comment by malton-ont** [comment]
Hi @Knight-WP,

Can you clear you build directory and post the full output of your configuration comand (`cmake -S . -B build`) please?
