### ISSUE TITLE
Question about modification call

### ISSUE THREAD

**Issue by kyleyhchan** [nanoporetech/dorado#941]
Hello, 
I have a question about modification calling. After basecalling and aligning the reads with Dorado (using sup, 5mC_5hmC), I visualized the reads with IGV and noticed that some bases do not have any modification calls.
<img width="2018" alt="image" src="https://github.com/user-attachments/assets/bdd66216-f8e1-47f4-8d0b-bba17eaee93d">

I know sometimes the color can be really light due to the low percentage so I click on it but it doesn't show me the percentage of 5mC and 5hmC.  

Is there any thing I can do to fix this issue? 

Thank you

**Comment by ArtRand** [comment]
Hello @kyleyhchan, 

Could you tell me which version of IGV you're using? Also, could you confirm that the modification calls are indeed missing with `modkit extract` ([docs](https://nanoporetech.github.io/modkit/intro_extract.html))? I would isolate just the reads at the positions you've highlighted like this:

```bash
region=... # the coordinates of the red box
$ modkit extract ${modbam} ${extract_tsv_filepath} --region ${region}
```

You could also pull out the reads missing the base modification calls by selecting them with `samtools view` and the `-N` option. If you have any additional questions regarding [modkit](https://nanoporetech.github.io/modkit/) feel free to open an issue there.

**Comment by malton-ont** [comment]
Dorado has a threshold value below which it does not report a base modification value as it is sufficiently certain that the base is not modified - could this be what is happening? The default value for this is 0.05, but this can be altered using the `--modified-bases-threshold` parameter.

**Comment by HalfPhoton** [comment]
We can check the value set for `--modified-bases-threshold` in the bam header.

```bash
samtools view -H calls.bam | grep "dorado"
```
