### ISSUE TITLE
Postprocess .bam file to filter for minimum read quality q-score?

### ISSUE THREAD

**Issue by faulk-lab** [nanoporetech/dorado#942]
This may or may not be a dorado problem but I will ask here since dorado might be the only solution.

I've used dorado basecaller to call a run and created a .bam file. I forgot to set a minimum q-score during basecalling. How can I filter the resulting bam to remove reads below a minimum q-score? 

samtools can only filter by 'mapping' score, not read PHRED score.

**Comment by faulk-lab** [comment]
Solved it. Can be achieved by `samtools view -b -e '[qs]>=10' file.bam > output.q10.bam`

**Comment by JMencius** [comment]
You can also try <https://github.com/JMencius/bamQVFilter>  if BAM does not have qs tag.
