### ISSUE TITLE
dorado RNA m6A basecall model

### ISSUE THREAD

**Issue by yinyuanmtu** [nanoporetech/dorado#944]
Dear developers,
I am wondering whether the dorado RNA base call models (both the m6A  DRACH motif model and all-context model) will work for rRNA and organellar RNAs. I have seen pretty good m6A base calling for poly(A) mRNA, but a lot of failed base calling for chloroplast RNAs, mitochondria RNAs and rRNAs. Note these different types of RNA that I mentioned are derived from same RNA 004 dataset. I would greatly appreciate your thoughts on this matter. Many thanks!

**Comment by HalfPhoton** [comment]
Hi @yinyuanmtu, this type question is probably best placed on the Nanopore Community.
