### ISSUE TITLE
Transient Gzipped Fastq Corruption Issue

### ISSUE THREAD

**Issue by BioWilko** [nanoporetech/dorado#948]
# Issue Report

## Please describe the issue:

Occasionally the GridION is producing corrupt gzipped fastqs (example read below), it is doing this non deterministically as far as I can tell, rebasecalling the pod5 containing the corrupted read leads to an uncorrupted fastq. In a recent run I observed 3 separate instances, this is a problem I have observed previously with Guppy on the same grid so I can't rule out some sort of bizarre hardware issue.

An example read (note the various invalid characters in the sequence line):
```
@1aebd7ad-ceff-4e8c-ac3f-71e000569d13 runid=cc28fea77367c212a92e8be15e3924bac5874b48 read=18536 ch=118 start_time=2024-07-15T18:02:31.086869+00:00 flow_cell_id=FAY25688 protocol_group_id=Harriet_16S_rep2 sample_id=Harriet_16S_rep2 barcode=barcode02 barcode_alias=barcode02 parent_read_id=1aebd7ad-ceff-4e8c-ac3f-71e000569d13 basecall_model_version_id=dna_r10.4.1_e8.2_400bps_hac@v4.3.0
TGTTGCACCTCGTTCAGTTACGTATTGCTAAG0.4.AACAGACGACTAC.AACGGAATCGACAGCACCTTACGGTTACCTTGTTACGACTTCACCCCAGTCGCTGTGTGTGCCGTGGGCAGTAGCTAATTTAGCATCCTGACTTAAG0C.AACAC.ACTCCCATGGTGTGACTGGCAGTFGAC1GrcoCAGTCTA<*TAGCHde=ACTGTGTAAGAATTTGTATTTATTTACCCCGACTFGACACTAGTFFGACACATAACATACTCTAGTGTGTATGGTAAGGCTCGTACCGACCCGACTGGGCAFFGAGACACAFFGFGACrcoCCGTAATTTATGCCTAATTTCATAACTAACTTAGCTCCCCCCCCGACCCGFGACCAcoCCCATCAcCAcCAcCCCTTAAACTGGCACAcCTAAGTFFTAGCCTGACCCAGTAATTTAGTATAAGGCTAAAAFFGAGAGGTFFCTAACCGA1GrcoCTA<*TAGCCTCCCCAGTAGTGCTCCCGCTGFGACGACrcGTAAFFTGCTAAAGGTTGCToCCTCCCCCAcGTATAFFTGGTTAACFFTAGFTGCGTATGCToCFCTAACTTAFFTAACCTGCACAAACCGCGACTCCATA<*CCGACCCAGAGTGCTTAACCAcoCCCAATAFAcCTGTGTAAFFTTACCGACEFGAACHE1EGGTGTCCATACCGACCCATAFGACAAACFGAFAcTGCToCFCACHCTCCACACTATAFACTGACTcCTGAGGTAFFTGCToCCHE1ETAACCTGTAATGACCCATA<CHECGACCGACCTAAAAGTFFGFTGToCFCGACCHE1ACCCGACCCTTAFAAAAFAcCoCCCAAAFFTAAGCAcoFFTGGTAACFACHCTAGCAAAACAAACHECHCTAGCAcACHEHEHCAcoACAAAcCocCTGAAAAFTGToCAcoFTGAACCGGTTGAGGoCCFTGHECHCGCToGCToCcACHCCCTECGACATACTGAHCCCTGToTGGTTCCTCoCFCoCAcFTGACHCCGACEAACFAEGGTAcFTGGCToFFTGGAACCCCTGAFTGCoCCCGAACCTGACGACCAAACTACTHCAcoACACCCGCTCoAACFCFCCCTECCGCGCFTGCCCTCHEHEGGTACoATAcFTGCFTEGGTCoAAACHGTTGAFAcFCFCoCCCACTECATAcTAGCACGACEGCTCoTGGCACGACCCAcTGToCATGToTAGFTTcCTTGACHCCcTGTCCCTGTGACGGACCAACCCCGAFCoCFCCCoCCTAGCCTAGCACACTAcFTGAGGoCoCGTCCcFTGHCAcACCCFTGACFCCoAAACHGTcCocGCTCoFCCoFCoCcACFCCFCCCoAAACCFCTCCcFCCAGCACTATAcTGCToFTGACCCTEATACoAEHCACCCACoTACAGCTATAcTGTGCTATATcFCFCCcFACACCcCCFCCCoAGTAGoATAEAToCcACGCToFCCCTAGCTACoAGCTATAFAcFTGTCTAcCCFAGoACocGATAcCGACoCCCACoAAcCocCCCoAcCGoACoTAGCCTcFCFAEHG
+
$$$$#$$$$$$'6:CECDBA@>=87888<=>HGFHSHIA=?:TAGDEEKA@ABBCBCHILIGHIFHHFLOKJMGDEIGLSSLPMSS<<;<;3///1/)))3446:988=8;<>>CHIJRQOJDECDJSKRSIISFJIILQIORJIKSKJHPJJPEGKIKINQHSLFIKI>>>(&&&*))*/..+*(&&%&+.,*))*)'&%%&&/0;BCEDSSJMSLSFEFDFJGGIIEJGGGLFBBQHNLJRGJKGFJFFDPSMSSFIFSEEAE:JGGJOIJGJISSILISSDDDGFGOFHHHMKEJHFSOGFFFFJMJSHDC;480..66<BD9988:.---:76_id---/,/;:;;=SLKFLHFHSKPHGFFDGKE?@?@>96644+)))-3223BDHJHHJFCCA@EECA@@CIIKHFCEKKLIFDLLSSSJLKKIHLQLJLPMIIKIJKKLRJKFKGESBACKFEEFJ@><211/$%%(CRLHFSDISCBCDKGC@ACBBCMLDEEGHJOHGEHGISJCECDMSIFGIHLHMHJJJFSKSSSMILFFKHFKFJMKJJGSDFKGG<JPJFEIFGGHJKEHFGLSGJLPHMQEGHKSIONPSHFKLSSKOKJFKISSSSDDABLIJSRSJOLFIHGLIMHJFCFHSNKKSGDGH>BCFAB;<??IGJOJNHSKGSHHDEHMKFJ@@CADBB><<<>FFFFJCA@BBCA=<;78NaECDMHJOHGSHHFDMHJA@EIIBAPEHEDFFECBBQHHEDDCIGSSHGHFKIGKHJ@ABC@?@C??<<..-.3<c585=?==<<=??@CHK>@;)FE@;=9:CGD@?EKABBDRSIFABLFLOKQGFJGFGJJJRHSJHFKMSKMMSNEJFFGJFGFN9999KJJJ>FFKKIHLQSKFFDDGHHHSCA=>PMSGLNGLIGIGILJJPEHSKSDEGCHHSLLNSIFHG722'%FSD*,.;:OJN?==*))+++<?97:C=DDCSLPBJHLQEDCEFQHHPLTAGLJSGGSSJMFFKG?==<JBBDRS5)FE@JPEHG';:::99188=>??>>?@C=AEGH(CRGIRGMHFIKSNQHKN<BDJKSIJPIKLJJQJFCDQHNG%%(C5444200FLHLI188IIKN<BONJJKHPSHSEA999JGFNHIH>BEGOFKDFEABCE>99SFQHHHMRLIGSFEHSIHE;52,('('&).DEEIDB?DCA@5557AAF>><352-41188I@ABCFE81GJJJHSR.-.DHOMSNGLHKSJMFIGMEMCRGIGBAC78NKGOFJ@EIBCRIIHEE?IGFIGFCCFJMJ@ENAFD<;;<BADPLTB@>6>=;=@@@820FL>?;<E<;3/NG%%DDHBBQC=7<>:<;:BBHHFL9:908>94***9>;944AEEGG-.DGEHCHE=;<<IH>5AEFFFKSMQESISNGGGG72MQOKQOFHINFHISEEEDH99JSK@NJJNEHS8NKIQESFCQKQONHMQIESD====)()'%FD@==H8777AEEGGLPIGKHIM@><EJLDEBBEHS?>@>FFK099::A;;<GSH4,(');:O&&(''''=BSLLFGJISC1))).DG>JMFF@C==EB@7>>?DSJFJHHEBBQ=4
```

## Steps to reproduce the issue:

I have never been able to reproduce this error, it seems to happen at complete random.

## Run environment:
- Dorado version: 7.3.11
- Dorado command: Basecalling done via Minknow but this was my command to test whether I could reproduce:
`/opt/ont/dorado/bin/ont_basecall_client --barcode_kits SQK-NBD114-24 -c /opt/ont/dorado/data/dna_r10.4.1_e8.2_400bps_hac.cfg -s {out_dir} -i {pod5_dir} --port /tmp/.guppy/5555 --compress_fastq`
- Operating system: Ubuntu
- Hardware (CPUs, Memory, GPUs): GridION mk1 (more detail available if needed)
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location (on device or networked drive - NFS, etc.): on device
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): r10.4.1, Bacterial 16S data, ~7Gbp of read data
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue): None can reproduce the issue reliably but happy to provide pod5s / corrupted fastqs if desired.
- 
[FAY25688_pass_barcode02_8ac238dd_cc28fea7_25.fastq.gz](https://github.com/user-attachments/files/16267899/FAY25688_pass_barcode02_8ac238dd_cc28fea7_25.fastq.gz)

**Comment by BioWilko** [comment]
Well now the exact same gzipped fastqs are behaving themselves (on the grid and off), suggesting the problem is with the gridIONs gzip rather than the files themselves.... If this should go to someone else more relevant let me know and I can close the issue here

**Comment by malton-ont** [comment]
Hi @BioWilko,

Please raise this on the nanopore community or with technical services - it sounds like a broader system issue rather than a dorado problem.

**Comment by BioWilko** [comment]
Yeah as soon as I spotted that the file itself wasn't corrupted I thought the same, sorry to bug you here.
