### ISSUE TITLE
No CUDA devices available

### ISSUE THREAD

**Issue by jvillanueva-cibus** [nanoporetech/dorado#949]
# Issue Report
## Please describe the issue:

**I'm trying to run standalone Dorado on the following system:**

Windows 11 Pro
11th Gen i5 @ 2.40GHz
64GB of RAM
64-bit operating system
No GPU but with Intel(R) Iris(R) Xe Graphics (Display Adapter)

**I've used PowerShell and cmd with elevated privileges in the folder where the dorado.exe file is located but get a no CUDA devices available**:

_PS C:\Users\jvillanueva\Desktop\dorado-0.7.2-win64\bin> .\dorado.exe duplex sup "C:\Users\jvillanueva\Desktop\Conversion Pod 1" > duplex.bam
[2024-07-10 11:16:09.995] [info] Running: "duplex" "sup" "C:\Users\jvillanueva\Desktop\Conversion Pod 1"
[2024-07-10 11:16:10.032] [info] > No duplex pairs file provided, pairing will be performed automatically
[2024-07-10 11:16:10.070] [error] device string set to cuda:all but no CUDA devices available.

**The standalone does seem to be able to download models so it is running:**

PS C:\Users\jvillanueva\Desktop\dorado-0.7.2-win64\bin> .\dorado.exe download --model rna004_130bps_sup@v3.0.1
[2024-07-10 11:22:47.010] [info] Running: "download" "--model" "rna004_130bps_sup@v3.0.1"
[2024-07-10 11:22:47.017] [info]  - downloading rna004_130bps_sup@v3.0.1 with httplib_

**It was suggested by support to try cuda:0 and I get the following**:

_PS C:\Users\jvillanueva\Desktop\dorado-0.7.2-win64\bin> .\dorado.exe duplex sup -x cuda:0 "C:\Users\jvillanueva\Desktop\Conversion Pod 1" > duplex.bam
[2024-07-15 10:03:12.686] [info] Running: "duplex" "sup" "-x" "cuda:0" "C:\Users\jvillanueva\Desktop\Conversion Pod 1"
[2024-07-15 10:03:12.742] [info] > No duplex pairs file provided, pairing will be performed automatically
[2024-07-15 10:03:12.757] [error] Invalid CUDA device index "0" from device string cuda:0, there are 0 visible CUDA devices._

**I was also asked to try "lspci | grep -i vga" & "nvidia-smi" but they just result in unrecognized errors:**

_PS C:\Users\jvillanueva\Desktop\dorado-0.7.2-win64\bin> lspci | grep -i vga
lspci : The term 'lspci' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ lspci | grep -i vga
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (lspci:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\jvillanueva\Desktop\dorado-0.7.2-win64\bin> nvidia-smi
nvidia-smi : The term 'nvidia-smi' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ nvidia-smi
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (nvidia-smi:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException_

## Run environment:
- Dorado version: 0.7.2-win64
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): Pod5
- Source data location (on device or networked drive - NFS, etc.): On device

**Comment by sklages** [comment]
`dorado` tells you that you don't have a valid CUDA device (**Nvidia GPU**).  If you are trying to direct `dorado basecaller|duplex` to such GPU it fails and quits with an error. 

You could use `--device cpu` to direct `dorado basecaller|duplex` to run basecalling on CPUs (appr 5 cores at a time). But this takes ages even for tiny datasets (tested with older version of dorado, from 2 minutes with GPU to hours with CPU for a single small POD5 file).

You won't get happy basecalling data with dorado without a powerful Nvidia GPU or a Mac with Apple Silicon Chip M1/M2 ..
See [Dorado Readme](https://github.com/nanoporetech/dorado?tab=readme-ov-file#platforms)

My 2p :-)

**Comment by HalfPhoton** [comment]
Thank you @sklages for your reply.

**Comment by jvillanueva-cibus** [comment]
@sklages Thanks! I was unaware that running it off of a CPU would be that slow. I would really like to get SUP calling running however, at the moment I don't have access to an Nvidia GPU. I was able to get access with a computer with an Intel 4600. Is there anyway to run it with an Intel GPU? How difficult would it be? I'm not familiar with the differences between the types of GPUs.

**Comment by sklages** [comment]
@jvillanueva-cibus - running `dorado` on GPU needs either `CUDA` (Nvidia **only**) or `Metal` (Apple Silicon chips). There is no other GPU type supported. So, no, you cannot run `dorado` on an `Intel HD 4600`.

**Comment by jvillanueva-cibus** [comment]
Sounds good. Thank you very much!
