### ISSUE TITLE
Stereo mode on deep sequencing dataset

### ISSUE THREAD

**Issue by asan-emirsaleh** [nanoporetech/dorado#95]
Hi dear colleagues!
Would it be a problem in terms of performance and accuracy if organelle either bacteria sequences, with depth ~10000 being achieved,  have been stereo rebasecalled? The idea is that there shall be 4-10 sequences with the same start and end positions. Either it would benefit in plural rebasecalling yielding in extra accurate results?

Best regards
Asan

**Comment by vellamike** [comment]
Hi @asan-emirsaleh

The duplex pairing algorithm using start and end time as well as positions to identify pairs, so the probability of a "false" pair is probably rather low. As such I think there is no problem with doing what you suggest.

**Comment by asan-emirsaleh** [comment]
Thank you! I also have another question. Let us assume there be not only 2, but 4 candidates for duplex, due to extra deep coverage obtained. Would they be processed as two duplex, or all four reads would be taken into account for rebasecalling?

**Comment by vellamike** [comment]
They would be processed as two duplex.
