### ISSUE TITLE
Is it impossible to obtain demultiplexed (per barcode) pod5 files using dorado?

### ISSUE THREAD

**Issue by ilnamkang** [nanoporetech/dorado#950]
Hi,

I'd like to obtain demultiplexed (per barcode) pod5 files using multiplexed pod5 files (e.g., output of MinKNOW) as input.

Is this impossible by using dorado commands?

I found a tip for this in the link below, but I'd like to know if I can obtain demultiplexed pod5 files using dorado commands.
https://github.com/nanoporetech/dorado/issues/834#issuecomment-2126560136

Thanks.

**Comment by HalfPhoton** [comment]
@ilnamkang
Dorado cannot demux pod5 files. 

Use the pod5 api and tools for this - [Link to POD5 Docs](https://pod5-file-format.readthedocs.io/en/latest/)

Best regards,
Rich

**Comment by JWDebler** [comment]
It is possible, just not very convenient. As already mentioned you need to install pod5 tools and then do something like this:

1. basecall your reads
2. demultiplex reads
3. extract read IDs from demultiplexed reads 
4. cleanup read ID files
5. use pod5 tools and read ID files to demultiplex pod5 files by barcode

I have a script that does that and a bit more including duplex calling and dealing with concatenated reads from several barcodes [here](https://github.com/JWDebler/nanopore_kit14_assembly/blob/main/basecalling.sh), but the most basic version is this:

```
dorado basecaller sup -r pod5_directory/  --kit-name SQK-NBD114-24 > basecalls.bam

dorado demux -t $(nproc) --output-dir basecalls_separated --no-classify basecalls.bam

for file in basecalls_separated/*.bam;
  do 
  id=$(echo "$file" | grep -oP 'barcode\d+'); 
  samtools view -@ $(nproc) -h $file | cut -f 1 > $id.readids.txt; 
  done

for file in *readids.txt; 
  do 
  id=$(echo "$file" | grep -oP 'barcode\d+'); 
  grep -v "@" $file > $id.clean.txt; 
  done

mkdir pod5_by_barcode

for file in *clean.txt; 
  do 
  id=$(echo "$file" | grep -oP 'barcode\d+'); 
  pod5 filter -r pod5_directory/ -i $file -t $(nproc) --missing-ok --duplicate-ok --output pod5_by_barcode/$id.pod5; 
  done
```
Hope this helps.
Cheers

**Comment by ilnamkang** [comment]
Thanks for the answers and suggestions. I'll try using pod5 tools.

**Comment by luckybillion** [comment]
> It is possible, just not very convenient. As already mentioned you need to install pod5 tools and then do something like this:
> 
> 1. basecall your reads
> 2. demultiplex reads
> 3. extract read IDs from demultiplexed reads
> 4. cleanup read ID files
> 5. use pod5 tools and read ID files to demultiplex pod5 files by barcode
> 
> I have a script that does that and a bit more including duplex calling and dealing with concatenated reads from several barcodes [here](https://github.com/JWDebler/nanopore_kit14_assembly/blob/main/basecalling.sh), but the most basic version is this:
> 
> ```
> dorado basecaller sup -r pod5_directory/  --kit-name SQK-NBD114-24 > basecalls.bam
> 
> dorado demux -t $(nproc) --output-dir basecalls_separated --no-classify basecalls.bam
> 
> for file in basecalls_separated/*.bam;
>   do 
>   id=$(echo "$file" | grep -oP 'barcode\d+'); 
>   samtools view -@ $(nproc) -h $file | cut -f 1 > $id.readids.txt; 
>   done
> 
> for file in *readids.txt; 
>   do 
>   id=$(echo "$file" | grep -oP 'barcode\d+'); 
>   grep -v "@" $file > $id.clean.txt; 
>   done
> 
> mkdir pod5_by_barcode
> 
> for file in *clean.txt; 
>   do 
>   id=$(echo "$file" | grep -oP 'barcode\d+'); 
>   pod5 filter -r pod5_directory/ -i $file -t $(nproc) --missing-ok --duplicate-ok --output pod5_by_barcode/$id.pod5; 
>   done
> ```
> 
> Hope this helps. Cheers

Just to clarify, when running dorado base caller would --no-trim need to be added for the demultiplex step to work?

**Comment by JWDebler** [comment]
Not that I'm aware of. The barcode information is stored in the bam file
for each read so it doesn't matter if the actual read is trimmed or not.
Depends if you want to keep the barcode and adapter sequence I suppose. But
none of that is trimmed from the pod5s files anyways
