### ISSUE TITLE
Can dorado mistakenly identify m6A as a result of other methylation on A?  

### ISSUE THREAD

**Issue by Salvobioinfo** [nanoporetech/dorado#951]
Hello,
I have KO samples for an enzyme responsible for m6A modification, and I have identified many m6A sites in these KO samples. I am currently analysing the entire sample library to quantify m6A sites in the KO samples.

Excluding KO related issues and other enzymes that could also insert m6A.  Is there any possibility dorado mistakenly identifies m6A because of other methylation on A?  

## Run environment:
- Dorado version: 0.7.0
- kit SQK-RNA004
- flow cell  FLO-PRO004RA

Thanks in advance

**Comment by Theo-Nelson** [comment]
Hi Salvobioinfo,

Not a developer of Dorado, but happy to add my two cents. 

The parameters of the experiment are key when quantifying m6a sites. To achieve robust decrease in m6a, the conserved catalytic domain (DPPF from https://www.nature.com/articles/s41589-018-0184-3) for most m6a writers needs to be removed. The most common writer is _METTL3_. Within the knockout design, you need to specifically target the exonic region corresponding to this catalytic domain to have the intended effect. You can verify via mass spec whether the total quantity of m6a in your sample as decreased. 

For our data, we observe more high-confidence signals with the newest m6a model present in WT absent from knockdown samples. All-context m6a calling is challenging - you should examine what percentage of your hits fall within homopolymer regions, rRNA, or mitochondrial regions. You can thereafter with a uniform filtering criteria compare the distributions of your KO and WT samples and see whether there are any differences. 

Best of luck!

Sincerely,
Theo

**Comment by Salvobioinfo** [comment]
Hi Theo-Nelson,

I appreciate your response greatly. The KO samples have received confirmation from both MS analysis and NGS.
I value your advice on examining m6a distribution across RNA species, and I also want to include m6a by mRNA regions. We will perform this analysis as soon as possible, but overall the m6a situation remains really strange. The decrease in knockouts seems to be only slightly minimal in comparison to MS. It appears to be a common issue based on what we are reading in the modkit tools issues section.

Best,
Salvo
