### ISSUE TITLE
Support AMD GPUs

### ISSUE THREAD

**Issue by husamia** [nanoporetech/dorado#952]
Will you be working on adding support for other types of GPUs such as those from AMD. There is https://docs.scale-lang.com/ that could potentially allow for CUDA applications to be compiled on AMD GPUs

**Comment by HalfPhoton** [comment]
Hi @husamia, 

Thanks for sharing this interesting project.

We're always investigating supporting new GPU hardware but we don't plan to support AMD hardware at this time.

Kind regards,
Rich
