### ISSUE TITLE
Question about FASTQ output with dorado duplex

### ISSUE THREAD

**Issue by gambalab** [nanoporetech/dorado#954]
Dear Dorado Team,

Thank you for developing the valuable Dorado tool.

I have a question regarding generating FASTQ files using the `--emit-fastq` parameter with the `dorado duplex` command. I understand that FASTQ format doesn't include the `dx` tag, which identifies reads originating from duplex or simplex calls. However, I have specific concerns:

1. **Read Types in FASTQ Output**: Does the FASTQ file generated by dorado duplex contain all three read types: (i) Duplex reads (ii) Simplex reads without duplex offspring (iii) Simplex reads with duplex offspring? Or it only contain just the first two types (duplex and simplex without duplex offspring)? his last behavior would be ideal since simplex reads that had a duplex offspring are just a duplicated read with more errors and could negatively affect variant calling accuracy. 

2.  **Adapter Trimming for Simplex Reads**: Since dorado duplex reportedly doesn't trim adapters in simplex reads, would it be appropriate to run `dorado trim` on the resulting FASTQ files for adapter removal before alignment?

Thank you for your clarification. I look forward to your response.

**Comment by HalfPhoton** [comment]
Hi @gambalab,

Q1. Yes - the FASTQ output will have all 3 "read types". I'm not sure if there's any way to find which reads are which other than;
1. "new" duplex and split simplex reads will have new UUID read ids which don't exist in the input data
2. Duplex read IDs do have concatenated IDs **currently** "parentID_a;parentID_b" but this is being deprecated as it causes [issues with VCF files](https://github.com/nanoporetech/dorado/issues/930).  

Q2 - The adapters that are **not** trimmed in simplex basecalling are rapid adapters.

Best regards,
Rich

**Comment by gambalab** [comment]
than for your prompt answer. So, regarding Q2, is it correct to use `dorado trim` command?

**Comment by HalfPhoton** [comment]
I believe the standard basecall settings should be sufficient and no additional trimming is needed.
