### ISSUE TITLE
basecalling speed with model v5.0.0 SUP is slower than before

### ISSUE THREAD

**Issue by bakeronit** [nanoporetech/dorado#957]
# Issue Report

## Please describe the issue:
The basecalling is taking much more time than before.

I am running things on L40S with a single GPU and noticed that the walltime is much longer (over 5 days for a single flowcell). Thus I tested with the same pod5 file using different dorado versions and models. I only used SUP model and here is the stats of speed  in the output log.

dorado/model version | v4.2.0 | v.4.3.0 | v5.0.0
-- | -- | -- | --
0.4.3 | 9.434240e+06  | 8.525480e+06  | NA |
0.6.0 | 8.749224e+06  | 8.012965e+06 | NA | 
0.7.2 | 8.810423e+06  | 8.059426e+06 | **3.118894e+06** | 

It seems the samples/s got process reduced a lot with the new model 5.0.0 

## Run environment:
- Dorado version: v0.4.3, v0.6.0, v0.7.2
- Dorado command: `\time -f "%e %M %P" $dorado basecaller $model_sup pod5 \
    --modified-bases-models $remora_sup \
    --device "cuda:0" > bam`
- Operating system: `CentOS Linux 7`
- Hardware (CPUs, Memory, GPUs): L40S 48G
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5

Here is the log of dorado v0.7.2 using model 5.0.0

```bash
[2024-07-22 13:34:27.756] [info] Running: "basecaller" "dna_r10.4.1_e8.2_400bps_sup@v5.0.0" "pod5" "--modified-bases-models" "dna_r10.4.1_e8.2_400bps_sup@v5.0.0_5mCG_5hmCG@v1" "--device" "cuda:0"
[2024-07-22 13:34:28.240] [info] > Creating basecall pipeline
[2024-07-22 13:34:42.698] [info] cuda:0 using chunk size 12288, batch size 224
[2024-07-22 13:34:43.580] [info] cuda:0 using chunk size 6144, batch size 224
[2024-07-22 13:37:19.101] [info] > Simplex reads basecalled: 4000
[2024-07-22 13:37:19.101] [info] > Basecalled @ Samples/s: 3.118894e+06
[2024-07-22 13:37:19.110] [info] > Finished
```

Q: Anything that I can do to improve the speed? Thank you.

**Comment by HalfPhoton** [comment]
The sup@v5.0.0 model uses the new transformer architecture which is what's giving us a significant improvement in accuracy over previous generations. We're actively working on specific optimisations which will be released soon which should see the gap between v5 and v4.3 close significantly.

Here's a link to the [YouTube video of the announcement](https://youtu.be/2Pg7-L2Iqdg?t=790) from our recent conference.

Kind regards
Rich

**Comment by bakeronit** [comment]
Thank you for getting back to me.  It makes sense now and we did notice the chunk size was much bigger. 
Gonna wait for further improvements.
