### ISSUE TITLE
Read splitting feature request

### ISSUE THREAD

**Issue by Psy-Fer** [nanoporetech/dorado#96]
Hello,

Is it possible to add read-splitting as a feature for the roadmap?
My guess is the barcoding stuff will form the basis for making this possible. Just making sure this gets taken care of.
This also removes the 2b step in duplex calling, if we can do read splitting when doing the simplex calling

Cheers
James

**Comment by iiSeymour** [comment]
Hey @Psy-Fer

Yes, it's already on the roadmap and we will get all the duplex steps folded into the single `dorado duplex` command.

**Comment by Psy-Fer** [comment]
That's great.
We are looking forward to the high levels of duplex output I'm hearing from the new kits/flowcells. So having the software up to scratch for this feature is on our mind. Glad it's on the list, thanks for the reassurance.

Cheers
James
