### ISSUE TITLE
Extremely small output after `dorado correct`

### ISSUE THREAD

**Issue by JoanJong** [nanoporetech/dorado#962]
# Issue Report

## Please describe the issue:

After running `dorado correct` on my trimmed reads, the output is very small.

I have a dataset of R10.4.1 non-UL reads from a reptile sample. I did not do basecalling using Dorado due to the lack of fast5 files. I ran `dorado trim` on the fastq file prior to `dorado correct`. The output of NanoStat after trimming is:

> number_of_reads	8131055
> **number_of_bases	138801673328.0** (coverage ~70x)
> median_read_length	15349.0
> mean_read_length	17070.6
> read_length_stdev	10960.4
> n50	21616.0
> mean_qual	30.0
> median_qual	30.0
> longest_read_(with_Q):1	941045 (30.0)
> longest_read_(with_Q):2	269229 (30.0)
> longest_read_(with_Q):3	238846 (30.0)
> longest_read_(with_Q):4	216142 (30.0)
> longest_read_(with_Q):5	197849 (30.0)
> highest_Q_read_(with_length):1	30.0 (16508)
> highest_Q_read_(with_length):2	30.0 (7991)
> highest_Q_read_(with_length):3	30.0 (2983)
> highest_Q_read_(with_length):4	30.0 (12172)
> highest_Q_read_(with_length):5	30.0 (15963)
> Reads >Q10:	8131055 (100.0%) 138801.7Mb
> Reads >Q15:	8131055 (100.0%) 138801.7Mb
> Reads >Q20:	8131055 (100.0%) 138801.7Mb
> Reads >Q25:	8131055 (100.0%) 138801.7Mb
> Reads >Q30:	0 (0.0%) 0.0Mb

I then ran `dorado correct` and it output a fasta file without any errors. Since it is unclear whether the herro-v1 model can be used for R10.4.1 data, I tried both models, herro-v1 from Dorado and the model_v0.1 from HERRO. Both models gave similar results but the fasta output is super small. NanoStat check:

Using Dorado's herro-v1 model:
> number_of_reads	15
> **number_of_bases	235935.0**
> median_read_length	13720.0
> mean_read_length	15729.0
> read_length_stdev	7335.1
> n50	14330.0
> longest_read_(with_Q):1	38502 (0)
> longest_read_(with_Q):2	23585 (0)
> longest_read_(with_Q):3	21176 (0)
> longest_read_(with_Q):4	18533 (0)
> longest_read_(with_Q):5	15133 (0)

Using HERRO's model_v0.1:
> number_of_reads	13
> **number_of_bases	206013.0**
> median_read_length	14680.0
> mean_read_length	15847.2
> read_length_stdev	6877.3
> n50	15107.0
> longest_read_(with_Q):1	31122 (0)
> longest_read_(with_Q):2	25546 (0)
> longest_read_(with_Q):3	25093 (0)
> longest_read_(with_Q):4	16452 (0)
> longest_read_(with_Q):5	15107 (0)

As you can see the number of bases dropped a lot. It seemed that a lot of the reads got discarded but I am not sure why that is the case. At the end of the log, it mentioned "total m_corrected_records size 64025.824 MB" and "Pushing 349208 records for correction", so I am not sure what happened to the bulk of the reads.

## Steps to reproduce the issue:

`dorado trim -v --emit-fastq ${IN_FASTQ} > ${TRIMMED_FASTQ}`
`dorado correct -v -m ${MODEL_PATH} ${TRIMMED_FASTQ} > ${OUT_FASTA}`

## Run environment:
- Dorado version: 0.7.2+9ac85c65
- Dorado command: dorado correct -v -m ${MODEL_PATH} ${IN_FASTQ} > ${OUT_FASTA}
- Operating system: Windows 11 Pro, OS build 22631.3880
- Hardware (CPUs, Memory, GPUs):  CPU - 13th Gen Intel(R) Core(TM) i9-13900, 24 cores; GPU - NVIDIA RTX A6000
- Source data type: fastq
- Source data location (on device or networked drive - NFS, etc.): Device
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): PromethION 2 Solo, R10.4.1, simplex non-ultralong reads

## Log

[run_Dorado_correct_230724 - forGitHub.log](https://github.com/user-attachments/files/16385771/run_Dorado_correct_230724.-.forGitHub.log)

**Comment by HalfPhoton** [comment]
Hi @JoanJong,

Something looks wrong here. All of your reads are exactly Q30? 

```text
number_of_reads 8131055
number_of_bases 138801673328.0 (coverage ~70x)
median_read_length 15349.0
mean_read_length 17070.6
read_length_stdev 10960.4
n50 21616.0
mean_qual 30.0                                              <-- Mean and Median are Q30... 
median_qual 30.0
longest_read_(with_Q):1 941045 (30.0)
longest_read_(with_Q):2 269229 (30.0)
longest_read_(with_Q):3 238846 (30.0)
longest_read_(with_Q):4 216142 (30.0)
longest_read_(with_Q):5 197849 (30.0)
highest_Q_read_(with_length):1 30.0 (16508)
highest_Q_read_(with_length):2 30.0 (7991)
highest_Q_read_(with_length):3 30.0 (2983)
highest_Q_read_(with_length):4 30.0 (12172)
highest_Q_read_(with_length):5 30.0 (15963).   <-- All these long reads are exactly Q30?
Reads >Q10: 8131055 (100.0%) 138801.7Mb
Reads >Q15: 8131055 (100.0%) 138801.7Mb
Reads >Q20: 8131055 (100.0%) 138801.7Mb
Reads >Q25: 8131055 (100.0%) 138801.7Mb.     <-- All reads > Q25
Reads >Q30: 0 (0.0%) 0.0Mb                                 <-- Zero reads > Q30
```

Kind regards,
Rich

**Comment by JoanJong** [comment]
Hi @HalfPhoton,

Thanks for pointing it out! I did a check and realised all of the Phred scores are "?" in the raw fastq input. I will ask my team for the fast5 file to redo basecalling. After that I will run the error correction again to see if the issue still persists and update you.

**Comment by JoanJong** [comment]
Hi @HalfPhoton,

Sorry to reopen this issue. I haven't been able to get the fast5 file for this reptile species, but I have in-house data from a plant species (1.5Gb) that I recently generated.

I followed the same command for `dorado correct` as before but the output is still extremely small. The input number of reads was 9269839 but dropped to 10 after `dorado correct`. 

I ran NanoStat for the raw fastq and filtered fastq (removed <10kb and <Q10 using `seqkit`, which is what HERRO would have done inherently). Even after filtering, there were still more than 4M reads left and the coverage was still high. In the log, there were 291192 records pushed for correction so some drastic filtering must have happened afterwards.

Raw fastq:
> Metrics	dataset
> number_of_reads	9269839
> number_of_bases	129713518126.0 
> median_read_length	7903.0
> mean_read_length	13993.1
> read_length_stdev	13892.3
> n50	26750.0
> mean_qual	14.3
> median_qual	15.9
> longest_read_(with_Q):1	389823 (10.8)
> longest_read_(with_Q):2	329473 (11.4)
> longest_read_(with_Q):3	280683 (11.5)
> longest_read_(with_Q):4	278108 (10.1)
> longest_read_(with_Q):5	275075 (12.7)
> highest_Q_read_(with_length):1	32.6 (1044)
> highest_Q_read_(with_length):2	32.4 (1699)
> highest_Q_read_(with_length):3	32.4 (1154)
> highest_Q_read_(with_length):4	32.0 (739)
> highest_Q_read_(with_length):5	31.6 (1501)
> Reads >Q10:	9084213 (98.0%) 127664.2Mb
> Reads >Q15:	5702048 (61.5%) 93878.1Mb
> Reads >Q20:	452915 (4.9%) 5557.4Mb
> Reads >Q25:	950 (0.0%) 2.2Mb
> Reads >Q30:	13 (0.0%) 0.0Mb

Filtered fastq:
> Metrics	dataset
> number_of_reads	4099565
> number_of_bases	107247880484.0
> median_read_length	24007.0
> mean_read_length	26160.8
> read_length_stdev	12429.5
> n50	29925.0
> mean_qual	15.3
> median_qual	16.6
> longest_read_(with_Q):1	389823 (10.8)
> longest_read_(with_Q):2	329473 (11.4)
> longest_read_(with_Q):3	280683 (11.5)
> longest_read_(with_Q):4	278108 (10.1)
> longest_read_(with_Q):5	275075 (12.7)
> highest_Q_read_(with_length):1	27.5 (74458)
> highest_Q_read_(with_length):2	26.8 (18037)
> highest_Q_read_(with_length):3	26.0 (19009)
> highest_Q_read_(with_length):4	25.7 (10232)
> highest_Q_read_(with_length):5	25.6 (13985)
> Reads >Q10:	4099565 (100.0%) 107247.9Mb
> Reads >Q15:	3152411 (76.9%) 82811.7Mb
> Reads >Q20:	182153 (4.4%) 4444.0Mb
> Reads >Q25:	20 (0.0%) 0.4Mb
> Reads >Q30:	0 (0.0%) 0.0Mb

## Steps to reproduce the issue:
1) Basecalling (high-accuracy) done within minKNOW to get fastq
2) Combine all passed fastq
3) dorado correct -v -m ${MODEL_PATH} ${IN_FASTQ} > ${OUT_FASTA}

## Run environment:
Dorado version: 0.7.2+9ac85c65
Dorado command: dorado correct -v -m ${MODEL_PATH} ${IN_FASTQ} > ${OUT_FASTA}
Operating system: Windows 11 Pro, OS build 22631.3880
Hardware (CPUs, Memory, GPUs): CPU - 13th Gen Intel(R) Core(TM) i9-13900, 24 cores; GPU - NVIDIA RTX A6000
Source data type: fastq
Source data location (on device or networked drive - NFS, etc.): Device
Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): PromethION 2 Solo, R10.4.1, simplex non-ultralong reads

## Log
[herro_correction.120824_forGitHub.log](https://github.com/user-attachments/files/16609132/herro_correction.120824_forGitHub.log)

**Comment by Jimingliu60** [comment]
Hi @HalfPhoton,

We have the similar issues like this, is this fixed? Our data is also PromethION R10 data, reads N50 is around 24 Kb, but we only got 10 reads output.

**Comment by HalfPhoton** [comment]
We're looking into why users with what appears to be sensible data are getting very little output.

**Comment by HalfPhoton** [comment]
Looking at @JoanJong 's stats again, it appears that they don't have enough coverage _at sufficient quality_ to be considered for correction. 

Very roughly - your Q20 reads cover about 2-3x of your genome. Considering there will be non-uniform sampling and repeats, it's possible that some regions will have greater coverage than this and it is only those regions that will be corrected. 

We're going to look into improving the dorado correct logging, reporting and documentation so that it better describes what data is being used and if it is of sufficient quality / coverage to be used given. 

Best regards,
Rich

**Comment by JoanJong** [comment]
Hi @HalfPhoton ,

Unfortunately I think this is the best dataset we can generate for our plant species. 

Do you think that perhaps rerunning basecalling with the super accuracy model could help?

Also, what then would be the required coverage for >Q20 reads for `dorado correct` to work? Now it seems like a very strict threshold. 

Thanks!

**Comment by HalfPhoton** [comment]
We need a minimum coverage of 30x for the Herro model architecture. If your data can attain that threshold then there maybe some benefit. 
Will basecalling with the SUP model will bring up your accuracy to a sufficient level on it's own?

**Comment by HalfPhoton** [comment]
The [dorado-0.8.0](https://github.com/nanoporetech/dorado/releases/tag/v0.8.0) has been released with new features and the [readme](https://github.com/nanoporetech/dorado/blob/release-v0.8/README.md#read-error-correction) has been updated better describing the requirements of the tool. 

Kind regards,
Rich
