### ISSUE TITLE
--resume-from didn't appear to merge the two files? 

### ISSUE THREAD

**Issue by DntBScrdDv** [nanoporetech/dorado#966]
Hi, 

My run was killed by the cluster (I set the wring time limit) and so I used the following command to resume the run: 

~/dorado/bin/dorado basecaller sup ~/all/ --no-trim --kit-name SQK-16S114-24 --resume-from ~/all/int.bam > ~/all/calls.bam

The interrupted all.bam file was approx 10Gb, which I renamed to int.bam. 

However, when the resumed run terminated, the all.bam file was only about 4Gb... 

Surely it should have been 14Gb? 

Using dorado 0.7.2 (latest version pulled from the site yesterday). 

Any ideas?

**Comment by HalfPhoton** [comment]
Hi @DntBScrdDv
This is intended behaviour as stated in the `--help`:

```text
-resume-from    Resume basecalling from the given HTS file. 
                            Fully written read records are not processed again. 
```

You'll need to merge the files with samtools 👍 

Kind regards,
Rich

**Comment by DntBScrdDv** [comment]
Hi @HalfPhoton ,

Many thanks for the quick response. However, are you sure? In the documentation it states: 

_If basecalling is interrupted, it is possible to resume basecalling from a BAM file. To do so, use the --resume-from flag to specify the path to the incomplete BAM file. For example:_

`$ dorado basecaller hac pod5s/ --resume-from incomplete.bam > calls.bam`

_calls.bam will contain all of the reads from incomplete.bam plus the new basecalls (incomplete.bam can be discarded after basecalling is complete)._

Indeed, when I demuxed the new file it gave me the correct number of reads - ~4.9M. 

However, here's the thing: 

1/ The resumed file was just **4.6Gb**, apparently containing 4.9M reads. When I demuxed, I kept just the files I wanted, and have 11Gb of fastq 

2/ As I wasn't sure what was going on, I re-ran dorado overnight, this time giving myself enough time on the cluster. It completed as expected, and today, the .bam file is **13.3Gb**. I demuxed, removed unwanted barcodes, and have again 11Gb of fastq files. 

Why the huge discrepancy in .bam file size? What are the extra 8-9Gb all about?

**Comment by DntBScrdDv** [comment]
@HalfPhoton my interpretation of `Fully written read records are not processed again.` is that those reads will not be processed by dorado again - rather that they will be copied directly across to the new .bam file. Dorado will then pick up from where it left off.

**Comment by HalfPhoton** [comment]
Hi @DntBScrdDv, 

I've had a check and you're correct my apologies - dorado should be copying the reads into the new output [src](https://github.com/nanoporetech/dorado/blob/release-v0.7/dorado/read_pipeline/ResumeLoaderNode.cpp#L59).

We'll clarify that in the --help documentation so save myself from the same mistake. 

---

As for the underlying issue regarding file size. I'm not sure why this would be happening and this is a very intriguing result.

Just for clarity:

You created an **interrupted.bam** (10Gb), resumed it into a **resumed.bam** (4.6Gb) with all* expected outputs.
You re-created the file, now un-interrupted giving a **complete.bam** (13.3Gb)with the same* outputs.

For sanity checking, can you run [samtools stats](https://www.htslib.org/doc/samtools-stats.html) to generate some information about the content of the two final files to check that they are the same? This result is quite surprising.

Kind regards,
Rich

**Comment by DntBScrdDv** [comment]
Thanks again @HalfPhoton 

Yes - that's exactly correct. I'll run samtools as you suggest when I get a moment. I'll come back shortly.

**Comment by DntBScrdDv** [comment]
Sorry - I'm not entirely sure what I'm doing... running samtools stats on either file outputs a bunch of variations of `Barcode separator for tag BC is in a different position or wrong barcode content('SQK-16S114-24_barcode04') at sequence 'e33700ab-38e6-4486-8a83-fcedaaea0f88'` and gives me an output file of several hundred MB..

**Comment by DntBScrdDv** [comment]
Just looking at the SN tags I see: 

--resume'd reads: 

`raw total sequences:	4979956	# excluding supplementary and secondary reads
filtered sequences:	0
sequences:	4979956
is sorted:	1
1st fragments:	4979956
last fragments:	0
reads mapped:	0
reads mapped and paired:	0	# paired-end technology bit set + both mates mapped
reads unmapped:	4979956
reads properly paired:	0	# proper-pair bit set
reads paired:	0	# paired-end technology bit set
reads duplicated:	0	# PCR or optical duplicate bit set
reads MQ0:	0	# mapped and MQ=0
reads QC failed:	0
non-primary alignments:	0
supplementary alignments:	0
total length:	6095761135	# ignores clipping
total first fragment length:	6095761135	# ignores clipping
total last fragment length:	0	# ignores clipping
bases mapped:	0	# ignores clipping
bases mapped (cigar):	0	# more accurate
bases trimmed:	0
bases duplicated:	0
mismatches:	0	# from NM fields
error rate:	0.000000e+00	# mismatches / bases mapped (cigar)
average length:	1224
average first fragment length:	1224
average last fragment length:	0
maximum length:	798684
maximum first fragment length:	798684
maximum last fragment length:	0
average quality:	38.3
insert size average:	0.0
insert size standard deviation:	0.0
inward oriented pairs:	0
outward oriented pairs:	0
pairs with other orientation:	0
pairs on different chromosomes:	0
percentage of properly paired reads (%):	0.0
`

"normal" 

`raw total sequences:	4979956	# excluding supplementary and secondary reads
filtered sequences:	0
sequences:	4979956
is sorted:	1
1st fragments:	4979956
last fragments:	0
reads mapped:	0
reads mapped and paired:	0	# paired-end technology bit set + both mates mapped
reads unmapped:	4979956
reads properly paired:	0	# proper-pair bit set
reads paired:	0	# paired-end technology bit set
reads duplicated:	0	# PCR or optical duplicate bit set
reads MQ0:	0	# mapped and MQ=0
reads QC failed:	0
non-primary alignments:	0
supplementary alignments:	0
total length:	6095761135	# ignores clipping
total first fragment length:	6095761135	# ignores clipping
total last fragment length:	0	# ignores clipping
bases mapped:	0	# ignores clipping
bases mapped (cigar):	0	# more accurate
bases trimmed:	0
bases duplicated:	0
mismatches:	0	# from NM fields
error rate:	0.000000e+00	# mismatches / bases mapped (cigar)
average length:	1224
average first fragment length:	1224
average last fragment length:	0
maximum length:	798684
maximum first fragment length:	798684
maximum last fragment length:	0
average quality:	38.3
insert size average:	0.0
insert size standard deviation:	0.0
inward oriented pairs:	0
outward oriented pairs:	0
pairs with other orientation:	0
pairs on different chromosomes:	0
percentage of properly paired reads (%):	0.0
`

**Comment by DntBScrdDv** [comment]
Just coming back to this - I ran duplex analysis on the same dataset, which gave me a reads file of 15 Gb... 

I think ran: 

```
samtools view -b -h -d dx:1 all_reads.bam > duplex.bam
samtools view -b -h -d dx:0 all_reads.bam > simplex.bam
```

to split out the duplex and simplex reads and got the following files: 

duplex.bam ==> 556 Mb
simplex.bam ==> 3.37 Gb

What happened to the other 11 Gb? 

I might try reinstalling dorado on the cluster...

**Comment by HalfPhoton** [comment]
I did some testing locally to see what effect various levels of compression would have on the output and there's approx 2x reduction from min and max compression. But nowhere are we adjusting this value and I suspect that neither are you 🤔 .

I'll ask around if anyone in the team has observed something similar.

**Comment by DntBScrdDv** [comment]
No - it's a weird one! I'd just upgraded to 0.7.2, could it be linked to the build I pulled?

**Comment by DntBScrdDv** [comment]
Hi @HalfPhoton,

For info - yesterday I pulled version 0.7.3, and ran SUP on my 4.9M reads. 

The resulting bam file is a wholly normal 3.9Gb, so perhaps a problem with the 0.7.2 build I pulled (I had to correct a load of library path errors).

Running on our cluster I get: 

```
[2024-08-05 13:06:35.312] [info] > Basecalled @ Samples/s: 1.615940e+06
[2024-08-05 13:06:35.312] [info] > 4979956 reads demuxed @ classifications/s: 9.547463e+01
```

I've literally no idea how that benchmarks, and would be interested to hear what you think, but SUP basecalling 4.9M reads or approx 1.5 Kb (16S genes) took from 22h00 to 13h00 ~15h. 

Running on an NVidia Tesla V100 (-N1 -n 1 --cpus-per-task 24)

Otherwise, I think we can probs mark this as closed... :)

**Comment by DntBScrdDv** [comment]
Closing

**Comment by HalfPhoton** [comment]
The Sup v5 models use the new transformer architecture which is slower but more accurate than existing models. There will be a significant increase in performance as we continue to optimise them.

Thanks for getting back to us with an update on the original issue - very strange one for sure but I'm glad to hear it was resolved. 

Best regards,
Rich
