### ISSUE TITLE
Extremely small output after dorado correct too

### ISSUE THREAD

**Issue by yplee614** [nanoporetech/dorado#968]
I ran Dorado with the command: dorado correct -m herro-v1 filter.fq > corrected.fasta 2> log
The log file shows:
[2024-08-01 20:37:12.161] [info] Running: "correct" "-m" "herro-v1" "filter.fq"
[2024-08-01 20:41:26.694] [info] > starting correction
[2024-08-01 20:44:25.782] [info] > Corrected reads written: 16583
[2024-08-01 20:44:25.782] [info] > finished correction

The input file filter.fq is filtered by a minimum length of 10kb, and has a total size of 22GB.
The output corrected.fasta file contains only 585MB of corrected reads.

## Run environment:
- Dorado version: 0.7.2+9ac85c6
- Dorado command: dorado correct -m herro-v1 filter.fq > corrected.fasta 2> log
- Operating system: Ubuntu 24.04
- Hardware (CPUs, Memory, GPUs): AMD 9654, 512Gb, NVIDIA 4070 super

**Comment by HalfPhoton** [comment]
Hi @yplee614, 

Have you seen this thread? https://github.com/nanoporetech/dorado/issues/956

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
Hi @tbenavi1
[Dorado-0.8.0](https://github.com/nanoporetech/dorado/releases/tag/v0.8.0) has updated the readme with guidance on the requirements of the input data to dorado correct.

Kind regards,
Rich
