### ISSUE TITLE
dna_r10.4.1_e8.2_400bps_sup@v5.0.0 crashes my server

### ISSUE THREAD

**Issue by piplus2** [nanoporetech/dorado#971]
# Issue Report
When I perform basecalling using the model dna_r10.4.1_e8.2_400bps_sup@v5.0.0, my server crashes.

## Please describe the issue:

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

After launching the basecalling using the model dna_r10.4.1_e8.2_400bps_sup@v5.0.0, the server gets stuck and I have to reboot it. This does not happen with the previous model dna_r10.4.1_e8.2_400bps_sup@v4.3.0

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version: 0.7.2
- Dorado command: dorado basecaller --min-qscore 10 <modeldir>/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 <pod5dir> > <bamfile> 
- Operating system: Ubuntu 20.04
- Hardware (CPUs, Memory, GPUs):
    - 4 x A100 80GB
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
    - pod5
- Source data location (on device or networked drive - NFS, etc.): 
    - local
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB):
    - 15 pod5 files 
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by iiSeymour** [comment]
Hey @paoloinglese can you post the output from `nvidia-smi`?

**Comment by paoloinglese** [comment]
Hi @iiSeymour ,

here it is:

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          On  |   00000000:06:00.0 Off |                    0 |
| N/A   31C    P0             61W /  500W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB          On  |   00000000:07:00.0 Off |                    0 |
| N/A   28C    P0             60W /  500W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA A100-SXM4-80GB          On  |   00000000:08:00.0 Off |                    0 |
| N/A   31C    P0             60W /  500W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA A100-SXM4-80GB          On  |   00000000:09:00.0 Off |                    0 |
| N/A   27C    P0             58W /  500W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

**Comment by paoloinglese** [comment]
This are the last lines of the output before it crashes:

```
[2024-08-05 11:39:56.431] [info] cuda:0 using chunk size 12288, batch size 512
[2024-08-05 11:39:56.431] [debug] cuda:0 Model memory 36.54GB
[2024-08-05 11:39:56.431] [debug] cuda:0 Decode memory 4.44GB
[2024-08-05 11:39:56.431] [info] cuda:3 using chunk size 12288, batch size 512
[2024-08-05 11:39:56.431] [debug] cuda:3 Model memory 36.54GB
[2024-08-05 11:39:56.431] [debug] cuda:3 Decode memory 4.44GB
[2024-08-05 11:39:56.431] [debug] Largest batch size for cuda:1: 512, time per chunk 0.345104 ms
[2024-08-05 11:39:56.431] [debug] Final batch size for cuda:1[0]: 512
[2024-08-05 11:39:56.431] [debug] Final batch size for cuda:1[1]: 512
[2024-08-05 11:39:56.431] [info] cuda:2 using chunk size 12288, batch size 512
[2024-08-05 11:39:56.431] [debug] cuda:2 Model memory 36.54GB
[2024-08-05 11:39:56.431] [debug] cuda:2 Decode memory 4.44GB
[2024-08-05 11:39:56.435] [info] cuda:1 using chunk size 12288, batch size 512
[2024-08-05 11:39:56.435] [debug] cuda:1 Model memory 36.54GB
[2024-08-05 11:39:56.435] [debug] cuda:1 Decode memory 4.44GB
```

**Comment by Mon3trK** [comment]
I got the same issue on chip with `SXM4` packing too, just switching to `PCIe` GPU works.

**Comment by paoloinglese** [comment]
Just found out that one GPU is faulty, as the model works with the other 3 when used individually.

**Comment by iiSeymour** [comment]
thanks for the update @paoloinglese 

@Mon3trK that shouldn't be the case 🤔 are you having success running other applications on your SXM4 devices?

**Comment by Mon3trK** [comment]
@iiSeymour Yeah, for Guppy my devices run great

**Comment by piplus2** [comment]
@iiSeymour to me
