### ISSUE TITLE
 A question about the direction  of 6th 5mC if C+m?5,2 is shown in a reverse strand read

### ISSUE THREAD

**Issue by wtfeng111** [nanoporetech/dorado#974]
After basecalling and alignment ,the bam gives us  modification information. If there is a reverse strand read, the sequence "ACCGGT..."  is alligned to the  forward strand?And I  don't know the direction  of 6th 5mC if C+m?5,2 is shown in a reverse strand read ,is it from the begining of 5'end   of this reverse read?

**Comment by HalfPhoton** [comment]
Hi @wtfeng111,

<p>The modbase tag specification annotations state the strandedness of the modifications.
This information allows for modifications on 2d reads to be annotated by indicating
on which strand the modification was observed. The table below shows how forward and
reverse complement reads with top (+) and bottom (-) modifications are
resolved in reference space.</p>
<p>For example, a reverse complement aligned read (-) with modifications on the
bottom-strand (-) will be resolved to the forward strand (+) aligned in the
reference direction.</p>

<table>
<tr>
<th colspan="2" rowspan="2">Strandedness in output file</th>
<th colspan="2">SEQ direction according to FLAG</th>
</tr>
<tr>
<th>0x10 not set (i.e. forward alignment)</th>
<th>0x10 set (i.e. reverse-complement alignment)</th>
</tr>
<tr>
<td rowspan="2">Modification Tag Strandedness</td>
<td>

\+
</td>
<td>

\+
</td>
<td>

\-
</td>
</tr>
<tr>
<td>

\-
</td>
<td>

\-
</td>
<td>

\+
</td>
</tr>
</table>

In your example, you have a forward alignment (+) and the mod is on the top (+) so your modification indexing is in the forward reference direction.

The [ModKit](https://github.com/nanoporetech/modkit) tools might also have something useful to view the mods as an annotated bed file.

Kind regards,
Rich
