### ISSUE TITLE
move table length * stride and ns - ts 

### ISSUE THREAD

**Issue by j-o-song** [nanoporetech/dorado#977]
Hello, 

I am new to dorado and nanopore datasets. As I was processing the bam file outputs from dorado basecalling from pod5 files, I noticed that for some reads, the length of the move table * stride does not equal ns - ts. 
(note: the value of ns does equal the number of raw signals in the pod5 file) 

Is this an expected result? If not, how can I fix this? 

Thank you for all your help.

**Comment by HalfPhoton** [comment]
Please complete the issue template to provide the necessary information (e.g. dorado version) so that we can take a look at this.

Kind regards,
Rich
