### ISSUE TITLE
Duplex basecalling is impractically slow

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/dorado#98]
The command I ran is: `dorado duplex dna_r10.4.1_e8.2_400bps_sup@v4.0.0 reads/ --pairs pairs_from_bam_hg2/pair_ids_filtered.txt`
Now 19 hours, but only 120,000 reads are done, on 4xTesla V100. For 1.2M pairs, it will be a few days. GPUs are consistently running at 80-95% utilisation in nvidia-smi.  Is it normal to be this slow?

**Comment by vellamike** [comment]
Hi, it’s possible that this is caused by a low pairing rate. Dorado v0.2.0
introduces performance improvements to Dupelx, could you try this?

**Comment by hasindu2008** [comment]
Keeps getting this with the nestest dorado
```
 /install/dorado-0.2.1/bin/dorado duplex /install/dorado-0.2.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.1.0  reads/  --pairs pairs_from_bam_hg2/pair_ids_filtered.txt > sup_duplex_hg2_pod.sam
[2023-02-17 14:32:33.612] [info] > Loading pairs file
[2023-02-17 14:32:35.223] [info] > Pairs file loaded
[2023-02-17 14:33:00.545] [info] > Reads basecalled: 0
[2023-02-17 14:33:00.545] [info] > Bases/s: 0.000000e+00
[2023-02-17 14:33:01.040] [error] toml::parse: file open error -> /install/dorado-0.2.1/models/dna_r10.4.1_e8.2_4khz_stereo@v1.1/config.toml
```

**Comment by vellamike** [comment]
Hi @hasindu2008 , is the model `dna_r10.4.1_e8.2_4khz_stereo@v1.1` in the directory `/install/dorado-0.2.1/models` ? It is necessary to download this model with `dorado download --model all`

**Comment by hasindu2008** [comment]
Now the time for duplex is good with 0.2.1! Took only around 6 hours.

**Comment by vellamike** [comment]
That's great! We are working on further performance improvements so expect that 6 hours to go down further.
