### ISSUE TITLE
New version of Dorado not running

### ISSUE THREAD

**Issue by fxc124** [nanoporetech/dorado#980]
Hi!
After updating to dorado-0.7.3-linux-x64, I get this error message when trying to run it:

/dorado-0.7.3-linux-x64/bin/dorado: error while loading shared libraries: /dorado-0.7.3-linux-x64/bin/../lib/libhdf5.so.8: file too short

I deleted dorado-0.7.3-linux-x64 and installed it again, with no effect. The version 0.7.2 is running ok.

**Comment by blawrence-ont** [comment]
I cannot repro the issue on that platform either. Do the outputs of the commands I ran above match what you see?

**Comment by avilella** [comment]
what output do you get if you execute the command below, substituting the dorado binary path to the one you downloaded?

```
ldd ~/dorado/dorado-0.7.2-linux-x64/bin/dorado
```
