### ISSUE TITLE
dorado aligner (minimap2 parameter settings)

### ISSUE THREAD

**Issue by kir1to455** [nanoporetech/dorado#984]
Hi, 
Thank you for developing Dorado !

I would like to know if there are different **standard** parameter settings for comparing the reference genome and reference transcriptome of dorado to RNA004?

The default settings is **lr:hq** preset for _-x map-ont -k19 -w 19 -U50,500 -g10k_. Is this for genome or transcriptome?

In RNA002, I usually use this code for genome:
`minimap2 -ax splice -uf -k14 --secondary=no -t 36 --junc-bed junctions.bed genome.fa $qfile | samtools view -F 2324 -q 1 -b -@ 36 -o genome.bam`

And this for transcriptome: 
`minimap2 -ax map-ont -uf -k14 --secondary=no -t 36 transcripts.fa $qfile | samtools view -F 2324 -q 1 -b -@ 36 -o transcriptome.bam`

Can someone give me some advice?

Best wishes,
Kirito

**Comment by kir1to455** [comment]
Hi, @HalfPhoton 

Thank you for your quick reply!
Should I use this parameter **--mm2-preset splice** on the dorado basecaller for genome or transcriptome?
In transcriptome, the sequence has not been splice and no GT[C/T]..[A/G]AG.

Best wishes,
Kirito

**Comment by HalfPhoton** [comment]
That question is best placed on the Nanopore Community where there are people much more well informed on these matters.

Kind regards,
Rich
