### ISSUE TITLE
Bascalled SAM file contains reads with IDs that are not in source POD5 file

### ISSUE THREAD

**Issue by ChristopherAdelmann** [nanoporetech/dorado#985]
# Issue Report

## Please describe the issue:

After base-calling pod5 files with dorado, the generated SAM file contains reads that are non-existent in the underlying pod5 file.
The read number tag (rn) is set to minus one. Most of the reads can be found, but for a small fraction, there is no corresponding read ID.

## Steps to reproduce the issue:

Start base-calling with dorado with SAM as output. Downstream analysis with remora revealed that some reads could not be associated with a read in the pod5 file -> missing. After extracting readIDs from sam file, running ```pod5 filter -i read_id_file``` also couldn't find reads.

## Run environment:
- Dorado version: 0.7.2+9ac85c65
- Dorado command: dorado basecaller --emit-sam --emit-moves --estimate-poly-a -r C:\Users\ONT-Seq\dorado_models\rna004_130bps_sup@v3.0.1 in_dir_path > out.sam
- Operating system: Windows 11 
- Hardware (CPUs, Memory, GPUs): CPU: AMD Ryzen 9 7900X; Memory: 64 GB DDR5; GPU: NVIDIA GeForce RTX 4090
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Source data location (on device or networked drive - NFS, etc.): on device
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): flow-cell: FLO-PRO004RA; kit: SQK-RNA004; read-length: 332  ; number of reads: 321.911; dataset size (pod5): 23GB
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue): This did not happen with a smaller subset.

**Comment by malton-ont** [comment]
Hi @ChristopherAdelmann,

These are most likely generated by read splitting. If you look for the `pt` tag on these reads, this will correspond to the original read-id from the pod5 file.

**Comment by ChristopherAdelmann** [comment]
Hi @malton-ont,

Thank you for your swift response and for pointing me in the right direction. I assume you meant the `pi` tag? After filtering for the pi read ID, I was able to locate the origin read.

By the term "read splitting" I would assume that the source raw read data is base-called and split into two or more reads. But when examining the SAM file, I can only find one read that has the source ID in its `pi` tag. There is no further filtering set or done by me, so is this expected?

**Comment by malton-ont** [comment]
Hi @ChristopherAdelmann,

Apologies, yes, that's the one I meant!

RNA read splitting is performed in signal space, before the basecall. In some cases the read splitter may discard parts of a read in a way which modifies the original but does not strictly create multiple reads (for instance, if it finds open-pore signal at one end). We still consider this a split and update the read-id and tag accordingly.
