### ISSUE TITLE
Error during basecalling with Rapid Barcoding kit

### ISSUE THREAD

**Issue by desmodus1984** [nanoporetech/dorado#986]
# Issue Report

I have previously basecalled data with the Rapid Sequencing kit (SQK-RAD114), and I sequenced now some samples with the Rapid Barcoding kit (SQK-RBK114.24)

I ran
## Run environment:
- Dorado version: 0.7.3 (the files in the release section are bad, they don't include the bin folder)

And I modified my previously working code:

```
export OMP_NUM_THREADS=35
/home/juaguila/appz/dorado-0.6.2-linux-x64/bin/dorado basecaller --min-qscore 5 --emit-fastq -x "cpu" \
        sup /home/juaguila/Ju760-basecalling/1st-P2 \
        > Ju760.Lig.P2.fastq
```

to this:

```
export OMP_NUM_THREADS=40
/home/juaguila/appz/dorado-0.7.3-linux-x64/bin/dorado basecaller --min-qscore 5 \
        --emit-fastq -x "cpu" --kit-name SQK-RBK114-24 \
        sup /RBK-xtra > RBK-xtra.fastq
```

And now, dorado is prompting a chemistry error.

[2024-08-12 15:37:45.239] [info] Running: "basecaller" "--min-qscore" "5" "--emit-fastq" "-x" "cpu" "--kit-name" "SQK-RBK114-24" "sup" "/RBK-xtra"
[2024-08-12 15:37:45.377] [info]  - Note: FASTQ output is not recommended as not all data can be preserved.
[2024-08-12 15:37:45.392] [error] Failed to determine sequencing chemistry from data. Please select a model by path

- Operating system: LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core

- Hardware (CPUs, Memory, GPUs): CPU - 40
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance):
- Source data location (on device or networked drive - NFS, etc.): on HPC
- Details about data ( in MB/GB/TB): 
flow cell 10.4.1
kit Rapid Barcoding Kit 24 V14
read lengths N50 - 250kb 
number of reads74.04 k
total dataset size 2.2 GB

## Logs
dorado -v
[2024-08-12 15:53:50.675] [info] Running: "-v"
0.7.3+6e6c45c

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

Do I need to provide any additional parameter for it to work with the Rapid Barcoding Kit 24 V14????

Thanks;

**Comment by desmodus1984** [comment]
I created a symlink as suggested before:

`ln -s /home/juaguila/appz/dorado-0.6.2-linux-x64/bin/dna_r10.4.1_e8.2_400bps_sup@v4.3.0 dna_r10.4.1_e8.2_400bps_sup@v4.3.0`

Then, I changed the code
```
export OMP_NUM_THREADS=40
/home/juaguila/appz/dorado-0.7.3-linux-x64/bin/dorado basecaller --min-qscore 5 \
        --emit-fastq -x "cpu" --kit-name SQK-RBK114-24 \
        /dna_r10.4.1_e8.2_400bps_sup@v4.3.0 /RBK-xtra > RBK-xtra.fastq
```

And I got a new error now:
[2024-08-12 16:25:04.927] [info]  - Note: FASTQ output is not recommended as not all data can be preserved.
terminate called after throwing an instance of 'std::runtime_error'
  what():  toml::parse: file open error -> /dna_r10.4.1_e8.2_400bps_sup@v4.3.0/config.toml
CPU-dorado.RBK-xtra.1.sh: line 4: 62789 Aborted                 /home/juaguila/appz/dorado-0.7.3-linux-x64/bin/dorado basecaller --min-qscore 5 --emit-fastq -x "cpu" --kit-name SQK-RBK114-24 /dna_r10.4.1_e8.2_400bps_sup@v4.3.0 /RBK-xtra > RBK-xtra.fastq

**Comment by desmodus1984** [comment]
Hi @sklages 

That is what I have. The HPC people here put up a node with Titan V GPUs for people needing GPU, and dorado doesn't work with that GPU! and we do not have money to buy one of the GPUs that dorado is "optimized" for.
Thus, I am bound to do basecalling in CPU mode anyways.

Moreover, I feel like wasting money with Nanopore anyway.
I used the Rapid Barcoding kit, and I got less than 3GB, ~ 2.9GB, for 4 worm samples, where one has a genome of 200 MB. Thus, even for this only one species, 15X.
And, to make it even worse, only half of the data is useful, in the best scenario of using sequences with a Phred score of 15.

That's why CPU basecalling should be optimized when CPUs are cheaper than fancy GPUs.

Documentation expects people to be experts, which I am not, and I - after wasting much time- figured out how to fix it.
Since dorado complained about model, and required a model path, I created a symlink as told before and used just the name of the model (**bold**)

```
export OMP_NUM_THREADS=40
/home/juaguila/appz/dorado-0.7.3-linux-x64/bin/dorado basecaller --min-qscore 5 \
        --emit-fastq -x "cpu" --kit-name SQK-RBK114-24 \
        **dna_r10.4.1_e8.2_400bps_sup@v4.3.0** /home/juaguila/Ju760-basecalling/RBK-xtra > RBK-xtra.fastq
```

The model should be plain text (no path), but nonetheless, the pod5 files directory always needs to be full path, I don't understand. If I use just /RBK-xtra it doesn't work. Very weird.

Also, I use the barcoding/demultiplexing and I thought that I would get several fastq files for the classified/missclassified sequences, and I only got a single file. Did I miss a parameter?
dorado didn't complain about a missing parameter.

**Comment by sklages** [comment]
> Hi @sklages
> 
> That is what I have. The HPC people here put up a node with Titan V GPUs for people needing GPU, and dorado doesn't work with that GPU! and we do not have money to buy one of the GPUs that dorado is "optimized" for. Thus, I am bound to do basecalling in CPU mode anyways.

Did you try or just read the "platform" of the docs? We did basecalling on a bunch of (old) GeForce RTX 2080 which worked pretty well, although not officially "optimized" for..


> Moreover, I feel like wasting money with Nanopore anyway. I used the Rapid Barcoding kit, and I got less than 3GB, ~ 2.9GB, for 4 worm samples, where one has a genome of 200 MB. Thus, even for this only one species, 15X. And, to make it even worse, only half of the data is useful, in the best scenario of using sequences with a Phred score of 15.

It is not just the ONT device, it is input material - quality, amount - library prep, library amount, quite some pitfalls to generate "bad data". 


> That's why CPU basecalling should be optimized when CPUs are cheaper than fancy GPUs.

It is not a matter of "cheaper", GPUs are simply more powerful to do the job here. I did some testing with an older version of `dorado` using a single POD5 file with 4K reads. It took less than 2 minutes on a A100/40G and more than six hours in CPU mode .. (you cannot control the number of threads used for basecalling, `dorado`uses appr five CPUs on average).


> Documentation expects people to be experts, which I am not, and I - after wasting much time- figured out how to fix it. Since dorado complained about model, and required a model path, I created a symlink as told before and used just the name of the model (**bold**)

Documentation is now better than at the beginning .. it is short, but precise. Minknow documentation is by far worse :-)


> `export OMP_NUM_THREADS=40`

.. is of no use ..

>```
> /home/juaguila/appz/dorado-0.7.3-linux-x64/bin/dorado basecaller --min-qscore 5 \
>         --emit-fastq -x "cpu" --kit-name SQK-RBK114-24 \
>         **dna_r10.4.1_e8.2_400bps_sup@v4.3.0** /home/juaguila/Ju760-basecalling/RBK-xtra > RBK-xtra.fastq
> 
>``` 
> The model should be plain text (no path), but nonetheless, the pod5 files directory always needs to be full path, 

Well, yes, not a real problem. POD5 can be searched recursively for basecalling (--recursively), so it is probably smarter to provide a directory for input data .. It is just a different type of parameter.


> I don't understand. If I use just /RBK-xtra it doesn't work. Very weird.
 Because `/` is the root file system of your OS. You are not allowed to store/write in `/` (and thus to `/RBK-xtra`). OTOH `/home/juaguila/` is your home directory, that is where you are allowed to write/store data. So you will probably never find any data stored in `/RBK-xtra`. These are Linux basics and are not related to `dorado`.


> Also, I use the barcoding/demultiplexing and I thought that I would get several fastq files for the classified/missclassified 
sequences, and I only got a single file. Did I miss a parameter? dorado didn't complain about a missing parameter.

Again, stick to BAM as long as you can. Inline demultiplexing organizes/stores the barcode information (with)in read groups in a single file, BAM or fastq. To get separate files for each of the barcode you need to run `dorado demux <..>` in a second step (which is cpu-bound), just as described in https://github.com/nanoporetech/dorado?tab=readme-ov-file#barcode-classification

**Comment by desmodus1984** [comment]
Hi,

> Did you try or just read the "platform" of the docs? We did basecalling on a bunch of (old) GeForce RTX 2080 which worked pretty well, although not officially "optimized" for..
The one that we have here at the HPC is the one that I told you, Titan V GPUs, 24 CPU cores, and 128 GB of memory, it has enough memory, and dorado just doesn't work with it at all.

> It is not just the ONT device, it is input material - quality, amount - library prep, library amount, quite some pitfalls to generate "bad data".
Again more excuses, I got 2.9 GB of data, with fresh DNA, pure - good 260/280,260/230 ratios, yet very low yield.
My friend did another sequencing attempt with even better DNA, and got less than 2GB. 
And that's the constant. We even bought new reagents just in case to make sure that we have high-quality material to prepare libraries, and no improvement at all.
 
> > That's why CPU basecalling should be optimized when CPUs are cheaper than fancy GPUs.
> 
> It is not a matter of "cheaper", GPUs are simply more powerful to do the job here. I did some testing with an older version of `dorado` using a single POD5 file with 4K reads. It took less than 2 minutes on a A100/40G and more than six hours in CPU mode .. (you cannot control the number of threads used for basecalling, `dorado`uses appr five CPUs on average).
My question is, why you cannot control the number of threads? It seems that the algorithm wasn't properly 
designed to be fully multithreaded.

 
> Documentation is now better than at the beginning .. it is short, but precise. Minknow documentation is by far worse :-)
It doesn't say clearly how to use the symlink to do the basecalling?
I was told about to do it because at the HPC here, the node can connect to the outside but not the outside to the node. Then, when dorado tries to connect to the Internet, it just fails, and the job is cancelled immediately - 
ANOTHER PROBLEM BESIDES THE GPU CARD INCOMPATIBILITY.
 

> Well, yes, not a real problem. POD5 can be searched recursively for basecalling (--recursively), so it is probably smarter to provide a directory for input data .. It is just a different type of parameter.
That is what I provided, right? /home/juaguila/Ju760-basecalling/RBK-xtra
I even used the directory with / and it didn't work before, it said missing parameter.


> Again, stick to BAM as long as you can. Inline demultiplexing organizes/stores the barcode information (with)in read groups in a single file, BAM or fastq. To get separate files for each of the barcode you need to run `dorado demux <..>` in a second step (which is cpu-bound), just as described in https://github.com/nanoporetech/dorado?tab=readme-ov-file#barcode-classification
Again it is described but not explicit and clear.

We got a Mk1C and it was a waste of money. It was supposed to be for sequencing and basecalling, to avoid having to buy a separate laptop/workstation, but it failed awfully for sequencing, and crashed within hours of sequencing.
