### ISSUE TITLE
version and verbose have the same short-hand flag

### ISSUE THREAD

**Issue by pwh124** [nanoporetech/dorado#99]
Hello all and thank you for working on this and keeping it open!

I just downloaded v0.2.1 and for the `download` and `basecaller` subcommands both the "verbose" and "version" flags have the same short hand flag (-v). See below

```
(base) phook2@whack:~/software/dorado_0.2.1$ bin/dorado download --help
Usage: dorado [-h] [--model VAR] [--directory VAR] [--list]

Optional arguments:
  -h, --help   	shows help message and exits 
  -v, --version	prints version information and exits 
  -v, --verbose	
  --model      	the model to download [default: "all"]
  --directory  	the directory to download the models into [default: "."]
  --list       	list the available models for download 
```

**Comment by iiSeymour** [comment]
Yes, this is confusing - we need to strip `-v, --version` from the subcommand arguments.

**Comment by iiSeymour** [comment]
Fixed in https://github.com/nanoporetech/dorado/commit/ac35a37ec4f832fade6387abb8d75d697a9c4450.
