### ISSUE TITLE
Reads count are different in stdout and output bam

### ISSUE THREAD

**Issue by Weihankk** [nanoporetech/dorado#992]
# Issue Report
Hi, I use dorado basecaller to conduct a basecalling in default parameters. I found in the final the screen print [2024-08-17 15:53:37.562] [info] > Simplex reads basecalled: 198394. However in the bam are 198527 reads. I am curious about what is going on with these extra reads and whether I need to remove these extra reads.

## Run environment:
- Dorado version: 0.7.3+6e6c45c
- Dorado command: dorado basecaller --no-trim dna_r9.4.1_e8_hac@v3.3 fast5/ > call.bam
- Operating system: centos
- Hardware (CPUs, Memory, GPUs): V100s
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): fast5

**Comment by malton-ont** [comment]
Hi @Weihankk,

This is expected. Some of the reads will have been basecalled and then split into multiple separate reads before output. You can verify this by checking for reads with a parent id tag `pi`:
```
samtools view -c -e "[pi]" call.bam
```
This value should be at least twice the difference between the stdout value and the number of reads in the bam file (more if some reads are split more than once).

**Comment by HalfPhoton** [comment]
Your input would have had 198,394 reads from your fast5 input data. Some of those reads would have been split (e.g. concatemers) giving 198,527 reads in your output. 
You should be able to check this by inspecting the parent id tag `[pi]`
```
samtools view -c -e "[pi]" call.bam
```

Best regards,
Rich

**Comment by Weihankk** [comment]
Thank you both for your help
