### ISSUE TITLE
basecalling Kit 12 in Dorado

### ISSUE THREAD

**Issue by hvanderheyden** [nanoporetech/dorado#993]
Is there a model version for basecalling Kit 12 (with R10.4 flowcell) data in Dorado ? 

Thanks

**Comment by HalfPhoton** [comment]
Hi @hvanderheyden, we don't distribute basecalling models for the Kit12 condition in Dorado.

**Comment by hvanderheyden** [comment]
Hello @HalfPhoton and thank you for your answer, 

Ok, so models are available for R9.4 + V9/V10 kits AND for R10 + V14  kits, but not for R10 + V12 kits, right? 

I need to stick with Guppy for this combination, or is it worth to try V14 models ? 

Many thanks

**Comment by HalfPhoton** [comment]
I can't _recommend_ using K14 models for K12 data as the training conditions are different.

However, if you find they do work well-enough for your use case / sample and **you can verify** that it's working then simply be aware that they're not designed for or trained on your data and there may be significant issues.
