### ISSUE TITLE
cmake: Problems to compile the software and then run it on another machine. 

### ISSUE THREAD

**Issue by ArnaudStigliani** [nanoporetech/dorado#999]
Dear developers,
I have dowloaded Dorado development version and made some changes to the code so that it fits perfectly our needs and our protocol. The code compiles and dorado run smoothly on a personal machine. However, we aim to deploy this dorado version on a GPU server.

Problem 1: I can't compile dorado on the server, the development tools and the libraries are too old and not updatable.
Problem 2: If I compile dorado on my personal computer, the binaries won't run on the server because of the dynamic linkings.

As a check, I downloaded the dorado tarball installer on the server
wget https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.7.3-linux-x64.tar.gz
and it runs great on the server, which shows that I should be able to compile a tuned version of dorado and export it there.

Thus, I wondered which parameter you use to compile dorado and run it on another machine (both machine use the same family of CPU, and are debian based systems).

So far, I have identified all the linked dynamic libraries with 
`$ ldd dorado  `
and put them in a personal lib folder that I can export on the target server with the dorado binaries. 

However, I am struggling hard to force cmake finding these dynamic libraries in the lib folder. 
Instead, cmake really wants to link the dorado binary to the equivalent dynamic libraries in locations like /usr/lib/.... .

Do you have an idea how to fix this ? 
Thank you for your help.

Best,
Arnaud

**Comment by malton-ont** [comment]
Hi @ArnaudStigliani,

You can generate the archive installer by using `cpack` - this should bundle all the necessary libraries. See [here](https://github.com/nanoporetech/dorado/blob/release-v0.7/.gitlab-ci.yml#L115C5-L115C50) for an example.

**Comment by ArnaudStigliani** [comment]
Wow, thank you so much, I was close to giving up !
It works great !

Arnaud
